import itk.itkInPlaceImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkAbsImageFilterIF2IF2_New(): ...

class itkAbsImageFilterIF2IF2(itk.itkUnaryGeneratorImageFilterPython.itkUnaryGeneratorImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ConvertibleCheck: Any = ...
    InputGreaterThanIntCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAbsImageFilterIF2IF2___New_orig__: Any
itkAbsImageFilterIF2IF2_cast: Any

def itkAbsImageFilterIF3IF3_New(): ...

class itkAbsImageFilterIF3IF3(itk.itkUnaryGeneratorImageFilterPython.itkUnaryGeneratorImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ConvertibleCheck: Any = ...
    InputGreaterThanIntCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAbsImageFilterIF3IF3___New_orig__: Any
itkAbsImageFilterIF3IF3_cast: Any

def itkAbsImageFilterISS2ISS2_New(): ...

class itkAbsImageFilterISS2ISS2(itk.itkUnaryGeneratorImageFilterPython.itkUnaryGeneratorImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ConvertibleCheck: Any = ...
    InputGreaterThanIntCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAbsImageFilterISS2ISS2___New_orig__: Any
itkAbsImageFilterISS2ISS2_cast: Any

def itkAbsImageFilterISS3ISS3_New(): ...

class itkAbsImageFilterISS3ISS3(itk.itkUnaryGeneratorImageFilterPython.itkUnaryGeneratorImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ConvertibleCheck: Any = ...
    InputGreaterThanIntCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAbsImageFilterISS3ISS3___New_orig__: Any
itkAbsImageFilterISS3ISS3_cast: Any

def itkAbsImageFilterIUC2IUC2_New(): ...

class itkAbsImageFilterIUC2IUC2(itk.itkUnaryGeneratorImageFilterPython.itkUnaryGeneratorImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ConvertibleCheck: Any = ...
    InputGreaterThanIntCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAbsImageFilterIUC2IUC2___New_orig__: Any
itkAbsImageFilterIUC2IUC2_cast: Any

def itkAbsImageFilterIUC3IUC3_New(): ...

class itkAbsImageFilterIUC3IUC3(itk.itkUnaryGeneratorImageFilterPython.itkUnaryGeneratorImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ConvertibleCheck: Any = ...
    InputGreaterThanIntCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAbsImageFilterIUC3IUC3___New_orig__: Any
itkAbsImageFilterIUC3IUC3_cast: Any

def abs_image_filter(*args: Any, **kwargs: Any): ...
def abs_image_filter_init_docstring() -> None: ...
