import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkAggregateLabelMapFilterLM2_New(): ...

class itkAggregateLabelMapFilterLM2(itk.itkInPlaceLabelMapFilterPython.itkInPlaceLabelMapFilterLM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAggregateLabelMapFilterLM2___New_orig__: Any
itkAggregateLabelMapFilterLM2_cast: Any

def itkAggregateLabelMapFilterLM3_New(): ...

class itkAggregateLabelMapFilterLM3(itk.itkInPlaceLabelMapFilterPython.itkInPlaceLabelMapFilterLM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAggregateLabelMapFilterLM3___New_orig__: Any
itkAggregateLabelMapFilterLM3_cast: Any

def aggregate_label_map_filter(*args: Any, **kwargs: Any): ...
def aggregate_label_map_filter_init_docstring() -> None: ...
