import itk.itkInPlaceImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkAddImageFilterIF2IF2IF2_New(): ...

class itkAddImageFilterIF2IF2IF2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIF2IF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1Input2OutputAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAddImageFilterIF2IF2IF2___New_orig__: Any
itkAddImageFilterIF2IF2IF2_cast: Any

def itkAddImageFilterIF3IF3IF3_New(): ...

class itkAddImageFilterIF3IF3IF3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIF3IF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1Input2OutputAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAddImageFilterIF3IF3IF3___New_orig__: Any
itkAddImageFilterIF3IF3IF3_cast: Any

def itkAddImageFilterISS2ISS2ISS2_New(): ...

class itkAddImageFilterISS2ISS2ISS2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterISS2ISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1Input2OutputAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAddImageFilterISS2ISS2ISS2___New_orig__: Any
itkAddImageFilterISS2ISS2ISS2_cast: Any

def itkAddImageFilterISS3ISS3ISS3_New(): ...

class itkAddImageFilterISS3ISS3ISS3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterISS3ISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1Input2OutputAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAddImageFilterISS3ISS3ISS3___New_orig__: Any
itkAddImageFilterISS3ISS3ISS3_cast: Any

def itkAddImageFilterIUC2IUC2IUC2_New(): ...

class itkAddImageFilterIUC2IUC2IUC2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC2IUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1Input2OutputAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAddImageFilterIUC2IUC2IUC2___New_orig__: Any
itkAddImageFilterIUC2IUC2IUC2_cast: Any

def itkAddImageFilterIUC3IUC3IUC3_New(): ...

class itkAddImageFilterIUC3IUC3IUC3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC3IUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1Input2OutputAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAddImageFilterIUC3IUC3IUC3___New_orig__: Any
itkAddImageFilterIUC3IUC3IUC3_cast: Any

def add_image_filter(*args: Any, **kwargs: Any): ...
def add_image_filter_init_docstring() -> None: ...
