import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkApproximateSignedDistanceMapImageFilterIF2IF2_New(): ...

class itkApproximateSignedDistanceMapImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    InputEqualityComparableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkApproximateSignedDistanceMapImageFilterIF2IF2___New_orig__: Any
itkApproximateSignedDistanceMapImageFilterIF2IF2_cast: Any

def itkApproximateSignedDistanceMapImageFilterIF3IF3_New(): ...

class itkApproximateSignedDistanceMapImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    InputEqualityComparableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkApproximateSignedDistanceMapImageFilterIF3IF3___New_orig__: Any
itkApproximateSignedDistanceMapImageFilterIF3IF3_cast: Any

def itkApproximateSignedDistanceMapImageFilterISS2ISS2_New(): ...

class itkApproximateSignedDistanceMapImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    InputEqualityComparableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkApproximateSignedDistanceMapImageFilterISS2ISS2___New_orig__: Any
itkApproximateSignedDistanceMapImageFilterISS2ISS2_cast: Any

def itkApproximateSignedDistanceMapImageFilterISS3ISS3_New(): ...

class itkApproximateSignedDistanceMapImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    InputEqualityComparableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkApproximateSignedDistanceMapImageFilterISS3ISS3___New_orig__: Any
itkApproximateSignedDistanceMapImageFilterISS3ISS3_cast: Any

def approximate_signed_distance_map_image_filter(*args: Any, **kwargs: Any): ...
def approximate_signed_distance_map_image_filter_init_docstring() -> None: ...
