import itk.itkInPlaceImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkAbsoluteValueDifferenceImageFilterIF2IF2IF2_New(): ...

class itkAbsoluteValueDifferenceImageFilterIF2IF2IF2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIF2IF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1CovertibleToDoubleCheck: Any = ...
    Input2ConvertibleToDoubleCheck: Any = ...
    DoubleCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAbsoluteValueDifferenceImageFilterIF2IF2IF2___New_orig__: Any
itkAbsoluteValueDifferenceImageFilterIF2IF2IF2_cast: Any

def itkAbsoluteValueDifferenceImageFilterIF3IF3IF3_New(): ...

class itkAbsoluteValueDifferenceImageFilterIF3IF3IF3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIF3IF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1CovertibleToDoubleCheck: Any = ...
    Input2ConvertibleToDoubleCheck: Any = ...
    DoubleCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAbsoluteValueDifferenceImageFilterIF3IF3IF3___New_orig__: Any
itkAbsoluteValueDifferenceImageFilterIF3IF3IF3_cast: Any

def itkAbsoluteValueDifferenceImageFilterISS2ISS2ISS2_New(): ...

class itkAbsoluteValueDifferenceImageFilterISS2ISS2ISS2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterISS2ISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1CovertibleToDoubleCheck: Any = ...
    Input2ConvertibleToDoubleCheck: Any = ...
    DoubleCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAbsoluteValueDifferenceImageFilterISS2ISS2ISS2___New_orig__: Any
itkAbsoluteValueDifferenceImageFilterISS2ISS2ISS2_cast: Any

def itkAbsoluteValueDifferenceImageFilterISS3ISS3ISS3_New(): ...

class itkAbsoluteValueDifferenceImageFilterISS3ISS3ISS3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterISS3ISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1CovertibleToDoubleCheck: Any = ...
    Input2ConvertibleToDoubleCheck: Any = ...
    DoubleCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAbsoluteValueDifferenceImageFilterISS3ISS3ISS3___New_orig__: Any
itkAbsoluteValueDifferenceImageFilterISS3ISS3ISS3_cast: Any

def itkAbsoluteValueDifferenceImageFilterIUC2IUC2IUC2_New(): ...

class itkAbsoluteValueDifferenceImageFilterIUC2IUC2IUC2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC2IUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1CovertibleToDoubleCheck: Any = ...
    Input2ConvertibleToDoubleCheck: Any = ...
    DoubleCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAbsoluteValueDifferenceImageFilterIUC2IUC2IUC2___New_orig__: Any
itkAbsoluteValueDifferenceImageFilterIUC2IUC2IUC2_cast: Any

def itkAbsoluteValueDifferenceImageFilterIUC3IUC3IUC3_New(): ...

class itkAbsoluteValueDifferenceImageFilterIUC3IUC3IUC3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC3IUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1CovertibleToDoubleCheck: Any = ...
    Input2ConvertibleToDoubleCheck: Any = ...
    DoubleCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAbsoluteValueDifferenceImageFilterIUC3IUC3IUC3___New_orig__: Any
itkAbsoluteValueDifferenceImageFilterIUC3IUC3IUC3_cast: Any

def absolute_value_difference_image_filter(*args: Any, **kwargs: Any): ...
def absolute_value_difference_image_filter_init_docstring() -> None: ...
