import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkAccumulateImageFilterIF2IF2_New(): ...

class itkAccumulateImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    GetAccumulateDimension: Any = ...
    SetAccumulateDimension: Any = ...
    SetAverage: Any = ...
    GetAverage: Any = ...
    AverageOn: Any = ...
    AverageOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAccumulateImageFilterIF2IF2___New_orig__: Any
itkAccumulateImageFilterIF2IF2_cast: Any

def itkAccumulateImageFilterIF3IF3_New(): ...

class itkAccumulateImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    GetAccumulateDimension: Any = ...
    SetAccumulateDimension: Any = ...
    SetAverage: Any = ...
    GetAverage: Any = ...
    AverageOn: Any = ...
    AverageOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAccumulateImageFilterIF3IF3___New_orig__: Any
itkAccumulateImageFilterIF3IF3_cast: Any

def itkAccumulateImageFilterISS2ISS2_New(): ...

class itkAccumulateImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    GetAccumulateDimension: Any = ...
    SetAccumulateDimension: Any = ...
    SetAverage: Any = ...
    GetAverage: Any = ...
    AverageOn: Any = ...
    AverageOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAccumulateImageFilterISS2ISS2___New_orig__: Any
itkAccumulateImageFilterISS2ISS2_cast: Any

def itkAccumulateImageFilterISS3ISS3_New(): ...

class itkAccumulateImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    GetAccumulateDimension: Any = ...
    SetAccumulateDimension: Any = ...
    SetAverage: Any = ...
    GetAverage: Any = ...
    AverageOn: Any = ...
    AverageOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAccumulateImageFilterISS3ISS3___New_orig__: Any
itkAccumulateImageFilterISS3ISS3_cast: Any

def itkAccumulateImageFilterIUC2IUC2_New(): ...

class itkAccumulateImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    GetAccumulateDimension: Any = ...
    SetAccumulateDimension: Any = ...
    SetAverage: Any = ...
    GetAverage: Any = ...
    AverageOn: Any = ...
    AverageOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAccumulateImageFilterIUC2IUC2___New_orig__: Any
itkAccumulateImageFilterIUC2IUC2_cast: Any

def itkAccumulateImageFilterIUC3IUC3_New(): ...

class itkAccumulateImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    GetAccumulateDimension: Any = ...
    SetAccumulateDimension: Any = ...
    SetAverage: Any = ...
    GetAverage: Any = ...
    AverageOn: Any = ...
    AverageOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAccumulateImageFilterIUC3IUC3___New_orig__: Any
itkAccumulateImageFilterIUC3IUC3_cast: Any

def accumulate_image_filter(*args: Any, **kwargs: Any): ...
def accumulate_image_filter_init_docstring() -> None: ...
