import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkAntiAliasBinaryImageFilterIF2IF2_New(): ...

class itkAntiAliasBinaryImageFilterIF2IF2(itk.itkSparseFieldLevelSetImageFilterPython.itkSparseFieldLevelSetImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetUpperBinaryValue: Any = ...
    GetLowerBinaryValue: Any = ...
    SetMaximumIterations: Any = ...
    GetMaximumIterations: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAntiAliasBinaryImageFilterIF2IF2___New_orig__: Any
itkAntiAliasBinaryImageFilterIF2IF2_cast: Any

def itkAntiAliasBinaryImageFilterIF3IF3_New(): ...

class itkAntiAliasBinaryImageFilterIF3IF3(itk.itkSparseFieldLevelSetImageFilterPython.itkSparseFieldLevelSetImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetUpperBinaryValue: Any = ...
    GetLowerBinaryValue: Any = ...
    SetMaximumIterations: Any = ...
    GetMaximumIterations: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAntiAliasBinaryImageFilterIF3IF3___New_orig__: Any
itkAntiAliasBinaryImageFilterIF3IF3_cast: Any

def anti_alias_binary_image_filter(*args: Any, **kwargs: Any): ...
def anti_alias_binary_image_filter_init_docstring() -> None: ...
