import itk.itkLevelSetFunctionPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkAnisotropicFourthOrderLevelSetImageFilterIF2IF2_New(): ...

class itkAnisotropicFourthOrderLevelSetImageFilterIF2IF2(itk.itkSparseFieldFourthOrderLevelSetImageFilterPython.itkSparseFieldFourthOrderLevelSetImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaxFilterIteration: Any = ...
    SetMaxFilterIteration: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAnisotropicFourthOrderLevelSetImageFilterIF2IF2___New_orig__: Any
itkAnisotropicFourthOrderLevelSetImageFilterIF2IF2_cast: Any

def itkAnisotropicFourthOrderLevelSetImageFilterIF3IF3_New(): ...

class itkAnisotropicFourthOrderLevelSetImageFilterIF3IF3(itk.itkSparseFieldFourthOrderLevelSetImageFilterPython.itkSparseFieldFourthOrderLevelSetImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaxFilterIteration: Any = ...
    SetMaxFilterIteration: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAnisotropicFourthOrderLevelSetImageFilterIF3IF3___New_orig__: Any
itkAnisotropicFourthOrderLevelSetImageFilterIF3IF3_cast: Any

def anisotropic_fourth_order_level_set_image_filter(*args: Any, **kwargs: Any): ...
def anisotropic_fourth_order_level_set_image_filter_init_docstring() -> None: ...
