import itk.pyBasePython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkArray2DD(itk.vnl_matrixPython.vnl_matrixD):
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    Fill: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    SetSize: Any = ...
    __swig_destroy__: Any = ...

class itkArray2DF(itk.vnl_matrixPython.vnl_matrixF):
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    Fill: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    SetSize: Any = ...
    __swig_destroy__: Any = ...

class itkArray2DUI(itk.vnl_matrixPython.vnl_matrixUI):
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    Fill: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    SetSize: Any = ...
    __swig_destroy__: Any = ...
