import itk.itkInPlaceImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkAtan2ImageFilterIF2IF2IF2_New(): ...

class itkAtan2ImageFilterIF2IF2IF2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIF2IF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1ConvertibleToDoubleCheck: Any = ...
    Input2ConvertibleToDoubleCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAtan2ImageFilterIF2IF2IF2___New_orig__: Any
itkAtan2ImageFilterIF2IF2IF2_cast: Any

def itkAtan2ImageFilterIF3IF3IF3_New(): ...

class itkAtan2ImageFilterIF3IF3IF3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIF3IF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1ConvertibleToDoubleCheck: Any = ...
    Input2ConvertibleToDoubleCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAtan2ImageFilterIF3IF3IF3___New_orig__: Any
itkAtan2ImageFilterIF3IF3IF3_cast: Any

def atan2_image_filter(*args: Any, **kwargs: Any): ...
def atan2_image_filter_init_docstring() -> None: ...
