import itk.itkImageRegionPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBSplineExponentialDiffeomorphicTransformD2_New(): ...

class itkBSplineExponentialDiffeomorphicTransformD2(itk.itkConstantVelocityFieldTransformPython.itkConstantVelocityFieldTransformD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    UpdateTransformParameters: Any = ...
    BSplineSmoothConstantVelocityField: Any = ...
    SetSplineOrder: Any = ...
    GetSplineOrder: Any = ...
    SetNumberOfControlPointsForTheConstantVelocityField: Any = ...
    GetNumberOfControlPointsForTheConstantVelocityField: Any = ...
    SetNumberOfControlPointsForTheUpdateField: Any = ...
    GetNumberOfControlPointsForTheUpdateField: Any = ...
    SetMeshSizeForTheConstantVelocityField: Any = ...
    SetMeshSizeForTheUpdateField: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineExponentialDiffeomorphicTransformD2___New_orig__: Any
itkBSplineExponentialDiffeomorphicTransformD2_cast: Any

def itkBSplineExponentialDiffeomorphicTransformD3_New(): ...

class itkBSplineExponentialDiffeomorphicTransformD3(itk.itkConstantVelocityFieldTransformPython.itkConstantVelocityFieldTransformD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    UpdateTransformParameters: Any = ...
    BSplineSmoothConstantVelocityField: Any = ...
    SetSplineOrder: Any = ...
    GetSplineOrder: Any = ...
    SetNumberOfControlPointsForTheConstantVelocityField: Any = ...
    GetNumberOfControlPointsForTheConstantVelocityField: Any = ...
    SetNumberOfControlPointsForTheUpdateField: Any = ...
    GetNumberOfControlPointsForTheUpdateField: Any = ...
    SetMeshSizeForTheConstantVelocityField: Any = ...
    SetMeshSizeForTheUpdateField: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineExponentialDiffeomorphicTransformD3___New_orig__: Any
itkBSplineExponentialDiffeomorphicTransformD3_cast: Any
