import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBinaryNotImageFilterISS2_Superclass_New(): ...

class itkBinaryNotImageFilterISS2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryNotImageFilterISS2_Superclass___New_orig__: Any
itkBinaryNotImageFilterISS2_Superclass_cast: Any

def itkBinaryNotImageFilterISS3_Superclass_New(): ...

class itkBinaryNotImageFilterISS3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryNotImageFilterISS3_Superclass___New_orig__: Any
itkBinaryNotImageFilterISS3_Superclass_cast: Any

def itkBinaryNotImageFilterIUC2_Superclass_New(): ...

class itkBinaryNotImageFilterIUC2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryNotImageFilterIUC2_Superclass___New_orig__: Any
itkBinaryNotImageFilterIUC2_Superclass_cast: Any

def itkBinaryNotImageFilterIUC3_Superclass_New(): ...

class itkBinaryNotImageFilterIUC3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryNotImageFilterIUC3_Superclass___New_orig__: Any
itkBinaryNotImageFilterIUC3_Superclass_cast: Any

def itkBinaryNotImageFilterISS2_New(): ...

class itkBinaryNotImageFilterISS2(itkBinaryNotImageFilterISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryNotImageFilterISS2___New_orig__: Any
itkBinaryNotImageFilterISS2_cast: Any

def itkBinaryNotImageFilterISS3_New(): ...

class itkBinaryNotImageFilterISS3(itkBinaryNotImageFilterISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryNotImageFilterISS3___New_orig__: Any
itkBinaryNotImageFilterISS3_cast: Any

def itkBinaryNotImageFilterIUC2_New(): ...

class itkBinaryNotImageFilterIUC2(itkBinaryNotImageFilterIUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryNotImageFilterIUC2___New_orig__: Any
itkBinaryNotImageFilterIUC2_cast: Any

def itkBinaryNotImageFilterIUC3_New(): ...

class itkBinaryNotImageFilterIUC3(itkBinaryNotImageFilterIUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryNotImageFilterIUC3___New_orig__: Any
itkBinaryNotImageFilterIUC3_cast: Any

def binary_not_image_filter(*args: Any, **kwargs: Any): ...
def binary_not_image_filter_init_docstring() -> None: ...
def unary_functor_image_filter(*args: Any, **kwargs: Any): ...
def unary_functor_image_filter_init_docstring() -> None: ...
