import itk.itkMathematicalMorphologyEnumsPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBlackTopHatImageFilterIF2IF2SE2_New(): ...

class itkBlackTopHatImageFilterIF2IF2SE2(itk.itkFlatStructuringElementPython.itkKernelImageFilterIF2IF2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetForceAlgorithm: Any = ...
    GetForceAlgorithm: Any = ...
    ForceAlgorithmOn: Any = ...
    ForceAlgorithmOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBlackTopHatImageFilterIF2IF2SE2___New_orig__: Any
itkBlackTopHatImageFilterIF2IF2SE2_cast: Any

def itkBlackTopHatImageFilterIF3IF3SE3_New(): ...

class itkBlackTopHatImageFilterIF3IF3SE3(itk.itkFlatStructuringElementPython.itkKernelImageFilterIF3IF3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetForceAlgorithm: Any = ...
    GetForceAlgorithm: Any = ...
    ForceAlgorithmOn: Any = ...
    ForceAlgorithmOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBlackTopHatImageFilterIF3IF3SE3___New_orig__: Any
itkBlackTopHatImageFilterIF3IF3SE3_cast: Any

def itkBlackTopHatImageFilterISS2ISS2SE2_New(): ...

class itkBlackTopHatImageFilterISS2ISS2SE2(itk.itkFlatStructuringElementPython.itkKernelImageFilterISS2ISS2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetForceAlgorithm: Any = ...
    GetForceAlgorithm: Any = ...
    ForceAlgorithmOn: Any = ...
    ForceAlgorithmOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBlackTopHatImageFilterISS2ISS2SE2___New_orig__: Any
itkBlackTopHatImageFilterISS2ISS2SE2_cast: Any

def itkBlackTopHatImageFilterISS3ISS3SE3_New(): ...

class itkBlackTopHatImageFilterISS3ISS3SE3(itk.itkFlatStructuringElementPython.itkKernelImageFilterISS3ISS3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetForceAlgorithm: Any = ...
    GetForceAlgorithm: Any = ...
    ForceAlgorithmOn: Any = ...
    ForceAlgorithmOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBlackTopHatImageFilterISS3ISS3SE3___New_orig__: Any
itkBlackTopHatImageFilterISS3ISS3SE3_cast: Any

def itkBlackTopHatImageFilterIUC2IUC2SE2_New(): ...

class itkBlackTopHatImageFilterIUC2IUC2SE2(itk.itkFlatStructuringElementPython.itkKernelImageFilterIUC2IUC2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetForceAlgorithm: Any = ...
    GetForceAlgorithm: Any = ...
    ForceAlgorithmOn: Any = ...
    ForceAlgorithmOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBlackTopHatImageFilterIUC2IUC2SE2___New_orig__: Any
itkBlackTopHatImageFilterIUC2IUC2SE2_cast: Any

def itkBlackTopHatImageFilterIUC3IUC3SE3_New(): ...

class itkBlackTopHatImageFilterIUC3IUC3SE3(itk.itkFlatStructuringElementPython.itkKernelImageFilterIUC3IUC3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetForceAlgorithm: Any = ...
    GetForceAlgorithm: Any = ...
    ForceAlgorithmOn: Any = ...
    ForceAlgorithmOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBlackTopHatImageFilterIUC3IUC3SE3___New_orig__: Any
itkBlackTopHatImageFilterIUC3IUC3SE3_cast: Any

def black_top_hat_image_filter(*args: Any, **kwargs: Any): ...
def black_top_hat_image_filter_init_docstring() -> None: ...
