import itk.itkMeshIOBasePython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBYUMeshIO_New(): ...

class itkBYUMeshIO(itk.itkMeshIOBasePython.itkMeshIOBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBYUMeshIO___New_orig__: Any
itkBYUMeshIO_cast: Any

def itkBYUMeshIOFactory_New(): ...

class itkBYUMeshIOFactory(itk.ITKCommonBasePython.itkObjectFactoryBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    RegisterOneFactory: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBYUMeshIOFactory___New_orig__: Any
itkBYUMeshIOFactory_RegisterOneFactory: Any
itkBYUMeshIOFactory_cast: Any
