import itk.itkRGBPixelPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkBSplineBaseTransformD23(itk.itkTransformBasePython.itkTransformD22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Clone: Any = ...
    SetIdentity: Any = ...
    SetCoefficientImages: Any = ...
    GetCoefficientImages: Any = ...
    UpdateTransformParameters: Any = ...
    TransformPoint: Any = ...
    GetNumberOfWeights: Any = ...
    TransformVector: Any = ...
    ComputeJacobianFromBSplineWeightsWithRespectToPosition: Any = ...
    GetNumberOfParametersPerDimension: Any = ...
    GetNumberOfAffectedWeights: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkBSplineBaseTransformD23_cast: Any

class itkBSplineBaseTransformD33(itk.itkTransformBasePython.itkTransformD33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Clone: Any = ...
    SetIdentity: Any = ...
    SetCoefficientImages: Any = ...
    GetCoefficientImages: Any = ...
    UpdateTransformParameters: Any = ...
    TransformPoint: Any = ...
    GetNumberOfWeights: Any = ...
    TransformVector: Any = ...
    ComputeJacobianFromBSplineWeightsWithRespectToPosition: Any = ...
    GetNumberOfParametersPerDimension: Any = ...
    GetNumberOfAffectedWeights: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkBSplineBaseTransformD33_cast: Any
