import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBSplineDecompositionImageFilterIF2IF2_New(): ...

class itkBSplineDecompositionImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSplineOrder: Any = ...
    GetSplineOrder: Any = ...
    GetSplinePoles: Any = ...
    GetNumberOfPoles: Any = ...
    DimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineDecompositionImageFilterIF2IF2___New_orig__: Any
itkBSplineDecompositionImageFilterIF2IF2_cast: Any

def itkBSplineDecompositionImageFilterIF3IF3_New(): ...

class itkBSplineDecompositionImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSplineOrder: Any = ...
    GetSplineOrder: Any = ...
    GetSplinePoles: Any = ...
    GetNumberOfPoles: Any = ...
    DimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineDecompositionImageFilterIF3IF3___New_orig__: Any
itkBSplineDecompositionImageFilterIF3IF3_cast: Any

def itkBSplineDecompositionImageFilterISS2ISS2_New(): ...

class itkBSplineDecompositionImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSplineOrder: Any = ...
    GetSplineOrder: Any = ...
    GetSplinePoles: Any = ...
    GetNumberOfPoles: Any = ...
    DimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineDecompositionImageFilterISS2ISS2___New_orig__: Any
itkBSplineDecompositionImageFilterISS2ISS2_cast: Any

def itkBSplineDecompositionImageFilterISS3ISS3_New(): ...

class itkBSplineDecompositionImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSplineOrder: Any = ...
    GetSplineOrder: Any = ...
    GetSplinePoles: Any = ...
    GetNumberOfPoles: Any = ...
    DimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineDecompositionImageFilterISS3ISS3___New_orig__: Any
itkBSplineDecompositionImageFilterISS3ISS3_cast: Any

def itkBSplineDecompositionImageFilterIUC2IUC2_New(): ...

class itkBSplineDecompositionImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSplineOrder: Any = ...
    GetSplineOrder: Any = ...
    GetSplinePoles: Any = ...
    GetNumberOfPoles: Any = ...
    DimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineDecompositionImageFilterIUC2IUC2___New_orig__: Any
itkBSplineDecompositionImageFilterIUC2IUC2_cast: Any

def itkBSplineDecompositionImageFilterIUC3IUC3_New(): ...

class itkBSplineDecompositionImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSplineOrder: Any = ...
    GetSplineOrder: Any = ...
    GetSplinePoles: Any = ...
    GetNumberOfPoles: Any = ...
    DimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineDecompositionImageFilterIUC3IUC3___New_orig__: Any
itkBSplineDecompositionImageFilterIUC3IUC3_cast: Any

def b_spline_decomposition_image_filter(*args: Any, **kwargs: Any): ...
def b_spline_decomposition_image_filter_init_docstring() -> None: ...
