import itk.itkOffsetPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkBackwardDifferenceOperatorF2(itk.itkNeighborhoodOperatorPython.itkNeighborhoodOperatorF2):
    thisown: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...

class itkBackwardDifferenceOperatorF3(itk.itkNeighborhoodOperatorPython.itkNeighborhoodOperatorF3):
    thisown: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
