import itk.itkArrayPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBSplineResampleImageFunctionIF2D_New(): ...

class itkBSplineResampleImageFunctionIF2D(itk.itkBSplineInterpolateImageFunctionPython.itkBSplineInterpolateImageFunctionIF2DF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineResampleImageFunctionIF2D___New_orig__: Any
itkBSplineResampleImageFunctionIF2D_cast: Any

def itkBSplineResampleImageFunctionIF3D_New(): ...

class itkBSplineResampleImageFunctionIF3D(itk.itkBSplineInterpolateImageFunctionPython.itkBSplineInterpolateImageFunctionIF3DF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineResampleImageFunctionIF3D___New_orig__: Any
itkBSplineResampleImageFunctionIF3D_cast: Any

def itkBSplineResampleImageFunctionISS2D_New(): ...

class itkBSplineResampleImageFunctionISS2D(itk.itkBSplineInterpolateImageFunctionPython.itkBSplineInterpolateImageFunctionISS2DSS):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineResampleImageFunctionISS2D___New_orig__: Any
itkBSplineResampleImageFunctionISS2D_cast: Any

def itkBSplineResampleImageFunctionISS3D_New(): ...

class itkBSplineResampleImageFunctionISS3D(itk.itkBSplineInterpolateImageFunctionPython.itkBSplineInterpolateImageFunctionISS3DSS):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineResampleImageFunctionISS3D___New_orig__: Any
itkBSplineResampleImageFunctionISS3D_cast: Any

def itkBSplineResampleImageFunctionIUC2D_New(): ...

class itkBSplineResampleImageFunctionIUC2D(itk.itkBSplineInterpolateImageFunctionPython.itkBSplineInterpolateImageFunctionIUC2DUC):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineResampleImageFunctionIUC2D___New_orig__: Any
itkBSplineResampleImageFunctionIUC2D_cast: Any

def itkBSplineResampleImageFunctionIUC3D_New(): ...

class itkBSplineResampleImageFunctionIUC3D(itk.itkBSplineInterpolateImageFunctionPython.itkBSplineInterpolateImageFunctionIUC3DUC):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineResampleImageFunctionIUC3D___New_orig__: Any
itkBSplineResampleImageFunctionIUC3D_cast: Any
