import itk.itkNeighborhoodPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBinaryClosingByReconstructionImageFilterIUC2SE2_New(): ...

class itkBinaryClosingByReconstructionImageFilterIUC2SE2(itk.itkFlatStructuringElementPython.itkKernelImageFilterIUC2IUC2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryClosingByReconstructionImageFilterIUC2SE2___New_orig__: Any
itkBinaryClosingByReconstructionImageFilterIUC2SE2_cast: Any

def itkBinaryClosingByReconstructionImageFilterIUC3SE3_New(): ...

class itkBinaryClosingByReconstructionImageFilterIUC3SE3(itk.itkFlatStructuringElementPython.itkKernelImageFilterIUC3IUC3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryClosingByReconstructionImageFilterIUC3SE3___New_orig__: Any
itkBinaryClosingByReconstructionImageFilterIUC3SE3_cast: Any

def binary_closing_by_reconstruction_image_filter(*args: Any, **kwargs: Any): ...
def binary_closing_by_reconstruction_image_filter_init_docstring() -> None: ...
