import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBinaryStatisticsOpeningImageFilterIUC2IF2_New(): ...

class itkBinaryStatisticsOpeningImageFilterIUC2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    GetLambda: Any = ...
    SetLambda: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryStatisticsOpeningImageFilterIUC2IF2___New_orig__: Any
itkBinaryStatisticsOpeningImageFilterIUC2IF2_cast: Any

def itkBinaryStatisticsOpeningImageFilterIUC2ISS2_New(): ...

class itkBinaryStatisticsOpeningImageFilterIUC2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    GetLambda: Any = ...
    SetLambda: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryStatisticsOpeningImageFilterIUC2ISS2___New_orig__: Any
itkBinaryStatisticsOpeningImageFilterIUC2ISS2_cast: Any

def itkBinaryStatisticsOpeningImageFilterIUC2IUC2_New(): ...

class itkBinaryStatisticsOpeningImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    GetLambda: Any = ...
    SetLambda: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryStatisticsOpeningImageFilterIUC2IUC2___New_orig__: Any
itkBinaryStatisticsOpeningImageFilterIUC2IUC2_cast: Any

def itkBinaryStatisticsOpeningImageFilterIUC3IF3_New(): ...

class itkBinaryStatisticsOpeningImageFilterIUC3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    GetLambda: Any = ...
    SetLambda: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryStatisticsOpeningImageFilterIUC3IF3___New_orig__: Any
itkBinaryStatisticsOpeningImageFilterIUC3IF3_cast: Any

def itkBinaryStatisticsOpeningImageFilterIUC3ISS3_New(): ...

class itkBinaryStatisticsOpeningImageFilterIUC3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    GetLambda: Any = ...
    SetLambda: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryStatisticsOpeningImageFilterIUC3ISS3___New_orig__: Any
itkBinaryStatisticsOpeningImageFilterIUC3ISS3_cast: Any

def itkBinaryStatisticsOpeningImageFilterIUC3IUC3_New(): ...

class itkBinaryStatisticsOpeningImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    GetLambda: Any = ...
    SetLambda: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryStatisticsOpeningImageFilterIUC3IUC3___New_orig__: Any
itkBinaryStatisticsOpeningImageFilterIUC3IUC3_cast: Any

def binary_statistics_opening_image_filter(*args: Any, **kwargs: Any): ...
def binary_statistics_opening_image_filter_init_docstring() -> None: ...
