import itk.itkVariableLengthVectorPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBSplineTransformD23_New(): ...

class itkBSplineTransformD23(itk.itkBSplineBaseTransformPython.itkBSplineBaseTransformD23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetTransformDomainOrigin: Any = ...
    GetTransformDomainOrigin: Any = ...
    SetTransformDomainPhysicalDimensions: Any = ...
    GetTransformDomainPhysicalDimensions: Any = ...
    SetTransformDomainDirection: Any = ...
    GetTransformDomainDirection: Any = ...
    SetTransformDomainMeshSize: Any = ...
    GetTransformDomainMeshSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineTransformD23___New_orig__: Any
itkBSplineTransformD23_cast: Any

def itkBSplineTransformD33_New(): ...

class itkBSplineTransformD33(itk.itkBSplineBaseTransformPython.itkBSplineBaseTransformD33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetTransformDomainOrigin: Any = ...
    GetTransformDomainOrigin: Any = ...
    SetTransformDomainPhysicalDimensions: Any = ...
    GetTransformDomainPhysicalDimensions: Any = ...
    SetTransformDomainDirection: Any = ...
    GetTransformDomainDirection: Any = ...
    SetTransformDomainMeshSize: Any = ...
    GetTransformDomainMeshSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineTransformD33___New_orig__: Any
itkBSplineTransformD33_cast: Any
