import itk.stdcomplexPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBruker2dseqImageIO_New(): ...

class itkBruker2dseqImageIO(itk.ITKIOImageBaseBasePython.itkImageIOBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBruker2dseqImageIO___New_orig__: Any
itkBruker2dseqImageIO_cast: Any

def itkBruker2dseqImageIOFactory_New(): ...

class itkBruker2dseqImageIOFactory(itk.ITKCommonBasePython.itkObjectFactoryBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    RegisterOneFactory: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBruker2dseqImageIOFactory___New_orig__: Any
itkBruker2dseqImageIOFactory_RegisterOneFactory: Any
itkBruker2dseqImageIOFactory_cast: Any
