import itk.itkMeshSourcePython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBinaryMask3DMeshSourceISS3MD3_New(): ...

class itkBinaryMask3DMeshSourceISS3MD3(itk.itkImageToMeshFilterPython.itkImageToMeshFilterISS3MD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetObjectValue: Any = ...
    GetNumberOfNodes: Any = ...
    GetNumberOfCells: Any = ...
    SetInput: Any = ...
    SetRegionOfInterest: Any = ...
    GetRegionOfInterest: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryMask3DMeshSourceISS3MD3___New_orig__: Any
itkBinaryMask3DMeshSourceISS3MD3_cast: Any

def itkBinaryMask3DMeshSourceISS3MF3_New(): ...

class itkBinaryMask3DMeshSourceISS3MF3(itk.itkImageToMeshFilterPython.itkImageToMeshFilterISS3MF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetObjectValue: Any = ...
    GetNumberOfNodes: Any = ...
    GetNumberOfCells: Any = ...
    SetInput: Any = ...
    SetRegionOfInterest: Any = ...
    GetRegionOfInterest: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryMask3DMeshSourceISS3MF3___New_orig__: Any
itkBinaryMask3DMeshSourceISS3MF3_cast: Any

def itkBinaryMask3DMeshSourceISS3MSS3_New(): ...

class itkBinaryMask3DMeshSourceISS3MSS3(itk.itkImageToMeshFilterPython.itkImageToMeshFilterISS3MSS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetObjectValue: Any = ...
    GetNumberOfNodes: Any = ...
    GetNumberOfCells: Any = ...
    SetInput: Any = ...
    SetRegionOfInterest: Any = ...
    GetRegionOfInterest: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryMask3DMeshSourceISS3MSS3___New_orig__: Any
itkBinaryMask3DMeshSourceISS3MSS3_cast: Any

def itkBinaryMask3DMeshSourceISS3MUC3_New(): ...

class itkBinaryMask3DMeshSourceISS3MUC3(itk.itkImageToMeshFilterPython.itkImageToMeshFilterISS3MUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetObjectValue: Any = ...
    GetNumberOfNodes: Any = ...
    GetNumberOfCells: Any = ...
    SetInput: Any = ...
    SetRegionOfInterest: Any = ...
    GetRegionOfInterest: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryMask3DMeshSourceISS3MUC3___New_orig__: Any
itkBinaryMask3DMeshSourceISS3MUC3_cast: Any

def itkBinaryMask3DMeshSourceIUC3MD3_New(): ...

class itkBinaryMask3DMeshSourceIUC3MD3(itk.itkImageToMeshFilterPython.itkImageToMeshFilterIUC3MD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetObjectValue: Any = ...
    GetNumberOfNodes: Any = ...
    GetNumberOfCells: Any = ...
    SetInput: Any = ...
    SetRegionOfInterest: Any = ...
    GetRegionOfInterest: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryMask3DMeshSourceIUC3MD3___New_orig__: Any
itkBinaryMask3DMeshSourceIUC3MD3_cast: Any

def itkBinaryMask3DMeshSourceIUC3MF3_New(): ...

class itkBinaryMask3DMeshSourceIUC3MF3(itk.itkImageToMeshFilterPython.itkImageToMeshFilterIUC3MF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetObjectValue: Any = ...
    GetNumberOfNodes: Any = ...
    GetNumberOfCells: Any = ...
    SetInput: Any = ...
    SetRegionOfInterest: Any = ...
    GetRegionOfInterest: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryMask3DMeshSourceIUC3MF3___New_orig__: Any
itkBinaryMask3DMeshSourceIUC3MF3_cast: Any

def itkBinaryMask3DMeshSourceIUC3MSS3_New(): ...

class itkBinaryMask3DMeshSourceIUC3MSS3(itk.itkImageToMeshFilterPython.itkImageToMeshFilterIUC3MSS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetObjectValue: Any = ...
    GetNumberOfNodes: Any = ...
    GetNumberOfCells: Any = ...
    SetInput: Any = ...
    SetRegionOfInterest: Any = ...
    GetRegionOfInterest: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryMask3DMeshSourceIUC3MSS3___New_orig__: Any
itkBinaryMask3DMeshSourceIUC3MSS3_cast: Any

def itkBinaryMask3DMeshSourceIUC3MUC3_New(): ...

class itkBinaryMask3DMeshSourceIUC3MUC3(itk.itkImageToMeshFilterPython.itkImageToMeshFilterIUC3MUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetObjectValue: Any = ...
    GetNumberOfNodes: Any = ...
    GetNumberOfCells: Any = ...
    SetInput: Any = ...
    SetRegionOfInterest: Any = ...
    GetRegionOfInterest: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryMask3DMeshSourceIUC3MUC3___New_orig__: Any
itkBinaryMask3DMeshSourceIUC3MUC3_cast: Any

def binary_mask3_d_mesh_source(*args: Any, **kwargs: Any): ...
def binary_mask3_d_mesh_source_init_docstring() -> None: ...
