import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBinaryDilateImageFilterIF2IF2SE2_Superclass_New(): ...

class itkBinaryDilateImageFilterIF2IF2SE2_Superclass(itk.itkFlatStructuringElementPython.itkKernelImageFilterIF2IF2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetBoundaryToForeground: Any = ...
    GetBoundaryToForeground: Any = ...
    BoundaryToForegroundOn: Any = ...
    BoundaryToForegroundOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryDilateImageFilterIF2IF2SE2_Superclass___New_orig__: Any
itkBinaryDilateImageFilterIF2IF2SE2_Superclass_cast: Any

def itkBinaryDilateImageFilterIF3IF3SE3_Superclass_New(): ...

class itkBinaryDilateImageFilterIF3IF3SE3_Superclass(itk.itkFlatStructuringElementPython.itkKernelImageFilterIF3IF3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetBoundaryToForeground: Any = ...
    GetBoundaryToForeground: Any = ...
    BoundaryToForegroundOn: Any = ...
    BoundaryToForegroundOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryDilateImageFilterIF3IF3SE3_Superclass___New_orig__: Any
itkBinaryDilateImageFilterIF3IF3SE3_Superclass_cast: Any

def itkBinaryDilateImageFilterISS2ISS2SE2_Superclass_New(): ...

class itkBinaryDilateImageFilterISS2ISS2SE2_Superclass(itk.itkFlatStructuringElementPython.itkKernelImageFilterISS2ISS2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetBoundaryToForeground: Any = ...
    GetBoundaryToForeground: Any = ...
    BoundaryToForegroundOn: Any = ...
    BoundaryToForegroundOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryDilateImageFilterISS2ISS2SE2_Superclass___New_orig__: Any
itkBinaryDilateImageFilterISS2ISS2SE2_Superclass_cast: Any

def itkBinaryDilateImageFilterISS3ISS3SE3_Superclass_New(): ...

class itkBinaryDilateImageFilterISS3ISS3SE3_Superclass(itk.itkFlatStructuringElementPython.itkKernelImageFilterISS3ISS3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetBoundaryToForeground: Any = ...
    GetBoundaryToForeground: Any = ...
    BoundaryToForegroundOn: Any = ...
    BoundaryToForegroundOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryDilateImageFilterISS3ISS3SE3_Superclass___New_orig__: Any
itkBinaryDilateImageFilterISS3ISS3SE3_Superclass_cast: Any

def itkBinaryDilateImageFilterIUC2IUC2SE2_Superclass_New(): ...

class itkBinaryDilateImageFilterIUC2IUC2SE2_Superclass(itk.itkFlatStructuringElementPython.itkKernelImageFilterIUC2IUC2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetBoundaryToForeground: Any = ...
    GetBoundaryToForeground: Any = ...
    BoundaryToForegroundOn: Any = ...
    BoundaryToForegroundOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryDilateImageFilterIUC2IUC2SE2_Superclass___New_orig__: Any
itkBinaryDilateImageFilterIUC2IUC2SE2_Superclass_cast: Any

def itkBinaryDilateImageFilterIUC3IUC3SE3_Superclass_New(): ...

class itkBinaryDilateImageFilterIUC3IUC3SE3_Superclass(itk.itkFlatStructuringElementPython.itkKernelImageFilterIUC3IUC3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetBoundaryToForeground: Any = ...
    GetBoundaryToForeground: Any = ...
    BoundaryToForegroundOn: Any = ...
    BoundaryToForegroundOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryDilateImageFilterIUC3IUC3SE3_Superclass___New_orig__: Any
itkBinaryDilateImageFilterIUC3IUC3SE3_Superclass_cast: Any

def itkBinaryDilateImageFilterIF2IF2SE2_New(): ...

class itkBinaryDilateImageFilterIF2IF2SE2(itkBinaryDilateImageFilterIF2IF2SE2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDilateValue: Any = ...
    GetDilateValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryDilateImageFilterIF2IF2SE2___New_orig__: Any
itkBinaryDilateImageFilterIF2IF2SE2_cast: Any

def itkBinaryDilateImageFilterIF3IF3SE3_New(): ...

class itkBinaryDilateImageFilterIF3IF3SE3(itkBinaryDilateImageFilterIF3IF3SE3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDilateValue: Any = ...
    GetDilateValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryDilateImageFilterIF3IF3SE3___New_orig__: Any
itkBinaryDilateImageFilterIF3IF3SE3_cast: Any

def itkBinaryDilateImageFilterISS2ISS2SE2_New(): ...

class itkBinaryDilateImageFilterISS2ISS2SE2(itkBinaryDilateImageFilterISS2ISS2SE2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDilateValue: Any = ...
    GetDilateValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryDilateImageFilterISS2ISS2SE2___New_orig__: Any
itkBinaryDilateImageFilterISS2ISS2SE2_cast: Any

def itkBinaryDilateImageFilterISS3ISS3SE3_New(): ...

class itkBinaryDilateImageFilterISS3ISS3SE3(itkBinaryDilateImageFilterISS3ISS3SE3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDilateValue: Any = ...
    GetDilateValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryDilateImageFilterISS3ISS3SE3___New_orig__: Any
itkBinaryDilateImageFilterISS3ISS3SE3_cast: Any

def itkBinaryDilateImageFilterIUC2IUC2SE2_New(): ...

class itkBinaryDilateImageFilterIUC2IUC2SE2(itkBinaryDilateImageFilterIUC2IUC2SE2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDilateValue: Any = ...
    GetDilateValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryDilateImageFilterIUC2IUC2SE2___New_orig__: Any
itkBinaryDilateImageFilterIUC2IUC2SE2_cast: Any

def itkBinaryDilateImageFilterIUC3IUC3SE3_New(): ...

class itkBinaryDilateImageFilterIUC3IUC3SE3(itkBinaryDilateImageFilterIUC3IUC3SE3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDilateValue: Any = ...
    GetDilateValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryDilateImageFilterIUC3IUC3SE3___New_orig__: Any
itkBinaryDilateImageFilterIUC3IUC3SE3_cast: Any

def binary_morphology_image_filter(*args: Any, **kwargs: Any): ...
def binary_morphology_image_filter_init_docstring() -> None: ...
def binary_dilate_image_filter(*args: Any, **kwargs: Any): ...
def binary_dilate_image_filter_init_docstring() -> None: ...
