import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBinaryStatisticsKeepNObjectsImageFilterIUC2IF2_New(): ...

class itkBinaryStatisticsKeepNObjectsImageFilterIUC2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    GetNumberOfObjects: Any = ...
    SetNumberOfObjects: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryStatisticsKeepNObjectsImageFilterIUC2IF2___New_orig__: Any
itkBinaryStatisticsKeepNObjectsImageFilterIUC2IF2_cast: Any

def itkBinaryStatisticsKeepNObjectsImageFilterIUC2ISS2_New(): ...

class itkBinaryStatisticsKeepNObjectsImageFilterIUC2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    GetNumberOfObjects: Any = ...
    SetNumberOfObjects: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryStatisticsKeepNObjectsImageFilterIUC2ISS2___New_orig__: Any
itkBinaryStatisticsKeepNObjectsImageFilterIUC2ISS2_cast: Any

def itkBinaryStatisticsKeepNObjectsImageFilterIUC2IUC2_New(): ...

class itkBinaryStatisticsKeepNObjectsImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    GetNumberOfObjects: Any = ...
    SetNumberOfObjects: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryStatisticsKeepNObjectsImageFilterIUC2IUC2___New_orig__: Any
itkBinaryStatisticsKeepNObjectsImageFilterIUC2IUC2_cast: Any

def itkBinaryStatisticsKeepNObjectsImageFilterIUC3IF3_New(): ...

class itkBinaryStatisticsKeepNObjectsImageFilterIUC3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    GetNumberOfObjects: Any = ...
    SetNumberOfObjects: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryStatisticsKeepNObjectsImageFilterIUC3IF3___New_orig__: Any
itkBinaryStatisticsKeepNObjectsImageFilterIUC3IF3_cast: Any

def itkBinaryStatisticsKeepNObjectsImageFilterIUC3ISS3_New(): ...

class itkBinaryStatisticsKeepNObjectsImageFilterIUC3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    GetNumberOfObjects: Any = ...
    SetNumberOfObjects: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryStatisticsKeepNObjectsImageFilterIUC3ISS3___New_orig__: Any
itkBinaryStatisticsKeepNObjectsImageFilterIUC3ISS3_cast: Any

def itkBinaryStatisticsKeepNObjectsImageFilterIUC3IUC3_New(): ...

class itkBinaryStatisticsKeepNObjectsImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    GetNumberOfObjects: Any = ...
    SetNumberOfObjects: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryStatisticsKeepNObjectsImageFilterIUC3IUC3___New_orig__: Any
itkBinaryStatisticsKeepNObjectsImageFilterIUC3IUC3_cast: Any

def binary_statistics_keep_n_objects_image_filter(*args: Any, **kwargs: Any): ...
def binary_statistics_keep_n_objects_image_filter_init_docstring() -> None: ...
