import itk.itkInPlaceImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBoundedReciprocalImageFilterIF2IF2_New(): ...

class itkBoundedReciprocalImageFilterIF2IF2(itk.itkUnaryGeneratorImageFilterPython.itkUnaryGeneratorImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToDoubleCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBoundedReciprocalImageFilterIF2IF2___New_orig__: Any
itkBoundedReciprocalImageFilterIF2IF2_cast: Any

def itkBoundedReciprocalImageFilterIF3IF3_New(): ...

class itkBoundedReciprocalImageFilterIF3IF3(itk.itkUnaryGeneratorImageFilterPython.itkUnaryGeneratorImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToDoubleCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBoundedReciprocalImageFilterIF3IF3___New_orig__: Any
itkBoundedReciprocalImageFilterIF3IF3_cast: Any

def itkBoundedReciprocalImageFilterISS2ISS2_New(): ...

class itkBoundedReciprocalImageFilterISS2ISS2(itk.itkUnaryGeneratorImageFilterPython.itkUnaryGeneratorImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToDoubleCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBoundedReciprocalImageFilterISS2ISS2___New_orig__: Any
itkBoundedReciprocalImageFilterISS2ISS2_cast: Any

def itkBoundedReciprocalImageFilterISS3ISS3_New(): ...

class itkBoundedReciprocalImageFilterISS3ISS3(itk.itkUnaryGeneratorImageFilterPython.itkUnaryGeneratorImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToDoubleCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBoundedReciprocalImageFilterISS3ISS3___New_orig__: Any
itkBoundedReciprocalImageFilterISS3ISS3_cast: Any

def itkBoundedReciprocalImageFilterIUC2IUC2_New(): ...

class itkBoundedReciprocalImageFilterIUC2IUC2(itk.itkUnaryGeneratorImageFilterPython.itkUnaryGeneratorImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToDoubleCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBoundedReciprocalImageFilterIUC2IUC2___New_orig__: Any
itkBoundedReciprocalImageFilterIUC2IUC2_cast: Any

def itkBoundedReciprocalImageFilterIUC3IUC3_New(): ...

class itkBoundedReciprocalImageFilterIUC3IUC3(itk.itkUnaryGeneratorImageFilterPython.itkUnaryGeneratorImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToDoubleCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBoundedReciprocalImageFilterIUC3IUC3___New_orig__: Any
itkBoundedReciprocalImageFilterIUC3IUC3_cast: Any

def bounded_reciprocal_image_filter(*args: Any, **kwargs: Any): ...
def bounded_reciprocal_image_filter_init_docstring() -> None: ...
