import itk.itkImageToImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBinaryProjectionImageFilterIF2IF2_Superclass_New(): ...

class itkBinaryProjectionImageFilterIF2IF2_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryProjectionImageFilterIF2IF2_Superclass___New_orig__: Any
itkBinaryProjectionImageFilterIF2IF2_Superclass_cast: Any

def itkBinaryProjectionImageFilterIF3IF3_Superclass_New(): ...

class itkBinaryProjectionImageFilterIF3IF3_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryProjectionImageFilterIF3IF3_Superclass___New_orig__: Any
itkBinaryProjectionImageFilterIF3IF3_Superclass_cast: Any

def itkBinaryProjectionImageFilterISS2ISS2_Superclass_New(): ...

class itkBinaryProjectionImageFilterISS2ISS2_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryProjectionImageFilterISS2ISS2_Superclass___New_orig__: Any
itkBinaryProjectionImageFilterISS2ISS2_Superclass_cast: Any

def itkBinaryProjectionImageFilterISS3ISS2_Superclass_New(): ...

class itkBinaryProjectionImageFilterISS3ISS2_Superclass(itk.itkImageToImageFilterBPython.itkImageToImageFilterISS3ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryProjectionImageFilterISS3ISS2_Superclass___New_orig__: Any
itkBinaryProjectionImageFilterISS3ISS2_Superclass_cast: Any

def itkBinaryProjectionImageFilterISS3ISS3_Superclass_New(): ...

class itkBinaryProjectionImageFilterISS3ISS3_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryProjectionImageFilterISS3ISS3_Superclass___New_orig__: Any
itkBinaryProjectionImageFilterISS3ISS3_Superclass_cast: Any

def itkBinaryProjectionImageFilterIUC2IUC2_Superclass_New(): ...

class itkBinaryProjectionImageFilterIUC2IUC2_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryProjectionImageFilterIUC2IUC2_Superclass___New_orig__: Any
itkBinaryProjectionImageFilterIUC2IUC2_Superclass_cast: Any

def itkBinaryProjectionImageFilterIUC3IUC2_Superclass_New(): ...

class itkBinaryProjectionImageFilterIUC3IUC2_Superclass(itk.itkImageToImageFilterBPython.itkImageToImageFilterIUC3IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryProjectionImageFilterIUC3IUC2_Superclass___New_orig__: Any
itkBinaryProjectionImageFilterIUC3IUC2_Superclass_cast: Any

def itkBinaryProjectionImageFilterIUC3IUC3_Superclass_New(): ...

class itkBinaryProjectionImageFilterIUC3IUC3_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryProjectionImageFilterIUC3IUC3_Superclass___New_orig__: Any
itkBinaryProjectionImageFilterIUC3IUC3_Superclass_cast: Any

def itkBinaryProjectionImageFilterIF2IF2_New(): ...

class itkBinaryProjectionImageFilterIF2IF2(itkBinaryProjectionImageFilterIF2IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    InputPixelTypeGreaterThanComparable: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryProjectionImageFilterIF2IF2___New_orig__: Any
itkBinaryProjectionImageFilterIF2IF2_cast: Any

def itkBinaryProjectionImageFilterIF3IF3_New(): ...

class itkBinaryProjectionImageFilterIF3IF3(itkBinaryProjectionImageFilterIF3IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    InputPixelTypeGreaterThanComparable: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryProjectionImageFilterIF3IF3___New_orig__: Any
itkBinaryProjectionImageFilterIF3IF3_cast: Any

def itkBinaryProjectionImageFilterISS2ISS2_New(): ...

class itkBinaryProjectionImageFilterISS2ISS2(itkBinaryProjectionImageFilterISS2ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    InputPixelTypeGreaterThanComparable: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryProjectionImageFilterISS2ISS2___New_orig__: Any
itkBinaryProjectionImageFilterISS2ISS2_cast: Any

def itkBinaryProjectionImageFilterISS3ISS2_New(): ...

class itkBinaryProjectionImageFilterISS3ISS2(itkBinaryProjectionImageFilterISS3ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    InputPixelTypeGreaterThanComparable: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryProjectionImageFilterISS3ISS2___New_orig__: Any
itkBinaryProjectionImageFilterISS3ISS2_cast: Any

def itkBinaryProjectionImageFilterISS3ISS3_New(): ...

class itkBinaryProjectionImageFilterISS3ISS3(itkBinaryProjectionImageFilterISS3ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    InputPixelTypeGreaterThanComparable: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryProjectionImageFilterISS3ISS3___New_orig__: Any
itkBinaryProjectionImageFilterISS3ISS3_cast: Any

def itkBinaryProjectionImageFilterIUC2IUC2_New(): ...

class itkBinaryProjectionImageFilterIUC2IUC2(itkBinaryProjectionImageFilterIUC2IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    InputPixelTypeGreaterThanComparable: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryProjectionImageFilterIUC2IUC2___New_orig__: Any
itkBinaryProjectionImageFilterIUC2IUC2_cast: Any

def itkBinaryProjectionImageFilterIUC3IUC2_New(): ...

class itkBinaryProjectionImageFilterIUC3IUC2(itkBinaryProjectionImageFilterIUC3IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    InputPixelTypeGreaterThanComparable: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryProjectionImageFilterIUC3IUC2___New_orig__: Any
itkBinaryProjectionImageFilterIUC3IUC2_cast: Any

def itkBinaryProjectionImageFilterIUC3IUC3_New(): ...

class itkBinaryProjectionImageFilterIUC3IUC3(itkBinaryProjectionImageFilterIUC3IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    InputPixelTypeGreaterThanComparable: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryProjectionImageFilterIUC3IUC3___New_orig__: Any
itkBinaryProjectionImageFilterIUC3IUC3_cast: Any

def binary_projection_image_filter(*args: Any, **kwargs: Any): ...
def binary_projection_image_filter_init_docstring() -> None: ...
def projection_image_filter(*args: Any, **kwargs: Any): ...
def projection_image_filter_init_docstring() -> None: ...
