import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBinaryPruningImageFilterIF2IF2_New(): ...

class itkBinaryPruningImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetPruning: Any = ...
    SetIteration: Any = ...
    GetIteration: Any = ...
    SameDimensionCheck: Any = ...
    SameTypeCheck: Any = ...
    AdditiveOperatorsCheck: Any = ...
    IntConvertibleToPixelTypeCheck: Any = ...
    PixelLessThanIntCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryPruningImageFilterIF2IF2___New_orig__: Any
itkBinaryPruningImageFilterIF2IF2_cast: Any

def itkBinaryPruningImageFilterIUC2IUC2_New(): ...

class itkBinaryPruningImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetPruning: Any = ...
    SetIteration: Any = ...
    GetIteration: Any = ...
    SameDimensionCheck: Any = ...
    SameTypeCheck: Any = ...
    AdditiveOperatorsCheck: Any = ...
    IntConvertibleToPixelTypeCheck: Any = ...
    PixelLessThanIntCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryPruningImageFilterIUC2IUC2___New_orig__: Any
itkBinaryPruningImageFilterIUC2IUC2_cast: Any

def binary_pruning_image_filter(*args: Any, **kwargs: Any): ...
def binary_pruning_image_filter_init_docstring() -> None: ...
