import itk.itkImageRegionPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBSplineSmoothingOnUpdateDisplacementFieldTransformD2_New(): ...

class itkBSplineSmoothingOnUpdateDisplacementFieldTransformD2(itk.itkDisplacementFieldTransformPython.itkDisplacementFieldTransformD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    UpdateTransformParameters: Any = ...
    SetSplineOrder: Any = ...
    GetSplineOrder: Any = ...
    SetNumberOfControlPointsForTheUpdateField: Any = ...
    GetNumberOfControlPointsForTheUpdateField: Any = ...
    SetMeshSizeForTheUpdateField: Any = ...
    SetNumberOfControlPointsForTheTotalField: Any = ...
    GetNumberOfControlPointsForTheTotalField: Any = ...
    SetMeshSizeForTheTotalField: Any = ...
    EnforceStationaryBoundaryOn: Any = ...
    EnforceStationaryBoundaryOff: Any = ...
    SetEnforceStationaryBoundary: Any = ...
    GetEnforceStationaryBoundary: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineSmoothingOnUpdateDisplacementFieldTransformD2___New_orig__: Any
itkBSplineSmoothingOnUpdateDisplacementFieldTransformD2_cast: Any

def itkBSplineSmoothingOnUpdateDisplacementFieldTransformD3_New(): ...

class itkBSplineSmoothingOnUpdateDisplacementFieldTransformD3(itk.itkDisplacementFieldTransformPython.itkDisplacementFieldTransformD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    UpdateTransformParameters: Any = ...
    SetSplineOrder: Any = ...
    GetSplineOrder: Any = ...
    SetNumberOfControlPointsForTheUpdateField: Any = ...
    GetNumberOfControlPointsForTheUpdateField: Any = ...
    SetMeshSizeForTheUpdateField: Any = ...
    SetNumberOfControlPointsForTheTotalField: Any = ...
    GetNumberOfControlPointsForTheTotalField: Any = ...
    SetMeshSizeForTheTotalField: Any = ...
    EnforceStationaryBoundaryOn: Any = ...
    EnforceStationaryBoundaryOff: Any = ...
    SetEnforceStationaryBoundary: Any = ...
    GetEnforceStationaryBoundary: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineSmoothingOnUpdateDisplacementFieldTransformD3___New_orig__: Any
itkBSplineSmoothingOnUpdateDisplacementFieldTransformD3_cast: Any
