import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBinaryThinningImageFilterISS2ISS2_New(): ...

class itkBinaryThinningImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetThinning: Any = ...
    SameDimensionCheck: Any = ...
    InputAdditiveOperatorsCheck: Any = ...
    InputConvertibleToIntCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    SameTypeCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryThinningImageFilterISS2ISS2___New_orig__: Any
itkBinaryThinningImageFilterISS2ISS2_cast: Any

def itkBinaryThinningImageFilterIUC2IUC2_New(): ...

class itkBinaryThinningImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetThinning: Any = ...
    SameDimensionCheck: Any = ...
    InputAdditiveOperatorsCheck: Any = ...
    InputConvertibleToIntCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    SameTypeCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryThinningImageFilterIUC2IUC2___New_orig__: Any
itkBinaryThinningImageFilterIUC2IUC2_cast: Any

def binary_thinning_image_filter(*args: Any, **kwargs: Any): ...
def binary_thinning_image_filter_init_docstring() -> None: ...
