import itk.itkLabelImageToLabelMapFilterPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBinaryImageToLabelMapFilterIUC2LM2_New(): ...

class itkBinaryImageToLabelMapFilterIUC2LM2(itk.ITKLabelMapBasePython.itkImageToImageFilterIUC2LM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    GetNumberOfObjects: Any = ...
    SetOutputBackgroundValue: Any = ...
    GetOutputBackgroundValue: Any = ...
    SetInputForegroundValue: Any = ...
    GetInputForegroundValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryImageToLabelMapFilterIUC2LM2___New_orig__: Any
itkBinaryImageToLabelMapFilterIUC2LM2_cast: Any

def itkBinaryImageToLabelMapFilterIUC3LM3_New(): ...

class itkBinaryImageToLabelMapFilterIUC3LM3(itk.ITKLabelMapBasePython.itkImageToImageFilterIUC3LM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    GetNumberOfObjects: Any = ...
    SetOutputBackgroundValue: Any = ...
    GetOutputBackgroundValue: Any = ...
    SetInputForegroundValue: Any = ...
    GetInputForegroundValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryImageToLabelMapFilterIUC3LM3___New_orig__: Any
itkBinaryImageToLabelMapFilterIUC3LM3_cast: Any

def binary_image_to_label_map_filter(*args: Any, **kwargs: Any): ...
def binary_image_to_label_map_filter_init_docstring() -> None: ...
