import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBinaryMinMaxCurvatureFlowImageFilterIF2IF2_New(): ...

class itkBinaryMinMaxCurvatureFlowImageFilterIF2IF2(itk.itkMinMaxCurvatureFlowImageFilterPython.itkMinMaxCurvatureFlowImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetThreshold: Any = ...
    GetThreshold: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryMinMaxCurvatureFlowImageFilterIF2IF2___New_orig__: Any
itkBinaryMinMaxCurvatureFlowImageFilterIF2IF2_cast: Any

def itkBinaryMinMaxCurvatureFlowImageFilterIF3IF3_New(): ...

class itkBinaryMinMaxCurvatureFlowImageFilterIF3IF3(itk.itkMinMaxCurvatureFlowImageFilterPython.itkMinMaxCurvatureFlowImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetThreshold: Any = ...
    GetThreshold: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryMinMaxCurvatureFlowImageFilterIF3IF3___New_orig__: Any
itkBinaryMinMaxCurvatureFlowImageFilterIF3IF3_cast: Any

def binary_min_max_curvature_flow_image_filter(*args: Any, **kwargs: Any): ...
def binary_min_max_curvature_flow_image_filter_init_docstring() -> None: ...
