import itk.itkNeighborhoodPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBinaryErodeImageFilterIF2IF2SE2_New(): ...

class itkBinaryErodeImageFilterIF2IF2SE2(itk.itkBinaryDilateImageFilterPython.itkBinaryDilateImageFilterIF2IF2SE2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetErodeValue: Any = ...
    GetErodeValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryErodeImageFilterIF2IF2SE2___New_orig__: Any
itkBinaryErodeImageFilterIF2IF2SE2_cast: Any

def itkBinaryErodeImageFilterIF3IF3SE3_New(): ...

class itkBinaryErodeImageFilterIF3IF3SE3(itk.itkBinaryDilateImageFilterPython.itkBinaryDilateImageFilterIF3IF3SE3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetErodeValue: Any = ...
    GetErodeValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryErodeImageFilterIF3IF3SE3___New_orig__: Any
itkBinaryErodeImageFilterIF3IF3SE3_cast: Any

def itkBinaryErodeImageFilterISS2ISS2SE2_New(): ...

class itkBinaryErodeImageFilterISS2ISS2SE2(itk.itkBinaryDilateImageFilterPython.itkBinaryDilateImageFilterISS2ISS2SE2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetErodeValue: Any = ...
    GetErodeValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryErodeImageFilterISS2ISS2SE2___New_orig__: Any
itkBinaryErodeImageFilterISS2ISS2SE2_cast: Any

def itkBinaryErodeImageFilterISS3ISS3SE3_New(): ...

class itkBinaryErodeImageFilterISS3ISS3SE3(itk.itkBinaryDilateImageFilterPython.itkBinaryDilateImageFilterISS3ISS3SE3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetErodeValue: Any = ...
    GetErodeValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryErodeImageFilterISS3ISS3SE3___New_orig__: Any
itkBinaryErodeImageFilterISS3ISS3SE3_cast: Any

def itkBinaryErodeImageFilterIUC2IUC2SE2_New(): ...

class itkBinaryErodeImageFilterIUC2IUC2SE2(itk.itkBinaryDilateImageFilterPython.itkBinaryDilateImageFilterIUC2IUC2SE2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetErodeValue: Any = ...
    GetErodeValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryErodeImageFilterIUC2IUC2SE2___New_orig__: Any
itkBinaryErodeImageFilterIUC2IUC2SE2_cast: Any

def itkBinaryErodeImageFilterIUC3IUC3SE3_New(): ...

class itkBinaryErodeImageFilterIUC3IUC3SE3(itk.itkBinaryDilateImageFilterPython.itkBinaryDilateImageFilterIUC3IUC3SE3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetErodeValue: Any = ...
    GetErodeValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryErodeImageFilterIUC3IUC3SE3___New_orig__: Any
itkBinaryErodeImageFilterIUC3IUC3SE3_cast: Any

def binary_erode_image_filter(*args: Any, **kwargs: Any): ...
def binary_erode_image_filter_init_docstring() -> None: ...
