import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBinaryMedianImageFilterIF2IF2_New(): ...

class itkBinaryMedianImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetForegroundValue: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryMedianImageFilterIF2IF2___New_orig__: Any
itkBinaryMedianImageFilterIF2IF2_cast: Any

def itkBinaryMedianImageFilterIF3IF3_New(): ...

class itkBinaryMedianImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetForegroundValue: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryMedianImageFilterIF3IF3___New_orig__: Any
itkBinaryMedianImageFilterIF3IF3_cast: Any

def itkBinaryMedianImageFilterISS2ISS2_New(): ...

class itkBinaryMedianImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetForegroundValue: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryMedianImageFilterISS2ISS2___New_orig__: Any
itkBinaryMedianImageFilterISS2ISS2_cast: Any

def itkBinaryMedianImageFilterISS3ISS3_New(): ...

class itkBinaryMedianImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetForegroundValue: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryMedianImageFilterISS3ISS3___New_orig__: Any
itkBinaryMedianImageFilterISS3ISS3_cast: Any

def itkBinaryMedianImageFilterIUC2IUC2_New(): ...

class itkBinaryMedianImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetForegroundValue: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryMedianImageFilterIUC2IUC2___New_orig__: Any
itkBinaryMedianImageFilterIUC2IUC2_cast: Any

def itkBinaryMedianImageFilterIUC3IUC3_New(): ...

class itkBinaryMedianImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetForegroundValue: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBinaryMedianImageFilterIUC3IUC3___New_orig__: Any
itkBinaryMedianImageFilterIUC3IUC3_cast: Any

def binary_median_image_filter(*args: Any, **kwargs: Any): ...
def binary_median_image_filter_init_docstring() -> None: ...
