import itk.itkArrayPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBSplineInterpolateImageFunctionIF2DF_New(): ...

class itkBSplineInterpolateImageFunctionIF2DF(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionIF2D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Evaluate: Any = ...
    EvaluateAtContinuousIndex: Any = ...
    EvaluateDerivative: Any = ...
    EvaluateDerivativeAtContinuousIndex: Any = ...
    EvaluateValueAndDerivative: Any = ...
    EvaluateValueAndDerivativeAtContinuousIndex: Any = ...
    SetSplineOrder: Any = ...
    GetSplineOrder: Any = ...
    SetNumberOfWorkUnits: Any = ...
    GetNumberOfWorkUnits: Any = ...
    SetUseImageDirection: Any = ...
    GetUseImageDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineInterpolateImageFunctionIF2DF___New_orig__: Any
itkBSplineInterpolateImageFunctionIF2DF_cast: Any

def itkBSplineInterpolateImageFunctionIF3DF_New(): ...

class itkBSplineInterpolateImageFunctionIF3DF(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionIF3D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Evaluate: Any = ...
    EvaluateAtContinuousIndex: Any = ...
    EvaluateDerivative: Any = ...
    EvaluateDerivativeAtContinuousIndex: Any = ...
    EvaluateValueAndDerivative: Any = ...
    EvaluateValueAndDerivativeAtContinuousIndex: Any = ...
    SetSplineOrder: Any = ...
    GetSplineOrder: Any = ...
    SetNumberOfWorkUnits: Any = ...
    GetNumberOfWorkUnits: Any = ...
    SetUseImageDirection: Any = ...
    GetUseImageDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineInterpolateImageFunctionIF3DF___New_orig__: Any
itkBSplineInterpolateImageFunctionIF3DF_cast: Any

def itkBSplineInterpolateImageFunctionISS2DSS_New(): ...

class itkBSplineInterpolateImageFunctionISS2DSS(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionISS2D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Evaluate: Any = ...
    EvaluateAtContinuousIndex: Any = ...
    EvaluateDerivative: Any = ...
    EvaluateDerivativeAtContinuousIndex: Any = ...
    EvaluateValueAndDerivative: Any = ...
    EvaluateValueAndDerivativeAtContinuousIndex: Any = ...
    SetSplineOrder: Any = ...
    GetSplineOrder: Any = ...
    SetNumberOfWorkUnits: Any = ...
    GetNumberOfWorkUnits: Any = ...
    SetUseImageDirection: Any = ...
    GetUseImageDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineInterpolateImageFunctionISS2DSS___New_orig__: Any
itkBSplineInterpolateImageFunctionISS2DSS_cast: Any

def itkBSplineInterpolateImageFunctionISS3DSS_New(): ...

class itkBSplineInterpolateImageFunctionISS3DSS(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionISS3D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Evaluate: Any = ...
    EvaluateAtContinuousIndex: Any = ...
    EvaluateDerivative: Any = ...
    EvaluateDerivativeAtContinuousIndex: Any = ...
    EvaluateValueAndDerivative: Any = ...
    EvaluateValueAndDerivativeAtContinuousIndex: Any = ...
    SetSplineOrder: Any = ...
    GetSplineOrder: Any = ...
    SetNumberOfWorkUnits: Any = ...
    GetNumberOfWorkUnits: Any = ...
    SetUseImageDirection: Any = ...
    GetUseImageDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineInterpolateImageFunctionISS3DSS___New_orig__: Any
itkBSplineInterpolateImageFunctionISS3DSS_cast: Any

def itkBSplineInterpolateImageFunctionIUC2DUC_New(): ...

class itkBSplineInterpolateImageFunctionIUC2DUC(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionIUC2D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Evaluate: Any = ...
    EvaluateAtContinuousIndex: Any = ...
    EvaluateDerivative: Any = ...
    EvaluateDerivativeAtContinuousIndex: Any = ...
    EvaluateValueAndDerivative: Any = ...
    EvaluateValueAndDerivativeAtContinuousIndex: Any = ...
    SetSplineOrder: Any = ...
    GetSplineOrder: Any = ...
    SetNumberOfWorkUnits: Any = ...
    GetNumberOfWorkUnits: Any = ...
    SetUseImageDirection: Any = ...
    GetUseImageDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineInterpolateImageFunctionIUC2DUC___New_orig__: Any
itkBSplineInterpolateImageFunctionIUC2DUC_cast: Any

def itkBSplineInterpolateImageFunctionIUC3DUC_New(): ...

class itkBSplineInterpolateImageFunctionIUC3DUC(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionIUC3D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Evaluate: Any = ...
    EvaluateAtContinuousIndex: Any = ...
    EvaluateDerivative: Any = ...
    EvaluateDerivativeAtContinuousIndex: Any = ...
    EvaluateValueAndDerivative: Any = ...
    EvaluateValueAndDerivativeAtContinuousIndex: Any = ...
    SetSplineOrder: Any = ...
    GetSplineOrder: Any = ...
    SetNumberOfWorkUnits: Any = ...
    GetNumberOfWorkUnits: Any = ...
    SetUseImageDirection: Any = ...
    GetUseImageDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBSplineInterpolateImageFunctionIUC3DUC___New_orig__: Any
itkBSplineInterpolateImageFunctionIUC3DUC_cast: Any
