import itk.itkImageRegionPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkCleanQuadEdgeMeshFilterQEMD2_New(): ...

class itkCleanQuadEdgeMeshFilterQEMD2(itk.itkQuadEdgeMeshToQuadEdgeMeshFilterPython.itkQuadEdgeMeshToQuadEdgeMeshFilterQEMD2QEMD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAbsoluteTolerance: Any = ...
    GetAbsoluteTolerance: Any = ...
    SetRelativeTolerance: Any = ...
    GetRelativeTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCleanQuadEdgeMeshFilterQEMD2___New_orig__: Any
itkCleanQuadEdgeMeshFilterQEMD2_cast: Any

def itkCleanQuadEdgeMeshFilterQEMD3_New(): ...

class itkCleanQuadEdgeMeshFilterQEMD3(itk.itkQuadEdgeMeshToQuadEdgeMeshFilterPython.itkQuadEdgeMeshToQuadEdgeMeshFilterQEMD3QEMD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAbsoluteTolerance: Any = ...
    GetAbsoluteTolerance: Any = ...
    SetRelativeTolerance: Any = ...
    GetRelativeTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCleanQuadEdgeMeshFilterQEMD3___New_orig__: Any
itkCleanQuadEdgeMeshFilterQEMD3_cast: Any

def clean_quad_edge_mesh_filter(*args: Any, **kwargs: Any): ...
def clean_quad_edge_mesh_filter_init_docstring() -> None: ...
