import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkCheckerBoardImageFilterICF2_New(): ...

class itkCheckerBoardImageFilterICF2(itk.itkImageToImageFilterBPython.itkImageToImageFilterICF2ICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterICF2___New_orig__: Any
itkCheckerBoardImageFilterICF2_cast: Any

def itkCheckerBoardImageFilterICF3_New(): ...

class itkCheckerBoardImageFilterICF3(itk.itkImageToImageFilterBPython.itkImageToImageFilterICF3ICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterICF3___New_orig__: Any
itkCheckerBoardImageFilterICF3_cast: Any

def itkCheckerBoardImageFilterICVF22_New(): ...

class itkCheckerBoardImageFilterICVF22(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF22ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterICVF22___New_orig__: Any
itkCheckerBoardImageFilterICVF22_cast: Any

def itkCheckerBoardImageFilterICVF23_New(): ...

class itkCheckerBoardImageFilterICVF23(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF23ICVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterICVF23___New_orig__: Any
itkCheckerBoardImageFilterICVF23_cast: Any

def itkCheckerBoardImageFilterICVF32_New(): ...

class itkCheckerBoardImageFilterICVF32(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF32ICVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterICVF32___New_orig__: Any
itkCheckerBoardImageFilterICVF32_cast: Any

def itkCheckerBoardImageFilterICVF33_New(): ...

class itkCheckerBoardImageFilterICVF33(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF33ICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterICVF33___New_orig__: Any
itkCheckerBoardImageFilterICVF33_cast: Any

def itkCheckerBoardImageFilterICVF42_New(): ...

class itkCheckerBoardImageFilterICVF42(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF42ICVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterICVF42___New_orig__: Any
itkCheckerBoardImageFilterICVF42_cast: Any

def itkCheckerBoardImageFilterICVF43_New(): ...

class itkCheckerBoardImageFilterICVF43(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF43ICVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterICVF43___New_orig__: Any
itkCheckerBoardImageFilterICVF43_cast: Any

def itkCheckerBoardImageFilterIF2_New(): ...

class itkCheckerBoardImageFilterIF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterIF2___New_orig__: Any
itkCheckerBoardImageFilterIF2_cast: Any

def itkCheckerBoardImageFilterIF3_New(): ...

class itkCheckerBoardImageFilterIF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterIF3___New_orig__: Any
itkCheckerBoardImageFilterIF3_cast: Any

def itkCheckerBoardImageFilterIRGBAUC2_New(): ...

class itkCheckerBoardImageFilterIRGBAUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBAUC2IRGBAUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterIRGBAUC2___New_orig__: Any
itkCheckerBoardImageFilterIRGBAUC2_cast: Any

def itkCheckerBoardImageFilterIRGBAUC3_New(): ...

class itkCheckerBoardImageFilterIRGBAUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBAUC3IRGBAUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterIRGBAUC3___New_orig__: Any
itkCheckerBoardImageFilterIRGBAUC3_cast: Any

def itkCheckerBoardImageFilterIRGBUC2_New(): ...

class itkCheckerBoardImageFilterIRGBUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBUC2IRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterIRGBUC2___New_orig__: Any
itkCheckerBoardImageFilterIRGBUC2_cast: Any

def itkCheckerBoardImageFilterIRGBUC3_New(): ...

class itkCheckerBoardImageFilterIRGBUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBUC3IRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterIRGBUC3___New_orig__: Any
itkCheckerBoardImageFilterIRGBUC3_cast: Any

def itkCheckerBoardImageFilterISS2_New(): ...

class itkCheckerBoardImageFilterISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterISS2___New_orig__: Any
itkCheckerBoardImageFilterISS2_cast: Any

def itkCheckerBoardImageFilterISS3_New(): ...

class itkCheckerBoardImageFilterISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterISS3___New_orig__: Any
itkCheckerBoardImageFilterISS3_cast: Any

def itkCheckerBoardImageFilterIUC2_New(): ...

class itkCheckerBoardImageFilterIUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterIUC2___New_orig__: Any
itkCheckerBoardImageFilterIUC2_cast: Any

def itkCheckerBoardImageFilterIUC3_New(): ...

class itkCheckerBoardImageFilterIUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterIUC3___New_orig__: Any
itkCheckerBoardImageFilterIUC3_cast: Any

def itkCheckerBoardImageFilterIVF22_New(): ...

class itkCheckerBoardImageFilterIVF22(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF22IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterIVF22___New_orig__: Any
itkCheckerBoardImageFilterIVF22_cast: Any

def itkCheckerBoardImageFilterIVF23_New(): ...

class itkCheckerBoardImageFilterIVF23(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF23IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterIVF23___New_orig__: Any
itkCheckerBoardImageFilterIVF23_cast: Any

def itkCheckerBoardImageFilterIVF32_New(): ...

class itkCheckerBoardImageFilterIVF32(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF32IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterIVF32___New_orig__: Any
itkCheckerBoardImageFilterIVF32_cast: Any

def itkCheckerBoardImageFilterIVF33_New(): ...

class itkCheckerBoardImageFilterIVF33(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF33IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterIVF33___New_orig__: Any
itkCheckerBoardImageFilterIVF33_cast: Any

def itkCheckerBoardImageFilterIVF42_New(): ...

class itkCheckerBoardImageFilterIVF42(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF42IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterIVF42___New_orig__: Any
itkCheckerBoardImageFilterIVF42_cast: Any

def itkCheckerBoardImageFilterIVF43_New(): ...

class itkCheckerBoardImageFilterIVF43(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF43IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetCheckerPattern: Any = ...
    GetCheckerPattern: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCheckerBoardImageFilterIVF43___New_orig__: Any
itkCheckerBoardImageFilterIVF43_cast: Any

def checker_board_image_filter(*args: Any, **kwargs: Any): ...
def checker_board_image_filter_init_docstring() -> None: ...
