import itk.stdcomplexPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkContinuousIndexD2(itk.itkPointPython.itkPointD2):
    thisown: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    __len__: Any = ...

itkContinuousIndexD2___len__: Any

class itkContinuousIndexD3(itk.itkPointPython.itkPointD3):
    thisown: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    __len__: Any = ...

itkContinuousIndexD3___len__: Any

class itkContinuousIndexD4(itk.itkPointPython.itkPointD4):
    thisown: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    __len__: Any = ...

itkContinuousIndexD4___len__: Any

class itkContinuousIndexF2(itk.itkPointPython.itkPointF2):
    thisown: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    __len__: Any = ...

itkContinuousIndexF2___len__: Any

class itkContinuousIndexF3(itk.itkPointPython.itkPointF3):
    thisown: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    __len__: Any = ...

itkContinuousIndexF3___len__: Any

class itkContinuousIndexF4(itk.itkPointPython.itkPointF4):
    thisown: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    __len__: Any = ...

itkContinuousIndexF4___len__: Any
