import itk.itkPointSetPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkCorrelationImageToImageMetricv4IF2IF2_New(): ...

class itkCorrelationImageToImageMetricv4IF2IF2(itk.itkImageToImageMetricv4Python.itkImageToImageMetricv4F2F2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCorrelationImageToImageMetricv4IF2IF2___New_orig__: Any
itkCorrelationImageToImageMetricv4IF2IF2_cast: Any

def itkCorrelationImageToImageMetricv4IF3IF3_New(): ...

class itkCorrelationImageToImageMetricv4IF3IF3(itk.itkImageToImageMetricv4Python.itkImageToImageMetricv4F3F3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCorrelationImageToImageMetricv4IF3IF3___New_orig__: Any
itkCorrelationImageToImageMetricv4IF3IF3_cast: Any
