import itk.itkImageRegionPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkConstantVelocityFieldTransformD2_New(): ...

class itkConstantVelocityFieldTransformD2(itk.itkDisplacementFieldTransformPython.itkDisplacementFieldTransformD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetConstantVelocityField: Any = ...
    GetModifiableConstantVelocityField: Any = ...
    GetConstantVelocityField: Any = ...
    SetConstantVelocityFieldInterpolator: Any = ...
    GetModifiableConstantVelocityFieldInterpolator: Any = ...
    GetConstantVelocityFieldInterpolator: Any = ...
    GetConstantVelocityFieldSetTime: Any = ...
    UpdateTransformParameters: Any = ...
    GetInverse: Any = ...
    IntegrateVelocityField: Any = ...
    SetCalculateNumberOfIntegrationStepsAutomatically: Any = ...
    GetCalculateNumberOfIntegrationStepsAutomatically: Any = ...
    CalculateNumberOfIntegrationStepsAutomaticallyOn: Any = ...
    CalculateNumberOfIntegrationStepsAutomaticallyOff: Any = ...
    SetLowerTimeBound: Any = ...
    GetLowerTimeBound: Any = ...
    SetUpperTimeBound: Any = ...
    GetUpperTimeBound: Any = ...
    SetNumberOfIntegrationSteps: Any = ...
    GetNumberOfIntegrationSteps: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConstantVelocityFieldTransformD2___New_orig__: Any
itkConstantVelocityFieldTransformD2_cast: Any

def itkConstantVelocityFieldTransformD3_New(): ...

class itkConstantVelocityFieldTransformD3(itk.itkDisplacementFieldTransformPython.itkDisplacementFieldTransformD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetConstantVelocityField: Any = ...
    GetModifiableConstantVelocityField: Any = ...
    GetConstantVelocityField: Any = ...
    SetConstantVelocityFieldInterpolator: Any = ...
    GetModifiableConstantVelocityFieldInterpolator: Any = ...
    GetConstantVelocityFieldInterpolator: Any = ...
    GetConstantVelocityFieldSetTime: Any = ...
    UpdateTransformParameters: Any = ...
    GetInverse: Any = ...
    IntegrateVelocityField: Any = ...
    SetCalculateNumberOfIntegrationStepsAutomatically: Any = ...
    GetCalculateNumberOfIntegrationStepsAutomatically: Any = ...
    CalculateNumberOfIntegrationStepsAutomaticallyOn: Any = ...
    CalculateNumberOfIntegrationStepsAutomaticallyOff: Any = ...
    SetLowerTimeBound: Any = ...
    GetLowerTimeBound: Any = ...
    SetUpperTimeBound: Any = ...
    GetUpperTimeBound: Any = ...
    SetNumberOfIntegrationSteps: Any = ...
    GetNumberOfIntegrationSteps: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConstantVelocityFieldTransformD3___New_orig__: Any
itkConstantVelocityFieldTransformD3_cast: Any
