import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkCyclicShiftImageFilterICF2ICF2_New(): ...

class itkCyclicShiftImageFilterICF2ICF2(itk.itkImageToImageFilterBPython.itkImageToImageFilterICF2ICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterICF2ICF2___New_orig__: Any
itkCyclicShiftImageFilterICF2ICF2_cast: Any

def itkCyclicShiftImageFilterICF3ICF3_New(): ...

class itkCyclicShiftImageFilterICF3ICF3(itk.itkImageToImageFilterBPython.itkImageToImageFilterICF3ICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterICF3ICF3___New_orig__: Any
itkCyclicShiftImageFilterICF3ICF3_cast: Any

def itkCyclicShiftImageFilterICVF22ICVF22_New(): ...

class itkCyclicShiftImageFilterICVF22ICVF22(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF22ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterICVF22ICVF22___New_orig__: Any
itkCyclicShiftImageFilterICVF22ICVF22_cast: Any

def itkCyclicShiftImageFilterICVF23ICVF23_New(): ...

class itkCyclicShiftImageFilterICVF23ICVF23(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF23ICVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterICVF23ICVF23___New_orig__: Any
itkCyclicShiftImageFilterICVF23ICVF23_cast: Any

def itkCyclicShiftImageFilterICVF32ICVF32_New(): ...

class itkCyclicShiftImageFilterICVF32ICVF32(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF32ICVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterICVF32ICVF32___New_orig__: Any
itkCyclicShiftImageFilterICVF32ICVF32_cast: Any

def itkCyclicShiftImageFilterICVF33ICVF33_New(): ...

class itkCyclicShiftImageFilterICVF33ICVF33(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF33ICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterICVF33ICVF33___New_orig__: Any
itkCyclicShiftImageFilterICVF33ICVF33_cast: Any

def itkCyclicShiftImageFilterICVF42ICVF42_New(): ...

class itkCyclicShiftImageFilterICVF42ICVF42(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF42ICVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterICVF42ICVF42___New_orig__: Any
itkCyclicShiftImageFilterICVF42ICVF42_cast: Any

def itkCyclicShiftImageFilterICVF43ICVF43_New(): ...

class itkCyclicShiftImageFilterICVF43ICVF43(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF43ICVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterICVF43ICVF43___New_orig__: Any
itkCyclicShiftImageFilterICVF43ICVF43_cast: Any

def itkCyclicShiftImageFilterIF2IF2_New(): ...

class itkCyclicShiftImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterIF2IF2___New_orig__: Any
itkCyclicShiftImageFilterIF2IF2_cast: Any

def itkCyclicShiftImageFilterIF3IF3_New(): ...

class itkCyclicShiftImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterIF3IF3___New_orig__: Any
itkCyclicShiftImageFilterIF3IF3_cast: Any

def itkCyclicShiftImageFilterIRGBAUC2IRGBAUC2_New(): ...

class itkCyclicShiftImageFilterIRGBAUC2IRGBAUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBAUC2IRGBAUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterIRGBAUC2IRGBAUC2___New_orig__: Any
itkCyclicShiftImageFilterIRGBAUC2IRGBAUC2_cast: Any

def itkCyclicShiftImageFilterIRGBAUC3IRGBAUC3_New(): ...

class itkCyclicShiftImageFilterIRGBAUC3IRGBAUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBAUC3IRGBAUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterIRGBAUC3IRGBAUC3___New_orig__: Any
itkCyclicShiftImageFilterIRGBAUC3IRGBAUC3_cast: Any

def itkCyclicShiftImageFilterIRGBUC2IRGBUC2_New(): ...

class itkCyclicShiftImageFilterIRGBUC2IRGBUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBUC2IRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterIRGBUC2IRGBUC2___New_orig__: Any
itkCyclicShiftImageFilterIRGBUC2IRGBUC2_cast: Any

def itkCyclicShiftImageFilterIRGBUC3IRGBUC3_New(): ...

class itkCyclicShiftImageFilterIRGBUC3IRGBUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBUC3IRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterIRGBUC3IRGBUC3___New_orig__: Any
itkCyclicShiftImageFilterIRGBUC3IRGBUC3_cast: Any

def itkCyclicShiftImageFilterISS2ISS2_New(): ...

class itkCyclicShiftImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterISS2ISS2___New_orig__: Any
itkCyclicShiftImageFilterISS2ISS2_cast: Any

def itkCyclicShiftImageFilterISS3ISS3_New(): ...

class itkCyclicShiftImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterISS3ISS3___New_orig__: Any
itkCyclicShiftImageFilterISS3ISS3_cast: Any

def itkCyclicShiftImageFilterIUC2IUC2_New(): ...

class itkCyclicShiftImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterIUC2IUC2___New_orig__: Any
itkCyclicShiftImageFilterIUC2IUC2_cast: Any

def itkCyclicShiftImageFilterIUC3IUC3_New(): ...

class itkCyclicShiftImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterIUC3IUC3___New_orig__: Any
itkCyclicShiftImageFilterIUC3IUC3_cast: Any

def itkCyclicShiftImageFilterIVF22IVF22_New(): ...

class itkCyclicShiftImageFilterIVF22IVF22(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF22IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterIVF22IVF22___New_orig__: Any
itkCyclicShiftImageFilterIVF22IVF22_cast: Any

def itkCyclicShiftImageFilterIVF23IVF23_New(): ...

class itkCyclicShiftImageFilterIVF23IVF23(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF23IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterIVF23IVF23___New_orig__: Any
itkCyclicShiftImageFilterIVF23IVF23_cast: Any

def itkCyclicShiftImageFilterIVF32IVF32_New(): ...

class itkCyclicShiftImageFilterIVF32IVF32(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF32IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterIVF32IVF32___New_orig__: Any
itkCyclicShiftImageFilterIVF32IVF32_cast: Any

def itkCyclicShiftImageFilterIVF33IVF33_New(): ...

class itkCyclicShiftImageFilterIVF33IVF33(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF33IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterIVF33IVF33___New_orig__: Any
itkCyclicShiftImageFilterIVF33IVF33_cast: Any

def itkCyclicShiftImageFilterIVF42IVF42_New(): ...

class itkCyclicShiftImageFilterIVF42IVF42(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF42IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterIVF42IVF42___New_orig__: Any
itkCyclicShiftImageFilterIVF42IVF42_cast: Any

def itkCyclicShiftImageFilterIVF43IVF43_New(): ...

class itkCyclicShiftImageFilterIVF43IVF43(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF43IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCyclicShiftImageFilterIVF43IVF43___New_orig__: Any
itkCyclicShiftImageFilterIVF43IVF43_cast: Any

def cyclic_shift_image_filter(*args: Any, **kwargs: Any): ...
def cyclic_shift_image_filter_init_docstring() -> None: ...
