import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkChangeLabelImageFilterISS2ISS2_Superclass_New(): ...

class itkChangeLabelImageFilterISS2ISS2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkChangeLabelImageFilterISS2ISS2_Superclass___New_orig__: Any
itkChangeLabelImageFilterISS2ISS2_Superclass_cast: Any

def itkChangeLabelImageFilterISS3ISS3_Superclass_New(): ...

class itkChangeLabelImageFilterISS3ISS3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkChangeLabelImageFilterISS3ISS3_Superclass___New_orig__: Any
itkChangeLabelImageFilterISS3ISS3_Superclass_cast: Any

def itkChangeLabelImageFilterIUC2IUC2_Superclass_New(): ...

class itkChangeLabelImageFilterIUC2IUC2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkChangeLabelImageFilterIUC2IUC2_Superclass___New_orig__: Any
itkChangeLabelImageFilterIUC2IUC2_Superclass_cast: Any

def itkChangeLabelImageFilterIUC3IUC3_Superclass_New(): ...

class itkChangeLabelImageFilterIUC3IUC3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkChangeLabelImageFilterIUC3IUC3_Superclass___New_orig__: Any
itkChangeLabelImageFilterIUC3IUC3_Superclass_cast: Any

def itkChangeLabelImageFilterISS2ISS2_New(): ...

class itkChangeLabelImageFilterISS2ISS2(itkChangeLabelImageFilterISS2ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetChange: Any = ...
    SetChangeMap: Any = ...
    ClearChangeMap: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    PixelTypeComparable: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkChangeLabelImageFilterISS2ISS2___New_orig__: Any
itkChangeLabelImageFilterISS2ISS2_cast: Any

def itkChangeLabelImageFilterISS3ISS3_New(): ...

class itkChangeLabelImageFilterISS3ISS3(itkChangeLabelImageFilterISS3ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetChange: Any = ...
    SetChangeMap: Any = ...
    ClearChangeMap: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    PixelTypeComparable: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkChangeLabelImageFilterISS3ISS3___New_orig__: Any
itkChangeLabelImageFilterISS3ISS3_cast: Any

def itkChangeLabelImageFilterIUC2IUC2_New(): ...

class itkChangeLabelImageFilterIUC2IUC2(itkChangeLabelImageFilterIUC2IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetChange: Any = ...
    SetChangeMap: Any = ...
    ClearChangeMap: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    PixelTypeComparable: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkChangeLabelImageFilterIUC2IUC2___New_orig__: Any
itkChangeLabelImageFilterIUC2IUC2_cast: Any

def itkChangeLabelImageFilterIUC3IUC3_New(): ...

class itkChangeLabelImageFilterIUC3IUC3(itkChangeLabelImageFilterIUC3IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetChange: Any = ...
    SetChangeMap: Any = ...
    ClearChangeMap: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    PixelTypeComparable: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkChangeLabelImageFilterIUC3IUC3___New_orig__: Any
itkChangeLabelImageFilterIUC3IUC3_cast: Any

def change_label_image_filter(*args: Any, **kwargs: Any): ...
def change_label_image_filter_init_docstring() -> None: ...
def unary_functor_image_filter(*args: Any, **kwargs: Any): ...
def unary_functor_image_filter_init_docstring() -> None: ...
