import itk.itkMatrixOffsetTransformBasePython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkCenteredEuler3DTransformD_New(): ...

class itkCenteredEuler3DTransformD(itk.itkEuler3DTransformPython.itkEuler3DTransformD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetInverse: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCenteredEuler3DTransformD___New_orig__: Any
itkCenteredEuler3DTransformD_cast: Any
