import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkConnectedThresholdImageFilterEnums:
    thisown: Any = ...
    Connectivity_FaceConnectivity: Any = ...
    Connectivity_FullConnectivity: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...

def itkConnectedThresholdImageFilterIF2IF2_New(): ...

class itkConnectedThresholdImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed: Any = ...
    AddSeed: Any = ...
    ClearSeeds: Any = ...
    GetSeeds: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetUpper: Any = ...
    SetLower: Any = ...
    SetUpperInput: Any = ...
    SetLowerInput: Any = ...
    GetUpper: Any = ...
    GetLower: Any = ...
    GetUpperInput: Any = ...
    GetLowerInput: Any = ...
    OutputEqualityComparableCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    SetConnectivity: Any = ...
    GetConnectivity: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConnectedThresholdImageFilterIF2IF2___New_orig__: Any
itkConnectedThresholdImageFilterIF2IF2_cast: Any

def itkConnectedThresholdImageFilterIF3IF3_New(): ...

class itkConnectedThresholdImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed: Any = ...
    AddSeed: Any = ...
    ClearSeeds: Any = ...
    GetSeeds: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetUpper: Any = ...
    SetLower: Any = ...
    SetUpperInput: Any = ...
    SetLowerInput: Any = ...
    GetUpper: Any = ...
    GetLower: Any = ...
    GetUpperInput: Any = ...
    GetLowerInput: Any = ...
    OutputEqualityComparableCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    SetConnectivity: Any = ...
    GetConnectivity: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConnectedThresholdImageFilterIF3IF3___New_orig__: Any
itkConnectedThresholdImageFilterIF3IF3_cast: Any

def itkConnectedThresholdImageFilterISS2ISS2_New(): ...

class itkConnectedThresholdImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed: Any = ...
    AddSeed: Any = ...
    ClearSeeds: Any = ...
    GetSeeds: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetUpper: Any = ...
    SetLower: Any = ...
    SetUpperInput: Any = ...
    SetLowerInput: Any = ...
    GetUpper: Any = ...
    GetLower: Any = ...
    GetUpperInput: Any = ...
    GetLowerInput: Any = ...
    OutputEqualityComparableCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    SetConnectivity: Any = ...
    GetConnectivity: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConnectedThresholdImageFilterISS2ISS2___New_orig__: Any
itkConnectedThresholdImageFilterISS2ISS2_cast: Any

def itkConnectedThresholdImageFilterISS3ISS3_New(): ...

class itkConnectedThresholdImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed: Any = ...
    AddSeed: Any = ...
    ClearSeeds: Any = ...
    GetSeeds: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetUpper: Any = ...
    SetLower: Any = ...
    SetUpperInput: Any = ...
    SetLowerInput: Any = ...
    GetUpper: Any = ...
    GetLower: Any = ...
    GetUpperInput: Any = ...
    GetLowerInput: Any = ...
    OutputEqualityComparableCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    SetConnectivity: Any = ...
    GetConnectivity: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConnectedThresholdImageFilterISS3ISS3___New_orig__: Any
itkConnectedThresholdImageFilterISS3ISS3_cast: Any

def itkConnectedThresholdImageFilterIUC2IUC2_New(): ...

class itkConnectedThresholdImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed: Any = ...
    AddSeed: Any = ...
    ClearSeeds: Any = ...
    GetSeeds: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetUpper: Any = ...
    SetLower: Any = ...
    SetUpperInput: Any = ...
    SetLowerInput: Any = ...
    GetUpper: Any = ...
    GetLower: Any = ...
    GetUpperInput: Any = ...
    GetLowerInput: Any = ...
    OutputEqualityComparableCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    SetConnectivity: Any = ...
    GetConnectivity: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConnectedThresholdImageFilterIUC2IUC2___New_orig__: Any
itkConnectedThresholdImageFilterIUC2IUC2_cast: Any

def itkConnectedThresholdImageFilterIUC3IUC3_New(): ...

class itkConnectedThresholdImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed: Any = ...
    AddSeed: Any = ...
    ClearSeeds: Any = ...
    GetSeeds: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetUpper: Any = ...
    SetLower: Any = ...
    SetUpperInput: Any = ...
    SetLowerInput: Any = ...
    GetUpper: Any = ...
    GetLower: Any = ...
    GetUpperInput: Any = ...
    GetLowerInput: Any = ...
    OutputEqualityComparableCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    SetConnectivity: Any = ...
    GetConnectivity: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConnectedThresholdImageFilterIUC3IUC3___New_orig__: Any
itkConnectedThresholdImageFilterIUC3IUC3_cast: Any

def connected_threshold_image_filter(*args: Any, **kwargs: Any): ...
def connected_threshold_image_filter_init_docstring() -> None: ...
