import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkConvolutionImageFilterBaseEnums:
    thisown: Any = ...
    ConvolutionImageFilterOutputRegion_SAME: Any = ...
    ConvolutionImageFilterOutputRegion_VALID: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...

class itkConvolutionImageFilterBaseIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetBoundaryCondition: Any = ...
    GetBoundaryCondition: Any = ...
    SetKernelImage: Any = ...
    GetKernelImage: Any = ...
    SetNormalize: Any = ...
    GetNormalize: Any = ...
    NormalizeOn: Any = ...
    NormalizeOff: Any = ...
    SetOutputRegionMode: Any = ...
    GetOutputRegionMode: Any = ...
    SetOutputRegionModeToSame: Any = ...
    SetOutputRegionModeToValid: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkConvolutionImageFilterBaseIF2IF2_cast: Any

class itkConvolutionImageFilterBaseIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetBoundaryCondition: Any = ...
    GetBoundaryCondition: Any = ...
    SetKernelImage: Any = ...
    GetKernelImage: Any = ...
    SetNormalize: Any = ...
    GetNormalize: Any = ...
    NormalizeOn: Any = ...
    NormalizeOff: Any = ...
    SetOutputRegionMode: Any = ...
    GetOutputRegionMode: Any = ...
    SetOutputRegionModeToSame: Any = ...
    SetOutputRegionModeToValid: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkConvolutionImageFilterBaseIF3IF3_cast: Any

class itkConvolutionImageFilterBaseISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetBoundaryCondition: Any = ...
    GetBoundaryCondition: Any = ...
    SetKernelImage: Any = ...
    GetKernelImage: Any = ...
    SetNormalize: Any = ...
    GetNormalize: Any = ...
    NormalizeOn: Any = ...
    NormalizeOff: Any = ...
    SetOutputRegionMode: Any = ...
    GetOutputRegionMode: Any = ...
    SetOutputRegionModeToSame: Any = ...
    SetOutputRegionModeToValid: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkConvolutionImageFilterBaseISS2ISS2_cast: Any

class itkConvolutionImageFilterBaseISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetBoundaryCondition: Any = ...
    GetBoundaryCondition: Any = ...
    SetKernelImage: Any = ...
    GetKernelImage: Any = ...
    SetNormalize: Any = ...
    GetNormalize: Any = ...
    NormalizeOn: Any = ...
    NormalizeOff: Any = ...
    SetOutputRegionMode: Any = ...
    GetOutputRegionMode: Any = ...
    SetOutputRegionModeToSame: Any = ...
    SetOutputRegionModeToValid: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkConvolutionImageFilterBaseISS3ISS3_cast: Any

class itkConvolutionImageFilterBaseIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetBoundaryCondition: Any = ...
    GetBoundaryCondition: Any = ...
    SetKernelImage: Any = ...
    GetKernelImage: Any = ...
    SetNormalize: Any = ...
    GetNormalize: Any = ...
    NormalizeOn: Any = ...
    NormalizeOff: Any = ...
    SetOutputRegionMode: Any = ...
    GetOutputRegionMode: Any = ...
    SetOutputRegionModeToSame: Any = ...
    SetOutputRegionModeToValid: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkConvolutionImageFilterBaseIUC2IUC2_cast: Any

class itkConvolutionImageFilterBaseIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetBoundaryCondition: Any = ...
    GetBoundaryCondition: Any = ...
    SetKernelImage: Any = ...
    GetKernelImage: Any = ...
    SetNormalize: Any = ...
    GetNormalize: Any = ...
    NormalizeOn: Any = ...
    NormalizeOff: Any = ...
    SetOutputRegionMode: Any = ...
    GetOutputRegionMode: Any = ...
    SetOutputRegionModeToSame: Any = ...
    SetOutputRegionModeToValid: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkConvolutionImageFilterBaseIUC3IUC3_cast: Any

def convolution_image_filter_base(*args: Any, **kwargs: Any): ...
def convolution_image_filter_base_init_docstring() -> None: ...
