import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkCurvesLevelSetImageFilterIF2IF2F_New(): ...

class itkCurvesLevelSetImageFilterIF2IF2F(itk.itkSegmentationLevelSetImageFilterPython.itkSegmentationLevelSetImageFilterIF2IF2F):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDerivativeSigma: Any = ...
    GetDerivativeSigma: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCurvesLevelSetImageFilterIF2IF2F___New_orig__: Any
itkCurvesLevelSetImageFilterIF2IF2F_cast: Any

def itkCurvesLevelSetImageFilterIF3IF3F_New(): ...

class itkCurvesLevelSetImageFilterIF3IF3F(itk.itkSegmentationLevelSetImageFilterPython.itkSegmentationLevelSetImageFilterIF3IF3F):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDerivativeSigma: Any = ...
    GetDerivativeSigma: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCurvesLevelSetImageFilterIF3IF3F___New_orig__: Any
itkCurvesLevelSetImageFilterIF3IF3F_cast: Any

def curves_level_set_image_filter(*args: Any, **kwargs: Any): ...
def curves_level_set_image_filter_init_docstring() -> None: ...
