import itk.itkInPlaceImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkComplexToModulusImageFilterICF2IF2_New(): ...

class itkComplexToModulusImageFilterICF2IF2(itk.itkUnaryGeneratorImageFilterPython.itkUnaryGeneratorImageFilterICF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputMultiplyOperatorCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkComplexToModulusImageFilterICF2IF2___New_orig__: Any
itkComplexToModulusImageFilterICF2IF2_cast: Any

def itkComplexToModulusImageFilterICF3IF3_New(): ...

class itkComplexToModulusImageFilterICF3IF3(itk.itkUnaryGeneratorImageFilterPython.itkUnaryGeneratorImageFilterICF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputMultiplyOperatorCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkComplexToModulusImageFilterICF3IF3___New_orig__: Any
itkComplexToModulusImageFilterICF3IF3_cast: Any

def complex_to_modulus_image_filter(*args: Any, **kwargs: Any): ...
def complex_to_modulus_image_filter_init_docstring() -> None: ...
