import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkCurvatureAnisotropicDiffusionImageFilterIF2IF2_New(): ...

class itkCurvatureAnisotropicDiffusionImageFilterIF2IF2(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCurvatureAnisotropicDiffusionImageFilterIF2IF2___New_orig__: Any
itkCurvatureAnisotropicDiffusionImageFilterIF2IF2_cast: Any

def itkCurvatureAnisotropicDiffusionImageFilterIF3IF3_New(): ...

class itkCurvatureAnisotropicDiffusionImageFilterIF3IF3(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCurvatureAnisotropicDiffusionImageFilterIF3IF3___New_orig__: Any
itkCurvatureAnisotropicDiffusionImageFilterIF3IF3_cast: Any

def curvature_anisotropic_diffusion_image_filter(*args: Any, **kwargs: Any): ...
def curvature_anisotropic_diffusion_image_filter_init_docstring() -> None: ...
