import itk.itkMeshSourcePython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkConnectedRegionsMeshFilterMF2MF2_New(): ...

class itkConnectedRegionsMeshFilterMF2MF2(itk.itkMeshToMeshFilterPython.itkMeshToMeshFilterMF2MF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PointSeededRegions: Any = ...
    CellSeededRegions: Any = ...
    SpecifiedRegions: Any = ...
    LargestRegion: Any = ...
    AllRegions: Any = ...
    ClosestPointRegion: Any = ...
    SetExtractionMode: Any = ...
    GetExtractionMode: Any = ...
    SetExtractionModeToPointSeededRegions: Any = ...
    SetExtractionModeToCellSeededRegions: Any = ...
    SetExtractionModeToSpecifiedRegions: Any = ...
    SetExtractionModeToLargestRegion: Any = ...
    SetExtractionModeToAllRegions: Any = ...
    SetExtractionModeToClosestPointRegion: Any = ...
    InitializeSeedList: Any = ...
    AddSeed: Any = ...
    DeleteSeed: Any = ...
    InitializeSpecifiedRegionList: Any = ...
    AddSpecifiedRegion: Any = ...
    DeleteSpecifiedRegion: Any = ...
    SetClosestPoint: Any = ...
    GetClosestPoint: Any = ...
    GetNumberOfExtractedRegions: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConnectedRegionsMeshFilterMF2MF2___New_orig__: Any
itkConnectedRegionsMeshFilterMF2MF2_cast: Any

def itkConnectedRegionsMeshFilterMF3MF3_New(): ...

class itkConnectedRegionsMeshFilterMF3MF3(itk.itkMeshToMeshFilterPython.itkMeshToMeshFilterMF3MF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PointSeededRegions: Any = ...
    CellSeededRegions: Any = ...
    SpecifiedRegions: Any = ...
    LargestRegion: Any = ...
    AllRegions: Any = ...
    ClosestPointRegion: Any = ...
    SetExtractionMode: Any = ...
    GetExtractionMode: Any = ...
    SetExtractionModeToPointSeededRegions: Any = ...
    SetExtractionModeToCellSeededRegions: Any = ...
    SetExtractionModeToSpecifiedRegions: Any = ...
    SetExtractionModeToLargestRegion: Any = ...
    SetExtractionModeToAllRegions: Any = ...
    SetExtractionModeToClosestPointRegion: Any = ...
    InitializeSeedList: Any = ...
    AddSeed: Any = ...
    DeleteSeed: Any = ...
    InitializeSpecifiedRegionList: Any = ...
    AddSpecifiedRegion: Any = ...
    DeleteSpecifiedRegion: Any = ...
    SetClosestPoint: Any = ...
    GetClosestPoint: Any = ...
    GetNumberOfExtractedRegions: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConnectedRegionsMeshFilterMF3MF3___New_orig__: Any
itkConnectedRegionsMeshFilterMF3MF3_cast: Any

def connected_regions_mesh_filter(*args: Any, **kwargs: Any): ...
def connected_regions_mesh_filter_init_docstring() -> None: ...
