import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkChangeInformationImageFilterIF2_New(): ...

class itkChangeInformationImageFilterIF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReferenceImage: Any = ...
    GetModifiableReferenceImage: Any = ...
    GetReferenceImage: Any = ...
    SetUseReferenceImage: Any = ...
    UseReferenceImageOn: Any = ...
    UseReferenceImageOff: Any = ...
    GetUseReferenceImage: Any = ...
    SetOutputSpacing: Any = ...
    GetOutputSpacing: Any = ...
    SetOutputOrigin: Any = ...
    GetOutputOrigin: Any = ...
    SetOutputDirection: Any = ...
    GetOutputDirection: Any = ...
    GetOutputOffset: Any = ...
    SetOutputOffset: Any = ...
    ChangeAll: Any = ...
    ChangeNone: Any = ...
    SetChangeSpacing: Any = ...
    ChangeSpacingOn: Any = ...
    ChangeSpacingOff: Any = ...
    GetChangeSpacing: Any = ...
    SetChangeOrigin: Any = ...
    ChangeOriginOn: Any = ...
    ChangeOriginOff: Any = ...
    GetChangeOrigin: Any = ...
    SetChangeDirection: Any = ...
    ChangeDirectionOn: Any = ...
    ChangeDirectionOff: Any = ...
    GetChangeDirection: Any = ...
    SetChangeRegion: Any = ...
    ChangeRegionOn: Any = ...
    ChangeRegionOff: Any = ...
    GetChangeRegion: Any = ...
    SetCenterImage: Any = ...
    CenterImageOn: Any = ...
    CenterImageOff: Any = ...
    GetCenterImage: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkChangeInformationImageFilterIF2___New_orig__: Any
itkChangeInformationImageFilterIF2_cast: Any

def itkChangeInformationImageFilterIF3_New(): ...

class itkChangeInformationImageFilterIF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReferenceImage: Any = ...
    GetModifiableReferenceImage: Any = ...
    GetReferenceImage: Any = ...
    SetUseReferenceImage: Any = ...
    UseReferenceImageOn: Any = ...
    UseReferenceImageOff: Any = ...
    GetUseReferenceImage: Any = ...
    SetOutputSpacing: Any = ...
    GetOutputSpacing: Any = ...
    SetOutputOrigin: Any = ...
    GetOutputOrigin: Any = ...
    SetOutputDirection: Any = ...
    GetOutputDirection: Any = ...
    GetOutputOffset: Any = ...
    SetOutputOffset: Any = ...
    ChangeAll: Any = ...
    ChangeNone: Any = ...
    SetChangeSpacing: Any = ...
    ChangeSpacingOn: Any = ...
    ChangeSpacingOff: Any = ...
    GetChangeSpacing: Any = ...
    SetChangeOrigin: Any = ...
    ChangeOriginOn: Any = ...
    ChangeOriginOff: Any = ...
    GetChangeOrigin: Any = ...
    SetChangeDirection: Any = ...
    ChangeDirectionOn: Any = ...
    ChangeDirectionOff: Any = ...
    GetChangeDirection: Any = ...
    SetChangeRegion: Any = ...
    ChangeRegionOn: Any = ...
    ChangeRegionOff: Any = ...
    GetChangeRegion: Any = ...
    SetCenterImage: Any = ...
    CenterImageOn: Any = ...
    CenterImageOff: Any = ...
    GetCenterImage: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkChangeInformationImageFilterIF3___New_orig__: Any
itkChangeInformationImageFilterIF3_cast: Any

def itkChangeInformationImageFilterISS2_New(): ...

class itkChangeInformationImageFilterISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReferenceImage: Any = ...
    GetModifiableReferenceImage: Any = ...
    GetReferenceImage: Any = ...
    SetUseReferenceImage: Any = ...
    UseReferenceImageOn: Any = ...
    UseReferenceImageOff: Any = ...
    GetUseReferenceImage: Any = ...
    SetOutputSpacing: Any = ...
    GetOutputSpacing: Any = ...
    SetOutputOrigin: Any = ...
    GetOutputOrigin: Any = ...
    SetOutputDirection: Any = ...
    GetOutputDirection: Any = ...
    GetOutputOffset: Any = ...
    SetOutputOffset: Any = ...
    ChangeAll: Any = ...
    ChangeNone: Any = ...
    SetChangeSpacing: Any = ...
    ChangeSpacingOn: Any = ...
    ChangeSpacingOff: Any = ...
    GetChangeSpacing: Any = ...
    SetChangeOrigin: Any = ...
    ChangeOriginOn: Any = ...
    ChangeOriginOff: Any = ...
    GetChangeOrigin: Any = ...
    SetChangeDirection: Any = ...
    ChangeDirectionOn: Any = ...
    ChangeDirectionOff: Any = ...
    GetChangeDirection: Any = ...
    SetChangeRegion: Any = ...
    ChangeRegionOn: Any = ...
    ChangeRegionOff: Any = ...
    GetChangeRegion: Any = ...
    SetCenterImage: Any = ...
    CenterImageOn: Any = ...
    CenterImageOff: Any = ...
    GetCenterImage: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkChangeInformationImageFilterISS2___New_orig__: Any
itkChangeInformationImageFilterISS2_cast: Any

def itkChangeInformationImageFilterISS3_New(): ...

class itkChangeInformationImageFilterISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReferenceImage: Any = ...
    GetModifiableReferenceImage: Any = ...
    GetReferenceImage: Any = ...
    SetUseReferenceImage: Any = ...
    UseReferenceImageOn: Any = ...
    UseReferenceImageOff: Any = ...
    GetUseReferenceImage: Any = ...
    SetOutputSpacing: Any = ...
    GetOutputSpacing: Any = ...
    SetOutputOrigin: Any = ...
    GetOutputOrigin: Any = ...
    SetOutputDirection: Any = ...
    GetOutputDirection: Any = ...
    GetOutputOffset: Any = ...
    SetOutputOffset: Any = ...
    ChangeAll: Any = ...
    ChangeNone: Any = ...
    SetChangeSpacing: Any = ...
    ChangeSpacingOn: Any = ...
    ChangeSpacingOff: Any = ...
    GetChangeSpacing: Any = ...
    SetChangeOrigin: Any = ...
    ChangeOriginOn: Any = ...
    ChangeOriginOff: Any = ...
    GetChangeOrigin: Any = ...
    SetChangeDirection: Any = ...
    ChangeDirectionOn: Any = ...
    ChangeDirectionOff: Any = ...
    GetChangeDirection: Any = ...
    SetChangeRegion: Any = ...
    ChangeRegionOn: Any = ...
    ChangeRegionOff: Any = ...
    GetChangeRegion: Any = ...
    SetCenterImage: Any = ...
    CenterImageOn: Any = ...
    CenterImageOff: Any = ...
    GetCenterImage: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkChangeInformationImageFilterISS3___New_orig__: Any
itkChangeInformationImageFilterISS3_cast: Any

def itkChangeInformationImageFilterIUC2_New(): ...

class itkChangeInformationImageFilterIUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReferenceImage: Any = ...
    GetModifiableReferenceImage: Any = ...
    GetReferenceImage: Any = ...
    SetUseReferenceImage: Any = ...
    UseReferenceImageOn: Any = ...
    UseReferenceImageOff: Any = ...
    GetUseReferenceImage: Any = ...
    SetOutputSpacing: Any = ...
    GetOutputSpacing: Any = ...
    SetOutputOrigin: Any = ...
    GetOutputOrigin: Any = ...
    SetOutputDirection: Any = ...
    GetOutputDirection: Any = ...
    GetOutputOffset: Any = ...
    SetOutputOffset: Any = ...
    ChangeAll: Any = ...
    ChangeNone: Any = ...
    SetChangeSpacing: Any = ...
    ChangeSpacingOn: Any = ...
    ChangeSpacingOff: Any = ...
    GetChangeSpacing: Any = ...
    SetChangeOrigin: Any = ...
    ChangeOriginOn: Any = ...
    ChangeOriginOff: Any = ...
    GetChangeOrigin: Any = ...
    SetChangeDirection: Any = ...
    ChangeDirectionOn: Any = ...
    ChangeDirectionOff: Any = ...
    GetChangeDirection: Any = ...
    SetChangeRegion: Any = ...
    ChangeRegionOn: Any = ...
    ChangeRegionOff: Any = ...
    GetChangeRegion: Any = ...
    SetCenterImage: Any = ...
    CenterImageOn: Any = ...
    CenterImageOff: Any = ...
    GetCenterImage: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkChangeInformationImageFilterIUC2___New_orig__: Any
itkChangeInformationImageFilterIUC2_cast: Any

def itkChangeInformationImageFilterIUC3_New(): ...

class itkChangeInformationImageFilterIUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReferenceImage: Any = ...
    GetModifiableReferenceImage: Any = ...
    GetReferenceImage: Any = ...
    SetUseReferenceImage: Any = ...
    UseReferenceImageOn: Any = ...
    UseReferenceImageOff: Any = ...
    GetUseReferenceImage: Any = ...
    SetOutputSpacing: Any = ...
    GetOutputSpacing: Any = ...
    SetOutputOrigin: Any = ...
    GetOutputOrigin: Any = ...
    SetOutputDirection: Any = ...
    GetOutputDirection: Any = ...
    GetOutputOffset: Any = ...
    SetOutputOffset: Any = ...
    ChangeAll: Any = ...
    ChangeNone: Any = ...
    SetChangeSpacing: Any = ...
    ChangeSpacingOn: Any = ...
    ChangeSpacingOff: Any = ...
    GetChangeSpacing: Any = ...
    SetChangeOrigin: Any = ...
    ChangeOriginOn: Any = ...
    ChangeOriginOff: Any = ...
    GetChangeOrigin: Any = ...
    SetChangeDirection: Any = ...
    ChangeDirectionOn: Any = ...
    ChangeDirectionOff: Any = ...
    GetChangeDirection: Any = ...
    SetChangeRegion: Any = ...
    ChangeRegionOn: Any = ...
    ChangeRegionOff: Any = ...
    GetChangeRegion: Any = ...
    SetCenterImage: Any = ...
    CenterImageOn: Any = ...
    CenterImageOff: Any = ...
    GetCenterImage: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkChangeInformationImageFilterIUC3___New_orig__: Any
itkChangeInformationImageFilterIUC3_cast: Any

def change_information_image_filter(*args: Any, **kwargs: Any): ...
def change_information_image_filter_init_docstring() -> None: ...
