import itk.pyBasePython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkCostFunctionTemplateD(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetNumberOfParameters: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkCostFunctionTemplateD_cast: Any

class itkCostFunctionTemplateF(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetNumberOfParameters: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkCostFunctionTemplateF_cast: Any
