import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkConfidenceConnectedImageFilterIF2ISS2_New(): ...

class itkConfidenceConnectedImageFilterIF2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed: Any = ...
    ClearSeeds: Any = ...
    AddSeed: Any = ...
    SetMultiplier: Any = ...
    GetMultiplier: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetInitialNeighborhoodRadius: Any = ...
    GetInitialNeighborhoodRadius: Any = ...
    GetMean: Any = ...
    GetVariance: Any = ...
    GetSeeds: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConfidenceConnectedImageFilterIF2ISS2___New_orig__: Any
itkConfidenceConnectedImageFilterIF2ISS2_cast: Any

def itkConfidenceConnectedImageFilterIF2IUC2_New(): ...

class itkConfidenceConnectedImageFilterIF2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed: Any = ...
    ClearSeeds: Any = ...
    AddSeed: Any = ...
    SetMultiplier: Any = ...
    GetMultiplier: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetInitialNeighborhoodRadius: Any = ...
    GetInitialNeighborhoodRadius: Any = ...
    GetMean: Any = ...
    GetVariance: Any = ...
    GetSeeds: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConfidenceConnectedImageFilterIF2IUC2___New_orig__: Any
itkConfidenceConnectedImageFilterIF2IUC2_cast: Any

def itkConfidenceConnectedImageFilterIF3ISS3_New(): ...

class itkConfidenceConnectedImageFilterIF3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed: Any = ...
    ClearSeeds: Any = ...
    AddSeed: Any = ...
    SetMultiplier: Any = ...
    GetMultiplier: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetInitialNeighborhoodRadius: Any = ...
    GetInitialNeighborhoodRadius: Any = ...
    GetMean: Any = ...
    GetVariance: Any = ...
    GetSeeds: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConfidenceConnectedImageFilterIF3ISS3___New_orig__: Any
itkConfidenceConnectedImageFilterIF3ISS3_cast: Any

def itkConfidenceConnectedImageFilterIF3IUC3_New(): ...

class itkConfidenceConnectedImageFilterIF3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed: Any = ...
    ClearSeeds: Any = ...
    AddSeed: Any = ...
    SetMultiplier: Any = ...
    GetMultiplier: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetInitialNeighborhoodRadius: Any = ...
    GetInitialNeighborhoodRadius: Any = ...
    GetMean: Any = ...
    GetVariance: Any = ...
    GetSeeds: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConfidenceConnectedImageFilterIF3IUC3___New_orig__: Any
itkConfidenceConnectedImageFilterIF3IUC3_cast: Any

def itkConfidenceConnectedImageFilterISS2ISS2_New(): ...

class itkConfidenceConnectedImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed: Any = ...
    ClearSeeds: Any = ...
    AddSeed: Any = ...
    SetMultiplier: Any = ...
    GetMultiplier: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetInitialNeighborhoodRadius: Any = ...
    GetInitialNeighborhoodRadius: Any = ...
    GetMean: Any = ...
    GetVariance: Any = ...
    GetSeeds: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConfidenceConnectedImageFilterISS2ISS2___New_orig__: Any
itkConfidenceConnectedImageFilterISS2ISS2_cast: Any

def itkConfidenceConnectedImageFilterISS2IUC2_New(): ...

class itkConfidenceConnectedImageFilterISS2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed: Any = ...
    ClearSeeds: Any = ...
    AddSeed: Any = ...
    SetMultiplier: Any = ...
    GetMultiplier: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetInitialNeighborhoodRadius: Any = ...
    GetInitialNeighborhoodRadius: Any = ...
    GetMean: Any = ...
    GetVariance: Any = ...
    GetSeeds: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConfidenceConnectedImageFilterISS2IUC2___New_orig__: Any
itkConfidenceConnectedImageFilterISS2IUC2_cast: Any

def itkConfidenceConnectedImageFilterISS3ISS3_New(): ...

class itkConfidenceConnectedImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed: Any = ...
    ClearSeeds: Any = ...
    AddSeed: Any = ...
    SetMultiplier: Any = ...
    GetMultiplier: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetInitialNeighborhoodRadius: Any = ...
    GetInitialNeighborhoodRadius: Any = ...
    GetMean: Any = ...
    GetVariance: Any = ...
    GetSeeds: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConfidenceConnectedImageFilterISS3ISS3___New_orig__: Any
itkConfidenceConnectedImageFilterISS3ISS3_cast: Any

def itkConfidenceConnectedImageFilterISS3IUC3_New(): ...

class itkConfidenceConnectedImageFilterISS3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed: Any = ...
    ClearSeeds: Any = ...
    AddSeed: Any = ...
    SetMultiplier: Any = ...
    GetMultiplier: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetInitialNeighborhoodRadius: Any = ...
    GetInitialNeighborhoodRadius: Any = ...
    GetMean: Any = ...
    GetVariance: Any = ...
    GetSeeds: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConfidenceConnectedImageFilterISS3IUC3___New_orig__: Any
itkConfidenceConnectedImageFilterISS3IUC3_cast: Any

def itkConfidenceConnectedImageFilterIUC2ISS2_New(): ...

class itkConfidenceConnectedImageFilterIUC2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed: Any = ...
    ClearSeeds: Any = ...
    AddSeed: Any = ...
    SetMultiplier: Any = ...
    GetMultiplier: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetInitialNeighborhoodRadius: Any = ...
    GetInitialNeighborhoodRadius: Any = ...
    GetMean: Any = ...
    GetVariance: Any = ...
    GetSeeds: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConfidenceConnectedImageFilterIUC2ISS2___New_orig__: Any
itkConfidenceConnectedImageFilterIUC2ISS2_cast: Any

def itkConfidenceConnectedImageFilterIUC2IUC2_New(): ...

class itkConfidenceConnectedImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed: Any = ...
    ClearSeeds: Any = ...
    AddSeed: Any = ...
    SetMultiplier: Any = ...
    GetMultiplier: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetInitialNeighborhoodRadius: Any = ...
    GetInitialNeighborhoodRadius: Any = ...
    GetMean: Any = ...
    GetVariance: Any = ...
    GetSeeds: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConfidenceConnectedImageFilterIUC2IUC2___New_orig__: Any
itkConfidenceConnectedImageFilterIUC2IUC2_cast: Any

def itkConfidenceConnectedImageFilterIUC3ISS3_New(): ...

class itkConfidenceConnectedImageFilterIUC3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed: Any = ...
    ClearSeeds: Any = ...
    AddSeed: Any = ...
    SetMultiplier: Any = ...
    GetMultiplier: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetInitialNeighborhoodRadius: Any = ...
    GetInitialNeighborhoodRadius: Any = ...
    GetMean: Any = ...
    GetVariance: Any = ...
    GetSeeds: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConfidenceConnectedImageFilterIUC3ISS3___New_orig__: Any
itkConfidenceConnectedImageFilterIUC3ISS3_cast: Any

def itkConfidenceConnectedImageFilterIUC3IUC3_New(): ...

class itkConfidenceConnectedImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed: Any = ...
    ClearSeeds: Any = ...
    AddSeed: Any = ...
    SetMultiplier: Any = ...
    GetMultiplier: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetInitialNeighborhoodRadius: Any = ...
    GetInitialNeighborhoodRadius: Any = ...
    GetMean: Any = ...
    GetVariance: Any = ...
    GetSeeds: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConfidenceConnectedImageFilterIUC3IUC3___New_orig__: Any
itkConfidenceConnectedImageFilterIUC3IUC3_cast: Any

def confidence_connected_image_filter(*args: Any, **kwargs: Any): ...
def confidence_connected_image_filter_init_docstring() -> None: ...
