import itk.itkMatrixOffsetTransformBasePython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkCenteredSimilarity2DTransformD_New(): ...

class itkCenteredSimilarity2DTransformD(itk.itkSimilarity2DTransformPython.itkSimilarity2DTransformD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CloneInverseTo: Any = ...
    GetInverse: Any = ...
    CloneTo: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCenteredSimilarity2DTransformD___New_orig__: Any
itkCenteredSimilarity2DTransformD_cast: Any
