import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkCropLabelMapFilterLM2_New(): ...

class itkCropLabelMapFilterLM2(itk.itkChangeRegionLabelMapFilterPython.itkChangeRegionLabelMapFilterLM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetUpperBoundaryCropSize: Any = ...
    GetUpperBoundaryCropSize: Any = ...
    SetLowerBoundaryCropSize: Any = ...
    GetLowerBoundaryCropSize: Any = ...
    SetCropSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCropLabelMapFilterLM2___New_orig__: Any
itkCropLabelMapFilterLM2_cast: Any

def itkCropLabelMapFilterLM3_New(): ...

class itkCropLabelMapFilterLM3(itk.itkChangeRegionLabelMapFilterPython.itkChangeRegionLabelMapFilterLM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetUpperBoundaryCropSize: Any = ...
    GetUpperBoundaryCropSize: Any = ...
    SetLowerBoundaryCropSize: Any = ...
    GetLowerBoundaryCropSize: Any = ...
    SetCropSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCropLabelMapFilterLM3___New_orig__: Any
itkCropLabelMapFilterLM3_cast: Any

def crop_label_map_filter(*args: Any, **kwargs: Any): ...
def crop_label_map_filter_init_docstring() -> None: ...
