import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkChangeRegionLabelMapFilterLM2_New(): ...

class itkChangeRegionLabelMapFilterLM2(itk.itkInPlaceLabelMapFilterPython.itkInPlaceLabelMapFilterLM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetRegion: Any = ...
    GetRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkChangeRegionLabelMapFilterLM2___New_orig__: Any
itkChangeRegionLabelMapFilterLM2_cast: Any

def itkChangeRegionLabelMapFilterLM3_New(): ...

class itkChangeRegionLabelMapFilterLM3(itk.itkInPlaceLabelMapFilterPython.itkInPlaceLabelMapFilterLM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetRegion: Any = ...
    GetRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkChangeRegionLabelMapFilterLM3___New_orig__: Any
itkChangeRegionLabelMapFilterLM3_cast: Any

def change_region_label_map_filter(*args: Any, **kwargs: Any): ...
def change_region_label_map_filter_init_docstring() -> None: ...
