import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkClampImageFilterIF2IF2_Superclass_New(): ...

class itkClampImageFilterIF2IF2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIF2IF2_Superclass___New_orig__: Any
itkClampImageFilterIF2IF2_Superclass_cast: Any

def itkClampImageFilterIF2ISS2_Superclass_New(): ...

class itkClampImageFilterIF2ISS2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIF2ISS2_Superclass___New_orig__: Any
itkClampImageFilterIF2ISS2_Superclass_cast: Any

def itkClampImageFilterIF2IUC2_Superclass_New(): ...

class itkClampImageFilterIF2IUC2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIF2IUC2_Superclass___New_orig__: Any
itkClampImageFilterIF2IUC2_Superclass_cast: Any

def itkClampImageFilterIF3IF3_Superclass_New(): ...

class itkClampImageFilterIF3IF3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIF3IF3_Superclass___New_orig__: Any
itkClampImageFilterIF3IF3_Superclass_cast: Any

def itkClampImageFilterIF3ISS3_Superclass_New(): ...

class itkClampImageFilterIF3ISS3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIF3ISS3_Superclass___New_orig__: Any
itkClampImageFilterIF3ISS3_Superclass_cast: Any

def itkClampImageFilterIF3IUC3_Superclass_New(): ...

class itkClampImageFilterIF3IUC3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIF3IUC3_Superclass___New_orig__: Any
itkClampImageFilterIF3IUC3_Superclass_cast: Any

def itkClampImageFilterISS2IF2_Superclass_New(): ...

class itkClampImageFilterISS2IF2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterISS2IF2_Superclass___New_orig__: Any
itkClampImageFilterISS2IF2_Superclass_cast: Any

def itkClampImageFilterISS2ISS2_Superclass_New(): ...

class itkClampImageFilterISS2ISS2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterISS2ISS2_Superclass___New_orig__: Any
itkClampImageFilterISS2ISS2_Superclass_cast: Any

def itkClampImageFilterISS2IUC2_Superclass_New(): ...

class itkClampImageFilterISS2IUC2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterISS2IUC2_Superclass___New_orig__: Any
itkClampImageFilterISS2IUC2_Superclass_cast: Any

def itkClampImageFilterISS3IF3_Superclass_New(): ...

class itkClampImageFilterISS3IF3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterISS3IF3_Superclass___New_orig__: Any
itkClampImageFilterISS3IF3_Superclass_cast: Any

def itkClampImageFilterISS3ISS3_Superclass_New(): ...

class itkClampImageFilterISS3ISS3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterISS3ISS3_Superclass___New_orig__: Any
itkClampImageFilterISS3ISS3_Superclass_cast: Any

def itkClampImageFilterISS3IUC3_Superclass_New(): ...

class itkClampImageFilterISS3IUC3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterISS3IUC3_Superclass___New_orig__: Any
itkClampImageFilterISS3IUC3_Superclass_cast: Any

def itkClampImageFilterIUC2IF2_Superclass_New(): ...

class itkClampImageFilterIUC2IF2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIUC2IF2_Superclass___New_orig__: Any
itkClampImageFilterIUC2IF2_Superclass_cast: Any

def itkClampImageFilterIUC2ISS2_Superclass_New(): ...

class itkClampImageFilterIUC2ISS2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIUC2ISS2_Superclass___New_orig__: Any
itkClampImageFilterIUC2ISS2_Superclass_cast: Any

def itkClampImageFilterIUC2IUC2_Superclass_New(): ...

class itkClampImageFilterIUC2IUC2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIUC2IUC2_Superclass___New_orig__: Any
itkClampImageFilterIUC2IUC2_Superclass_cast: Any

def itkClampImageFilterIUC3IF3_Superclass_New(): ...

class itkClampImageFilterIUC3IF3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIUC3IF3_Superclass___New_orig__: Any
itkClampImageFilterIUC3IF3_Superclass_cast: Any

def itkClampImageFilterIUC3ISS3_Superclass_New(): ...

class itkClampImageFilterIUC3ISS3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIUC3ISS3_Superclass___New_orig__: Any
itkClampImageFilterIUC3ISS3_Superclass_cast: Any

def itkClampImageFilterIUC3IUC3_Superclass_New(): ...

class itkClampImageFilterIUC3IUC3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIUC3IUC3_Superclass___New_orig__: Any
itkClampImageFilterIUC3IUC3_Superclass_cast: Any

def itkClampImageFilterIF2IF2_New(): ...

class itkClampImageFilterIF2IF2(itkClampImageFilterIF2IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetLowerBound: Any = ...
    GetUpperBound: Any = ...
    SetBounds: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIF2IF2___New_orig__: Any
itkClampImageFilterIF2IF2_cast: Any

def itkClampImageFilterIF2ISS2_New(): ...

class itkClampImageFilterIF2ISS2(itkClampImageFilterIF2ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetLowerBound: Any = ...
    GetUpperBound: Any = ...
    SetBounds: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIF2ISS2___New_orig__: Any
itkClampImageFilterIF2ISS2_cast: Any

def itkClampImageFilterIF2IUC2_New(): ...

class itkClampImageFilterIF2IUC2(itkClampImageFilterIF2IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetLowerBound: Any = ...
    GetUpperBound: Any = ...
    SetBounds: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIF2IUC2___New_orig__: Any
itkClampImageFilterIF2IUC2_cast: Any

def itkClampImageFilterIF3IF3_New(): ...

class itkClampImageFilterIF3IF3(itkClampImageFilterIF3IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetLowerBound: Any = ...
    GetUpperBound: Any = ...
    SetBounds: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIF3IF3___New_orig__: Any
itkClampImageFilterIF3IF3_cast: Any

def itkClampImageFilterIF3ISS3_New(): ...

class itkClampImageFilterIF3ISS3(itkClampImageFilterIF3ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetLowerBound: Any = ...
    GetUpperBound: Any = ...
    SetBounds: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIF3ISS3___New_orig__: Any
itkClampImageFilterIF3ISS3_cast: Any

def itkClampImageFilterIF3IUC3_New(): ...

class itkClampImageFilterIF3IUC3(itkClampImageFilterIF3IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetLowerBound: Any = ...
    GetUpperBound: Any = ...
    SetBounds: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIF3IUC3___New_orig__: Any
itkClampImageFilterIF3IUC3_cast: Any

def itkClampImageFilterISS2IF2_New(): ...

class itkClampImageFilterISS2IF2(itkClampImageFilterISS2IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetLowerBound: Any = ...
    GetUpperBound: Any = ...
    SetBounds: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterISS2IF2___New_orig__: Any
itkClampImageFilterISS2IF2_cast: Any

def itkClampImageFilterISS2ISS2_New(): ...

class itkClampImageFilterISS2ISS2(itkClampImageFilterISS2ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetLowerBound: Any = ...
    GetUpperBound: Any = ...
    SetBounds: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterISS2ISS2___New_orig__: Any
itkClampImageFilterISS2ISS2_cast: Any

def itkClampImageFilterISS2IUC2_New(): ...

class itkClampImageFilterISS2IUC2(itkClampImageFilterISS2IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetLowerBound: Any = ...
    GetUpperBound: Any = ...
    SetBounds: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterISS2IUC2___New_orig__: Any
itkClampImageFilterISS2IUC2_cast: Any

def itkClampImageFilterISS3IF3_New(): ...

class itkClampImageFilterISS3IF3(itkClampImageFilterISS3IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetLowerBound: Any = ...
    GetUpperBound: Any = ...
    SetBounds: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterISS3IF3___New_orig__: Any
itkClampImageFilterISS3IF3_cast: Any

def itkClampImageFilterISS3ISS3_New(): ...

class itkClampImageFilterISS3ISS3(itkClampImageFilterISS3ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetLowerBound: Any = ...
    GetUpperBound: Any = ...
    SetBounds: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterISS3ISS3___New_orig__: Any
itkClampImageFilterISS3ISS3_cast: Any

def itkClampImageFilterISS3IUC3_New(): ...

class itkClampImageFilterISS3IUC3(itkClampImageFilterISS3IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetLowerBound: Any = ...
    GetUpperBound: Any = ...
    SetBounds: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterISS3IUC3___New_orig__: Any
itkClampImageFilterISS3IUC3_cast: Any

def itkClampImageFilterIUC2IF2_New(): ...

class itkClampImageFilterIUC2IF2(itkClampImageFilterIUC2IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetLowerBound: Any = ...
    GetUpperBound: Any = ...
    SetBounds: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIUC2IF2___New_orig__: Any
itkClampImageFilterIUC2IF2_cast: Any

def itkClampImageFilterIUC2ISS2_New(): ...

class itkClampImageFilterIUC2ISS2(itkClampImageFilterIUC2ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetLowerBound: Any = ...
    GetUpperBound: Any = ...
    SetBounds: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIUC2ISS2___New_orig__: Any
itkClampImageFilterIUC2ISS2_cast: Any

def itkClampImageFilterIUC2IUC2_New(): ...

class itkClampImageFilterIUC2IUC2(itkClampImageFilterIUC2IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetLowerBound: Any = ...
    GetUpperBound: Any = ...
    SetBounds: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIUC2IUC2___New_orig__: Any
itkClampImageFilterIUC2IUC2_cast: Any

def itkClampImageFilterIUC3IF3_New(): ...

class itkClampImageFilterIUC3IF3(itkClampImageFilterIUC3IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetLowerBound: Any = ...
    GetUpperBound: Any = ...
    SetBounds: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIUC3IF3___New_orig__: Any
itkClampImageFilterIUC3IF3_cast: Any

def itkClampImageFilterIUC3ISS3_New(): ...

class itkClampImageFilterIUC3ISS3(itkClampImageFilterIUC3ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetLowerBound: Any = ...
    GetUpperBound: Any = ...
    SetBounds: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIUC3ISS3___New_orig__: Any
itkClampImageFilterIUC3ISS3_cast: Any

def itkClampImageFilterIUC3IUC3_New(): ...

class itkClampImageFilterIUC3IUC3(itkClampImageFilterIUC3IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetLowerBound: Any = ...
    GetUpperBound: Any = ...
    SetBounds: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkClampImageFilterIUC3IUC3___New_orig__: Any
itkClampImageFilterIUC3IUC3_cast: Any

def clamp_image_filter(*args: Any, **kwargs: Any): ...
def clamp_image_filter_init_docstring() -> None: ...
def unary_functor_image_filter(*args: Any, **kwargs: Any): ...
def unary_functor_image_filter_init_docstring() -> None: ...
