import itk.itkInPlaceImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkCosImageFilterIF2IF2_New(): ...

class itkCosImageFilterIF2IF2(itk.itkUnaryGeneratorImageFilterPython.itkUnaryGeneratorImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToDoubleCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCosImageFilterIF2IF2___New_orig__: Any
itkCosImageFilterIF2IF2_cast: Any

def itkCosImageFilterIF3IF3_New(): ...

class itkCosImageFilterIF3IF3(itk.itkUnaryGeneratorImageFilterPython.itkUnaryGeneratorImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToDoubleCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCosImageFilterIF3IF3___New_orig__: Any
itkCosImageFilterIF3IF3_cast: Any

def cos_image_filter(*args: Any, **kwargs: Any): ...
def cos_image_filter_init_docstring() -> None: ...
