import itk.itkInPlaceImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkComplexToRealImageFilterICF2IF2_New(): ...

class itkComplexToRealImageFilterICF2IF2(itk.itkUnaryGeneratorImageFilterPython.itkUnaryGeneratorImageFilterICF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkComplexToRealImageFilterICF2IF2___New_orig__: Any
itkComplexToRealImageFilterICF2IF2_cast: Any

def itkComplexToRealImageFilterICF3IF3_New(): ...

class itkComplexToRealImageFilterICF3IF3(itk.itkUnaryGeneratorImageFilterPython.itkUnaryGeneratorImageFilterICF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkComplexToRealImageFilterICF3IF3___New_orig__: Any
itkComplexToRealImageFilterICF3IF3_cast: Any

def complex_to_real_image_filter(*args: Any, **kwargs: Any): ...
def complex_to_real_image_filter_init_docstring() -> None: ...
