import itk.itkInPlaceImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkConstrainedValueDifferenceImageFilterIF2IF2IF2_New(): ...

class itkConstrainedValueDifferenceImageFilterIF2IF2IF2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIF2IF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1ConvertibleToDoubleCheck: Any = ...
    Input2ConvertibleToDoubleCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    DoubleGreaterThanOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConstrainedValueDifferenceImageFilterIF2IF2IF2___New_orig__: Any
itkConstrainedValueDifferenceImageFilterIF2IF2IF2_cast: Any

def itkConstrainedValueDifferenceImageFilterIF3IF3IF3_New(): ...

class itkConstrainedValueDifferenceImageFilterIF3IF3IF3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIF3IF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1ConvertibleToDoubleCheck: Any = ...
    Input2ConvertibleToDoubleCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    DoubleGreaterThanOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConstrainedValueDifferenceImageFilterIF3IF3IF3___New_orig__: Any
itkConstrainedValueDifferenceImageFilterIF3IF3IF3_cast: Any

def itkConstrainedValueDifferenceImageFilterISS2ISS2ISS2_New(): ...

class itkConstrainedValueDifferenceImageFilterISS2ISS2ISS2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterISS2ISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1ConvertibleToDoubleCheck: Any = ...
    Input2ConvertibleToDoubleCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    DoubleGreaterThanOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConstrainedValueDifferenceImageFilterISS2ISS2ISS2___New_orig__: Any
itkConstrainedValueDifferenceImageFilterISS2ISS2ISS2_cast: Any

def itkConstrainedValueDifferenceImageFilterISS3ISS3ISS3_New(): ...

class itkConstrainedValueDifferenceImageFilterISS3ISS3ISS3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterISS3ISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1ConvertibleToDoubleCheck: Any = ...
    Input2ConvertibleToDoubleCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    DoubleGreaterThanOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConstrainedValueDifferenceImageFilterISS3ISS3ISS3___New_orig__: Any
itkConstrainedValueDifferenceImageFilterISS3ISS3ISS3_cast: Any

def itkConstrainedValueDifferenceImageFilterIUC2IUC2IUC2_New(): ...

class itkConstrainedValueDifferenceImageFilterIUC2IUC2IUC2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC2IUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1ConvertibleToDoubleCheck: Any = ...
    Input2ConvertibleToDoubleCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    DoubleGreaterThanOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConstrainedValueDifferenceImageFilterIUC2IUC2IUC2___New_orig__: Any
itkConstrainedValueDifferenceImageFilterIUC2IUC2IUC2_cast: Any

def itkConstrainedValueDifferenceImageFilterIUC3IUC3IUC3_New(): ...

class itkConstrainedValueDifferenceImageFilterIUC3IUC3IUC3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC3IUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1ConvertibleToDoubleCheck: Any = ...
    Input2ConvertibleToDoubleCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    DoubleGreaterThanOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConstrainedValueDifferenceImageFilterIUC3IUC3IUC3___New_orig__: Any
itkConstrainedValueDifferenceImageFilterIUC3IUC3IUC3_cast: Any

def constrained_value_difference_image_filter(*args: Any, **kwargs: Any): ...
def constrained_value_difference_image_filter_init_docstring() -> None: ...
