import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkComplexToComplexFFTImageFilterEnums:
    thisown: Any = ...
    TransformDirection_FORWARD: Any = ...
    TransformDirection_INVERSE: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...

def itkComplexToComplexFFTImageFilterICF2_New(): ...

class itkComplexToComplexFFTImageFilterICF2(itk.itkImageToImageFilterBPython.itkImageToImageFilterICF2ICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    SetTransformDirection: Any = ...
    GetTransformDirection: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkComplexToComplexFFTImageFilterICF2___New_orig__: Any
itkComplexToComplexFFTImageFilterICF2_cast: Any

def itkComplexToComplexFFTImageFilterICF3_New(): ...

class itkComplexToComplexFFTImageFilterICF3(itk.itkImageToImageFilterBPython.itkImageToImageFilterICF3ICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    SetTransformDirection: Any = ...
    GetTransformDirection: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkComplexToComplexFFTImageFilterICF3___New_orig__: Any
itkComplexToComplexFFTImageFilterICF3_cast: Any

def complex_to_complex_fft_image_filter(*args: Any, **kwargs: Any): ...
def complex_to_complex_fft_image_filter_init_docstring() -> None: ...
