import itk.itkImageRegionPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkDiscreteCurvatureQuadEdgeMeshFilterQEMD2(itk.itkQuadEdgeMeshToQuadEdgeMeshFilterPython.itkQuadEdgeMeshToQuadEdgeMeshFilterQEMD2QEMD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    OutputIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkDiscreteCurvatureQuadEdgeMeshFilterQEMD2_cast: Any

class itkDiscreteCurvatureQuadEdgeMeshFilterQEMD3(itk.itkQuadEdgeMeshToQuadEdgeMeshFilterPython.itkQuadEdgeMeshToQuadEdgeMeshFilterQEMD3QEMD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    OutputIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkDiscreteCurvatureQuadEdgeMeshFilterQEMD3_cast: Any

def discrete_curvature_quad_edge_mesh_filter(*args: Any, **kwargs: Any): ...
def discrete_curvature_quad_edge_mesh_filter_init_docstring() -> None: ...
