import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkDisplacementFieldJacobianDeterminantFilterIVF22F_New(): ...

class itkDisplacementFieldJacobianDeterminantFilterIVF22F(itk.itkImageToImageFilterBPython.itkImageToImageFilterIVF22IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SetUseImageSpacingOn: Any = ...
    SetUseImageSpacingOff: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    SetDerivativeWeights: Any = ...
    GetDerivativeWeights: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDisplacementFieldJacobianDeterminantFilterIVF22F___New_orig__: Any
itkDisplacementFieldJacobianDeterminantFilterIVF22F_cast: Any

def itkDisplacementFieldJacobianDeterminantFilterIVF33F_New(): ...

class itkDisplacementFieldJacobianDeterminantFilterIVF33F(itk.itkImageToImageFilterBPython.itkImageToImageFilterIVF33IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SetUseImageSpacingOn: Any = ...
    SetUseImageSpacingOff: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    SetDerivativeWeights: Any = ...
    GetDerivativeWeights: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDisplacementFieldJacobianDeterminantFilterIVF33F___New_orig__: Any
itkDisplacementFieldJacobianDeterminantFilterIVF33F_cast: Any

def displacement_field_jacobian_determinant_filter(*args: Any, **kwargs: Any): ...
def displacement_field_jacobian_determinant_filter_init_docstring() -> None: ...
