import itk.itkImageRegionPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkDiscreteCurvatureTensorQuadEdgeMeshFilterQEMD2_New(): ...

class itkDiscreteCurvatureTensorQuadEdgeMeshFilterQEMD2(itk.itkQuadEdgeMeshToQuadEdgeMeshFilterPython.itkQuadEdgeMeshToQuadEdgeMeshFilterQEMD2QEMD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDiscreteCurvatureTensorQuadEdgeMeshFilterQEMD2___New_orig__: Any
itkDiscreteCurvatureTensorQuadEdgeMeshFilterQEMD2_cast: Any

def itkDiscreteCurvatureTensorQuadEdgeMeshFilterQEMD3_New(): ...

class itkDiscreteCurvatureTensorQuadEdgeMeshFilterQEMD3(itk.itkQuadEdgeMeshToQuadEdgeMeshFilterPython.itkQuadEdgeMeshToQuadEdgeMeshFilterQEMD3QEMD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDiscreteCurvatureTensorQuadEdgeMeshFilterQEMD3___New_orig__: Any
itkDiscreteCurvatureTensorQuadEdgeMeshFilterQEMD3_cast: Any

def discrete_curvature_tensor_quad_edge_mesh_filter(*args: Any, **kwargs: Any): ...
def discrete_curvature_tensor_quad_edge_mesh_filter_init_docstring() -> None: ...
