import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkDirectedHausdorffDistanceImageFilterIF2IF2_New(): ...

class itkDirectedHausdorffDistanceImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    GetInput1: Any = ...
    GetInput2: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    GetDirectedHausdorffDistance: Any = ...
    GetAverageHausdorffDistance: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDirectedHausdorffDistanceImageFilterIF2IF2___New_orig__: Any
itkDirectedHausdorffDistanceImageFilterIF2IF2_cast: Any

def itkDirectedHausdorffDistanceImageFilterIF3IF3_New(): ...

class itkDirectedHausdorffDistanceImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    GetInput1: Any = ...
    GetInput2: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    GetDirectedHausdorffDistance: Any = ...
    GetAverageHausdorffDistance: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDirectedHausdorffDistanceImageFilterIF3IF3___New_orig__: Any
itkDirectedHausdorffDistanceImageFilterIF3IF3_cast: Any

def itkDirectedHausdorffDistanceImageFilterISS2ISS2_New(): ...

class itkDirectedHausdorffDistanceImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    GetInput1: Any = ...
    GetInput2: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    GetDirectedHausdorffDistance: Any = ...
    GetAverageHausdorffDistance: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDirectedHausdorffDistanceImageFilterISS2ISS2___New_orig__: Any
itkDirectedHausdorffDistanceImageFilterISS2ISS2_cast: Any

def itkDirectedHausdorffDistanceImageFilterISS3ISS3_New(): ...

class itkDirectedHausdorffDistanceImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    GetInput1: Any = ...
    GetInput2: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    GetDirectedHausdorffDistance: Any = ...
    GetAverageHausdorffDistance: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDirectedHausdorffDistanceImageFilterISS3ISS3___New_orig__: Any
itkDirectedHausdorffDistanceImageFilterISS3ISS3_cast: Any

def itkDirectedHausdorffDistanceImageFilterIUC2IF2_New(): ...

class itkDirectedHausdorffDistanceImageFilterIUC2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    GetInput1: Any = ...
    GetInput2: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    GetDirectedHausdorffDistance: Any = ...
    GetAverageHausdorffDistance: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDirectedHausdorffDistanceImageFilterIUC2IF2___New_orig__: Any
itkDirectedHausdorffDistanceImageFilterIUC2IF2_cast: Any

def itkDirectedHausdorffDistanceImageFilterIUC3IF3_New(): ...

class itkDirectedHausdorffDistanceImageFilterIUC3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    GetInput1: Any = ...
    GetInput2: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    GetDirectedHausdorffDistance: Any = ...
    GetAverageHausdorffDistance: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDirectedHausdorffDistanceImageFilterIUC3IF3___New_orig__: Any
itkDirectedHausdorffDistanceImageFilterIUC3IF3_cast: Any

def directed_hausdorff_distance_image_filter(*args: Any, **kwargs: Any): ...
def directed_hausdorff_distance_image_filter_init_docstring() -> None: ...
