import itk.itkCovariantVectorPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkDiffusionTensor3DD(itk.itkSymmetricSecondRankTensorPython.itkSymmetricSecondRankTensorD3):
    thisown: Any = ...
    GetTrace: Any = ...
    GetFractionalAnisotropy: Any = ...
    GetRelativeAnisotropy: Any = ...
    GetInnerScalarProduct: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...

class itkDiffusionTensor3DF(itk.itkSymmetricSecondRankTensorPython.itkSymmetricSecondRankTensorF3):
    thisown: Any = ...
    GetTrace: Any = ...
    GetFractionalAnisotropy: Any = ...
    GetRelativeAnisotropy: Any = ...
    GetInnerScalarProduct: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
