import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkDemonsRegistrationFilterIF2IF2IVF22_New(): ...

class itkDemonsRegistrationFilterIF2IF2IVF22(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIF2IF2IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetUseMovingImageGradient: Any = ...
    GetUseMovingImageGradient: Any = ...
    UseMovingImageGradientOn: Any = ...
    UseMovingImageGradientOff: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDemonsRegistrationFilterIF2IF2IVF22___New_orig__: Any
itkDemonsRegistrationFilterIF2IF2IVF22_cast: Any

def itkDemonsRegistrationFilterIF2IF2IVF32_New(): ...

class itkDemonsRegistrationFilterIF2IF2IVF32(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIF2IF2IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetUseMovingImageGradient: Any = ...
    GetUseMovingImageGradient: Any = ...
    UseMovingImageGradientOn: Any = ...
    UseMovingImageGradientOff: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDemonsRegistrationFilterIF2IF2IVF32___New_orig__: Any
itkDemonsRegistrationFilterIF2IF2IVF32_cast: Any

def itkDemonsRegistrationFilterIF2IF2IVF42_New(): ...

class itkDemonsRegistrationFilterIF2IF2IVF42(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIF2IF2IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetUseMovingImageGradient: Any = ...
    GetUseMovingImageGradient: Any = ...
    UseMovingImageGradientOn: Any = ...
    UseMovingImageGradientOff: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDemonsRegistrationFilterIF2IF2IVF42___New_orig__: Any
itkDemonsRegistrationFilterIF2IF2IVF42_cast: Any

def itkDemonsRegistrationFilterIF3IF3IVF23_New(): ...

class itkDemonsRegistrationFilterIF3IF3IVF23(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIF3IF3IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetUseMovingImageGradient: Any = ...
    GetUseMovingImageGradient: Any = ...
    UseMovingImageGradientOn: Any = ...
    UseMovingImageGradientOff: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDemonsRegistrationFilterIF3IF3IVF23___New_orig__: Any
itkDemonsRegistrationFilterIF3IF3IVF23_cast: Any

def itkDemonsRegistrationFilterIF3IF3IVF33_New(): ...

class itkDemonsRegistrationFilterIF3IF3IVF33(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIF3IF3IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetUseMovingImageGradient: Any = ...
    GetUseMovingImageGradient: Any = ...
    UseMovingImageGradientOn: Any = ...
    UseMovingImageGradientOff: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDemonsRegistrationFilterIF3IF3IVF33___New_orig__: Any
itkDemonsRegistrationFilterIF3IF3IVF33_cast: Any

def itkDemonsRegistrationFilterIF3IF3IVF43_New(): ...

class itkDemonsRegistrationFilterIF3IF3IVF43(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIF3IF3IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetUseMovingImageGradient: Any = ...
    GetUseMovingImageGradient: Any = ...
    UseMovingImageGradientOn: Any = ...
    UseMovingImageGradientOff: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDemonsRegistrationFilterIF3IF3IVF43___New_orig__: Any
itkDemonsRegistrationFilterIF3IF3IVF43_cast: Any

def itkDemonsRegistrationFilterISS2ISS2IVF22_New(): ...

class itkDemonsRegistrationFilterISS2ISS2IVF22(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterISS2ISS2IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetUseMovingImageGradient: Any = ...
    GetUseMovingImageGradient: Any = ...
    UseMovingImageGradientOn: Any = ...
    UseMovingImageGradientOff: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDemonsRegistrationFilterISS2ISS2IVF22___New_orig__: Any
itkDemonsRegistrationFilterISS2ISS2IVF22_cast: Any

def itkDemonsRegistrationFilterISS2ISS2IVF32_New(): ...

class itkDemonsRegistrationFilterISS2ISS2IVF32(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterISS2ISS2IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetUseMovingImageGradient: Any = ...
    GetUseMovingImageGradient: Any = ...
    UseMovingImageGradientOn: Any = ...
    UseMovingImageGradientOff: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDemonsRegistrationFilterISS2ISS2IVF32___New_orig__: Any
itkDemonsRegistrationFilterISS2ISS2IVF32_cast: Any

def itkDemonsRegistrationFilterISS2ISS2IVF42_New(): ...

class itkDemonsRegistrationFilterISS2ISS2IVF42(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterISS2ISS2IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetUseMovingImageGradient: Any = ...
    GetUseMovingImageGradient: Any = ...
    UseMovingImageGradientOn: Any = ...
    UseMovingImageGradientOff: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDemonsRegistrationFilterISS2ISS2IVF42___New_orig__: Any
itkDemonsRegistrationFilterISS2ISS2IVF42_cast: Any

def itkDemonsRegistrationFilterISS3ISS3IVF23_New(): ...

class itkDemonsRegistrationFilterISS3ISS3IVF23(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterISS3ISS3IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetUseMovingImageGradient: Any = ...
    GetUseMovingImageGradient: Any = ...
    UseMovingImageGradientOn: Any = ...
    UseMovingImageGradientOff: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDemonsRegistrationFilterISS3ISS3IVF23___New_orig__: Any
itkDemonsRegistrationFilterISS3ISS3IVF23_cast: Any

def itkDemonsRegistrationFilterISS3ISS3IVF33_New(): ...

class itkDemonsRegistrationFilterISS3ISS3IVF33(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterISS3ISS3IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetUseMovingImageGradient: Any = ...
    GetUseMovingImageGradient: Any = ...
    UseMovingImageGradientOn: Any = ...
    UseMovingImageGradientOff: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDemonsRegistrationFilterISS3ISS3IVF33___New_orig__: Any
itkDemonsRegistrationFilterISS3ISS3IVF33_cast: Any

def itkDemonsRegistrationFilterISS3ISS3IVF43_New(): ...

class itkDemonsRegistrationFilterISS3ISS3IVF43(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterISS3ISS3IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetUseMovingImageGradient: Any = ...
    GetUseMovingImageGradient: Any = ...
    UseMovingImageGradientOn: Any = ...
    UseMovingImageGradientOff: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDemonsRegistrationFilterISS3ISS3IVF43___New_orig__: Any
itkDemonsRegistrationFilterISS3ISS3IVF43_cast: Any

def itkDemonsRegistrationFilterIUC2IUC2IVF22_New(): ...

class itkDemonsRegistrationFilterIUC2IUC2IVF22(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIUC2IUC2IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetUseMovingImageGradient: Any = ...
    GetUseMovingImageGradient: Any = ...
    UseMovingImageGradientOn: Any = ...
    UseMovingImageGradientOff: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDemonsRegistrationFilterIUC2IUC2IVF22___New_orig__: Any
itkDemonsRegistrationFilterIUC2IUC2IVF22_cast: Any

def itkDemonsRegistrationFilterIUC2IUC2IVF32_New(): ...

class itkDemonsRegistrationFilterIUC2IUC2IVF32(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIUC2IUC2IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetUseMovingImageGradient: Any = ...
    GetUseMovingImageGradient: Any = ...
    UseMovingImageGradientOn: Any = ...
    UseMovingImageGradientOff: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDemonsRegistrationFilterIUC2IUC2IVF32___New_orig__: Any
itkDemonsRegistrationFilterIUC2IUC2IVF32_cast: Any

def itkDemonsRegistrationFilterIUC2IUC2IVF42_New(): ...

class itkDemonsRegistrationFilterIUC2IUC2IVF42(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIUC2IUC2IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetUseMovingImageGradient: Any = ...
    GetUseMovingImageGradient: Any = ...
    UseMovingImageGradientOn: Any = ...
    UseMovingImageGradientOff: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDemonsRegistrationFilterIUC2IUC2IVF42___New_orig__: Any
itkDemonsRegistrationFilterIUC2IUC2IVF42_cast: Any

def itkDemonsRegistrationFilterIUC3IUC3IVF23_New(): ...

class itkDemonsRegistrationFilterIUC3IUC3IVF23(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIUC3IUC3IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetUseMovingImageGradient: Any = ...
    GetUseMovingImageGradient: Any = ...
    UseMovingImageGradientOn: Any = ...
    UseMovingImageGradientOff: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDemonsRegistrationFilterIUC3IUC3IVF23___New_orig__: Any
itkDemonsRegistrationFilterIUC3IUC3IVF23_cast: Any

def itkDemonsRegistrationFilterIUC3IUC3IVF33_New(): ...

class itkDemonsRegistrationFilterIUC3IUC3IVF33(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIUC3IUC3IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetUseMovingImageGradient: Any = ...
    GetUseMovingImageGradient: Any = ...
    UseMovingImageGradientOn: Any = ...
    UseMovingImageGradientOff: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDemonsRegistrationFilterIUC3IUC3IVF33___New_orig__: Any
itkDemonsRegistrationFilterIUC3IUC3IVF33_cast: Any

def itkDemonsRegistrationFilterIUC3IUC3IVF43_New(): ...

class itkDemonsRegistrationFilterIUC3IUC3IVF43(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIUC3IUC3IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetUseMovingImageGradient: Any = ...
    GetUseMovingImageGradient: Any = ...
    UseMovingImageGradientOn: Any = ...
    UseMovingImageGradientOff: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDemonsRegistrationFilterIUC3IUC3IVF43___New_orig__: Any
itkDemonsRegistrationFilterIUC3IUC3IVF43_cast: Any

def demons_registration_filter(*args: Any, **kwargs: Any): ...
def demons_registration_filter_init_docstring() -> None: ...
