import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkDoubleThresholdImageFilterIF2IF2_New(): ...

class itkDoubleThresholdImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetThreshold1: Any = ...
    SetThreshold2: Any = ...
    SetThreshold3: Any = ...
    SetThreshold4: Any = ...
    GetThreshold1: Any = ...
    GetThreshold2: Any = ...
    GetThreshold3: Any = ...
    GetThreshold4: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    OutputEqualityComparableCheck: Any = ...
    InputComparableCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDoubleThresholdImageFilterIF2IF2___New_orig__: Any
itkDoubleThresholdImageFilterIF2IF2_cast: Any

def itkDoubleThresholdImageFilterIF2IUC2_New(): ...

class itkDoubleThresholdImageFilterIF2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetThreshold1: Any = ...
    SetThreshold2: Any = ...
    SetThreshold3: Any = ...
    SetThreshold4: Any = ...
    GetThreshold1: Any = ...
    GetThreshold2: Any = ...
    GetThreshold3: Any = ...
    GetThreshold4: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    OutputEqualityComparableCheck: Any = ...
    InputComparableCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDoubleThresholdImageFilterIF2IUC2___New_orig__: Any
itkDoubleThresholdImageFilterIF2IUC2_cast: Any

def itkDoubleThresholdImageFilterIF3IF3_New(): ...

class itkDoubleThresholdImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetThreshold1: Any = ...
    SetThreshold2: Any = ...
    SetThreshold3: Any = ...
    SetThreshold4: Any = ...
    GetThreshold1: Any = ...
    GetThreshold2: Any = ...
    GetThreshold3: Any = ...
    GetThreshold4: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    OutputEqualityComparableCheck: Any = ...
    InputComparableCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDoubleThresholdImageFilterIF3IF3___New_orig__: Any
itkDoubleThresholdImageFilterIF3IF3_cast: Any

def itkDoubleThresholdImageFilterIF3IUC3_New(): ...

class itkDoubleThresholdImageFilterIF3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetThreshold1: Any = ...
    SetThreshold2: Any = ...
    SetThreshold3: Any = ...
    SetThreshold4: Any = ...
    GetThreshold1: Any = ...
    GetThreshold2: Any = ...
    GetThreshold3: Any = ...
    GetThreshold4: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    OutputEqualityComparableCheck: Any = ...
    InputComparableCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDoubleThresholdImageFilterIF3IUC3___New_orig__: Any
itkDoubleThresholdImageFilterIF3IUC3_cast: Any

def itkDoubleThresholdImageFilterISS2ISS2_New(): ...

class itkDoubleThresholdImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetThreshold1: Any = ...
    SetThreshold2: Any = ...
    SetThreshold3: Any = ...
    SetThreshold4: Any = ...
    GetThreshold1: Any = ...
    GetThreshold2: Any = ...
    GetThreshold3: Any = ...
    GetThreshold4: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    OutputEqualityComparableCheck: Any = ...
    InputComparableCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDoubleThresholdImageFilterISS2ISS2___New_orig__: Any
itkDoubleThresholdImageFilterISS2ISS2_cast: Any

def itkDoubleThresholdImageFilterISS3ISS3_New(): ...

class itkDoubleThresholdImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetThreshold1: Any = ...
    SetThreshold2: Any = ...
    SetThreshold3: Any = ...
    SetThreshold4: Any = ...
    GetThreshold1: Any = ...
    GetThreshold2: Any = ...
    GetThreshold3: Any = ...
    GetThreshold4: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    OutputEqualityComparableCheck: Any = ...
    InputComparableCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDoubleThresholdImageFilterISS3ISS3___New_orig__: Any
itkDoubleThresholdImageFilterISS3ISS3_cast: Any

def itkDoubleThresholdImageFilterIUC2IUC2_New(): ...

class itkDoubleThresholdImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetThreshold1: Any = ...
    SetThreshold2: Any = ...
    SetThreshold3: Any = ...
    SetThreshold4: Any = ...
    GetThreshold1: Any = ...
    GetThreshold2: Any = ...
    GetThreshold3: Any = ...
    GetThreshold4: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    OutputEqualityComparableCheck: Any = ...
    InputComparableCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDoubleThresholdImageFilterIUC2IUC2___New_orig__: Any
itkDoubleThresholdImageFilterIUC2IUC2_cast: Any

def itkDoubleThresholdImageFilterIUC3IUC3_New(): ...

class itkDoubleThresholdImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetThreshold1: Any = ...
    SetThreshold2: Any = ...
    SetThreshold3: Any = ...
    SetThreshold4: Any = ...
    GetThreshold1: Any = ...
    GetThreshold2: Any = ...
    GetThreshold3: Any = ...
    GetThreshold4: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    OutputEqualityComparableCheck: Any = ...
    InputComparableCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDoubleThresholdImageFilterIUC3IUC3___New_orig__: Any
itkDoubleThresholdImageFilterIUC3IUC3_cast: Any

def double_threshold_image_filter(*args: Any, **kwargs: Any): ...
def double_threshold_image_filter_init_docstring() -> None: ...
