import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkDifferenceOfGaussiansGradientImageFilterIF2F_New(): ...

class itkDifferenceOfGaussiansGradientImageFilterIF2F(itk.itkImageToImageFilterBPython.itkImageToImageFilterIF2ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetWidth: Any = ...
    SetWidth: Any = ...
    DataTypeHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDifferenceOfGaussiansGradientImageFilterIF2F___New_orig__: Any
itkDifferenceOfGaussiansGradientImageFilterIF2F_cast: Any

def itkDifferenceOfGaussiansGradientImageFilterIF3F_New(): ...

class itkDifferenceOfGaussiansGradientImageFilterIF3F(itk.itkImageToImageFilterBPython.itkImageToImageFilterIF3ICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetWidth: Any = ...
    SetWidth: Any = ...
    DataTypeHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDifferenceOfGaussiansGradientImageFilterIF3F___New_orig__: Any
itkDifferenceOfGaussiansGradientImageFilterIF3F_cast: Any

def itkDifferenceOfGaussiansGradientImageFilterISS2F_New(): ...

class itkDifferenceOfGaussiansGradientImageFilterISS2F(itk.itkImageToImageFilterBPython.itkImageToImageFilterISS2ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetWidth: Any = ...
    SetWidth: Any = ...
    DataTypeHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDifferenceOfGaussiansGradientImageFilterISS2F___New_orig__: Any
itkDifferenceOfGaussiansGradientImageFilterISS2F_cast: Any

def itkDifferenceOfGaussiansGradientImageFilterISS3F_New(): ...

class itkDifferenceOfGaussiansGradientImageFilterISS3F(itk.itkImageToImageFilterBPython.itkImageToImageFilterISS3ICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetWidth: Any = ...
    SetWidth: Any = ...
    DataTypeHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDifferenceOfGaussiansGradientImageFilterISS3F___New_orig__: Any
itkDifferenceOfGaussiansGradientImageFilterISS3F_cast: Any

def itkDifferenceOfGaussiansGradientImageFilterIUC2F_New(): ...

class itkDifferenceOfGaussiansGradientImageFilterIUC2F(itk.itkImageToImageFilterBPython.itkImageToImageFilterIUC2ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetWidth: Any = ...
    SetWidth: Any = ...
    DataTypeHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDifferenceOfGaussiansGradientImageFilterIUC2F___New_orig__: Any
itkDifferenceOfGaussiansGradientImageFilterIUC2F_cast: Any

def itkDifferenceOfGaussiansGradientImageFilterIUC3F_New(): ...

class itkDifferenceOfGaussiansGradientImageFilterIUC3F(itk.itkImageToImageFilterBPython.itkImageToImageFilterIUC3ICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetWidth: Any = ...
    SetWidth: Any = ...
    DataTypeHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDifferenceOfGaussiansGradientImageFilterIUC3F___New_orig__: Any
itkDifferenceOfGaussiansGradientImageFilterIUC3F_cast: Any

def difference_of_gaussians_gradient_image_filter(*args: Any, **kwargs: Any): ...
def difference_of_gaussians_gradient_image_filter_init_docstring() -> None: ...
