import itk.itkRGBPixelPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkDisplacementFieldTransformD2_New(): ...

class itkDisplacementFieldTransformD2(itk.itkTransformBasePython.itkTransformD22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDisplacementField: Any = ...
    GetModifiableDisplacementField: Any = ...
    GetDisplacementField: Any = ...
    SetInverseDisplacementField: Any = ...
    GetModifiableInverseDisplacementField: Any = ...
    GetInverseDisplacementField: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    SetInverseInterpolator: Any = ...
    GetModifiableInverseInterpolator: Any = ...
    GetInverseInterpolator: Any = ...
    GetDisplacementFieldSetTime: Any = ...
    TransformVector: Any = ...
    TransformDiffusionTensor: Any = ...
    TransformCovariantVector: Any = ...
    ComputeJacobianWithRespectToParameters: Any = ...
    ComputeJacobianWithRespectToPosition: Any = ...
    GetInverseJacobianOfForwardFieldWithRespectToPosition: Any = ...
    UpdateTransformParameters: Any = ...
    GetInverse: Any = ...
    SetIdentity: Any = ...
    SetCoordinateTolerance: Any = ...
    GetCoordinateTolerance: Any = ...
    SetDirectionTolerance: Any = ...
    GetDirectionTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDisplacementFieldTransformD2___New_orig__: Any
itkDisplacementFieldTransformD2_cast: Any

def itkDisplacementFieldTransformD3_New(): ...

class itkDisplacementFieldTransformD3(itk.itkTransformBasePython.itkTransformD33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDisplacementField: Any = ...
    GetModifiableDisplacementField: Any = ...
    GetDisplacementField: Any = ...
    SetInverseDisplacementField: Any = ...
    GetModifiableInverseDisplacementField: Any = ...
    GetInverseDisplacementField: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    SetInverseInterpolator: Any = ...
    GetModifiableInverseInterpolator: Any = ...
    GetInverseInterpolator: Any = ...
    GetDisplacementFieldSetTime: Any = ...
    TransformVector: Any = ...
    TransformDiffusionTensor: Any = ...
    TransformCovariantVector: Any = ...
    ComputeJacobianWithRespectToParameters: Any = ...
    ComputeJacobianWithRespectToPosition: Any = ...
    GetInverseJacobianOfForwardFieldWithRespectToPosition: Any = ...
    UpdateTransformParameters: Any = ...
    GetInverse: Any = ...
    SetIdentity: Any = ...
    SetCoordinateTolerance: Any = ...
    GetCoordinateTolerance: Any = ...
    SetDirectionTolerance: Any = ...
    GetDirectionTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDisplacementFieldTransformD3___New_orig__: Any
itkDisplacementFieldTransformD3_cast: Any
