import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkDiscreteGaussianDerivativeImageFilterIF2IF2_New(): ...

class itkDiscreteGaussianDerivativeImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOrder: Any = ...
    GetVariance: Any = ...
    GetMaximumError: Any = ...
    GetMaximumKernelWidth: Any = ...
    SetMaximumKernelWidth: Any = ...
    SetInternalNumberOfStreamDivisions: Any = ...
    GetInternalNumberOfStreamDivisions: Any = ...
    SetOrder: Any = ...
    SetVariance: Any = ...
    SetMaximumError: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    NormalizeAcrossScaleOn: Any = ...
    NormalizeAcrossScaleOff: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDiscreteGaussianDerivativeImageFilterIF2IF2___New_orig__: Any
itkDiscreteGaussianDerivativeImageFilterIF2IF2_cast: Any

def itkDiscreteGaussianDerivativeImageFilterIF3IF3_New(): ...

class itkDiscreteGaussianDerivativeImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOrder: Any = ...
    GetVariance: Any = ...
    GetMaximumError: Any = ...
    GetMaximumKernelWidth: Any = ...
    SetMaximumKernelWidth: Any = ...
    SetInternalNumberOfStreamDivisions: Any = ...
    GetInternalNumberOfStreamDivisions: Any = ...
    SetOrder: Any = ...
    SetVariance: Any = ...
    SetMaximumError: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    NormalizeAcrossScaleOn: Any = ...
    NormalizeAcrossScaleOff: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDiscreteGaussianDerivativeImageFilterIF3IF3___New_orig__: Any
itkDiscreteGaussianDerivativeImageFilterIF3IF3_cast: Any

def itkDiscreteGaussianDerivativeImageFilterISS2ISS2_New(): ...

class itkDiscreteGaussianDerivativeImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOrder: Any = ...
    GetVariance: Any = ...
    GetMaximumError: Any = ...
    GetMaximumKernelWidth: Any = ...
    SetMaximumKernelWidth: Any = ...
    SetInternalNumberOfStreamDivisions: Any = ...
    GetInternalNumberOfStreamDivisions: Any = ...
    SetOrder: Any = ...
    SetVariance: Any = ...
    SetMaximumError: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    NormalizeAcrossScaleOn: Any = ...
    NormalizeAcrossScaleOff: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDiscreteGaussianDerivativeImageFilterISS2ISS2___New_orig__: Any
itkDiscreteGaussianDerivativeImageFilterISS2ISS2_cast: Any

def itkDiscreteGaussianDerivativeImageFilterISS3ISS3_New(): ...

class itkDiscreteGaussianDerivativeImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOrder: Any = ...
    GetVariance: Any = ...
    GetMaximumError: Any = ...
    GetMaximumKernelWidth: Any = ...
    SetMaximumKernelWidth: Any = ...
    SetInternalNumberOfStreamDivisions: Any = ...
    GetInternalNumberOfStreamDivisions: Any = ...
    SetOrder: Any = ...
    SetVariance: Any = ...
    SetMaximumError: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    NormalizeAcrossScaleOn: Any = ...
    NormalizeAcrossScaleOff: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDiscreteGaussianDerivativeImageFilterISS3ISS3___New_orig__: Any
itkDiscreteGaussianDerivativeImageFilterISS3ISS3_cast: Any

def itkDiscreteGaussianDerivativeImageFilterIUC2IUC2_New(): ...

class itkDiscreteGaussianDerivativeImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOrder: Any = ...
    GetVariance: Any = ...
    GetMaximumError: Any = ...
    GetMaximumKernelWidth: Any = ...
    SetMaximumKernelWidth: Any = ...
    SetInternalNumberOfStreamDivisions: Any = ...
    GetInternalNumberOfStreamDivisions: Any = ...
    SetOrder: Any = ...
    SetVariance: Any = ...
    SetMaximumError: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    NormalizeAcrossScaleOn: Any = ...
    NormalizeAcrossScaleOff: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDiscreteGaussianDerivativeImageFilterIUC2IUC2___New_orig__: Any
itkDiscreteGaussianDerivativeImageFilterIUC2IUC2_cast: Any

def itkDiscreteGaussianDerivativeImageFilterIUC3IUC3_New(): ...

class itkDiscreteGaussianDerivativeImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOrder: Any = ...
    GetVariance: Any = ...
    GetMaximumError: Any = ...
    GetMaximumKernelWidth: Any = ...
    SetMaximumKernelWidth: Any = ...
    SetInternalNumberOfStreamDivisions: Any = ...
    GetInternalNumberOfStreamDivisions: Any = ...
    SetOrder: Any = ...
    SetVariance: Any = ...
    SetMaximumError: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    NormalizeAcrossScaleOn: Any = ...
    NormalizeAcrossScaleOff: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDiscreteGaussianDerivativeImageFilterIUC3IUC3___New_orig__: Any
itkDiscreteGaussianDerivativeImageFilterIUC3IUC3_cast: Any

def discrete_gaussian_derivative_image_filter(*args: Any, **kwargs: Any): ...
def discrete_gaussian_derivative_image_filter_init_docstring() -> None: ...
