import itk.itkArrayPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkDiscretePrincipalCurvaturesQuadEdgeMeshFilterQEMD2(itk.itkDiscreteCurvatureQuadEdgeMeshFilterPython.itkDiscreteCurvatureQuadEdgeMeshFilterQEMD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    OutputIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkDiscretePrincipalCurvaturesQuadEdgeMeshFilterQEMD2_cast: Any

class itkDiscretePrincipalCurvaturesQuadEdgeMeshFilterQEMD3(itk.itkDiscreteCurvatureQuadEdgeMeshFilterPython.itkDiscreteCurvatureQuadEdgeMeshFilterQEMD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    OutputIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkDiscretePrincipalCurvaturesQuadEdgeMeshFilterQEMD3_cast: Any

def discrete_principal_curvatures_quad_edge_mesh_filter(*args: Any, **kwargs: Any): ...
def discrete_principal_curvatures_quad_edge_mesh_filter_init_docstring() -> None: ...
