import itk.itkOffsetPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkDerivativeOperatorF2(itk.itkNeighborhoodOperatorPython.itkNeighborhoodOperatorF2):
    thisown: Any = ...
    SetOrder: Any = ...
    GetOrder: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...

class itkDerivativeOperatorF3(itk.itkNeighborhoodOperatorPython.itkNeighborhoodOperatorF3):
    thisown: Any = ...
    SetOrder: Any = ...
    GetOrder: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
