import itk.itkImageRegionPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkDiscreteMaximumCurvatureQuadEdgeMeshFilterQEMD2_New(): ...

class itkDiscreteMaximumCurvatureQuadEdgeMeshFilterQEMD2(itk.itkDiscretePrincipalCurvaturesQuadEdgeMeshFilterPython.itkDiscretePrincipalCurvaturesQuadEdgeMeshFilterQEMD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    OutputIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDiscreteMaximumCurvatureQuadEdgeMeshFilterQEMD2___New_orig__: Any
itkDiscreteMaximumCurvatureQuadEdgeMeshFilterQEMD2_cast: Any

def itkDiscreteMaximumCurvatureQuadEdgeMeshFilterQEMD3_New(): ...

class itkDiscreteMaximumCurvatureQuadEdgeMeshFilterQEMD3(itk.itkDiscretePrincipalCurvaturesQuadEdgeMeshFilterPython.itkDiscretePrincipalCurvaturesQuadEdgeMeshFilterQEMD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    OutputIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDiscreteMaximumCurvatureQuadEdgeMeshFilterQEMD3___New_orig__: Any
itkDiscreteMaximumCurvatureQuadEdgeMeshFilterQEMD3_cast: Any

def discrete_maximum_curvature_quad_edge_mesh_filter(*args: Any, **kwargs: Any): ...
def discrete_maximum_curvature_quad_edge_mesh_filter_init_docstring() -> None: ...
