import itk.itkTransformBasePython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkEuler3DTransformD_New(): ...

class itkEuler3DTransformD(itk.itkRigid3DTransformPython.itkRigid3DTransformD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetRotation: Any = ...
    GetAngleX: Any = ...
    GetAngleY: Any = ...
    GetAngleZ: Any = ...
    SetComputeZYX: Any = ...
    GetComputeZYX: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkEuler3DTransformD___New_orig__: Any
itkEuler3DTransformD_cast: Any
