import itk.itkArrayPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkExpandImageFilterIF2IF2_New(): ...

class itkExpandImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    SetExpandFactors: Any = ...
    GetExpandFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExpandImageFilterIF2IF2___New_orig__: Any
itkExpandImageFilterIF2IF2_cast: Any

def itkExpandImageFilterIF3IF3_New(): ...

class itkExpandImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    SetExpandFactors: Any = ...
    GetExpandFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExpandImageFilterIF3IF3___New_orig__: Any
itkExpandImageFilterIF3IF3_cast: Any

def itkExpandImageFilterISS2ISS2_New(): ...

class itkExpandImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    SetExpandFactors: Any = ...
    GetExpandFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExpandImageFilterISS2ISS2___New_orig__: Any
itkExpandImageFilterISS2ISS2_cast: Any

def itkExpandImageFilterISS3ISS3_New(): ...

class itkExpandImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    SetExpandFactors: Any = ...
    GetExpandFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExpandImageFilterISS3ISS3___New_orig__: Any
itkExpandImageFilterISS3ISS3_cast: Any

def itkExpandImageFilterIUC2IUC2_New(): ...

class itkExpandImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    SetExpandFactors: Any = ...
    GetExpandFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExpandImageFilterIUC2IUC2___New_orig__: Any
itkExpandImageFilterIUC2IUC2_cast: Any

def itkExpandImageFilterIUC3IUC3_New(): ...

class itkExpandImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    SetExpandFactors: Any = ...
    GetExpandFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExpandImageFilterIUC3IUC3___New_orig__: Any
itkExpandImageFilterIUC3IUC3_cast: Any

def itkExpandImageFilterIVF22IVF22_New(): ...

class itkExpandImageFilterIVF22IVF22(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF22IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    SetExpandFactors: Any = ...
    GetExpandFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExpandImageFilterIVF22IVF22___New_orig__: Any
itkExpandImageFilterIVF22IVF22_cast: Any

def itkExpandImageFilterIVF23IVF23_New(): ...

class itkExpandImageFilterIVF23IVF23(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF23IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    SetExpandFactors: Any = ...
    GetExpandFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExpandImageFilterIVF23IVF23___New_orig__: Any
itkExpandImageFilterIVF23IVF23_cast: Any

def itkExpandImageFilterIVF32IVF32_New(): ...

class itkExpandImageFilterIVF32IVF32(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF32IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    SetExpandFactors: Any = ...
    GetExpandFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExpandImageFilterIVF32IVF32___New_orig__: Any
itkExpandImageFilterIVF32IVF32_cast: Any

def itkExpandImageFilterIVF33IVF33_New(): ...

class itkExpandImageFilterIVF33IVF33(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF33IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    SetExpandFactors: Any = ...
    GetExpandFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExpandImageFilterIVF33IVF33___New_orig__: Any
itkExpandImageFilterIVF33IVF33_cast: Any

def itkExpandImageFilterIVF42IVF42_New(): ...

class itkExpandImageFilterIVF42IVF42(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF42IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    SetExpandFactors: Any = ...
    GetExpandFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExpandImageFilterIVF42IVF42___New_orig__: Any
itkExpandImageFilterIVF42IVF42_cast: Any

def itkExpandImageFilterIVF43IVF43_New(): ...

class itkExpandImageFilterIVF43IVF43(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF43IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    SetExpandFactors: Any = ...
    GetExpandFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExpandImageFilterIVF43IVF43___New_orig__: Any
itkExpandImageFilterIVF43IVF43_cast: Any

def expand_image_filter(*args: Any, **kwargs: Any): ...
def expand_image_filter_init_docstring() -> None: ...
