import itk.itkPointSetPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkElasticBodySplineKernelTransformD2_New(): ...

class itkElasticBodySplineKernelTransformD2(itk.itkKernelTransformPython.itkKernelTransformD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkElasticBodySplineKernelTransformD2___New_orig__: Any
itkElasticBodySplineKernelTransformD2_cast: Any

def itkElasticBodySplineKernelTransformD3_New(): ...

class itkElasticBodySplineKernelTransformD3(itk.itkKernelTransformPython.itkKernelTransformD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkElasticBodySplineKernelTransformD3___New_orig__: Any
itkElasticBodySplineKernelTransformD3_cast: Any
