import itk.itkImageRegionPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkEuclideanDistanceMetricVF2_New(): ...

class itkEuclideanDistanceMetricVF2(itk.itkDistanceMetricPython.itkDistanceMetricVF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkEuclideanDistanceMetricVF2___New_orig__: Any
itkEuclideanDistanceMetricVF2_cast: Any

def itkEuclideanDistanceMetricVF3_New(): ...

class itkEuclideanDistanceMetricVF3(itk.itkDistanceMetricPython.itkDistanceMetricVF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkEuclideanDistanceMetricVF3___New_orig__: Any
itkEuclideanDistanceMetricVF3_cast: Any
