import itk.itkContinuousIndexPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkExpectationBasedPointSetToPointSetMetricv4PSD2_New(): ...

class itkExpectationBasedPointSetToPointSetMetricv4PSD2(itk.itkEuclideanDistancePointSetToPointSetMetricPython.itkEuclideanDistancePointSetToPointSetMetricv4PSD2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    GetLocalNeighborhoodValue: Any = ...
    GetLocalNeighborhoodValueAndDerivative: Any = ...
    SetPointSetSigma: Any = ...
    GetPointSetSigma: Any = ...
    SetEvaluationKNeighborhood: Any = ...
    GetEvaluationKNeighborhood: Any = ...
    InternalClone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExpectationBasedPointSetToPointSetMetricv4PSD2___New_orig__: Any
itkExpectationBasedPointSetToPointSetMetricv4PSD2_cast: Any

def itkExpectationBasedPointSetToPointSetMetricv4PSD3_New(): ...

class itkExpectationBasedPointSetToPointSetMetricv4PSD3(itk.itkEuclideanDistancePointSetToPointSetMetricPython.itkEuclideanDistancePointSetToPointSetMetricv4PSD3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    GetLocalNeighborhoodValue: Any = ...
    GetLocalNeighborhoodValueAndDerivative: Any = ...
    SetPointSetSigma: Any = ...
    GetPointSetSigma: Any = ...
    SetEvaluationKNeighborhood: Any = ...
    GetEvaluationKNeighborhood: Any = ...
    InternalClone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExpectationBasedPointSetToPointSetMetricv4PSD3___New_orig__: Any
itkExpectationBasedPointSetToPointSetMetricv4PSD3_cast: Any

def itkExpectationBasedPointSetToPointSetMetricv4PSF2_New(): ...

class itkExpectationBasedPointSetToPointSetMetricv4PSF2(itk.itkEuclideanDistancePointSetToPointSetMetricPython.itkEuclideanDistancePointSetToPointSetMetricv4PSF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    GetLocalNeighborhoodValue: Any = ...
    GetLocalNeighborhoodValueAndDerivative: Any = ...
    SetPointSetSigma: Any = ...
    GetPointSetSigma: Any = ...
    SetEvaluationKNeighborhood: Any = ...
    GetEvaluationKNeighborhood: Any = ...
    InternalClone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExpectationBasedPointSetToPointSetMetricv4PSF2___New_orig__: Any
itkExpectationBasedPointSetToPointSetMetricv4PSF2_cast: Any

def itkExpectationBasedPointSetToPointSetMetricv4PSF3_New(): ...

class itkExpectationBasedPointSetToPointSetMetricv4PSF3(itk.itkEuclideanDistancePointSetToPointSetMetricPython.itkEuclideanDistancePointSetToPointSetMetricv4PSF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    GetLocalNeighborhoodValue: Any = ...
    GetLocalNeighborhoodValueAndDerivative: Any = ...
    SetPointSetSigma: Any = ...
    GetPointSetSigma: Any = ...
    SetEvaluationKNeighborhood: Any = ...
    GetEvaluationKNeighborhood: Any = ...
    InternalClone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExpectationBasedPointSetToPointSetMetricv4PSF3___New_orig__: Any
itkExpectationBasedPointSetToPointSetMetricv4PSF3_cast: Any

def itkExpectationBasedPointSetToPointSetMetricv4PSSS2_New(): ...

class itkExpectationBasedPointSetToPointSetMetricv4PSSS2(itk.itkEuclideanDistancePointSetToPointSetMetricPython.itkEuclideanDistancePointSetToPointSetMetricv4PSSS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    GetLocalNeighborhoodValue: Any = ...
    GetLocalNeighborhoodValueAndDerivative: Any = ...
    SetPointSetSigma: Any = ...
    GetPointSetSigma: Any = ...
    SetEvaluationKNeighborhood: Any = ...
    GetEvaluationKNeighborhood: Any = ...
    InternalClone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExpectationBasedPointSetToPointSetMetricv4PSSS2___New_orig__: Any
itkExpectationBasedPointSetToPointSetMetricv4PSSS2_cast: Any

def itkExpectationBasedPointSetToPointSetMetricv4PSSS3_New(): ...

class itkExpectationBasedPointSetToPointSetMetricv4PSSS3(itk.itkEuclideanDistancePointSetToPointSetMetricPython.itkEuclideanDistancePointSetToPointSetMetricv4PSSS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    GetLocalNeighborhoodValue: Any = ...
    GetLocalNeighborhoodValueAndDerivative: Any = ...
    SetPointSetSigma: Any = ...
    GetPointSetSigma: Any = ...
    SetEvaluationKNeighborhood: Any = ...
    GetEvaluationKNeighborhood: Any = ...
    InternalClone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExpectationBasedPointSetToPointSetMetricv4PSSS3___New_orig__: Any
itkExpectationBasedPointSetToPointSetMetricv4PSSS3_cast: Any

def itkExpectationBasedPointSetToPointSetMetricv4PSUC2_New(): ...

class itkExpectationBasedPointSetToPointSetMetricv4PSUC2(itk.itkEuclideanDistancePointSetToPointSetMetricPython.itkEuclideanDistancePointSetToPointSetMetricv4PSUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    GetLocalNeighborhoodValue: Any = ...
    GetLocalNeighborhoodValueAndDerivative: Any = ...
    SetPointSetSigma: Any = ...
    GetPointSetSigma: Any = ...
    SetEvaluationKNeighborhood: Any = ...
    GetEvaluationKNeighborhood: Any = ...
    InternalClone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExpectationBasedPointSetToPointSetMetricv4PSUC2___New_orig__: Any
itkExpectationBasedPointSetToPointSetMetricv4PSUC2_cast: Any

def itkExpectationBasedPointSetToPointSetMetricv4PSUC3_New(): ...

class itkExpectationBasedPointSetToPointSetMetricv4PSUC3(itk.itkEuclideanDistancePointSetToPointSetMetricPython.itkEuclideanDistancePointSetToPointSetMetricv4PSUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    GetLocalNeighborhoodValue: Any = ...
    GetLocalNeighborhoodValueAndDerivative: Any = ...
    SetPointSetSigma: Any = ...
    GetPointSetSigma: Any = ...
    SetEvaluationKNeighborhood: Any = ...
    GetEvaluationKNeighborhood: Any = ...
    InternalClone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExpectationBasedPointSetToPointSetMetricv4PSUC3___New_orig__: Any
itkExpectationBasedPointSetToPointSetMetricv4PSUC3_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSD2_Superclass_Superclass(itk.itkOptimizerParameterScalesEstimatorPython.itkOptimizerParameterScalesEstimatorTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMetric: Any = ...
    SetTransformForward: Any = ...
    GetTransformForward: Any = ...
    SetVirtualDomainPointSet: Any = ...
    GetVirtualDomainPointSet: Any = ...
    SetCentralRegionRadius: Any = ...
    SetScalesSamplingStrategy: Any = ...
    SetStepScaleSamplingStrategy: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSD2_Superclass_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSD3_Superclass_Superclass(itk.itkOptimizerParameterScalesEstimatorPython.itkOptimizerParameterScalesEstimatorTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMetric: Any = ...
    SetTransformForward: Any = ...
    GetTransformForward: Any = ...
    SetVirtualDomainPointSet: Any = ...
    GetVirtualDomainPointSet: Any = ...
    SetCentralRegionRadius: Any = ...
    SetScalesSamplingStrategy: Any = ...
    SetStepScaleSamplingStrategy: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSD3_Superclass_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSF2_Superclass_Superclass(itk.itkOptimizerParameterScalesEstimatorPython.itkOptimizerParameterScalesEstimatorTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMetric: Any = ...
    SetTransformForward: Any = ...
    GetTransformForward: Any = ...
    SetVirtualDomainPointSet: Any = ...
    GetVirtualDomainPointSet: Any = ...
    SetCentralRegionRadius: Any = ...
    SetScalesSamplingStrategy: Any = ...
    SetStepScaleSamplingStrategy: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSF2_Superclass_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSF3_Superclass_Superclass(itk.itkOptimizerParameterScalesEstimatorPython.itkOptimizerParameterScalesEstimatorTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMetric: Any = ...
    SetTransformForward: Any = ...
    GetTransformForward: Any = ...
    SetVirtualDomainPointSet: Any = ...
    GetVirtualDomainPointSet: Any = ...
    SetCentralRegionRadius: Any = ...
    SetScalesSamplingStrategy: Any = ...
    SetStepScaleSamplingStrategy: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSF3_Superclass_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSSS2_Superclass_Superclass(itk.itkOptimizerParameterScalesEstimatorPython.itkOptimizerParameterScalesEstimatorTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMetric: Any = ...
    SetTransformForward: Any = ...
    GetTransformForward: Any = ...
    SetVirtualDomainPointSet: Any = ...
    GetVirtualDomainPointSet: Any = ...
    SetCentralRegionRadius: Any = ...
    SetScalesSamplingStrategy: Any = ...
    SetStepScaleSamplingStrategy: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSSS2_Superclass_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSSS3_Superclass_Superclass(itk.itkOptimizerParameterScalesEstimatorPython.itkOptimizerParameterScalesEstimatorTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMetric: Any = ...
    SetTransformForward: Any = ...
    GetTransformForward: Any = ...
    SetVirtualDomainPointSet: Any = ...
    GetVirtualDomainPointSet: Any = ...
    SetCentralRegionRadius: Any = ...
    SetScalesSamplingStrategy: Any = ...
    SetStepScaleSamplingStrategy: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSSS3_Superclass_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSUC2_Superclass_Superclass(itk.itkOptimizerParameterScalesEstimatorPython.itkOptimizerParameterScalesEstimatorTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMetric: Any = ...
    SetTransformForward: Any = ...
    GetTransformForward: Any = ...
    SetVirtualDomainPointSet: Any = ...
    GetVirtualDomainPointSet: Any = ...
    SetCentralRegionRadius: Any = ...
    SetScalesSamplingStrategy: Any = ...
    SetStepScaleSamplingStrategy: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSUC2_Superclass_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSUC3_Superclass_Superclass(itk.itkOptimizerParameterScalesEstimatorPython.itkOptimizerParameterScalesEstimatorTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMetric: Any = ...
    SetTransformForward: Any = ...
    GetTransformForward: Any = ...
    SetVirtualDomainPointSet: Any = ...
    GetVirtualDomainPointSet: Any = ...
    SetCentralRegionRadius: Any = ...
    SetScalesSamplingStrategy: Any = ...
    SetStepScaleSamplingStrategy: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSUC3_Superclass_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSD2_Superclass(itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSD2_Superclass_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetSmallParameterVariation: Any = ...
    GetSmallParameterVariation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSD2_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSD3_Superclass(itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSD3_Superclass_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetSmallParameterVariation: Any = ...
    GetSmallParameterVariation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSD3_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSF2_Superclass(itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSF2_Superclass_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetSmallParameterVariation: Any = ...
    GetSmallParameterVariation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSF2_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSF3_Superclass(itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSF3_Superclass_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetSmallParameterVariation: Any = ...
    GetSmallParameterVariation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSF3_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSSS2_Superclass(itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSSS2_Superclass_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetSmallParameterVariation: Any = ...
    GetSmallParameterVariation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSSS2_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSSS3_Superclass(itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSSS3_Superclass_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetSmallParameterVariation: Any = ...
    GetSmallParameterVariation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSSS3_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSUC2_Superclass(itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSUC2_Superclass_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetSmallParameterVariation: Any = ...
    GetSmallParameterVariation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSUC2_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSUC3_Superclass(itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSUC3_Superclass_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetSmallParameterVariation: Any = ...
    GetSmallParameterVariation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSUC3_Superclass_cast: Any

def itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSD2_New(): ...

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSD2(itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSD2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSD2___New_orig__: Any
itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSD2_cast: Any

def itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSD3_New(): ...

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSD3(itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSD3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSD3___New_orig__: Any
itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSD3_cast: Any

def itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSF2_New(): ...

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSF2(itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSF2___New_orig__: Any
itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSF2_cast: Any

def itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSF3_New(): ...

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSF3(itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSF3___New_orig__: Any
itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSF3_cast: Any

def itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSSS2_New(): ...

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSSS2(itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSSS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSSS2___New_orig__: Any
itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSSS2_cast: Any

def itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSSS3_New(): ...

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSSS3(itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSSS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSSS3___New_orig__: Any
itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSSS3_cast: Any

def itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSUC2_New(): ...

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSUC2(itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSUC2___New_orig__: Any
itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSUC2_cast: Any

def itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSUC3_New(): ...

class itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSUC3(itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSUC3___New_orig__: Any
itkRegistrationParameterScalesFromPhysicalShiftEBPSTPSMPSUC3_cast: Any
