import itk.itkPointSetPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkElasticBodyReciprocalSplineKernelTransformD2_New(): ...

class itkElasticBodyReciprocalSplineKernelTransformD2(itk.itkKernelTransformPython.itkKernelTransformD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkElasticBodyReciprocalSplineKernelTransformD2___New_orig__: Any
itkElasticBodyReciprocalSplineKernelTransformD2_cast: Any

def itkElasticBodyReciprocalSplineKernelTransformD3_New(): ...

class itkElasticBodyReciprocalSplineKernelTransformD3(itk.itkKernelTransformPython.itkKernelTransformD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkElasticBodyReciprocalSplineKernelTransformD3___New_orig__: Any
itkElasticBodyReciprocalSplineKernelTransformD3_cast: Any
