import itk.itkCostFunctionPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkExhaustiveOptimizerv4D_New(): ...

class itkExhaustiveOptimizerv4D(itk.itkObjectToObjectOptimizerBasePython.itkObjectToObjectOptimizerBaseTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    StartOptimization: Any = ...
    StartWalking: Any = ...
    ResumeWalking: Any = ...
    StopWalking: Any = ...
    SetStepLength: Any = ...
    SetNumberOfSteps: Any = ...
    GetStepLength: Any = ...
    GetNumberOfSteps: Any = ...
    GetCurrentValue: Any = ...
    GetMaximumMetricValue: Any = ...
    GetMinimumMetricValue: Any = ...
    GetMinimumMetricValuePosition: Any = ...
    GetMaximumMetricValuePosition: Any = ...
    GetCurrentIndex: Any = ...
    SetInitialPosition: Any = ...
    GetInitialPosition: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExhaustiveOptimizerv4D___New_orig__: Any
itkExhaustiveOptimizerv4D_cast: Any

def itkExhaustiveOptimizerv4F_New(): ...

class itkExhaustiveOptimizerv4F(itk.itkObjectToObjectOptimizerBasePython.itkObjectToObjectOptimizerBaseTemplateF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    StartOptimization: Any = ...
    StartWalking: Any = ...
    ResumeWalking: Any = ...
    StopWalking: Any = ...
    SetStepLength: Any = ...
    SetNumberOfSteps: Any = ...
    GetStepLength: Any = ...
    GetNumberOfSteps: Any = ...
    GetCurrentValue: Any = ...
    GetMaximumMetricValue: Any = ...
    GetMinimumMetricValue: Any = ...
    GetMinimumMetricValuePosition: Any = ...
    GetMaximumMetricValuePosition: Any = ...
    GetCurrentIndex: Any = ...
    SetInitialPosition: Any = ...
    GetInitialPosition: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExhaustiveOptimizerv4F___New_orig__: Any
itkExhaustiveOptimizerv4F_cast: Any
