import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkExtractImageFilterEnums:
    thisown: Any = ...
    DirectionCollapseStrategy_DIRECTIONCOLLAPSETOUNKOWN: Any = ...
    DirectionCollapseStrategy_DIRECTIONCOLLAPSETOIDENTITY: Any = ...
    DirectionCollapseStrategy_DIRECTIONCOLLAPSETOSUBMATRIX: Any = ...
    DirectionCollapseStrategy_DIRECTIONCOLLAPSETOGUESS: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...

def itkExtractImageFilterICF2ICF2_New(): ...

class itkExtractImageFilterICF2ICF2(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterICF2ICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterICF2ICF2___New_orig__: Any
itkExtractImageFilterICF2ICF2_cast: Any

def itkExtractImageFilterICF3ICF2_New(): ...

class itkExtractImageFilterICF3ICF2(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterICF3ICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterICF3ICF2___New_orig__: Any
itkExtractImageFilterICF3ICF2_cast: Any

def itkExtractImageFilterICF3ICF3_New(): ...

class itkExtractImageFilterICF3ICF3(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterICF3ICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterICF3ICF3___New_orig__: Any
itkExtractImageFilterICF3ICF3_cast: Any

def itkExtractImageFilterICVF22ICVF22_New(): ...

class itkExtractImageFilterICVF22ICVF22(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterICVF22ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterICVF22ICVF22___New_orig__: Any
itkExtractImageFilterICVF22ICVF22_cast: Any

def itkExtractImageFilterICVF23ICVF23_New(): ...

class itkExtractImageFilterICVF23ICVF23(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterICVF23ICVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterICVF23ICVF23___New_orig__: Any
itkExtractImageFilterICVF23ICVF23_cast: Any

def itkExtractImageFilterICVF32ICVF32_New(): ...

class itkExtractImageFilterICVF32ICVF32(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterICVF32ICVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterICVF32ICVF32___New_orig__: Any
itkExtractImageFilterICVF32ICVF32_cast: Any

def itkExtractImageFilterICVF33ICVF33_New(): ...

class itkExtractImageFilterICVF33ICVF33(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterICVF33ICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterICVF33ICVF33___New_orig__: Any
itkExtractImageFilterICVF33ICVF33_cast: Any

def itkExtractImageFilterICVF42ICVF42_New(): ...

class itkExtractImageFilterICVF42ICVF42(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterICVF42ICVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterICVF42ICVF42___New_orig__: Any
itkExtractImageFilterICVF42ICVF42_cast: Any

def itkExtractImageFilterICVF43ICVF43_New(): ...

class itkExtractImageFilterICVF43ICVF43(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterICVF43ICVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterICVF43ICVF43___New_orig__: Any
itkExtractImageFilterICVF43ICVF43_cast: Any

def itkExtractImageFilterIF2IF2_New(): ...

class itkExtractImageFilterIF2IF2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterIF2IF2___New_orig__: Any
itkExtractImageFilterIF2IF2_cast: Any

def itkExtractImageFilterIF3IF2_New(): ...

class itkExtractImageFilterIF3IF2(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterIF3IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterIF3IF2___New_orig__: Any
itkExtractImageFilterIF3IF2_cast: Any

def itkExtractImageFilterIF3IF3_New(): ...

class itkExtractImageFilterIF3IF3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterIF3IF3___New_orig__: Any
itkExtractImageFilterIF3IF3_cast: Any

def itkExtractImageFilterIRGBAUC2IRGBAUC2_New(): ...

class itkExtractImageFilterIRGBAUC2IRGBAUC2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIRGBAUC2IRGBAUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterIRGBAUC2IRGBAUC2___New_orig__: Any
itkExtractImageFilterIRGBAUC2IRGBAUC2_cast: Any

def itkExtractImageFilterIRGBAUC3IRGBAUC3_New(): ...

class itkExtractImageFilterIRGBAUC3IRGBAUC3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIRGBAUC3IRGBAUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterIRGBAUC3IRGBAUC3___New_orig__: Any
itkExtractImageFilterIRGBAUC3IRGBAUC3_cast: Any

def itkExtractImageFilterIRGBUC2IRGBUC2_New(): ...

class itkExtractImageFilterIRGBUC2IRGBUC2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIRGBUC2IRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterIRGBUC2IRGBUC2___New_orig__: Any
itkExtractImageFilterIRGBUC2IRGBUC2_cast: Any

def itkExtractImageFilterIRGBUC3IRGBUC2_New(): ...

class itkExtractImageFilterIRGBUC3IRGBUC2(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterIRGBUC3IRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterIRGBUC3IRGBUC2___New_orig__: Any
itkExtractImageFilterIRGBUC3IRGBUC2_cast: Any

def itkExtractImageFilterIRGBUC3IRGBUC3_New(): ...

class itkExtractImageFilterIRGBUC3IRGBUC3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIRGBUC3IRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterIRGBUC3IRGBUC3___New_orig__: Any
itkExtractImageFilterIRGBUC3IRGBUC3_cast: Any

def itkExtractImageFilterISS2ISS2_New(): ...

class itkExtractImageFilterISS2ISS2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterISS2ISS2___New_orig__: Any
itkExtractImageFilterISS2ISS2_cast: Any

def itkExtractImageFilterISS3ISS2_New(): ...

class itkExtractImageFilterISS3ISS2(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterISS3ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterISS3ISS2___New_orig__: Any
itkExtractImageFilterISS3ISS2_cast: Any

def itkExtractImageFilterISS3ISS3_New(): ...

class itkExtractImageFilterISS3ISS3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterISS3ISS3___New_orig__: Any
itkExtractImageFilterISS3ISS3_cast: Any

def itkExtractImageFilterIUC2IUC2_New(): ...

class itkExtractImageFilterIUC2IUC2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterIUC2IUC2___New_orig__: Any
itkExtractImageFilterIUC2IUC2_cast: Any

def itkExtractImageFilterIUC3IUC2_New(): ...

class itkExtractImageFilterIUC3IUC2(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterIUC3IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterIUC3IUC2___New_orig__: Any
itkExtractImageFilterIUC3IUC2_cast: Any

def itkExtractImageFilterIUC3IUC3_New(): ...

class itkExtractImageFilterIUC3IUC3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterIUC3IUC3___New_orig__: Any
itkExtractImageFilterIUC3IUC3_cast: Any

def itkExtractImageFilterIUL2IUL2_New(): ...

class itkExtractImageFilterIUL2IUL2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUL2IUL2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterIUL2IUL2___New_orig__: Any
itkExtractImageFilterIUL2IUL2_cast: Any

def itkExtractImageFilterIUL3IUL3_New(): ...

class itkExtractImageFilterIUL3IUL3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUL3IUL3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterIUL3IUL3___New_orig__: Any
itkExtractImageFilterIUL3IUL3_cast: Any

def itkExtractImageFilterIVF22IVF22_New(): ...

class itkExtractImageFilterIVF22IVF22(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIVF22IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterIVF22IVF22___New_orig__: Any
itkExtractImageFilterIVF22IVF22_cast: Any

def itkExtractImageFilterIVF23IVF23_New(): ...

class itkExtractImageFilterIVF23IVF23(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIVF23IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterIVF23IVF23___New_orig__: Any
itkExtractImageFilterIVF23IVF23_cast: Any

def itkExtractImageFilterIVF32IVF32_New(): ...

class itkExtractImageFilterIVF32IVF32(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIVF32IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterIVF32IVF32___New_orig__: Any
itkExtractImageFilterIVF32IVF32_cast: Any

def itkExtractImageFilterIVF33IVF33_New(): ...

class itkExtractImageFilterIVF33IVF33(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIVF33IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterIVF33IVF33___New_orig__: Any
itkExtractImageFilterIVF33IVF33_cast: Any

def itkExtractImageFilterIVF42IVF42_New(): ...

class itkExtractImageFilterIVF42IVF42(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIVF42IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterIVF42IVF42___New_orig__: Any
itkExtractImageFilterIVF42IVF42_cast: Any

def itkExtractImageFilterIVF43IVF43_New(): ...

class itkExtractImageFilterIVF43IVF43(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIVF43IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectionCollapseToStrategy: Any = ...
    GetDirectionCollapseToStrategy: Any = ...
    SetDirectionCollapseToGuess: Any = ...
    SetDirectionCollapseToIdentity: Any = ...
    SetDirectionCollapseToSubmatrix: Any = ...
    SetExtractionRegion: Any = ...
    GetExtractionRegion: Any = ...
    InputCovertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExtractImageFilterIVF43IVF43___New_orig__: Any
itkExtractImageFilterIVF43IVF43_cast: Any

def extract_image_filter(*args: Any, **kwargs: Any): ...
def extract_image_filter_init_docstring() -> None: ...
