import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkFFTNormalizedCorrelationImageFilterIF2IF2_New(): ...

class itkFFTNormalizedCorrelationImageFilterIF2IF2(itk.itkMaskedFFTNormalizedCorrelationImageFilterPython.itkMaskedFFTNormalizedCorrelationImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFFTNormalizedCorrelationImageFilterIF2IF2___New_orig__: Any
itkFFTNormalizedCorrelationImageFilterIF2IF2_cast: Any

def itkFFTNormalizedCorrelationImageFilterIF3IF3_New(): ...

class itkFFTNormalizedCorrelationImageFilterIF3IF3(itk.itkMaskedFFTNormalizedCorrelationImageFilterPython.itkMaskedFFTNormalizedCorrelationImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFFTNormalizedCorrelationImageFilterIF3IF3___New_orig__: Any
itkFFTNormalizedCorrelationImageFilterIF3IF3_cast: Any

def itkFFTNormalizedCorrelationImageFilterISS2IF2_New(): ...

class itkFFTNormalizedCorrelationImageFilterISS2IF2(itk.itkMaskedFFTNormalizedCorrelationImageFilterPython.itkMaskedFFTNormalizedCorrelationImageFilterISS2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFFTNormalizedCorrelationImageFilterISS2IF2___New_orig__: Any
itkFFTNormalizedCorrelationImageFilterISS2IF2_cast: Any

def itkFFTNormalizedCorrelationImageFilterISS3IF3_New(): ...

class itkFFTNormalizedCorrelationImageFilterISS3IF3(itk.itkMaskedFFTNormalizedCorrelationImageFilterPython.itkMaskedFFTNormalizedCorrelationImageFilterISS3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFFTNormalizedCorrelationImageFilterISS3IF3___New_orig__: Any
itkFFTNormalizedCorrelationImageFilterISS3IF3_cast: Any

def itkFFTNormalizedCorrelationImageFilterIUC2IF2_New(): ...

class itkFFTNormalizedCorrelationImageFilterIUC2IF2(itk.itkMaskedFFTNormalizedCorrelationImageFilterPython.itkMaskedFFTNormalizedCorrelationImageFilterIUC2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFFTNormalizedCorrelationImageFilterIUC2IF2___New_orig__: Any
itkFFTNormalizedCorrelationImageFilterIUC2IF2_cast: Any

def itkFFTNormalizedCorrelationImageFilterIUC3IF3_New(): ...

class itkFFTNormalizedCorrelationImageFilterIUC3IF3(itk.itkMaskedFFTNormalizedCorrelationImageFilterPython.itkMaskedFFTNormalizedCorrelationImageFilterIUC3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFFTNormalizedCorrelationImageFilterIUC3IF3___New_orig__: Any
itkFFTNormalizedCorrelationImageFilterIUC3IF3_cast: Any

def fft_normalized_correlation_image_filter(*args: Any, **kwargs: Any): ...
def fft_normalized_correlation_image_filter_init_docstring() -> None: ...
