import itk.itkMeshIOBasePython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkFreeSurferBinaryMeshIO_New(): ...

class itkFreeSurferBinaryMeshIO(itk.itkMeshIOBasePython.itkMeshIOBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFreeSurferBinaryMeshIO___New_orig__: Any
itkFreeSurferBinaryMeshIO_cast: Any

def itkFreeSurferBinaryMeshIOFactory_New(): ...

class itkFreeSurferBinaryMeshIOFactory(itk.ITKCommonBasePython.itkObjectFactoryBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    RegisterOneFactory: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFreeSurferBinaryMeshIOFactory___New_orig__: Any
itkFreeSurferBinaryMeshIOFactory_RegisterOneFactory: Any
itkFreeSurferBinaryMeshIOFactory_cast: Any
