import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkFastChamferDistanceImageFilterIF2IF2_New(): ...

class itkFastChamferDistanceImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetWeights: Any = ...
    GetWeights: Any = ...
    SetMaximumDistance: Any = ...
    GetMaximumDistance: Any = ...
    SetRegionToProcess: Any = ...
    GetRegionToProcess: Any = ...
    SetNarrowBand: Any = ...
    GetNarrowBand: Any = ...
    SameDimensionCheck: Any = ...
    SameTypeCheck: Any = ...
    FloatConvertibleToPixelTypeCheck: Any = ...
    PixelTypeConvertibleToFloatCheck: Any = ...
    PixelTypeGreaterThanFloatCheck: Any = ...
    PixelTypeLessThanFloatCheck: Any = ...
    PixelTypeFloatAdditiveOperatorsCheck: Any = ...
    FloatGreaterThanPixelTypeCheck: Any = ...
    FloatLessThanPixelTypeCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFastChamferDistanceImageFilterIF2IF2___New_orig__: Any
itkFastChamferDistanceImageFilterIF2IF2_cast: Any

def itkFastChamferDistanceImageFilterIF3IF3_New(): ...

class itkFastChamferDistanceImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetWeights: Any = ...
    GetWeights: Any = ...
    SetMaximumDistance: Any = ...
    GetMaximumDistance: Any = ...
    SetRegionToProcess: Any = ...
    GetRegionToProcess: Any = ...
    SetNarrowBand: Any = ...
    GetNarrowBand: Any = ...
    SameDimensionCheck: Any = ...
    SameTypeCheck: Any = ...
    FloatConvertibleToPixelTypeCheck: Any = ...
    PixelTypeConvertibleToFloatCheck: Any = ...
    PixelTypeGreaterThanFloatCheck: Any = ...
    PixelTypeLessThanFloatCheck: Any = ...
    PixelTypeFloatAdditiveOperatorsCheck: Any = ...
    FloatGreaterThanPixelTypeCheck: Any = ...
    FloatLessThanPixelTypeCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFastChamferDistanceImageFilterIF3IF3___New_orig__: Any
itkFastChamferDistanceImageFilterIF3IF3_cast: Any

def itkFastChamferDistanceImageFilterISS2ISS2_New(): ...

class itkFastChamferDistanceImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetWeights: Any = ...
    GetWeights: Any = ...
    SetMaximumDistance: Any = ...
    GetMaximumDistance: Any = ...
    SetRegionToProcess: Any = ...
    GetRegionToProcess: Any = ...
    SetNarrowBand: Any = ...
    GetNarrowBand: Any = ...
    SameDimensionCheck: Any = ...
    SameTypeCheck: Any = ...
    FloatConvertibleToPixelTypeCheck: Any = ...
    PixelTypeConvertibleToFloatCheck: Any = ...
    PixelTypeGreaterThanFloatCheck: Any = ...
    PixelTypeLessThanFloatCheck: Any = ...
    PixelTypeFloatAdditiveOperatorsCheck: Any = ...
    FloatGreaterThanPixelTypeCheck: Any = ...
    FloatLessThanPixelTypeCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFastChamferDistanceImageFilterISS2ISS2___New_orig__: Any
itkFastChamferDistanceImageFilterISS2ISS2_cast: Any

def itkFastChamferDistanceImageFilterISS3ISS3_New(): ...

class itkFastChamferDistanceImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetWeights: Any = ...
    GetWeights: Any = ...
    SetMaximumDistance: Any = ...
    GetMaximumDistance: Any = ...
    SetRegionToProcess: Any = ...
    GetRegionToProcess: Any = ...
    SetNarrowBand: Any = ...
    GetNarrowBand: Any = ...
    SameDimensionCheck: Any = ...
    SameTypeCheck: Any = ...
    FloatConvertibleToPixelTypeCheck: Any = ...
    PixelTypeConvertibleToFloatCheck: Any = ...
    PixelTypeGreaterThanFloatCheck: Any = ...
    PixelTypeLessThanFloatCheck: Any = ...
    PixelTypeFloatAdditiveOperatorsCheck: Any = ...
    FloatGreaterThanPixelTypeCheck: Any = ...
    FloatLessThanPixelTypeCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFastChamferDistanceImageFilterISS3ISS3___New_orig__: Any
itkFastChamferDistanceImageFilterISS3ISS3_cast: Any

def fast_chamfer_distance_image_filter(*args: Any, **kwargs: Any): ...
def fast_chamfer_distance_image_filter_init_docstring() -> None: ...
