import itk.itkImageRegionPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkFastMarchingReachedTargetNodesStoppingCriterionEnums:
    thisown: Any = ...
    TargetCondition_OneTarget: Any = ...
    TargetCondition_SomeTargets: Any = ...
    TargetCondition_AllTargets: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...

def itkFastMarchingReachedTargetNodesStoppingCriterionIF2IF2_New(): ...

class itkFastMarchingReachedTargetNodesStoppingCriterionIF2IF2(itk.itkFastMarchingStoppingCriterionBasePython.itkFastMarchingStoppingCriterionBaseIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetTargetCondition: Any = ...
    GetTargetCondition: Any = ...
    SetTargetOffset: Any = ...
    GetTargetOffset: Any = ...
    SetNumberOfTargetsToBeReached: Any = ...
    SetTargetNodes: Any = ...
    SetCurrentNode: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFastMarchingReachedTargetNodesStoppingCriterionIF2IF2___New_orig__: Any
itkFastMarchingReachedTargetNodesStoppingCriterionIF2IF2_cast: Any

def itkFastMarchingReachedTargetNodesStoppingCriterionIF3IF3_New(): ...

class itkFastMarchingReachedTargetNodesStoppingCriterionIF3IF3(itk.itkFastMarchingStoppingCriterionBasePython.itkFastMarchingStoppingCriterionBaseIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetTargetCondition: Any = ...
    GetTargetCondition: Any = ...
    SetTargetOffset: Any = ...
    GetTargetOffset: Any = ...
    SetNumberOfTargetsToBeReached: Any = ...
    SetTargetNodes: Any = ...
    SetCurrentNode: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFastMarchingReachedTargetNodesStoppingCriterionIF3IF3___New_orig__: Any
itkFastMarchingReachedTargetNodesStoppingCriterionIF3IF3_cast: Any
