import itk.itkContinuousIndexPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkFastMarchingExtensionImageFilterIF2UC1IF2_New(): ...

class itkFastMarchingExtensionImageFilterIF2UC1IF2(itk.itkFastMarchingImageFilterPython.itkFastMarchingImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetAuxiliaryImage: Any = ...
    SetAuxiliaryAliveValues: Any = ...
    GetAuxiliaryAliveValues: Any = ...
    SetAuxiliaryTrialValues: Any = ...
    GetAuxiliaryTrialValues: Any = ...
    AuxValueHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFastMarchingExtensionImageFilterIF2UC1IF2___New_orig__: Any
itkFastMarchingExtensionImageFilterIF2UC1IF2_cast: Any

def itkFastMarchingExtensionImageFilterIF3UC1IF3_New(): ...

class itkFastMarchingExtensionImageFilterIF3UC1IF3(itk.itkFastMarchingImageFilterPython.itkFastMarchingImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetAuxiliaryImage: Any = ...
    SetAuxiliaryAliveValues: Any = ...
    GetAuxiliaryAliveValues: Any = ...
    SetAuxiliaryTrialValues: Any = ...
    GetAuxiliaryTrialValues: Any = ...
    AuxValueHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFastMarchingExtensionImageFilterIF3UC1IF3___New_orig__: Any
itkFastMarchingExtensionImageFilterIF3UC1IF3_cast: Any

def fast_marching_extension_image_filter(*args: Any, **kwargs: Any): ...
def fast_marching_extension_image_filter_init_docstring() -> None: ...
