import itk.itkFastMarchingStoppingCriterionBasePython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkFastMarchingImageFilterBaseIF2IF2_New(): ...

class itkFastMarchingImageFilterBaseIF2IF2(itk.ITKFastMarchingBasePython.itkFastMarchingBaseIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetModifiableLabelImage: Any = ...
    GetLabelImage: Any = ...
    SetOutputSize: Any = ...
    GetOutputSize: Any = ...
    SetOutputRegion: Any = ...
    GetOutputRegion: Any = ...
    SetOutputSpacing: Any = ...
    GetOutputSpacing: Any = ...
    SetOutputDirection: Any = ...
    GetOutputDirection: Any = ...
    SetOutputOrigin: Any = ...
    GetOutputOrigin: Any = ...
    SetOverrideOutputInformation: Any = ...
    GetOverrideOutputInformation: Any = ...
    OverrideOutputInformationOn: Any = ...
    OverrideOutputInformationOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFastMarchingImageFilterBaseIF2IF2___New_orig__: Any
itkFastMarchingImageFilterBaseIF2IF2_cast: Any

def itkFastMarchingImageFilterBaseIF3IF3_New(): ...

class itkFastMarchingImageFilterBaseIF3IF3(itk.ITKFastMarchingBasePython.itkFastMarchingBaseIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetModifiableLabelImage: Any = ...
    GetLabelImage: Any = ...
    SetOutputSize: Any = ...
    GetOutputSize: Any = ...
    SetOutputRegion: Any = ...
    GetOutputRegion: Any = ...
    SetOutputSpacing: Any = ...
    GetOutputSpacing: Any = ...
    SetOutputDirection: Any = ...
    GetOutputDirection: Any = ...
    SetOutputOrigin: Any = ...
    GetOutputOrigin: Any = ...
    SetOverrideOutputInformation: Any = ...
    GetOverrideOutputInformation: Any = ...
    OverrideOutputInformationOn: Any = ...
    OverrideOutputInformationOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFastMarchingImageFilterBaseIF3IF3___New_orig__: Any
itkFastMarchingImageFilterBaseIF3IF3_cast: Any

def fast_marching_image_filter_base(*args: Any, **kwargs: Any): ...
def fast_marching_image_filter_base_init_docstring() -> None: ...
