import itk.itkImageRegionPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkFunctionBaseCID2AD(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBaseCID2AD_cast: Any

class itkFunctionBaseCID3AD(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBaseCID3AD_cast: Any

class itkFunctionBaseCIF2AD(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBaseCIF2AD_cast: Any

class itkFunctionBaseCIF3AD(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBaseCIF3AD_cast: Any

class itkFunctionBaseFF(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBaseFF_cast: Any

class itkFunctionBaseIF2D(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBaseIF2D_cast: Any

class itkFunctionBaseIF3D(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBaseIF3D_cast: Any

class itkFunctionBasePD2CVD2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBasePD2CVD2_cast: Any

class itkFunctionBasePD2D(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBasePD2D_cast: Any

class itkFunctionBasePD2F(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBasePD2F_cast: Any

class itkFunctionBasePD2RGBAD(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBasePD2RGBAD_cast: Any

class itkFunctionBasePD2RGBAUC(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBasePD2RGBAUC_cast: Any

class itkFunctionBasePD2RGBD(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBasePD2RGBD_cast: Any

class itkFunctionBasePD2RGBUC(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBasePD2RGBUC_cast: Any

class itkFunctionBasePD2VD2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBasePD2VD2_cast: Any

class itkFunctionBasePD3CVD3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBasePD3CVD3_cast: Any

class itkFunctionBasePD3D(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBasePD3D_cast: Any

class itkFunctionBasePD3F(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBasePD3F_cast: Any

class itkFunctionBasePD3RGBAD(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBasePD3RGBAD_cast: Any

class itkFunctionBasePD3RGBAUC(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBasePD3RGBAUC_cast: Any

class itkFunctionBasePD3RGBD(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBasePD3RGBD_cast: Any

class itkFunctionBasePD3RGBUC(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBasePD3RGBUC_cast: Any

class itkFunctionBasePD3VD3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBasePD3VD3_cast: Any

class itkFunctionBasePF2D(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBasePF2D_cast: Any

class itkFunctionBasePF2F(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBasePF2F_cast: Any

class itkFunctionBasePF3D(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBasePF3D_cast: Any

class itkFunctionBasePF3F(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBasePF3F_cast: Any

class itkFunctionBaseVF2D(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBaseVF2D_cast: Any

class itkFunctionBaseVF3D(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Evaluate: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFunctionBaseVF3D_cast: Any
