import itk.itkSizePython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkFiniteDifferenceFunctionICVF22(itk.ITKCommonBasePython.itkLightObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    InitializeIteration: Any = ...
    ComputeUpdate: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetScaleCoefficients: Any = ...
    GetScaleCoefficients: Any = ...
    ComputeNeighborhoodScales: Any = ...
    ComputeGlobalTimeStep: Any = ...
    GetGlobalDataPointer: Any = ...
    ReleaseGlobalDataPointer: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceFunctionICVF22_cast: Any

class itkFiniteDifferenceFunctionICVF23(itk.ITKCommonBasePython.itkLightObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    InitializeIteration: Any = ...
    ComputeUpdate: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetScaleCoefficients: Any = ...
    GetScaleCoefficients: Any = ...
    ComputeNeighborhoodScales: Any = ...
    ComputeGlobalTimeStep: Any = ...
    GetGlobalDataPointer: Any = ...
    ReleaseGlobalDataPointer: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceFunctionICVF23_cast: Any

class itkFiniteDifferenceFunctionICVF32(itk.ITKCommonBasePython.itkLightObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    InitializeIteration: Any = ...
    ComputeUpdate: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetScaleCoefficients: Any = ...
    GetScaleCoefficients: Any = ...
    ComputeNeighborhoodScales: Any = ...
    ComputeGlobalTimeStep: Any = ...
    GetGlobalDataPointer: Any = ...
    ReleaseGlobalDataPointer: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceFunctionICVF32_cast: Any

class itkFiniteDifferenceFunctionICVF33(itk.ITKCommonBasePython.itkLightObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    InitializeIteration: Any = ...
    ComputeUpdate: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetScaleCoefficients: Any = ...
    GetScaleCoefficients: Any = ...
    ComputeNeighborhoodScales: Any = ...
    ComputeGlobalTimeStep: Any = ...
    GetGlobalDataPointer: Any = ...
    ReleaseGlobalDataPointer: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceFunctionICVF33_cast: Any

class itkFiniteDifferenceFunctionICVF42(itk.ITKCommonBasePython.itkLightObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    InitializeIteration: Any = ...
    ComputeUpdate: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetScaleCoefficients: Any = ...
    GetScaleCoefficients: Any = ...
    ComputeNeighborhoodScales: Any = ...
    ComputeGlobalTimeStep: Any = ...
    GetGlobalDataPointer: Any = ...
    ReleaseGlobalDataPointer: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceFunctionICVF42_cast: Any

class itkFiniteDifferenceFunctionICVF43(itk.ITKCommonBasePython.itkLightObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    InitializeIteration: Any = ...
    ComputeUpdate: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetScaleCoefficients: Any = ...
    GetScaleCoefficients: Any = ...
    ComputeNeighborhoodScales: Any = ...
    ComputeGlobalTimeStep: Any = ...
    GetGlobalDataPointer: Any = ...
    ReleaseGlobalDataPointer: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceFunctionICVF43_cast: Any

class itkFiniteDifferenceFunctionIF2(itk.ITKCommonBasePython.itkLightObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    InitializeIteration: Any = ...
    ComputeUpdate: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetScaleCoefficients: Any = ...
    GetScaleCoefficients: Any = ...
    ComputeNeighborhoodScales: Any = ...
    ComputeGlobalTimeStep: Any = ...
    GetGlobalDataPointer: Any = ...
    ReleaseGlobalDataPointer: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceFunctionIF2_cast: Any

class itkFiniteDifferenceFunctionIF3(itk.ITKCommonBasePython.itkLightObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    InitializeIteration: Any = ...
    ComputeUpdate: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetScaleCoefficients: Any = ...
    GetScaleCoefficients: Any = ...
    ComputeNeighborhoodScales: Any = ...
    ComputeGlobalTimeStep: Any = ...
    GetGlobalDataPointer: Any = ...
    ReleaseGlobalDataPointer: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceFunctionIF3_cast: Any

class itkFiniteDifferenceFunctionISS2(itk.ITKCommonBasePython.itkLightObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    InitializeIteration: Any = ...
    ComputeUpdate: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetScaleCoefficients: Any = ...
    GetScaleCoefficients: Any = ...
    ComputeNeighborhoodScales: Any = ...
    ComputeGlobalTimeStep: Any = ...
    GetGlobalDataPointer: Any = ...
    ReleaseGlobalDataPointer: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceFunctionISS2_cast: Any

class itkFiniteDifferenceFunctionISS3(itk.ITKCommonBasePython.itkLightObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    InitializeIteration: Any = ...
    ComputeUpdate: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetScaleCoefficients: Any = ...
    GetScaleCoefficients: Any = ...
    ComputeNeighborhoodScales: Any = ...
    ComputeGlobalTimeStep: Any = ...
    GetGlobalDataPointer: Any = ...
    ReleaseGlobalDataPointer: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceFunctionISS3_cast: Any

class itkFiniteDifferenceFunctionIUC2(itk.ITKCommonBasePython.itkLightObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    InitializeIteration: Any = ...
    ComputeUpdate: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetScaleCoefficients: Any = ...
    GetScaleCoefficients: Any = ...
    ComputeNeighborhoodScales: Any = ...
    ComputeGlobalTimeStep: Any = ...
    GetGlobalDataPointer: Any = ...
    ReleaseGlobalDataPointer: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceFunctionIUC2_cast: Any

class itkFiniteDifferenceFunctionIUC3(itk.ITKCommonBasePython.itkLightObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    InitializeIteration: Any = ...
    ComputeUpdate: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetScaleCoefficients: Any = ...
    GetScaleCoefficients: Any = ...
    ComputeNeighborhoodScales: Any = ...
    ComputeGlobalTimeStep: Any = ...
    GetGlobalDataPointer: Any = ...
    ReleaseGlobalDataPointer: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceFunctionIUC3_cast: Any

class itkFiniteDifferenceFunctionIVF22(itk.ITKCommonBasePython.itkLightObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    InitializeIteration: Any = ...
    ComputeUpdate: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetScaleCoefficients: Any = ...
    GetScaleCoefficients: Any = ...
    ComputeNeighborhoodScales: Any = ...
    ComputeGlobalTimeStep: Any = ...
    GetGlobalDataPointer: Any = ...
    ReleaseGlobalDataPointer: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceFunctionIVF22_cast: Any

class itkFiniteDifferenceFunctionIVF23(itk.ITKCommonBasePython.itkLightObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    InitializeIteration: Any = ...
    ComputeUpdate: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetScaleCoefficients: Any = ...
    GetScaleCoefficients: Any = ...
    ComputeNeighborhoodScales: Any = ...
    ComputeGlobalTimeStep: Any = ...
    GetGlobalDataPointer: Any = ...
    ReleaseGlobalDataPointer: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceFunctionIVF23_cast: Any

class itkFiniteDifferenceFunctionIVF32(itk.ITKCommonBasePython.itkLightObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    InitializeIteration: Any = ...
    ComputeUpdate: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetScaleCoefficients: Any = ...
    GetScaleCoefficients: Any = ...
    ComputeNeighborhoodScales: Any = ...
    ComputeGlobalTimeStep: Any = ...
    GetGlobalDataPointer: Any = ...
    ReleaseGlobalDataPointer: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceFunctionIVF32_cast: Any

class itkFiniteDifferenceFunctionIVF33(itk.ITKCommonBasePython.itkLightObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    InitializeIteration: Any = ...
    ComputeUpdate: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetScaleCoefficients: Any = ...
    GetScaleCoefficients: Any = ...
    ComputeNeighborhoodScales: Any = ...
    ComputeGlobalTimeStep: Any = ...
    GetGlobalDataPointer: Any = ...
    ReleaseGlobalDataPointer: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceFunctionIVF33_cast: Any

class itkFiniteDifferenceFunctionIVF42(itk.ITKCommonBasePython.itkLightObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    InitializeIteration: Any = ...
    ComputeUpdate: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetScaleCoefficients: Any = ...
    GetScaleCoefficients: Any = ...
    ComputeNeighborhoodScales: Any = ...
    ComputeGlobalTimeStep: Any = ...
    GetGlobalDataPointer: Any = ...
    ReleaseGlobalDataPointer: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceFunctionIVF42_cast: Any

class itkFiniteDifferenceFunctionIVF43(itk.ITKCommonBasePython.itkLightObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    InitializeIteration: Any = ...
    ComputeUpdate: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetScaleCoefficients: Any = ...
    GetScaleCoefficients: Any = ...
    ComputeNeighborhoodScales: Any = ...
    ComputeGlobalTimeStep: Any = ...
    GetGlobalDataPointer: Any = ...
    ReleaseGlobalDataPointer: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceFunctionIVF43_cast: Any
