import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkFFTConvolutionImageFilterIF2IF2_New(): ...

class itkFFTConvolutionImageFilterIF2IF2(itk.itkConvolutionImageFilterBasePython.itkConvolutionImageFilterBaseIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSizeGreatestPrimeFactor: Any = ...
    GetSizeGreatestPrimeFactor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFFTConvolutionImageFilterIF2IF2___New_orig__: Any
itkFFTConvolutionImageFilterIF2IF2_cast: Any

def itkFFTConvolutionImageFilterIF3IF3_New(): ...

class itkFFTConvolutionImageFilterIF3IF3(itk.itkConvolutionImageFilterBasePython.itkConvolutionImageFilterBaseIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSizeGreatestPrimeFactor: Any = ...
    GetSizeGreatestPrimeFactor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFFTConvolutionImageFilterIF3IF3___New_orig__: Any
itkFFTConvolutionImageFilterIF3IF3_cast: Any

def itkFFTConvolutionImageFilterISS2ISS2_New(): ...

class itkFFTConvolutionImageFilterISS2ISS2(itk.itkConvolutionImageFilterBasePython.itkConvolutionImageFilterBaseISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSizeGreatestPrimeFactor: Any = ...
    GetSizeGreatestPrimeFactor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFFTConvolutionImageFilterISS2ISS2___New_orig__: Any
itkFFTConvolutionImageFilterISS2ISS2_cast: Any

def itkFFTConvolutionImageFilterISS3ISS3_New(): ...

class itkFFTConvolutionImageFilterISS3ISS3(itk.itkConvolutionImageFilterBasePython.itkConvolutionImageFilterBaseISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSizeGreatestPrimeFactor: Any = ...
    GetSizeGreatestPrimeFactor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFFTConvolutionImageFilterISS3ISS3___New_orig__: Any
itkFFTConvolutionImageFilterISS3ISS3_cast: Any

def itkFFTConvolutionImageFilterIUC2IUC2_New(): ...

class itkFFTConvolutionImageFilterIUC2IUC2(itk.itkConvolutionImageFilterBasePython.itkConvolutionImageFilterBaseIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSizeGreatestPrimeFactor: Any = ...
    GetSizeGreatestPrimeFactor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFFTConvolutionImageFilterIUC2IUC2___New_orig__: Any
itkFFTConvolutionImageFilterIUC2IUC2_cast: Any

def itkFFTConvolutionImageFilterIUC3IUC3_New(): ...

class itkFFTConvolutionImageFilterIUC3IUC3(itk.itkConvolutionImageFilterBasePython.itkConvolutionImageFilterBaseIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSizeGreatestPrimeFactor: Any = ...
    GetSizeGreatestPrimeFactor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFFTConvolutionImageFilterIUC3IUC3___New_orig__: Any
itkFFTConvolutionImageFilterIUC3IUC3_cast: Any

def fft_convolution_image_filter(*args: Any, **kwargs: Any): ...
def fft_convolution_image_filter_init_docstring() -> None: ...
