import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkFiniteDifferenceImageFilterICVF22ICVF22(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterICVF22ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetElapsedIterations: Any = ...
    GetDifferenceFunction: Any = ...
    SetDifferenceFunction: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetUseImageSpacing: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    GetUseImageSpacing: Any = ...
    SetMaximumRMSError: Any = ...
    GetMaximumRMSError: Any = ...
    SetRMSChange: Any = ...
    GetRMSChange: Any = ...
    SetManualReinitialization: Any = ...
    GetManualReinitialization: Any = ...
    ManualReinitializationOn: Any = ...
    ManualReinitializationOff: Any = ...
    SetIsInitialized: Any = ...
    GetIsInitialized: Any = ...
    SetStateToUninitialized: Any = ...
    SetStateToInitialized: Any = ...
    OutputPixelIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceImageFilterICVF22ICVF22_cast: Any

class itkFiniteDifferenceImageFilterICVF23ICVF23(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterICVF23ICVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetElapsedIterations: Any = ...
    GetDifferenceFunction: Any = ...
    SetDifferenceFunction: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetUseImageSpacing: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    GetUseImageSpacing: Any = ...
    SetMaximumRMSError: Any = ...
    GetMaximumRMSError: Any = ...
    SetRMSChange: Any = ...
    GetRMSChange: Any = ...
    SetManualReinitialization: Any = ...
    GetManualReinitialization: Any = ...
    ManualReinitializationOn: Any = ...
    ManualReinitializationOff: Any = ...
    SetIsInitialized: Any = ...
    GetIsInitialized: Any = ...
    SetStateToUninitialized: Any = ...
    SetStateToInitialized: Any = ...
    OutputPixelIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceImageFilterICVF23ICVF23_cast: Any

class itkFiniteDifferenceImageFilterICVF32ICVF32(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterICVF32ICVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetElapsedIterations: Any = ...
    GetDifferenceFunction: Any = ...
    SetDifferenceFunction: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetUseImageSpacing: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    GetUseImageSpacing: Any = ...
    SetMaximumRMSError: Any = ...
    GetMaximumRMSError: Any = ...
    SetRMSChange: Any = ...
    GetRMSChange: Any = ...
    SetManualReinitialization: Any = ...
    GetManualReinitialization: Any = ...
    ManualReinitializationOn: Any = ...
    ManualReinitializationOff: Any = ...
    SetIsInitialized: Any = ...
    GetIsInitialized: Any = ...
    SetStateToUninitialized: Any = ...
    SetStateToInitialized: Any = ...
    OutputPixelIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceImageFilterICVF32ICVF32_cast: Any

class itkFiniteDifferenceImageFilterICVF33ICVF33(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterICVF33ICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetElapsedIterations: Any = ...
    GetDifferenceFunction: Any = ...
    SetDifferenceFunction: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetUseImageSpacing: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    GetUseImageSpacing: Any = ...
    SetMaximumRMSError: Any = ...
    GetMaximumRMSError: Any = ...
    SetRMSChange: Any = ...
    GetRMSChange: Any = ...
    SetManualReinitialization: Any = ...
    GetManualReinitialization: Any = ...
    ManualReinitializationOn: Any = ...
    ManualReinitializationOff: Any = ...
    SetIsInitialized: Any = ...
    GetIsInitialized: Any = ...
    SetStateToUninitialized: Any = ...
    SetStateToInitialized: Any = ...
    OutputPixelIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceImageFilterICVF33ICVF33_cast: Any

class itkFiniteDifferenceImageFilterICVF42ICVF42(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterICVF42ICVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetElapsedIterations: Any = ...
    GetDifferenceFunction: Any = ...
    SetDifferenceFunction: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetUseImageSpacing: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    GetUseImageSpacing: Any = ...
    SetMaximumRMSError: Any = ...
    GetMaximumRMSError: Any = ...
    SetRMSChange: Any = ...
    GetRMSChange: Any = ...
    SetManualReinitialization: Any = ...
    GetManualReinitialization: Any = ...
    ManualReinitializationOn: Any = ...
    ManualReinitializationOff: Any = ...
    SetIsInitialized: Any = ...
    GetIsInitialized: Any = ...
    SetStateToUninitialized: Any = ...
    SetStateToInitialized: Any = ...
    OutputPixelIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceImageFilterICVF42ICVF42_cast: Any

class itkFiniteDifferenceImageFilterICVF43ICVF43(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterICVF43ICVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetElapsedIterations: Any = ...
    GetDifferenceFunction: Any = ...
    SetDifferenceFunction: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetUseImageSpacing: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    GetUseImageSpacing: Any = ...
    SetMaximumRMSError: Any = ...
    GetMaximumRMSError: Any = ...
    SetRMSChange: Any = ...
    GetRMSChange: Any = ...
    SetManualReinitialization: Any = ...
    GetManualReinitialization: Any = ...
    ManualReinitializationOn: Any = ...
    ManualReinitializationOff: Any = ...
    SetIsInitialized: Any = ...
    GetIsInitialized: Any = ...
    SetStateToUninitialized: Any = ...
    SetStateToInitialized: Any = ...
    OutputPixelIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceImageFilterICVF43ICVF43_cast: Any

class itkFiniteDifferenceImageFilterIF2IF2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetElapsedIterations: Any = ...
    GetDifferenceFunction: Any = ...
    SetDifferenceFunction: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetUseImageSpacing: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    GetUseImageSpacing: Any = ...
    SetMaximumRMSError: Any = ...
    GetMaximumRMSError: Any = ...
    SetRMSChange: Any = ...
    GetRMSChange: Any = ...
    SetManualReinitialization: Any = ...
    GetManualReinitialization: Any = ...
    ManualReinitializationOn: Any = ...
    ManualReinitializationOff: Any = ...
    SetIsInitialized: Any = ...
    GetIsInitialized: Any = ...
    SetStateToUninitialized: Any = ...
    SetStateToInitialized: Any = ...
    OutputPixelIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceImageFilterIF2IF2_cast: Any

class itkFiniteDifferenceImageFilterIF3IF3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetElapsedIterations: Any = ...
    GetDifferenceFunction: Any = ...
    SetDifferenceFunction: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetUseImageSpacing: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    GetUseImageSpacing: Any = ...
    SetMaximumRMSError: Any = ...
    GetMaximumRMSError: Any = ...
    SetRMSChange: Any = ...
    GetRMSChange: Any = ...
    SetManualReinitialization: Any = ...
    GetManualReinitialization: Any = ...
    ManualReinitializationOn: Any = ...
    ManualReinitializationOff: Any = ...
    SetIsInitialized: Any = ...
    GetIsInitialized: Any = ...
    SetStateToUninitialized: Any = ...
    SetStateToInitialized: Any = ...
    OutputPixelIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceImageFilterIF3IF3_cast: Any

class itkFiniteDifferenceImageFilterIVF22IVF22(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIVF22IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetElapsedIterations: Any = ...
    GetDifferenceFunction: Any = ...
    SetDifferenceFunction: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetUseImageSpacing: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    GetUseImageSpacing: Any = ...
    SetMaximumRMSError: Any = ...
    GetMaximumRMSError: Any = ...
    SetRMSChange: Any = ...
    GetRMSChange: Any = ...
    SetManualReinitialization: Any = ...
    GetManualReinitialization: Any = ...
    ManualReinitializationOn: Any = ...
    ManualReinitializationOff: Any = ...
    SetIsInitialized: Any = ...
    GetIsInitialized: Any = ...
    SetStateToUninitialized: Any = ...
    SetStateToInitialized: Any = ...
    OutputPixelIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceImageFilterIVF22IVF22_cast: Any

class itkFiniteDifferenceImageFilterIVF23IVF23(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIVF23IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetElapsedIterations: Any = ...
    GetDifferenceFunction: Any = ...
    SetDifferenceFunction: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetUseImageSpacing: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    GetUseImageSpacing: Any = ...
    SetMaximumRMSError: Any = ...
    GetMaximumRMSError: Any = ...
    SetRMSChange: Any = ...
    GetRMSChange: Any = ...
    SetManualReinitialization: Any = ...
    GetManualReinitialization: Any = ...
    ManualReinitializationOn: Any = ...
    ManualReinitializationOff: Any = ...
    SetIsInitialized: Any = ...
    GetIsInitialized: Any = ...
    SetStateToUninitialized: Any = ...
    SetStateToInitialized: Any = ...
    OutputPixelIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceImageFilterIVF23IVF23_cast: Any

class itkFiniteDifferenceImageFilterIVF32IVF32(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIVF32IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetElapsedIterations: Any = ...
    GetDifferenceFunction: Any = ...
    SetDifferenceFunction: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetUseImageSpacing: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    GetUseImageSpacing: Any = ...
    SetMaximumRMSError: Any = ...
    GetMaximumRMSError: Any = ...
    SetRMSChange: Any = ...
    GetRMSChange: Any = ...
    SetManualReinitialization: Any = ...
    GetManualReinitialization: Any = ...
    ManualReinitializationOn: Any = ...
    ManualReinitializationOff: Any = ...
    SetIsInitialized: Any = ...
    GetIsInitialized: Any = ...
    SetStateToUninitialized: Any = ...
    SetStateToInitialized: Any = ...
    OutputPixelIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceImageFilterIVF32IVF32_cast: Any

class itkFiniteDifferenceImageFilterIVF33IVF33(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIVF33IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetElapsedIterations: Any = ...
    GetDifferenceFunction: Any = ...
    SetDifferenceFunction: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetUseImageSpacing: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    GetUseImageSpacing: Any = ...
    SetMaximumRMSError: Any = ...
    GetMaximumRMSError: Any = ...
    SetRMSChange: Any = ...
    GetRMSChange: Any = ...
    SetManualReinitialization: Any = ...
    GetManualReinitialization: Any = ...
    ManualReinitializationOn: Any = ...
    ManualReinitializationOff: Any = ...
    SetIsInitialized: Any = ...
    GetIsInitialized: Any = ...
    SetStateToUninitialized: Any = ...
    SetStateToInitialized: Any = ...
    OutputPixelIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceImageFilterIVF33IVF33_cast: Any

class itkFiniteDifferenceImageFilterIVF42IVF42(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIVF42IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetElapsedIterations: Any = ...
    GetDifferenceFunction: Any = ...
    SetDifferenceFunction: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetUseImageSpacing: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    GetUseImageSpacing: Any = ...
    SetMaximumRMSError: Any = ...
    GetMaximumRMSError: Any = ...
    SetRMSChange: Any = ...
    GetRMSChange: Any = ...
    SetManualReinitialization: Any = ...
    GetManualReinitialization: Any = ...
    ManualReinitializationOn: Any = ...
    ManualReinitializationOff: Any = ...
    SetIsInitialized: Any = ...
    GetIsInitialized: Any = ...
    SetStateToUninitialized: Any = ...
    SetStateToInitialized: Any = ...
    OutputPixelIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceImageFilterIVF42IVF42_cast: Any

class itkFiniteDifferenceImageFilterIVF43IVF43(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIVF43IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetElapsedIterations: Any = ...
    GetDifferenceFunction: Any = ...
    SetDifferenceFunction: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    SetUseImageSpacing: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    GetUseImageSpacing: Any = ...
    SetMaximumRMSError: Any = ...
    GetMaximumRMSError: Any = ...
    SetRMSChange: Any = ...
    GetRMSChange: Any = ...
    SetManualReinitialization: Any = ...
    GetManualReinitialization: Any = ...
    ManualReinitializationOn: Any = ...
    ManualReinitializationOff: Any = ...
    SetIsInitialized: Any = ...
    GetIsInitialized: Any = ...
    SetStateToUninitialized: Any = ...
    SetStateToInitialized: Any = ...
    OutputPixelIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkFiniteDifferenceImageFilterIVF43IVF43_cast: Any

def finite_difference_image_filter(*args: Any, **kwargs: Any): ...
def finite_difference_image_filter_init_docstring() -> None: ...
