import itk.itkArrayPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkFullToHalfHermitianImageFilterICF2_New(): ...

class itkFullToHalfHermitianImageFilterICF2(itk.itkImageToImageFilterBPython.itkImageToImageFilterICF2ICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetActualXDimensionIsOddOutput: Any = ...
    GetActualXDimensionIsOdd: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFullToHalfHermitianImageFilterICF2___New_orig__: Any
itkFullToHalfHermitianImageFilterICF2_cast: Any

def itkFullToHalfHermitianImageFilterICF3_New(): ...

class itkFullToHalfHermitianImageFilterICF3(itk.itkImageToImageFilterBPython.itkImageToImageFilterICF3ICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetActualXDimensionIsOddOutput: Any = ...
    GetActualXDimensionIsOdd: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFullToHalfHermitianImageFilterICF3___New_orig__: Any
itkFullToHalfHermitianImageFilterICF3_cast: Any

def full_to_half_hermitian_image_filter(*args: Any, **kwargs: Any): ...
def full_to_half_hermitian_image_filter_init_docstring() -> None: ...
