import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkGeodesicActiveContourLevelSetImageFilterIF2IF2F_New(): ...

class itkGeodesicActiveContourLevelSetImageFilterIF2IF2F(itk.itkSegmentationLevelSetImageFilterPython.itkSegmentationLevelSetImageFilterIF2IF2F):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDerivativeSigma: Any = ...
    GetDerivativeSigma: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGeodesicActiveContourLevelSetImageFilterIF2IF2F___New_orig__: Any
itkGeodesicActiveContourLevelSetImageFilterIF2IF2F_cast: Any

def itkGeodesicActiveContourLevelSetImageFilterIF3IF3F_New(): ...

class itkGeodesicActiveContourLevelSetImageFilterIF3IF3F(itk.itkSegmentationLevelSetImageFilterPython.itkSegmentationLevelSetImageFilterIF3IF3F):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDerivativeSigma: Any = ...
    GetDerivativeSigma: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGeodesicActiveContourLevelSetImageFilterIF3IF3F___New_orig__: Any
itkGeodesicActiveContourLevelSetImageFilterIF3IF3F_cast: Any

def geodesic_active_contour_level_set_image_filter(*args: Any, **kwargs: Any): ...
def geodesic_active_contour_level_set_image_filter_init_docstring() -> None: ...
