import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkGrayscaleConnectedOpeningImageFilterIF2IF2_New(): ...

class itkGrayscaleConnectedOpeningImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSeed: Any = ...
    GetSeed: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleConnectedOpeningImageFilterIF2IF2___New_orig__: Any
itkGrayscaleConnectedOpeningImageFilterIF2IF2_cast: Any

def itkGrayscaleConnectedOpeningImageFilterIF3IF3_New(): ...

class itkGrayscaleConnectedOpeningImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSeed: Any = ...
    GetSeed: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleConnectedOpeningImageFilterIF3IF3___New_orig__: Any
itkGrayscaleConnectedOpeningImageFilterIF3IF3_cast: Any

def itkGrayscaleConnectedOpeningImageFilterISS2ISS2_New(): ...

class itkGrayscaleConnectedOpeningImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSeed: Any = ...
    GetSeed: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleConnectedOpeningImageFilterISS2ISS2___New_orig__: Any
itkGrayscaleConnectedOpeningImageFilterISS2ISS2_cast: Any

def itkGrayscaleConnectedOpeningImageFilterISS3ISS3_New(): ...

class itkGrayscaleConnectedOpeningImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSeed: Any = ...
    GetSeed: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleConnectedOpeningImageFilterISS3ISS3___New_orig__: Any
itkGrayscaleConnectedOpeningImageFilterISS3ISS3_cast: Any

def itkGrayscaleConnectedOpeningImageFilterIUC2IUC2_New(): ...

class itkGrayscaleConnectedOpeningImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSeed: Any = ...
    GetSeed: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleConnectedOpeningImageFilterIUC2IUC2___New_orig__: Any
itkGrayscaleConnectedOpeningImageFilterIUC2IUC2_cast: Any

def itkGrayscaleConnectedOpeningImageFilterIUC3IUC3_New(): ...

class itkGrayscaleConnectedOpeningImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSeed: Any = ...
    GetSeed: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleConnectedOpeningImageFilterIUC3IUC3___New_orig__: Any
itkGrayscaleConnectedOpeningImageFilterIUC3IUC3_cast: Any

def grayscale_connected_opening_image_filter(*args: Any, **kwargs: Any): ...
def grayscale_connected_opening_image_filter_init_docstring() -> None: ...
