import itk.stdcomplexPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkGiplImageIO_New(): ...

class itkGiplImageIO(itk.ITKIOImageBaseBasePython.itkImageIOBase):
    thisown: Any = ...
    __New_orig__: Any = ...
    Clone: Any = ...
    def __init__(self) -> None: ...
    PrintSelf: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGiplImageIO___New_orig__: Any
itkGiplImageIO_cast: Any

def itkGiplImageIOFactory_New(): ...

class itkGiplImageIOFactory(itk.ITKCommonBasePython.itkObjectFactoryBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    RegisterOneFactory: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGiplImageIOFactory___New_orig__: Any
itkGiplImageIOFactory_RegisterOneFactory: Any
itkGiplImageIOFactory_cast: Any
