import itk.itkContinuousIndexPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class listitkGaussianSpatialObject2_Pointer:
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

class listitkGaussianSpatialObject3_Pointer:
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

def itkGaussianSpatialObject2_New(): ...

class itkGaussianSpatialObject2(itk.itkSpatialObjectBasePython.itkSpatialObject2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetRadiusInObjectSpace: Any = ...
    GetRadiusInObjectSpace: Any = ...
    SetSigmaInObjectSpace: Any = ...
    GetSigmaInObjectSpace: Any = ...
    SetCenterInObjectSpace: Any = ...
    GetCenterInObjectSpace: Any = ...
    SetMaximum: Any = ...
    GetMaximum: Any = ...
    SquaredZScoreInObjectSpace: Any = ...
    SquaredZScoreInWorldSpace: Any = ...
    ValueAtInObjectSpace: Any = ...
    GetEllipsoid: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaussianSpatialObject2___New_orig__: Any
itkGaussianSpatialObject2_cast: Any

def itkGaussianSpatialObject3_New(): ...

class itkGaussianSpatialObject3(itk.itkSpatialObjectBasePython.itkSpatialObject3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetRadiusInObjectSpace: Any = ...
    GetRadiusInObjectSpace: Any = ...
    SetSigmaInObjectSpace: Any = ...
    GetSigmaInObjectSpace: Any = ...
    SetCenterInObjectSpace: Any = ...
    GetCenterInObjectSpace: Any = ...
    SetMaximum: Any = ...
    GetMaximum: Any = ...
    SquaredZScoreInObjectSpace: Any = ...
    SquaredZScoreInWorldSpace: Any = ...
    ValueAtInObjectSpace: Any = ...
    GetEllipsoid: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaussianSpatialObject3___New_orig__: Any
itkGaussianSpatialObject3_cast: Any
