import itk.itkLaplacianImageFilterPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkGradientVectorFlowImageFilterICVF22ICVF22F_New(): ...

class itkGradientVectorFlowImageFilterICVF22ICVF22F(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF22ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetLaplacianFilter: Any = ...
    GetModifiableLaplacianFilter: Any = ...
    GetLaplacianFilter: Any = ...
    SetTimeStep: Any = ...
    GetTimeStep: Any = ...
    SetNoiseLevel: Any = ...
    GetNoiseLevel: Any = ...
    SetIterationNum: Any = ...
    GetIterationNum: Any = ...
    SameDimensionCheck: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGradientVectorFlowImageFilterICVF22ICVF22F___New_orig__: Any
itkGradientVectorFlowImageFilterICVF22ICVF22F_cast: Any

def itkGradientVectorFlowImageFilterICVF33ICVF33F_New(): ...

class itkGradientVectorFlowImageFilterICVF33ICVF33F(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF33ICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetLaplacianFilter: Any = ...
    GetModifiableLaplacianFilter: Any = ...
    GetLaplacianFilter: Any = ...
    SetTimeStep: Any = ...
    GetTimeStep: Any = ...
    SetNoiseLevel: Any = ...
    GetNoiseLevel: Any = ...
    SetIterationNum: Any = ...
    GetIterationNum: Any = ...
    SameDimensionCheck: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGradientVectorFlowImageFilterICVF33ICVF33F___New_orig__: Any
itkGradientVectorFlowImageFilterICVF33ICVF33F_cast: Any

def itkGradientVectorFlowImageFilterIVF22IVF22F_New(): ...

class itkGradientVectorFlowImageFilterIVF22IVF22F(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF22IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetLaplacianFilter: Any = ...
    GetModifiableLaplacianFilter: Any = ...
    GetLaplacianFilter: Any = ...
    SetTimeStep: Any = ...
    GetTimeStep: Any = ...
    SetNoiseLevel: Any = ...
    GetNoiseLevel: Any = ...
    SetIterationNum: Any = ...
    GetIterationNum: Any = ...
    SameDimensionCheck: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGradientVectorFlowImageFilterIVF22IVF22F___New_orig__: Any
itkGradientVectorFlowImageFilterIVF22IVF22F_cast: Any

def itkGradientVectorFlowImageFilterIVF33IVF33F_New(): ...

class itkGradientVectorFlowImageFilterIVF33IVF33F(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF33IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetLaplacianFilter: Any = ...
    GetModifiableLaplacianFilter: Any = ...
    GetLaplacianFilter: Any = ...
    SetTimeStep: Any = ...
    GetTimeStep: Any = ...
    SetNoiseLevel: Any = ...
    GetNoiseLevel: Any = ...
    SetIterationNum: Any = ...
    GetIterationNum: Any = ...
    SameDimensionCheck: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGradientVectorFlowImageFilterIVF33IVF33F___New_orig__: Any
itkGradientVectorFlowImageFilterIVF33IVF33F_cast: Any

def gradient_vector_flow_image_filter(*args: Any, **kwargs: Any): ...
def gradient_vector_flow_image_filter_init_docstring() -> None: ...
