import itk.itkNeighborhoodPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkGrayscaleDilateImageFilterIF2IF2SE2_New(): ...

class itkGrayscaleDilateImageFilterIF2IF2SE2(itk.itkFlatStructuringElementPython.itkKernelImageFilterIF2IF2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetBoundary: Any = ...
    GetBoundary: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleDilateImageFilterIF2IF2SE2___New_orig__: Any
itkGrayscaleDilateImageFilterIF2IF2SE2_cast: Any

def itkGrayscaleDilateImageFilterIF3IF3SE3_New(): ...

class itkGrayscaleDilateImageFilterIF3IF3SE3(itk.itkFlatStructuringElementPython.itkKernelImageFilterIF3IF3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetBoundary: Any = ...
    GetBoundary: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleDilateImageFilterIF3IF3SE3___New_orig__: Any
itkGrayscaleDilateImageFilterIF3IF3SE3_cast: Any

def itkGrayscaleDilateImageFilterISS2ISS2SE2_New(): ...

class itkGrayscaleDilateImageFilterISS2ISS2SE2(itk.itkFlatStructuringElementPython.itkKernelImageFilterISS2ISS2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetBoundary: Any = ...
    GetBoundary: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleDilateImageFilterISS2ISS2SE2___New_orig__: Any
itkGrayscaleDilateImageFilterISS2ISS2SE2_cast: Any

def itkGrayscaleDilateImageFilterISS3ISS3SE3_New(): ...

class itkGrayscaleDilateImageFilterISS3ISS3SE3(itk.itkFlatStructuringElementPython.itkKernelImageFilterISS3ISS3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetBoundary: Any = ...
    GetBoundary: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleDilateImageFilterISS3ISS3SE3___New_orig__: Any
itkGrayscaleDilateImageFilterISS3ISS3SE3_cast: Any

def itkGrayscaleDilateImageFilterIUC2IUC2SE2_New(): ...

class itkGrayscaleDilateImageFilterIUC2IUC2SE2(itk.itkFlatStructuringElementPython.itkKernelImageFilterIUC2IUC2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetBoundary: Any = ...
    GetBoundary: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleDilateImageFilterIUC2IUC2SE2___New_orig__: Any
itkGrayscaleDilateImageFilterIUC2IUC2SE2_cast: Any

def itkGrayscaleDilateImageFilterIUC3IUC3SE3_New(): ...

class itkGrayscaleDilateImageFilterIUC3IUC3SE3(itk.itkFlatStructuringElementPython.itkKernelImageFilterIUC3IUC3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetBoundary: Any = ...
    GetBoundary: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleDilateImageFilterIUC3IUC3SE3___New_orig__: Any
itkGrayscaleDilateImageFilterIUC3IUC3SE3_cast: Any

def grayscale_dilate_image_filter(*args: Any, **kwargs: Any): ...
def grayscale_dilate_image_filter_init_docstring() -> None: ...
