import itk.itkArrayPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkGaussianImageSourceIF2_New(): ...

class itkGaussianImageSourceIF2(itk.itkParametricImageSourcePython.itkParametricImageSourceIF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetScale: Any = ...
    GetScale: Any = ...
    SetNormalized: Any = ...
    GetNormalized: Any = ...
    NormalizedOn: Any = ...
    NormalizedOff: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetMean: Any = ...
    GetMean: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaussianImageSourceIF2___New_orig__: Any
itkGaussianImageSourceIF2_cast: Any

def itkGaussianImageSourceIF3_New(): ...

class itkGaussianImageSourceIF3(itk.itkParametricImageSourcePython.itkParametricImageSourceIF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetScale: Any = ...
    GetScale: Any = ...
    SetNormalized: Any = ...
    GetNormalized: Any = ...
    NormalizedOn: Any = ...
    NormalizedOff: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetMean: Any = ...
    GetMean: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaussianImageSourceIF3___New_orig__: Any
itkGaussianImageSourceIF3_cast: Any

def itkGaussianImageSourceISS2_New(): ...

class itkGaussianImageSourceISS2(itk.itkParametricImageSourcePython.itkParametricImageSourceISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetScale: Any = ...
    GetScale: Any = ...
    SetNormalized: Any = ...
    GetNormalized: Any = ...
    NormalizedOn: Any = ...
    NormalizedOff: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetMean: Any = ...
    GetMean: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaussianImageSourceISS2___New_orig__: Any
itkGaussianImageSourceISS2_cast: Any

def itkGaussianImageSourceISS3_New(): ...

class itkGaussianImageSourceISS3(itk.itkParametricImageSourcePython.itkParametricImageSourceISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetScale: Any = ...
    GetScale: Any = ...
    SetNormalized: Any = ...
    GetNormalized: Any = ...
    NormalizedOn: Any = ...
    NormalizedOff: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetMean: Any = ...
    GetMean: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaussianImageSourceISS3___New_orig__: Any
itkGaussianImageSourceISS3_cast: Any

def itkGaussianImageSourceIUC2_New(): ...

class itkGaussianImageSourceIUC2(itk.itkParametricImageSourcePython.itkParametricImageSourceIUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetScale: Any = ...
    GetScale: Any = ...
    SetNormalized: Any = ...
    GetNormalized: Any = ...
    NormalizedOn: Any = ...
    NormalizedOff: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetMean: Any = ...
    GetMean: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaussianImageSourceIUC2___New_orig__: Any
itkGaussianImageSourceIUC2_cast: Any

def itkGaussianImageSourceIUC3_New(): ...

class itkGaussianImageSourceIUC3(itk.itkParametricImageSourcePython.itkParametricImageSourceIUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetScale: Any = ...
    GetScale: Any = ...
    SetNormalized: Any = ...
    GetNormalized: Any = ...
    NormalizedOn: Any = ...
    NormalizedOff: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetMean: Any = ...
    GetMean: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaussianImageSourceIUC3___New_orig__: Any
itkGaussianImageSourceIUC3_cast: Any

def gaussian_image_source(*args: Any, **kwargs: Any): ...
def gaussian_image_source_init_docstring() -> None: ...
