import itk.stdcomplexPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkGE4ImageIO_New(): ...

class itkGE4ImageIO(itk.itkIPLCommonImageIOPython.itkIPLCommonImageIO):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGE4ImageIO___New_orig__: Any
itkGE4ImageIO_cast: Any

def itkGE4ImageIOFactory_New(): ...

class itkGE4ImageIOFactory(itk.ITKCommonBasePython.itkObjectFactoryBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    RegisterOneFactory: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGE4ImageIOFactory___New_orig__: Any
itkGE4ImageIOFactory_RegisterOneFactory: Any
itkGE4ImageIOFactory_cast: Any
