import itk.itkVariableLengthVectorPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkGaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransformD2_New(): ...

class itkGaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransformD2(itk.itkTimeVaryingVelocityFieldTransformPython.itkTimeVaryingVelocityFieldTransformD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetGaussianSpatialSmoothingVarianceForTheUpdateField: Any = ...
    GetGaussianSpatialSmoothingVarianceForTheUpdateField: Any = ...
    SetGaussianTemporalSmoothingVarianceForTheUpdateField: Any = ...
    GetGaussianTemporalSmoothingVarianceForTheUpdateField: Any = ...
    SetGaussianSpatialSmoothingVarianceForTheTotalField: Any = ...
    GetGaussianSpatialSmoothingVarianceForTheTotalField: Any = ...
    SetGaussianTemporalSmoothingVarianceForTheTotalField: Any = ...
    GetGaussianTemporalSmoothingVarianceForTheTotalField: Any = ...
    UpdateTransformParameters: Any = ...
    GaussianSmoothTimeVaryingVelocityField: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransformD2___New_orig__: Any
itkGaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransformD2_cast: Any

def itkGaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransformD3_New(): ...

class itkGaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransformD3(itk.itkTimeVaryingVelocityFieldTransformPython.itkTimeVaryingVelocityFieldTransformD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetGaussianSpatialSmoothingVarianceForTheUpdateField: Any = ...
    GetGaussianSpatialSmoothingVarianceForTheUpdateField: Any = ...
    SetGaussianTemporalSmoothingVarianceForTheUpdateField: Any = ...
    GetGaussianTemporalSmoothingVarianceForTheUpdateField: Any = ...
    SetGaussianSpatialSmoothingVarianceForTheTotalField: Any = ...
    GetGaussianSpatialSmoothingVarianceForTheTotalField: Any = ...
    SetGaussianTemporalSmoothingVarianceForTheTotalField: Any = ...
    GetGaussianTemporalSmoothingVarianceForTheTotalField: Any = ...
    UpdateTransformParameters: Any = ...
    GaussianSmoothTimeVaryingVelocityField: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransformD3___New_orig__: Any
itkGaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransformD3_cast: Any
