import itk.itkImageBoundaryConditionPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkGrayscaleFunctionDilateImageFilterIF2IF2SE2_New(): ...

class itkGrayscaleFunctionDilateImageFilterIF2IF2SE2(itk.itkGrayscaleFunctionErodeImageFilterPython.itkGrayscaleFunctionErodeImageFilterIF2IF2SE2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SameDimensionCheck1: Any = ...
    SameDimensionCheck2: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    KernelConvertibleToInputCheck: Any = ...
    InputAdditiveOperatorsCheck: Any = ...
    InputGreaterThanComparableCheck: Any = ...
    KernelGreaterThanComparableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleFunctionDilateImageFilterIF2IF2SE2___New_orig__: Any
itkGrayscaleFunctionDilateImageFilterIF2IF2SE2_cast: Any

def itkGrayscaleFunctionDilateImageFilterIF3IF3SE3_New(): ...

class itkGrayscaleFunctionDilateImageFilterIF3IF3SE3(itk.itkGrayscaleFunctionErodeImageFilterPython.itkGrayscaleFunctionErodeImageFilterIF3IF3SE3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SameDimensionCheck1: Any = ...
    SameDimensionCheck2: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    KernelConvertibleToInputCheck: Any = ...
    InputAdditiveOperatorsCheck: Any = ...
    InputGreaterThanComparableCheck: Any = ...
    KernelGreaterThanComparableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleFunctionDilateImageFilterIF3IF3SE3___New_orig__: Any
itkGrayscaleFunctionDilateImageFilterIF3IF3SE3_cast: Any

def itkGrayscaleFunctionDilateImageFilterISS2ISS2SE2_New(): ...

class itkGrayscaleFunctionDilateImageFilterISS2ISS2SE2(itk.itkGrayscaleFunctionErodeImageFilterPython.itkGrayscaleFunctionErodeImageFilterISS2ISS2SE2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SameDimensionCheck1: Any = ...
    SameDimensionCheck2: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    KernelConvertibleToInputCheck: Any = ...
    InputAdditiveOperatorsCheck: Any = ...
    InputGreaterThanComparableCheck: Any = ...
    KernelGreaterThanComparableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleFunctionDilateImageFilterISS2ISS2SE2___New_orig__: Any
itkGrayscaleFunctionDilateImageFilterISS2ISS2SE2_cast: Any

def itkGrayscaleFunctionDilateImageFilterISS3ISS3SE3_New(): ...

class itkGrayscaleFunctionDilateImageFilterISS3ISS3SE3(itk.itkGrayscaleFunctionErodeImageFilterPython.itkGrayscaleFunctionErodeImageFilterISS3ISS3SE3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SameDimensionCheck1: Any = ...
    SameDimensionCheck2: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    KernelConvertibleToInputCheck: Any = ...
    InputAdditiveOperatorsCheck: Any = ...
    InputGreaterThanComparableCheck: Any = ...
    KernelGreaterThanComparableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleFunctionDilateImageFilterISS3ISS3SE3___New_orig__: Any
itkGrayscaleFunctionDilateImageFilterISS3ISS3SE3_cast: Any

def itkGrayscaleFunctionDilateImageFilterIUC2IUC2SE2_New(): ...

class itkGrayscaleFunctionDilateImageFilterIUC2IUC2SE2(itk.itkGrayscaleFunctionErodeImageFilterPython.itkGrayscaleFunctionErodeImageFilterIUC2IUC2SE2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SameDimensionCheck1: Any = ...
    SameDimensionCheck2: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    KernelConvertibleToInputCheck: Any = ...
    InputAdditiveOperatorsCheck: Any = ...
    InputGreaterThanComparableCheck: Any = ...
    KernelGreaterThanComparableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleFunctionDilateImageFilterIUC2IUC2SE2___New_orig__: Any
itkGrayscaleFunctionDilateImageFilterIUC2IUC2SE2_cast: Any

def itkGrayscaleFunctionDilateImageFilterIUC3IUC3SE3_New(): ...

class itkGrayscaleFunctionDilateImageFilterIUC3IUC3SE3(itk.itkGrayscaleFunctionErodeImageFilterPython.itkGrayscaleFunctionErodeImageFilterIUC3IUC3SE3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SameDimensionCheck1: Any = ...
    SameDimensionCheck2: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    KernelConvertibleToInputCheck: Any = ...
    InputAdditiveOperatorsCheck: Any = ...
    InputGreaterThanComparableCheck: Any = ...
    KernelGreaterThanComparableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleFunctionDilateImageFilterIUC3IUC3SE3___New_orig__: Any
itkGrayscaleFunctionDilateImageFilterIUC3IUC3SE3_cast: Any

def grayscale_function_dilate_image_filter(*args: Any, **kwargs: Any): ...
def grayscale_function_dilate_image_filter_init_docstring() -> None: ...
