import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkGridImageSourceIF2_New(): ...

class itkGridImageSourceIF2(itk.itkGenerateImageSourcePython.itkGenerateImageSourceIF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetKernelFunction: Any = ...
    GetKernelFunction: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetGridSpacing: Any = ...
    GetGridSpacing: Any = ...
    SetGridOffset: Any = ...
    GetGridOffset: Any = ...
    SetWhichDimensions: Any = ...
    GetWhichDimensions: Any = ...
    SetScale: Any = ...
    GetScale: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGridImageSourceIF2___New_orig__: Any
itkGridImageSourceIF2_cast: Any

def itkGridImageSourceIF3_New(): ...

class itkGridImageSourceIF3(itk.itkGenerateImageSourcePython.itkGenerateImageSourceIF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetKernelFunction: Any = ...
    GetKernelFunction: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetGridSpacing: Any = ...
    GetGridSpacing: Any = ...
    SetGridOffset: Any = ...
    GetGridOffset: Any = ...
    SetWhichDimensions: Any = ...
    GetWhichDimensions: Any = ...
    SetScale: Any = ...
    GetScale: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGridImageSourceIF3___New_orig__: Any
itkGridImageSourceIF3_cast: Any

def itkGridImageSourceISS2_New(): ...

class itkGridImageSourceISS2(itk.itkGenerateImageSourcePython.itkGenerateImageSourceISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetKernelFunction: Any = ...
    GetKernelFunction: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetGridSpacing: Any = ...
    GetGridSpacing: Any = ...
    SetGridOffset: Any = ...
    GetGridOffset: Any = ...
    SetWhichDimensions: Any = ...
    GetWhichDimensions: Any = ...
    SetScale: Any = ...
    GetScale: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGridImageSourceISS2___New_orig__: Any
itkGridImageSourceISS2_cast: Any

def itkGridImageSourceISS3_New(): ...

class itkGridImageSourceISS3(itk.itkGenerateImageSourcePython.itkGenerateImageSourceISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetKernelFunction: Any = ...
    GetKernelFunction: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetGridSpacing: Any = ...
    GetGridSpacing: Any = ...
    SetGridOffset: Any = ...
    GetGridOffset: Any = ...
    SetWhichDimensions: Any = ...
    GetWhichDimensions: Any = ...
    SetScale: Any = ...
    GetScale: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGridImageSourceISS3___New_orig__: Any
itkGridImageSourceISS3_cast: Any

def itkGridImageSourceIUC2_New(): ...

class itkGridImageSourceIUC2(itk.itkGenerateImageSourcePython.itkGenerateImageSourceIUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetKernelFunction: Any = ...
    GetKernelFunction: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetGridSpacing: Any = ...
    GetGridSpacing: Any = ...
    SetGridOffset: Any = ...
    GetGridOffset: Any = ...
    SetWhichDimensions: Any = ...
    GetWhichDimensions: Any = ...
    SetScale: Any = ...
    GetScale: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGridImageSourceIUC2___New_orig__: Any
itkGridImageSourceIUC2_cast: Any

def itkGridImageSourceIUC3_New(): ...

class itkGridImageSourceIUC3(itk.itkGenerateImageSourcePython.itkGenerateImageSourceIUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetKernelFunction: Any = ...
    GetKernelFunction: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetGridSpacing: Any = ...
    GetGridSpacing: Any = ...
    SetGridOffset: Any = ...
    GetGridOffset: Any = ...
    SetWhichDimensions: Any = ...
    GetWhichDimensions: Any = ...
    SetScale: Any = ...
    GetScale: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGridImageSourceIUC3___New_orig__: Any
itkGridImageSourceIUC3_cast: Any

def grid_image_source(*args: Any, **kwargs: Any): ...
def grid_image_source_init_docstring() -> None: ...
