import itk.itkImageSourceCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkGaborImageSourceIF2_New(): ...

class itkGaborImageSourceIF2(itk.itkGenerateImageSourcePython.itkGenerateImageSourceIF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetMean: Any = ...
    GetMean: Any = ...
    SetFrequency: Any = ...
    GetFrequency: Any = ...
    SetCalculateImaginaryPart: Any = ...
    GetCalculateImaginaryPart: Any = ...
    CalculateImaginaryPartOn: Any = ...
    CalculateImaginaryPartOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaborImageSourceIF2___New_orig__: Any
itkGaborImageSourceIF2_cast: Any

def itkGaborImageSourceIF3_New(): ...

class itkGaborImageSourceIF3(itk.itkGenerateImageSourcePython.itkGenerateImageSourceIF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetMean: Any = ...
    GetMean: Any = ...
    SetFrequency: Any = ...
    GetFrequency: Any = ...
    SetCalculateImaginaryPart: Any = ...
    GetCalculateImaginaryPart: Any = ...
    CalculateImaginaryPartOn: Any = ...
    CalculateImaginaryPartOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaborImageSourceIF3___New_orig__: Any
itkGaborImageSourceIF3_cast: Any

def itkGaborImageSourceISS2_New(): ...

class itkGaborImageSourceISS2(itk.itkGenerateImageSourcePython.itkGenerateImageSourceISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetMean: Any = ...
    GetMean: Any = ...
    SetFrequency: Any = ...
    GetFrequency: Any = ...
    SetCalculateImaginaryPart: Any = ...
    GetCalculateImaginaryPart: Any = ...
    CalculateImaginaryPartOn: Any = ...
    CalculateImaginaryPartOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaborImageSourceISS2___New_orig__: Any
itkGaborImageSourceISS2_cast: Any

def itkGaborImageSourceISS3_New(): ...

class itkGaborImageSourceISS3(itk.itkGenerateImageSourcePython.itkGenerateImageSourceISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetMean: Any = ...
    GetMean: Any = ...
    SetFrequency: Any = ...
    GetFrequency: Any = ...
    SetCalculateImaginaryPart: Any = ...
    GetCalculateImaginaryPart: Any = ...
    CalculateImaginaryPartOn: Any = ...
    CalculateImaginaryPartOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaborImageSourceISS3___New_orig__: Any
itkGaborImageSourceISS3_cast: Any

def itkGaborImageSourceIUC2_New(): ...

class itkGaborImageSourceIUC2(itk.itkGenerateImageSourcePython.itkGenerateImageSourceIUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetMean: Any = ...
    GetMean: Any = ...
    SetFrequency: Any = ...
    GetFrequency: Any = ...
    SetCalculateImaginaryPart: Any = ...
    GetCalculateImaginaryPart: Any = ...
    CalculateImaginaryPartOn: Any = ...
    CalculateImaginaryPartOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaborImageSourceIUC2___New_orig__: Any
itkGaborImageSourceIUC2_cast: Any

def itkGaborImageSourceIUC3_New(): ...

class itkGaborImageSourceIUC3(itk.itkGenerateImageSourcePython.itkGenerateImageSourceIUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetMean: Any = ...
    GetMean: Any = ...
    SetFrequency: Any = ...
    GetFrequency: Any = ...
    SetCalculateImaginaryPart: Any = ...
    GetCalculateImaginaryPart: Any = ...
    CalculateImaginaryPartOn: Any = ...
    CalculateImaginaryPartOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaborImageSourceIUC3___New_orig__: Any
itkGaborImageSourceIUC3_cast: Any

def gabor_image_source(*args: Any, **kwargs: Any): ...
def gabor_image_source_init_docstring() -> None: ...
