import itk.itkNeighborhoodPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkGrayscaleMorphologicalOpeningImageFilterIF2IF2SE2_New(): ...

class itkGrayscaleMorphologicalOpeningImageFilterIF2IF2SE2(itk.itkFlatStructuringElementPython.itkKernelImageFilterIF2IF2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleMorphologicalOpeningImageFilterIF2IF2SE2___New_orig__: Any
itkGrayscaleMorphologicalOpeningImageFilterIF2IF2SE2_cast: Any

def itkGrayscaleMorphologicalOpeningImageFilterIF3IF3SE3_New(): ...

class itkGrayscaleMorphologicalOpeningImageFilterIF3IF3SE3(itk.itkFlatStructuringElementPython.itkKernelImageFilterIF3IF3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleMorphologicalOpeningImageFilterIF3IF3SE3___New_orig__: Any
itkGrayscaleMorphologicalOpeningImageFilterIF3IF3SE3_cast: Any

def itkGrayscaleMorphologicalOpeningImageFilterISS2ISS2SE2_New(): ...

class itkGrayscaleMorphologicalOpeningImageFilterISS2ISS2SE2(itk.itkFlatStructuringElementPython.itkKernelImageFilterISS2ISS2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleMorphologicalOpeningImageFilterISS2ISS2SE2___New_orig__: Any
itkGrayscaleMorphologicalOpeningImageFilterISS2ISS2SE2_cast: Any

def itkGrayscaleMorphologicalOpeningImageFilterISS3ISS3SE3_New(): ...

class itkGrayscaleMorphologicalOpeningImageFilterISS3ISS3SE3(itk.itkFlatStructuringElementPython.itkKernelImageFilterISS3ISS3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleMorphologicalOpeningImageFilterISS3ISS3SE3___New_orig__: Any
itkGrayscaleMorphologicalOpeningImageFilterISS3ISS3SE3_cast: Any

def itkGrayscaleMorphologicalOpeningImageFilterIUC2IUC2SE2_New(): ...

class itkGrayscaleMorphologicalOpeningImageFilterIUC2IUC2SE2(itk.itkFlatStructuringElementPython.itkKernelImageFilterIUC2IUC2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleMorphologicalOpeningImageFilterIUC2IUC2SE2___New_orig__: Any
itkGrayscaleMorphologicalOpeningImageFilterIUC2IUC2SE2_cast: Any

def itkGrayscaleMorphologicalOpeningImageFilterIUC3IUC3SE3_New(): ...

class itkGrayscaleMorphologicalOpeningImageFilterIUC3IUC3SE3(itk.itkFlatStructuringElementPython.itkKernelImageFilterIUC3IUC3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleMorphologicalOpeningImageFilterIUC3IUC3SE3___New_orig__: Any
itkGrayscaleMorphologicalOpeningImageFilterIUC3IUC3SE3_cast: Any

def grayscale_morphological_opening_image_filter(*args: Any, **kwargs: Any): ...
def grayscale_morphological_opening_image_filter_init_docstring() -> None: ...
