import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkGrayscaleGeodesicErodeImageFilterIF2IF2_New(): ...

class itkGrayscaleGeodesicErodeImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMarkerImage: Any = ...
    GetMarkerImage: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetRunOneIteration: Any = ...
    GetRunOneIteration: Any = ...
    RunOneIterationOn: Any = ...
    RunOneIterationOff: Any = ...
    GetNumberOfIterationsUsed: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    SameDimensionCheck: Any = ...
    InputComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleGeodesicErodeImageFilterIF2IF2___New_orig__: Any
itkGrayscaleGeodesicErodeImageFilterIF2IF2_cast: Any

def itkGrayscaleGeodesicErodeImageFilterIF3IF3_New(): ...

class itkGrayscaleGeodesicErodeImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMarkerImage: Any = ...
    GetMarkerImage: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetRunOneIteration: Any = ...
    GetRunOneIteration: Any = ...
    RunOneIterationOn: Any = ...
    RunOneIterationOff: Any = ...
    GetNumberOfIterationsUsed: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    SameDimensionCheck: Any = ...
    InputComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleGeodesicErodeImageFilterIF3IF3___New_orig__: Any
itkGrayscaleGeodesicErodeImageFilterIF3IF3_cast: Any

def itkGrayscaleGeodesicErodeImageFilterISS2ISS2_New(): ...

class itkGrayscaleGeodesicErodeImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMarkerImage: Any = ...
    GetMarkerImage: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetRunOneIteration: Any = ...
    GetRunOneIteration: Any = ...
    RunOneIterationOn: Any = ...
    RunOneIterationOff: Any = ...
    GetNumberOfIterationsUsed: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    SameDimensionCheck: Any = ...
    InputComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleGeodesicErodeImageFilterISS2ISS2___New_orig__: Any
itkGrayscaleGeodesicErodeImageFilterISS2ISS2_cast: Any

def itkGrayscaleGeodesicErodeImageFilterISS3ISS3_New(): ...

class itkGrayscaleGeodesicErodeImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMarkerImage: Any = ...
    GetMarkerImage: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetRunOneIteration: Any = ...
    GetRunOneIteration: Any = ...
    RunOneIterationOn: Any = ...
    RunOneIterationOff: Any = ...
    GetNumberOfIterationsUsed: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    SameDimensionCheck: Any = ...
    InputComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleGeodesicErodeImageFilterISS3ISS3___New_orig__: Any
itkGrayscaleGeodesicErodeImageFilterISS3ISS3_cast: Any

def itkGrayscaleGeodesicErodeImageFilterIUC2IUC2_New(): ...

class itkGrayscaleGeodesicErodeImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMarkerImage: Any = ...
    GetMarkerImage: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetRunOneIteration: Any = ...
    GetRunOneIteration: Any = ...
    RunOneIterationOn: Any = ...
    RunOneIterationOff: Any = ...
    GetNumberOfIterationsUsed: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    SameDimensionCheck: Any = ...
    InputComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleGeodesicErodeImageFilterIUC2IUC2___New_orig__: Any
itkGrayscaleGeodesicErodeImageFilterIUC2IUC2_cast: Any

def itkGrayscaleGeodesicErodeImageFilterIUC3IUC3_New(): ...

class itkGrayscaleGeodesicErodeImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMarkerImage: Any = ...
    GetMarkerImage: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetRunOneIteration: Any = ...
    GetRunOneIteration: Any = ...
    RunOneIterationOn: Any = ...
    RunOneIterationOff: Any = ...
    GetNumberOfIterationsUsed: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    SameDimensionCheck: Any = ...
    InputComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleGeodesicErodeImageFilterIUC3IUC3___New_orig__: Any
itkGrayscaleGeodesicErodeImageFilterIUC3IUC3_cast: Any

def grayscale_geodesic_erode_image_filter(*args: Any, **kwargs: Any): ...
def grayscale_geodesic_erode_image_filter_init_docstring() -> None: ...
