import itk.itkOffsetPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkGradientDescentOptimizerBasev4TemplateD(itk.itkObjectToObjectOptimizerBasePython.itkObjectToObjectOptimizerBaseTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetGradient: Any = ...
    GetStopCondition: Any = ...
    StartOptimization: Any = ...
    ResumeOptimization: Any = ...
    StopOptimization: Any = ...
    ModifyGradientByScales: Any = ...
    ModifyGradientByLearningRate: Any = ...
    ModifyGradientByScalesOverSubRange: Any = ...
    ModifyGradientByLearningRateOverSubRange: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkGradientDescentOptimizerBasev4TemplateD_cast: Any

class itkGradientDescentOptimizerBasev4TemplateF(itk.itkObjectToObjectOptimizerBasePython.itkObjectToObjectOptimizerBaseTemplateF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetGradient: Any = ...
    GetStopCondition: Any = ...
    StartOptimization: Any = ...
    ResumeOptimization: Any = ...
    StopOptimization: Any = ...
    ModifyGradientByScales: Any = ...
    ModifyGradientByLearningRate: Any = ...
    ModifyGradientByScalesOverSubRange: Any = ...
    ModifyGradientByLearningRateOverSubRange: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkGradientDescentOptimizerBasev4TemplateF_cast: Any
