import itk.itkArrayPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkGaussianInterpolateImageFunctionIF2D_New(): ...

class itkGaussianInterpolateImageFunctionIF2D(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionIF2D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetParameters: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaussianInterpolateImageFunctionIF2D___New_orig__: Any
itkGaussianInterpolateImageFunctionIF2D_cast: Any

def itkGaussianInterpolateImageFunctionIF3D_New(): ...

class itkGaussianInterpolateImageFunctionIF3D(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionIF3D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetParameters: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaussianInterpolateImageFunctionIF3D___New_orig__: Any
itkGaussianInterpolateImageFunctionIF3D_cast: Any

def itkGaussianInterpolateImageFunctionISS2D_New(): ...

class itkGaussianInterpolateImageFunctionISS2D(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionISS2D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetParameters: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaussianInterpolateImageFunctionISS2D___New_orig__: Any
itkGaussianInterpolateImageFunctionISS2D_cast: Any

def itkGaussianInterpolateImageFunctionISS3D_New(): ...

class itkGaussianInterpolateImageFunctionISS3D(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionISS3D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetParameters: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaussianInterpolateImageFunctionISS3D___New_orig__: Any
itkGaussianInterpolateImageFunctionISS3D_cast: Any

def itkGaussianInterpolateImageFunctionIUC2D_New(): ...

class itkGaussianInterpolateImageFunctionIUC2D(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionIUC2D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetParameters: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaussianInterpolateImageFunctionIUC2D___New_orig__: Any
itkGaussianInterpolateImageFunctionIUC2D_cast: Any

def itkGaussianInterpolateImageFunctionIUC3D_New(): ...

class itkGaussianInterpolateImageFunctionIUC3D(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionIUC3D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetParameters: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGaussianInterpolateImageFunctionIUC3D___New_orig__: Any
itkGaussianInterpolateImageFunctionIUC3D_cast: Any
