import itk.itkOffsetPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkGaussianDerivativeOperatorEnums:
    thisown: Any = ...
    InterpolationMode_NearestNeighbourInterpolation: Any = ...
    InterpolationMode_LinearInterpolation: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...

class itkGaussianDerivativeOperatorF2(itk.itkNeighborhoodOperatorPython.itkNeighborhoodOperatorF2):
    thisown: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    NormalizeAcrossScaleOn: Any = ...
    NormalizeAcrossScaleOff: Any = ...
    SetVariance: Any = ...
    GetVariance: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetMaximumError: Any = ...
    GetMaximumError: Any = ...
    SetMaximumKernelWidth: Any = ...
    SetOrder: Any = ...
    GetOrder: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...

class itkGaussianDerivativeOperatorF3(itk.itkNeighborhoodOperatorPython.itkNeighborhoodOperatorF3):
    thisown: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    NormalizeAcrossScaleOn: Any = ...
    NormalizeAcrossScaleOff: Any = ...
    SetVariance: Any = ...
    GetVariance: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetMaximumError: Any = ...
    GetMaximumError: Any = ...
    SetMaximumKernelWidth: Any = ...
    SetOrder: Any = ...
    GetOrder: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
