import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkGradientRecursiveGaussianImageFilterIF2ICVF22_New(): ...

class itkGradientRecursiveGaussianImageFilterIF2ICVF22(itk.itkImageToImageFilterBPython.itkImageToImageFilterIF2ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigmaArray: Any = ...
    SetSigma: Any = ...
    GetSigmaArray: Any = ...
    GetSigma: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SetUseImageDirection: Any = ...
    GetUseImageDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGradientRecursiveGaussianImageFilterIF2ICVF22___New_orig__: Any
itkGradientRecursiveGaussianImageFilterIF2ICVF22_cast: Any

def itkGradientRecursiveGaussianImageFilterIF3ICVF23_New(): ...

class itkGradientRecursiveGaussianImageFilterIF3ICVF23(itk.itkImageToImageFilterBPython.itkImageToImageFilterIF3ICVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigmaArray: Any = ...
    SetSigma: Any = ...
    GetSigmaArray: Any = ...
    GetSigma: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SetUseImageDirection: Any = ...
    GetUseImageDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGradientRecursiveGaussianImageFilterIF3ICVF23___New_orig__: Any
itkGradientRecursiveGaussianImageFilterIF3ICVF23_cast: Any

def itkGradientRecursiveGaussianImageFilterISS2ICVF22_New(): ...

class itkGradientRecursiveGaussianImageFilterISS2ICVF22(itk.itkImageToImageFilterBPython.itkImageToImageFilterISS2ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigmaArray: Any = ...
    SetSigma: Any = ...
    GetSigmaArray: Any = ...
    GetSigma: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SetUseImageDirection: Any = ...
    GetUseImageDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGradientRecursiveGaussianImageFilterISS2ICVF22___New_orig__: Any
itkGradientRecursiveGaussianImageFilterISS2ICVF22_cast: Any

def itkGradientRecursiveGaussianImageFilterISS3ICVF23_New(): ...

class itkGradientRecursiveGaussianImageFilterISS3ICVF23(itk.itkImageToImageFilterBPython.itkImageToImageFilterISS3ICVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigmaArray: Any = ...
    SetSigma: Any = ...
    GetSigmaArray: Any = ...
    GetSigma: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SetUseImageDirection: Any = ...
    GetUseImageDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGradientRecursiveGaussianImageFilterISS3ICVF23___New_orig__: Any
itkGradientRecursiveGaussianImageFilterISS3ICVF23_cast: Any

def itkGradientRecursiveGaussianImageFilterIUC2ICVF22_New(): ...

class itkGradientRecursiveGaussianImageFilterIUC2ICVF22(itk.itkImageToImageFilterBPython.itkImageToImageFilterIUC2ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigmaArray: Any = ...
    SetSigma: Any = ...
    GetSigmaArray: Any = ...
    GetSigma: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SetUseImageDirection: Any = ...
    GetUseImageDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGradientRecursiveGaussianImageFilterIUC2ICVF22___New_orig__: Any
itkGradientRecursiveGaussianImageFilterIUC2ICVF22_cast: Any

def itkGradientRecursiveGaussianImageFilterIUC3ICVF23_New(): ...

class itkGradientRecursiveGaussianImageFilterIUC3ICVF23(itk.itkImageToImageFilterBPython.itkImageToImageFilterIUC3ICVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigmaArray: Any = ...
    SetSigma: Any = ...
    GetSigmaArray: Any = ...
    GetSigma: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SetUseImageDirection: Any = ...
    GetUseImageDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGradientRecursiveGaussianImageFilterIUC3ICVF23___New_orig__: Any
itkGradientRecursiveGaussianImageFilterIUC3ICVF23_cast: Any

def itkGradientRecursiveGaussianImageFilterIVF22ICVF42_New(): ...

class itkGradientRecursiveGaussianImageFilterIVF22ICVF42(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF22ICVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigmaArray: Any = ...
    SetSigma: Any = ...
    GetSigmaArray: Any = ...
    GetSigma: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SetUseImageDirection: Any = ...
    GetUseImageDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGradientRecursiveGaussianImageFilterIVF22ICVF42___New_orig__: Any
itkGradientRecursiveGaussianImageFilterIVF22ICVF42_cast: Any

def itkGradientRecursiveGaussianImageFilterIVF23ICVF43_New(): ...

class itkGradientRecursiveGaussianImageFilterIVF23ICVF43(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF23ICVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigmaArray: Any = ...
    SetSigma: Any = ...
    GetSigmaArray: Any = ...
    GetSigma: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SetUseImageDirection: Any = ...
    GetUseImageDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGradientRecursiveGaussianImageFilterIVF23ICVF43___New_orig__: Any
itkGradientRecursiveGaussianImageFilterIVF23ICVF43_cast: Any

def gradient_recursive_gaussian_image_filter(*args: Any, **kwargs: Any): ...
def gradient_recursive_gaussian_image_filter_init_docstring() -> None: ...
