import itk.itkMathematicalMorphologyEnumsPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkGrayscaleMorphologicalClosingImageFilterIF2IF2SE2_New(): ...

class itkGrayscaleMorphologicalClosingImageFilterIF2IF2SE2(itk.itkFlatStructuringElementPython.itkKernelImageFilterIF2IF2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleMorphologicalClosingImageFilterIF2IF2SE2___New_orig__: Any
itkGrayscaleMorphologicalClosingImageFilterIF2IF2SE2_cast: Any

def itkGrayscaleMorphologicalClosingImageFilterIF3IF3SE3_New(): ...

class itkGrayscaleMorphologicalClosingImageFilterIF3IF3SE3(itk.itkFlatStructuringElementPython.itkKernelImageFilterIF3IF3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleMorphologicalClosingImageFilterIF3IF3SE3___New_orig__: Any
itkGrayscaleMorphologicalClosingImageFilterIF3IF3SE3_cast: Any

def itkGrayscaleMorphologicalClosingImageFilterISS2ISS2SE2_New(): ...

class itkGrayscaleMorphologicalClosingImageFilterISS2ISS2SE2(itk.itkFlatStructuringElementPython.itkKernelImageFilterISS2ISS2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleMorphologicalClosingImageFilterISS2ISS2SE2___New_orig__: Any
itkGrayscaleMorphologicalClosingImageFilterISS2ISS2SE2_cast: Any

def itkGrayscaleMorphologicalClosingImageFilterISS3ISS3SE3_New(): ...

class itkGrayscaleMorphologicalClosingImageFilterISS3ISS3SE3(itk.itkFlatStructuringElementPython.itkKernelImageFilterISS3ISS3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleMorphologicalClosingImageFilterISS3ISS3SE3___New_orig__: Any
itkGrayscaleMorphologicalClosingImageFilterISS3ISS3SE3_cast: Any

def itkGrayscaleMorphologicalClosingImageFilterIUC2IUC2SE2_New(): ...

class itkGrayscaleMorphologicalClosingImageFilterIUC2IUC2SE2(itk.itkFlatStructuringElementPython.itkKernelImageFilterIUC2IUC2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleMorphologicalClosingImageFilterIUC2IUC2SE2___New_orig__: Any
itkGrayscaleMorphologicalClosingImageFilterIUC2IUC2SE2_cast: Any

def itkGrayscaleMorphologicalClosingImageFilterIUC3IUC3SE3_New(): ...

class itkGrayscaleMorphologicalClosingImageFilterIUC3IUC3SE3(itk.itkFlatStructuringElementPython.itkKernelImageFilterIUC3IUC3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleMorphologicalClosingImageFilterIUC3IUC3SE3___New_orig__: Any
itkGrayscaleMorphologicalClosingImageFilterIUC3IUC3SE3_cast: Any

def grayscale_morphological_closing_image_filter(*args: Any, **kwargs: Any): ...
def grayscale_morphological_closing_image_filter_init_docstring() -> None: ...
