import itk.itkNeighborhoodPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkGrayscaleErodeImageFilterIF2IF2SE2_New(): ...

class itkGrayscaleErodeImageFilterIF2IF2SE2(itk.itkFlatStructuringElementPython.itkKernelImageFilterIF2IF2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetBoundary: Any = ...
    GetBoundary: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleErodeImageFilterIF2IF2SE2___New_orig__: Any
itkGrayscaleErodeImageFilterIF2IF2SE2_cast: Any

def itkGrayscaleErodeImageFilterIF3IF3SE3_New(): ...

class itkGrayscaleErodeImageFilterIF3IF3SE3(itk.itkFlatStructuringElementPython.itkKernelImageFilterIF3IF3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetBoundary: Any = ...
    GetBoundary: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleErodeImageFilterIF3IF3SE3___New_orig__: Any
itkGrayscaleErodeImageFilterIF3IF3SE3_cast: Any

def itkGrayscaleErodeImageFilterISS2ISS2SE2_New(): ...

class itkGrayscaleErodeImageFilterISS2ISS2SE2(itk.itkFlatStructuringElementPython.itkKernelImageFilterISS2ISS2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetBoundary: Any = ...
    GetBoundary: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleErodeImageFilterISS2ISS2SE2___New_orig__: Any
itkGrayscaleErodeImageFilterISS2ISS2SE2_cast: Any

def itkGrayscaleErodeImageFilterISS3ISS3SE3_New(): ...

class itkGrayscaleErodeImageFilterISS3ISS3SE3(itk.itkFlatStructuringElementPython.itkKernelImageFilterISS3ISS3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetBoundary: Any = ...
    GetBoundary: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleErodeImageFilterISS3ISS3SE3___New_orig__: Any
itkGrayscaleErodeImageFilterISS3ISS3SE3_cast: Any

def itkGrayscaleErodeImageFilterIUC2IUC2SE2_New(): ...

class itkGrayscaleErodeImageFilterIUC2IUC2SE2(itk.itkFlatStructuringElementPython.itkKernelImageFilterIUC2IUC2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetBoundary: Any = ...
    GetBoundary: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleErodeImageFilterIUC2IUC2SE2___New_orig__: Any
itkGrayscaleErodeImageFilterIUC2IUC2SE2_cast: Any

def itkGrayscaleErodeImageFilterIUC3IUC3SE3_New(): ...

class itkGrayscaleErodeImageFilterIUC3IUC3SE3(itk.itkFlatStructuringElementPython.itkKernelImageFilterIUC3IUC3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetBoundary: Any = ...
    GetBoundary: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleErodeImageFilterIUC3IUC3SE3___New_orig__: Any
itkGrayscaleErodeImageFilterIUC3IUC3SE3_cast: Any

def grayscale_erode_image_filter(*args: Any, **kwargs: Any): ...
def grayscale_erode_image_filter_init_docstring() -> None: ...
