import itk.stdcomplexPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkGEAdwImageIO_New(): ...

class itkGEAdwImageIO(itk.itkIPLCommonImageIOPython.itkIPLCommonImageIO):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGEAdwImageIO___New_orig__: Any
itkGEAdwImageIO_cast: Any

def itkGEAdwImageIOFactory_New(): ...

class itkGEAdwImageIOFactory(itk.ITKCommonBasePython.itkObjectFactoryBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    RegisterOneFactory: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGEAdwImageIOFactory___New_orig__: Any
itkGEAdwImageIOFactory_RegisterOneFactory: Any
itkGEAdwImageIOFactory_cast: Any
