import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkGrayscaleFillholeImageFilterIF2IF2_New(): ...

class itkGrayscaleFillholeImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleFillholeImageFilterIF2IF2___New_orig__: Any
itkGrayscaleFillholeImageFilterIF2IF2_cast: Any

def itkGrayscaleFillholeImageFilterIF3IF3_New(): ...

class itkGrayscaleFillholeImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleFillholeImageFilterIF3IF3___New_orig__: Any
itkGrayscaleFillholeImageFilterIF3IF3_cast: Any

def itkGrayscaleFillholeImageFilterISS2ISS2_New(): ...

class itkGrayscaleFillholeImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleFillholeImageFilterISS2ISS2___New_orig__: Any
itkGrayscaleFillholeImageFilterISS2ISS2_cast: Any

def itkGrayscaleFillholeImageFilterISS3ISS3_New(): ...

class itkGrayscaleFillholeImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleFillholeImageFilterISS3ISS3___New_orig__: Any
itkGrayscaleFillholeImageFilterISS3ISS3_cast: Any

def itkGrayscaleFillholeImageFilterIUC2IUC2_New(): ...

class itkGrayscaleFillholeImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleFillholeImageFilterIUC2IUC2___New_orig__: Any
itkGrayscaleFillholeImageFilterIUC2IUC2_cast: Any

def itkGrayscaleFillholeImageFilterIUC3IUC3_New(): ...

class itkGrayscaleFillholeImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    InputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGrayscaleFillholeImageFilterIUC3IUC3___New_orig__: Any
itkGrayscaleFillholeImageFilterIUC3IUC3_cast: Any

def grayscale_fillhole_image_filter(*args: Any, **kwargs: Any): ...
def grayscale_fillhole_image_filter_init_docstring() -> None: ...
