import itk.stdcomplexPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkGE5ImageIO_New(): ...

class itkGE5ImageIO(itk.itkIPLCommonImageIOPython.itkIPLCommonImageIO):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGE5ImageIO___New_orig__: Any
itkGE5ImageIO_cast: Any

def itkGE5ImageIOFactory_New(): ...

class itkGE5ImageIOFactory(itk.ITKCommonBasePython.itkObjectFactoryBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    RegisterOneFactory: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGE5ImageIOFactory___New_orig__: Any
itkGE5ImageIOFactory_RegisterOneFactory: Any
itkGE5ImageIOFactory_cast: Any
