import itk.itkArrayPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkHalfToFullHermitianImageFilterICF2_New(): ...

class itkHalfToFullHermitianImageFilterICF2(itk.itkImageToImageFilterBPython.itkImageToImageFilterICF2ICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetActualXDimensionIsOddInput: Any = ...
    SetActualXDimensionIsOdd: Any = ...
    GetActualXDimensionIsOddInput: Any = ...
    GetActualXDimensionIsOdd: Any = ...
    ActualXDimensionIsOddOn: Any = ...
    ActualXDimensionIsOddOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHalfToFullHermitianImageFilterICF2___New_orig__: Any
itkHalfToFullHermitianImageFilterICF2_cast: Any

def itkHalfToFullHermitianImageFilterICF3_New(): ...

class itkHalfToFullHermitianImageFilterICF3(itk.itkImageToImageFilterBPython.itkImageToImageFilterICF3ICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetActualXDimensionIsOddInput: Any = ...
    SetActualXDimensionIsOdd: Any = ...
    GetActualXDimensionIsOddInput: Any = ...
    GetActualXDimensionIsOdd: Any = ...
    ActualXDimensionIsOddOn: Any = ...
    ActualXDimensionIsOddOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHalfToFullHermitianImageFilterICF3___New_orig__: Any
itkHalfToFullHermitianImageFilterICF3_cast: Any

def half_to_full_hermitian_image_filter(*args: Any, **kwargs: Any): ...
def half_to_full_hermitian_image_filter_init_docstring() -> None: ...
