import itk.itkSamplePython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkHuangThresholdCalculatorHDF_New(): ...

class itkHuangThresholdCalculatorHDF(itk.itkHistogramThresholdCalculatorPython.itkHistogramThresholdCalculatorHDF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHuangThresholdCalculatorHDF___New_orig__: Any
itkHuangThresholdCalculatorHDF_cast: Any

def itkHuangThresholdCalculatorHDSS_New(): ...

class itkHuangThresholdCalculatorHDSS(itk.itkHistogramThresholdCalculatorPython.itkHistogramThresholdCalculatorHDSS):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHuangThresholdCalculatorHDSS___New_orig__: Any
itkHuangThresholdCalculatorHDSS_cast: Any

def itkHuangThresholdCalculatorHDUC_New(): ...

class itkHuangThresholdCalculatorHDUC(itk.itkHistogramThresholdCalculatorPython.itkHistogramThresholdCalculatorHDUC):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHuangThresholdCalculatorHDUC___New_orig__: Any
itkHuangThresholdCalculatorHDUC_cast: Any

def itkHuangThresholdCalculatorHFF_New(): ...

class itkHuangThresholdCalculatorHFF(itk.itkHistogramThresholdCalculatorPython.itkHistogramThresholdCalculatorHFF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHuangThresholdCalculatorHFF___New_orig__: Any
itkHuangThresholdCalculatorHFF_cast: Any

def itkHuangThresholdCalculatorHFSS_New(): ...

class itkHuangThresholdCalculatorHFSS(itk.itkHistogramThresholdCalculatorPython.itkHistogramThresholdCalculatorHFSS):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHuangThresholdCalculatorHFSS___New_orig__: Any
itkHuangThresholdCalculatorHFSS_cast: Any

def itkHuangThresholdCalculatorHFUC_New(): ...

class itkHuangThresholdCalculatorHFUC(itk.itkHistogramThresholdCalculatorPython.itkHistogramThresholdCalculatorHFUC):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHuangThresholdCalculatorHFUC___New_orig__: Any
itkHuangThresholdCalculatorHFUC_cast: Any

def huang_threshold_calculator(*args: Any, **kwargs: Any): ...
def huang_threshold_calculator_init_docstring() -> None: ...
