import itk.itkVectorImagePython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkHoughTransform2DCirclesImageFilterFULF_New(): ...

class itkHoughTransform2DCirclesImageFilterFULF(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IUL2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    VerifyPreconditions: Any = ...
    GenerateData: Any = ...
    SetRadius: Any = ...
    SetMinimumRadius: Any = ...
    GetMinimumRadius: Any = ...
    SetMaximumRadius: Any = ...
    GetMaximumRadius: Any = ...
    SetThreshold: Any = ...
    GetThreshold: Any = ...
    SetGradientNormThreshold: Any = ...
    GetGradientNormThreshold: Any = ...
    GetModifiableRadiusImage: Any = ...
    GetRadiusImage: Any = ...
    SetSigmaGradient: Any = ...
    GetSigmaGradient: Any = ...
    GetCircles: Any = ...
    SetNumberOfCircles: Any = ...
    GetNumberOfCircles: Any = ...
    SetDiscRadiusRatio: Any = ...
    GetDiscRadiusRatio: Any = ...
    SetVariance: Any = ...
    GetVariance: Any = ...
    SetSweepAngle: Any = ...
    GetSweepAngle: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    IntConvertibleToOutputCheck: Any = ...
    InputGreaterThanDoubleCheck: Any = ...
    OutputPlusIntCheck: Any = ...
    OutputDividedByIntCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHoughTransform2DCirclesImageFilterFULF___New_orig__: Any
itkHoughTransform2DCirclesImageFilterFULF_cast: Any

def itkHoughTransform2DCirclesImageFilterSSULF_New(): ...

class itkHoughTransform2DCirclesImageFilterSSULF(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2IUL2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    VerifyPreconditions: Any = ...
    GenerateData: Any = ...
    SetRadius: Any = ...
    SetMinimumRadius: Any = ...
    GetMinimumRadius: Any = ...
    SetMaximumRadius: Any = ...
    GetMaximumRadius: Any = ...
    SetThreshold: Any = ...
    GetThreshold: Any = ...
    SetGradientNormThreshold: Any = ...
    GetGradientNormThreshold: Any = ...
    GetModifiableRadiusImage: Any = ...
    GetRadiusImage: Any = ...
    SetSigmaGradient: Any = ...
    GetSigmaGradient: Any = ...
    GetCircles: Any = ...
    SetNumberOfCircles: Any = ...
    GetNumberOfCircles: Any = ...
    SetDiscRadiusRatio: Any = ...
    GetDiscRadiusRatio: Any = ...
    SetVariance: Any = ...
    GetVariance: Any = ...
    SetSweepAngle: Any = ...
    GetSweepAngle: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    IntConvertibleToOutputCheck: Any = ...
    InputGreaterThanDoubleCheck: Any = ...
    OutputPlusIntCheck: Any = ...
    OutputDividedByIntCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHoughTransform2DCirclesImageFilterSSULF___New_orig__: Any
itkHoughTransform2DCirclesImageFilterSSULF_cast: Any

def itkHoughTransform2DCirclesImageFilterUCULF_New(): ...

class itkHoughTransform2DCirclesImageFilterUCULF(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUL2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    VerifyPreconditions: Any = ...
    GenerateData: Any = ...
    SetRadius: Any = ...
    SetMinimumRadius: Any = ...
    GetMinimumRadius: Any = ...
    SetMaximumRadius: Any = ...
    GetMaximumRadius: Any = ...
    SetThreshold: Any = ...
    GetThreshold: Any = ...
    SetGradientNormThreshold: Any = ...
    GetGradientNormThreshold: Any = ...
    GetModifiableRadiusImage: Any = ...
    GetRadiusImage: Any = ...
    SetSigmaGradient: Any = ...
    GetSigmaGradient: Any = ...
    GetCircles: Any = ...
    SetNumberOfCircles: Any = ...
    GetNumberOfCircles: Any = ...
    SetDiscRadiusRatio: Any = ...
    GetDiscRadiusRatio: Any = ...
    SetVariance: Any = ...
    GetVariance: Any = ...
    SetSweepAngle: Any = ...
    GetSweepAngle: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    IntConvertibleToOutputCheck: Any = ...
    InputGreaterThanDoubleCheck: Any = ...
    OutputPlusIntCheck: Any = ...
    OutputDividedByIntCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHoughTransform2DCirclesImageFilterUCULF___New_orig__: Any
itkHoughTransform2DCirclesImageFilterUCULF_cast: Any

def hough_transform2_d_circles_image_filter(*args: Any, **kwargs: Any): ...
def hough_transform2_d_circles_image_filter_init_docstring() -> None: ...
