import itk.itkArrayPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkHalfHermitianToRealInverseFFTImageFilterICF2IF2_New(): ...

class itkHalfHermitianToRealInverseFFTImageFilterICF2IF2(itk.itkImageToImageFilterBPython.itkImageToImageFilterICF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    SetActualXDimensionIsOddInput: Any = ...
    SetActualXDimensionIsOdd: Any = ...
    GetActualXDimensionIsOddInput: Any = ...
    GetActualXDimensionIsOdd: Any = ...
    ActualXDimensionIsOddOn: Any = ...
    ActualXDimensionIsOddOff: Any = ...
    GetSizeGreatestPrimeFactor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHalfHermitianToRealInverseFFTImageFilterICF2IF2___New_orig__: Any
itkHalfHermitianToRealInverseFFTImageFilterICF2IF2_cast: Any

def itkHalfHermitianToRealInverseFFTImageFilterICF3IF3_New(): ...

class itkHalfHermitianToRealInverseFFTImageFilterICF3IF3(itk.itkImageToImageFilterBPython.itkImageToImageFilterICF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    SetActualXDimensionIsOddInput: Any = ...
    SetActualXDimensionIsOdd: Any = ...
    GetActualXDimensionIsOddInput: Any = ...
    GetActualXDimensionIsOdd: Any = ...
    ActualXDimensionIsOddOn: Any = ...
    ActualXDimensionIsOddOff: Any = ...
    GetSizeGreatestPrimeFactor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHalfHermitianToRealInverseFFTImageFilterICF3IF3___New_orig__: Any
itkHalfHermitianToRealInverseFFTImageFilterICF3IF3_cast: Any

def half_hermitian_to_real_inverse_fft_image_filter(*args: Any, **kwargs: Any): ...
def half_hermitian_to_real_inverse_fft_image_filter_init_docstring() -> None: ...
