import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkHardConnectedComponentImageFilterISS2ISS2_New(): ...

class itkHardConnectedComponentImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetObjectSeed: Any = ...
    SameDimensionCheck: Any = ...
    IntConvertibleToOutputCheck: Any = ...
    UnsignedShortConvertibleToOutputCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    UnsignedCharConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHardConnectedComponentImageFilterISS2ISS2___New_orig__: Any
itkHardConnectedComponentImageFilterISS2ISS2_cast: Any

def itkHardConnectedComponentImageFilterISS2IUL2_New(): ...

class itkHardConnectedComponentImageFilterISS2IUL2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2IUL2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetObjectSeed: Any = ...
    SameDimensionCheck: Any = ...
    IntConvertibleToOutputCheck: Any = ...
    UnsignedShortConvertibleToOutputCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    UnsignedCharConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHardConnectedComponentImageFilterISS2IUL2___New_orig__: Any
itkHardConnectedComponentImageFilterISS2IUL2_cast: Any

def itkHardConnectedComponentImageFilterISS3ISS3_New(): ...

class itkHardConnectedComponentImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetObjectSeed: Any = ...
    SameDimensionCheck: Any = ...
    IntConvertibleToOutputCheck: Any = ...
    UnsignedShortConvertibleToOutputCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    UnsignedCharConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHardConnectedComponentImageFilterISS3ISS3___New_orig__: Any
itkHardConnectedComponentImageFilterISS3ISS3_cast: Any

def itkHardConnectedComponentImageFilterISS3IUL3_New(): ...

class itkHardConnectedComponentImageFilterISS3IUL3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3IUL3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetObjectSeed: Any = ...
    SameDimensionCheck: Any = ...
    IntConvertibleToOutputCheck: Any = ...
    UnsignedShortConvertibleToOutputCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    UnsignedCharConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHardConnectedComponentImageFilterISS3IUL3___New_orig__: Any
itkHardConnectedComponentImageFilterISS3IUL3_cast: Any

def itkHardConnectedComponentImageFilterIUC2ISS2_New(): ...

class itkHardConnectedComponentImageFilterIUC2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetObjectSeed: Any = ...
    SameDimensionCheck: Any = ...
    IntConvertibleToOutputCheck: Any = ...
    UnsignedShortConvertibleToOutputCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    UnsignedCharConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHardConnectedComponentImageFilterIUC2ISS2___New_orig__: Any
itkHardConnectedComponentImageFilterIUC2ISS2_cast: Any

def itkHardConnectedComponentImageFilterIUC2IUL2_New(): ...

class itkHardConnectedComponentImageFilterIUC2IUL2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUL2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetObjectSeed: Any = ...
    SameDimensionCheck: Any = ...
    IntConvertibleToOutputCheck: Any = ...
    UnsignedShortConvertibleToOutputCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    UnsignedCharConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHardConnectedComponentImageFilterIUC2IUL2___New_orig__: Any
itkHardConnectedComponentImageFilterIUC2IUL2_cast: Any

def itkHardConnectedComponentImageFilterIUC3ISS3_New(): ...

class itkHardConnectedComponentImageFilterIUC3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetObjectSeed: Any = ...
    SameDimensionCheck: Any = ...
    IntConvertibleToOutputCheck: Any = ...
    UnsignedShortConvertibleToOutputCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    UnsignedCharConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHardConnectedComponentImageFilterIUC3ISS3___New_orig__: Any
itkHardConnectedComponentImageFilterIUC3ISS3_cast: Any

def itkHardConnectedComponentImageFilterIUC3IUL3_New(): ...

class itkHardConnectedComponentImageFilterIUC3IUL3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUL3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetObjectSeed: Any = ...
    SameDimensionCheck: Any = ...
    IntConvertibleToOutputCheck: Any = ...
    UnsignedShortConvertibleToOutputCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    UnsignedCharConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHardConnectedComponentImageFilterIUC3IUL3___New_orig__: Any
itkHardConnectedComponentImageFilterIUC3IUL3_cast: Any

def hard_connected_component_image_filter(*args: Any, **kwargs: Any): ...
def hard_connected_component_image_filter_init_docstring() -> None: ...
