import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkHausdorffDistanceImageFilterIF2IF2_New(): ...

class itkHausdorffDistanceImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    GetInput1: Any = ...
    GetInput2: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    GetHausdorffDistance: Any = ...
    GetAverageHausdorffDistance: Any = ...
    Input1HasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHausdorffDistanceImageFilterIF2IF2___New_orig__: Any
itkHausdorffDistanceImageFilterIF2IF2_cast: Any

def itkHausdorffDistanceImageFilterIF3IF3_New(): ...

class itkHausdorffDistanceImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    GetInput1: Any = ...
    GetInput2: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    GetHausdorffDistance: Any = ...
    GetAverageHausdorffDistance: Any = ...
    Input1HasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHausdorffDistanceImageFilterIF3IF3___New_orig__: Any
itkHausdorffDistanceImageFilterIF3IF3_cast: Any

def itkHausdorffDistanceImageFilterISS2ISS2_New(): ...

class itkHausdorffDistanceImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    GetInput1: Any = ...
    GetInput2: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    GetHausdorffDistance: Any = ...
    GetAverageHausdorffDistance: Any = ...
    Input1HasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHausdorffDistanceImageFilterISS2ISS2___New_orig__: Any
itkHausdorffDistanceImageFilterISS2ISS2_cast: Any

def itkHausdorffDistanceImageFilterISS3ISS3_New(): ...

class itkHausdorffDistanceImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    GetInput1: Any = ...
    GetInput2: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    GetHausdorffDistance: Any = ...
    GetAverageHausdorffDistance: Any = ...
    Input1HasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHausdorffDistanceImageFilterISS3ISS3___New_orig__: Any
itkHausdorffDistanceImageFilterISS3ISS3_cast: Any

def itkHausdorffDistanceImageFilterIUC2IF2_New(): ...

class itkHausdorffDistanceImageFilterIUC2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    GetInput1: Any = ...
    GetInput2: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    GetHausdorffDistance: Any = ...
    GetAverageHausdorffDistance: Any = ...
    Input1HasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHausdorffDistanceImageFilterIUC2IF2___New_orig__: Any
itkHausdorffDistanceImageFilterIUC2IF2_cast: Any

def itkHausdorffDistanceImageFilterIUC3IF3_New(): ...

class itkHausdorffDistanceImageFilterIUC3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    GetInput1: Any = ...
    GetInput2: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    GetHausdorffDistance: Any = ...
    GetAverageHausdorffDistance: Any = ...
    Input1HasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHausdorffDistanceImageFilterIUC3IF3___New_orig__: Any
itkHausdorffDistanceImageFilterIUC3IF3_cast: Any

def hausdorff_distance_image_filter(*args: Any, **kwargs: Any): ...
def hausdorff_distance_image_filter_init_docstring() -> None: ...
