import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkHessianRecursiveGaussianImageFilterIF2_New(): ...

class itkHessianRecursiveGaussianImageFilterIF2(itk.itkImageToImageFilterBPython.itkImageToImageFilterIF2ISSRTD22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasPixelTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHessianRecursiveGaussianImageFilterIF2___New_orig__: Any
itkHessianRecursiveGaussianImageFilterIF2_cast: Any

def itkHessianRecursiveGaussianImageFilterIF3_New(): ...

class itkHessianRecursiveGaussianImageFilterIF3(itk.itkImageToImageFilterBPython.itkImageToImageFilterIF3ISSRTD33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasPixelTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHessianRecursiveGaussianImageFilterIF3___New_orig__: Any
itkHessianRecursiveGaussianImageFilterIF3_cast: Any

def itkHessianRecursiveGaussianImageFilterISS2_New(): ...

class itkHessianRecursiveGaussianImageFilterISS2(itk.itkImageToImageFilterBPython.itkImageToImageFilterISS2ISSRTD22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasPixelTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHessianRecursiveGaussianImageFilterISS2___New_orig__: Any
itkHessianRecursiveGaussianImageFilterISS2_cast: Any

def itkHessianRecursiveGaussianImageFilterISS3_New(): ...

class itkHessianRecursiveGaussianImageFilterISS3(itk.itkImageToImageFilterBPython.itkImageToImageFilterISS3ISSRTD33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasPixelTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHessianRecursiveGaussianImageFilterISS3___New_orig__: Any
itkHessianRecursiveGaussianImageFilterISS3_cast: Any

def itkHessianRecursiveGaussianImageFilterIUC2_New(): ...

class itkHessianRecursiveGaussianImageFilterIUC2(itk.itkImageToImageFilterBPython.itkImageToImageFilterIUC2ISSRTD22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasPixelTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHessianRecursiveGaussianImageFilterIUC2___New_orig__: Any
itkHessianRecursiveGaussianImageFilterIUC2_cast: Any

def itkHessianRecursiveGaussianImageFilterIUC3_New(): ...

class itkHessianRecursiveGaussianImageFilterIUC3(itk.itkImageToImageFilterBPython.itkImageToImageFilterIUC3ISSRTD33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSigma: Any = ...
    GetSigma: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasPixelTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHessianRecursiveGaussianImageFilterIUC3___New_orig__: Any
itkHessianRecursiveGaussianImageFilterIUC3_cast: Any

def hessian_recursive_gaussian_image_filter(*args: Any, **kwargs: Any): ...
def hessian_recursive_gaussian_image_filter_init_docstring() -> None: ...
