import itk.itkSamplePython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkHistogramThresholdCalculatorHDF_New(): ...

class itkHistogramThresholdCalculatorHDF(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GetThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHistogramThresholdCalculatorHDF___New_orig__: Any
itkHistogramThresholdCalculatorHDF_cast: Any

def itkHistogramThresholdCalculatorHDSS_New(): ...

class itkHistogramThresholdCalculatorHDSS(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GetThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHistogramThresholdCalculatorHDSS___New_orig__: Any
itkHistogramThresholdCalculatorHDSS_cast: Any

def itkHistogramThresholdCalculatorHDUC_New(): ...

class itkHistogramThresholdCalculatorHDUC(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GetThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHistogramThresholdCalculatorHDUC___New_orig__: Any
itkHistogramThresholdCalculatorHDUC_cast: Any

def itkHistogramThresholdCalculatorHFF_New(): ...

class itkHistogramThresholdCalculatorHFF(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GetThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHistogramThresholdCalculatorHFF___New_orig__: Any
itkHistogramThresholdCalculatorHFF_cast: Any

def itkHistogramThresholdCalculatorHFSS_New(): ...

class itkHistogramThresholdCalculatorHFSS(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GetThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHistogramThresholdCalculatorHFSS___New_orig__: Any
itkHistogramThresholdCalculatorHFSS_cast: Any

def itkHistogramThresholdCalculatorHFUC_New(): ...

class itkHistogramThresholdCalculatorHFUC(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GetThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHistogramThresholdCalculatorHFUC___New_orig__: Any
itkHistogramThresholdCalculatorHFUC_cast: Any

def histogram_threshold_calculator(*args: Any, **kwargs: Any): ...
def histogram_threshold_calculator_init_docstring() -> None: ...
