import itk.vnl_vector_refPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkHistogramD_New(): ...

class itkHistogramD(itk.itkSamplePython.itkSampleAD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Initialize: Any = ...
    SetToZero: Any = ...
    GetIndex: Any = ...
    GetClipBinsAtEnds: Any = ...
    SetClipBinsAtEnds: Any = ...
    IsIndexOutOfBounds: Any = ...
    GetInstanceIdentifier: Any = ...
    GetSize: Any = ...
    GetBinMin: Any = ...
    GetBinMax: Any = ...
    SetBinMin: Any = ...
    SetBinMax: Any = ...
    GetBinMinFromValue: Any = ...
    GetBinMaxFromValue: Any = ...
    GetDimensionMins: Any = ...
    GetDimensionMaxs: Any = ...
    GetMins: Any = ...
    GetMaxs: Any = ...
    GetHistogramMinFromIndex: Any = ...
    GetHistogramMaxFromIndex: Any = ...
    SetFrequency: Any = ...
    SetFrequencyOfIndex: Any = ...
    SetFrequencyOfMeasurement: Any = ...
    IncreaseFrequency: Any = ...
    IncreaseFrequencyOfIndex: Any = ...
    IncreaseFrequencyOfMeasurement: Any = ...
    GetMeasurementVector: Any = ...
    GetMeasurement: Any = ...
    GetFrequency: Any = ...
    Quantile: Any = ...
    Mean: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHistogramD___New_orig__: Any
itkHistogramD_cast: Any

def itkHistogramF_New(): ...

class itkHistogramF(itk.itkSamplePython.itkSampleAF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Initialize: Any = ...
    SetToZero: Any = ...
    GetIndex: Any = ...
    GetClipBinsAtEnds: Any = ...
    SetClipBinsAtEnds: Any = ...
    IsIndexOutOfBounds: Any = ...
    GetInstanceIdentifier: Any = ...
    GetSize: Any = ...
    GetBinMin: Any = ...
    GetBinMax: Any = ...
    SetBinMin: Any = ...
    SetBinMax: Any = ...
    GetBinMinFromValue: Any = ...
    GetBinMaxFromValue: Any = ...
    GetDimensionMins: Any = ...
    GetDimensionMaxs: Any = ...
    GetMins: Any = ...
    GetMaxs: Any = ...
    GetHistogramMinFromIndex: Any = ...
    GetHistogramMaxFromIndex: Any = ...
    SetFrequency: Any = ...
    SetFrequencyOfIndex: Any = ...
    SetFrequencyOfMeasurement: Any = ...
    IncreaseFrequency: Any = ...
    IncreaseFrequencyOfIndex: Any = ...
    IncreaseFrequencyOfMeasurement: Any = ...
    GetMeasurementVector: Any = ...
    GetMeasurement: Any = ...
    GetFrequency: Any = ...
    Quantile: Any = ...
    Mean: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHistogramF___New_orig__: Any
itkHistogramF_cast: Any

def itkSimpleDataObjectDecoratorHD_New(): ...

class itkSimpleDataObjectDecoratorHD(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorHD___New_orig__: Any
itkSimpleDataObjectDecoratorHD_cast: Any

def itkSimpleDataObjectDecoratorHF_New(): ...

class itkSimpleDataObjectDecoratorHF(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorHF___New_orig__: Any
itkSimpleDataObjectDecoratorHF_cast: Any
