import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkHessianToObjectnessMeasureImageFilterISSRTD22IF2_New(): ...

class itkHessianToObjectnessMeasureImageFilterISSRTD22IF2(itk.itkImageToImageFilterBPython.itkImageToImageFilterISSRTD22IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetBeta: Any = ...
    GetBeta: Any = ...
    SetGamma: Any = ...
    GetGamma: Any = ...
    SetScaleObjectnessMeasure: Any = ...
    GetScaleObjectnessMeasure: Any = ...
    ScaleObjectnessMeasureOn: Any = ...
    ScaleObjectnessMeasureOff: Any = ...
    SetObjectDimension: Any = ...
    GetObjectDimension: Any = ...
    SetBrightObject: Any = ...
    GetBrightObject: Any = ...
    BrightObjectOn: Any = ...
    BrightObjectOff: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHessianToObjectnessMeasureImageFilterISSRTD22IF2___New_orig__: Any
itkHessianToObjectnessMeasureImageFilterISSRTD22IF2_cast: Any

def itkHessianToObjectnessMeasureImageFilterISSRTD22ISS2_New(): ...

class itkHessianToObjectnessMeasureImageFilterISSRTD22ISS2(itk.itkImageToImageFilterBPython.itkImageToImageFilterISSRTD22ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetBeta: Any = ...
    GetBeta: Any = ...
    SetGamma: Any = ...
    GetGamma: Any = ...
    SetScaleObjectnessMeasure: Any = ...
    GetScaleObjectnessMeasure: Any = ...
    ScaleObjectnessMeasureOn: Any = ...
    ScaleObjectnessMeasureOff: Any = ...
    SetObjectDimension: Any = ...
    GetObjectDimension: Any = ...
    SetBrightObject: Any = ...
    GetBrightObject: Any = ...
    BrightObjectOn: Any = ...
    BrightObjectOff: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHessianToObjectnessMeasureImageFilterISSRTD22ISS2___New_orig__: Any
itkHessianToObjectnessMeasureImageFilterISSRTD22ISS2_cast: Any

def itkHessianToObjectnessMeasureImageFilterISSRTD22IUC2_New(): ...

class itkHessianToObjectnessMeasureImageFilterISSRTD22IUC2(itk.itkImageToImageFilterBPython.itkImageToImageFilterISSRTD22IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetBeta: Any = ...
    GetBeta: Any = ...
    SetGamma: Any = ...
    GetGamma: Any = ...
    SetScaleObjectnessMeasure: Any = ...
    GetScaleObjectnessMeasure: Any = ...
    ScaleObjectnessMeasureOn: Any = ...
    ScaleObjectnessMeasureOff: Any = ...
    SetObjectDimension: Any = ...
    GetObjectDimension: Any = ...
    SetBrightObject: Any = ...
    GetBrightObject: Any = ...
    BrightObjectOn: Any = ...
    BrightObjectOff: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHessianToObjectnessMeasureImageFilterISSRTD22IUC2___New_orig__: Any
itkHessianToObjectnessMeasureImageFilterISSRTD22IUC2_cast: Any

def itkHessianToObjectnessMeasureImageFilterISSRTD33IF3_New(): ...

class itkHessianToObjectnessMeasureImageFilterISSRTD33IF3(itk.itkImageToImageFilterBPython.itkImageToImageFilterISSRTD33IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetBeta: Any = ...
    GetBeta: Any = ...
    SetGamma: Any = ...
    GetGamma: Any = ...
    SetScaleObjectnessMeasure: Any = ...
    GetScaleObjectnessMeasure: Any = ...
    ScaleObjectnessMeasureOn: Any = ...
    ScaleObjectnessMeasureOff: Any = ...
    SetObjectDimension: Any = ...
    GetObjectDimension: Any = ...
    SetBrightObject: Any = ...
    GetBrightObject: Any = ...
    BrightObjectOn: Any = ...
    BrightObjectOff: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHessianToObjectnessMeasureImageFilterISSRTD33IF3___New_orig__: Any
itkHessianToObjectnessMeasureImageFilterISSRTD33IF3_cast: Any

def itkHessianToObjectnessMeasureImageFilterISSRTD33ISS3_New(): ...

class itkHessianToObjectnessMeasureImageFilterISSRTD33ISS3(itk.itkImageToImageFilterBPython.itkImageToImageFilterISSRTD33ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetBeta: Any = ...
    GetBeta: Any = ...
    SetGamma: Any = ...
    GetGamma: Any = ...
    SetScaleObjectnessMeasure: Any = ...
    GetScaleObjectnessMeasure: Any = ...
    ScaleObjectnessMeasureOn: Any = ...
    ScaleObjectnessMeasureOff: Any = ...
    SetObjectDimension: Any = ...
    GetObjectDimension: Any = ...
    SetBrightObject: Any = ...
    GetBrightObject: Any = ...
    BrightObjectOn: Any = ...
    BrightObjectOff: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHessianToObjectnessMeasureImageFilterISSRTD33ISS3___New_orig__: Any
itkHessianToObjectnessMeasureImageFilterISSRTD33ISS3_cast: Any

def itkHessianToObjectnessMeasureImageFilterISSRTD33IUC3_New(): ...

class itkHessianToObjectnessMeasureImageFilterISSRTD33IUC3(itk.itkImageToImageFilterBPython.itkImageToImageFilterISSRTD33IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetBeta: Any = ...
    GetBeta: Any = ...
    SetGamma: Any = ...
    GetGamma: Any = ...
    SetScaleObjectnessMeasure: Any = ...
    GetScaleObjectnessMeasure: Any = ...
    ScaleObjectnessMeasureOn: Any = ...
    ScaleObjectnessMeasureOff: Any = ...
    SetObjectDimension: Any = ...
    GetObjectDimension: Any = ...
    SetBrightObject: Any = ...
    GetBrightObject: Any = ...
    BrightObjectOn: Any = ...
    BrightObjectOff: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHessianToObjectnessMeasureImageFilterISSRTD33IUC3___New_orig__: Any
itkHessianToObjectnessMeasureImageFilterISSRTD33IUC3_cast: Any

def hessian_to_objectness_measure_image_filter(*args: Any, **kwargs: Any): ...
def hessian_to_objectness_measure_image_filter_init_docstring() -> None: ...
