import itk.itkImageSourceCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkHuangThresholdImageFilterIF2ISS2_New(): ...

class itkHuangThresholdImageFilterIF2ISS2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHuangThresholdImageFilterIF2ISS2___New_orig__: Any
itkHuangThresholdImageFilterIF2ISS2_cast: Any

def itkHuangThresholdImageFilterIF2IUC2_New(): ...

class itkHuangThresholdImageFilterIF2IUC2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHuangThresholdImageFilterIF2IUC2___New_orig__: Any
itkHuangThresholdImageFilterIF2IUC2_cast: Any

def itkHuangThresholdImageFilterIF3ISS3_New(): ...

class itkHuangThresholdImageFilterIF3ISS3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHuangThresholdImageFilterIF3ISS3___New_orig__: Any
itkHuangThresholdImageFilterIF3ISS3_cast: Any

def itkHuangThresholdImageFilterIF3IUC3_New(): ...

class itkHuangThresholdImageFilterIF3IUC3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHuangThresholdImageFilterIF3IUC3___New_orig__: Any
itkHuangThresholdImageFilterIF3IUC3_cast: Any

def itkHuangThresholdImageFilterISS2ISS2_New(): ...

class itkHuangThresholdImageFilterISS2ISS2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHuangThresholdImageFilterISS2ISS2___New_orig__: Any
itkHuangThresholdImageFilterISS2ISS2_cast: Any

def itkHuangThresholdImageFilterISS2IUC2_New(): ...

class itkHuangThresholdImageFilterISS2IUC2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHuangThresholdImageFilterISS2IUC2___New_orig__: Any
itkHuangThresholdImageFilterISS2IUC2_cast: Any

def itkHuangThresholdImageFilterISS3ISS3_New(): ...

class itkHuangThresholdImageFilterISS3ISS3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHuangThresholdImageFilterISS3ISS3___New_orig__: Any
itkHuangThresholdImageFilterISS3ISS3_cast: Any

def itkHuangThresholdImageFilterISS3IUC3_New(): ...

class itkHuangThresholdImageFilterISS3IUC3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHuangThresholdImageFilterISS3IUC3___New_orig__: Any
itkHuangThresholdImageFilterISS3IUC3_cast: Any

def itkHuangThresholdImageFilterIUC2ISS2_New(): ...

class itkHuangThresholdImageFilterIUC2ISS2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHuangThresholdImageFilterIUC2ISS2___New_orig__: Any
itkHuangThresholdImageFilterIUC2ISS2_cast: Any

def itkHuangThresholdImageFilterIUC2IUC2_New(): ...

class itkHuangThresholdImageFilterIUC2IUC2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHuangThresholdImageFilterIUC2IUC2___New_orig__: Any
itkHuangThresholdImageFilterIUC2IUC2_cast: Any

def itkHuangThresholdImageFilterIUC3ISS3_New(): ...

class itkHuangThresholdImageFilterIUC3ISS3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHuangThresholdImageFilterIUC3ISS3___New_orig__: Any
itkHuangThresholdImageFilterIUC3ISS3_cast: Any

def itkHuangThresholdImageFilterIUC3IUC3_New(): ...

class itkHuangThresholdImageFilterIUC3IUC3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkHuangThresholdImageFilterIUC3IUC3___New_orig__: Any
itkHuangThresholdImageFilterIUC3IUC3_cast: Any

def huang_threshold_image_filter(*args: Any, **kwargs: Any): ...
def huang_threshold_image_filter_init_docstring() -> None: ...
