import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkIntensityWindowingImageFilterIF2IF2_Superclass_New(): ...

class itkIntensityWindowingImageFilterIF2IF2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIF2IF2_Superclass___New_orig__: Any
itkIntensityWindowingImageFilterIF2IF2_Superclass_cast: Any

def itkIntensityWindowingImageFilterIF2ISS2_Superclass_New(): ...

class itkIntensityWindowingImageFilterIF2ISS2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIF2ISS2_Superclass___New_orig__: Any
itkIntensityWindowingImageFilterIF2ISS2_Superclass_cast: Any

def itkIntensityWindowingImageFilterIF2IUC2_Superclass_New(): ...

class itkIntensityWindowingImageFilterIF2IUC2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIF2IUC2_Superclass___New_orig__: Any
itkIntensityWindowingImageFilterIF2IUC2_Superclass_cast: Any

def itkIntensityWindowingImageFilterIF3IF3_Superclass_New(): ...

class itkIntensityWindowingImageFilterIF3IF3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIF3IF3_Superclass___New_orig__: Any
itkIntensityWindowingImageFilterIF3IF3_Superclass_cast: Any

def itkIntensityWindowingImageFilterIF3ISS3_Superclass_New(): ...

class itkIntensityWindowingImageFilterIF3ISS3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIF3ISS3_Superclass___New_orig__: Any
itkIntensityWindowingImageFilterIF3ISS3_Superclass_cast: Any

def itkIntensityWindowingImageFilterIF3IUC3_Superclass_New(): ...

class itkIntensityWindowingImageFilterIF3IUC3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIF3IUC3_Superclass___New_orig__: Any
itkIntensityWindowingImageFilterIF3IUC3_Superclass_cast: Any

def itkIntensityWindowingImageFilterISS2IF2_Superclass_New(): ...

class itkIntensityWindowingImageFilterISS2IF2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterISS2IF2_Superclass___New_orig__: Any
itkIntensityWindowingImageFilterISS2IF2_Superclass_cast: Any

def itkIntensityWindowingImageFilterISS2ISS2_Superclass_New(): ...

class itkIntensityWindowingImageFilterISS2ISS2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterISS2ISS2_Superclass___New_orig__: Any
itkIntensityWindowingImageFilterISS2ISS2_Superclass_cast: Any

def itkIntensityWindowingImageFilterISS2IUC2_Superclass_New(): ...

class itkIntensityWindowingImageFilterISS2IUC2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterISS2IUC2_Superclass___New_orig__: Any
itkIntensityWindowingImageFilterISS2IUC2_Superclass_cast: Any

def itkIntensityWindowingImageFilterISS3IF3_Superclass_New(): ...

class itkIntensityWindowingImageFilterISS3IF3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterISS3IF3_Superclass___New_orig__: Any
itkIntensityWindowingImageFilterISS3IF3_Superclass_cast: Any

def itkIntensityWindowingImageFilterISS3ISS3_Superclass_New(): ...

class itkIntensityWindowingImageFilterISS3ISS3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterISS3ISS3_Superclass___New_orig__: Any
itkIntensityWindowingImageFilterISS3ISS3_Superclass_cast: Any

def itkIntensityWindowingImageFilterISS3IUC3_Superclass_New(): ...

class itkIntensityWindowingImageFilterISS3IUC3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterISS3IUC3_Superclass___New_orig__: Any
itkIntensityWindowingImageFilterISS3IUC3_Superclass_cast: Any

def itkIntensityWindowingImageFilterIUC2IF2_Superclass_New(): ...

class itkIntensityWindowingImageFilterIUC2IF2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIUC2IF2_Superclass___New_orig__: Any
itkIntensityWindowingImageFilterIUC2IF2_Superclass_cast: Any

def itkIntensityWindowingImageFilterIUC2ISS2_Superclass_New(): ...

class itkIntensityWindowingImageFilterIUC2ISS2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIUC2ISS2_Superclass___New_orig__: Any
itkIntensityWindowingImageFilterIUC2ISS2_Superclass_cast: Any

def itkIntensityWindowingImageFilterIUC2IUC2_Superclass_New(): ...

class itkIntensityWindowingImageFilterIUC2IUC2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIUC2IUC2_Superclass___New_orig__: Any
itkIntensityWindowingImageFilterIUC2IUC2_Superclass_cast: Any

def itkIntensityWindowingImageFilterIUC3IF3_Superclass_New(): ...

class itkIntensityWindowingImageFilterIUC3IF3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIUC3IF3_Superclass___New_orig__: Any
itkIntensityWindowingImageFilterIUC3IF3_Superclass_cast: Any

def itkIntensityWindowingImageFilterIUC3ISS3_Superclass_New(): ...

class itkIntensityWindowingImageFilterIUC3ISS3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIUC3ISS3_Superclass___New_orig__: Any
itkIntensityWindowingImageFilterIUC3ISS3_Superclass_cast: Any

def itkIntensityWindowingImageFilterIUC3IUC3_Superclass_New(): ...

class itkIntensityWindowingImageFilterIUC3IUC3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIUC3IUC3_Superclass___New_orig__: Any
itkIntensityWindowingImageFilterIUC3IUC3_Superclass_cast: Any

def itkIntensityWindowingImageFilterIF2IF2_New(): ...

class itkIntensityWindowingImageFilterIF2IF2(itkIntensityWindowingImageFilterIF2IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    SetWindowMinimum: Any = ...
    SetWindowMaximum: Any = ...
    GetWindowMinimum: Any = ...
    GetWindowMaximum: Any = ...
    SetWindowLevel: Any = ...
    GetWindow: Any = ...
    GetLevel: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIF2IF2___New_orig__: Any
itkIntensityWindowingImageFilterIF2IF2_cast: Any

def itkIntensityWindowingImageFilterIF2ISS2_New(): ...

class itkIntensityWindowingImageFilterIF2ISS2(itkIntensityWindowingImageFilterIF2ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    SetWindowMinimum: Any = ...
    SetWindowMaximum: Any = ...
    GetWindowMinimum: Any = ...
    GetWindowMaximum: Any = ...
    SetWindowLevel: Any = ...
    GetWindow: Any = ...
    GetLevel: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIF2ISS2___New_orig__: Any
itkIntensityWindowingImageFilterIF2ISS2_cast: Any

def itkIntensityWindowingImageFilterIF2IUC2_New(): ...

class itkIntensityWindowingImageFilterIF2IUC2(itkIntensityWindowingImageFilterIF2IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    SetWindowMinimum: Any = ...
    SetWindowMaximum: Any = ...
    GetWindowMinimum: Any = ...
    GetWindowMaximum: Any = ...
    SetWindowLevel: Any = ...
    GetWindow: Any = ...
    GetLevel: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIF2IUC2___New_orig__: Any
itkIntensityWindowingImageFilterIF2IUC2_cast: Any

def itkIntensityWindowingImageFilterIF3IF3_New(): ...

class itkIntensityWindowingImageFilterIF3IF3(itkIntensityWindowingImageFilterIF3IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    SetWindowMinimum: Any = ...
    SetWindowMaximum: Any = ...
    GetWindowMinimum: Any = ...
    GetWindowMaximum: Any = ...
    SetWindowLevel: Any = ...
    GetWindow: Any = ...
    GetLevel: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIF3IF3___New_orig__: Any
itkIntensityWindowingImageFilterIF3IF3_cast: Any

def itkIntensityWindowingImageFilterIF3ISS3_New(): ...

class itkIntensityWindowingImageFilterIF3ISS3(itkIntensityWindowingImageFilterIF3ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    SetWindowMinimum: Any = ...
    SetWindowMaximum: Any = ...
    GetWindowMinimum: Any = ...
    GetWindowMaximum: Any = ...
    SetWindowLevel: Any = ...
    GetWindow: Any = ...
    GetLevel: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIF3ISS3___New_orig__: Any
itkIntensityWindowingImageFilterIF3ISS3_cast: Any

def itkIntensityWindowingImageFilterIF3IUC3_New(): ...

class itkIntensityWindowingImageFilterIF3IUC3(itkIntensityWindowingImageFilterIF3IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    SetWindowMinimum: Any = ...
    SetWindowMaximum: Any = ...
    GetWindowMinimum: Any = ...
    GetWindowMaximum: Any = ...
    SetWindowLevel: Any = ...
    GetWindow: Any = ...
    GetLevel: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIF3IUC3___New_orig__: Any
itkIntensityWindowingImageFilterIF3IUC3_cast: Any

def itkIntensityWindowingImageFilterISS2IF2_New(): ...

class itkIntensityWindowingImageFilterISS2IF2(itkIntensityWindowingImageFilterISS2IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    SetWindowMinimum: Any = ...
    SetWindowMaximum: Any = ...
    GetWindowMinimum: Any = ...
    GetWindowMaximum: Any = ...
    SetWindowLevel: Any = ...
    GetWindow: Any = ...
    GetLevel: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterISS2IF2___New_orig__: Any
itkIntensityWindowingImageFilterISS2IF2_cast: Any

def itkIntensityWindowingImageFilterISS2ISS2_New(): ...

class itkIntensityWindowingImageFilterISS2ISS2(itkIntensityWindowingImageFilterISS2ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    SetWindowMinimum: Any = ...
    SetWindowMaximum: Any = ...
    GetWindowMinimum: Any = ...
    GetWindowMaximum: Any = ...
    SetWindowLevel: Any = ...
    GetWindow: Any = ...
    GetLevel: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterISS2ISS2___New_orig__: Any
itkIntensityWindowingImageFilterISS2ISS2_cast: Any

def itkIntensityWindowingImageFilterISS2IUC2_New(): ...

class itkIntensityWindowingImageFilterISS2IUC2(itkIntensityWindowingImageFilterISS2IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    SetWindowMinimum: Any = ...
    SetWindowMaximum: Any = ...
    GetWindowMinimum: Any = ...
    GetWindowMaximum: Any = ...
    SetWindowLevel: Any = ...
    GetWindow: Any = ...
    GetLevel: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterISS2IUC2___New_orig__: Any
itkIntensityWindowingImageFilterISS2IUC2_cast: Any

def itkIntensityWindowingImageFilterISS3IF3_New(): ...

class itkIntensityWindowingImageFilterISS3IF3(itkIntensityWindowingImageFilterISS3IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    SetWindowMinimum: Any = ...
    SetWindowMaximum: Any = ...
    GetWindowMinimum: Any = ...
    GetWindowMaximum: Any = ...
    SetWindowLevel: Any = ...
    GetWindow: Any = ...
    GetLevel: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterISS3IF3___New_orig__: Any
itkIntensityWindowingImageFilterISS3IF3_cast: Any

def itkIntensityWindowingImageFilterISS3ISS3_New(): ...

class itkIntensityWindowingImageFilterISS3ISS3(itkIntensityWindowingImageFilterISS3ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    SetWindowMinimum: Any = ...
    SetWindowMaximum: Any = ...
    GetWindowMinimum: Any = ...
    GetWindowMaximum: Any = ...
    SetWindowLevel: Any = ...
    GetWindow: Any = ...
    GetLevel: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterISS3ISS3___New_orig__: Any
itkIntensityWindowingImageFilterISS3ISS3_cast: Any

def itkIntensityWindowingImageFilterISS3IUC3_New(): ...

class itkIntensityWindowingImageFilterISS3IUC3(itkIntensityWindowingImageFilterISS3IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    SetWindowMinimum: Any = ...
    SetWindowMaximum: Any = ...
    GetWindowMinimum: Any = ...
    GetWindowMaximum: Any = ...
    SetWindowLevel: Any = ...
    GetWindow: Any = ...
    GetLevel: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterISS3IUC3___New_orig__: Any
itkIntensityWindowingImageFilterISS3IUC3_cast: Any

def itkIntensityWindowingImageFilterIUC2IF2_New(): ...

class itkIntensityWindowingImageFilterIUC2IF2(itkIntensityWindowingImageFilterIUC2IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    SetWindowMinimum: Any = ...
    SetWindowMaximum: Any = ...
    GetWindowMinimum: Any = ...
    GetWindowMaximum: Any = ...
    SetWindowLevel: Any = ...
    GetWindow: Any = ...
    GetLevel: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIUC2IF2___New_orig__: Any
itkIntensityWindowingImageFilterIUC2IF2_cast: Any

def itkIntensityWindowingImageFilterIUC2ISS2_New(): ...

class itkIntensityWindowingImageFilterIUC2ISS2(itkIntensityWindowingImageFilterIUC2ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    SetWindowMinimum: Any = ...
    SetWindowMaximum: Any = ...
    GetWindowMinimum: Any = ...
    GetWindowMaximum: Any = ...
    SetWindowLevel: Any = ...
    GetWindow: Any = ...
    GetLevel: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIUC2ISS2___New_orig__: Any
itkIntensityWindowingImageFilterIUC2ISS2_cast: Any

def itkIntensityWindowingImageFilterIUC2IUC2_New(): ...

class itkIntensityWindowingImageFilterIUC2IUC2(itkIntensityWindowingImageFilterIUC2IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    SetWindowMinimum: Any = ...
    SetWindowMaximum: Any = ...
    GetWindowMinimum: Any = ...
    GetWindowMaximum: Any = ...
    SetWindowLevel: Any = ...
    GetWindow: Any = ...
    GetLevel: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIUC2IUC2___New_orig__: Any
itkIntensityWindowingImageFilterIUC2IUC2_cast: Any

def itkIntensityWindowingImageFilterIUC3IF3_New(): ...

class itkIntensityWindowingImageFilterIUC3IF3(itkIntensityWindowingImageFilterIUC3IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    SetWindowMinimum: Any = ...
    SetWindowMaximum: Any = ...
    GetWindowMinimum: Any = ...
    GetWindowMaximum: Any = ...
    SetWindowLevel: Any = ...
    GetWindow: Any = ...
    GetLevel: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIUC3IF3___New_orig__: Any
itkIntensityWindowingImageFilterIUC3IF3_cast: Any

def itkIntensityWindowingImageFilterIUC3ISS3_New(): ...

class itkIntensityWindowingImageFilterIUC3ISS3(itkIntensityWindowingImageFilterIUC3ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    SetWindowMinimum: Any = ...
    SetWindowMaximum: Any = ...
    GetWindowMinimum: Any = ...
    GetWindowMaximum: Any = ...
    SetWindowLevel: Any = ...
    GetWindow: Any = ...
    GetLevel: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIUC3ISS3___New_orig__: Any
itkIntensityWindowingImageFilterIUC3ISS3_cast: Any

def itkIntensityWindowingImageFilterIUC3IUC3_New(): ...

class itkIntensityWindowingImageFilterIUC3IUC3(itkIntensityWindowingImageFilterIUC3IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    SetWindowMinimum: Any = ...
    SetWindowMaximum: Any = ...
    GetWindowMinimum: Any = ...
    GetWindowMaximum: Any = ...
    SetWindowLevel: Any = ...
    GetWindow: Any = ...
    GetLevel: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIntensityWindowingImageFilterIUC3IUC3___New_orig__: Any
itkIntensityWindowingImageFilterIUC3IUC3_cast: Any

def intensity_windowing_image_filter(*args: Any, **kwargs: Any): ...
def intensity_windowing_image_filter_init_docstring() -> None: ...
def unary_functor_image_filter(*args: Any, **kwargs: Any): ...
def unary_functor_image_filter_init_docstring() -> None: ...
