import itk.stdcomplexPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkIPLCommonImageIO_New(): ...

class itkIPLCommonImageIO(itk.ITKIOImageBaseBasePython.itkImageIOBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ModifyImageInformation: Any = ...
    SortImageListByNameAscend: Any = ...
    SortImageListByNameDescend: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIPLCommonImageIO___New_orig__: Any
itkIPLCommonImageIO_cast: Any
