import itk.stdcomplexPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkArchetypeSeriesFileNames_New(): ...

class itkArchetypeSeriesFileNames(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetArchetype: Any = ...
    GetArchetype: Any = ...
    GetNumberOfGroupings: Any = ...
    GetFileNames: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkArchetypeSeriesFileNames___New_orig__: Any
itkArchetypeSeriesFileNames_cast: Any

class itkImageIOBase(itk.ITKCommonBasePython.itkLightProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetNumberOfDimensions: Any = ...
    GetNumberOfDimensions: Any = ...
    SetDimensions: Any = ...
    GetDimensions: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    GetDefaultDirection: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetPixelType: Any = ...
    GetPixelType: Any = ...
    SetComponentType: Any = ...
    GetComponentType: Any = ...
    GetComponentTypeInfo: Any = ...
    SetNumberOfComponents: Any = ...
    GetNumberOfComponents: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetCompressor: Any = ...
    GetCompressor: Any = ...
    SetUseStreamedReading: Any = ...
    GetUseStreamedReading: Any = ...
    UseStreamedReadingOn: Any = ...
    UseStreamedReadingOff: Any = ...
    SetUseStreamedWriting: Any = ...
    GetUseStreamedWriting: Any = ...
    UseStreamedWritingOn: Any = ...
    UseStreamedWritingOff: Any = ...
    SetExpandRGBPalette: Any = ...
    GetExpandRGBPalette: Any = ...
    ExpandRGBPaletteOn: Any = ...
    ExpandRGBPaletteOff: Any = ...
    SetWritePalette: Any = ...
    GetWritePalette: Any = ...
    WritePaletteOn: Any = ...
    WritePaletteOff: Any = ...
    GetIsReadAsScalarPlusPalette: Any = ...
    GetComponentTypeAsString: Any = ...
    GetComponentTypeFromString: Any = ...
    GetPixelTypeAsString: Any = ...
    GetPixelTypeFromString: Any = ...
    SetFileType: Any = ...
    GetFileType: Any = ...
    SetFileTypeToASCII: Any = ...
    SetFileTypeToBinary: Any = ...
    SetByteOrder: Any = ...
    GetByteOrder: Any = ...
    SetByteOrderToBigEndian: Any = ...
    SetByteOrderToLittleEndian: Any = ...
    GetFileTypeAsString: Any = ...
    GetByteOrderAsString: Any = ...
    GetPixelStride: Any = ...
    GetImageSizeInPixels: Any = ...
    GetImageSizeInBytes: Any = ...
    GetImageSizeInComponents: Any = ...
    GetComponentSize: Any = ...
    CanReadFile: Any = ...
    CanStreamRead: Any = ...
    ReadImageInformation: Any = ...
    Read: Any = ...
    CanWriteFile: Any = ...
    CanStreamWrite: Any = ...
    WriteImageInformation: Any = ...
    Write: Any = ...
    SupportsDimension: Any = ...
    GenerateStreamableReadRegionFromRequestedRegion: Any = ...
    GetActualNumberOfSplitsForWriting: Any = ...
    GetSplitRegionForWriting: Any = ...
    GetSupportedReadExtensions: Any = ...
    GetSupportedWriteExtensions: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageIOBase_GetComponentTypeAsString: Any
itkImageIOBase_GetComponentTypeFromString: Any
itkImageIOBase_GetPixelTypeAsString: Any
itkImageIOBase_GetPixelTypeFromString: Any
itkImageIOBase_cast: Any

class itkImageIOFactory(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CreateImageIO: Any = ...

itkImageIOFactory_CreateImageIO: Any

def itkNumericSeriesFileNames_New(): ...

class itkNumericSeriesFileNames(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetEndIndex: Any = ...
    GetEndIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    GetFileNames: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNumericSeriesFileNames___New_orig__: Any
itkNumericSeriesFileNames_cast: Any

def itkRegularExpressionSeriesFileNames_New(): ...

class itkRegularExpressionSeriesFileNames(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDirectory: Any = ...
    GetDirectory: Any = ...
    SetRegularExpression: Any = ...
    GetRegularExpression: Any = ...
    SetSubMatch: Any = ...
    GetSubMatch: Any = ...
    SetNumericSort: Any = ...
    GetNumericSort: Any = ...
    NumericSortOn: Any = ...
    NumericSortOff: Any = ...
    GetFileNames: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRegularExpressionSeriesFileNames___New_orig__: Any
itkRegularExpressionSeriesFileNames_cast: Any

class itkStreamingImageIOBase(itkImageIOBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkStreamingImageIOBase_cast: Any
