import itk.itkVectorContainerPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkImageToPathFilterIF2PLPP2(itk.itkPathSourcePython.itkPathSourcePLPP2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToPathFilterIF2PLPP2_cast: Any

class itkImageToPathFilterIF3PLPP3(itk.itkPathSourcePython.itkPathSourcePLPP3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToPathFilterIF3PLPP3_cast: Any

class itkImageToPathFilterISS2PLPP2(itk.itkPathSourcePython.itkPathSourcePLPP2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToPathFilterISS2PLPP2_cast: Any

class itkImageToPathFilterISS3PLPP3(itk.itkPathSourcePython.itkPathSourcePLPP3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToPathFilterISS3PLPP3_cast: Any

class itkImageToPathFilterIUC2PLPP2(itk.itkPathSourcePython.itkPathSourcePLPP2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToPathFilterIUC2PLPP2_cast: Any

class itkImageToPathFilterIUC3PLPP3(itk.itkPathSourcePython.itkPathSourcePLPP3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToPathFilterIUC3PLPP3_cast: Any

def image_to_path_filter(*args: Any, **kwargs: Any): ...
def image_to_path_filter_init_docstring() -> None: ...
