import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkIsolatedConnectedImageFilterIF2IF2_New(): ...

class itkIsolatedConnectedImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    AddSeed1: Any = ...
    SetSeed1: Any = ...
    ClearSeeds1: Any = ...
    AddSeed2: Any = ...
    SetSeed2: Any = ...
    ClearSeeds2: Any = ...
    GetSeeds1: Any = ...
    GetSeeds2: Any = ...
    SetLower: Any = ...
    GetLower: Any = ...
    SetUpper: Any = ...
    GetUpper: Any = ...
    SetIsolatedValueTolerance: Any = ...
    GetIsolatedValueTolerance: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    GetIsolatedValue: Any = ...
    SetFindUpperThreshold: Any = ...
    FindUpperThresholdOn: Any = ...
    FindUpperThresholdOff: Any = ...
    GetFindUpperThreshold: Any = ...
    GetThresholdingFailed: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsolatedConnectedImageFilterIF2IF2___New_orig__: Any
itkIsolatedConnectedImageFilterIF2IF2_cast: Any

def itkIsolatedConnectedImageFilterIF3IF3_New(): ...

class itkIsolatedConnectedImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    AddSeed1: Any = ...
    SetSeed1: Any = ...
    ClearSeeds1: Any = ...
    AddSeed2: Any = ...
    SetSeed2: Any = ...
    ClearSeeds2: Any = ...
    GetSeeds1: Any = ...
    GetSeeds2: Any = ...
    SetLower: Any = ...
    GetLower: Any = ...
    SetUpper: Any = ...
    GetUpper: Any = ...
    SetIsolatedValueTolerance: Any = ...
    GetIsolatedValueTolerance: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    GetIsolatedValue: Any = ...
    SetFindUpperThreshold: Any = ...
    FindUpperThresholdOn: Any = ...
    FindUpperThresholdOff: Any = ...
    GetFindUpperThreshold: Any = ...
    GetThresholdingFailed: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsolatedConnectedImageFilterIF3IF3___New_orig__: Any
itkIsolatedConnectedImageFilterIF3IF3_cast: Any

def itkIsolatedConnectedImageFilterISS2ISS2_New(): ...

class itkIsolatedConnectedImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    AddSeed1: Any = ...
    SetSeed1: Any = ...
    ClearSeeds1: Any = ...
    AddSeed2: Any = ...
    SetSeed2: Any = ...
    ClearSeeds2: Any = ...
    GetSeeds1: Any = ...
    GetSeeds2: Any = ...
    SetLower: Any = ...
    GetLower: Any = ...
    SetUpper: Any = ...
    GetUpper: Any = ...
    SetIsolatedValueTolerance: Any = ...
    GetIsolatedValueTolerance: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    GetIsolatedValue: Any = ...
    SetFindUpperThreshold: Any = ...
    FindUpperThresholdOn: Any = ...
    FindUpperThresholdOff: Any = ...
    GetFindUpperThreshold: Any = ...
    GetThresholdingFailed: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsolatedConnectedImageFilterISS2ISS2___New_orig__: Any
itkIsolatedConnectedImageFilterISS2ISS2_cast: Any

def itkIsolatedConnectedImageFilterISS3ISS3_New(): ...

class itkIsolatedConnectedImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    AddSeed1: Any = ...
    SetSeed1: Any = ...
    ClearSeeds1: Any = ...
    AddSeed2: Any = ...
    SetSeed2: Any = ...
    ClearSeeds2: Any = ...
    GetSeeds1: Any = ...
    GetSeeds2: Any = ...
    SetLower: Any = ...
    GetLower: Any = ...
    SetUpper: Any = ...
    GetUpper: Any = ...
    SetIsolatedValueTolerance: Any = ...
    GetIsolatedValueTolerance: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    GetIsolatedValue: Any = ...
    SetFindUpperThreshold: Any = ...
    FindUpperThresholdOn: Any = ...
    FindUpperThresholdOff: Any = ...
    GetFindUpperThreshold: Any = ...
    GetThresholdingFailed: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsolatedConnectedImageFilterISS3ISS3___New_orig__: Any
itkIsolatedConnectedImageFilterISS3ISS3_cast: Any

def itkIsolatedConnectedImageFilterIUC2IUC2_New(): ...

class itkIsolatedConnectedImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    AddSeed1: Any = ...
    SetSeed1: Any = ...
    ClearSeeds1: Any = ...
    AddSeed2: Any = ...
    SetSeed2: Any = ...
    ClearSeeds2: Any = ...
    GetSeeds1: Any = ...
    GetSeeds2: Any = ...
    SetLower: Any = ...
    GetLower: Any = ...
    SetUpper: Any = ...
    GetUpper: Any = ...
    SetIsolatedValueTolerance: Any = ...
    GetIsolatedValueTolerance: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    GetIsolatedValue: Any = ...
    SetFindUpperThreshold: Any = ...
    FindUpperThresholdOn: Any = ...
    FindUpperThresholdOff: Any = ...
    GetFindUpperThreshold: Any = ...
    GetThresholdingFailed: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsolatedConnectedImageFilterIUC2IUC2___New_orig__: Any
itkIsolatedConnectedImageFilterIUC2IUC2_cast: Any

def itkIsolatedConnectedImageFilterIUC3IUC3_New(): ...

class itkIsolatedConnectedImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    AddSeed1: Any = ...
    SetSeed1: Any = ...
    ClearSeeds1: Any = ...
    AddSeed2: Any = ...
    SetSeed2: Any = ...
    ClearSeeds2: Any = ...
    GetSeeds1: Any = ...
    GetSeeds2: Any = ...
    SetLower: Any = ...
    GetLower: Any = ...
    SetUpper: Any = ...
    GetUpper: Any = ...
    SetIsolatedValueTolerance: Any = ...
    GetIsolatedValueTolerance: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    GetIsolatedValue: Any = ...
    SetFindUpperThreshold: Any = ...
    FindUpperThresholdOn: Any = ...
    FindUpperThresholdOff: Any = ...
    GetFindUpperThreshold: Any = ...
    GetThresholdingFailed: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsolatedConnectedImageFilterIUC3IUC3___New_orig__: Any
itkIsolatedConnectedImageFilterIUC3IUC3_cast: Any

def isolated_connected_image_filter(*args: Any, **kwargs: Any): ...
def isolated_connected_image_filter_init_docstring() -> None: ...
