import itk.itkVectorContainerPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class listitkImageMaskSpatialObject2_Pointer:
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

class listitkImageMaskSpatialObject3_Pointer:
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

def itkImageMaskSpatialObject2_New(): ...

class itkImageMaskSpatialObject2(itk.itkImageSpatialObjectPython.itkImageSpatialObject2UC):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ComputeMyBoundingBoxInIndexSpace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageMaskSpatialObject2___New_orig__: Any
itkImageMaskSpatialObject2_cast: Any

def itkImageMaskSpatialObject3_New(): ...

class itkImageMaskSpatialObject3(itk.itkImageSpatialObjectPython.itkImageSpatialObject3UC):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ComputeMyBoundingBoxInIndexSpace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageMaskSpatialObject3___New_orig__: Any
itkImageMaskSpatialObject3_cast: Any
