import itk.itkArrayPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkInterpolateImageFunctionICVF22D(itk.itkImageFunctionBasePython.itkImageFunctionICVF22CVD2D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetRadius: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInterpolateImageFunctionICVF22D_cast: Any

class itkInterpolateImageFunctionICVF33D(itk.itkImageFunctionBasePython.itkImageFunctionICVF33CVD3D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetRadius: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInterpolateImageFunctionICVF33D_cast: Any

class itkInterpolateImageFunctionIF2D(itk.itkImageFunctionBasePython.itkImageFunctionIF2DD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetRadius: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInterpolateImageFunctionIF2D_cast: Any

class itkInterpolateImageFunctionIF2F(itk.itkImageFunctionBasePython.itkImageFunctionIF2DF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetRadius: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInterpolateImageFunctionIF2F_cast: Any

class itkInterpolateImageFunctionIF3D(itk.itkImageFunctionBasePython.itkImageFunctionIF3DD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetRadius: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInterpolateImageFunctionIF3D_cast: Any

class itkInterpolateImageFunctionIF3F(itk.itkImageFunctionBasePython.itkImageFunctionIF3DF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetRadius: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInterpolateImageFunctionIF3F_cast: Any

class itkInterpolateImageFunctionIRGBAUC2D(itk.itkImageFunctionBasePython.itkImageFunctionIRGBAUC2RGBADD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetRadius: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInterpolateImageFunctionIRGBAUC2D_cast: Any

class itkInterpolateImageFunctionIRGBAUC3D(itk.itkImageFunctionBasePython.itkImageFunctionIRGBAUC3RGBADD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetRadius: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInterpolateImageFunctionIRGBAUC3D_cast: Any

class itkInterpolateImageFunctionIRGBUC2D(itk.itkImageFunctionBasePython.itkImageFunctionIRGBUC2RGBDD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetRadius: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInterpolateImageFunctionIRGBUC2D_cast: Any

class itkInterpolateImageFunctionIRGBUC3D(itk.itkImageFunctionBasePython.itkImageFunctionIRGBUC3RGBDD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetRadius: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInterpolateImageFunctionIRGBUC3D_cast: Any

class itkInterpolateImageFunctionISS2D(itk.itkImageFunctionBasePython.itkImageFunctionISS2DD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetRadius: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInterpolateImageFunctionISS2D_cast: Any

class itkInterpolateImageFunctionISS2F(itk.itkImageFunctionBasePython.itkImageFunctionISS2DF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetRadius: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInterpolateImageFunctionISS2F_cast: Any

class itkInterpolateImageFunctionISS3D(itk.itkImageFunctionBasePython.itkImageFunctionISS3DD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetRadius: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInterpolateImageFunctionISS3D_cast: Any

class itkInterpolateImageFunctionISS3F(itk.itkImageFunctionBasePython.itkImageFunctionISS3DF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetRadius: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInterpolateImageFunctionISS3F_cast: Any

class itkInterpolateImageFunctionIUC2D(itk.itkImageFunctionBasePython.itkImageFunctionIUC2DD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetRadius: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInterpolateImageFunctionIUC2D_cast: Any

class itkInterpolateImageFunctionIUC2F(itk.itkImageFunctionBasePython.itkImageFunctionIUC2DF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetRadius: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInterpolateImageFunctionIUC2F_cast: Any

class itkInterpolateImageFunctionIUC3D(itk.itkImageFunctionBasePython.itkImageFunctionIUC3DD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetRadius: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInterpolateImageFunctionIUC3D_cast: Any

class itkInterpolateImageFunctionIUC3F(itk.itkImageFunctionBasePython.itkImageFunctionIUC3DF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetRadius: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInterpolateImageFunctionIUC3F_cast: Any

class itkInterpolateImageFunctionIVF22D(itk.itkImageFunctionBasePython.itkImageFunctionIVF22DD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetRadius: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInterpolateImageFunctionIVF22D_cast: Any

class itkInterpolateImageFunctionIVF33D(itk.itkImageFunctionBasePython.itkImageFunctionIVF33DD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetRadius: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInterpolateImageFunctionIVF33D_cast: Any
