import itk.itkPointSetPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkImageToMeshFilterIF2MD2(itk.itkMeshSourcePython.itkMeshSourceMD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIF2MD2_cast: Any

class itkImageToMeshFilterIF2MF2(itk.itkMeshSourcePython.itkMeshSourceMF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIF2MF2_cast: Any

class itkImageToMeshFilterIF2MSS2(itk.itkMeshSourcePython.itkMeshSourceMSS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIF2MSS2_cast: Any

class itkImageToMeshFilterIF2MUC2(itk.itkMeshSourcePython.itkMeshSourceMUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIF2MUC2_cast: Any

class itkImageToMeshFilterIF2PSD2(itk.itkMeshSourcePython.itkMeshSourcePSD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIF2PSD2_cast: Any

class itkImageToMeshFilterIF2PSF2(itk.itkMeshSourcePython.itkMeshSourcePSF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIF2PSF2_cast: Any

class itkImageToMeshFilterIF2PSSS2(itk.itkMeshSourcePython.itkMeshSourcePSSS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIF2PSSS2_cast: Any

class itkImageToMeshFilterIF2PSUC2(itk.itkMeshSourcePython.itkMeshSourcePSUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIF2PSUC2_cast: Any

class itkImageToMeshFilterIF3MD3(itk.itkMeshSourcePython.itkMeshSourceMD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIF3MD3_cast: Any

class itkImageToMeshFilterIF3MF3(itk.itkMeshSourcePython.itkMeshSourceMF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIF3MF3_cast: Any

class itkImageToMeshFilterIF3MSS3(itk.itkMeshSourcePython.itkMeshSourceMSS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIF3MSS3_cast: Any

class itkImageToMeshFilterIF3MUC3(itk.itkMeshSourcePython.itkMeshSourceMUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIF3MUC3_cast: Any

class itkImageToMeshFilterIF3PSD3(itk.itkMeshSourcePython.itkMeshSourcePSD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIF3PSD3_cast: Any

class itkImageToMeshFilterIF3PSF3(itk.itkMeshSourcePython.itkMeshSourcePSF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIF3PSF3_cast: Any

class itkImageToMeshFilterIF3PSSS3(itk.itkMeshSourcePython.itkMeshSourcePSSS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIF3PSSS3_cast: Any

class itkImageToMeshFilterIF3PSUC3(itk.itkMeshSourcePython.itkMeshSourcePSUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIF3PSUC3_cast: Any

class itkImageToMeshFilterISS2MD2(itk.itkMeshSourcePython.itkMeshSourceMD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterISS2MD2_cast: Any

class itkImageToMeshFilterISS2MF2(itk.itkMeshSourcePython.itkMeshSourceMF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterISS2MF2_cast: Any

class itkImageToMeshFilterISS2MSS2(itk.itkMeshSourcePython.itkMeshSourceMSS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterISS2MSS2_cast: Any

class itkImageToMeshFilterISS2MUC2(itk.itkMeshSourcePython.itkMeshSourceMUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterISS2MUC2_cast: Any

class itkImageToMeshFilterISS2PSD2(itk.itkMeshSourcePython.itkMeshSourcePSD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterISS2PSD2_cast: Any

class itkImageToMeshFilterISS2PSF2(itk.itkMeshSourcePython.itkMeshSourcePSF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterISS2PSF2_cast: Any

class itkImageToMeshFilterISS2PSSS2(itk.itkMeshSourcePython.itkMeshSourcePSSS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterISS2PSSS2_cast: Any

class itkImageToMeshFilterISS2PSUC2(itk.itkMeshSourcePython.itkMeshSourcePSUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterISS2PSUC2_cast: Any

class itkImageToMeshFilterISS3MD3(itk.itkMeshSourcePython.itkMeshSourceMD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterISS3MD3_cast: Any

class itkImageToMeshFilterISS3MF3(itk.itkMeshSourcePython.itkMeshSourceMF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterISS3MF3_cast: Any

class itkImageToMeshFilterISS3MSS3(itk.itkMeshSourcePython.itkMeshSourceMSS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterISS3MSS3_cast: Any

class itkImageToMeshFilterISS3MUC3(itk.itkMeshSourcePython.itkMeshSourceMUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterISS3MUC3_cast: Any

class itkImageToMeshFilterISS3PSD3(itk.itkMeshSourcePython.itkMeshSourcePSD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterISS3PSD3_cast: Any

class itkImageToMeshFilterISS3PSF3(itk.itkMeshSourcePython.itkMeshSourcePSF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterISS3PSF3_cast: Any

class itkImageToMeshFilterISS3PSSS3(itk.itkMeshSourcePython.itkMeshSourcePSSS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterISS3PSSS3_cast: Any

class itkImageToMeshFilterISS3PSUC3(itk.itkMeshSourcePython.itkMeshSourcePSUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterISS3PSUC3_cast: Any

class itkImageToMeshFilterIUC2MD2(itk.itkMeshSourcePython.itkMeshSourceMD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIUC2MD2_cast: Any

class itkImageToMeshFilterIUC2MF2(itk.itkMeshSourcePython.itkMeshSourceMF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIUC2MF2_cast: Any

class itkImageToMeshFilterIUC2MSS2(itk.itkMeshSourcePython.itkMeshSourceMSS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIUC2MSS2_cast: Any

class itkImageToMeshFilterIUC2MUC2(itk.itkMeshSourcePython.itkMeshSourceMUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIUC2MUC2_cast: Any

class itkImageToMeshFilterIUC2PSD2(itk.itkMeshSourcePython.itkMeshSourcePSD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIUC2PSD2_cast: Any

class itkImageToMeshFilterIUC2PSF2(itk.itkMeshSourcePython.itkMeshSourcePSF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIUC2PSF2_cast: Any

class itkImageToMeshFilterIUC2PSSS2(itk.itkMeshSourcePython.itkMeshSourcePSSS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIUC2PSSS2_cast: Any

class itkImageToMeshFilterIUC2PSUC2(itk.itkMeshSourcePython.itkMeshSourcePSUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIUC2PSUC2_cast: Any

class itkImageToMeshFilterIUC3MD3(itk.itkMeshSourcePython.itkMeshSourceMD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIUC3MD3_cast: Any

class itkImageToMeshFilterIUC3MF3(itk.itkMeshSourcePython.itkMeshSourceMF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIUC3MF3_cast: Any

class itkImageToMeshFilterIUC3MSS3(itk.itkMeshSourcePython.itkMeshSourceMSS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIUC3MSS3_cast: Any

class itkImageToMeshFilterIUC3MUC3(itk.itkMeshSourcePython.itkMeshSourceMUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIUC3MUC3_cast: Any

class itkImageToMeshFilterIUC3PSD3(itk.itkMeshSourcePython.itkMeshSourcePSD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIUC3PSD3_cast: Any

class itkImageToMeshFilterIUC3PSF3(itk.itkMeshSourcePython.itkMeshSourcePSF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIUC3PSF3_cast: Any

class itkImageToMeshFilterIUC3PSSS3(itk.itkMeshSourcePython.itkMeshSourcePSSS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIUC3PSSS3_cast: Any

class itkImageToMeshFilterIUC3PSUC3(itk.itkMeshSourcePython.itkMeshSourcePSUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIUC3PSUC3_cast: Any

def image_to_mesh_filter(*args: Any, **kwargs: Any): ...
def image_to_mesh_filter_init_docstring() -> None: ...
