import itk.itkImageSourceCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkImageSeriesReaderICF2_New(): ...

class itkImageSeriesReaderICF2(itk.itkImageSourcePython.itkImageSourceICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderICF2___New_orig__: Any
itkImageSeriesReaderICF2_cast: Any

def itkImageSeriesReaderICF3_New(): ...

class itkImageSeriesReaderICF3(itk.itkImageSourcePython.itkImageSourceICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderICF3___New_orig__: Any
itkImageSeriesReaderICF3_cast: Any

def itkImageSeriesReaderICVF22_New(): ...

class itkImageSeriesReaderICVF22(itk.itkImageSourcePython.itkImageSourceICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderICVF22___New_orig__: Any
itkImageSeriesReaderICVF22_cast: Any

def itkImageSeriesReaderICVF23_New(): ...

class itkImageSeriesReaderICVF23(itk.itkImageSourcePython.itkImageSourceICVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderICVF23___New_orig__: Any
itkImageSeriesReaderICVF23_cast: Any

def itkImageSeriesReaderICVF32_New(): ...

class itkImageSeriesReaderICVF32(itk.itkImageSourcePython.itkImageSourceICVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderICVF32___New_orig__: Any
itkImageSeriesReaderICVF32_cast: Any

def itkImageSeriesReaderICVF33_New(): ...

class itkImageSeriesReaderICVF33(itk.itkImageSourcePython.itkImageSourceICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderICVF33___New_orig__: Any
itkImageSeriesReaderICVF33_cast: Any

def itkImageSeriesReaderICVF42_New(): ...

class itkImageSeriesReaderICVF42(itk.itkImageSourcePython.itkImageSourceICVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderICVF42___New_orig__: Any
itkImageSeriesReaderICVF42_cast: Any

def itkImageSeriesReaderICVF43_New(): ...

class itkImageSeriesReaderICVF43(itk.itkImageSourcePython.itkImageSourceICVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderICVF43___New_orig__: Any
itkImageSeriesReaderICVF43_cast: Any

def itkImageSeriesReaderIF2_New(): ...

class itkImageSeriesReaderIF2(itk.itkImageSourcePython.itkImageSourceIF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderIF2___New_orig__: Any
itkImageSeriesReaderIF2_cast: Any

def itkImageSeriesReaderIF3_New(): ...

class itkImageSeriesReaderIF3(itk.itkImageSourcePython.itkImageSourceIF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderIF3___New_orig__: Any
itkImageSeriesReaderIF3_cast: Any

def itkImageSeriesReaderIRGBAUC2_New(): ...

class itkImageSeriesReaderIRGBAUC2(itk.itkImageSourcePython.itkImageSourceIRGBAUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderIRGBAUC2___New_orig__: Any
itkImageSeriesReaderIRGBAUC2_cast: Any

def itkImageSeriesReaderIRGBAUC3_New(): ...

class itkImageSeriesReaderIRGBAUC3(itk.itkImageSourcePython.itkImageSourceIRGBAUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderIRGBAUC3___New_orig__: Any
itkImageSeriesReaderIRGBAUC3_cast: Any

def itkImageSeriesReaderIRGBUC2_New(): ...

class itkImageSeriesReaderIRGBUC2(itk.itkImageSourcePython.itkImageSourceIRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderIRGBUC2___New_orig__: Any
itkImageSeriesReaderIRGBUC2_cast: Any

def itkImageSeriesReaderIRGBUC3_New(): ...

class itkImageSeriesReaderIRGBUC3(itk.itkImageSourcePython.itkImageSourceIRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderIRGBUC3___New_orig__: Any
itkImageSeriesReaderIRGBUC3_cast: Any

def itkImageSeriesReaderISS2_New(): ...

class itkImageSeriesReaderISS2(itk.itkImageSourcePython.itkImageSourceISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderISS2___New_orig__: Any
itkImageSeriesReaderISS2_cast: Any

def itkImageSeriesReaderISS3_New(): ...

class itkImageSeriesReaderISS3(itk.itkImageSourcePython.itkImageSourceISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderISS3___New_orig__: Any
itkImageSeriesReaderISS3_cast: Any

def itkImageSeriesReaderIUC2_New(): ...

class itkImageSeriesReaderIUC2(itk.itkImageSourcePython.itkImageSourceIUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderIUC2___New_orig__: Any
itkImageSeriesReaderIUC2_cast: Any

def itkImageSeriesReaderIUC3_New(): ...

class itkImageSeriesReaderIUC3(itk.itkImageSourcePython.itkImageSourceIUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderIUC3___New_orig__: Any
itkImageSeriesReaderIUC3_cast: Any

def itkImageSeriesReaderIVF22_New(): ...

class itkImageSeriesReaderIVF22(itk.itkImageSourcePython.itkImageSourceIVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderIVF22___New_orig__: Any
itkImageSeriesReaderIVF22_cast: Any

def itkImageSeriesReaderIVF23_New(): ...

class itkImageSeriesReaderIVF23(itk.itkImageSourcePython.itkImageSourceIVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderIVF23___New_orig__: Any
itkImageSeriesReaderIVF23_cast: Any

def itkImageSeriesReaderIVF32_New(): ...

class itkImageSeriesReaderIVF32(itk.itkImageSourcePython.itkImageSourceIVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderIVF32___New_orig__: Any
itkImageSeriesReaderIVF32_cast: Any

def itkImageSeriesReaderIVF33_New(): ...

class itkImageSeriesReaderIVF33(itk.itkImageSourcePython.itkImageSourceIVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderIVF33___New_orig__: Any
itkImageSeriesReaderIVF33_cast: Any

def itkImageSeriesReaderIVF42_New(): ...

class itkImageSeriesReaderIVF42(itk.itkImageSourcePython.itkImageSourceIVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderIVF42___New_orig__: Any
itkImageSeriesReaderIVF42_cast: Any

def itkImageSeriesReaderIVF43_New(): ...

class itkImageSeriesReaderIVF43(itk.itkImageSourcePython.itkImageSourceIVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetReverseOrder: Any = ...
    GetReverseOrder: Any = ...
    ReverseOrderOn: Any = ...
    ReverseOrderOff: Any = ...
    SetForceOrthogonalDirection: Any = ...
    GetForceOrthogonalDirection: Any = ...
    ForceOrthogonalDirectionOn: Any = ...
    ForceOrthogonalDirectionOff: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    SetMetaDataDictionaryArrayUpdate: Any = ...
    GetMetaDataDictionaryArrayUpdate: Any = ...
    MetaDataDictionaryArrayUpdateOn: Any = ...
    MetaDataDictionaryArrayUpdateOff: Any = ...
    GenerateOutputInformation: Any = ...
    GetMetaDataDictionaryArray: Any = ...
    SetUseStreaming: Any = ...
    GetUseStreaming: Any = ...
    UseStreamingOn: Any = ...
    UseStreamingOff: Any = ...
    SetSpacingWarningRelThreshold: Any = ...
    GetSpacingWarningRelThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesReaderIVF43___New_orig__: Any
itkImageSeriesReaderIVF43_cast: Any

def image_series_reader(*args: Any, **kwargs: Any): ...
def image_series_reader_init_docstring() -> None: ...
