import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkIterativeDeconvolutionImageFilterIF2IF2(itk.itkFFTConvolutionImageFilterPython.itkFFTConvolutionImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    GetModifiableCurrentEstimate: Any = ...
    GetCurrentEstimate: Any = ...
    SetStopIteration: Any = ...
    GetStopIteration: Any = ...
    GetIteration: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkIterativeDeconvolutionImageFilterIF2IF2_cast: Any

class itkIterativeDeconvolutionImageFilterIF3IF3(itk.itkFFTConvolutionImageFilterPython.itkFFTConvolutionImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    GetModifiableCurrentEstimate: Any = ...
    GetCurrentEstimate: Any = ...
    SetStopIteration: Any = ...
    GetStopIteration: Any = ...
    GetIteration: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkIterativeDeconvolutionImageFilterIF3IF3_cast: Any

class itkIterativeDeconvolutionImageFilterISS2ISS2(itk.itkFFTConvolutionImageFilterPython.itkFFTConvolutionImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    GetModifiableCurrentEstimate: Any = ...
    GetCurrentEstimate: Any = ...
    SetStopIteration: Any = ...
    GetStopIteration: Any = ...
    GetIteration: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkIterativeDeconvolutionImageFilterISS2ISS2_cast: Any

class itkIterativeDeconvolutionImageFilterISS3ISS3(itk.itkFFTConvolutionImageFilterPython.itkFFTConvolutionImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    GetModifiableCurrentEstimate: Any = ...
    GetCurrentEstimate: Any = ...
    SetStopIteration: Any = ...
    GetStopIteration: Any = ...
    GetIteration: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkIterativeDeconvolutionImageFilterISS3ISS3_cast: Any

class itkIterativeDeconvolutionImageFilterIUC2IUC2(itk.itkFFTConvolutionImageFilterPython.itkFFTConvolutionImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    GetModifiableCurrentEstimate: Any = ...
    GetCurrentEstimate: Any = ...
    SetStopIteration: Any = ...
    GetStopIteration: Any = ...
    GetIteration: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkIterativeDeconvolutionImageFilterIUC2IUC2_cast: Any

class itkIterativeDeconvolutionImageFilterIUC3IUC3(itk.itkFFTConvolutionImageFilterPython.itkFFTConvolutionImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    GetModifiableCurrentEstimate: Any = ...
    GetCurrentEstimate: Any = ...
    SetStopIteration: Any = ...
    GetStopIteration: Any = ...
    GetIteration: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkIterativeDeconvolutionImageFilterIUC3IUC3_cast: Any

def iterative_deconvolution_image_filter(*args: Any, **kwargs: Any): ...
def iterative_deconvolution_image_filter_init_docstring() -> None: ...
