import itk.ITKIOImageBaseBasePython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkImageFileWriterICF2_New(): ...

class itkImageFileWriterICF2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterICF2___New_orig__: Any
itkImageFileWriterICF2_cast: Any

def itkImageFileWriterICF3_New(): ...

class itkImageFileWriterICF3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterICF3___New_orig__: Any
itkImageFileWriterICF3_cast: Any

def itkImageFileWriterICVF22_New(): ...

class itkImageFileWriterICVF22(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterICVF22___New_orig__: Any
itkImageFileWriterICVF22_cast: Any

def itkImageFileWriterICVF23_New(): ...

class itkImageFileWriterICVF23(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterICVF23___New_orig__: Any
itkImageFileWriterICVF23_cast: Any

def itkImageFileWriterICVF32_New(): ...

class itkImageFileWriterICVF32(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterICVF32___New_orig__: Any
itkImageFileWriterICVF32_cast: Any

def itkImageFileWriterICVF33_New(): ...

class itkImageFileWriterICVF33(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterICVF33___New_orig__: Any
itkImageFileWriterICVF33_cast: Any

def itkImageFileWriterICVF42_New(): ...

class itkImageFileWriterICVF42(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterICVF42___New_orig__: Any
itkImageFileWriterICVF42_cast: Any

def itkImageFileWriterICVF43_New(): ...

class itkImageFileWriterICVF43(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterICVF43___New_orig__: Any
itkImageFileWriterICVF43_cast: Any

def itkImageFileWriterIF2_New(): ...

class itkImageFileWriterIF2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterIF2___New_orig__: Any
itkImageFileWriterIF2_cast: Any

def itkImageFileWriterIF3_New(): ...

class itkImageFileWriterIF3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterIF3___New_orig__: Any
itkImageFileWriterIF3_cast: Any

def itkImageFileWriterIRGBAUC2_New(): ...

class itkImageFileWriterIRGBAUC2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterIRGBAUC2___New_orig__: Any
itkImageFileWriterIRGBAUC2_cast: Any

def itkImageFileWriterIRGBAUC3_New(): ...

class itkImageFileWriterIRGBAUC3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterIRGBAUC3___New_orig__: Any
itkImageFileWriterIRGBAUC3_cast: Any

def itkImageFileWriterIRGBUC2_New(): ...

class itkImageFileWriterIRGBUC2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterIRGBUC2___New_orig__: Any
itkImageFileWriterIRGBUC2_cast: Any

def itkImageFileWriterIRGBUC3_New(): ...

class itkImageFileWriterIRGBUC3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterIRGBUC3___New_orig__: Any
itkImageFileWriterIRGBUC3_cast: Any

def itkImageFileWriterISS2_New(): ...

class itkImageFileWriterISS2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterISS2___New_orig__: Any
itkImageFileWriterISS2_cast: Any

def itkImageFileWriterISS3_New(): ...

class itkImageFileWriterISS3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterISS3___New_orig__: Any
itkImageFileWriterISS3_cast: Any

def itkImageFileWriterIUC2_New(): ...

class itkImageFileWriterIUC2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterIUC2___New_orig__: Any
itkImageFileWriterIUC2_cast: Any

def itkImageFileWriterIUC3_New(): ...

class itkImageFileWriterIUC3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterIUC3___New_orig__: Any
itkImageFileWriterIUC3_cast: Any

def itkImageFileWriterIULL2_New(): ...

class itkImageFileWriterIULL2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterIULL2___New_orig__: Any
itkImageFileWriterIULL2_cast: Any

def itkImageFileWriterIULL3_New(): ...

class itkImageFileWriterIULL3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterIULL3___New_orig__: Any
itkImageFileWriterIULL3_cast: Any

def itkImageFileWriterIVF22_New(): ...

class itkImageFileWriterIVF22(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterIVF22___New_orig__: Any
itkImageFileWriterIVF22_cast: Any

def itkImageFileWriterIVF23_New(): ...

class itkImageFileWriterIVF23(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterIVF23___New_orig__: Any
itkImageFileWriterIVF23_cast: Any

def itkImageFileWriterIVF32_New(): ...

class itkImageFileWriterIVF32(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterIVF32___New_orig__: Any
itkImageFileWriterIVF32_cast: Any

def itkImageFileWriterIVF33_New(): ...

class itkImageFileWriterIVF33(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterIVF33___New_orig__: Any
itkImageFileWriterIVF33_cast: Any

def itkImageFileWriterIVF42_New(): ...

class itkImageFileWriterIVF42(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterIVF42___New_orig__: Any
itkImageFileWriterIVF42_cast: Any

def itkImageFileWriterIVF43_New(): ...

class itkImageFileWriterIVF43(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterIVF43___New_orig__: Any
itkImageFileWriterIVF43_cast: Any

def itkImageFileWriterVIF2_New(): ...

class itkImageFileWriterVIF2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterVIF2___New_orig__: Any
itkImageFileWriterVIF2_cast: Any

def itkImageFileWriterVIF3_New(): ...

class itkImageFileWriterVIF3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterVIF3___New_orig__: Any
itkImageFileWriterVIF3_cast: Any

def itkImageFileWriterVISS2_New(): ...

class itkImageFileWriterVISS2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterVISS2___New_orig__: Any
itkImageFileWriterVISS2_cast: Any

def itkImageFileWriterVISS3_New(): ...

class itkImageFileWriterVISS3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterVISS3___New_orig__: Any
itkImageFileWriterVISS3_cast: Any

def itkImageFileWriterVIUC2_New(): ...

class itkImageFileWriterVIUC2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterVIUC2___New_orig__: Any
itkImageFileWriterVIUC2_cast: Any

def itkImageFileWriterVIUC3_New(): ...

class itkImageFileWriterVIUC3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetIORegion: Any = ...
    GetIORegion: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    SetCompressionLevel: Any = ...
    GetCompressionLevel: Any = ...
    SetUseInputMetaDataDictionary: Any = ...
    GetUseInputMetaDataDictionary: Any = ...
    UseInputMetaDataDictionaryOn: Any = ...
    UseInputMetaDataDictionaryOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageFileWriterVIUC3___New_orig__: Any
itkImageFileWriterVIUC3_cast: Any

def image_file_writer(*args: Any, **kwargs: Any): ...
def image_file_writer_init_docstring() -> None: ...
