import itk.ITKCommonBasePython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class vectoritkImageRegion2(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectoritkImageRegion3(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class itkImageRegion2(itk.ITKCommonBasePython.itkRegion):
    thisown: Any = ...
    GetImageDimension: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __GetModifiableIndex_orig__: Any = ...
    __GetModifiableSize_orig__: Any = ...
    SetSize: Any = ...
    __GetSize_orig__: Any = ...
    SetIndex: Any = ...
    __GetIndex_orig__: Any = ...
    GetUpperIndex: Any = ...
    SetUpperIndex: Any = ...
    ComputeOffsetTable: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    IsInside: Any = ...
    GetNumberOfPixels: Any = ...
    PadByRadius: Any = ...
    ShrinkByRadius: Any = ...
    Crop: Any = ...
    Slice: Any = ...
    def GetIndex(self): ...
    def GetModifiableIndex(self): ...
    def GetSize(self): ...
    def GetModifiableSize(self): ...

itkImageRegion2_GetImageDimension: Any

class itkImageRegion3(itk.ITKCommonBasePython.itkRegion):
    thisown: Any = ...
    GetImageDimension: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __GetModifiableIndex_orig__: Any = ...
    __GetModifiableSize_orig__: Any = ...
    SetSize: Any = ...
    __GetSize_orig__: Any = ...
    SetIndex: Any = ...
    __GetIndex_orig__: Any = ...
    GetUpperIndex: Any = ...
    SetUpperIndex: Any = ...
    ComputeOffsetTable: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    IsInside: Any = ...
    GetNumberOfPixels: Any = ...
    PadByRadius: Any = ...
    ShrinkByRadius: Any = ...
    Crop: Any = ...
    Slice: Any = ...
    def GetIndex(self): ...
    def GetModifiableIndex(self): ...
    def GetSize(self): ...
    def GetModifiableSize(self): ...

itkImageRegion3_GetImageDimension: Any
