import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkInvertIntensityImageFilterIF2IF2_Superclass_New(): ...

class itkInvertIntensityImageFilterIF2IF2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkInvertIntensityImageFilterIF2IF2_Superclass___New_orig__: Any
itkInvertIntensityImageFilterIF2IF2_Superclass_cast: Any

def itkInvertIntensityImageFilterIF3IF3_Superclass_New(): ...

class itkInvertIntensityImageFilterIF3IF3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkInvertIntensityImageFilterIF3IF3_Superclass___New_orig__: Any
itkInvertIntensityImageFilterIF3IF3_Superclass_cast: Any

def itkInvertIntensityImageFilterISS2ISS2_Superclass_New(): ...

class itkInvertIntensityImageFilterISS2ISS2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkInvertIntensityImageFilterISS2ISS2_Superclass___New_orig__: Any
itkInvertIntensityImageFilterISS2ISS2_Superclass_cast: Any

def itkInvertIntensityImageFilterISS3ISS3_Superclass_New(): ...

class itkInvertIntensityImageFilterISS3ISS3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkInvertIntensityImageFilterISS3ISS3_Superclass___New_orig__: Any
itkInvertIntensityImageFilterISS3ISS3_Superclass_cast: Any

def itkInvertIntensityImageFilterIUC2IUC2_Superclass_New(): ...

class itkInvertIntensityImageFilterIUC2IUC2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkInvertIntensityImageFilterIUC2IUC2_Superclass___New_orig__: Any
itkInvertIntensityImageFilterIUC2IUC2_Superclass_cast: Any

def itkInvertIntensityImageFilterIUC3IUC3_Superclass_New(): ...

class itkInvertIntensityImageFilterIUC3IUC3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkInvertIntensityImageFilterIUC3IUC3_Superclass___New_orig__: Any
itkInvertIntensityImageFilterIUC3IUC3_Superclass_cast: Any

def itkInvertIntensityImageFilterIF2IF2_New(): ...

class itkInvertIntensityImageFilterIF2IF2(itkInvertIntensityImageFilterIF2IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaximum: Any = ...
    GetMaximum: Any = ...
    PrintSelf: Any = ...
    BeforeThreadedGenerateData: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkInvertIntensityImageFilterIF2IF2___New_orig__: Any
itkInvertIntensityImageFilterIF2IF2_cast: Any

def itkInvertIntensityImageFilterIF3IF3_New(): ...

class itkInvertIntensityImageFilterIF3IF3(itkInvertIntensityImageFilterIF3IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaximum: Any = ...
    GetMaximum: Any = ...
    PrintSelf: Any = ...
    BeforeThreadedGenerateData: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkInvertIntensityImageFilterIF3IF3___New_orig__: Any
itkInvertIntensityImageFilterIF3IF3_cast: Any

def itkInvertIntensityImageFilterISS2ISS2_New(): ...

class itkInvertIntensityImageFilterISS2ISS2(itkInvertIntensityImageFilterISS2ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaximum: Any = ...
    GetMaximum: Any = ...
    PrintSelf: Any = ...
    BeforeThreadedGenerateData: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkInvertIntensityImageFilterISS2ISS2___New_orig__: Any
itkInvertIntensityImageFilterISS2ISS2_cast: Any

def itkInvertIntensityImageFilterISS3ISS3_New(): ...

class itkInvertIntensityImageFilterISS3ISS3(itkInvertIntensityImageFilterISS3ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaximum: Any = ...
    GetMaximum: Any = ...
    PrintSelf: Any = ...
    BeforeThreadedGenerateData: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkInvertIntensityImageFilterISS3ISS3___New_orig__: Any
itkInvertIntensityImageFilterISS3ISS3_cast: Any

def itkInvertIntensityImageFilterIUC2IUC2_New(): ...

class itkInvertIntensityImageFilterIUC2IUC2(itkInvertIntensityImageFilterIUC2IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaximum: Any = ...
    GetMaximum: Any = ...
    PrintSelf: Any = ...
    BeforeThreadedGenerateData: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkInvertIntensityImageFilterIUC2IUC2___New_orig__: Any
itkInvertIntensityImageFilterIUC2IUC2_cast: Any

def itkInvertIntensityImageFilterIUC3IUC3_New(): ...

class itkInvertIntensityImageFilterIUC3IUC3(itkInvertIntensityImageFilterIUC3IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaximum: Any = ...
    GetMaximum: Any = ...
    PrintSelf: Any = ...
    BeforeThreadedGenerateData: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkInvertIntensityImageFilterIUC3IUC3___New_orig__: Any
itkInvertIntensityImageFilterIUC3IUC3_cast: Any

def invert_intensity_image_filter(*args: Any, **kwargs: Any): ...
def invert_intensity_image_filter_init_docstring() -> None: ...
def unary_functor_image_filter(*args: Any, **kwargs: Any): ...
def unary_functor_image_filter_init_docstring() -> None: ...
