import itk.itkOptimizerParameterScalesEstimatorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkImageRegistrationMethodv4Enums:
    thisown: Any = ...
    MetricSamplingStrategy_NONE: Any = ...
    MetricSamplingStrategy_REGULAR: Any = ...
    MetricSamplingStrategy_RANDOM: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...

def itkImageRegistrationMethodv4REGv4F2F2_New(): ...

class itkImageRegistrationMethodv4REGv4F2F2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedPointSet: Any = ...
    GetFixedPointSet: Any = ...
    SetMovingPointSet: Any = ...
    GetMovingPointSet: Any = ...
    SetOptimizer: Any = ...
    GetModifiableOptimizer: Any = ...
    GetOptimizer: Any = ...
    SetOptimizerWeights: Any = ...
    GetOptimizerWeights: Any = ...
    SetMetric: Any = ...
    GetModifiableMetric: Any = ...
    GetMetric: Any = ...
    SetMetricSamplingStrategy: Any = ...
    GetMetricSamplingStrategy: Any = ...
    MetricSamplingReinitializeSeed: Any = ...
    SetMetricSamplingPercentage: Any = ...
    SetMetricSamplingPercentagePerLevel: Any = ...
    GetMetricSamplingPercentagePerLevel: Any = ...
    SetFixedInitialTransformInput: Any = ...
    SetFixedInitialTransform: Any = ...
    GetFixedInitialTransformInput: Any = ...
    GetFixedInitialTransform: Any = ...
    SetMovingInitialTransformInput: Any = ...
    SetMovingInitialTransform: Any = ...
    GetMovingInitialTransformInput: Any = ...
    GetMovingInitialTransform: Any = ...
    SetInitialTransformInput: Any = ...
    SetInitialTransform: Any = ...
    GetInitialTransformInput: Any = ...
    GetInitialTransform: Any = ...
    SetTransformParametersAdaptorsPerLevel: Any = ...
    GetTransformParametersAdaptorsPerLevel: Any = ...
    SetNumberOfLevels: Any = ...
    GetNumberOfLevels: Any = ...
    SetShrinkFactorsPerLevel: Any = ...
    GetShrinkFactorsPerDimension: Any = ...
    SetShrinkFactorsPerDimension: Any = ...
    SetSmoothingSigmasPerLevel: Any = ...
    GetSmoothingSigmasPerLevel: Any = ...
    SetSmoothingSigmasAreSpecifiedInPhysicalUnits: Any = ...
    GetSmoothingSigmasAreSpecifiedInPhysicalUnits: Any = ...
    SmoothingSigmasAreSpecifiedInPhysicalUnitsOn: Any = ...
    SmoothingSigmasAreSpecifiedInPhysicalUnitsOff: Any = ...
    GetOutput: Any = ...
    GetTransformOutput: Any = ...
    GetModifiableTransform: Any = ...
    GetTransform: Any = ...
    GetCurrentLevel: Any = ...
    GetCurrentIteration: Any = ...
    GetCurrentMetricValue: Any = ...
    GetCurrentConvergenceValue: Any = ...
    GetIsConverged: Any = ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    InitializeCenterOfLinearOutputTransformOn: Any = ...
    InitializeCenterOfLinearOutputTransformOff: Any = ...
    SetInitializeCenterOfLinearOutputTransform: Any = ...
    GetInitializeCenterOfLinearOutputTransform: Any = ...
    InitializeCenterOfLinearOutputTransform: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageRegistrationMethodv4REGv4F2F2___New_orig__: Any
itkImageRegistrationMethodv4REGv4F2F2_cast: Any

def itkImageRegistrationMethodv4REGv4F3F3_New(): ...

class itkImageRegistrationMethodv4REGv4F3F3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedPointSet: Any = ...
    GetFixedPointSet: Any = ...
    SetMovingPointSet: Any = ...
    GetMovingPointSet: Any = ...
    SetOptimizer: Any = ...
    GetModifiableOptimizer: Any = ...
    GetOptimizer: Any = ...
    SetOptimizerWeights: Any = ...
    GetOptimizerWeights: Any = ...
    SetMetric: Any = ...
    GetModifiableMetric: Any = ...
    GetMetric: Any = ...
    SetMetricSamplingStrategy: Any = ...
    GetMetricSamplingStrategy: Any = ...
    MetricSamplingReinitializeSeed: Any = ...
    SetMetricSamplingPercentage: Any = ...
    SetMetricSamplingPercentagePerLevel: Any = ...
    GetMetricSamplingPercentagePerLevel: Any = ...
    SetFixedInitialTransformInput: Any = ...
    SetFixedInitialTransform: Any = ...
    GetFixedInitialTransformInput: Any = ...
    GetFixedInitialTransform: Any = ...
    SetMovingInitialTransformInput: Any = ...
    SetMovingInitialTransform: Any = ...
    GetMovingInitialTransformInput: Any = ...
    GetMovingInitialTransform: Any = ...
    SetInitialTransformInput: Any = ...
    SetInitialTransform: Any = ...
    GetInitialTransformInput: Any = ...
    GetInitialTransform: Any = ...
    SetTransformParametersAdaptorsPerLevel: Any = ...
    GetTransformParametersAdaptorsPerLevel: Any = ...
    SetNumberOfLevels: Any = ...
    GetNumberOfLevels: Any = ...
    SetShrinkFactorsPerLevel: Any = ...
    GetShrinkFactorsPerDimension: Any = ...
    SetShrinkFactorsPerDimension: Any = ...
    SetSmoothingSigmasPerLevel: Any = ...
    GetSmoothingSigmasPerLevel: Any = ...
    SetSmoothingSigmasAreSpecifiedInPhysicalUnits: Any = ...
    GetSmoothingSigmasAreSpecifiedInPhysicalUnits: Any = ...
    SmoothingSigmasAreSpecifiedInPhysicalUnitsOn: Any = ...
    SmoothingSigmasAreSpecifiedInPhysicalUnitsOff: Any = ...
    GetOutput: Any = ...
    GetTransformOutput: Any = ...
    GetModifiableTransform: Any = ...
    GetTransform: Any = ...
    GetCurrentLevel: Any = ...
    GetCurrentIteration: Any = ...
    GetCurrentMetricValue: Any = ...
    GetCurrentConvergenceValue: Any = ...
    GetIsConverged: Any = ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    InitializeCenterOfLinearOutputTransformOn: Any = ...
    InitializeCenterOfLinearOutputTransformOff: Any = ...
    SetInitializeCenterOfLinearOutputTransform: Any = ...
    GetInitializeCenterOfLinearOutputTransform: Any = ...
    InitializeCenterOfLinearOutputTransform: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageRegistrationMethodv4REGv4F3F3___New_orig__: Any
itkImageRegistrationMethodv4REGv4F3F3_cast: Any

def image_registration_methodv4(*args: Any, **kwargs: Any): ...
def image_registration_methodv4_init_docstring() -> None: ...
