import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkImageShapeModelEstimatorBaseIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageShapeModelEstimatorBaseIF2IF2_cast: Any

class itkImageShapeModelEstimatorBaseIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageShapeModelEstimatorBaseIF3IF3_cast: Any

class itkImageShapeModelEstimatorBaseISS2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageShapeModelEstimatorBaseISS2IF2_cast: Any

class itkImageShapeModelEstimatorBaseISS3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageShapeModelEstimatorBaseISS3IF3_cast: Any

class itkImageShapeModelEstimatorBaseIUC2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageShapeModelEstimatorBaseIUC2IF2_cast: Any

class itkImageShapeModelEstimatorBaseIUC3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageShapeModelEstimatorBaseIUC3IF3_cast: Any

def image_shape_model_estimator_base(*args: Any, **kwargs: Any): ...
def image_shape_model_estimator_base_init_docstring() -> None: ...
