import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkIsolatedWatershedImageFilterIF2IF2_New(): ...

class itkIsolatedWatershedImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed1: Any = ...
    GetSeed1: Any = ...
    SetSeed2: Any = ...
    GetSeed2: Any = ...
    SetThreshold: Any = ...
    GetThreshold: Any = ...
    SetIsolatedValueTolerance: Any = ...
    GetIsolatedValueTolerance: Any = ...
    SetUpperValueLimit: Any = ...
    GetUpperValueLimit: Any = ...
    SetReplaceValue1: Any = ...
    GetReplaceValue1: Any = ...
    SetReplaceValue2: Any = ...
    GetReplaceValue2: Any = ...
    GetIsolatedValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsolatedWatershedImageFilterIF2IF2___New_orig__: Any
itkIsolatedWatershedImageFilterIF2IF2_cast: Any

def itkIsolatedWatershedImageFilterIF3IF3_New(): ...

class itkIsolatedWatershedImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed1: Any = ...
    GetSeed1: Any = ...
    SetSeed2: Any = ...
    GetSeed2: Any = ...
    SetThreshold: Any = ...
    GetThreshold: Any = ...
    SetIsolatedValueTolerance: Any = ...
    GetIsolatedValueTolerance: Any = ...
    SetUpperValueLimit: Any = ...
    GetUpperValueLimit: Any = ...
    SetReplaceValue1: Any = ...
    GetReplaceValue1: Any = ...
    SetReplaceValue2: Any = ...
    GetReplaceValue2: Any = ...
    GetIsolatedValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsolatedWatershedImageFilterIF3IF3___New_orig__: Any
itkIsolatedWatershedImageFilterIF3IF3_cast: Any

def itkIsolatedWatershedImageFilterISS2ISS2_New(): ...

class itkIsolatedWatershedImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed1: Any = ...
    GetSeed1: Any = ...
    SetSeed2: Any = ...
    GetSeed2: Any = ...
    SetThreshold: Any = ...
    GetThreshold: Any = ...
    SetIsolatedValueTolerance: Any = ...
    GetIsolatedValueTolerance: Any = ...
    SetUpperValueLimit: Any = ...
    GetUpperValueLimit: Any = ...
    SetReplaceValue1: Any = ...
    GetReplaceValue1: Any = ...
    SetReplaceValue2: Any = ...
    GetReplaceValue2: Any = ...
    GetIsolatedValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsolatedWatershedImageFilterISS2ISS2___New_orig__: Any
itkIsolatedWatershedImageFilterISS2ISS2_cast: Any

def itkIsolatedWatershedImageFilterISS3ISS3_New(): ...

class itkIsolatedWatershedImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed1: Any = ...
    GetSeed1: Any = ...
    SetSeed2: Any = ...
    GetSeed2: Any = ...
    SetThreshold: Any = ...
    GetThreshold: Any = ...
    SetIsolatedValueTolerance: Any = ...
    GetIsolatedValueTolerance: Any = ...
    SetUpperValueLimit: Any = ...
    GetUpperValueLimit: Any = ...
    SetReplaceValue1: Any = ...
    GetReplaceValue1: Any = ...
    SetReplaceValue2: Any = ...
    GetReplaceValue2: Any = ...
    GetIsolatedValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsolatedWatershedImageFilterISS3ISS3___New_orig__: Any
itkIsolatedWatershedImageFilterISS3ISS3_cast: Any

def itkIsolatedWatershedImageFilterIUC2IUC2_New(): ...

class itkIsolatedWatershedImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed1: Any = ...
    GetSeed1: Any = ...
    SetSeed2: Any = ...
    GetSeed2: Any = ...
    SetThreshold: Any = ...
    GetThreshold: Any = ...
    SetIsolatedValueTolerance: Any = ...
    GetIsolatedValueTolerance: Any = ...
    SetUpperValueLimit: Any = ...
    GetUpperValueLimit: Any = ...
    SetReplaceValue1: Any = ...
    GetReplaceValue1: Any = ...
    SetReplaceValue2: Any = ...
    GetReplaceValue2: Any = ...
    GetIsolatedValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsolatedWatershedImageFilterIUC2IUC2___New_orig__: Any
itkIsolatedWatershedImageFilterIUC2IUC2_cast: Any

def itkIsolatedWatershedImageFilterIUC3IUC3_New(): ...

class itkIsolatedWatershedImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    SetSeed1: Any = ...
    GetSeed1: Any = ...
    SetSeed2: Any = ...
    GetSeed2: Any = ...
    SetThreshold: Any = ...
    GetThreshold: Any = ...
    SetIsolatedValueTolerance: Any = ...
    GetIsolatedValueTolerance: Any = ...
    SetUpperValueLimit: Any = ...
    GetUpperValueLimit: Any = ...
    SetReplaceValue1: Any = ...
    GetReplaceValue1: Any = ...
    SetReplaceValue2: Any = ...
    GetReplaceValue2: Any = ...
    GetIsolatedValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsolatedWatershedImageFilterIUC3IUC3___New_orig__: Any
itkIsolatedWatershedImageFilterIUC3IUC3_cast: Any

def isolated_watershed_image_filter(*args: Any, **kwargs: Any): ...
def isolated_watershed_image_filter_init_docstring() -> None: ...
