import itk.itkArrayPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkInterpolateImageFilterIF2IF2_New(): ...

class itkInterpolateImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    GetInput1: Any = ...
    SetInput2: Any = ...
    GetInput2: Any = ...
    SetDistance: Any = ...
    GetDistance: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    BeforeThreadedGenerateData: Any = ...
    AfterThreadedGenerateData: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkInterpolateImageFilterIF2IF2___New_orig__: Any
itkInterpolateImageFilterIF2IF2_cast: Any

def itkInterpolateImageFilterIF3IF3_New(): ...

class itkInterpolateImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    GetInput1: Any = ...
    SetInput2: Any = ...
    GetInput2: Any = ...
    SetDistance: Any = ...
    GetDistance: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    BeforeThreadedGenerateData: Any = ...
    AfterThreadedGenerateData: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkInterpolateImageFilterIF3IF3___New_orig__: Any
itkInterpolateImageFilterIF3IF3_cast: Any

def itkInterpolateImageFilterISS2ISS2_New(): ...

class itkInterpolateImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    GetInput1: Any = ...
    SetInput2: Any = ...
    GetInput2: Any = ...
    SetDistance: Any = ...
    GetDistance: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    BeforeThreadedGenerateData: Any = ...
    AfterThreadedGenerateData: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkInterpolateImageFilterISS2ISS2___New_orig__: Any
itkInterpolateImageFilterISS2ISS2_cast: Any

def itkInterpolateImageFilterISS3ISS3_New(): ...

class itkInterpolateImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    GetInput1: Any = ...
    SetInput2: Any = ...
    GetInput2: Any = ...
    SetDistance: Any = ...
    GetDistance: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    BeforeThreadedGenerateData: Any = ...
    AfterThreadedGenerateData: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkInterpolateImageFilterISS3ISS3___New_orig__: Any
itkInterpolateImageFilterISS3ISS3_cast: Any

def itkInterpolateImageFilterIUC2IUC2_New(): ...

class itkInterpolateImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    GetInput1: Any = ...
    SetInput2: Any = ...
    GetInput2: Any = ...
    SetDistance: Any = ...
    GetDistance: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    BeforeThreadedGenerateData: Any = ...
    AfterThreadedGenerateData: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkInterpolateImageFilterIUC2IUC2___New_orig__: Any
itkInterpolateImageFilterIUC2IUC2_cast: Any

def itkInterpolateImageFilterIUC3IUC3_New(): ...

class itkInterpolateImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    GetInput1: Any = ...
    SetInput2: Any = ...
    GetInput2: Any = ...
    SetDistance: Any = ...
    GetDistance: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    BeforeThreadedGenerateData: Any = ...
    AfterThreadedGenerateData: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkInterpolateImageFilterIUC3IUC3___New_orig__: Any
itkInterpolateImageFilterIUC3IUC3_cast: Any

def interpolate_image_filter(*args: Any, **kwargs: Any): ...
def interpolate_image_filter_init_docstring() -> None: ...
