import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkImagePCAShapeModelEstimatorIF2IF2_New(): ...

class itkImagePCAShapeModelEstimatorIF2IF2(itk.itkImageShapeModelEstimatorBasePython.itkImageShapeModelEstimatorBaseIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfPrincipalComponentsRequired: Any = ...
    GetNumberOfPrincipalComponentsRequired: Any = ...
    SetNumberOfTrainingImages: Any = ...
    GetNumberOfTrainingImages: Any = ...
    GetEigenValues: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImagePCAShapeModelEstimatorIF2IF2___New_orig__: Any
itkImagePCAShapeModelEstimatorIF2IF2_cast: Any

def itkImagePCAShapeModelEstimatorIF3IF3_New(): ...

class itkImagePCAShapeModelEstimatorIF3IF3(itk.itkImageShapeModelEstimatorBasePython.itkImageShapeModelEstimatorBaseIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfPrincipalComponentsRequired: Any = ...
    GetNumberOfPrincipalComponentsRequired: Any = ...
    SetNumberOfTrainingImages: Any = ...
    GetNumberOfTrainingImages: Any = ...
    GetEigenValues: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImagePCAShapeModelEstimatorIF3IF3___New_orig__: Any
itkImagePCAShapeModelEstimatorIF3IF3_cast: Any

def itkImagePCAShapeModelEstimatorISS2IF2_New(): ...

class itkImagePCAShapeModelEstimatorISS2IF2(itk.itkImageShapeModelEstimatorBasePython.itkImageShapeModelEstimatorBaseISS2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfPrincipalComponentsRequired: Any = ...
    GetNumberOfPrincipalComponentsRequired: Any = ...
    SetNumberOfTrainingImages: Any = ...
    GetNumberOfTrainingImages: Any = ...
    GetEigenValues: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImagePCAShapeModelEstimatorISS2IF2___New_orig__: Any
itkImagePCAShapeModelEstimatorISS2IF2_cast: Any

def itkImagePCAShapeModelEstimatorISS3IF3_New(): ...

class itkImagePCAShapeModelEstimatorISS3IF3(itk.itkImageShapeModelEstimatorBasePython.itkImageShapeModelEstimatorBaseISS3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfPrincipalComponentsRequired: Any = ...
    GetNumberOfPrincipalComponentsRequired: Any = ...
    SetNumberOfTrainingImages: Any = ...
    GetNumberOfTrainingImages: Any = ...
    GetEigenValues: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImagePCAShapeModelEstimatorISS3IF3___New_orig__: Any
itkImagePCAShapeModelEstimatorISS3IF3_cast: Any

def itkImagePCAShapeModelEstimatorIUC2IF2_New(): ...

class itkImagePCAShapeModelEstimatorIUC2IF2(itk.itkImageShapeModelEstimatorBasePython.itkImageShapeModelEstimatorBaseIUC2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfPrincipalComponentsRequired: Any = ...
    GetNumberOfPrincipalComponentsRequired: Any = ...
    SetNumberOfTrainingImages: Any = ...
    GetNumberOfTrainingImages: Any = ...
    GetEigenValues: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImagePCAShapeModelEstimatorIUC2IF2___New_orig__: Any
itkImagePCAShapeModelEstimatorIUC2IF2_cast: Any

def itkImagePCAShapeModelEstimatorIUC3IF3_New(): ...

class itkImagePCAShapeModelEstimatorIUC3IF3(itk.itkImageShapeModelEstimatorBasePython.itkImageShapeModelEstimatorBaseIUC3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfPrincipalComponentsRequired: Any = ...
    GetNumberOfPrincipalComponentsRequired: Any = ...
    SetNumberOfTrainingImages: Any = ...
    GetNumberOfTrainingImages: Any = ...
    GetEigenValues: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImagePCAShapeModelEstimatorIUC3IF3___New_orig__: Any
itkImagePCAShapeModelEstimatorIUC3IF3_cast: Any

def image_pca_shape_model_estimator(*args: Any, **kwargs: Any): ...
def image_pca_shape_model_estimator_init_docstring() -> None: ...
