import itk.itkImageSourceCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkIsoDataThresholdImageFilterIF2ISS2_New(): ...

class itkIsoDataThresholdImageFilterIF2ISS2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsoDataThresholdImageFilterIF2ISS2___New_orig__: Any
itkIsoDataThresholdImageFilterIF2ISS2_cast: Any

def itkIsoDataThresholdImageFilterIF2IUC2_New(): ...

class itkIsoDataThresholdImageFilterIF2IUC2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsoDataThresholdImageFilterIF2IUC2___New_orig__: Any
itkIsoDataThresholdImageFilterIF2IUC2_cast: Any

def itkIsoDataThresholdImageFilterIF3ISS3_New(): ...

class itkIsoDataThresholdImageFilterIF3ISS3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsoDataThresholdImageFilterIF3ISS3___New_orig__: Any
itkIsoDataThresholdImageFilterIF3ISS3_cast: Any

def itkIsoDataThresholdImageFilterIF3IUC3_New(): ...

class itkIsoDataThresholdImageFilterIF3IUC3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsoDataThresholdImageFilterIF3IUC3___New_orig__: Any
itkIsoDataThresholdImageFilterIF3IUC3_cast: Any

def itkIsoDataThresholdImageFilterISS2ISS2_New(): ...

class itkIsoDataThresholdImageFilterISS2ISS2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsoDataThresholdImageFilterISS2ISS2___New_orig__: Any
itkIsoDataThresholdImageFilterISS2ISS2_cast: Any

def itkIsoDataThresholdImageFilterISS2IUC2_New(): ...

class itkIsoDataThresholdImageFilterISS2IUC2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsoDataThresholdImageFilterISS2IUC2___New_orig__: Any
itkIsoDataThresholdImageFilterISS2IUC2_cast: Any

def itkIsoDataThresholdImageFilterISS3ISS3_New(): ...

class itkIsoDataThresholdImageFilterISS3ISS3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsoDataThresholdImageFilterISS3ISS3___New_orig__: Any
itkIsoDataThresholdImageFilterISS3ISS3_cast: Any

def itkIsoDataThresholdImageFilterISS3IUC3_New(): ...

class itkIsoDataThresholdImageFilterISS3IUC3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsoDataThresholdImageFilterISS3IUC3___New_orig__: Any
itkIsoDataThresholdImageFilterISS3IUC3_cast: Any

def itkIsoDataThresholdImageFilterIUC2ISS2_New(): ...

class itkIsoDataThresholdImageFilterIUC2ISS2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsoDataThresholdImageFilterIUC2ISS2___New_orig__: Any
itkIsoDataThresholdImageFilterIUC2ISS2_cast: Any

def itkIsoDataThresholdImageFilterIUC2IUC2_New(): ...

class itkIsoDataThresholdImageFilterIUC2IUC2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsoDataThresholdImageFilterIUC2IUC2___New_orig__: Any
itkIsoDataThresholdImageFilterIUC2IUC2_cast: Any

def itkIsoDataThresholdImageFilterIUC3ISS3_New(): ...

class itkIsoDataThresholdImageFilterIUC3ISS3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsoDataThresholdImageFilterIUC3ISS3___New_orig__: Any
itkIsoDataThresholdImageFilterIUC3ISS3_cast: Any

def itkIsoDataThresholdImageFilterIUC3IUC3_New(): ...

class itkIsoDataThresholdImageFilterIUC3IUC3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkIsoDataThresholdImageFilterIUC3IUC3___New_orig__: Any
itkIsoDataThresholdImageFilterIUC3IUC3_cast: Any

def iso_data_threshold_image_filter(*args: Any, **kwargs: Any): ...
def iso_data_threshold_image_filter_init_docstring() -> None: ...
