import itk.itkPointSetPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkImageToImageMetricv4F2F2_Superclass(itk.itkObjectToObjectMetricBasePython.itkObjectToObjectMetricBaseTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetFixedTransform: Any = ...
    GetModifiableFixedTransform: Any = ...
    GetFixedTransform: Any = ...
    SetMovingTransform: Any = ...
    GetModifiableMovingTransform: Any = ...
    GetMovingTransform: Any = ...
    SetTransform: Any = ...
    GetTransform: Any = ...
    GetNumberOfValidPoints: Any = ...
    SetVirtualDomain: Any = ...
    SetVirtualDomainFromImage: Any = ...
    SupportsArbitraryVirtualDomainSamples: Any = ...
    GetVirtualDomainTimeStamp: Any = ...
    GetVirtualSpacing: Any = ...
    GetVirtualOrigin: Any = ...
    GetVirtualDirection: Any = ...
    GetVirtualRegion: Any = ...
    GetModifiableVirtualImage: Any = ...
    GetVirtualImage: Any = ...
    ComputeParameterOffsetFromVirtualIndex: Any = ...
    ComputeParameterOffsetFromVirtualPoint: Any = ...
    IsInsideVirtualDomain: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToImageMetricv4F2F2_Superclass_cast: Any

class itkImageToImageMetricv4F3F3_Superclass(itk.itkObjectToObjectMetricBasePython.itkObjectToObjectMetricBaseTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetFixedTransform: Any = ...
    GetModifiableFixedTransform: Any = ...
    GetFixedTransform: Any = ...
    SetMovingTransform: Any = ...
    GetModifiableMovingTransform: Any = ...
    GetMovingTransform: Any = ...
    SetTransform: Any = ...
    GetTransform: Any = ...
    GetNumberOfValidPoints: Any = ...
    SetVirtualDomain: Any = ...
    SetVirtualDomainFromImage: Any = ...
    SupportsArbitraryVirtualDomainSamples: Any = ...
    GetVirtualDomainTimeStamp: Any = ...
    GetVirtualSpacing: Any = ...
    GetVirtualOrigin: Any = ...
    GetVirtualDirection: Any = ...
    GetVirtualRegion: Any = ...
    GetModifiableVirtualImage: Any = ...
    GetVirtualImage: Any = ...
    ComputeParameterOffsetFromVirtualIndex: Any = ...
    ComputeParameterOffsetFromVirtualPoint: Any = ...
    IsInsideVirtualDomain: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToImageMetricv4F3F3_Superclass_cast: Any

class itkImageToImageMetricv4F2F2(itkImageToImageMetricv4F2F2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedInterpolator: Any = ...
    GetModifiableFixedInterpolator: Any = ...
    GetFixedInterpolator: Any = ...
    SetMovingInterpolator: Any = ...
    GetModifiableMovingInterpolator: Any = ...
    GetMovingInterpolator: Any = ...
    SetMovingImageMask: Any = ...
    GetMovingImageMask: Any = ...
    SetFixedImageMask: Any = ...
    GetFixedImageMask: Any = ...
    SetFixedSampledPointSet: Any = ...
    GetFixedSampledPointSet: Any = ...
    SetVirtualSampledPointSet: Any = ...
    GetVirtualSampledPointSet: Any = ...
    SetUseSampledPointSet: Any = ...
    GetUseSampledPointSet: Any = ...
    UseSampledPointSetOn: Any = ...
    UseSampledPointSetOff: Any = ...
    SetUseVirtualSampledPointSet: Any = ...
    GetUseVirtualSampledPointSet: Any = ...
    UseVirtualSampledPointSetOn: Any = ...
    UseVirtualSampledPointSetOff: Any = ...
    SetFixedImageGradientFilter: Any = ...
    GetModifiableFixedImageGradientFilter: Any = ...
    GetFixedImageGradientFilter: Any = ...
    SetMovingImageGradientFilter: Any = ...
    GetModifiableMovingImageGradientFilter: Any = ...
    GetMovingImageGradientFilter: Any = ...
    SetFixedImageGradientCalculator: Any = ...
    GetModifiableFixedImageGradientCalculator: Any = ...
    GetFixedImageGradientCalculator: Any = ...
    SetMovingImageGradientCalculator: Any = ...
    GetModifiableMovingImageGradientCalculator: Any = ...
    GetMovingImageGradientCalculator: Any = ...
    SetUseFixedImageGradientFilter: Any = ...
    GetUseFixedImageGradientFilter: Any = ...
    UseFixedImageGradientFilterOn: Any = ...
    UseFixedImageGradientFilterOff: Any = ...
    SetUseMovingImageGradientFilter: Any = ...
    GetUseMovingImageGradientFilter: Any = ...
    UseMovingImageGradientFilterOn: Any = ...
    UseMovingImageGradientFilterOff: Any = ...
    GetNumberOfWorkUnitsUsed: Any = ...
    SetMaximumNumberOfWorkUnits: Any = ...
    GetMaximumNumberOfWorkUnits: Any = ...
    FinalizeThread: Any = ...
    GetModifiableFixedImageGradientImage: Any = ...
    GetFixedImageGradientImage: Any = ...
    GetModifiableMovingImageGradientImage: Any = ...
    GetMovingImageGradientImage: Any = ...
    GetNumberOfDomainPoints: Any = ...
    SetUseFloatingPointCorrection: Any = ...
    GetUseFloatingPointCorrection: Any = ...
    UseFloatingPointCorrectionOn: Any = ...
    UseFloatingPointCorrectionOff: Any = ...
    SetFloatingPointCorrectionResolution: Any = ...
    GetFloatingPointCorrectionResolution: Any = ...
    GetNumberOfSkippedFixedSampledPoints: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToImageMetricv4F2F2_cast: Any

class itkImageToImageMetricv4F3F3(itkImageToImageMetricv4F3F3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedInterpolator: Any = ...
    GetModifiableFixedInterpolator: Any = ...
    GetFixedInterpolator: Any = ...
    SetMovingInterpolator: Any = ...
    GetModifiableMovingInterpolator: Any = ...
    GetMovingInterpolator: Any = ...
    SetMovingImageMask: Any = ...
    GetMovingImageMask: Any = ...
    SetFixedImageMask: Any = ...
    GetFixedImageMask: Any = ...
    SetFixedSampledPointSet: Any = ...
    GetFixedSampledPointSet: Any = ...
    SetVirtualSampledPointSet: Any = ...
    GetVirtualSampledPointSet: Any = ...
    SetUseSampledPointSet: Any = ...
    GetUseSampledPointSet: Any = ...
    UseSampledPointSetOn: Any = ...
    UseSampledPointSetOff: Any = ...
    SetUseVirtualSampledPointSet: Any = ...
    GetUseVirtualSampledPointSet: Any = ...
    UseVirtualSampledPointSetOn: Any = ...
    UseVirtualSampledPointSetOff: Any = ...
    SetFixedImageGradientFilter: Any = ...
    GetModifiableFixedImageGradientFilter: Any = ...
    GetFixedImageGradientFilter: Any = ...
    SetMovingImageGradientFilter: Any = ...
    GetModifiableMovingImageGradientFilter: Any = ...
    GetMovingImageGradientFilter: Any = ...
    SetFixedImageGradientCalculator: Any = ...
    GetModifiableFixedImageGradientCalculator: Any = ...
    GetFixedImageGradientCalculator: Any = ...
    SetMovingImageGradientCalculator: Any = ...
    GetModifiableMovingImageGradientCalculator: Any = ...
    GetMovingImageGradientCalculator: Any = ...
    SetUseFixedImageGradientFilter: Any = ...
    GetUseFixedImageGradientFilter: Any = ...
    UseFixedImageGradientFilterOn: Any = ...
    UseFixedImageGradientFilterOff: Any = ...
    SetUseMovingImageGradientFilter: Any = ...
    GetUseMovingImageGradientFilter: Any = ...
    UseMovingImageGradientFilterOn: Any = ...
    UseMovingImageGradientFilterOff: Any = ...
    GetNumberOfWorkUnitsUsed: Any = ...
    SetMaximumNumberOfWorkUnits: Any = ...
    GetMaximumNumberOfWorkUnits: Any = ...
    FinalizeThread: Any = ...
    GetModifiableFixedImageGradientImage: Any = ...
    GetFixedImageGradientImage: Any = ...
    GetModifiableMovingImageGradientImage: Any = ...
    GetMovingImageGradientImage: Any = ...
    GetNumberOfDomainPoints: Any = ...
    SetUseFloatingPointCorrection: Any = ...
    GetUseFloatingPointCorrection: Any = ...
    UseFloatingPointCorrectionOn: Any = ...
    UseFloatingPointCorrectionOff: Any = ...
    SetFloatingPointCorrectionResolution: Any = ...
    GetFloatingPointCorrectionResolution: Any = ...
    GetNumberOfSkippedFixedSampledPoints: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToImageMetricv4F3F3_cast: Any
