import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkInPlaceImageFilterICVF22ICVF22(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF22ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterICVF22ICVF22_cast: Any

class itkInPlaceImageFilterICVF22IVF22(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF22IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterICVF22IVF22_cast: Any

class itkInPlaceImageFilterICVF23ICVF23(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF23ICVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterICVF23ICVF23_cast: Any

class itkInPlaceImageFilterICVF23IVF23(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF23IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterICVF23IVF23_cast: Any

class itkInPlaceImageFilterICVF32ICVF32(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF32ICVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterICVF32ICVF32_cast: Any

class itkInPlaceImageFilterICVF32IVF32(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF32IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterICVF32IVF32_cast: Any

class itkInPlaceImageFilterICVF33ICVF33(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF33ICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterICVF33ICVF33_cast: Any

class itkInPlaceImageFilterICVF33IVF33(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF33IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterICVF33IVF33_cast: Any

class itkInPlaceImageFilterICVF42ICVF42(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF42ICVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterICVF42ICVF42_cast: Any

class itkInPlaceImageFilterICVF42IVF42(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF42IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterICVF42IVF42_cast: Any

class itkInPlaceImageFilterICVF43ICVF43(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF43ICVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterICVF43ICVF43_cast: Any

class itkInPlaceImageFilterICVF43IVF43(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF43IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterICVF43IVF43_cast: Any

class itkInPlaceImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIF2IF2_cast: Any

class itkInPlaceImageFilterIF2IRGBAUC2(itk.itkImageToImageFilterBPython.itkImageToImageFilterIF2IRGBAUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIF2IRGBAUC2_cast: Any

class itkInPlaceImageFilterIF2IRGBUC2(itk.itkImageToImageFilterBPython.itkImageToImageFilterIF2IRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIF2IRGBUC2_cast: Any

class itkInPlaceImageFilterIF2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIF2ISS2_cast: Any

class itkInPlaceImageFilterIF2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIF2IUC2_cast: Any

class itkInPlaceImageFilterIF2IUL2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IUL2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIF2IUL2_cast: Any

class itkInPlaceImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIF3IF3_cast: Any

class itkInPlaceImageFilterIF3IRGBAUC3(itk.itkImageToImageFilterBPython.itkImageToImageFilterIF3IRGBAUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIF3IRGBAUC3_cast: Any

class itkInPlaceImageFilterIF3IRGBUC3(itk.itkImageToImageFilterBPython.itkImageToImageFilterIF3IRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIF3IRGBUC3_cast: Any

class itkInPlaceImageFilterIF3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIF3ISS3_cast: Any

class itkInPlaceImageFilterIF3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIF3IUC3_cast: Any

class itkInPlaceImageFilterIF3IUL3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IUL3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIF3IUL3_cast: Any

class itkInPlaceImageFilterIRGBAUC2IRGBAUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBAUC2IRGBAUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIRGBAUC2IRGBAUC2_cast: Any

class itkInPlaceImageFilterIRGBAUC2IUC2(itk.itkImageToImageFilterBPython.itkImageToImageFilterIRGBAUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIRGBAUC2IUC2_cast: Any

class itkInPlaceImageFilterIRGBAUC3IRGBAUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBAUC3IRGBAUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIRGBAUC3IRGBAUC3_cast: Any

class itkInPlaceImageFilterIRGBAUC3IUC3(itk.itkImageToImageFilterBPython.itkImageToImageFilterIRGBAUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIRGBAUC3IUC3_cast: Any

class itkInPlaceImageFilterIRGBUC2IRGBUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBUC2IRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIRGBUC2IRGBUC2_cast: Any

class itkInPlaceImageFilterIRGBUC3IRGBUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBUC3IRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIRGBUC3IRGBUC3_cast: Any

class itkInPlaceImageFilterISS2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterISS2IF2_cast: Any

class itkInPlaceImageFilterISS2IRGBAUC2(itk.itkImageToImageFilterBPython.itkImageToImageFilterISS2IRGBAUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterISS2IRGBAUC2_cast: Any

class itkInPlaceImageFilterISS2IRGBUC2(itk.itkImageToImageFilterBPython.itkImageToImageFilterISS2IRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterISS2IRGBUC2_cast: Any

class itkInPlaceImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterISS2ISS2_cast: Any

class itkInPlaceImageFilterISS2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterISS2IUC2_cast: Any

class itkInPlaceImageFilterISS2IUL2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2IUL2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterISS2IUL2_cast: Any

class itkInPlaceImageFilterISS3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterISS3IF3_cast: Any

class itkInPlaceImageFilterISS3IRGBAUC3(itk.itkImageToImageFilterBPython.itkImageToImageFilterISS3IRGBAUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterISS3IRGBAUC3_cast: Any

class itkInPlaceImageFilterISS3IRGBUC3(itk.itkImageToImageFilterBPython.itkImageToImageFilterISS3IRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterISS3IRGBUC3_cast: Any

class itkInPlaceImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterISS3ISS3_cast: Any

class itkInPlaceImageFilterISS3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterISS3IUC3_cast: Any

class itkInPlaceImageFilterISS3IUL3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3IUL3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterISS3IUL3_cast: Any

class itkInPlaceImageFilterIUC2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUC2IF2_cast: Any

class itkInPlaceImageFilterIUC2IRGBAUC2(itk.itkImageToImageFilterBPython.itkImageToImageFilterIUC2IRGBAUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUC2IRGBAUC2_cast: Any

class itkInPlaceImageFilterIUC2IRGBUC2(itk.itkImageToImageFilterBPython.itkImageToImageFilterIUC2IRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUC2IRGBUC2_cast: Any

class itkInPlaceImageFilterIUC2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUC2ISS2_cast: Any

class itkInPlaceImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUC2IUC2_cast: Any

class itkInPlaceImageFilterIUC2IUL2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUL2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUC2IUL2_cast: Any

class itkInPlaceImageFilterIUC3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUC3IF3_cast: Any

class itkInPlaceImageFilterIUC3IRGBAUC3(itk.itkImageToImageFilterBPython.itkImageToImageFilterIUC3IRGBAUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUC3IRGBAUC3_cast: Any

class itkInPlaceImageFilterIUC3IRGBUC3(itk.itkImageToImageFilterBPython.itkImageToImageFilterIUC3IRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUC3IRGBUC3_cast: Any

class itkInPlaceImageFilterIUC3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUC3ISS3_cast: Any

class itkInPlaceImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUC3IUC3_cast: Any

class itkInPlaceImageFilterIUC3IUL3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUL3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUC3IUL3_cast: Any

class itkInPlaceImageFilterIUL2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUL2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUL2IF2_cast: Any

class itkInPlaceImageFilterIUL2IRGBAUC2(itk.itkImageToImageFilterBPython.itkImageToImageFilterIUL2IRGBAUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUL2IRGBAUC2_cast: Any

class itkInPlaceImageFilterIUL2IRGBUC2(itk.itkImageToImageFilterBPython.itkImageToImageFilterIUL2IRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUL2IRGBUC2_cast: Any

class itkInPlaceImageFilterIUL2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUL2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUL2ISS2_cast: Any

class itkInPlaceImageFilterIUL2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUL2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUL2IUC2_cast: Any

class itkInPlaceImageFilterIUL2IUL2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUL2IUL2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUL2IUL2_cast: Any

class itkInPlaceImageFilterIUL3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUL3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUL3IF3_cast: Any

class itkInPlaceImageFilterIUL3IRGBAUC3(itk.itkImageToImageFilterBPython.itkImageToImageFilterIUL3IRGBAUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUL3IRGBAUC3_cast: Any

class itkInPlaceImageFilterIUL3IRGBUC3(itk.itkImageToImageFilterBPython.itkImageToImageFilterIUL3IRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUL3IRGBUC3_cast: Any

class itkInPlaceImageFilterIUL3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUL3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUL3ISS3_cast: Any

class itkInPlaceImageFilterIUL3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUL3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUL3IUC3_cast: Any

class itkInPlaceImageFilterIUL3IUL3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUL3IUL3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIUL3IUL3_cast: Any

class itkInPlaceImageFilterIULL2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIULL2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIULL2IF2_cast: Any

class itkInPlaceImageFilterIULL2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIULL2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIULL2ISS2_cast: Any

class itkInPlaceImageFilterIULL2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIULL2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIULL2IUC2_cast: Any

class itkInPlaceImageFilterIULL2IUL2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIULL2IUL2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIULL2IUL2_cast: Any

class itkInPlaceImageFilterIULL3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIULL3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIULL3IF3_cast: Any

class itkInPlaceImageFilterIULL3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIULL3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIULL3ISS3_cast: Any

class itkInPlaceImageFilterIULL3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIULL3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIULL3IUC3_cast: Any

class itkInPlaceImageFilterIULL3IUL3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIULL3IUL3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIULL3IUL3_cast: Any

class itkInPlaceImageFilterIVF22ICVF22(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF22ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIVF22ICVF22_cast: Any

class itkInPlaceImageFilterIVF22IVF22(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF22IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIVF22IVF22_cast: Any

class itkInPlaceImageFilterIVF23ICVF23(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF23ICVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIVF23ICVF23_cast: Any

class itkInPlaceImageFilterIVF23IVF23(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF23IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIVF23IVF23_cast: Any

class itkInPlaceImageFilterIVF32ICVF32(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF32ICVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIVF32ICVF32_cast: Any

class itkInPlaceImageFilterIVF32IVF32(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF32IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIVF32IVF32_cast: Any

class itkInPlaceImageFilterIVF33ICVF33(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF33ICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIVF33ICVF33_cast: Any

class itkInPlaceImageFilterIVF33IVF33(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF33IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIVF33IVF33_cast: Any

class itkInPlaceImageFilterIVF42ICVF42(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF42ICVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIVF42ICVF42_cast: Any

class itkInPlaceImageFilterIVF42IVF42(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF42IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIVF42IVF42_cast: Any

class itkInPlaceImageFilterIVF43ICVF43(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF43ICVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIVF43ICVF43_cast: Any

class itkInPlaceImageFilterIVF43IVF43(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF43IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkInPlaceImageFilterIVF43IVF43_cast: Any

def in_place_image_filter(*args: Any, **kwargs: Any): ...
def in_place_image_filter_init_docstring() -> None: ...
