import itk.itkImageRegionPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkImageSeriesWriterICF2ICF2_New(): ...

class itkImageSeriesWriterICF2ICF2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterICF2ICF2___New_orig__: Any
itkImageSeriesWriterICF2ICF2_cast: Any

def itkImageSeriesWriterICF3ICF2_New(): ...

class itkImageSeriesWriterICF3ICF2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterICF3ICF2___New_orig__: Any
itkImageSeriesWriterICF3ICF2_cast: Any

def itkImageSeriesWriterICF3ICF3_New(): ...

class itkImageSeriesWriterICF3ICF3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterICF3ICF3___New_orig__: Any
itkImageSeriesWriterICF3ICF3_cast: Any

def itkImageSeriesWriterICVF22ICVF22_New(): ...

class itkImageSeriesWriterICVF22ICVF22(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterICVF22ICVF22___New_orig__: Any
itkImageSeriesWriterICVF22ICVF22_cast: Any

def itkImageSeriesWriterICVF23ICVF23_New(): ...

class itkImageSeriesWriterICVF23ICVF23(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterICVF23ICVF23___New_orig__: Any
itkImageSeriesWriterICVF23ICVF23_cast: Any

def itkImageSeriesWriterICVF32ICVF32_New(): ...

class itkImageSeriesWriterICVF32ICVF32(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterICVF32ICVF32___New_orig__: Any
itkImageSeriesWriterICVF32ICVF32_cast: Any

def itkImageSeriesWriterICVF33ICVF33_New(): ...

class itkImageSeriesWriterICVF33ICVF33(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterICVF33ICVF33___New_orig__: Any
itkImageSeriesWriterICVF33ICVF33_cast: Any

def itkImageSeriesWriterICVF42ICVF42_New(): ...

class itkImageSeriesWriterICVF42ICVF42(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterICVF42ICVF42___New_orig__: Any
itkImageSeriesWriterICVF42ICVF42_cast: Any

def itkImageSeriesWriterICVF43ICVF43_New(): ...

class itkImageSeriesWriterICVF43ICVF43(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterICVF43ICVF43___New_orig__: Any
itkImageSeriesWriterICVF43ICVF43_cast: Any

def itkImageSeriesWriterIF2IF2_New(): ...

class itkImageSeriesWriterIF2IF2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterIF2IF2___New_orig__: Any
itkImageSeriesWriterIF2IF2_cast: Any

def itkImageSeriesWriterIF3IF2_New(): ...

class itkImageSeriesWriterIF3IF2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterIF3IF2___New_orig__: Any
itkImageSeriesWriterIF3IF2_cast: Any

def itkImageSeriesWriterIF3IF3_New(): ...

class itkImageSeriesWriterIF3IF3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterIF3IF3___New_orig__: Any
itkImageSeriesWriterIF3IF3_cast: Any

def itkImageSeriesWriterIRGBAUC2IRGBAUC2_New(): ...

class itkImageSeriesWriterIRGBAUC2IRGBAUC2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterIRGBAUC2IRGBAUC2___New_orig__: Any
itkImageSeriesWriterIRGBAUC2IRGBAUC2_cast: Any

def itkImageSeriesWriterIRGBAUC3IRGBAUC3_New(): ...

class itkImageSeriesWriterIRGBAUC3IRGBAUC3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterIRGBAUC3IRGBAUC3___New_orig__: Any
itkImageSeriesWriterIRGBAUC3IRGBAUC3_cast: Any

def itkImageSeriesWriterIRGBUC2IRGBUC2_New(): ...

class itkImageSeriesWriterIRGBUC2IRGBUC2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterIRGBUC2IRGBUC2___New_orig__: Any
itkImageSeriesWriterIRGBUC2IRGBUC2_cast: Any

def itkImageSeriesWriterIRGBUC3IRGBUC2_New(): ...

class itkImageSeriesWriterIRGBUC3IRGBUC2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterIRGBUC3IRGBUC2___New_orig__: Any
itkImageSeriesWriterIRGBUC3IRGBUC2_cast: Any

def itkImageSeriesWriterIRGBUC3IRGBUC3_New(): ...

class itkImageSeriesWriterIRGBUC3IRGBUC3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterIRGBUC3IRGBUC3___New_orig__: Any
itkImageSeriesWriterIRGBUC3IRGBUC3_cast: Any

def itkImageSeriesWriterISS2ISS2_New(): ...

class itkImageSeriesWriterISS2ISS2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterISS2ISS2___New_orig__: Any
itkImageSeriesWriterISS2ISS2_cast: Any

def itkImageSeriesWriterISS3ISS2_New(): ...

class itkImageSeriesWriterISS3ISS2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterISS3ISS2___New_orig__: Any
itkImageSeriesWriterISS3ISS2_cast: Any

def itkImageSeriesWriterISS3ISS3_New(): ...

class itkImageSeriesWriterISS3ISS3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterISS3ISS3___New_orig__: Any
itkImageSeriesWriterISS3ISS3_cast: Any

def itkImageSeriesWriterIUC2IUC2_New(): ...

class itkImageSeriesWriterIUC2IUC2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterIUC2IUC2___New_orig__: Any
itkImageSeriesWriterIUC2IUC2_cast: Any

def itkImageSeriesWriterIUC3IUC2_New(): ...

class itkImageSeriesWriterIUC3IUC2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterIUC3IUC2___New_orig__: Any
itkImageSeriesWriterIUC3IUC2_cast: Any

def itkImageSeriesWriterIUC3IUC3_New(): ...

class itkImageSeriesWriterIUC3IUC3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterIUC3IUC3___New_orig__: Any
itkImageSeriesWriterIUC3IUC3_cast: Any

def itkImageSeriesWriterIVF22IVF22_New(): ...

class itkImageSeriesWriterIVF22IVF22(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterIVF22IVF22___New_orig__: Any
itkImageSeriesWriterIVF22IVF22_cast: Any

def itkImageSeriesWriterIVF23IVF23_New(): ...

class itkImageSeriesWriterIVF23IVF23(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterIVF23IVF23___New_orig__: Any
itkImageSeriesWriterIVF23IVF23_cast: Any

def itkImageSeriesWriterIVF32IVF32_New(): ...

class itkImageSeriesWriterIVF32IVF32(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterIVF32IVF32___New_orig__: Any
itkImageSeriesWriterIVF32IVF32_cast: Any

def itkImageSeriesWriterIVF33IVF33_New(): ...

class itkImageSeriesWriterIVF33IVF33(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterIVF33IVF33___New_orig__: Any
itkImageSeriesWriterIVF33IVF33_cast: Any

def itkImageSeriesWriterIVF42IVF42_New(): ...

class itkImageSeriesWriterIVF42IVF42(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterIVF42IVF42___New_orig__: Any
itkImageSeriesWriterIVF42IVF42_cast: Any

def itkImageSeriesWriterIVF43IVF43_New(): ...

class itkImageSeriesWriterIVF43IVF43(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetImageIO: Any = ...
    GetModifiableImageIO: Any = ...
    GetImageIO: Any = ...
    Write: Any = ...
    SetStartIndex: Any = ...
    GetStartIndex: Any = ...
    SetIncrementIndex: Any = ...
    GetIncrementIndex: Any = ...
    SetSeriesFormat: Any = ...
    GetSeriesFormat: Any = ...
    SetFileNames: Any = ...
    GetFileNames: Any = ...
    SetFileName: Any = ...
    AddFileName: Any = ...
    SetMetaDataDictionaryArray: Any = ...
    SetUseCompression: Any = ...
    GetUseCompression: Any = ...
    UseCompressionOn: Any = ...
    UseCompressionOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageSeriesWriterIVF43IVF43___New_orig__: Any
itkImageSeriesWriterIVF43IVF43_cast: Any

def image_series_writer(*args: Any, **kwargs: Any): ...
def image_series_writer_init_docstring() -> None: ...
