import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkInPlaceLabelMapFilterLM2_New(): ...

class itkInPlaceLabelMapFilterLM2(itk.itkLabelMapFilterPython.itkLabelMapFilterLM2LM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkInPlaceLabelMapFilterLM2___New_orig__: Any
itkInPlaceLabelMapFilterLM2_cast: Any

def itkInPlaceLabelMapFilterLM3_New(): ...

class itkInPlaceLabelMapFilterLM3(itk.itkLabelMapFilterPython.itkLabelMapFilterLM3LM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInPlace: Any = ...
    GetInPlace: Any = ...
    InPlaceOn: Any = ...
    InPlaceOff: Any = ...
    CanRunInPlace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkInPlaceLabelMapFilterLM3___New_orig__: Any
itkInPlaceLabelMapFilterLM3_cast: Any

def in_place_label_map_filter(*args: Any, **kwargs: Any): ...
def in_place_label_map_filter_init_docstring() -> None: ...
