import itk.itkRGBPixelPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkImageDuplicatorICVF22_New(): ...

class itkImageDuplicatorICVF22(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorICVF22___New_orig__: Any
itkImageDuplicatorICVF22_cast: Any

def itkImageDuplicatorICVF23_New(): ...

class itkImageDuplicatorICVF23(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorICVF23___New_orig__: Any
itkImageDuplicatorICVF23_cast: Any

def itkImageDuplicatorICVF32_New(): ...

class itkImageDuplicatorICVF32(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorICVF32___New_orig__: Any
itkImageDuplicatorICVF32_cast: Any

def itkImageDuplicatorICVF33_New(): ...

class itkImageDuplicatorICVF33(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorICVF33___New_orig__: Any
itkImageDuplicatorICVF33_cast: Any

def itkImageDuplicatorICVF42_New(): ...

class itkImageDuplicatorICVF42(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorICVF42___New_orig__: Any
itkImageDuplicatorICVF42_cast: Any

def itkImageDuplicatorICVF43_New(): ...

class itkImageDuplicatorICVF43(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorICVF43___New_orig__: Any
itkImageDuplicatorICVF43_cast: Any

def itkImageDuplicatorID2_New(): ...

class itkImageDuplicatorID2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorID2___New_orig__: Any
itkImageDuplicatorID2_cast: Any

def itkImageDuplicatorID3_New(): ...

class itkImageDuplicatorID3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorID3___New_orig__: Any
itkImageDuplicatorID3_cast: Any

def itkImageDuplicatorIF2_New(): ...

class itkImageDuplicatorIF2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorIF2___New_orig__: Any
itkImageDuplicatorIF2_cast: Any

def itkImageDuplicatorIF3_New(): ...

class itkImageDuplicatorIF3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorIF3___New_orig__: Any
itkImageDuplicatorIF3_cast: Any

def itkImageDuplicatorIRGBAUC2_New(): ...

class itkImageDuplicatorIRGBAUC2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorIRGBAUC2___New_orig__: Any
itkImageDuplicatorIRGBAUC2_cast: Any

def itkImageDuplicatorIRGBAUC3_New(): ...

class itkImageDuplicatorIRGBAUC3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorIRGBAUC3___New_orig__: Any
itkImageDuplicatorIRGBAUC3_cast: Any

def itkImageDuplicatorIRGBUC2_New(): ...

class itkImageDuplicatorIRGBUC2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorIRGBUC2___New_orig__: Any
itkImageDuplicatorIRGBUC2_cast: Any

def itkImageDuplicatorIRGBUC3_New(): ...

class itkImageDuplicatorIRGBUC3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorIRGBUC3___New_orig__: Any
itkImageDuplicatorIRGBUC3_cast: Any

def itkImageDuplicatorISS2_New(): ...

class itkImageDuplicatorISS2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorISS2___New_orig__: Any
itkImageDuplicatorISS2_cast: Any

def itkImageDuplicatorISS3_New(): ...

class itkImageDuplicatorISS3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorISS3___New_orig__: Any
itkImageDuplicatorISS3_cast: Any

def itkImageDuplicatorISSRTD22_New(): ...

class itkImageDuplicatorISSRTD22(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorISSRTD22___New_orig__: Any
itkImageDuplicatorISSRTD22_cast: Any

def itkImageDuplicatorISSRTD33_New(): ...

class itkImageDuplicatorISSRTD33(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorISSRTD33___New_orig__: Any
itkImageDuplicatorISSRTD33_cast: Any

def itkImageDuplicatorIUC2_New(): ...

class itkImageDuplicatorIUC2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorIUC2___New_orig__: Any
itkImageDuplicatorIUC2_cast: Any

def itkImageDuplicatorIUC3_New(): ...

class itkImageDuplicatorIUC3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorIUC3___New_orig__: Any
itkImageDuplicatorIUC3_cast: Any

def itkImageDuplicatorIUL2_New(): ...

class itkImageDuplicatorIUL2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorIUL2___New_orig__: Any
itkImageDuplicatorIUL2_cast: Any

def itkImageDuplicatorIUL3_New(): ...

class itkImageDuplicatorIUL3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorIUL3___New_orig__: Any
itkImageDuplicatorIUL3_cast: Any

def itkImageDuplicatorIVF22_New(): ...

class itkImageDuplicatorIVF22(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorIVF22___New_orig__: Any
itkImageDuplicatorIVF22_cast: Any

def itkImageDuplicatorIVF23_New(): ...

class itkImageDuplicatorIVF23(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorIVF23___New_orig__: Any
itkImageDuplicatorIVF23_cast: Any

def itkImageDuplicatorIVF32_New(): ...

class itkImageDuplicatorIVF32(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorIVF32___New_orig__: Any
itkImageDuplicatorIVF32_cast: Any

def itkImageDuplicatorIVF33_New(): ...

class itkImageDuplicatorIVF33(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorIVF33___New_orig__: Any
itkImageDuplicatorIVF33_cast: Any

def itkImageDuplicatorIVF42_New(): ...

class itkImageDuplicatorIVF42(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorIVF42___New_orig__: Any
itkImageDuplicatorIVF42_cast: Any

def itkImageDuplicatorIVF43_New(): ...

class itkImageDuplicatorIVF43(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputImage: Any = ...
    GetOutput: Any = ...
    Update: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __internal_call__(self): ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageDuplicatorIVF43___New_orig__: Any
itkImageDuplicatorIVF43_cast: Any

def image_duplicator(*args: Any, **kwargs: Any): ...
def image_duplicator_init_docstring() -> None: ...
