import itk.itkFunctionBasePython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkImageRegistrationMethodIF2IF2_New(): ...

class itkImageRegistrationMethodIF2IF2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetOptimizer: Any = ...
    GetModifiableOptimizer: Any = ...
    GetOptimizer: Any = ...
    SetMetric: Any = ...
    GetModifiableMetric: Any = ...
    GetMetric: Any = ...
    SetTransform: Any = ...
    GetModifiableTransform: Any = ...
    GetTransform: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    SetInitialTransformParameters: Any = ...
    GetInitialTransformParameters: Any = ...
    GetLastTransformParameters: Any = ...
    SetFixedImageRegion: Any = ...
    GetFixedImageRegion: Any = ...
    GetFixedImageRegionDefined: Any = ...
    SetFixedImageRegionDefined: Any = ...
    Initialize: Any = ...
    GetOutput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageRegistrationMethodIF2IF2___New_orig__: Any
itkImageRegistrationMethodIF2IF2_cast: Any

def itkImageRegistrationMethodIF3IF3_New(): ...

class itkImageRegistrationMethodIF3IF3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetOptimizer: Any = ...
    GetModifiableOptimizer: Any = ...
    GetOptimizer: Any = ...
    SetMetric: Any = ...
    GetModifiableMetric: Any = ...
    GetMetric: Any = ...
    SetTransform: Any = ...
    GetModifiableTransform: Any = ...
    GetTransform: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    SetInitialTransformParameters: Any = ...
    GetInitialTransformParameters: Any = ...
    GetLastTransformParameters: Any = ...
    SetFixedImageRegion: Any = ...
    GetFixedImageRegion: Any = ...
    GetFixedImageRegionDefined: Any = ...
    SetFixedImageRegionDefined: Any = ...
    Initialize: Any = ...
    GetOutput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageRegistrationMethodIF3IF3___New_orig__: Any
itkImageRegistrationMethodIF3IF3_cast: Any

def itkImageRegistrationMethodISS2ISS2_New(): ...

class itkImageRegistrationMethodISS2ISS2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetOptimizer: Any = ...
    GetModifiableOptimizer: Any = ...
    GetOptimizer: Any = ...
    SetMetric: Any = ...
    GetModifiableMetric: Any = ...
    GetMetric: Any = ...
    SetTransform: Any = ...
    GetModifiableTransform: Any = ...
    GetTransform: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    SetInitialTransformParameters: Any = ...
    GetInitialTransformParameters: Any = ...
    GetLastTransformParameters: Any = ...
    SetFixedImageRegion: Any = ...
    GetFixedImageRegion: Any = ...
    GetFixedImageRegionDefined: Any = ...
    SetFixedImageRegionDefined: Any = ...
    Initialize: Any = ...
    GetOutput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageRegistrationMethodISS2ISS2___New_orig__: Any
itkImageRegistrationMethodISS2ISS2_cast: Any

def itkImageRegistrationMethodISS3ISS3_New(): ...

class itkImageRegistrationMethodISS3ISS3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetOptimizer: Any = ...
    GetModifiableOptimizer: Any = ...
    GetOptimizer: Any = ...
    SetMetric: Any = ...
    GetModifiableMetric: Any = ...
    GetMetric: Any = ...
    SetTransform: Any = ...
    GetModifiableTransform: Any = ...
    GetTransform: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    SetInitialTransformParameters: Any = ...
    GetInitialTransformParameters: Any = ...
    GetLastTransformParameters: Any = ...
    SetFixedImageRegion: Any = ...
    GetFixedImageRegion: Any = ...
    GetFixedImageRegionDefined: Any = ...
    SetFixedImageRegionDefined: Any = ...
    Initialize: Any = ...
    GetOutput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageRegistrationMethodISS3ISS3___New_orig__: Any
itkImageRegistrationMethodISS3ISS3_cast: Any

def itkImageRegistrationMethodIUC2IUC2_New(): ...

class itkImageRegistrationMethodIUC2IUC2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetOptimizer: Any = ...
    GetModifiableOptimizer: Any = ...
    GetOptimizer: Any = ...
    SetMetric: Any = ...
    GetModifiableMetric: Any = ...
    GetMetric: Any = ...
    SetTransform: Any = ...
    GetModifiableTransform: Any = ...
    GetTransform: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    SetInitialTransformParameters: Any = ...
    GetInitialTransformParameters: Any = ...
    GetLastTransformParameters: Any = ...
    SetFixedImageRegion: Any = ...
    GetFixedImageRegion: Any = ...
    GetFixedImageRegionDefined: Any = ...
    SetFixedImageRegionDefined: Any = ...
    Initialize: Any = ...
    GetOutput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageRegistrationMethodIUC2IUC2___New_orig__: Any
itkImageRegistrationMethodIUC2IUC2_cast: Any

def itkImageRegistrationMethodIUC3IUC3_New(): ...

class itkImageRegistrationMethodIUC3IUC3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetOptimizer: Any = ...
    GetModifiableOptimizer: Any = ...
    GetOptimizer: Any = ...
    SetMetric: Any = ...
    GetModifiableMetric: Any = ...
    GetMetric: Any = ...
    SetTransform: Any = ...
    GetModifiableTransform: Any = ...
    GetTransform: Any = ...
    SetInterpolator: Any = ...
    GetModifiableInterpolator: Any = ...
    GetInterpolator: Any = ...
    SetInitialTransformParameters: Any = ...
    GetInitialTransformParameters: Any = ...
    GetLastTransformParameters: Any = ...
    SetFixedImageRegion: Any = ...
    GetFixedImageRegion: Any = ...
    GetFixedImageRegionDefined: Any = ...
    SetFixedImageRegionDefined: Any = ...
    Initialize: Any = ...
    GetOutput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkImageRegistrationMethodIUC3IUC3___New_orig__: Any
itkImageRegistrationMethodIUC3IUC3_cast: Any

def image_registration_method(*args: Any, **kwargs: Any): ...
def image_registration_method_init_docstring() -> None: ...
