import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkJoinSeriesImageFilterIF2IF3_New(): ...

class itkJoinSeriesImageFilterIF2IF3(itk.itkImageToImageFilterBPython.itkImageToImageFilterIF2IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkJoinSeriesImageFilterIF2IF3___New_orig__: Any
itkJoinSeriesImageFilterIF2IF3_cast: Any

def itkJoinSeriesImageFilterISS2ISS3_New(): ...

class itkJoinSeriesImageFilterISS2ISS3(itk.itkImageToImageFilterBPython.itkImageToImageFilterISS2ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkJoinSeriesImageFilterISS2ISS3___New_orig__: Any
itkJoinSeriesImageFilterISS2ISS3_cast: Any

def itkJoinSeriesImageFilterIUC2IUC3_New(): ...

class itkJoinSeriesImageFilterIUC2IUC3(itk.itkImageToImageFilterBPython.itkImageToImageFilterIUC2IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkJoinSeriesImageFilterIUC2IUC3___New_orig__: Any
itkJoinSeriesImageFilterIUC2IUC3_cast: Any

def join_series_image_filter(*args: Any, **kwargs: Any): ...
def join_series_image_filter_init_docstring() -> None: ...
