import itk.itkContinuousIndexPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSD2_New(): ...

class itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSD2(itk.itkEuclideanDistancePointSetToPointSetMetricPython.itkEuclideanDistancePointSetToPointSetMetricv4PSD2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetPointSetSigma: Any = ...
    GetPointSetSigma: Any = ...
    SetEvaluationKNeighborhood: Any = ...
    GetEvaluationKNeighborhood: Any = ...
    SetUseAnisotropicCovariances: Any = ...
    GetUseAnisotropicCovariances: Any = ...
    UseAnisotropicCovariancesOn: Any = ...
    UseAnisotropicCovariancesOff: Any = ...
    SetCovarianceKNeighborhood: Any = ...
    GetCovarianceKNeighborhood: Any = ...
    SetKernelSigma: Any = ...
    GetKernelSigma: Any = ...
    GetLocalNeighborhoodValue: Any = ...
    GetLocalNeighborhoodValueAndDerivative: Any = ...
    InternalClone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSD2___New_orig__: Any
itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSD2_cast: Any

def itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSD3_New(): ...

class itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSD3(itk.itkEuclideanDistancePointSetToPointSetMetricPython.itkEuclideanDistancePointSetToPointSetMetricv4PSD3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetPointSetSigma: Any = ...
    GetPointSetSigma: Any = ...
    SetEvaluationKNeighborhood: Any = ...
    GetEvaluationKNeighborhood: Any = ...
    SetUseAnisotropicCovariances: Any = ...
    GetUseAnisotropicCovariances: Any = ...
    UseAnisotropicCovariancesOn: Any = ...
    UseAnisotropicCovariancesOff: Any = ...
    SetCovarianceKNeighborhood: Any = ...
    GetCovarianceKNeighborhood: Any = ...
    SetKernelSigma: Any = ...
    GetKernelSigma: Any = ...
    GetLocalNeighborhoodValue: Any = ...
    GetLocalNeighborhoodValueAndDerivative: Any = ...
    InternalClone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSD3___New_orig__: Any
itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSD3_cast: Any

def itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSF2_New(): ...

class itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSF2(itk.itkEuclideanDistancePointSetToPointSetMetricPython.itkEuclideanDistancePointSetToPointSetMetricv4PSF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetPointSetSigma: Any = ...
    GetPointSetSigma: Any = ...
    SetEvaluationKNeighborhood: Any = ...
    GetEvaluationKNeighborhood: Any = ...
    SetUseAnisotropicCovariances: Any = ...
    GetUseAnisotropicCovariances: Any = ...
    UseAnisotropicCovariancesOn: Any = ...
    UseAnisotropicCovariancesOff: Any = ...
    SetCovarianceKNeighborhood: Any = ...
    GetCovarianceKNeighborhood: Any = ...
    SetKernelSigma: Any = ...
    GetKernelSigma: Any = ...
    GetLocalNeighborhoodValue: Any = ...
    GetLocalNeighborhoodValueAndDerivative: Any = ...
    InternalClone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSF2___New_orig__: Any
itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSF2_cast: Any

def itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSF3_New(): ...

class itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSF3(itk.itkEuclideanDistancePointSetToPointSetMetricPython.itkEuclideanDistancePointSetToPointSetMetricv4PSF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetPointSetSigma: Any = ...
    GetPointSetSigma: Any = ...
    SetEvaluationKNeighborhood: Any = ...
    GetEvaluationKNeighborhood: Any = ...
    SetUseAnisotropicCovariances: Any = ...
    GetUseAnisotropicCovariances: Any = ...
    UseAnisotropicCovariancesOn: Any = ...
    UseAnisotropicCovariancesOff: Any = ...
    SetCovarianceKNeighborhood: Any = ...
    GetCovarianceKNeighborhood: Any = ...
    SetKernelSigma: Any = ...
    GetKernelSigma: Any = ...
    GetLocalNeighborhoodValue: Any = ...
    GetLocalNeighborhoodValueAndDerivative: Any = ...
    InternalClone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSF3___New_orig__: Any
itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSF3_cast: Any

def itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSSS2_New(): ...

class itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSSS2(itk.itkEuclideanDistancePointSetToPointSetMetricPython.itkEuclideanDistancePointSetToPointSetMetricv4PSSS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetPointSetSigma: Any = ...
    GetPointSetSigma: Any = ...
    SetEvaluationKNeighborhood: Any = ...
    GetEvaluationKNeighborhood: Any = ...
    SetUseAnisotropicCovariances: Any = ...
    GetUseAnisotropicCovariances: Any = ...
    UseAnisotropicCovariancesOn: Any = ...
    UseAnisotropicCovariancesOff: Any = ...
    SetCovarianceKNeighborhood: Any = ...
    GetCovarianceKNeighborhood: Any = ...
    SetKernelSigma: Any = ...
    GetKernelSigma: Any = ...
    GetLocalNeighborhoodValue: Any = ...
    GetLocalNeighborhoodValueAndDerivative: Any = ...
    InternalClone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSSS2___New_orig__: Any
itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSSS2_cast: Any

def itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSSS3_New(): ...

class itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSSS3(itk.itkEuclideanDistancePointSetToPointSetMetricPython.itkEuclideanDistancePointSetToPointSetMetricv4PSSS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetPointSetSigma: Any = ...
    GetPointSetSigma: Any = ...
    SetEvaluationKNeighborhood: Any = ...
    GetEvaluationKNeighborhood: Any = ...
    SetUseAnisotropicCovariances: Any = ...
    GetUseAnisotropicCovariances: Any = ...
    UseAnisotropicCovariancesOn: Any = ...
    UseAnisotropicCovariancesOff: Any = ...
    SetCovarianceKNeighborhood: Any = ...
    GetCovarianceKNeighborhood: Any = ...
    SetKernelSigma: Any = ...
    GetKernelSigma: Any = ...
    GetLocalNeighborhoodValue: Any = ...
    GetLocalNeighborhoodValueAndDerivative: Any = ...
    InternalClone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSSS3___New_orig__: Any
itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSSS3_cast: Any

def itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSUC2_New(): ...

class itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSUC2(itk.itkEuclideanDistancePointSetToPointSetMetricPython.itkEuclideanDistancePointSetToPointSetMetricv4PSUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetPointSetSigma: Any = ...
    GetPointSetSigma: Any = ...
    SetEvaluationKNeighborhood: Any = ...
    GetEvaluationKNeighborhood: Any = ...
    SetUseAnisotropicCovariances: Any = ...
    GetUseAnisotropicCovariances: Any = ...
    UseAnisotropicCovariancesOn: Any = ...
    UseAnisotropicCovariancesOff: Any = ...
    SetCovarianceKNeighborhood: Any = ...
    GetCovarianceKNeighborhood: Any = ...
    SetKernelSigma: Any = ...
    GetKernelSigma: Any = ...
    GetLocalNeighborhoodValue: Any = ...
    GetLocalNeighborhoodValueAndDerivative: Any = ...
    InternalClone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSUC2___New_orig__: Any
itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSUC2_cast: Any

def itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSUC3_New(): ...

class itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSUC3(itk.itkEuclideanDistancePointSetToPointSetMetricPython.itkEuclideanDistancePointSetToPointSetMetricv4PSUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetPointSetSigma: Any = ...
    GetPointSetSigma: Any = ...
    SetEvaluationKNeighborhood: Any = ...
    GetEvaluationKNeighborhood: Any = ...
    SetUseAnisotropicCovariances: Any = ...
    GetUseAnisotropicCovariances: Any = ...
    UseAnisotropicCovariancesOn: Any = ...
    UseAnisotropicCovariancesOff: Any = ...
    SetCovarianceKNeighborhood: Any = ...
    GetCovarianceKNeighborhood: Any = ...
    SetKernelSigma: Any = ...
    GetKernelSigma: Any = ...
    GetLocalNeighborhoodValue: Any = ...
    GetLocalNeighborhoodValueAndDerivative: Any = ...
    InternalClone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSUC3___New_orig__: Any
itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4PSUC3_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSD2_Superclass_Superclass(itk.itkOptimizerParameterScalesEstimatorPython.itkOptimizerParameterScalesEstimatorTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMetric: Any = ...
    SetTransformForward: Any = ...
    GetTransformForward: Any = ...
    SetVirtualDomainPointSet: Any = ...
    GetVirtualDomainPointSet: Any = ...
    SetCentralRegionRadius: Any = ...
    SetScalesSamplingStrategy: Any = ...
    SetStepScaleSamplingStrategy: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSD2_Superclass_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSD3_Superclass_Superclass(itk.itkOptimizerParameterScalesEstimatorPython.itkOptimizerParameterScalesEstimatorTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMetric: Any = ...
    SetTransformForward: Any = ...
    GetTransformForward: Any = ...
    SetVirtualDomainPointSet: Any = ...
    GetVirtualDomainPointSet: Any = ...
    SetCentralRegionRadius: Any = ...
    SetScalesSamplingStrategy: Any = ...
    SetStepScaleSamplingStrategy: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSD3_Superclass_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSF2_Superclass_Superclass(itk.itkOptimizerParameterScalesEstimatorPython.itkOptimizerParameterScalesEstimatorTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMetric: Any = ...
    SetTransformForward: Any = ...
    GetTransformForward: Any = ...
    SetVirtualDomainPointSet: Any = ...
    GetVirtualDomainPointSet: Any = ...
    SetCentralRegionRadius: Any = ...
    SetScalesSamplingStrategy: Any = ...
    SetStepScaleSamplingStrategy: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSF2_Superclass_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSF3_Superclass_Superclass(itk.itkOptimizerParameterScalesEstimatorPython.itkOptimizerParameterScalesEstimatorTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMetric: Any = ...
    SetTransformForward: Any = ...
    GetTransformForward: Any = ...
    SetVirtualDomainPointSet: Any = ...
    GetVirtualDomainPointSet: Any = ...
    SetCentralRegionRadius: Any = ...
    SetScalesSamplingStrategy: Any = ...
    SetStepScaleSamplingStrategy: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSF3_Superclass_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSSS2_Superclass_Superclass(itk.itkOptimizerParameterScalesEstimatorPython.itkOptimizerParameterScalesEstimatorTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMetric: Any = ...
    SetTransformForward: Any = ...
    GetTransformForward: Any = ...
    SetVirtualDomainPointSet: Any = ...
    GetVirtualDomainPointSet: Any = ...
    SetCentralRegionRadius: Any = ...
    SetScalesSamplingStrategy: Any = ...
    SetStepScaleSamplingStrategy: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSSS2_Superclass_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSSS3_Superclass_Superclass(itk.itkOptimizerParameterScalesEstimatorPython.itkOptimizerParameterScalesEstimatorTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMetric: Any = ...
    SetTransformForward: Any = ...
    GetTransformForward: Any = ...
    SetVirtualDomainPointSet: Any = ...
    GetVirtualDomainPointSet: Any = ...
    SetCentralRegionRadius: Any = ...
    SetScalesSamplingStrategy: Any = ...
    SetStepScaleSamplingStrategy: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSSS3_Superclass_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSUC2_Superclass_Superclass(itk.itkOptimizerParameterScalesEstimatorPython.itkOptimizerParameterScalesEstimatorTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMetric: Any = ...
    SetTransformForward: Any = ...
    GetTransformForward: Any = ...
    SetVirtualDomainPointSet: Any = ...
    GetVirtualDomainPointSet: Any = ...
    SetCentralRegionRadius: Any = ...
    SetScalesSamplingStrategy: Any = ...
    SetStepScaleSamplingStrategy: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSUC2_Superclass_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSUC3_Superclass_Superclass(itk.itkOptimizerParameterScalesEstimatorPython.itkOptimizerParameterScalesEstimatorTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMetric: Any = ...
    SetTransformForward: Any = ...
    GetTransformForward: Any = ...
    SetVirtualDomainPointSet: Any = ...
    GetVirtualDomainPointSet: Any = ...
    SetCentralRegionRadius: Any = ...
    SetScalesSamplingStrategy: Any = ...
    SetStepScaleSamplingStrategy: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSUC3_Superclass_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSD2_Superclass(itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSD2_Superclass_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetSmallParameterVariation: Any = ...
    GetSmallParameterVariation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSD2_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSD3_Superclass(itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSD3_Superclass_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetSmallParameterVariation: Any = ...
    GetSmallParameterVariation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSD3_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSF2_Superclass(itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSF2_Superclass_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetSmallParameterVariation: Any = ...
    GetSmallParameterVariation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSF2_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSF3_Superclass(itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSF3_Superclass_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetSmallParameterVariation: Any = ...
    GetSmallParameterVariation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSF3_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSSS2_Superclass(itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSSS2_Superclass_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetSmallParameterVariation: Any = ...
    GetSmallParameterVariation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSSS2_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSSS3_Superclass(itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSSS3_Superclass_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetSmallParameterVariation: Any = ...
    GetSmallParameterVariation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSSS3_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSUC2_Superclass(itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSUC2_Superclass_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetSmallParameterVariation: Any = ...
    GetSmallParameterVariation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSUC2_Superclass_cast: Any

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSUC3_Superclass(itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSUC3_Superclass_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetSmallParameterVariation: Any = ...
    GetSmallParameterVariation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSUC3_Superclass_cast: Any

def itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSD2_New(): ...

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSD2(itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSD2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSD2___New_orig__: Any
itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSD2_cast: Any

def itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSD3_New(): ...

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSD3(itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSD3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSD3___New_orig__: Any
itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSD3_cast: Any

def itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSF2_New(): ...

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSF2(itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSF2___New_orig__: Any
itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSF2_cast: Any

def itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSF3_New(): ...

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSF3(itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSF3___New_orig__: Any
itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSF3_cast: Any

def itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSSS2_New(): ...

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSSS2(itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSSS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSSS2___New_orig__: Any
itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSSS2_cast: Any

def itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSSS3_New(): ...

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSSS3(itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSSS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSSS3___New_orig__: Any
itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSSS3_cast: Any

def itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSUC2_New(): ...

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSUC2(itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSUC2___New_orig__: Any
itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSUC2_cast: Any

def itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSUC3_New(): ...

class itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSUC3(itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSUC3___New_orig__: Any
itkRegistrationParameterScalesFromPhysicalShiftJHCTPSTPSMPSUC3_cast: Any
