import itk.stdcomplexPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkJPEGImageIO_New(): ...

class itkJPEGImageIO(itk.ITKIOImageBaseBasePython.itkImageIOBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetQuality: Any = ...
    GetQuality: Any = ...
    SetProgressive: Any = ...
    GetProgressive: Any = ...
    ReadVolume: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkJPEGImageIO___New_orig__: Any
itkJPEGImageIO_cast: Any

def itkJPEGImageIOFactory_New(): ...

class itkJPEGImageIOFactory(itk.ITKCommonBasePython.itkObjectFactoryBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    FactoryNew: Any = ...
    RegisterOneFactory: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkJPEGImageIOFactory___New_orig__: Any
itkJPEGImageIOFactory_FactoryNew: Any
itkJPEGImageIOFactory_RegisterOneFactory: Any
itkJPEGImageIOFactory_cast: Any
