import itk.itkSamplePython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkKittlerIllingworthThresholdCalculatorHDF_New(): ...

class itkKittlerIllingworthThresholdCalculatorHDF(itk.itkHistogramThresholdCalculatorPython.itkHistogramThresholdCalculatorHDF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkKittlerIllingworthThresholdCalculatorHDF___New_orig__: Any
itkKittlerIllingworthThresholdCalculatorHDF_cast: Any

def itkKittlerIllingworthThresholdCalculatorHDSS_New(): ...

class itkKittlerIllingworthThresholdCalculatorHDSS(itk.itkHistogramThresholdCalculatorPython.itkHistogramThresholdCalculatorHDSS):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkKittlerIllingworthThresholdCalculatorHDSS___New_orig__: Any
itkKittlerIllingworthThresholdCalculatorHDSS_cast: Any

def itkKittlerIllingworthThresholdCalculatorHDUC_New(): ...

class itkKittlerIllingworthThresholdCalculatorHDUC(itk.itkHistogramThresholdCalculatorPython.itkHistogramThresholdCalculatorHDUC):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkKittlerIllingworthThresholdCalculatorHDUC___New_orig__: Any
itkKittlerIllingworthThresholdCalculatorHDUC_cast: Any

def itkKittlerIllingworthThresholdCalculatorHFF_New(): ...

class itkKittlerIllingworthThresholdCalculatorHFF(itk.itkHistogramThresholdCalculatorPython.itkHistogramThresholdCalculatorHFF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkKittlerIllingworthThresholdCalculatorHFF___New_orig__: Any
itkKittlerIllingworthThresholdCalculatorHFF_cast: Any

def itkKittlerIllingworthThresholdCalculatorHFSS_New(): ...

class itkKittlerIllingworthThresholdCalculatorHFSS(itk.itkHistogramThresholdCalculatorPython.itkHistogramThresholdCalculatorHFSS):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkKittlerIllingworthThresholdCalculatorHFSS___New_orig__: Any
itkKittlerIllingworthThresholdCalculatorHFSS_cast: Any

def itkKittlerIllingworthThresholdCalculatorHFUC_New(): ...

class itkKittlerIllingworthThresholdCalculatorHFUC(itk.itkHistogramThresholdCalculatorPython.itkHistogramThresholdCalculatorHFUC):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkKittlerIllingworthThresholdCalculatorHFUC___New_orig__: Any
itkKittlerIllingworthThresholdCalculatorHFUC_cast: Any

def kittler_illingworth_threshold_calculator(*args: Any, **kwargs: Any): ...
def kittler_illingworth_threshold_calculator_init_docstring() -> None: ...
