import itk.itkImageRegionPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkKdTreeBasedKmeansEstimatorKdTreeLSVF2_New(): ...

class itkKdTreeBasedKmeansEstimatorKdTreeLSVF2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOutput: Any = ...
    SetParameters: Any = ...
    GetParameters: Any = ...
    SetMaximumIteration: Any = ...
    GetMaximumIteration: Any = ...
    SetCentroidPositionChangesThreshold: Any = ...
    GetCentroidPositionChangesThreshold: Any = ...
    SetKdTree: Any = ...
    GetKdTree: Any = ...
    GetMeasurementVectorSize: Any = ...
    GetCurrentIteration: Any = ...
    GetCentroidPositionChanges: Any = ...
    StartOptimization: Any = ...
    SetUseClusterLabels: Any = ...
    GetUseClusterLabels: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkKdTreeBasedKmeansEstimatorKdTreeLSVF2___New_orig__: Any
itkKdTreeBasedKmeansEstimatorKdTreeLSVF2_cast: Any

def itkKdTreeBasedKmeansEstimatorKdTreeLSVF3_New(): ...

class itkKdTreeBasedKmeansEstimatorKdTreeLSVF3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOutput: Any = ...
    SetParameters: Any = ...
    GetParameters: Any = ...
    SetMaximumIteration: Any = ...
    GetMaximumIteration: Any = ...
    SetCentroidPositionChangesThreshold: Any = ...
    GetCentroidPositionChangesThreshold: Any = ...
    SetKdTree: Any = ...
    GetKdTree: Any = ...
    GetMeasurementVectorSize: Any = ...
    GetCurrentIteration: Any = ...
    GetCentroidPositionChanges: Any = ...
    StartOptimization: Any = ...
    SetUseClusterLabels: Any = ...
    GetUseClusterLabels: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkKdTreeBasedKmeansEstimatorKdTreeLSVF3___New_orig__: Any
itkKdTreeBasedKmeansEstimatorKdTreeLSVF3_cast: Any
