import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkImageSourceLM2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetOutput: Any = ...
    GraftOutput: Any = ...
    GraftNthOutput: Any = ...
    MakeOutput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageSourceLM2_cast: Any

class itkImageSourceLM3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetOutput: Any = ...
    GraftOutput: Any = ...
    GraftNthOutput: Any = ...
    MakeOutput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageSourceLM3_cast: Any

class itkImageToImageFilterIF2LM2(itkImageSourceLM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    PushBackInput: Any = ...
    PopBackInput: Any = ...
    PushFrontInput: Any = ...
    PopFrontInput: Any = ...
    SetCoordinateTolerance: Any = ...
    GetCoordinateTolerance: Any = ...
    SetDirectionTolerance: Any = ...
    GetDirectionTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToImageFilterIF2LM2_cast: Any

class itkImageToImageFilterIF3LM3(itkImageSourceLM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    PushBackInput: Any = ...
    PopBackInput: Any = ...
    PushFrontInput: Any = ...
    PopFrontInput: Any = ...
    SetCoordinateTolerance: Any = ...
    GetCoordinateTolerance: Any = ...
    SetDirectionTolerance: Any = ...
    GetDirectionTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToImageFilterIF3LM3_cast: Any

class itkImageToImageFilterISS2LM2(itkImageSourceLM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    PushBackInput: Any = ...
    PopBackInput: Any = ...
    PushFrontInput: Any = ...
    PopFrontInput: Any = ...
    SetCoordinateTolerance: Any = ...
    GetCoordinateTolerance: Any = ...
    SetDirectionTolerance: Any = ...
    GetDirectionTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToImageFilterISS2LM2_cast: Any

class itkImageToImageFilterISS3LM3(itkImageSourceLM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    PushBackInput: Any = ...
    PopBackInput: Any = ...
    PushFrontInput: Any = ...
    PopFrontInput: Any = ...
    SetCoordinateTolerance: Any = ...
    GetCoordinateTolerance: Any = ...
    SetDirectionTolerance: Any = ...
    GetDirectionTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToImageFilterISS3LM3_cast: Any

class itkImageToImageFilterIUC2LM2(itkImageSourceLM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    PushBackInput: Any = ...
    PopBackInput: Any = ...
    PushFrontInput: Any = ...
    PopFrontInput: Any = ...
    SetCoordinateTolerance: Any = ...
    GetCoordinateTolerance: Any = ...
    SetDirectionTolerance: Any = ...
    GetDirectionTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToImageFilterIUC2LM2_cast: Any

class itkImageToImageFilterIUC3LM3(itkImageSourceLM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    PushBackInput: Any = ...
    PopBackInput: Any = ...
    PushFrontInput: Any = ...
    PopFrontInput: Any = ...
    SetCoordinateTolerance: Any = ...
    GetCoordinateTolerance: Any = ...
    SetDirectionTolerance: Any = ...
    GetDirectionTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToImageFilterIUC3LM3_cast: Any

class itkImageToImageFilterLM2IF2(itk.itkImageSourcePython.itkImageSourceIF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    PushBackInput: Any = ...
    PopBackInput: Any = ...
    PushFrontInput: Any = ...
    PopFrontInput: Any = ...
    SetCoordinateTolerance: Any = ...
    GetCoordinateTolerance: Any = ...
    SetDirectionTolerance: Any = ...
    GetDirectionTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToImageFilterLM2IF2_cast: Any

class itkImageToImageFilterLM2IRGBUC2(itk.itkImageSourcePython.itkImageSourceIRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    PushBackInput: Any = ...
    PopBackInput: Any = ...
    PushFrontInput: Any = ...
    PopFrontInput: Any = ...
    SetCoordinateTolerance: Any = ...
    GetCoordinateTolerance: Any = ...
    SetDirectionTolerance: Any = ...
    GetDirectionTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToImageFilterLM2IRGBUC2_cast: Any

class itkImageToImageFilterLM2ISS2(itk.itkImageSourcePython.itkImageSourceISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    PushBackInput: Any = ...
    PopBackInput: Any = ...
    PushFrontInput: Any = ...
    PopFrontInput: Any = ...
    SetCoordinateTolerance: Any = ...
    GetCoordinateTolerance: Any = ...
    SetDirectionTolerance: Any = ...
    GetDirectionTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToImageFilterLM2ISS2_cast: Any

class itkImageToImageFilterLM2IUC2(itk.itkImageSourcePython.itkImageSourceIUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    PushBackInput: Any = ...
    PopBackInput: Any = ...
    PushFrontInput: Any = ...
    PopFrontInput: Any = ...
    SetCoordinateTolerance: Any = ...
    GetCoordinateTolerance: Any = ...
    SetDirectionTolerance: Any = ...
    GetDirectionTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToImageFilterLM2IUC2_cast: Any

class itkImageToImageFilterLM2LM2(itkImageSourceLM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    PushBackInput: Any = ...
    PopBackInput: Any = ...
    PushFrontInput: Any = ...
    PopFrontInput: Any = ...
    SetCoordinateTolerance: Any = ...
    GetCoordinateTolerance: Any = ...
    SetDirectionTolerance: Any = ...
    GetDirectionTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToImageFilterLM2LM2_cast: Any

class itkImageToImageFilterLM3IF3(itk.itkImageSourcePython.itkImageSourceIF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    PushBackInput: Any = ...
    PopBackInput: Any = ...
    PushFrontInput: Any = ...
    PopFrontInput: Any = ...
    SetCoordinateTolerance: Any = ...
    GetCoordinateTolerance: Any = ...
    SetDirectionTolerance: Any = ...
    GetDirectionTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToImageFilterLM3IF3_cast: Any

class itkImageToImageFilterLM3IRGBUC3(itk.itkImageSourcePython.itkImageSourceIRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    PushBackInput: Any = ...
    PopBackInput: Any = ...
    PushFrontInput: Any = ...
    PopFrontInput: Any = ...
    SetCoordinateTolerance: Any = ...
    GetCoordinateTolerance: Any = ...
    SetDirectionTolerance: Any = ...
    GetDirectionTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToImageFilterLM3IRGBUC3_cast: Any

class itkImageToImageFilterLM3ISS3(itk.itkImageSourcePython.itkImageSourceISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    PushBackInput: Any = ...
    PopBackInput: Any = ...
    PushFrontInput: Any = ...
    PopFrontInput: Any = ...
    SetCoordinateTolerance: Any = ...
    GetCoordinateTolerance: Any = ...
    SetDirectionTolerance: Any = ...
    GetDirectionTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToImageFilterLM3ISS3_cast: Any

class itkImageToImageFilterLM3IUC3(itk.itkImageSourcePython.itkImageSourceIUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    PushBackInput: Any = ...
    PopBackInput: Any = ...
    PushFrontInput: Any = ...
    PopFrontInput: Any = ...
    SetCoordinateTolerance: Any = ...
    GetCoordinateTolerance: Any = ...
    SetDirectionTolerance: Any = ...
    GetDirectionTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToImageFilterLM3IUC3_cast: Any

class itkImageToImageFilterLM3LM3(itkImageSourceLM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    PushBackInput: Any = ...
    PopBackInput: Any = ...
    PushFrontInput: Any = ...
    PopFrontInput: Any = ...
    SetCoordinateTolerance: Any = ...
    GetCoordinateTolerance: Any = ...
    SetDirectionTolerance: Any = ...
    GetDirectionTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToImageFilterLM3LM3_cast: Any

def itkLabelMap2_New(): ...

class itkLabelMap2(itk.itkImagePython.itkImageBase2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Allocate: Any = ...
    Graft: Any = ...
    HasLabel: Any = ...
    GetNthLabelObject: Any = ...
    GetPixel: Any = ...
    SetPixel: Any = ...
    AddPixel: Any = ...
    RemovePixel: Any = ...
    SetLine: Any = ...
    GetLabelObject: Any = ...
    AddLabelObject: Any = ...
    PushLabelObject: Any = ...
    RemoveLabelObject: Any = ...
    RemoveLabel: Any = ...
    ClearLabels: Any = ...
    GetNumberOfLabelObjects: Any = ...
    GetLabels: Any = ...
    GetLabelObjects: Any = ...
    GetBackgroundValue: Any = ...
    SetBackgroundValue: Any = ...
    PrintLabelObjects: Any = ...
    Optimize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __len__(self): ...
    def __getitem__(self, label: Any): ...
    def __iter__(self) -> Any: ...
    def __len__(self): ...
    def __getitem__(self, label: Any): ...
    def __iter__(self) -> Any: ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelMap2___New_orig__: Any
itkLabelMap2_cast: Any

def itkLabelMap3_New(): ...

class itkLabelMap3(itk.itkImagePython.itkImageBase3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Allocate: Any = ...
    Graft: Any = ...
    HasLabel: Any = ...
    GetNthLabelObject: Any = ...
    GetPixel: Any = ...
    SetPixel: Any = ...
    AddPixel: Any = ...
    RemovePixel: Any = ...
    SetLine: Any = ...
    GetLabelObject: Any = ...
    AddLabelObject: Any = ...
    PushLabelObject: Any = ...
    RemoveLabelObject: Any = ...
    RemoveLabel: Any = ...
    ClearLabels: Any = ...
    GetNumberOfLabelObjects: Any = ...
    GetLabels: Any = ...
    GetLabelObjects: Any = ...
    GetBackgroundValue: Any = ...
    SetBackgroundValue: Any = ...
    PrintLabelObjects: Any = ...
    Optimize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def __len__(self): ...
    def __getitem__(self, label: Any): ...
    def __iter__(self) -> Any: ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelMap3___New_orig__: Any
itkLabelMap3_cast: Any

def image_source(*args: Any, **kwargs: Any): ...
def image_source_init_docstring() -> None: ...
def image_to_image_filter(*args: Any, **kwargs: Any): ...
def image_to_image_filter_init_docstring() -> None: ...
