import itk.itkScanlineFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkLabelContourImageFilterIF2IF2_New(): ...

class itkLabelContourImageFilterIF2IF2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelContourImageFilterIF2IF2___New_orig__: Any
itkLabelContourImageFilterIF2IF2_cast: Any

def itkLabelContourImageFilterIF3IF3_New(): ...

class itkLabelContourImageFilterIF3IF3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelContourImageFilterIF3IF3___New_orig__: Any
itkLabelContourImageFilterIF3IF3_cast: Any

def itkLabelContourImageFilterISS2ISS2_New(): ...

class itkLabelContourImageFilterISS2ISS2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelContourImageFilterISS2ISS2___New_orig__: Any
itkLabelContourImageFilterISS2ISS2_cast: Any

def itkLabelContourImageFilterISS3ISS3_New(): ...

class itkLabelContourImageFilterISS3ISS3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelContourImageFilterISS3ISS3___New_orig__: Any
itkLabelContourImageFilterISS3ISS3_cast: Any

def itkLabelContourImageFilterIUC2IUC2_New(): ...

class itkLabelContourImageFilterIUC2IUC2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelContourImageFilterIUC2IUC2___New_orig__: Any
itkLabelContourImageFilterIUC2IUC2_cast: Any

def itkLabelContourImageFilterIUC3IUC3_New(): ...

class itkLabelContourImageFilterIUC3IUC3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelContourImageFilterIUC3IUC3___New_orig__: Any
itkLabelContourImageFilterIUC3IUC3_cast: Any

def label_contour_image_filter(*args: Any, **kwargs: Any): ...
def label_contour_image_filter_init_docstring() -> None: ...
