import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkLaplacianSharpeningImageFilterIF2IF2_New(): ...

class itkLaplacianSharpeningImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GenerateInputRequestedRegion: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLaplacianSharpeningImageFilterIF2IF2___New_orig__: Any
itkLaplacianSharpeningImageFilterIF2IF2_cast: Any

def itkLaplacianSharpeningImageFilterIF3IF3_New(): ...

class itkLaplacianSharpeningImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GenerateInputRequestedRegion: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLaplacianSharpeningImageFilterIF3IF3___New_orig__: Any
itkLaplacianSharpeningImageFilterIF3IF3_cast: Any

def itkLaplacianSharpeningImageFilterISS2ISS2_New(): ...

class itkLaplacianSharpeningImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GenerateInputRequestedRegion: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLaplacianSharpeningImageFilterISS2ISS2___New_orig__: Any
itkLaplacianSharpeningImageFilterISS2ISS2_cast: Any

def itkLaplacianSharpeningImageFilterISS3ISS3_New(): ...

class itkLaplacianSharpeningImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GenerateInputRequestedRegion: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLaplacianSharpeningImageFilterISS3ISS3___New_orig__: Any
itkLaplacianSharpeningImageFilterISS3ISS3_cast: Any

def itkLaplacianSharpeningImageFilterIUC2IUC2_New(): ...

class itkLaplacianSharpeningImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GenerateInputRequestedRegion: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLaplacianSharpeningImageFilterIUC2IUC2___New_orig__: Any
itkLaplacianSharpeningImageFilterIUC2IUC2_cast: Any

def itkLaplacianSharpeningImageFilterIUC3IUC3_New(): ...

class itkLaplacianSharpeningImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GenerateInputRequestedRegion: Any = ...
    UseImageSpacingOn: Any = ...
    UseImageSpacingOff: Any = ...
    SetUseImageSpacing: Any = ...
    GetUseImageSpacing: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLaplacianSharpeningImageFilterIUC3IUC3___New_orig__: Any
itkLaplacianSharpeningImageFilterIUC3IUC3_cast: Any

def laplacian_sharpening_image_filter(*args: Any, **kwargs: Any): ...
def laplacian_sharpening_image_filter_init_docstring() -> None: ...
