import itk.itkLabelMapFilterPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkLabelMapContourOverlayImageFilterLM2IUC2IRGBUC2_New(): ...

class itkLabelMapContourOverlayImageFilterLM2IUC2IRGBUC2(itk.itkLabelMapFilterPython.itkLabelMapFilterLM2IRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    PLAIN: Any = ...
    CONTOUR: Any = ...
    SLICE_CONTOUR: Any = ...
    HIGH_LABEL_ON_TOP: Any = ...
    LOW_LABEL_ON_TOP: Any = ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetOpacity: Any = ...
    GetOpacity: Any = ...
    SetType: Any = ...
    GetType: Any = ...
    SetPriority: Any = ...
    GetPriority: Any = ...
    SetDilationRadius: Any = ...
    GetDilationRadius: Any = ...
    SetContourThickness: Any = ...
    GetContourThickness: Any = ...
    SetSliceDimension: Any = ...
    GetSliceDimension: Any = ...
    SetFunctor: Any = ...
    GetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelMapContourOverlayImageFilterLM2IUC2IRGBUC2___New_orig__: Any
itkLabelMapContourOverlayImageFilterLM2IUC2IRGBUC2_cast: Any

def itkLabelMapContourOverlayImageFilterLM3IUC3IRGBUC3_New(): ...

class itkLabelMapContourOverlayImageFilterLM3IUC3IRGBUC3(itk.itkLabelMapFilterPython.itkLabelMapFilterLM3IRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    PLAIN: Any = ...
    CONTOUR: Any = ...
    SLICE_CONTOUR: Any = ...
    HIGH_LABEL_ON_TOP: Any = ...
    LOW_LABEL_ON_TOP: Any = ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetOpacity: Any = ...
    GetOpacity: Any = ...
    SetType: Any = ...
    GetType: Any = ...
    SetPriority: Any = ...
    GetPriority: Any = ...
    SetDilationRadius: Any = ...
    GetDilationRadius: Any = ...
    SetContourThickness: Any = ...
    GetContourThickness: Any = ...
    SetSliceDimension: Any = ...
    GetSliceDimension: Any = ...
    SetFunctor: Any = ...
    GetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelMapContourOverlayImageFilterLM3IUC3IRGBUC3___New_orig__: Any
itkLabelMapContourOverlayImageFilterLM3IUC3IRGBUC3_cast: Any

def label_map_contour_overlay_image_filter(*args: Any, **kwargs: Any): ...
def label_map_contour_overlay_image_filter_init_docstring() -> None: ...
