import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkLabelMapToBinaryImageFilterLM2IUC2_New(): ...

class itkLabelMapToBinaryImageFilterLM2IUC2(itk.itkLabelMapFilterPython.itkLabelMapFilterLM2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundImage: Any = ...
    GetBackgroundImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelMapToBinaryImageFilterLM2IUC2___New_orig__: Any
itkLabelMapToBinaryImageFilterLM2IUC2_cast: Any

def itkLabelMapToBinaryImageFilterLM3IUC3_New(): ...

class itkLabelMapToBinaryImageFilterLM3IUC3(itk.itkLabelMapFilterPython.itkLabelMapFilterLM3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundImage: Any = ...
    GetBackgroundImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelMapToBinaryImageFilterLM3IUC3___New_orig__: Any
itkLabelMapToBinaryImageFilterLM3IUC3_cast: Any

def label_map_to_binary_image_filter(*args: Any, **kwargs: Any): ...
def label_map_to_binary_image_filter_init_docstring() -> None: ...
