import itk.vnl_vector_refPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkListSampleVF2_New(): ...

class itkListSampleVF2(itk.itkSamplePython.itkSampleVF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Resize: Any = ...
    Clear: Any = ...
    PushBack: Any = ...
    SetMeasurement: Any = ...
    SetMeasurementVector: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkListSampleVF2___New_orig__: Any
itkListSampleVF2_cast: Any

def itkListSampleVF3_New(): ...

class itkListSampleVF3(itk.itkSamplePython.itkSampleVF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Resize: Any = ...
    Clear: Any = ...
    PushBack: Any = ...
    SetMeasurement: Any = ...
    SetMeasurementVector: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkListSampleVF3___New_orig__: Any
itkListSampleVF3_cast: Any
