import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkLabelStatisticsKeepNObjectsImageFilterIUC2IF2_New(): ...

class itkLabelStatisticsKeepNObjectsImageFilterIUC2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetNumberOfObjects: Any = ...
    SetNumberOfObjects: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsKeepNObjectsImageFilterIUC2IF2___New_orig__: Any
itkLabelStatisticsKeepNObjectsImageFilterIUC2IF2_cast: Any

def itkLabelStatisticsKeepNObjectsImageFilterIUC2ISS2_New(): ...

class itkLabelStatisticsKeepNObjectsImageFilterIUC2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetNumberOfObjects: Any = ...
    SetNumberOfObjects: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsKeepNObjectsImageFilterIUC2ISS2___New_orig__: Any
itkLabelStatisticsKeepNObjectsImageFilterIUC2ISS2_cast: Any

def itkLabelStatisticsKeepNObjectsImageFilterIUC2IUC2_New(): ...

class itkLabelStatisticsKeepNObjectsImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetNumberOfObjects: Any = ...
    SetNumberOfObjects: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsKeepNObjectsImageFilterIUC2IUC2___New_orig__: Any
itkLabelStatisticsKeepNObjectsImageFilterIUC2IUC2_cast: Any

def itkLabelStatisticsKeepNObjectsImageFilterIUC3IF3_New(): ...

class itkLabelStatisticsKeepNObjectsImageFilterIUC3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetNumberOfObjects: Any = ...
    SetNumberOfObjects: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsKeepNObjectsImageFilterIUC3IF3___New_orig__: Any
itkLabelStatisticsKeepNObjectsImageFilterIUC3IF3_cast: Any

def itkLabelStatisticsKeepNObjectsImageFilterIUC3ISS3_New(): ...

class itkLabelStatisticsKeepNObjectsImageFilterIUC3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetNumberOfObjects: Any = ...
    SetNumberOfObjects: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsKeepNObjectsImageFilterIUC3ISS3___New_orig__: Any
itkLabelStatisticsKeepNObjectsImageFilterIUC3ISS3_cast: Any

def itkLabelStatisticsKeepNObjectsImageFilterIUC3IUC3_New(): ...

class itkLabelStatisticsKeepNObjectsImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetNumberOfObjects: Any = ...
    SetNumberOfObjects: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsKeepNObjectsImageFilterIUC3IUC3___New_orig__: Any
itkLabelStatisticsKeepNObjectsImageFilterIUC3IUC3_cast: Any

def label_statistics_keep_n_objects_image_filter(*args: Any, **kwargs: Any): ...
def label_statistics_keep_n_objects_image_filter_init_docstring() -> None: ...
