import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkLabelImageToStatisticsLabelMapFilterIUC2IF2LM2_New(): ...

class itkLabelImageToStatisticsLabelMapFilterIUC2IF2LM2(itk.ITKLabelMapBasePython.itkImageToImageFilterIUC2LM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetComputeFeretDiameter: Any = ...
    GetComputeFeretDiameter: Any = ...
    ComputeFeretDiameterOn: Any = ...
    ComputeFeretDiameterOff: Any = ...
    SetComputePerimeter: Any = ...
    GetComputePerimeter: Any = ...
    ComputePerimeterOn: Any = ...
    ComputePerimeterOff: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetComputeHistogram: Any = ...
    GetComputeHistogram: Any = ...
    ComputeHistogramOn: Any = ...
    ComputeHistogramOff: Any = ...
    SetNumberOfBins: Any = ...
    GetNumberOfBins: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelImageToStatisticsLabelMapFilterIUC2IF2LM2___New_orig__: Any
itkLabelImageToStatisticsLabelMapFilterIUC2IF2LM2_cast: Any

def itkLabelImageToStatisticsLabelMapFilterIUC2ISS2LM2_New(): ...

class itkLabelImageToStatisticsLabelMapFilterIUC2ISS2LM2(itk.ITKLabelMapBasePython.itkImageToImageFilterIUC2LM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetComputeFeretDiameter: Any = ...
    GetComputeFeretDiameter: Any = ...
    ComputeFeretDiameterOn: Any = ...
    ComputeFeretDiameterOff: Any = ...
    SetComputePerimeter: Any = ...
    GetComputePerimeter: Any = ...
    ComputePerimeterOn: Any = ...
    ComputePerimeterOff: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetComputeHistogram: Any = ...
    GetComputeHistogram: Any = ...
    ComputeHistogramOn: Any = ...
    ComputeHistogramOff: Any = ...
    SetNumberOfBins: Any = ...
    GetNumberOfBins: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelImageToStatisticsLabelMapFilterIUC2ISS2LM2___New_orig__: Any
itkLabelImageToStatisticsLabelMapFilterIUC2ISS2LM2_cast: Any

def itkLabelImageToStatisticsLabelMapFilterIUC2IUC2LM2_New(): ...

class itkLabelImageToStatisticsLabelMapFilterIUC2IUC2LM2(itk.ITKLabelMapBasePython.itkImageToImageFilterIUC2LM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetComputeFeretDiameter: Any = ...
    GetComputeFeretDiameter: Any = ...
    ComputeFeretDiameterOn: Any = ...
    ComputeFeretDiameterOff: Any = ...
    SetComputePerimeter: Any = ...
    GetComputePerimeter: Any = ...
    ComputePerimeterOn: Any = ...
    ComputePerimeterOff: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetComputeHistogram: Any = ...
    GetComputeHistogram: Any = ...
    ComputeHistogramOn: Any = ...
    ComputeHistogramOff: Any = ...
    SetNumberOfBins: Any = ...
    GetNumberOfBins: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelImageToStatisticsLabelMapFilterIUC2IUC2LM2___New_orig__: Any
itkLabelImageToStatisticsLabelMapFilterIUC2IUC2LM2_cast: Any

def itkLabelImageToStatisticsLabelMapFilterIUC3IF3LM3_New(): ...

class itkLabelImageToStatisticsLabelMapFilterIUC3IF3LM3(itk.ITKLabelMapBasePython.itkImageToImageFilterIUC3LM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetComputeFeretDiameter: Any = ...
    GetComputeFeretDiameter: Any = ...
    ComputeFeretDiameterOn: Any = ...
    ComputeFeretDiameterOff: Any = ...
    SetComputePerimeter: Any = ...
    GetComputePerimeter: Any = ...
    ComputePerimeterOn: Any = ...
    ComputePerimeterOff: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetComputeHistogram: Any = ...
    GetComputeHistogram: Any = ...
    ComputeHistogramOn: Any = ...
    ComputeHistogramOff: Any = ...
    SetNumberOfBins: Any = ...
    GetNumberOfBins: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelImageToStatisticsLabelMapFilterIUC3IF3LM3___New_orig__: Any
itkLabelImageToStatisticsLabelMapFilterIUC3IF3LM3_cast: Any

def itkLabelImageToStatisticsLabelMapFilterIUC3ISS3LM3_New(): ...

class itkLabelImageToStatisticsLabelMapFilterIUC3ISS3LM3(itk.ITKLabelMapBasePython.itkImageToImageFilterIUC3LM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetComputeFeretDiameter: Any = ...
    GetComputeFeretDiameter: Any = ...
    ComputeFeretDiameterOn: Any = ...
    ComputeFeretDiameterOff: Any = ...
    SetComputePerimeter: Any = ...
    GetComputePerimeter: Any = ...
    ComputePerimeterOn: Any = ...
    ComputePerimeterOff: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetComputeHistogram: Any = ...
    GetComputeHistogram: Any = ...
    ComputeHistogramOn: Any = ...
    ComputeHistogramOff: Any = ...
    SetNumberOfBins: Any = ...
    GetNumberOfBins: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelImageToStatisticsLabelMapFilterIUC3ISS3LM3___New_orig__: Any
itkLabelImageToStatisticsLabelMapFilterIUC3ISS3LM3_cast: Any

def itkLabelImageToStatisticsLabelMapFilterIUC3IUC3LM3_New(): ...

class itkLabelImageToStatisticsLabelMapFilterIUC3IUC3LM3(itk.ITKLabelMapBasePython.itkImageToImageFilterIUC3LM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetComputeFeretDiameter: Any = ...
    GetComputeFeretDiameter: Any = ...
    ComputeFeretDiameterOn: Any = ...
    ComputeFeretDiameterOff: Any = ...
    SetComputePerimeter: Any = ...
    GetComputePerimeter: Any = ...
    ComputePerimeterOn: Any = ...
    ComputePerimeterOff: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetComputeHistogram: Any = ...
    GetComputeHistogram: Any = ...
    ComputeHistogramOn: Any = ...
    ComputeHistogramOff: Any = ...
    SetNumberOfBins: Any = ...
    GetNumberOfBins: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelImageToStatisticsLabelMapFilterIUC3IUC3LM3___New_orig__: Any
itkLabelImageToStatisticsLabelMapFilterIUC3IUC3LM3_cast: Any

def label_image_to_statistics_label_map_filter(*args: Any, **kwargs: Any): ...
def label_image_to_statistics_label_map_filter_init_docstring() -> None: ...
