import itk.itkInPlaceImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkLabelOverlayImageFilterIUC2ISS2IRGBUC2_New(): ...

class itkLabelOverlayImageFilterIUC2ISS2IRGBUC2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC2ISS2IRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetLabelImage: Any = ...
    GetLabelImage: Any = ...
    SetOpacity: Any = ...
    GetOpacity: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    OutputPixelShouldHaveValueType: Any = ...
    OutputPixelShouldHaveBracketOperator: Any = ...
    ResetColors: Any = ...
    GetNumberOfColors: Any = ...
    AddColor: Any = ...
    GetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelOverlayImageFilterIUC2ISS2IRGBUC2___New_orig__: Any
itkLabelOverlayImageFilterIUC2ISS2IRGBUC2_cast: Any

def itkLabelOverlayImageFilterIUC2IUC2IRGBUC2_New(): ...

class itkLabelOverlayImageFilterIUC2IUC2IRGBUC2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC2IUC2IRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetLabelImage: Any = ...
    GetLabelImage: Any = ...
    SetOpacity: Any = ...
    GetOpacity: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    OutputPixelShouldHaveValueType: Any = ...
    OutputPixelShouldHaveBracketOperator: Any = ...
    ResetColors: Any = ...
    GetNumberOfColors: Any = ...
    AddColor: Any = ...
    GetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelOverlayImageFilterIUC2IUC2IRGBUC2___New_orig__: Any
itkLabelOverlayImageFilterIUC2IUC2IRGBUC2_cast: Any

def itkLabelOverlayImageFilterIUC2IUL2IRGBUC2_New(): ...

class itkLabelOverlayImageFilterIUC2IUL2IRGBUC2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC2IUL2IRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetLabelImage: Any = ...
    GetLabelImage: Any = ...
    SetOpacity: Any = ...
    GetOpacity: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    OutputPixelShouldHaveValueType: Any = ...
    OutputPixelShouldHaveBracketOperator: Any = ...
    ResetColors: Any = ...
    GetNumberOfColors: Any = ...
    AddColor: Any = ...
    GetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelOverlayImageFilterIUC2IUL2IRGBUC2___New_orig__: Any
itkLabelOverlayImageFilterIUC2IUL2IRGBUC2_cast: Any

def itkLabelOverlayImageFilterIUC3ISS3IRGBUC3_New(): ...

class itkLabelOverlayImageFilterIUC3ISS3IRGBUC3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC3ISS3IRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetLabelImage: Any = ...
    GetLabelImage: Any = ...
    SetOpacity: Any = ...
    GetOpacity: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    OutputPixelShouldHaveValueType: Any = ...
    OutputPixelShouldHaveBracketOperator: Any = ...
    ResetColors: Any = ...
    GetNumberOfColors: Any = ...
    AddColor: Any = ...
    GetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelOverlayImageFilterIUC3ISS3IRGBUC3___New_orig__: Any
itkLabelOverlayImageFilterIUC3ISS3IRGBUC3_cast: Any

def itkLabelOverlayImageFilterIUC3IUC3IRGBUC3_New(): ...

class itkLabelOverlayImageFilterIUC3IUC3IRGBUC3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC3IUC3IRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetLabelImage: Any = ...
    GetLabelImage: Any = ...
    SetOpacity: Any = ...
    GetOpacity: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    OutputPixelShouldHaveValueType: Any = ...
    OutputPixelShouldHaveBracketOperator: Any = ...
    ResetColors: Any = ...
    GetNumberOfColors: Any = ...
    AddColor: Any = ...
    GetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelOverlayImageFilterIUC3IUC3IRGBUC3___New_orig__: Any
itkLabelOverlayImageFilterIUC3IUC3IRGBUC3_cast: Any

def itkLabelOverlayImageFilterIUC3IUL3IRGBUC3_New(): ...

class itkLabelOverlayImageFilterIUC3IUL3IRGBUC3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC3IUL3IRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetLabelImage: Any = ...
    GetLabelImage: Any = ...
    SetOpacity: Any = ...
    GetOpacity: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    OutputPixelShouldHaveValueType: Any = ...
    OutputPixelShouldHaveBracketOperator: Any = ...
    ResetColors: Any = ...
    GetNumberOfColors: Any = ...
    AddColor: Any = ...
    GetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelOverlayImageFilterIUC3IUL3IRGBUC3___New_orig__: Any
itkLabelOverlayImageFilterIUC3IUL3IRGBUC3_cast: Any

def label_overlay_image_filter(*args: Any, **kwargs: Any): ...
def label_overlay_image_filter_init_docstring() -> None: ...
