import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkLabelStatisticsOpeningImageFilterIUC2IF2_New(): ...

class itkLabelStatisticsOpeningImageFilterIUC2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetLambda: Any = ...
    SetLambda: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsOpeningImageFilterIUC2IF2___New_orig__: Any
itkLabelStatisticsOpeningImageFilterIUC2IF2_cast: Any

def itkLabelStatisticsOpeningImageFilterIUC2ISS2_New(): ...

class itkLabelStatisticsOpeningImageFilterIUC2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetLambda: Any = ...
    SetLambda: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsOpeningImageFilterIUC2ISS2___New_orig__: Any
itkLabelStatisticsOpeningImageFilterIUC2ISS2_cast: Any

def itkLabelStatisticsOpeningImageFilterIUC2IUC2_New(): ...

class itkLabelStatisticsOpeningImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetLambda: Any = ...
    SetLambda: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsOpeningImageFilterIUC2IUC2___New_orig__: Any
itkLabelStatisticsOpeningImageFilterIUC2IUC2_cast: Any

def itkLabelStatisticsOpeningImageFilterIUC3IF3_New(): ...

class itkLabelStatisticsOpeningImageFilterIUC3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetLambda: Any = ...
    SetLambda: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsOpeningImageFilterIUC3IF3___New_orig__: Any
itkLabelStatisticsOpeningImageFilterIUC3IF3_cast: Any

def itkLabelStatisticsOpeningImageFilterIUC3ISS3_New(): ...

class itkLabelStatisticsOpeningImageFilterIUC3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetLambda: Any = ...
    SetLambda: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsOpeningImageFilterIUC3ISS3___New_orig__: Any
itkLabelStatisticsOpeningImageFilterIUC3ISS3_cast: Any

def itkLabelStatisticsOpeningImageFilterIUC3IUC3_New(): ...

class itkLabelStatisticsOpeningImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputEqualityComparableCheck: Any = ...
    IntConvertibleToInputCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetLambda: Any = ...
    SetLambda: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsOpeningImageFilterIUC3IUC3___New_orig__: Any
itkLabelStatisticsOpeningImageFilterIUC3IUC3_cast: Any

def label_statistics_opening_image_filter(*args: Any, **kwargs: Any): ...
def label_statistics_opening_image_filter_init_docstring() -> None: ...
