import itk.itkArrayPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkLinearInterpolateImageFunctionICVF22D_New(): ...

class itkLinearInterpolateImageFunctionICVF22D(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionICVF22D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLinearInterpolateImageFunctionICVF22D___New_orig__: Any
itkLinearInterpolateImageFunctionICVF22D_cast: Any

def itkLinearInterpolateImageFunctionICVF33D_New(): ...

class itkLinearInterpolateImageFunctionICVF33D(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionICVF33D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLinearInterpolateImageFunctionICVF33D___New_orig__: Any
itkLinearInterpolateImageFunctionICVF33D_cast: Any

def itkLinearInterpolateImageFunctionIF2D_New(): ...

class itkLinearInterpolateImageFunctionIF2D(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionIF2D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLinearInterpolateImageFunctionIF2D___New_orig__: Any
itkLinearInterpolateImageFunctionIF2D_cast: Any

def itkLinearInterpolateImageFunctionIF3D_New(): ...

class itkLinearInterpolateImageFunctionIF3D(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionIF3D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLinearInterpolateImageFunctionIF3D___New_orig__: Any
itkLinearInterpolateImageFunctionIF3D_cast: Any

def itkLinearInterpolateImageFunctionIRGBAUC2D_New(): ...

class itkLinearInterpolateImageFunctionIRGBAUC2D(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionIRGBAUC2D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLinearInterpolateImageFunctionIRGBAUC2D___New_orig__: Any
itkLinearInterpolateImageFunctionIRGBAUC2D_cast: Any

def itkLinearInterpolateImageFunctionIRGBAUC3D_New(): ...

class itkLinearInterpolateImageFunctionIRGBAUC3D(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionIRGBAUC3D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLinearInterpolateImageFunctionIRGBAUC3D___New_orig__: Any
itkLinearInterpolateImageFunctionIRGBAUC3D_cast: Any

def itkLinearInterpolateImageFunctionIRGBUC2D_New(): ...

class itkLinearInterpolateImageFunctionIRGBUC2D(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionIRGBUC2D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLinearInterpolateImageFunctionIRGBUC2D___New_orig__: Any
itkLinearInterpolateImageFunctionIRGBUC2D_cast: Any

def itkLinearInterpolateImageFunctionIRGBUC3D_New(): ...

class itkLinearInterpolateImageFunctionIRGBUC3D(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionIRGBUC3D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLinearInterpolateImageFunctionIRGBUC3D___New_orig__: Any
itkLinearInterpolateImageFunctionIRGBUC3D_cast: Any

def itkLinearInterpolateImageFunctionISS2D_New(): ...

class itkLinearInterpolateImageFunctionISS2D(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionISS2D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLinearInterpolateImageFunctionISS2D___New_orig__: Any
itkLinearInterpolateImageFunctionISS2D_cast: Any

def itkLinearInterpolateImageFunctionISS3D_New(): ...

class itkLinearInterpolateImageFunctionISS3D(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionISS3D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLinearInterpolateImageFunctionISS3D___New_orig__: Any
itkLinearInterpolateImageFunctionISS3D_cast: Any

def itkLinearInterpolateImageFunctionIUC2D_New(): ...

class itkLinearInterpolateImageFunctionIUC2D(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionIUC2D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLinearInterpolateImageFunctionIUC2D___New_orig__: Any
itkLinearInterpolateImageFunctionIUC2D_cast: Any

def itkLinearInterpolateImageFunctionIUC3D_New(): ...

class itkLinearInterpolateImageFunctionIUC3D(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionIUC3D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLinearInterpolateImageFunctionIUC3D___New_orig__: Any
itkLinearInterpolateImageFunctionIUC3D_cast: Any

def itkLinearInterpolateImageFunctionIVF22D_New(): ...

class itkLinearInterpolateImageFunctionIVF22D(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionIVF22D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLinearInterpolateImageFunctionIVF22D___New_orig__: Any
itkLinearInterpolateImageFunctionIVF22D_cast: Any

def itkLinearInterpolateImageFunctionIVF33D_New(): ...

class itkLinearInterpolateImageFunctionIVF33D(itk.itkInterpolateImageFunctionPython.itkInterpolateImageFunctionIVF33D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLinearInterpolateImageFunctionIVF33D___New_orig__: Any
itkLinearInterpolateImageFunctionIVF33D_cast: Any
