import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkLabelStatisticsImageFilterIF2ISS2_New(): ...

class itkLabelStatisticsImageFilterIF2ISS2(itk.itkImageSinkPython.itkImageSinkIF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetUseHistograms: Any = ...
    GetUseHistograms: Any = ...
    UseHistogramsOn: Any = ...
    UseHistogramsOff: Any = ...
    GetValidLabelValues: Any = ...
    SetLabelInput: Any = ...
    GetLabelInput: Any = ...
    HasLabel: Any = ...
    GetNumberOfObjects: Any = ...
    GetNumberOfLabels: Any = ...
    GetMinimum: Any = ...
    GetMaximum: Any = ...
    GetMean: Any = ...
    GetMedian: Any = ...
    GetSigma: Any = ...
    GetVariance: Any = ...
    GetBoundingBox: Any = ...
    GetRegion: Any = ...
    GetSum: Any = ...
    GetCount: Any = ...
    GetHistogram: Any = ...
    SetHistogramParameters: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsImageFilterIF2ISS2___New_orig__: Any
itkLabelStatisticsImageFilterIF2ISS2_cast: Any

def itkLabelStatisticsImageFilterIF2IUC2_New(): ...

class itkLabelStatisticsImageFilterIF2IUC2(itk.itkImageSinkPython.itkImageSinkIF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetUseHistograms: Any = ...
    GetUseHistograms: Any = ...
    UseHistogramsOn: Any = ...
    UseHistogramsOff: Any = ...
    GetValidLabelValues: Any = ...
    SetLabelInput: Any = ...
    GetLabelInput: Any = ...
    HasLabel: Any = ...
    GetNumberOfObjects: Any = ...
    GetNumberOfLabels: Any = ...
    GetMinimum: Any = ...
    GetMaximum: Any = ...
    GetMean: Any = ...
    GetMedian: Any = ...
    GetSigma: Any = ...
    GetVariance: Any = ...
    GetBoundingBox: Any = ...
    GetRegion: Any = ...
    GetSum: Any = ...
    GetCount: Any = ...
    GetHistogram: Any = ...
    SetHistogramParameters: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsImageFilterIF2IUC2___New_orig__: Any
itkLabelStatisticsImageFilterIF2IUC2_cast: Any

def itkLabelStatisticsImageFilterIF3ISS3_New(): ...

class itkLabelStatisticsImageFilterIF3ISS3(itk.itkImageSinkPython.itkImageSinkIF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetUseHistograms: Any = ...
    GetUseHistograms: Any = ...
    UseHistogramsOn: Any = ...
    UseHistogramsOff: Any = ...
    GetValidLabelValues: Any = ...
    SetLabelInput: Any = ...
    GetLabelInput: Any = ...
    HasLabel: Any = ...
    GetNumberOfObjects: Any = ...
    GetNumberOfLabels: Any = ...
    GetMinimum: Any = ...
    GetMaximum: Any = ...
    GetMean: Any = ...
    GetMedian: Any = ...
    GetSigma: Any = ...
    GetVariance: Any = ...
    GetBoundingBox: Any = ...
    GetRegion: Any = ...
    GetSum: Any = ...
    GetCount: Any = ...
    GetHistogram: Any = ...
    SetHistogramParameters: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsImageFilterIF3ISS3___New_orig__: Any
itkLabelStatisticsImageFilterIF3ISS3_cast: Any

def itkLabelStatisticsImageFilterIF3IUC3_New(): ...

class itkLabelStatisticsImageFilterIF3IUC3(itk.itkImageSinkPython.itkImageSinkIF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetUseHistograms: Any = ...
    GetUseHistograms: Any = ...
    UseHistogramsOn: Any = ...
    UseHistogramsOff: Any = ...
    GetValidLabelValues: Any = ...
    SetLabelInput: Any = ...
    GetLabelInput: Any = ...
    HasLabel: Any = ...
    GetNumberOfObjects: Any = ...
    GetNumberOfLabels: Any = ...
    GetMinimum: Any = ...
    GetMaximum: Any = ...
    GetMean: Any = ...
    GetMedian: Any = ...
    GetSigma: Any = ...
    GetVariance: Any = ...
    GetBoundingBox: Any = ...
    GetRegion: Any = ...
    GetSum: Any = ...
    GetCount: Any = ...
    GetHistogram: Any = ...
    SetHistogramParameters: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsImageFilterIF3IUC3___New_orig__: Any
itkLabelStatisticsImageFilterIF3IUC3_cast: Any

def itkLabelStatisticsImageFilterISS2ISS2_New(): ...

class itkLabelStatisticsImageFilterISS2ISS2(itk.itkImageSinkPython.itkImageSinkISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetUseHistograms: Any = ...
    GetUseHistograms: Any = ...
    UseHistogramsOn: Any = ...
    UseHistogramsOff: Any = ...
    GetValidLabelValues: Any = ...
    SetLabelInput: Any = ...
    GetLabelInput: Any = ...
    HasLabel: Any = ...
    GetNumberOfObjects: Any = ...
    GetNumberOfLabels: Any = ...
    GetMinimum: Any = ...
    GetMaximum: Any = ...
    GetMean: Any = ...
    GetMedian: Any = ...
    GetSigma: Any = ...
    GetVariance: Any = ...
    GetBoundingBox: Any = ...
    GetRegion: Any = ...
    GetSum: Any = ...
    GetCount: Any = ...
    GetHistogram: Any = ...
    SetHistogramParameters: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsImageFilterISS2ISS2___New_orig__: Any
itkLabelStatisticsImageFilterISS2ISS2_cast: Any

def itkLabelStatisticsImageFilterISS2IUC2_New(): ...

class itkLabelStatisticsImageFilterISS2IUC2(itk.itkImageSinkPython.itkImageSinkISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetUseHistograms: Any = ...
    GetUseHistograms: Any = ...
    UseHistogramsOn: Any = ...
    UseHistogramsOff: Any = ...
    GetValidLabelValues: Any = ...
    SetLabelInput: Any = ...
    GetLabelInput: Any = ...
    HasLabel: Any = ...
    GetNumberOfObjects: Any = ...
    GetNumberOfLabels: Any = ...
    GetMinimum: Any = ...
    GetMaximum: Any = ...
    GetMean: Any = ...
    GetMedian: Any = ...
    GetSigma: Any = ...
    GetVariance: Any = ...
    GetBoundingBox: Any = ...
    GetRegion: Any = ...
    GetSum: Any = ...
    GetCount: Any = ...
    GetHistogram: Any = ...
    SetHistogramParameters: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsImageFilterISS2IUC2___New_orig__: Any
itkLabelStatisticsImageFilterISS2IUC2_cast: Any

def itkLabelStatisticsImageFilterISS3ISS3_New(): ...

class itkLabelStatisticsImageFilterISS3ISS3(itk.itkImageSinkPython.itkImageSinkISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetUseHistograms: Any = ...
    GetUseHistograms: Any = ...
    UseHistogramsOn: Any = ...
    UseHistogramsOff: Any = ...
    GetValidLabelValues: Any = ...
    SetLabelInput: Any = ...
    GetLabelInput: Any = ...
    HasLabel: Any = ...
    GetNumberOfObjects: Any = ...
    GetNumberOfLabels: Any = ...
    GetMinimum: Any = ...
    GetMaximum: Any = ...
    GetMean: Any = ...
    GetMedian: Any = ...
    GetSigma: Any = ...
    GetVariance: Any = ...
    GetBoundingBox: Any = ...
    GetRegion: Any = ...
    GetSum: Any = ...
    GetCount: Any = ...
    GetHistogram: Any = ...
    SetHistogramParameters: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsImageFilterISS3ISS3___New_orig__: Any
itkLabelStatisticsImageFilterISS3ISS3_cast: Any

def itkLabelStatisticsImageFilterISS3IUC3_New(): ...

class itkLabelStatisticsImageFilterISS3IUC3(itk.itkImageSinkPython.itkImageSinkISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetUseHistograms: Any = ...
    GetUseHistograms: Any = ...
    UseHistogramsOn: Any = ...
    UseHistogramsOff: Any = ...
    GetValidLabelValues: Any = ...
    SetLabelInput: Any = ...
    GetLabelInput: Any = ...
    HasLabel: Any = ...
    GetNumberOfObjects: Any = ...
    GetNumberOfLabels: Any = ...
    GetMinimum: Any = ...
    GetMaximum: Any = ...
    GetMean: Any = ...
    GetMedian: Any = ...
    GetSigma: Any = ...
    GetVariance: Any = ...
    GetBoundingBox: Any = ...
    GetRegion: Any = ...
    GetSum: Any = ...
    GetCount: Any = ...
    GetHistogram: Any = ...
    SetHistogramParameters: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsImageFilterISS3IUC3___New_orig__: Any
itkLabelStatisticsImageFilterISS3IUC3_cast: Any

def itkLabelStatisticsImageFilterIUC2ISS2_New(): ...

class itkLabelStatisticsImageFilterIUC2ISS2(itk.itkImageSinkPython.itkImageSinkIUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetUseHistograms: Any = ...
    GetUseHistograms: Any = ...
    UseHistogramsOn: Any = ...
    UseHistogramsOff: Any = ...
    GetValidLabelValues: Any = ...
    SetLabelInput: Any = ...
    GetLabelInput: Any = ...
    HasLabel: Any = ...
    GetNumberOfObjects: Any = ...
    GetNumberOfLabels: Any = ...
    GetMinimum: Any = ...
    GetMaximum: Any = ...
    GetMean: Any = ...
    GetMedian: Any = ...
    GetSigma: Any = ...
    GetVariance: Any = ...
    GetBoundingBox: Any = ...
    GetRegion: Any = ...
    GetSum: Any = ...
    GetCount: Any = ...
    GetHistogram: Any = ...
    SetHistogramParameters: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsImageFilterIUC2ISS2___New_orig__: Any
itkLabelStatisticsImageFilterIUC2ISS2_cast: Any

def itkLabelStatisticsImageFilterIUC2IUC2_New(): ...

class itkLabelStatisticsImageFilterIUC2IUC2(itk.itkImageSinkPython.itkImageSinkIUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetUseHistograms: Any = ...
    GetUseHistograms: Any = ...
    UseHistogramsOn: Any = ...
    UseHistogramsOff: Any = ...
    GetValidLabelValues: Any = ...
    SetLabelInput: Any = ...
    GetLabelInput: Any = ...
    HasLabel: Any = ...
    GetNumberOfObjects: Any = ...
    GetNumberOfLabels: Any = ...
    GetMinimum: Any = ...
    GetMaximum: Any = ...
    GetMean: Any = ...
    GetMedian: Any = ...
    GetSigma: Any = ...
    GetVariance: Any = ...
    GetBoundingBox: Any = ...
    GetRegion: Any = ...
    GetSum: Any = ...
    GetCount: Any = ...
    GetHistogram: Any = ...
    SetHistogramParameters: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsImageFilterIUC2IUC2___New_orig__: Any
itkLabelStatisticsImageFilterIUC2IUC2_cast: Any

def itkLabelStatisticsImageFilterIUC3ISS3_New(): ...

class itkLabelStatisticsImageFilterIUC3ISS3(itk.itkImageSinkPython.itkImageSinkIUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetUseHistograms: Any = ...
    GetUseHistograms: Any = ...
    UseHistogramsOn: Any = ...
    UseHistogramsOff: Any = ...
    GetValidLabelValues: Any = ...
    SetLabelInput: Any = ...
    GetLabelInput: Any = ...
    HasLabel: Any = ...
    GetNumberOfObjects: Any = ...
    GetNumberOfLabels: Any = ...
    GetMinimum: Any = ...
    GetMaximum: Any = ...
    GetMean: Any = ...
    GetMedian: Any = ...
    GetSigma: Any = ...
    GetVariance: Any = ...
    GetBoundingBox: Any = ...
    GetRegion: Any = ...
    GetSum: Any = ...
    GetCount: Any = ...
    GetHistogram: Any = ...
    SetHistogramParameters: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsImageFilterIUC3ISS3___New_orig__: Any
itkLabelStatisticsImageFilterIUC3ISS3_cast: Any

def itkLabelStatisticsImageFilterIUC3IUC3_New(): ...

class itkLabelStatisticsImageFilterIUC3IUC3(itk.itkImageSinkPython.itkImageSinkIUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetUseHistograms: Any = ...
    GetUseHistograms: Any = ...
    UseHistogramsOn: Any = ...
    UseHistogramsOff: Any = ...
    GetValidLabelValues: Any = ...
    SetLabelInput: Any = ...
    GetLabelInput: Any = ...
    HasLabel: Any = ...
    GetNumberOfObjects: Any = ...
    GetNumberOfLabels: Any = ...
    GetMinimum: Any = ...
    GetMaximum: Any = ...
    GetMean: Any = ...
    GetMedian: Any = ...
    GetSigma: Any = ...
    GetVariance: Any = ...
    GetBoundingBox: Any = ...
    GetRegion: Any = ...
    GetSum: Any = ...
    GetCount: Any = ...
    GetHistogram: Any = ...
    SetHistogramParameters: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelStatisticsImageFilterIUC3IUC3___New_orig__: Any
itkLabelStatisticsImageFilterIUC3IUC3_cast: Any

def label_statistics_image_filter(*args: Any, **kwargs: Any): ...
def label_statistics_image_filter_init_docstring() -> None: ...
