import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkLabelOverlapMeasuresImageFilterISS2_New(): ...

class itkLabelOverlapMeasuresImageFilterISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSourceImage: Any = ...
    SetTargetImage: Any = ...
    GetSourceImage: Any = ...
    GetTargetImage: Any = ...
    GetLabelSetMeasures: Any = ...
    GetTotalOverlap: Any = ...
    GetTargetOverlap: Any = ...
    GetUnionOverlap: Any = ...
    GetJaccardCoefficient: Any = ...
    GetMeanOverlap: Any = ...
    GetDiceCoefficient: Any = ...
    GetVolumeSimilarity: Any = ...
    GetFalseNegativeError: Any = ...
    GetFalsePositiveError: Any = ...
    Input1HasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelOverlapMeasuresImageFilterISS2___New_orig__: Any
itkLabelOverlapMeasuresImageFilterISS2_cast: Any

def itkLabelOverlapMeasuresImageFilterISS3_New(): ...

class itkLabelOverlapMeasuresImageFilterISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSourceImage: Any = ...
    SetTargetImage: Any = ...
    GetSourceImage: Any = ...
    GetTargetImage: Any = ...
    GetLabelSetMeasures: Any = ...
    GetTotalOverlap: Any = ...
    GetTargetOverlap: Any = ...
    GetUnionOverlap: Any = ...
    GetJaccardCoefficient: Any = ...
    GetMeanOverlap: Any = ...
    GetDiceCoefficient: Any = ...
    GetVolumeSimilarity: Any = ...
    GetFalseNegativeError: Any = ...
    GetFalsePositiveError: Any = ...
    Input1HasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelOverlapMeasuresImageFilterISS3___New_orig__: Any
itkLabelOverlapMeasuresImageFilterISS3_cast: Any

def itkLabelOverlapMeasuresImageFilterIUC2_New(): ...

class itkLabelOverlapMeasuresImageFilterIUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSourceImage: Any = ...
    SetTargetImage: Any = ...
    GetSourceImage: Any = ...
    GetTargetImage: Any = ...
    GetLabelSetMeasures: Any = ...
    GetTotalOverlap: Any = ...
    GetTargetOverlap: Any = ...
    GetUnionOverlap: Any = ...
    GetJaccardCoefficient: Any = ...
    GetMeanOverlap: Any = ...
    GetDiceCoefficient: Any = ...
    GetVolumeSimilarity: Any = ...
    GetFalseNegativeError: Any = ...
    GetFalsePositiveError: Any = ...
    Input1HasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelOverlapMeasuresImageFilterIUC2___New_orig__: Any
itkLabelOverlapMeasuresImageFilterIUC2_cast: Any

def itkLabelOverlapMeasuresImageFilterIUC3_New(): ...

class itkLabelOverlapMeasuresImageFilterIUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSourceImage: Any = ...
    SetTargetImage: Any = ...
    GetSourceImage: Any = ...
    GetTargetImage: Any = ...
    GetLabelSetMeasures: Any = ...
    GetTotalOverlap: Any = ...
    GetTargetOverlap: Any = ...
    GetUnionOverlap: Any = ...
    GetJaccardCoefficient: Any = ...
    GetMeanOverlap: Any = ...
    GetDiceCoefficient: Any = ...
    GetVolumeSimilarity: Any = ...
    GetFalseNegativeError: Any = ...
    GetFalsePositiveError: Any = ...
    Input1HasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelOverlapMeasuresImageFilterIUC3___New_orig__: Any
itkLabelOverlapMeasuresImageFilterIUC3_cast: Any

def label_overlap_measures_image_filter(*args: Any, **kwargs: Any): ...
def label_overlap_measures_image_filter_init_docstring() -> None: ...
