import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkLabelMapToLabelImageFilterLM2IUC2_New(): ...

class itkLabelMapToLabelImageFilterLM2IUC2(itk.itkLabelMapFilterPython.itkLabelMapFilterLM2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelMapToLabelImageFilterLM2IUC2___New_orig__: Any
itkLabelMapToLabelImageFilterLM2IUC2_cast: Any

def itkLabelMapToLabelImageFilterLM3IUC3_New(): ...

class itkLabelMapToLabelImageFilterLM3IUC3(itk.itkLabelMapFilterPython.itkLabelMapFilterLM3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLabelMapToLabelImageFilterLM3IUC3___New_orig__: Any
itkLabelMapToLabelImageFilterLM3IUC3_cast: Any

def label_map_to_label_image_filter(*args: Any, **kwargs: Any): ...
def label_map_to_label_image_filter_init_docstring() -> None: ...
