import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkLevelSetMotionRegistrationFilterIF2IF2IVF22_New(): ...

class itkLevelSetMotionRegistrationFilterIF2IF2IVF22(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIF2IF2IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    SetGradientMagnitudeThreshold: Any = ...
    GetGradientMagnitudeThreshold: Any = ...
    SetGradientSmoothingStandardDeviations: Any = ...
    GetGradientSmoothingStandardDeviations: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLevelSetMotionRegistrationFilterIF2IF2IVF22___New_orig__: Any
itkLevelSetMotionRegistrationFilterIF2IF2IVF22_cast: Any

def itkLevelSetMotionRegistrationFilterIF2IF2IVF32_New(): ...

class itkLevelSetMotionRegistrationFilterIF2IF2IVF32(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIF2IF2IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    SetGradientMagnitudeThreshold: Any = ...
    GetGradientMagnitudeThreshold: Any = ...
    SetGradientSmoothingStandardDeviations: Any = ...
    GetGradientSmoothingStandardDeviations: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLevelSetMotionRegistrationFilterIF2IF2IVF32___New_orig__: Any
itkLevelSetMotionRegistrationFilterIF2IF2IVF32_cast: Any

def itkLevelSetMotionRegistrationFilterIF2IF2IVF42_New(): ...

class itkLevelSetMotionRegistrationFilterIF2IF2IVF42(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIF2IF2IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    SetGradientMagnitudeThreshold: Any = ...
    GetGradientMagnitudeThreshold: Any = ...
    SetGradientSmoothingStandardDeviations: Any = ...
    GetGradientSmoothingStandardDeviations: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLevelSetMotionRegistrationFilterIF2IF2IVF42___New_orig__: Any
itkLevelSetMotionRegistrationFilterIF2IF2IVF42_cast: Any

def itkLevelSetMotionRegistrationFilterIF3IF3IVF23_New(): ...

class itkLevelSetMotionRegistrationFilterIF3IF3IVF23(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIF3IF3IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    SetGradientMagnitudeThreshold: Any = ...
    GetGradientMagnitudeThreshold: Any = ...
    SetGradientSmoothingStandardDeviations: Any = ...
    GetGradientSmoothingStandardDeviations: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLevelSetMotionRegistrationFilterIF3IF3IVF23___New_orig__: Any
itkLevelSetMotionRegistrationFilterIF3IF3IVF23_cast: Any

def itkLevelSetMotionRegistrationFilterIF3IF3IVF33_New(): ...

class itkLevelSetMotionRegistrationFilterIF3IF3IVF33(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIF3IF3IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    SetGradientMagnitudeThreshold: Any = ...
    GetGradientMagnitudeThreshold: Any = ...
    SetGradientSmoothingStandardDeviations: Any = ...
    GetGradientSmoothingStandardDeviations: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLevelSetMotionRegistrationFilterIF3IF3IVF33___New_orig__: Any
itkLevelSetMotionRegistrationFilterIF3IF3IVF33_cast: Any

def itkLevelSetMotionRegistrationFilterIF3IF3IVF43_New(): ...

class itkLevelSetMotionRegistrationFilterIF3IF3IVF43(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIF3IF3IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    SetGradientMagnitudeThreshold: Any = ...
    GetGradientMagnitudeThreshold: Any = ...
    SetGradientSmoothingStandardDeviations: Any = ...
    GetGradientSmoothingStandardDeviations: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLevelSetMotionRegistrationFilterIF3IF3IVF43___New_orig__: Any
itkLevelSetMotionRegistrationFilterIF3IF3IVF43_cast: Any

def itkLevelSetMotionRegistrationFilterISS2ISS2IVF22_New(): ...

class itkLevelSetMotionRegistrationFilterISS2ISS2IVF22(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterISS2ISS2IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    SetGradientMagnitudeThreshold: Any = ...
    GetGradientMagnitudeThreshold: Any = ...
    SetGradientSmoothingStandardDeviations: Any = ...
    GetGradientSmoothingStandardDeviations: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLevelSetMotionRegistrationFilterISS2ISS2IVF22___New_orig__: Any
itkLevelSetMotionRegistrationFilterISS2ISS2IVF22_cast: Any

def itkLevelSetMotionRegistrationFilterISS2ISS2IVF32_New(): ...

class itkLevelSetMotionRegistrationFilterISS2ISS2IVF32(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterISS2ISS2IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    SetGradientMagnitudeThreshold: Any = ...
    GetGradientMagnitudeThreshold: Any = ...
    SetGradientSmoothingStandardDeviations: Any = ...
    GetGradientSmoothingStandardDeviations: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLevelSetMotionRegistrationFilterISS2ISS2IVF32___New_orig__: Any
itkLevelSetMotionRegistrationFilterISS2ISS2IVF32_cast: Any

def itkLevelSetMotionRegistrationFilterISS2ISS2IVF42_New(): ...

class itkLevelSetMotionRegistrationFilterISS2ISS2IVF42(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterISS2ISS2IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    SetGradientMagnitudeThreshold: Any = ...
    GetGradientMagnitudeThreshold: Any = ...
    SetGradientSmoothingStandardDeviations: Any = ...
    GetGradientSmoothingStandardDeviations: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLevelSetMotionRegistrationFilterISS2ISS2IVF42___New_orig__: Any
itkLevelSetMotionRegistrationFilterISS2ISS2IVF42_cast: Any

def itkLevelSetMotionRegistrationFilterISS3ISS3IVF23_New(): ...

class itkLevelSetMotionRegistrationFilterISS3ISS3IVF23(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterISS3ISS3IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    SetGradientMagnitudeThreshold: Any = ...
    GetGradientMagnitudeThreshold: Any = ...
    SetGradientSmoothingStandardDeviations: Any = ...
    GetGradientSmoothingStandardDeviations: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLevelSetMotionRegistrationFilterISS3ISS3IVF23___New_orig__: Any
itkLevelSetMotionRegistrationFilterISS3ISS3IVF23_cast: Any

def itkLevelSetMotionRegistrationFilterISS3ISS3IVF33_New(): ...

class itkLevelSetMotionRegistrationFilterISS3ISS3IVF33(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterISS3ISS3IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    SetGradientMagnitudeThreshold: Any = ...
    GetGradientMagnitudeThreshold: Any = ...
    SetGradientSmoothingStandardDeviations: Any = ...
    GetGradientSmoothingStandardDeviations: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLevelSetMotionRegistrationFilterISS3ISS3IVF33___New_orig__: Any
itkLevelSetMotionRegistrationFilterISS3ISS3IVF33_cast: Any

def itkLevelSetMotionRegistrationFilterISS3ISS3IVF43_New(): ...

class itkLevelSetMotionRegistrationFilterISS3ISS3IVF43(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterISS3ISS3IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    SetGradientMagnitudeThreshold: Any = ...
    GetGradientMagnitudeThreshold: Any = ...
    SetGradientSmoothingStandardDeviations: Any = ...
    GetGradientSmoothingStandardDeviations: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLevelSetMotionRegistrationFilterISS3ISS3IVF43___New_orig__: Any
itkLevelSetMotionRegistrationFilterISS3ISS3IVF43_cast: Any

def itkLevelSetMotionRegistrationFilterIUC2IUC2IVF22_New(): ...

class itkLevelSetMotionRegistrationFilterIUC2IUC2IVF22(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIUC2IUC2IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    SetGradientMagnitudeThreshold: Any = ...
    GetGradientMagnitudeThreshold: Any = ...
    SetGradientSmoothingStandardDeviations: Any = ...
    GetGradientSmoothingStandardDeviations: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLevelSetMotionRegistrationFilterIUC2IUC2IVF22___New_orig__: Any
itkLevelSetMotionRegistrationFilterIUC2IUC2IVF22_cast: Any

def itkLevelSetMotionRegistrationFilterIUC2IUC2IVF32_New(): ...

class itkLevelSetMotionRegistrationFilterIUC2IUC2IVF32(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIUC2IUC2IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    SetGradientMagnitudeThreshold: Any = ...
    GetGradientMagnitudeThreshold: Any = ...
    SetGradientSmoothingStandardDeviations: Any = ...
    GetGradientSmoothingStandardDeviations: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLevelSetMotionRegistrationFilterIUC2IUC2IVF32___New_orig__: Any
itkLevelSetMotionRegistrationFilterIUC2IUC2IVF32_cast: Any

def itkLevelSetMotionRegistrationFilterIUC2IUC2IVF42_New(): ...

class itkLevelSetMotionRegistrationFilterIUC2IUC2IVF42(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIUC2IUC2IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    SetGradientMagnitudeThreshold: Any = ...
    GetGradientMagnitudeThreshold: Any = ...
    SetGradientSmoothingStandardDeviations: Any = ...
    GetGradientSmoothingStandardDeviations: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLevelSetMotionRegistrationFilterIUC2IUC2IVF42___New_orig__: Any
itkLevelSetMotionRegistrationFilterIUC2IUC2IVF42_cast: Any

def itkLevelSetMotionRegistrationFilterIUC3IUC3IVF23_New(): ...

class itkLevelSetMotionRegistrationFilterIUC3IUC3IVF23(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIUC3IUC3IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    SetGradientMagnitudeThreshold: Any = ...
    GetGradientMagnitudeThreshold: Any = ...
    SetGradientSmoothingStandardDeviations: Any = ...
    GetGradientSmoothingStandardDeviations: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLevelSetMotionRegistrationFilterIUC3IUC3IVF23___New_orig__: Any
itkLevelSetMotionRegistrationFilterIUC3IUC3IVF23_cast: Any

def itkLevelSetMotionRegistrationFilterIUC3IUC3IVF33_New(): ...

class itkLevelSetMotionRegistrationFilterIUC3IUC3IVF33(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIUC3IUC3IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    SetGradientMagnitudeThreshold: Any = ...
    GetGradientMagnitudeThreshold: Any = ...
    SetGradientSmoothingStandardDeviations: Any = ...
    GetGradientSmoothingStandardDeviations: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLevelSetMotionRegistrationFilterIUC3IUC3IVF33___New_orig__: Any
itkLevelSetMotionRegistrationFilterIUC3IUC3IVF33_cast: Any

def itkLevelSetMotionRegistrationFilterIUC3IUC3IVF43_New(): ...

class itkLevelSetMotionRegistrationFilterIUC3IUC3IVF43(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIUC3IUC3IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    SetGradientMagnitudeThreshold: Any = ...
    GetGradientMagnitudeThreshold: Any = ...
    SetGradientSmoothingStandardDeviations: Any = ...
    GetGradientSmoothingStandardDeviations: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLevelSetMotionRegistrationFilterIUC3IUC3IVF43___New_orig__: Any
itkLevelSetMotionRegistrationFilterIUC3IUC3IVF43_cast: Any

def level_set_motion_registration_filter(*args: Any, **kwargs: Any): ...
def level_set_motion_registration_filter_init_docstring() -> None: ...
