from itk.itkLabelObjectLinePython import *
from itk.itkLabelObjectPython import *
from itk.itkShapeLabelObjectPython import *
from itk.itkStatisticsLabelObjectPython import *
from itk.ITKLabelMapBasePython import *
from itk.itkLabelMapFilterPython import *
from itk.itkInPlaceLabelMapFilterPython import *
from itk.itkChangeRegionLabelMapFilterPython import *
from itk.itkAggregateLabelMapFilterPython import *
from itk.itkAutoCropLabelMapFilterPython import *
from itk.itkBinaryFillholeImageFilterPython import *
from itk.itkBinaryGrindPeakImageFilterPython import *
from itk.itkBinaryImageToLabelMapFilterPython import *
from itk.itkBinaryImageToShapeLabelMapFilterPython import *
from itk.itkBinaryImageToStatisticsLabelMapFilterPython import *
from itk.itkBinaryNotImageFilterPython import *
from itk.itkBinaryReconstructionByDilationImageFilterPython import *
from itk.itkBinaryReconstructionByErosionImageFilterPython import *
from itk.itkBinaryShapeKeepNObjectsImageFilterPython import *
from itk.itkBinaryShapeOpeningImageFilterPython import *
from itk.itkBinaryStatisticsKeepNObjectsImageFilterPython import *
from itk.itkBinaryStatisticsOpeningImageFilterPython import *
from itk.itkChangeLabelLabelMapFilterPython import *
from itk.itkCropLabelMapFilterPython import *
from itk.itkLabelImageToLabelMapFilterPython import *
from itk.itkLabelImageToShapeLabelMapFilterPython import *
from itk.itkLabelImageToStatisticsLabelMapFilterPython import *
from itk.itkLabelMapMaskImageFilterPython import *
from itk.itkLabelMapToBinaryImageFilterPython import *
from itk.itkLabelMapToLabelImageFilterPython import *
from itk.itkLabelSelectionLabelMapFilterPython import *
from itk.itkLabelShapeKeepNObjectsImageFilterPython import *
from itk.itkLabelShapeOpeningImageFilterPython import *
from itk.itkLabelStatisticsKeepNObjectsImageFilterPython import *
from itk.itkLabelStatisticsOpeningImageFilterPython import *
from itk.itkLabelUniqueLabelMapFilterPython import *
from itk.itkMergeLabelMapFilterPython import *
from itk.itkObjectByObjectLabelMapFilterPython import *
from itk.itkPadLabelMapFilterPython import *
from itk.itkRegionFromReferenceLabelMapFilterPython import *
from itk.itkRelabelLabelMapFilterPython import *
from itk.itkShapeKeepNObjectsLabelMapFilterPython import *
from itk.itkShapeLabelMapFilterPython import *
from itk.itkShapeOpeningLabelMapFilterPython import *
from itk.itkShapePositionLabelMapFilterPython import *
from itk.itkShapeRelabelImageFilterPython import *
from itk.itkShapeRelabelLabelMapFilterPython import *
from itk.itkShapeUniqueLabelMapFilterPython import *
from itk.itkShiftScaleLabelMapFilterPython import *
from itk.itkStatisticsKeepNObjectsLabelMapFilterPython import *
from itk.itkStatisticsLabelMapFilterPython import *
from itk.itkStatisticsOpeningLabelMapFilterPython import *
from itk.itkStatisticsPositionLabelMapFilterPython import *
from itk.itkStatisticsRelabelImageFilterPython import *
from itk.itkStatisticsRelabelLabelMapFilterPython import *
from itk.itkStatisticsUniqueLabelMapFilterPython import *
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

swig: Any
