import itk.itkSymmetricSecondRankTensorPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkMatrixOffsetTransformBaseD22_New(): ...

class itkMatrixOffsetTransformBaseD22(itk.itkTransformBasePython.itkTransformD22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIdentity: Any = ...
    SetMatrix: Any = ...
    GetMatrix: Any = ...
    SetOffset: Any = ...
    GetOffset: Any = ...
    SetCenter: Any = ...
    GetCenter: Any = ...
    SetTranslation: Any = ...
    GetTranslation: Any = ...
    Compose: Any = ...
    TransformVector: Any = ...
    TransformCovariantVector: Any = ...
    TransformDiffusionTensor3D: Any = ...
    TransformSymmetricSecondRankTensor: Any = ...
    GetInverse: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMatrixOffsetTransformBaseD22___New_orig__: Any
itkMatrixOffsetTransformBaseD22_cast: Any

def itkMatrixOffsetTransformBaseD33_New(): ...

class itkMatrixOffsetTransformBaseD33(itk.itkTransformBasePython.itkTransformD33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIdentity: Any = ...
    SetMatrix: Any = ...
    GetMatrix: Any = ...
    SetOffset: Any = ...
    GetOffset: Any = ...
    SetCenter: Any = ...
    GetCenter: Any = ...
    SetTranslation: Any = ...
    GetTranslation: Any = ...
    Compose: Any = ...
    TransformVector: Any = ...
    TransformCovariantVector: Any = ...
    TransformDiffusionTensor3D: Any = ...
    TransformSymmetricSecondRankTensor: Any = ...
    GetInverse: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMatrixOffsetTransformBaseD33___New_orig__: Any
itkMatrixOffsetTransformBaseD33_cast: Any

def itkMatrixOffsetTransformBaseF22_New(): ...

class itkMatrixOffsetTransformBaseF22(itk.itkTransformBasePython.itkTransformF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIdentity: Any = ...
    SetMatrix: Any = ...
    GetMatrix: Any = ...
    SetOffset: Any = ...
    GetOffset: Any = ...
    SetCenter: Any = ...
    GetCenter: Any = ...
    SetTranslation: Any = ...
    GetTranslation: Any = ...
    Compose: Any = ...
    TransformVector: Any = ...
    TransformCovariantVector: Any = ...
    TransformDiffusionTensor3D: Any = ...
    TransformSymmetricSecondRankTensor: Any = ...
    GetInverse: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMatrixOffsetTransformBaseF22___New_orig__: Any
itkMatrixOffsetTransformBaseF22_cast: Any

def itkMatrixOffsetTransformBaseF33_New(): ...

class itkMatrixOffsetTransformBaseF33(itk.itkTransformBasePython.itkTransformF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIdentity: Any = ...
    SetMatrix: Any = ...
    GetMatrix: Any = ...
    SetOffset: Any = ...
    GetOffset: Any = ...
    SetCenter: Any = ...
    GetCenter: Any = ...
    SetTranslation: Any = ...
    GetTranslation: Any = ...
    Compose: Any = ...
    TransformVector: Any = ...
    TransformCovariantVector: Any = ...
    TransformDiffusionTensor3D: Any = ...
    TransformSymmetricSecondRankTensor: Any = ...
    GetInverse: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMatrixOffsetTransformBaseF33___New_orig__: Any
itkMatrixOffsetTransformBaseF33_cast: Any
