import itk.itkCostFunctionPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkMeanSquaresImageToImageMetricIF2IF2_New(): ...

class itkMeanSquaresImageToImageMetricIF2IF2(itk.itkImageToImageMetricPython.itkImageToImageMetricIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMeanSquaresImageToImageMetricIF2IF2___New_orig__: Any
itkMeanSquaresImageToImageMetricIF2IF2_cast: Any

def itkMeanSquaresImageToImageMetricIF3IF3_New(): ...

class itkMeanSquaresImageToImageMetricIF3IF3(itk.itkImageToImageMetricPython.itkImageToImageMetricIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMeanSquaresImageToImageMetricIF3IF3___New_orig__: Any
itkMeanSquaresImageToImageMetricIF3IF3_cast: Any

def itkMeanSquaresImageToImageMetricISS2ISS2_New(): ...

class itkMeanSquaresImageToImageMetricISS2ISS2(itk.itkImageToImageMetricPython.itkImageToImageMetricISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMeanSquaresImageToImageMetricISS2ISS2___New_orig__: Any
itkMeanSquaresImageToImageMetricISS2ISS2_cast: Any

def itkMeanSquaresImageToImageMetricISS3ISS3_New(): ...

class itkMeanSquaresImageToImageMetricISS3ISS3(itk.itkImageToImageMetricPython.itkImageToImageMetricISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMeanSquaresImageToImageMetricISS3ISS3___New_orig__: Any
itkMeanSquaresImageToImageMetricISS3ISS3_cast: Any

def itkMeanSquaresImageToImageMetricIUC2IUC2_New(): ...

class itkMeanSquaresImageToImageMetricIUC2IUC2(itk.itkImageToImageMetricPython.itkImageToImageMetricIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMeanSquaresImageToImageMetricIUC2IUC2___New_orig__: Any
itkMeanSquaresImageToImageMetricIUC2IUC2_cast: Any

def itkMeanSquaresImageToImageMetricIUC3IUC3_New(): ...

class itkMeanSquaresImageToImageMetricIUC3IUC3(itk.itkImageToImageMetricPython.itkImageToImageMetricIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMeanSquaresImageToImageMetricIUC3IUC3___New_orig__: Any
itkMeanSquaresImageToImageMetricIUC3IUC3_cast: Any
