import itk.pyBasePython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkMeshIOFactory_New(): ...

class itkMeshIOFactory(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CreateMeshIO: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMeshIOFactory___New_orig__: Any
itkMeshIOFactory_CreateMeshIO: Any
itkMeshIOFactory_cast: Any
