import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkMedianImageFilterIF2IF2_New(): ...

class itkMedianImageFilterIF2IF2(itk.itkBoxImageFilterPython.itkBoxImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SameDimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputLessThanComparableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianImageFilterIF2IF2___New_orig__: Any
itkMedianImageFilterIF2IF2_cast: Any

def itkMedianImageFilterIF3IF3_New(): ...

class itkMedianImageFilterIF3IF3(itk.itkBoxImageFilterPython.itkBoxImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SameDimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputLessThanComparableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianImageFilterIF3IF3___New_orig__: Any
itkMedianImageFilterIF3IF3_cast: Any

def itkMedianImageFilterISS2ISS2_New(): ...

class itkMedianImageFilterISS2ISS2(itk.itkBoxImageFilterPython.itkBoxImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SameDimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputLessThanComparableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianImageFilterISS2ISS2___New_orig__: Any
itkMedianImageFilterISS2ISS2_cast: Any

def itkMedianImageFilterISS3ISS3_New(): ...

class itkMedianImageFilterISS3ISS3(itk.itkBoxImageFilterPython.itkBoxImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SameDimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputLessThanComparableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianImageFilterISS3ISS3___New_orig__: Any
itkMedianImageFilterISS3ISS3_cast: Any

def itkMedianImageFilterIUC2IUC2_New(): ...

class itkMedianImageFilterIUC2IUC2(itk.itkBoxImageFilterPython.itkBoxImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SameDimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputLessThanComparableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianImageFilterIUC2IUC2___New_orig__: Any
itkMedianImageFilterIUC2IUC2_cast: Any

def itkMedianImageFilterIUC3IUC3_New(): ...

class itkMedianImageFilterIUC3IUC3(itk.itkBoxImageFilterPython.itkBoxImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SameDimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputLessThanComparableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianImageFilterIUC3IUC3___New_orig__: Any
itkMedianImageFilterIUC3IUC3_cast: Any

def median_image_filter(*args: Any, **kwargs: Any): ...
def median_image_filter_init_docstring() -> None: ...
