from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkMathematicalMorphologyEnums:
    thisown: Any = ...
    Algorithm_BASIC: Any = ...
    Algorithm_HISTO: Any = ...
    Algorithm_ANCHOR: Any = ...
    Algorithm_VHGW: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
