import itk.itkFunctionBasePython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkMattesMutualInformationImageToImageMetricIF2IF2_New(): ...

class itkMattesMutualInformationImageToImageMetricIF2IF2(itk.itkImageToImageMetricPython.itkImageToImageMetricIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfHistogramBins: Any = ...
    GetNumberOfHistogramBins: Any = ...
    SetUseExplicitPDFDerivatives: Any = ...
    GetUseExplicitPDFDerivatives: Any = ...
    UseExplicitPDFDerivativesOn: Any = ...
    UseExplicitPDFDerivativesOff: Any = ...
    GetJointPDF: Any = ...
    GetJointPDFDerivatives: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMattesMutualInformationImageToImageMetricIF2IF2___New_orig__: Any
itkMattesMutualInformationImageToImageMetricIF2IF2_cast: Any

def itkMattesMutualInformationImageToImageMetricIF3IF3_New(): ...

class itkMattesMutualInformationImageToImageMetricIF3IF3(itk.itkImageToImageMetricPython.itkImageToImageMetricIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfHistogramBins: Any = ...
    GetNumberOfHistogramBins: Any = ...
    SetUseExplicitPDFDerivatives: Any = ...
    GetUseExplicitPDFDerivatives: Any = ...
    UseExplicitPDFDerivativesOn: Any = ...
    UseExplicitPDFDerivativesOff: Any = ...
    GetJointPDF: Any = ...
    GetJointPDFDerivatives: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMattesMutualInformationImageToImageMetricIF3IF3___New_orig__: Any
itkMattesMutualInformationImageToImageMetricIF3IF3_cast: Any

def itkMattesMutualInformationImageToImageMetricISS2ISS2_New(): ...

class itkMattesMutualInformationImageToImageMetricISS2ISS2(itk.itkImageToImageMetricPython.itkImageToImageMetricISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfHistogramBins: Any = ...
    GetNumberOfHistogramBins: Any = ...
    SetUseExplicitPDFDerivatives: Any = ...
    GetUseExplicitPDFDerivatives: Any = ...
    UseExplicitPDFDerivativesOn: Any = ...
    UseExplicitPDFDerivativesOff: Any = ...
    GetJointPDF: Any = ...
    GetJointPDFDerivatives: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMattesMutualInformationImageToImageMetricISS2ISS2___New_orig__: Any
itkMattesMutualInformationImageToImageMetricISS2ISS2_cast: Any

def itkMattesMutualInformationImageToImageMetricISS3ISS3_New(): ...

class itkMattesMutualInformationImageToImageMetricISS3ISS3(itk.itkImageToImageMetricPython.itkImageToImageMetricISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfHistogramBins: Any = ...
    GetNumberOfHistogramBins: Any = ...
    SetUseExplicitPDFDerivatives: Any = ...
    GetUseExplicitPDFDerivatives: Any = ...
    UseExplicitPDFDerivativesOn: Any = ...
    UseExplicitPDFDerivativesOff: Any = ...
    GetJointPDF: Any = ...
    GetJointPDFDerivatives: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMattesMutualInformationImageToImageMetricISS3ISS3___New_orig__: Any
itkMattesMutualInformationImageToImageMetricISS3ISS3_cast: Any

def itkMattesMutualInformationImageToImageMetricIUC2IUC2_New(): ...

class itkMattesMutualInformationImageToImageMetricIUC2IUC2(itk.itkImageToImageMetricPython.itkImageToImageMetricIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfHistogramBins: Any = ...
    GetNumberOfHistogramBins: Any = ...
    SetUseExplicitPDFDerivatives: Any = ...
    GetUseExplicitPDFDerivatives: Any = ...
    UseExplicitPDFDerivativesOn: Any = ...
    UseExplicitPDFDerivativesOff: Any = ...
    GetJointPDF: Any = ...
    GetJointPDFDerivatives: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMattesMutualInformationImageToImageMetricIUC2IUC2___New_orig__: Any
itkMattesMutualInformationImageToImageMetricIUC2IUC2_cast: Any

def itkMattesMutualInformationImageToImageMetricIUC3IUC3_New(): ...

class itkMattesMutualInformationImageToImageMetricIUC3IUC3(itk.itkImageToImageMetricPython.itkImageToImageMetricIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfHistogramBins: Any = ...
    GetNumberOfHistogramBins: Any = ...
    SetUseExplicitPDFDerivatives: Any = ...
    GetUseExplicitPDFDerivatives: Any = ...
    UseExplicitPDFDerivativesOn: Any = ...
    UseExplicitPDFDerivativesOff: Any = ...
    GetJointPDF: Any = ...
    GetJointPDFDerivatives: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMattesMutualInformationImageToImageMetricIUC3IUC3___New_orig__: Any
itkMattesMutualInformationImageToImageMetricIUC3IUC3_cast: Any
