import itk.itkImageRegionPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkMetaConverterBase2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ReadMeta: Any = ...
    WriteMeta: Any = ...
    MetaObjectToSpatialObject: Any = ...
    SpatialObjectToMetaObject: Any = ...
    SetWriteImagesInSeparateFile: Any = ...
    GetWriteImagesInSeparateFile: Any = ...
    WriteImagesInSeparateFileOn: Any = ...
    WriteImagesInSeparateFileOff: Any = ...

class itkMetaConverterBase3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ReadMeta: Any = ...
    WriteMeta: Any = ...
    MetaObjectToSpatialObject: Any = ...
    SpatialObjectToMetaObject: Any = ...
    SetWriteImagesInSeparateFile: Any = ...
    GetWriteImagesInSeparateFile: Any = ...
    WriteImagesInSeparateFileOn: Any = ...
    WriteImagesInSeparateFileOff: Any = ...
