import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkMultiResolutionPyramidImageFilterIF2IF2_New(): ...

class itkMultiResolutionPyramidImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfLevels: Any = ...
    GetNumberOfLevels: Any = ...
    SetSchedule: Any = ...
    GetSchedule: Any = ...
    SetStartingShrinkFactors: Any = ...
    GetStartingShrinkFactors: Any = ...
    IsScheduleDownwardDivisible: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateOutputRequestedRegion: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SetMaximumError: Any = ...
    GetMaximumError: Any = ...
    SetUseShrinkImageFilter: Any = ...
    GetUseShrinkImageFilter: Any = ...
    UseShrinkImageFilterOn: Any = ...
    UseShrinkImageFilterOff: Any = ...
    SameDimensionCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMultiResolutionPyramidImageFilterIF2IF2___New_orig__: Any
itkMultiResolutionPyramidImageFilterIF2IF2_IsScheduleDownwardDivisible: Any
itkMultiResolutionPyramidImageFilterIF2IF2_cast: Any

def itkMultiResolutionPyramidImageFilterIF3IF3_New(): ...

class itkMultiResolutionPyramidImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfLevels: Any = ...
    GetNumberOfLevels: Any = ...
    SetSchedule: Any = ...
    GetSchedule: Any = ...
    SetStartingShrinkFactors: Any = ...
    GetStartingShrinkFactors: Any = ...
    IsScheduleDownwardDivisible: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateOutputRequestedRegion: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SetMaximumError: Any = ...
    GetMaximumError: Any = ...
    SetUseShrinkImageFilter: Any = ...
    GetUseShrinkImageFilter: Any = ...
    UseShrinkImageFilterOn: Any = ...
    UseShrinkImageFilterOff: Any = ...
    SameDimensionCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMultiResolutionPyramidImageFilterIF3IF3___New_orig__: Any
itkMultiResolutionPyramidImageFilterIF3IF3_IsScheduleDownwardDivisible: Any
itkMultiResolutionPyramidImageFilterIF3IF3_cast: Any

def itkMultiResolutionPyramidImageFilterISS2ISS2_New(): ...

class itkMultiResolutionPyramidImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfLevels: Any = ...
    GetNumberOfLevels: Any = ...
    SetSchedule: Any = ...
    GetSchedule: Any = ...
    SetStartingShrinkFactors: Any = ...
    GetStartingShrinkFactors: Any = ...
    IsScheduleDownwardDivisible: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateOutputRequestedRegion: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SetMaximumError: Any = ...
    GetMaximumError: Any = ...
    SetUseShrinkImageFilter: Any = ...
    GetUseShrinkImageFilter: Any = ...
    UseShrinkImageFilterOn: Any = ...
    UseShrinkImageFilterOff: Any = ...
    SameDimensionCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMultiResolutionPyramidImageFilterISS2ISS2___New_orig__: Any
itkMultiResolutionPyramidImageFilterISS2ISS2_IsScheduleDownwardDivisible: Any
itkMultiResolutionPyramidImageFilterISS2ISS2_cast: Any

def itkMultiResolutionPyramidImageFilterISS3ISS3_New(): ...

class itkMultiResolutionPyramidImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfLevels: Any = ...
    GetNumberOfLevels: Any = ...
    SetSchedule: Any = ...
    GetSchedule: Any = ...
    SetStartingShrinkFactors: Any = ...
    GetStartingShrinkFactors: Any = ...
    IsScheduleDownwardDivisible: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateOutputRequestedRegion: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SetMaximumError: Any = ...
    GetMaximumError: Any = ...
    SetUseShrinkImageFilter: Any = ...
    GetUseShrinkImageFilter: Any = ...
    UseShrinkImageFilterOn: Any = ...
    UseShrinkImageFilterOff: Any = ...
    SameDimensionCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMultiResolutionPyramidImageFilterISS3ISS3___New_orig__: Any
itkMultiResolutionPyramidImageFilterISS3ISS3_IsScheduleDownwardDivisible: Any
itkMultiResolutionPyramidImageFilterISS3ISS3_cast: Any

def itkMultiResolutionPyramidImageFilterIUC2IUC2_New(): ...

class itkMultiResolutionPyramidImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfLevels: Any = ...
    GetNumberOfLevels: Any = ...
    SetSchedule: Any = ...
    GetSchedule: Any = ...
    SetStartingShrinkFactors: Any = ...
    GetStartingShrinkFactors: Any = ...
    IsScheduleDownwardDivisible: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateOutputRequestedRegion: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SetMaximumError: Any = ...
    GetMaximumError: Any = ...
    SetUseShrinkImageFilter: Any = ...
    GetUseShrinkImageFilter: Any = ...
    UseShrinkImageFilterOn: Any = ...
    UseShrinkImageFilterOff: Any = ...
    SameDimensionCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMultiResolutionPyramidImageFilterIUC2IUC2___New_orig__: Any
itkMultiResolutionPyramidImageFilterIUC2IUC2_IsScheduleDownwardDivisible: Any
itkMultiResolutionPyramidImageFilterIUC2IUC2_cast: Any

def itkMultiResolutionPyramidImageFilterIUC3IUC3_New(): ...

class itkMultiResolutionPyramidImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfLevels: Any = ...
    GetNumberOfLevels: Any = ...
    SetSchedule: Any = ...
    GetSchedule: Any = ...
    SetStartingShrinkFactors: Any = ...
    GetStartingShrinkFactors: Any = ...
    IsScheduleDownwardDivisible: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateOutputRequestedRegion: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SetMaximumError: Any = ...
    GetMaximumError: Any = ...
    SetUseShrinkImageFilter: Any = ...
    GetUseShrinkImageFilter: Any = ...
    UseShrinkImageFilterOn: Any = ...
    UseShrinkImageFilterOff: Any = ...
    SameDimensionCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMultiResolutionPyramidImageFilterIUC3IUC3___New_orig__: Any
itkMultiResolutionPyramidImageFilterIUC3IUC3_IsScheduleDownwardDivisible: Any
itkMultiResolutionPyramidImageFilterIUC3IUC3_cast: Any

def multi_resolution_pyramid_image_filter(*args: Any, **kwargs: Any): ...
def multi_resolution_pyramid_image_filter_init_docstring() -> None: ...
