import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkMinimumMaximumImageFilterIF2_New(): ...

class itkMinimumMaximumImageFilterIF2(itk.itkImageSinkPython.itkImageSinkIF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMinimumOutput: Any = ...
    GetMinimum: Any = ...
    GetMaximumOutput: Any = ...
    GetMaximum: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    LessThanComparableCheck: Any = ...
    GreaterThanComparableCheck: Any = ...
    OStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumMaximumImageFilterIF2___New_orig__: Any
itkMinimumMaximumImageFilterIF2_cast: Any

def itkMinimumMaximumImageFilterIF3_New(): ...

class itkMinimumMaximumImageFilterIF3(itk.itkImageSinkPython.itkImageSinkIF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMinimumOutput: Any = ...
    GetMinimum: Any = ...
    GetMaximumOutput: Any = ...
    GetMaximum: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    LessThanComparableCheck: Any = ...
    GreaterThanComparableCheck: Any = ...
    OStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumMaximumImageFilterIF3___New_orig__: Any
itkMinimumMaximumImageFilterIF3_cast: Any

def itkMinimumMaximumImageFilterISS2_New(): ...

class itkMinimumMaximumImageFilterISS2(itk.itkImageSinkPython.itkImageSinkISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMinimumOutput: Any = ...
    GetMinimum: Any = ...
    GetMaximumOutput: Any = ...
    GetMaximum: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    LessThanComparableCheck: Any = ...
    GreaterThanComparableCheck: Any = ...
    OStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumMaximumImageFilterISS2___New_orig__: Any
itkMinimumMaximumImageFilterISS2_cast: Any

def itkMinimumMaximumImageFilterISS3_New(): ...

class itkMinimumMaximumImageFilterISS3(itk.itkImageSinkPython.itkImageSinkISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMinimumOutput: Any = ...
    GetMinimum: Any = ...
    GetMaximumOutput: Any = ...
    GetMaximum: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    LessThanComparableCheck: Any = ...
    GreaterThanComparableCheck: Any = ...
    OStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumMaximumImageFilterISS3___New_orig__: Any
itkMinimumMaximumImageFilterISS3_cast: Any

def itkMinimumMaximumImageFilterIUC2_New(): ...

class itkMinimumMaximumImageFilterIUC2(itk.itkImageSinkPython.itkImageSinkIUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMinimumOutput: Any = ...
    GetMinimum: Any = ...
    GetMaximumOutput: Any = ...
    GetMaximum: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    LessThanComparableCheck: Any = ...
    GreaterThanComparableCheck: Any = ...
    OStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumMaximumImageFilterIUC2___New_orig__: Any
itkMinimumMaximumImageFilterIUC2_cast: Any

def itkMinimumMaximumImageFilterIUC3_New(): ...

class itkMinimumMaximumImageFilterIUC3(itk.itkImageSinkPython.itkImageSinkIUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMinimumOutput: Any = ...
    GetMinimum: Any = ...
    GetMaximumOutput: Any = ...
    GetMaximum: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    LessThanComparableCheck: Any = ...
    GreaterThanComparableCheck: Any = ...
    OStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumMaximumImageFilterIUC3___New_orig__: Any
itkMinimumMaximumImageFilterIUC3_cast: Any

def minimum_maximum_image_filter(*args: Any, **kwargs: Any): ...
def minimum_maximum_image_filter_init_docstring() -> None: ...
