from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkMatrixF22_New(): ...
def itkMatrixD22_New(): ...
def itkMatrixF23_New(): ...
def itkMatrixD23_New(): ...
def itkMatrixF24_New(): ...
def itkMatrixD24_New(): ...
def itkMatrixF32_New(): ...
def itkMatrixD32_New(): ...
def itkMatrixF33_New(): ...
def itkMatrixD33_New(): ...
def itkMatrixF34_New(): ...
def itkMatrixD34_New(): ...
def itkMatrixF42_New(): ...
def itkMatrixD42_New(): ...
def itkMatrixF43_New(): ...
def itkMatrixD43_New(): ...
def itkMatrixF44_New(): ...
def itkMatrixD44_New(): ...

class itkMatrixD22:
    thisown: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __imul__: Any = ...
    __mul__: Any = ...
    def __itruediv__(self, *args: Any): ...
    __idiv__: Any = ...
    def __truediv__(self, *args: Any): ...
    __div__: Any = ...
    __call__: Any = ...
    __GetVnlMatrix_orig__: Any = ...
    SetIdentity: Any = ...
    Fill: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetInverse: Any = ...
    GetTranspose: Any = ...
    def __init__(self, *args: Any) -> None: ...
    swap: Any = ...
    __swig_destroy__: Any = ...
    def GetVnlMatrix(self): ...

class itkMatrixD23:
    thisown: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __imul__: Any = ...
    __mul__: Any = ...
    def __itruediv__(self, *args: Any): ...
    __idiv__: Any = ...
    def __truediv__(self, *args: Any): ...
    __div__: Any = ...
    __call__: Any = ...
    __GetVnlMatrix_orig__: Any = ...
    SetIdentity: Any = ...
    Fill: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetInverse: Any = ...
    GetTranspose: Any = ...
    def __init__(self, *args: Any) -> None: ...
    swap: Any = ...
    __swig_destroy__: Any = ...
    def GetVnlMatrix(self): ...

class itkMatrixD24:
    thisown: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __imul__: Any = ...
    __mul__: Any = ...
    def __itruediv__(self, *args: Any): ...
    __idiv__: Any = ...
    def __truediv__(self, *args: Any): ...
    __div__: Any = ...
    __call__: Any = ...
    __GetVnlMatrix_orig__: Any = ...
    SetIdentity: Any = ...
    Fill: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetInverse: Any = ...
    GetTranspose: Any = ...
    def __init__(self, *args: Any) -> None: ...
    swap: Any = ...
    __swig_destroy__: Any = ...
    def GetVnlMatrix(self): ...

class itkMatrixD32:
    thisown: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __imul__: Any = ...
    __mul__: Any = ...
    def __itruediv__(self, *args: Any): ...
    __idiv__: Any = ...
    def __truediv__(self, *args: Any): ...
    __div__: Any = ...
    __call__: Any = ...
    __GetVnlMatrix_orig__: Any = ...
    SetIdentity: Any = ...
    Fill: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetInverse: Any = ...
    GetTranspose: Any = ...
    def __init__(self, *args: Any) -> None: ...
    swap: Any = ...
    __swig_destroy__: Any = ...
    def GetVnlMatrix(self): ...

class itkMatrixD33:
    thisown: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __imul__: Any = ...
    __mul__: Any = ...
    def __itruediv__(self, *args: Any): ...
    __idiv__: Any = ...
    def __truediv__(self, *args: Any): ...
    __div__: Any = ...
    __call__: Any = ...
    __GetVnlMatrix_orig__: Any = ...
    SetIdentity: Any = ...
    Fill: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetInverse: Any = ...
    GetTranspose: Any = ...
    def __init__(self, *args: Any) -> None: ...
    swap: Any = ...
    __swig_destroy__: Any = ...
    def GetVnlMatrix(self): ...

class itkMatrixD34:
    thisown: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __imul__: Any = ...
    __mul__: Any = ...
    def __itruediv__(self, *args: Any): ...
    __idiv__: Any = ...
    def __truediv__(self, *args: Any): ...
    __div__: Any = ...
    __call__: Any = ...
    __GetVnlMatrix_orig__: Any = ...
    SetIdentity: Any = ...
    Fill: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetInverse: Any = ...
    GetTranspose: Any = ...
    def __init__(self, *args: Any) -> None: ...
    swap: Any = ...
    __swig_destroy__: Any = ...
    def GetVnlMatrix(self): ...

class itkMatrixD42:
    thisown: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __imul__: Any = ...
    __mul__: Any = ...
    def __itruediv__(self, *args: Any): ...
    __idiv__: Any = ...
    def __truediv__(self, *args: Any): ...
    __div__: Any = ...
    __call__: Any = ...
    __GetVnlMatrix_orig__: Any = ...
    SetIdentity: Any = ...
    Fill: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetInverse: Any = ...
    GetTranspose: Any = ...
    def __init__(self, *args: Any) -> None: ...
    swap: Any = ...
    __swig_destroy__: Any = ...
    def GetVnlMatrix(self): ...

class itkMatrixD43:
    thisown: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __imul__: Any = ...
    __mul__: Any = ...
    def __itruediv__(self, *args: Any): ...
    __idiv__: Any = ...
    def __truediv__(self, *args: Any): ...
    __div__: Any = ...
    __call__: Any = ...
    __GetVnlMatrix_orig__: Any = ...
    SetIdentity: Any = ...
    Fill: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetInverse: Any = ...
    GetTranspose: Any = ...
    def __init__(self, *args: Any) -> None: ...
    swap: Any = ...
    __swig_destroy__: Any = ...
    def GetVnlMatrix(self): ...

class itkMatrixD44:
    thisown: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __imul__: Any = ...
    __mul__: Any = ...
    def __itruediv__(self, *args: Any): ...
    __idiv__: Any = ...
    def __truediv__(self, *args: Any): ...
    __div__: Any = ...
    __call__: Any = ...
    __GetVnlMatrix_orig__: Any = ...
    SetIdentity: Any = ...
    Fill: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetInverse: Any = ...
    GetTranspose: Any = ...
    def __init__(self, *args: Any) -> None: ...
    swap: Any = ...
    __swig_destroy__: Any = ...
    def GetVnlMatrix(self): ...

class itkMatrixF22:
    thisown: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __imul__: Any = ...
    __mul__: Any = ...
    def __itruediv__(self, *args: Any): ...
    __idiv__: Any = ...
    def __truediv__(self, *args: Any): ...
    __div__: Any = ...
    __call__: Any = ...
    __GetVnlMatrix_orig__: Any = ...
    SetIdentity: Any = ...
    Fill: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetInverse: Any = ...
    GetTranspose: Any = ...
    def __init__(self, *args: Any) -> None: ...
    swap: Any = ...
    __swig_destroy__: Any = ...
    def GetVnlMatrix(self): ...

class itkMatrixF23:
    thisown: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __imul__: Any = ...
    __mul__: Any = ...
    def __itruediv__(self, *args: Any): ...
    __idiv__: Any = ...
    def __truediv__(self, *args: Any): ...
    __div__: Any = ...
    __call__: Any = ...
    __GetVnlMatrix_orig__: Any = ...
    SetIdentity: Any = ...
    Fill: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetInverse: Any = ...
    GetTranspose: Any = ...
    def __init__(self, *args: Any) -> None: ...
    swap: Any = ...
    __swig_destroy__: Any = ...
    def GetVnlMatrix(self): ...

class itkMatrixF24:
    thisown: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __imul__: Any = ...
    __mul__: Any = ...
    def __itruediv__(self, *args: Any): ...
    __idiv__: Any = ...
    def __truediv__(self, *args: Any): ...
    __div__: Any = ...
    __call__: Any = ...
    __GetVnlMatrix_orig__: Any = ...
    SetIdentity: Any = ...
    Fill: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetInverse: Any = ...
    GetTranspose: Any = ...
    def __init__(self, *args: Any) -> None: ...
    swap: Any = ...
    __swig_destroy__: Any = ...
    def GetVnlMatrix(self): ...

class itkMatrixF32:
    thisown: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __imul__: Any = ...
    __mul__: Any = ...
    def __itruediv__(self, *args: Any): ...
    __idiv__: Any = ...
    def __truediv__(self, *args: Any): ...
    __div__: Any = ...
    __call__: Any = ...
    __GetVnlMatrix_orig__: Any = ...
    SetIdentity: Any = ...
    Fill: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetInverse: Any = ...
    GetTranspose: Any = ...
    def __init__(self, *args: Any) -> None: ...
    swap: Any = ...
    __swig_destroy__: Any = ...
    def GetVnlMatrix(self): ...

class itkMatrixF33:
    thisown: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __imul__: Any = ...
    __mul__: Any = ...
    def __itruediv__(self, *args: Any): ...
    __idiv__: Any = ...
    def __truediv__(self, *args: Any): ...
    __div__: Any = ...
    __call__: Any = ...
    __GetVnlMatrix_orig__: Any = ...
    SetIdentity: Any = ...
    Fill: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetInverse: Any = ...
    GetTranspose: Any = ...
    def __init__(self, *args: Any) -> None: ...
    swap: Any = ...
    __swig_destroy__: Any = ...
    def GetVnlMatrix(self): ...

class itkMatrixF34:
    thisown: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __imul__: Any = ...
    __mul__: Any = ...
    def __itruediv__(self, *args: Any): ...
    __idiv__: Any = ...
    def __truediv__(self, *args: Any): ...
    __div__: Any = ...
    __call__: Any = ...
    __GetVnlMatrix_orig__: Any = ...
    SetIdentity: Any = ...
    Fill: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetInverse: Any = ...
    GetTranspose: Any = ...
    def __init__(self, *args: Any) -> None: ...
    swap: Any = ...
    __swig_destroy__: Any = ...
    def GetVnlMatrix(self): ...

class itkMatrixF42:
    thisown: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __imul__: Any = ...
    __mul__: Any = ...
    def __itruediv__(self, *args: Any): ...
    __idiv__: Any = ...
    def __truediv__(self, *args: Any): ...
    __div__: Any = ...
    __call__: Any = ...
    __GetVnlMatrix_orig__: Any = ...
    SetIdentity: Any = ...
    Fill: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetInverse: Any = ...
    GetTranspose: Any = ...
    def __init__(self, *args: Any) -> None: ...
    swap: Any = ...
    __swig_destroy__: Any = ...
    def GetVnlMatrix(self): ...

class itkMatrixF43:
    thisown: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __imul__: Any = ...
    __mul__: Any = ...
    def __itruediv__(self, *args: Any): ...
    __idiv__: Any = ...
    def __truediv__(self, *args: Any): ...
    __div__: Any = ...
    __call__: Any = ...
    __GetVnlMatrix_orig__: Any = ...
    SetIdentity: Any = ...
    Fill: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetInverse: Any = ...
    GetTranspose: Any = ...
    def __init__(self, *args: Any) -> None: ...
    swap: Any = ...
    __swig_destroy__: Any = ...
    def GetVnlMatrix(self): ...

class itkMatrixF44:
    thisown: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __imul__: Any = ...
    __mul__: Any = ...
    def __itruediv__(self, *args: Any): ...
    __idiv__: Any = ...
    def __truediv__(self, *args: Any): ...
    __div__: Any = ...
    __call__: Any = ...
    __GetVnlMatrix_orig__: Any = ...
    SetIdentity: Any = ...
    Fill: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetInverse: Any = ...
    GetTranspose: Any = ...
    def __init__(self, *args: Any) -> None: ...
    swap: Any = ...
    __swig_destroy__: Any = ...
    def GetVnlMatrix(self): ...
