import itk.itkImageToImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkMinimumProjectionImageFilterIF2IF2_Superclass_New(): ...

class itkMinimumProjectionImageFilterIF2IF2_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumProjectionImageFilterIF2IF2_Superclass___New_orig__: Any
itkMinimumProjectionImageFilterIF2IF2_Superclass_cast: Any

def itkMinimumProjectionImageFilterIF3IF2_Superclass_New(): ...

class itkMinimumProjectionImageFilterIF3IF2_Superclass(itk.itkImageToImageFilterBPython.itkImageToImageFilterIF3IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumProjectionImageFilterIF3IF2_Superclass___New_orig__: Any
itkMinimumProjectionImageFilterIF3IF2_Superclass_cast: Any

def itkMinimumProjectionImageFilterIF3IF3_Superclass_New(): ...

class itkMinimumProjectionImageFilterIF3IF3_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumProjectionImageFilterIF3IF3_Superclass___New_orig__: Any
itkMinimumProjectionImageFilterIF3IF3_Superclass_cast: Any

def itkMinimumProjectionImageFilterISS2ISS2_Superclass_New(): ...

class itkMinimumProjectionImageFilterISS2ISS2_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumProjectionImageFilterISS2ISS2_Superclass___New_orig__: Any
itkMinimumProjectionImageFilterISS2ISS2_Superclass_cast: Any

def itkMinimumProjectionImageFilterISS3ISS2_Superclass_New(): ...

class itkMinimumProjectionImageFilterISS3ISS2_Superclass(itk.itkImageToImageFilterBPython.itkImageToImageFilterISS3ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumProjectionImageFilterISS3ISS2_Superclass___New_orig__: Any
itkMinimumProjectionImageFilterISS3ISS2_Superclass_cast: Any

def itkMinimumProjectionImageFilterISS3ISS3_Superclass_New(): ...

class itkMinimumProjectionImageFilterISS3ISS3_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumProjectionImageFilterISS3ISS3_Superclass___New_orig__: Any
itkMinimumProjectionImageFilterISS3ISS3_Superclass_cast: Any

def itkMinimumProjectionImageFilterIUC2IUC2_Superclass_New(): ...

class itkMinimumProjectionImageFilterIUC2IUC2_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumProjectionImageFilterIUC2IUC2_Superclass___New_orig__: Any
itkMinimumProjectionImageFilterIUC2IUC2_Superclass_cast: Any

def itkMinimumProjectionImageFilterIUC3IUC2_Superclass_New(): ...

class itkMinimumProjectionImageFilterIUC3IUC2_Superclass(itk.itkImageToImageFilterBPython.itkImageToImageFilterIUC3IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumProjectionImageFilterIUC3IUC2_Superclass___New_orig__: Any
itkMinimumProjectionImageFilterIUC3IUC2_Superclass_cast: Any

def itkMinimumProjectionImageFilterIUC3IUC3_Superclass_New(): ...

class itkMinimumProjectionImageFilterIUC3IUC3_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumProjectionImageFilterIUC3IUC3_Superclass___New_orig__: Any
itkMinimumProjectionImageFilterIUC3IUC3_Superclass_cast: Any

def itkMinimumProjectionImageFilterIF2IF2_New(): ...

class itkMinimumProjectionImageFilterIF2IF2(itkMinimumProjectionImageFilterIF2IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputPixelTypeGreaterThanComparable: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumProjectionImageFilterIF2IF2___New_orig__: Any
itkMinimumProjectionImageFilterIF2IF2_cast: Any

def itkMinimumProjectionImageFilterIF3IF2_New(): ...

class itkMinimumProjectionImageFilterIF3IF2(itkMinimumProjectionImageFilterIF3IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputPixelTypeGreaterThanComparable: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumProjectionImageFilterIF3IF2___New_orig__: Any
itkMinimumProjectionImageFilterIF3IF2_cast: Any

def itkMinimumProjectionImageFilterIF3IF3_New(): ...

class itkMinimumProjectionImageFilterIF3IF3(itkMinimumProjectionImageFilterIF3IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputPixelTypeGreaterThanComparable: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumProjectionImageFilterIF3IF3___New_orig__: Any
itkMinimumProjectionImageFilterIF3IF3_cast: Any

def itkMinimumProjectionImageFilterISS2ISS2_New(): ...

class itkMinimumProjectionImageFilterISS2ISS2(itkMinimumProjectionImageFilterISS2ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputPixelTypeGreaterThanComparable: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumProjectionImageFilterISS2ISS2___New_orig__: Any
itkMinimumProjectionImageFilterISS2ISS2_cast: Any

def itkMinimumProjectionImageFilterISS3ISS2_New(): ...

class itkMinimumProjectionImageFilterISS3ISS2(itkMinimumProjectionImageFilterISS3ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputPixelTypeGreaterThanComparable: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumProjectionImageFilterISS3ISS2___New_orig__: Any
itkMinimumProjectionImageFilterISS3ISS2_cast: Any

def itkMinimumProjectionImageFilterISS3ISS3_New(): ...

class itkMinimumProjectionImageFilterISS3ISS3(itkMinimumProjectionImageFilterISS3ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputPixelTypeGreaterThanComparable: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumProjectionImageFilterISS3ISS3___New_orig__: Any
itkMinimumProjectionImageFilterISS3ISS3_cast: Any

def itkMinimumProjectionImageFilterIUC2IUC2_New(): ...

class itkMinimumProjectionImageFilterIUC2IUC2(itkMinimumProjectionImageFilterIUC2IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputPixelTypeGreaterThanComparable: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumProjectionImageFilterIUC2IUC2___New_orig__: Any
itkMinimumProjectionImageFilterIUC2IUC2_cast: Any

def itkMinimumProjectionImageFilterIUC3IUC2_New(): ...

class itkMinimumProjectionImageFilterIUC3IUC2(itkMinimumProjectionImageFilterIUC3IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputPixelTypeGreaterThanComparable: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumProjectionImageFilterIUC3IUC2___New_orig__: Any
itkMinimumProjectionImageFilterIUC3IUC2_cast: Any

def itkMinimumProjectionImageFilterIUC3IUC3_New(): ...

class itkMinimumProjectionImageFilterIUC3IUC3(itkMinimumProjectionImageFilterIUC3IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputPixelTypeGreaterThanComparable: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumProjectionImageFilterIUC3IUC3___New_orig__: Any
itkMinimumProjectionImageFilterIUC3IUC3_cast: Any

def minimum_projection_image_filter(*args: Any, **kwargs: Any): ...
def minimum_projection_image_filter_init_docstring() -> None: ...
def projection_image_filter(*args: Any, **kwargs: Any): ...
def projection_image_filter_init_docstring() -> None: ...
