import itk.itkInPlaceImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkMaskImageFilterICF2ISS2ICF2_New(): ...

class itkMaskImageFilterICF2ISS2ICF2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICF2ISS2ICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterICF2ISS2ICF2___New_orig__: Any
itkMaskImageFilterICF2ISS2ICF2_cast: Any

def itkMaskImageFilterICF2IUC2ICF2_New(): ...

class itkMaskImageFilterICF2IUC2ICF2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICF2IUC2ICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterICF2IUC2ICF2___New_orig__: Any
itkMaskImageFilterICF2IUC2ICF2_cast: Any

def itkMaskImageFilterICF3ISS3ICF3_New(): ...

class itkMaskImageFilterICF3ISS3ICF3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICF3ISS3ICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterICF3ISS3ICF3___New_orig__: Any
itkMaskImageFilterICF3ISS3ICF3_cast: Any

def itkMaskImageFilterICF3IUC3ICF3_New(): ...

class itkMaskImageFilterICF3IUC3ICF3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICF3IUC3ICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterICF3IUC3ICF3___New_orig__: Any
itkMaskImageFilterICF3IUC3ICF3_cast: Any

def itkMaskImageFilterICVF22ISS2ICVF22_New(): ...

class itkMaskImageFilterICVF22ISS2ICVF22(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF22ISS2ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterICVF22ISS2ICVF22___New_orig__: Any
itkMaskImageFilterICVF22ISS2ICVF22_cast: Any

def itkMaskImageFilterICVF22IUC2ICVF22_New(): ...

class itkMaskImageFilterICVF22IUC2ICVF22(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF22IUC2ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterICVF22IUC2ICVF22___New_orig__: Any
itkMaskImageFilterICVF22IUC2ICVF22_cast: Any

def itkMaskImageFilterICVF23ISS3ICVF23_New(): ...

class itkMaskImageFilterICVF23ISS3ICVF23(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF23ISS3ICVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterICVF23ISS3ICVF23___New_orig__: Any
itkMaskImageFilterICVF23ISS3ICVF23_cast: Any

def itkMaskImageFilterICVF23IUC3ICVF23_New(): ...

class itkMaskImageFilterICVF23IUC3ICVF23(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF23IUC3ICVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterICVF23IUC3ICVF23___New_orig__: Any
itkMaskImageFilterICVF23IUC3ICVF23_cast: Any

def itkMaskImageFilterICVF32ISS2ICVF32_New(): ...

class itkMaskImageFilterICVF32ISS2ICVF32(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF32ISS2ICVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterICVF32ISS2ICVF32___New_orig__: Any
itkMaskImageFilterICVF32ISS2ICVF32_cast: Any

def itkMaskImageFilterICVF32IUC2ICVF32_New(): ...

class itkMaskImageFilterICVF32IUC2ICVF32(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF32IUC2ICVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterICVF32IUC2ICVF32___New_orig__: Any
itkMaskImageFilterICVF32IUC2ICVF32_cast: Any

def itkMaskImageFilterICVF33ISS3ICVF33_New(): ...

class itkMaskImageFilterICVF33ISS3ICVF33(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF33ISS3ICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterICVF33ISS3ICVF33___New_orig__: Any
itkMaskImageFilterICVF33ISS3ICVF33_cast: Any

def itkMaskImageFilterICVF33IUC3ICVF33_New(): ...

class itkMaskImageFilterICVF33IUC3ICVF33(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF33IUC3ICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterICVF33IUC3ICVF33___New_orig__: Any
itkMaskImageFilterICVF33IUC3ICVF33_cast: Any

def itkMaskImageFilterICVF42ISS2ICVF42_New(): ...

class itkMaskImageFilterICVF42ISS2ICVF42(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF42ISS2ICVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterICVF42ISS2ICVF42___New_orig__: Any
itkMaskImageFilterICVF42ISS2ICVF42_cast: Any

def itkMaskImageFilterICVF42IUC2ICVF42_New(): ...

class itkMaskImageFilterICVF42IUC2ICVF42(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF42IUC2ICVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterICVF42IUC2ICVF42___New_orig__: Any
itkMaskImageFilterICVF42IUC2ICVF42_cast: Any

def itkMaskImageFilterICVF43ISS3ICVF43_New(): ...

class itkMaskImageFilterICVF43ISS3ICVF43(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF43ISS3ICVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterICVF43ISS3ICVF43___New_orig__: Any
itkMaskImageFilterICVF43ISS3ICVF43_cast: Any

def itkMaskImageFilterICVF43IUC3ICVF43_New(): ...

class itkMaskImageFilterICVF43IUC3ICVF43(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF43IUC3ICVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterICVF43IUC3ICVF43___New_orig__: Any
itkMaskImageFilterICVF43IUC3ICVF43_cast: Any

def itkMaskImageFilterIF2ISS2IF2_New(): ...

class itkMaskImageFilterIF2ISS2IF2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIF2ISS2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIF2ISS2IF2___New_orig__: Any
itkMaskImageFilterIF2ISS2IF2_cast: Any

def itkMaskImageFilterIF2IUC2IF2_New(): ...

class itkMaskImageFilterIF2IUC2IF2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIF2IUC2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIF2IUC2IF2___New_orig__: Any
itkMaskImageFilterIF2IUC2IF2_cast: Any

def itkMaskImageFilterIF3ISS3IF3_New(): ...

class itkMaskImageFilterIF3ISS3IF3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIF3ISS3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIF3ISS3IF3___New_orig__: Any
itkMaskImageFilterIF3ISS3IF3_cast: Any

def itkMaskImageFilterIF3IUC3IF3_New(): ...

class itkMaskImageFilterIF3IUC3IF3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIF3IUC3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIF3IUC3IF3___New_orig__: Any
itkMaskImageFilterIF3IUC3IF3_cast: Any

def itkMaskImageFilterIRGBAUC2ISS2IRGBAUC2_New(): ...

class itkMaskImageFilterIRGBAUC2ISS2IRGBAUC2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIRGBAUC2ISS2IRGBAUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIRGBAUC2ISS2IRGBAUC2___New_orig__: Any
itkMaskImageFilterIRGBAUC2ISS2IRGBAUC2_cast: Any

def itkMaskImageFilterIRGBAUC2IUC2IRGBAUC2_New(): ...

class itkMaskImageFilterIRGBAUC2IUC2IRGBAUC2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIRGBAUC2IUC2IRGBAUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIRGBAUC2IUC2IRGBAUC2___New_orig__: Any
itkMaskImageFilterIRGBAUC2IUC2IRGBAUC2_cast: Any

def itkMaskImageFilterIRGBAUC3ISS3IRGBAUC3_New(): ...

class itkMaskImageFilterIRGBAUC3ISS3IRGBAUC3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIRGBAUC3ISS3IRGBAUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIRGBAUC3ISS3IRGBAUC3___New_orig__: Any
itkMaskImageFilterIRGBAUC3ISS3IRGBAUC3_cast: Any

def itkMaskImageFilterIRGBAUC3IUC3IRGBAUC3_New(): ...

class itkMaskImageFilterIRGBAUC3IUC3IRGBAUC3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIRGBAUC3IUC3IRGBAUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIRGBAUC3IUC3IRGBAUC3___New_orig__: Any
itkMaskImageFilterIRGBAUC3IUC3IRGBAUC3_cast: Any

def itkMaskImageFilterIRGBUC2ISS2IRGBUC2_New(): ...

class itkMaskImageFilterIRGBUC2ISS2IRGBUC2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIRGBUC2ISS2IRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIRGBUC2ISS2IRGBUC2___New_orig__: Any
itkMaskImageFilterIRGBUC2ISS2IRGBUC2_cast: Any

def itkMaskImageFilterIRGBUC2IUC2IRGBUC2_New(): ...

class itkMaskImageFilterIRGBUC2IUC2IRGBUC2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIRGBUC2IUC2IRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIRGBUC2IUC2IRGBUC2___New_orig__: Any
itkMaskImageFilterIRGBUC2IUC2IRGBUC2_cast: Any

def itkMaskImageFilterIRGBUC3ISS3IRGBUC3_New(): ...

class itkMaskImageFilterIRGBUC3ISS3IRGBUC3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIRGBUC3ISS3IRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIRGBUC3ISS3IRGBUC3___New_orig__: Any
itkMaskImageFilterIRGBUC3ISS3IRGBUC3_cast: Any

def itkMaskImageFilterIRGBUC3IUC3IRGBUC3_New(): ...

class itkMaskImageFilterIRGBUC3IUC3IRGBUC3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIRGBUC3IUC3IRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIRGBUC3IUC3IRGBUC3___New_orig__: Any
itkMaskImageFilterIRGBUC3IUC3IRGBUC3_cast: Any

def itkMaskImageFilterISS2ISS2ISS2_New(): ...

class itkMaskImageFilterISS2ISS2ISS2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterISS2ISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterISS2ISS2ISS2___New_orig__: Any
itkMaskImageFilterISS2ISS2ISS2_cast: Any

def itkMaskImageFilterISS2IUC2ISS2_New(): ...

class itkMaskImageFilterISS2IUC2ISS2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterISS2IUC2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterISS2IUC2ISS2___New_orig__: Any
itkMaskImageFilterISS2IUC2ISS2_cast: Any

def itkMaskImageFilterISS3ISS3ISS3_New(): ...

class itkMaskImageFilterISS3ISS3ISS3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterISS3ISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterISS3ISS3ISS3___New_orig__: Any
itkMaskImageFilterISS3ISS3ISS3_cast: Any

def itkMaskImageFilterISS3IUC3ISS3_New(): ...

class itkMaskImageFilterISS3IUC3ISS3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterISS3IUC3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterISS3IUC3ISS3___New_orig__: Any
itkMaskImageFilterISS3IUC3ISS3_cast: Any

def itkMaskImageFilterIUC2ISS2IUC2_New(): ...

class itkMaskImageFilterIUC2ISS2IUC2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC2ISS2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIUC2ISS2IUC2___New_orig__: Any
itkMaskImageFilterIUC2ISS2IUC2_cast: Any

def itkMaskImageFilterIUC2IUC2IUC2_New(): ...

class itkMaskImageFilterIUC2IUC2IUC2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC2IUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIUC2IUC2IUC2___New_orig__: Any
itkMaskImageFilterIUC2IUC2IUC2_cast: Any

def itkMaskImageFilterIUC3ISS3IUC3_New(): ...

class itkMaskImageFilterIUC3ISS3IUC3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC3ISS3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIUC3ISS3IUC3___New_orig__: Any
itkMaskImageFilterIUC3ISS3IUC3_cast: Any

def itkMaskImageFilterIUC3IUC3IUC3_New(): ...

class itkMaskImageFilterIUC3IUC3IUC3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC3IUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIUC3IUC3IUC3___New_orig__: Any
itkMaskImageFilterIUC3IUC3IUC3_cast: Any

def itkMaskImageFilterIVF22ISS2IVF22_New(): ...

class itkMaskImageFilterIVF22ISS2IVF22(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF22ISS2IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIVF22ISS2IVF22___New_orig__: Any
itkMaskImageFilterIVF22ISS2IVF22_cast: Any

def itkMaskImageFilterIVF22IUC2IVF22_New(): ...

class itkMaskImageFilterIVF22IUC2IVF22(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF22IUC2IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIVF22IUC2IVF22___New_orig__: Any
itkMaskImageFilterIVF22IUC2IVF22_cast: Any

def itkMaskImageFilterIVF23ISS3IVF23_New(): ...

class itkMaskImageFilterIVF23ISS3IVF23(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF23ISS3IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIVF23ISS3IVF23___New_orig__: Any
itkMaskImageFilterIVF23ISS3IVF23_cast: Any

def itkMaskImageFilterIVF23IUC3IVF23_New(): ...

class itkMaskImageFilterIVF23IUC3IVF23(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF23IUC3IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIVF23IUC3IVF23___New_orig__: Any
itkMaskImageFilterIVF23IUC3IVF23_cast: Any

def itkMaskImageFilterIVF32ISS2IVF32_New(): ...

class itkMaskImageFilterIVF32ISS2IVF32(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF32ISS2IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIVF32ISS2IVF32___New_orig__: Any
itkMaskImageFilterIVF32ISS2IVF32_cast: Any

def itkMaskImageFilterIVF32IUC2IVF32_New(): ...

class itkMaskImageFilterIVF32IUC2IVF32(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF32IUC2IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIVF32IUC2IVF32___New_orig__: Any
itkMaskImageFilterIVF32IUC2IVF32_cast: Any

def itkMaskImageFilterIVF33ISS3IVF33_New(): ...

class itkMaskImageFilterIVF33ISS3IVF33(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF33ISS3IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIVF33ISS3IVF33___New_orig__: Any
itkMaskImageFilterIVF33ISS3IVF33_cast: Any

def itkMaskImageFilterIVF33IUC3IVF33_New(): ...

class itkMaskImageFilterIVF33IUC3IVF33(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF33IUC3IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIVF33IUC3IVF33___New_orig__: Any
itkMaskImageFilterIVF33IUC3IVF33_cast: Any

def itkMaskImageFilterIVF42ISS2IVF42_New(): ...

class itkMaskImageFilterIVF42ISS2IVF42(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF42ISS2IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIVF42ISS2IVF42___New_orig__: Any
itkMaskImageFilterIVF42ISS2IVF42_cast: Any

def itkMaskImageFilterIVF42IUC2IVF42_New(): ...

class itkMaskImageFilterIVF42IUC2IVF42(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF42IUC2IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIVF42IUC2IVF42___New_orig__: Any
itkMaskImageFilterIVF42IUC2IVF42_cast: Any

def itkMaskImageFilterIVF43ISS3IVF43_New(): ...

class itkMaskImageFilterIVF43ISS3IVF43(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF43ISS3IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIVF43ISS3IVF43___New_orig__: Any
itkMaskImageFilterIVF43ISS3IVF43_cast: Any

def itkMaskImageFilterIVF43IUC3IVF43_New(): ...

class itkMaskImageFilterIVF43IUC3IVF43(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF43IUC3IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskImageFilterIVF43IUC3IVF43___New_orig__: Any
itkMaskImageFilterIVF43IUC3IVF43_cast: Any

def mask_image_filter(*args: Any, **kwargs: Any): ...
def mask_image_filter_init_docstring() -> None: ...
