import itk.itkSamplePython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkMaximumEntropyThresholdCalculatorHDF_New(): ...

class itkMaximumEntropyThresholdCalculatorHDF(itk.itkHistogramThresholdCalculatorPython.itkHistogramThresholdCalculatorHDF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaximumEntropyThresholdCalculatorHDF___New_orig__: Any
itkMaximumEntropyThresholdCalculatorHDF_cast: Any

def itkMaximumEntropyThresholdCalculatorHDSS_New(): ...

class itkMaximumEntropyThresholdCalculatorHDSS(itk.itkHistogramThresholdCalculatorPython.itkHistogramThresholdCalculatorHDSS):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaximumEntropyThresholdCalculatorHDSS___New_orig__: Any
itkMaximumEntropyThresholdCalculatorHDSS_cast: Any

def itkMaximumEntropyThresholdCalculatorHDUC_New(): ...

class itkMaximumEntropyThresholdCalculatorHDUC(itk.itkHistogramThresholdCalculatorPython.itkHistogramThresholdCalculatorHDUC):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaximumEntropyThresholdCalculatorHDUC___New_orig__: Any
itkMaximumEntropyThresholdCalculatorHDUC_cast: Any

def itkMaximumEntropyThresholdCalculatorHFF_New(): ...

class itkMaximumEntropyThresholdCalculatorHFF(itk.itkHistogramThresholdCalculatorPython.itkHistogramThresholdCalculatorHFF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaximumEntropyThresholdCalculatorHFF___New_orig__: Any
itkMaximumEntropyThresholdCalculatorHFF_cast: Any

def itkMaximumEntropyThresholdCalculatorHFSS_New(): ...

class itkMaximumEntropyThresholdCalculatorHFSS(itk.itkHistogramThresholdCalculatorPython.itkHistogramThresholdCalculatorHFSS):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaximumEntropyThresholdCalculatorHFSS___New_orig__: Any
itkMaximumEntropyThresholdCalculatorHFSS_cast: Any

def itkMaximumEntropyThresholdCalculatorHFUC_New(): ...

class itkMaximumEntropyThresholdCalculatorHFUC(itk.itkHistogramThresholdCalculatorPython.itkHistogramThresholdCalculatorHFUC):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaximumEntropyThresholdCalculatorHFUC___New_orig__: Any
itkMaximumEntropyThresholdCalculatorHFUC_cast: Any

def maximum_entropy_threshold_calculator(*args: Any, **kwargs: Any): ...
def maximum_entropy_threshold_calculator_init_docstring() -> None: ...
