import itk.itkMeshSourcePython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkMeshToMeshFilterMF2MF2_New(): ...

class itkMeshToMeshFilterMF2MF2(itk.itkMeshSourcePython.itkMeshSourceMF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMeshToMeshFilterMF2MF2___New_orig__: Any
itkMeshToMeshFilterMF2MF2_cast: Any

def itkMeshToMeshFilterMF3MF3_New(): ...

class itkMeshToMeshFilterMF3MF3(itk.itkMeshSourcePython.itkMeshSourceMF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMeshToMeshFilterMF3MF3___New_orig__: Any
itkMeshToMeshFilterMF3MF3_cast: Any

def mesh_to_mesh_filter(*args: Any, **kwargs: Any): ...
def mesh_to_mesh_filter_init_docstring() -> None: ...
