import itk.itkRGBPixelPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkMinimumMaximumImageCalculatorIF2_New(): ...

class itkMinimumMaximumImageCalculatorIF2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetImage: Any = ...
    ComputeMinimum: Any = ...
    ComputeMaximum: Any = ...
    Compute: Any = ...
    GetMinimum: Any = ...
    GetMaximum: Any = ...
    GetIndexOfMinimum: Any = ...
    GetIndexOfMaximum: Any = ...
    SetRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumMaximumImageCalculatorIF2___New_orig__: Any
itkMinimumMaximumImageCalculatorIF2_cast: Any

def itkMinimumMaximumImageCalculatorIF3_New(): ...

class itkMinimumMaximumImageCalculatorIF3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetImage: Any = ...
    ComputeMinimum: Any = ...
    ComputeMaximum: Any = ...
    Compute: Any = ...
    GetMinimum: Any = ...
    GetMaximum: Any = ...
    GetIndexOfMinimum: Any = ...
    GetIndexOfMaximum: Any = ...
    SetRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumMaximumImageCalculatorIF3___New_orig__: Any
itkMinimumMaximumImageCalculatorIF3_cast: Any

def itkMinimumMaximumImageCalculatorISS2_New(): ...

class itkMinimumMaximumImageCalculatorISS2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetImage: Any = ...
    ComputeMinimum: Any = ...
    ComputeMaximum: Any = ...
    Compute: Any = ...
    GetMinimum: Any = ...
    GetMaximum: Any = ...
    GetIndexOfMinimum: Any = ...
    GetIndexOfMaximum: Any = ...
    SetRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumMaximumImageCalculatorISS2___New_orig__: Any
itkMinimumMaximumImageCalculatorISS2_cast: Any

def itkMinimumMaximumImageCalculatorISS3_New(): ...

class itkMinimumMaximumImageCalculatorISS3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetImage: Any = ...
    ComputeMinimum: Any = ...
    ComputeMaximum: Any = ...
    Compute: Any = ...
    GetMinimum: Any = ...
    GetMaximum: Any = ...
    GetIndexOfMinimum: Any = ...
    GetIndexOfMaximum: Any = ...
    SetRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumMaximumImageCalculatorISS3___New_orig__: Any
itkMinimumMaximumImageCalculatorISS3_cast: Any

def itkMinimumMaximumImageCalculatorIUC2_New(): ...

class itkMinimumMaximumImageCalculatorIUC2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetImage: Any = ...
    ComputeMinimum: Any = ...
    ComputeMaximum: Any = ...
    Compute: Any = ...
    GetMinimum: Any = ...
    GetMaximum: Any = ...
    GetIndexOfMinimum: Any = ...
    GetIndexOfMaximum: Any = ...
    SetRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumMaximumImageCalculatorIUC2___New_orig__: Any
itkMinimumMaximumImageCalculatorIUC2_cast: Any

def itkMinimumMaximumImageCalculatorIUC3_New(): ...

class itkMinimumMaximumImageCalculatorIUC3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetImage: Any = ...
    ComputeMinimum: Any = ...
    ComputeMaximum: Any = ...
    Compute: Any = ...
    GetMinimum: Any = ...
    GetMaximum: Any = ...
    GetIndexOfMinimum: Any = ...
    GetIndexOfMaximum: Any = ...
    SetRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMinimumMaximumImageCalculatorIUC3___New_orig__: Any
itkMinimumMaximumImageCalculatorIUC3_cast: Any
