import itk.itkImageToImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkMedianProjectionImageFilterIF2IF2_Superclass_New(): ...

class itkMedianProjectionImageFilterIF2IF2_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianProjectionImageFilterIF2IF2_Superclass___New_orig__: Any
itkMedianProjectionImageFilterIF2IF2_Superclass_cast: Any

def itkMedianProjectionImageFilterIF3IF2_Superclass_New(): ...

class itkMedianProjectionImageFilterIF3IF2_Superclass(itk.itkImageToImageFilterBPython.itkImageToImageFilterIF3IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianProjectionImageFilterIF3IF2_Superclass___New_orig__: Any
itkMedianProjectionImageFilterIF3IF2_Superclass_cast: Any

def itkMedianProjectionImageFilterIF3IF3_Superclass_New(): ...

class itkMedianProjectionImageFilterIF3IF3_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianProjectionImageFilterIF3IF3_Superclass___New_orig__: Any
itkMedianProjectionImageFilterIF3IF3_Superclass_cast: Any

def itkMedianProjectionImageFilterISS2ISS2_Superclass_New(): ...

class itkMedianProjectionImageFilterISS2ISS2_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianProjectionImageFilterISS2ISS2_Superclass___New_orig__: Any
itkMedianProjectionImageFilterISS2ISS2_Superclass_cast: Any

def itkMedianProjectionImageFilterISS3ISS2_Superclass_New(): ...

class itkMedianProjectionImageFilterISS3ISS2_Superclass(itk.itkImageToImageFilterBPython.itkImageToImageFilterISS3ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianProjectionImageFilterISS3ISS2_Superclass___New_orig__: Any
itkMedianProjectionImageFilterISS3ISS2_Superclass_cast: Any

def itkMedianProjectionImageFilterISS3ISS3_Superclass_New(): ...

class itkMedianProjectionImageFilterISS3ISS3_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianProjectionImageFilterISS3ISS3_Superclass___New_orig__: Any
itkMedianProjectionImageFilterISS3ISS3_Superclass_cast: Any

def itkMedianProjectionImageFilterIUC2IUC2_Superclass_New(): ...

class itkMedianProjectionImageFilterIUC2IUC2_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianProjectionImageFilterIUC2IUC2_Superclass___New_orig__: Any
itkMedianProjectionImageFilterIUC2IUC2_Superclass_cast: Any

def itkMedianProjectionImageFilterIUC3IUC2_Superclass_New(): ...

class itkMedianProjectionImageFilterIUC3IUC2_Superclass(itk.itkImageToImageFilterBPython.itkImageToImageFilterIUC3IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianProjectionImageFilterIUC3IUC2_Superclass___New_orig__: Any
itkMedianProjectionImageFilterIUC3IUC2_Superclass_cast: Any

def itkMedianProjectionImageFilterIUC3IUC3_Superclass_New(): ...

class itkMedianProjectionImageFilterIUC3IUC3_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionCheck: Any = ...
    SetProjectionDimension: Any = ...
    GetProjectionDimension: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianProjectionImageFilterIUC3IUC3_Superclass___New_orig__: Any
itkMedianProjectionImageFilterIUC3IUC3_Superclass_cast: Any

def itkMedianProjectionImageFilterIF2IF2_New(): ...

class itkMedianProjectionImageFilterIF2IF2(itkMedianProjectionImageFilterIF2IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianProjectionImageFilterIF2IF2___New_orig__: Any
itkMedianProjectionImageFilterIF2IF2_cast: Any

def itkMedianProjectionImageFilterIF3IF2_New(): ...

class itkMedianProjectionImageFilterIF3IF2(itkMedianProjectionImageFilterIF3IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianProjectionImageFilterIF3IF2___New_orig__: Any
itkMedianProjectionImageFilterIF3IF2_cast: Any

def itkMedianProjectionImageFilterIF3IF3_New(): ...

class itkMedianProjectionImageFilterIF3IF3(itkMedianProjectionImageFilterIF3IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianProjectionImageFilterIF3IF3___New_orig__: Any
itkMedianProjectionImageFilterIF3IF3_cast: Any

def itkMedianProjectionImageFilterISS2ISS2_New(): ...

class itkMedianProjectionImageFilterISS2ISS2(itkMedianProjectionImageFilterISS2ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianProjectionImageFilterISS2ISS2___New_orig__: Any
itkMedianProjectionImageFilterISS2ISS2_cast: Any

def itkMedianProjectionImageFilterISS3ISS2_New(): ...

class itkMedianProjectionImageFilterISS3ISS2(itkMedianProjectionImageFilterISS3ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianProjectionImageFilterISS3ISS2___New_orig__: Any
itkMedianProjectionImageFilterISS3ISS2_cast: Any

def itkMedianProjectionImageFilterISS3ISS3_New(): ...

class itkMedianProjectionImageFilterISS3ISS3(itkMedianProjectionImageFilterISS3ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianProjectionImageFilterISS3ISS3___New_orig__: Any
itkMedianProjectionImageFilterISS3ISS3_cast: Any

def itkMedianProjectionImageFilterIUC2IUC2_New(): ...

class itkMedianProjectionImageFilterIUC2IUC2(itkMedianProjectionImageFilterIUC2IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianProjectionImageFilterIUC2IUC2___New_orig__: Any
itkMedianProjectionImageFilterIUC2IUC2_cast: Any

def itkMedianProjectionImageFilterIUC3IUC2_New(): ...

class itkMedianProjectionImageFilterIUC3IUC2(itkMedianProjectionImageFilterIUC3IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianProjectionImageFilterIUC3IUC2___New_orig__: Any
itkMedianProjectionImageFilterIUC3IUC2_cast: Any

def itkMedianProjectionImageFilterIUC3IUC3_New(): ...

class itkMedianProjectionImageFilterIUC3IUC3(itkMedianProjectionImageFilterIUC3IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMedianProjectionImageFilterIUC3IUC3___New_orig__: Any
itkMedianProjectionImageFilterIUC3IUC3_cast: Any

def median_projection_image_filter(*args: Any, **kwargs: Any): ...
def median_projection_image_filter_init_docstring() -> None: ...
def projection_image_filter(*args: Any, **kwargs: Any): ...
def projection_image_filter_init_docstring() -> None: ...
