import itk.itkInPlaceImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkMaskNegatedImageFilterICF2ISS2ICF2_New(): ...

class itkMaskNegatedImageFilterICF2ISS2ICF2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICF2ISS2ICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterICF2ISS2ICF2___New_orig__: Any
itkMaskNegatedImageFilterICF2ISS2ICF2_cast: Any

def itkMaskNegatedImageFilterICF2IUC2ICF2_New(): ...

class itkMaskNegatedImageFilterICF2IUC2ICF2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICF2IUC2ICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterICF2IUC2ICF2___New_orig__: Any
itkMaskNegatedImageFilterICF2IUC2ICF2_cast: Any

def itkMaskNegatedImageFilterICF3ISS3ICF3_New(): ...

class itkMaskNegatedImageFilterICF3ISS3ICF3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICF3ISS3ICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterICF3ISS3ICF3___New_orig__: Any
itkMaskNegatedImageFilterICF3ISS3ICF3_cast: Any

def itkMaskNegatedImageFilterICF3IUC3ICF3_New(): ...

class itkMaskNegatedImageFilterICF3IUC3ICF3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICF3IUC3ICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterICF3IUC3ICF3___New_orig__: Any
itkMaskNegatedImageFilterICF3IUC3ICF3_cast: Any

def itkMaskNegatedImageFilterICVF22ISS2ICVF22_New(): ...

class itkMaskNegatedImageFilterICVF22ISS2ICVF22(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF22ISS2ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterICVF22ISS2ICVF22___New_orig__: Any
itkMaskNegatedImageFilterICVF22ISS2ICVF22_cast: Any

def itkMaskNegatedImageFilterICVF22IUC2ICVF22_New(): ...

class itkMaskNegatedImageFilterICVF22IUC2ICVF22(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF22IUC2ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterICVF22IUC2ICVF22___New_orig__: Any
itkMaskNegatedImageFilterICVF22IUC2ICVF22_cast: Any

def itkMaskNegatedImageFilterICVF23ISS3ICVF23_New(): ...

class itkMaskNegatedImageFilterICVF23ISS3ICVF23(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF23ISS3ICVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterICVF23ISS3ICVF23___New_orig__: Any
itkMaskNegatedImageFilterICVF23ISS3ICVF23_cast: Any

def itkMaskNegatedImageFilterICVF23IUC3ICVF23_New(): ...

class itkMaskNegatedImageFilterICVF23IUC3ICVF23(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF23IUC3ICVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterICVF23IUC3ICVF23___New_orig__: Any
itkMaskNegatedImageFilterICVF23IUC3ICVF23_cast: Any

def itkMaskNegatedImageFilterICVF32ISS2ICVF32_New(): ...

class itkMaskNegatedImageFilterICVF32ISS2ICVF32(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF32ISS2ICVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterICVF32ISS2ICVF32___New_orig__: Any
itkMaskNegatedImageFilterICVF32ISS2ICVF32_cast: Any

def itkMaskNegatedImageFilterICVF32IUC2ICVF32_New(): ...

class itkMaskNegatedImageFilterICVF32IUC2ICVF32(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF32IUC2ICVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterICVF32IUC2ICVF32___New_orig__: Any
itkMaskNegatedImageFilterICVF32IUC2ICVF32_cast: Any

def itkMaskNegatedImageFilterICVF33ISS3ICVF33_New(): ...

class itkMaskNegatedImageFilterICVF33ISS3ICVF33(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF33ISS3ICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterICVF33ISS3ICVF33___New_orig__: Any
itkMaskNegatedImageFilterICVF33ISS3ICVF33_cast: Any

def itkMaskNegatedImageFilterICVF33IUC3ICVF33_New(): ...

class itkMaskNegatedImageFilterICVF33IUC3ICVF33(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF33IUC3ICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterICVF33IUC3ICVF33___New_orig__: Any
itkMaskNegatedImageFilterICVF33IUC3ICVF33_cast: Any

def itkMaskNegatedImageFilterICVF42ISS2ICVF42_New(): ...

class itkMaskNegatedImageFilterICVF42ISS2ICVF42(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF42ISS2ICVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterICVF42ISS2ICVF42___New_orig__: Any
itkMaskNegatedImageFilterICVF42ISS2ICVF42_cast: Any

def itkMaskNegatedImageFilterICVF42IUC2ICVF42_New(): ...

class itkMaskNegatedImageFilterICVF42IUC2ICVF42(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF42IUC2ICVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterICVF42IUC2ICVF42___New_orig__: Any
itkMaskNegatedImageFilterICVF42IUC2ICVF42_cast: Any

def itkMaskNegatedImageFilterICVF43ISS3ICVF43_New(): ...

class itkMaskNegatedImageFilterICVF43ISS3ICVF43(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF43ISS3ICVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterICVF43ISS3ICVF43___New_orig__: Any
itkMaskNegatedImageFilterICVF43ISS3ICVF43_cast: Any

def itkMaskNegatedImageFilterICVF43IUC3ICVF43_New(): ...

class itkMaskNegatedImageFilterICVF43IUC3ICVF43(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterICVF43IUC3ICVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterICVF43IUC3ICVF43___New_orig__: Any
itkMaskNegatedImageFilterICVF43IUC3ICVF43_cast: Any

def itkMaskNegatedImageFilterIF2ISS2IF2_New(): ...

class itkMaskNegatedImageFilterIF2ISS2IF2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIF2ISS2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIF2ISS2IF2___New_orig__: Any
itkMaskNegatedImageFilterIF2ISS2IF2_cast: Any

def itkMaskNegatedImageFilterIF2IUC2IF2_New(): ...

class itkMaskNegatedImageFilterIF2IUC2IF2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIF2IUC2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIF2IUC2IF2___New_orig__: Any
itkMaskNegatedImageFilterIF2IUC2IF2_cast: Any

def itkMaskNegatedImageFilterIF3ISS3IF3_New(): ...

class itkMaskNegatedImageFilterIF3ISS3IF3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIF3ISS3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIF3ISS3IF3___New_orig__: Any
itkMaskNegatedImageFilterIF3ISS3IF3_cast: Any

def itkMaskNegatedImageFilterIF3IUC3IF3_New(): ...

class itkMaskNegatedImageFilterIF3IUC3IF3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIF3IUC3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIF3IUC3IF3___New_orig__: Any
itkMaskNegatedImageFilterIF3IUC3IF3_cast: Any

def itkMaskNegatedImageFilterIRGBAUC2ISS2IRGBAUC2_New(): ...

class itkMaskNegatedImageFilterIRGBAUC2ISS2IRGBAUC2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIRGBAUC2ISS2IRGBAUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIRGBAUC2ISS2IRGBAUC2___New_orig__: Any
itkMaskNegatedImageFilterIRGBAUC2ISS2IRGBAUC2_cast: Any

def itkMaskNegatedImageFilterIRGBAUC2IUC2IRGBAUC2_New(): ...

class itkMaskNegatedImageFilterIRGBAUC2IUC2IRGBAUC2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIRGBAUC2IUC2IRGBAUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIRGBAUC2IUC2IRGBAUC2___New_orig__: Any
itkMaskNegatedImageFilterIRGBAUC2IUC2IRGBAUC2_cast: Any

def itkMaskNegatedImageFilterIRGBAUC3ISS3IRGBAUC3_New(): ...

class itkMaskNegatedImageFilterIRGBAUC3ISS3IRGBAUC3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIRGBAUC3ISS3IRGBAUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIRGBAUC3ISS3IRGBAUC3___New_orig__: Any
itkMaskNegatedImageFilterIRGBAUC3ISS3IRGBAUC3_cast: Any

def itkMaskNegatedImageFilterIRGBAUC3IUC3IRGBAUC3_New(): ...

class itkMaskNegatedImageFilterIRGBAUC3IUC3IRGBAUC3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIRGBAUC3IUC3IRGBAUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIRGBAUC3IUC3IRGBAUC3___New_orig__: Any
itkMaskNegatedImageFilterIRGBAUC3IUC3IRGBAUC3_cast: Any

def itkMaskNegatedImageFilterIRGBUC2ISS2IRGBUC2_New(): ...

class itkMaskNegatedImageFilterIRGBUC2ISS2IRGBUC2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIRGBUC2ISS2IRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIRGBUC2ISS2IRGBUC2___New_orig__: Any
itkMaskNegatedImageFilterIRGBUC2ISS2IRGBUC2_cast: Any

def itkMaskNegatedImageFilterIRGBUC2IUC2IRGBUC2_New(): ...

class itkMaskNegatedImageFilterIRGBUC2IUC2IRGBUC2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIRGBUC2IUC2IRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIRGBUC2IUC2IRGBUC2___New_orig__: Any
itkMaskNegatedImageFilterIRGBUC2IUC2IRGBUC2_cast: Any

def itkMaskNegatedImageFilterIRGBUC3ISS3IRGBUC3_New(): ...

class itkMaskNegatedImageFilterIRGBUC3ISS3IRGBUC3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIRGBUC3ISS3IRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIRGBUC3ISS3IRGBUC3___New_orig__: Any
itkMaskNegatedImageFilterIRGBUC3ISS3IRGBUC3_cast: Any

def itkMaskNegatedImageFilterIRGBUC3IUC3IRGBUC3_New(): ...

class itkMaskNegatedImageFilterIRGBUC3IUC3IRGBUC3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIRGBUC3IUC3IRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIRGBUC3IUC3IRGBUC3___New_orig__: Any
itkMaskNegatedImageFilterIRGBUC3IUC3IRGBUC3_cast: Any

def itkMaskNegatedImageFilterISS2ISS2ISS2_New(): ...

class itkMaskNegatedImageFilterISS2ISS2ISS2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterISS2ISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterISS2ISS2ISS2___New_orig__: Any
itkMaskNegatedImageFilterISS2ISS2ISS2_cast: Any

def itkMaskNegatedImageFilterISS2IUC2ISS2_New(): ...

class itkMaskNegatedImageFilterISS2IUC2ISS2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterISS2IUC2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterISS2IUC2ISS2___New_orig__: Any
itkMaskNegatedImageFilterISS2IUC2ISS2_cast: Any

def itkMaskNegatedImageFilterISS3ISS3ISS3_New(): ...

class itkMaskNegatedImageFilterISS3ISS3ISS3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterISS3ISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterISS3ISS3ISS3___New_orig__: Any
itkMaskNegatedImageFilterISS3ISS3ISS3_cast: Any

def itkMaskNegatedImageFilterISS3IUC3ISS3_New(): ...

class itkMaskNegatedImageFilterISS3IUC3ISS3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterISS3IUC3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterISS3IUC3ISS3___New_orig__: Any
itkMaskNegatedImageFilterISS3IUC3ISS3_cast: Any

def itkMaskNegatedImageFilterIUC2ISS2IUC2_New(): ...

class itkMaskNegatedImageFilterIUC2ISS2IUC2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC2ISS2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIUC2ISS2IUC2___New_orig__: Any
itkMaskNegatedImageFilterIUC2ISS2IUC2_cast: Any

def itkMaskNegatedImageFilterIUC2IUC2IUC2_New(): ...

class itkMaskNegatedImageFilterIUC2IUC2IUC2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC2IUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIUC2IUC2IUC2___New_orig__: Any
itkMaskNegatedImageFilterIUC2IUC2IUC2_cast: Any

def itkMaskNegatedImageFilterIUC3ISS3IUC3_New(): ...

class itkMaskNegatedImageFilterIUC3ISS3IUC3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC3ISS3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIUC3ISS3IUC3___New_orig__: Any
itkMaskNegatedImageFilterIUC3ISS3IUC3_cast: Any

def itkMaskNegatedImageFilterIUC3IUC3IUC3_New(): ...

class itkMaskNegatedImageFilterIUC3IUC3IUC3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC3IUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIUC3IUC3IUC3___New_orig__: Any
itkMaskNegatedImageFilterIUC3IUC3IUC3_cast: Any

def itkMaskNegatedImageFilterIVF22ISS2IVF22_New(): ...

class itkMaskNegatedImageFilterIVF22ISS2IVF22(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF22ISS2IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIVF22ISS2IVF22___New_orig__: Any
itkMaskNegatedImageFilterIVF22ISS2IVF22_cast: Any

def itkMaskNegatedImageFilterIVF22IUC2IVF22_New(): ...

class itkMaskNegatedImageFilterIVF22IUC2IVF22(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF22IUC2IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIVF22IUC2IVF22___New_orig__: Any
itkMaskNegatedImageFilterIVF22IUC2IVF22_cast: Any

def itkMaskNegatedImageFilterIVF23ISS3IVF23_New(): ...

class itkMaskNegatedImageFilterIVF23ISS3IVF23(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF23ISS3IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIVF23ISS3IVF23___New_orig__: Any
itkMaskNegatedImageFilterIVF23ISS3IVF23_cast: Any

def itkMaskNegatedImageFilterIVF23IUC3IVF23_New(): ...

class itkMaskNegatedImageFilterIVF23IUC3IVF23(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF23IUC3IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIVF23IUC3IVF23___New_orig__: Any
itkMaskNegatedImageFilterIVF23IUC3IVF23_cast: Any

def itkMaskNegatedImageFilterIVF32ISS2IVF32_New(): ...

class itkMaskNegatedImageFilterIVF32ISS2IVF32(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF32ISS2IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIVF32ISS2IVF32___New_orig__: Any
itkMaskNegatedImageFilterIVF32ISS2IVF32_cast: Any

def itkMaskNegatedImageFilterIVF32IUC2IVF32_New(): ...

class itkMaskNegatedImageFilterIVF32IUC2IVF32(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF32IUC2IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIVF32IUC2IVF32___New_orig__: Any
itkMaskNegatedImageFilterIVF32IUC2IVF32_cast: Any

def itkMaskNegatedImageFilterIVF33ISS3IVF33_New(): ...

class itkMaskNegatedImageFilterIVF33ISS3IVF33(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF33ISS3IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIVF33ISS3IVF33___New_orig__: Any
itkMaskNegatedImageFilterIVF33ISS3IVF33_cast: Any

def itkMaskNegatedImageFilterIVF33IUC3IVF33_New(): ...

class itkMaskNegatedImageFilterIVF33IUC3IVF33(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF33IUC3IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIVF33IUC3IVF33___New_orig__: Any
itkMaskNegatedImageFilterIVF33IUC3IVF33_cast: Any

def itkMaskNegatedImageFilterIVF42ISS2IVF42_New(): ...

class itkMaskNegatedImageFilterIVF42ISS2IVF42(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF42ISS2IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIVF42ISS2IVF42___New_orig__: Any
itkMaskNegatedImageFilterIVF42ISS2IVF42_cast: Any

def itkMaskNegatedImageFilterIVF42IUC2IVF42_New(): ...

class itkMaskNegatedImageFilterIVF42IUC2IVF42(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF42IUC2IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIVF42IUC2IVF42___New_orig__: Any
itkMaskNegatedImageFilterIVF42IUC2IVF42_cast: Any

def itkMaskNegatedImageFilterIVF43ISS3IVF43_New(): ...

class itkMaskNegatedImageFilterIVF43ISS3IVF43(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF43ISS3IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIVF43ISS3IVF43___New_orig__: Any
itkMaskNegatedImageFilterIVF43ISS3IVF43_cast: Any

def itkMaskNegatedImageFilterIVF43IUC3IVF43_New(): ...

class itkMaskNegatedImageFilterIVF43IUC3IVF43(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIVF43IUC3IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetMaskingValue: Any = ...
    GetMaskingValue: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    MaskEqualityComparableCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMaskNegatedImageFilterIVF43IUC3IVF43___New_orig__: Any
itkMaskNegatedImageFilterIVF43IUC3IVF43_cast: Any

def mask_negated_image_filter(*args: Any, **kwargs: Any): ...
def mask_negated_image_filter_init_docstring() -> None: ...
