import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkNoiseImageFilterIF2IF2_New(): ...

class itkNoiseImageFilterIF2IF2(itk.itkBoxImageFilterPython.itkBoxImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNoiseImageFilterIF2IF2___New_orig__: Any
itkNoiseImageFilterIF2IF2_cast: Any

def itkNoiseImageFilterIF3IF3_New(): ...

class itkNoiseImageFilterIF3IF3(itk.itkBoxImageFilterPython.itkBoxImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNoiseImageFilterIF3IF3___New_orig__: Any
itkNoiseImageFilterIF3IF3_cast: Any

def itkNoiseImageFilterISS2ISS2_New(): ...

class itkNoiseImageFilterISS2ISS2(itk.itkBoxImageFilterPython.itkBoxImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNoiseImageFilterISS2ISS2___New_orig__: Any
itkNoiseImageFilterISS2ISS2_cast: Any

def itkNoiseImageFilterISS3ISS3_New(): ...

class itkNoiseImageFilterISS3ISS3(itk.itkBoxImageFilterPython.itkBoxImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNoiseImageFilterISS3ISS3___New_orig__: Any
itkNoiseImageFilterISS3ISS3_cast: Any

def itkNoiseImageFilterIUC2IUC2_New(): ...

class itkNoiseImageFilterIUC2IUC2(itk.itkBoxImageFilterPython.itkBoxImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNoiseImageFilterIUC2IUC2___New_orig__: Any
itkNoiseImageFilterIUC2IUC2_cast: Any

def itkNoiseImageFilterIUC3IUC3_New(): ...

class itkNoiseImageFilterIUC3IUC3(itk.itkBoxImageFilterPython.itkBoxImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNoiseImageFilterIUC3IUC3___New_orig__: Any
itkNoiseImageFilterIUC3IUC3_cast: Any

def noise_image_filter(*args: Any, **kwargs: Any): ...
def noise_image_filter_init_docstring() -> None: ...
