import itk.itkOffsetPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkNeighborhoodOperatorF2(itk.itkNeighborhoodPython.itkNeighborhoodF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    CreateDirectional: Any = ...
    CreateToRadius: Any = ...
    FlipAxes: Any = ...
    PrintSelf: Any = ...
    ScaleCoefficients: Any = ...
    __swig_destroy__: Any = ...

class itkNeighborhoodOperatorF3(itk.itkNeighborhoodPython.itkNeighborhoodF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    CreateDirectional: Any = ...
    CreateToRadius: Any = ...
    FlipAxes: Any = ...
    PrintSelf: Any = ...
    ScaleCoefficients: Any = ...
    __swig_destroy__: Any = ...
