import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkNaryMaximumImageFilterIF2IF2_Superclass_New(): ...

class itkNaryMaximumImageFilterIF2IF2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    OutputHasZeroCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryMaximumImageFilterIF2IF2_Superclass___New_orig__: Any
itkNaryMaximumImageFilterIF2IF2_Superclass_cast: Any

def itkNaryMaximumImageFilterIF3IF3_Superclass_New(): ...

class itkNaryMaximumImageFilterIF3IF3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    OutputHasZeroCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryMaximumImageFilterIF3IF3_Superclass___New_orig__: Any
itkNaryMaximumImageFilterIF3IF3_Superclass_cast: Any

def itkNaryMaximumImageFilterISS2ISS2_Superclass_New(): ...

class itkNaryMaximumImageFilterISS2ISS2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    OutputHasZeroCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryMaximumImageFilterISS2ISS2_Superclass___New_orig__: Any
itkNaryMaximumImageFilterISS2ISS2_Superclass_cast: Any

def itkNaryMaximumImageFilterISS3ISS3_Superclass_New(): ...

class itkNaryMaximumImageFilterISS3ISS3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    OutputHasZeroCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryMaximumImageFilterISS3ISS3_Superclass___New_orig__: Any
itkNaryMaximumImageFilterISS3ISS3_Superclass_cast: Any

def itkNaryMaximumImageFilterIUC2IUC2_Superclass_New(): ...

class itkNaryMaximumImageFilterIUC2IUC2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    OutputHasZeroCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryMaximumImageFilterIUC2IUC2_Superclass___New_orig__: Any
itkNaryMaximumImageFilterIUC2IUC2_Superclass_cast: Any

def itkNaryMaximumImageFilterIUC3IUC3_Superclass_New(): ...

class itkNaryMaximumImageFilterIUC3IUC3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    OutputHasZeroCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryMaximumImageFilterIUC3IUC3_Superclass___New_orig__: Any
itkNaryMaximumImageFilterIUC3IUC3_Superclass_cast: Any

def itkNaryMaximumImageFilterIF2IF2_New(): ...

class itkNaryMaximumImageFilterIF2IF2(itkNaryMaximumImageFilterIF2IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputLessThanComparableCheck: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryMaximumImageFilterIF2IF2___New_orig__: Any
itkNaryMaximumImageFilterIF2IF2_cast: Any

def itkNaryMaximumImageFilterIF3IF3_New(): ...

class itkNaryMaximumImageFilterIF3IF3(itkNaryMaximumImageFilterIF3IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputLessThanComparableCheck: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryMaximumImageFilterIF3IF3___New_orig__: Any
itkNaryMaximumImageFilterIF3IF3_cast: Any

def itkNaryMaximumImageFilterISS2ISS2_New(): ...

class itkNaryMaximumImageFilterISS2ISS2(itkNaryMaximumImageFilterISS2ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputLessThanComparableCheck: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryMaximumImageFilterISS2ISS2___New_orig__: Any
itkNaryMaximumImageFilterISS2ISS2_cast: Any

def itkNaryMaximumImageFilterISS3ISS3_New(): ...

class itkNaryMaximumImageFilterISS3ISS3(itkNaryMaximumImageFilterISS3ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputLessThanComparableCheck: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryMaximumImageFilterISS3ISS3___New_orig__: Any
itkNaryMaximumImageFilterISS3ISS3_cast: Any

def itkNaryMaximumImageFilterIUC2IUC2_New(): ...

class itkNaryMaximumImageFilterIUC2IUC2(itkNaryMaximumImageFilterIUC2IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputLessThanComparableCheck: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryMaximumImageFilterIUC2IUC2___New_orig__: Any
itkNaryMaximumImageFilterIUC2IUC2_cast: Any

def itkNaryMaximumImageFilterIUC3IUC3_New(): ...

class itkNaryMaximumImageFilterIUC3IUC3(itkNaryMaximumImageFilterIUC3IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputLessThanComparableCheck: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryMaximumImageFilterIUC3IUC3___New_orig__: Any
itkNaryMaximumImageFilterIUC3IUC3_cast: Any

def nary_functor_image_filter(*args: Any, **kwargs: Any): ...
def nary_functor_image_filter_init_docstring() -> None: ...
def nary_maximum_image_filter(*args: Any, **kwargs: Any): ...
def nary_maximum_image_filter_init_docstring() -> None: ...
