import itk.itkNeighborhoodPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkImageBoundaryConditionF2F2:
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetNameOfClass: Any = ...
    Print: Any = ...
    __call__: Any = ...
    __swig_destroy__: Any = ...
    RequiresCompleteNeighborhood: Any = ...
    GetInputRequestedRegion: Any = ...
    GetPixel: Any = ...

class itkImageBoundaryConditionF3F3:
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetNameOfClass: Any = ...
    Print: Any = ...
    __call__: Any = ...
    __swig_destroy__: Any = ...
    RequiresCompleteNeighborhood: Any = ...
    GetInputRequestedRegion: Any = ...
    GetPixel: Any = ...

class itkImageBoundaryConditionSS2SS2:
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetNameOfClass: Any = ...
    Print: Any = ...
    __call__: Any = ...
    __swig_destroy__: Any = ...
    RequiresCompleteNeighborhood: Any = ...
    GetInputRequestedRegion: Any = ...
    GetPixel: Any = ...

class itkImageBoundaryConditionSS3SS3:
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetNameOfClass: Any = ...
    Print: Any = ...
    __call__: Any = ...
    __swig_destroy__: Any = ...
    RequiresCompleteNeighborhood: Any = ...
    GetInputRequestedRegion: Any = ...
    GetPixel: Any = ...

class itkImageBoundaryConditionUC2UC2:
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetNameOfClass: Any = ...
    Print: Any = ...
    __call__: Any = ...
    __swig_destroy__: Any = ...
    RequiresCompleteNeighborhood: Any = ...
    GetInputRequestedRegion: Any = ...
    GetPixel: Any = ...

class itkImageBoundaryConditionUC3UC3:
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetNameOfClass: Any = ...
    Print: Any = ...
    __call__: Any = ...
    __swig_destroy__: Any = ...
    RequiresCompleteNeighborhood: Any = ...
    GetInputRequestedRegion: Any = ...
    GetPixel: Any = ...

def itkNeighborhoodOperatorImageFilterF2F2F_New(): ...

class itkNeighborhoodOperatorImageFilterF2F2F(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOperator: Any = ...
    GetOperator: Any = ...
    OverrideBoundaryCondition: Any = ...
    GetBoundaryCondition: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SameDimensionCheck: Any = ...
    OperatorConvertibleToOutputCheck: Any = ...
    InputConvertibleToOperatorCheck: Any = ...
    OperatorMultiplyOperatorCheck: Any = ...
    OperatorAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNeighborhoodOperatorImageFilterF2F2F___New_orig__: Any
itkNeighborhoodOperatorImageFilterF2F2F_cast: Any

def itkNeighborhoodOperatorImageFilterF3F3F_New(): ...

class itkNeighborhoodOperatorImageFilterF3F3F(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOperator: Any = ...
    GetOperator: Any = ...
    OverrideBoundaryCondition: Any = ...
    GetBoundaryCondition: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SameDimensionCheck: Any = ...
    OperatorConvertibleToOutputCheck: Any = ...
    InputConvertibleToOperatorCheck: Any = ...
    OperatorMultiplyOperatorCheck: Any = ...
    OperatorAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNeighborhoodOperatorImageFilterF3F3F___New_orig__: Any
itkNeighborhoodOperatorImageFilterF3F3F_cast: Any

def itkNeighborhoodOperatorImageFilterSS2SS2SS_New(): ...

class itkNeighborhoodOperatorImageFilterSS2SS2SS(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOperator: Any = ...
    GetOperator: Any = ...
    OverrideBoundaryCondition: Any = ...
    GetBoundaryCondition: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SameDimensionCheck: Any = ...
    OperatorConvertibleToOutputCheck: Any = ...
    InputConvertibleToOperatorCheck: Any = ...
    OperatorMultiplyOperatorCheck: Any = ...
    OperatorAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNeighborhoodOperatorImageFilterSS2SS2SS___New_orig__: Any
itkNeighborhoodOperatorImageFilterSS2SS2SS_cast: Any

def itkNeighborhoodOperatorImageFilterSS3SS3SS_New(): ...

class itkNeighborhoodOperatorImageFilterSS3SS3SS(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOperator: Any = ...
    GetOperator: Any = ...
    OverrideBoundaryCondition: Any = ...
    GetBoundaryCondition: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SameDimensionCheck: Any = ...
    OperatorConvertibleToOutputCheck: Any = ...
    InputConvertibleToOperatorCheck: Any = ...
    OperatorMultiplyOperatorCheck: Any = ...
    OperatorAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNeighborhoodOperatorImageFilterSS3SS3SS___New_orig__: Any
itkNeighborhoodOperatorImageFilterSS3SS3SS_cast: Any

def itkNeighborhoodOperatorImageFilterUC2UC2UC_New(): ...

class itkNeighborhoodOperatorImageFilterUC2UC2UC(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOperator: Any = ...
    GetOperator: Any = ...
    OverrideBoundaryCondition: Any = ...
    GetBoundaryCondition: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SameDimensionCheck: Any = ...
    OperatorConvertibleToOutputCheck: Any = ...
    InputConvertibleToOperatorCheck: Any = ...
    OperatorMultiplyOperatorCheck: Any = ...
    OperatorAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNeighborhoodOperatorImageFilterUC2UC2UC___New_orig__: Any
itkNeighborhoodOperatorImageFilterUC2UC2UC_cast: Any

def itkNeighborhoodOperatorImageFilterUC3UC3UC_New(): ...

class itkNeighborhoodOperatorImageFilterUC3UC3UC(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOperator: Any = ...
    GetOperator: Any = ...
    OverrideBoundaryCondition: Any = ...
    GetBoundaryCondition: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SameDimensionCheck: Any = ...
    OperatorConvertibleToOutputCheck: Any = ...
    InputConvertibleToOperatorCheck: Any = ...
    OperatorMultiplyOperatorCheck: Any = ...
    OperatorAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNeighborhoodOperatorImageFilterUC3UC3UC___New_orig__: Any
itkNeighborhoodOperatorImageFilterUC3UC3UC_cast: Any

def neighborhood_operator_image_filter(*args: Any, **kwargs: Any): ...
def neighborhood_operator_image_filter_init_docstring() -> None: ...
