from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkNeighborhoodB2:
    thisown: Any = ...
    GetNameOfClass: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetRadius: Any = ...
    GetSize: Any = ...
    GetStride: Any = ...
    Size: Any = ...
    GetElement: Any = ...
    GetCenterValue: Any = ...
    SetRadius: Any = ...
    Print: Any = ...
    GetBufferReference: Any = ...
    GetOffset: Any = ...
    GetNeighborhoodIndex: Any = ...
    GetCenterNeighborhoodIndex: Any = ...
    GetSlice: Any = ...

class itkNeighborhoodB3:
    thisown: Any = ...
    GetNameOfClass: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetRadius: Any = ...
    GetSize: Any = ...
    GetStride: Any = ...
    Size: Any = ...
    GetElement: Any = ...
    GetCenterValue: Any = ...
    SetRadius: Any = ...
    Print: Any = ...
    GetBufferReference: Any = ...
    GetOffset: Any = ...
    GetNeighborhoodIndex: Any = ...
    GetCenterNeighborhoodIndex: Any = ...
    GetSlice: Any = ...

class itkNeighborhoodCVF22:
    thisown: Any = ...
    GetNameOfClass: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetRadius: Any = ...
    GetSize: Any = ...
    GetStride: Any = ...
    Size: Any = ...
    GetElement: Any = ...
    GetCenterValue: Any = ...
    SetRadius: Any = ...
    Print: Any = ...
    GetBufferReference: Any = ...
    GetOffset: Any = ...
    GetNeighborhoodIndex: Any = ...
    GetCenterNeighborhoodIndex: Any = ...
    GetSlice: Any = ...

class itkNeighborhoodCVF33:
    thisown: Any = ...
    GetNameOfClass: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetRadius: Any = ...
    GetSize: Any = ...
    GetStride: Any = ...
    Size: Any = ...
    GetElement: Any = ...
    GetCenterValue: Any = ...
    SetRadius: Any = ...
    Print: Any = ...
    GetBufferReference: Any = ...
    GetOffset: Any = ...
    GetNeighborhoodIndex: Any = ...
    GetCenterNeighborhoodIndex: Any = ...
    GetSlice: Any = ...

class itkNeighborhoodF2:
    thisown: Any = ...
    GetNameOfClass: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetRadius: Any = ...
    GetSize: Any = ...
    GetStride: Any = ...
    Size: Any = ...
    GetElement: Any = ...
    GetCenterValue: Any = ...
    SetRadius: Any = ...
    Print: Any = ...
    GetBufferReference: Any = ...
    GetOffset: Any = ...
    GetNeighborhoodIndex: Any = ...
    GetCenterNeighborhoodIndex: Any = ...
    GetSlice: Any = ...

class itkNeighborhoodF3:
    thisown: Any = ...
    GetNameOfClass: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetRadius: Any = ...
    GetSize: Any = ...
    GetStride: Any = ...
    Size: Any = ...
    GetElement: Any = ...
    GetCenterValue: Any = ...
    SetRadius: Any = ...
    Print: Any = ...
    GetBufferReference: Any = ...
    GetOffset: Any = ...
    GetNeighborhoodIndex: Any = ...
    GetCenterNeighborhoodIndex: Any = ...
    GetSlice: Any = ...

class itkNeighborhoodRGBUC2:
    thisown: Any = ...
    GetNameOfClass: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetRadius: Any = ...
    GetSize: Any = ...
    GetStride: Any = ...
    Size: Any = ...
    GetElement: Any = ...
    GetCenterValue: Any = ...
    SetRadius: Any = ...
    Print: Any = ...
    GetBufferReference: Any = ...
    GetOffset: Any = ...
    GetNeighborhoodIndex: Any = ...
    GetCenterNeighborhoodIndex: Any = ...
    GetSlice: Any = ...

class itkNeighborhoodRGBUC3:
    thisown: Any = ...
    GetNameOfClass: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetRadius: Any = ...
    GetSize: Any = ...
    GetStride: Any = ...
    Size: Any = ...
    GetElement: Any = ...
    GetCenterValue: Any = ...
    SetRadius: Any = ...
    Print: Any = ...
    GetBufferReference: Any = ...
    GetOffset: Any = ...
    GetNeighborhoodIndex: Any = ...
    GetCenterNeighborhoodIndex: Any = ...
    GetSlice: Any = ...

class itkNeighborhoodSS2:
    thisown: Any = ...
    GetNameOfClass: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetRadius: Any = ...
    GetSize: Any = ...
    GetStride: Any = ...
    Size: Any = ...
    GetElement: Any = ...
    GetCenterValue: Any = ...
    SetRadius: Any = ...
    Print: Any = ...
    GetBufferReference: Any = ...
    GetOffset: Any = ...
    GetNeighborhoodIndex: Any = ...
    GetCenterNeighborhoodIndex: Any = ...
    GetSlice: Any = ...

class itkNeighborhoodSS3:
    thisown: Any = ...
    GetNameOfClass: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetRadius: Any = ...
    GetSize: Any = ...
    GetStride: Any = ...
    Size: Any = ...
    GetElement: Any = ...
    GetCenterValue: Any = ...
    SetRadius: Any = ...
    Print: Any = ...
    GetBufferReference: Any = ...
    GetOffset: Any = ...
    GetNeighborhoodIndex: Any = ...
    GetCenterNeighborhoodIndex: Any = ...
    GetSlice: Any = ...

class itkNeighborhoodUC2:
    thisown: Any = ...
    GetNameOfClass: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetRadius: Any = ...
    GetSize: Any = ...
    GetStride: Any = ...
    Size: Any = ...
    GetElement: Any = ...
    GetCenterValue: Any = ...
    SetRadius: Any = ...
    Print: Any = ...
    GetBufferReference: Any = ...
    GetOffset: Any = ...
    GetNeighborhoodIndex: Any = ...
    GetCenterNeighborhoodIndex: Any = ...
    GetSlice: Any = ...

class itkNeighborhoodUC3:
    thisown: Any = ...
    GetNameOfClass: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetRadius: Any = ...
    GetSize: Any = ...
    GetStride: Any = ...
    Size: Any = ...
    GetElement: Any = ...
    GetCenterValue: Any = ...
    SetRadius: Any = ...
    Print: Any = ...
    GetBufferReference: Any = ...
    GetOffset: Any = ...
    GetNeighborhoodIndex: Any = ...
    GetCenterNeighborhoodIndex: Any = ...
    GetSlice: Any = ...

class itkNeighborhoodVF22:
    thisown: Any = ...
    GetNameOfClass: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetRadius: Any = ...
    GetSize: Any = ...
    GetStride: Any = ...
    Size: Any = ...
    GetElement: Any = ...
    GetCenterValue: Any = ...
    SetRadius: Any = ...
    Print: Any = ...
    GetBufferReference: Any = ...
    GetOffset: Any = ...
    GetNeighborhoodIndex: Any = ...
    GetCenterNeighborhoodIndex: Any = ...
    GetSlice: Any = ...

class itkNeighborhoodVF33:
    thisown: Any = ...
    GetNameOfClass: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetRadius: Any = ...
    GetSize: Any = ...
    GetStride: Any = ...
    Size: Any = ...
    GetElement: Any = ...
    GetCenterValue: Any = ...
    SetRadius: Any = ...
    Print: Any = ...
    GetBufferReference: Any = ...
    GetOffset: Any = ...
    GetNeighborhoodIndex: Any = ...
    GetCenterNeighborhoodIndex: Any = ...
    GetSlice: Any = ...
