import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkNeighborhoodConnectedImageFilterIF2IF2_New(): ...

class itkNeighborhoodConnectedImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    ClearSeeds: Any = ...
    SetSeed: Any = ...
    AddSeed: Any = ...
    SetLower: Any = ...
    GetLower: Any = ...
    SetUpper: Any = ...
    GetUpper: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    SameDimensionCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNeighborhoodConnectedImageFilterIF2IF2___New_orig__: Any
itkNeighborhoodConnectedImageFilterIF2IF2_cast: Any

def itkNeighborhoodConnectedImageFilterIF3IF3_New(): ...

class itkNeighborhoodConnectedImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    ClearSeeds: Any = ...
    SetSeed: Any = ...
    AddSeed: Any = ...
    SetLower: Any = ...
    GetLower: Any = ...
    SetUpper: Any = ...
    GetUpper: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    SameDimensionCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNeighborhoodConnectedImageFilterIF3IF3___New_orig__: Any
itkNeighborhoodConnectedImageFilterIF3IF3_cast: Any

def itkNeighborhoodConnectedImageFilterISS2ISS2_New(): ...

class itkNeighborhoodConnectedImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    ClearSeeds: Any = ...
    SetSeed: Any = ...
    AddSeed: Any = ...
    SetLower: Any = ...
    GetLower: Any = ...
    SetUpper: Any = ...
    GetUpper: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    SameDimensionCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNeighborhoodConnectedImageFilterISS2ISS2___New_orig__: Any
itkNeighborhoodConnectedImageFilterISS2ISS2_cast: Any

def itkNeighborhoodConnectedImageFilterISS3ISS3_New(): ...

class itkNeighborhoodConnectedImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    ClearSeeds: Any = ...
    SetSeed: Any = ...
    AddSeed: Any = ...
    SetLower: Any = ...
    GetLower: Any = ...
    SetUpper: Any = ...
    GetUpper: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    SameDimensionCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNeighborhoodConnectedImageFilterISS3ISS3___New_orig__: Any
itkNeighborhoodConnectedImageFilterISS3ISS3_cast: Any

def itkNeighborhoodConnectedImageFilterIUC2IUC2_New(): ...

class itkNeighborhoodConnectedImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    ClearSeeds: Any = ...
    SetSeed: Any = ...
    AddSeed: Any = ...
    SetLower: Any = ...
    GetLower: Any = ...
    SetUpper: Any = ...
    GetUpper: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    SameDimensionCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNeighborhoodConnectedImageFilterIUC2IUC2___New_orig__: Any
itkNeighborhoodConnectedImageFilterIUC2IUC2_cast: Any

def itkNeighborhoodConnectedImageFilterIUC3IUC3_New(): ...

class itkNeighborhoodConnectedImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PrintSelf: Any = ...
    ClearSeeds: Any = ...
    SetSeed: Any = ...
    AddSeed: Any = ...
    SetLower: Any = ...
    GetLower: Any = ...
    SetUpper: Any = ...
    GetUpper: Any = ...
    SetReplaceValue: Any = ...
    GetReplaceValue: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    SameDimensionCheck: Any = ...
    InputOStreamWritableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNeighborhoodConnectedImageFilterIUC3IUC3___New_orig__: Any
itkNeighborhoodConnectedImageFilterIUC3IUC3_cast: Any

def neighborhood_connected_image_filter(*args: Any, **kwargs: Any): ...
def neighborhood_connected_image_filter_init_docstring() -> None: ...
