import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkNaryAddImageFilterIF2IF2_Superclass_New(): ...

class itkNaryAddImageFilterIF2IF2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    OutputHasZeroCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryAddImageFilterIF2IF2_Superclass___New_orig__: Any
itkNaryAddImageFilterIF2IF2_Superclass_cast: Any

def itkNaryAddImageFilterIF3IF3_Superclass_New(): ...

class itkNaryAddImageFilterIF3IF3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    OutputHasZeroCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryAddImageFilterIF3IF3_Superclass___New_orig__: Any
itkNaryAddImageFilterIF3IF3_Superclass_cast: Any

def itkNaryAddImageFilterISS2ISS2_Superclass_New(): ...

class itkNaryAddImageFilterISS2ISS2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    OutputHasZeroCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryAddImageFilterISS2ISS2_Superclass___New_orig__: Any
itkNaryAddImageFilterISS2ISS2_Superclass_cast: Any

def itkNaryAddImageFilterISS3ISS3_Superclass_New(): ...

class itkNaryAddImageFilterISS3ISS3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    OutputHasZeroCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryAddImageFilterISS3ISS3_Superclass___New_orig__: Any
itkNaryAddImageFilterISS3ISS3_Superclass_cast: Any

def itkNaryAddImageFilterIUC2IUC2_Superclass_New(): ...

class itkNaryAddImageFilterIUC2IUC2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    OutputHasZeroCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryAddImageFilterIUC2IUC2_Superclass___New_orig__: Any
itkNaryAddImageFilterIUC2IUC2_Superclass_cast: Any

def itkNaryAddImageFilterIUC3IUC3_Superclass_New(): ...

class itkNaryAddImageFilterIUC3IUC3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    OutputHasZeroCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryAddImageFilterIUC3IUC3_Superclass___New_orig__: Any
itkNaryAddImageFilterIUC3IUC3_Superclass_cast: Any

def itkNaryAddImageFilterIF2IF2_New(): ...

class itkNaryAddImageFilterIF2IF2(itkNaryAddImageFilterIF2IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputHasZeroCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryAddImageFilterIF2IF2___New_orig__: Any
itkNaryAddImageFilterIF2IF2_cast: Any

def itkNaryAddImageFilterIF3IF3_New(): ...

class itkNaryAddImageFilterIF3IF3(itkNaryAddImageFilterIF3IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputHasZeroCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryAddImageFilterIF3IF3___New_orig__: Any
itkNaryAddImageFilterIF3IF3_cast: Any

def itkNaryAddImageFilterISS2ISS2_New(): ...

class itkNaryAddImageFilterISS2ISS2(itkNaryAddImageFilterISS2ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputHasZeroCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryAddImageFilterISS2ISS2___New_orig__: Any
itkNaryAddImageFilterISS2ISS2_cast: Any

def itkNaryAddImageFilterISS3ISS3_New(): ...

class itkNaryAddImageFilterISS3ISS3(itkNaryAddImageFilterISS3ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputHasZeroCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryAddImageFilterISS3ISS3___New_orig__: Any
itkNaryAddImageFilterISS3ISS3_cast: Any

def itkNaryAddImageFilterIUC2IUC2_New(): ...

class itkNaryAddImageFilterIUC2IUC2(itkNaryAddImageFilterIUC2IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputHasZeroCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryAddImageFilterIUC2IUC2___New_orig__: Any
itkNaryAddImageFilterIUC2IUC2_cast: Any

def itkNaryAddImageFilterIUC3IUC3_New(): ...

class itkNaryAddImageFilterIUC3IUC3(itkNaryAddImageFilterIUC3IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    InputHasZeroCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNaryAddImageFilterIUC3IUC3___New_orig__: Any
itkNaryAddImageFilterIUC3IUC3_cast: Any

def nary_add_image_filter(*args: Any, **kwargs: Any): ...
def nary_add_image_filter_init_docstring() -> None: ...
def nary_functor_image_filter(*args: Any, **kwargs: Any): ...
def nary_functor_image_filter_init_docstring() -> None: ...
