from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkNodePairI2F:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    SetValue: Any = ...
    GetValue: Any = ...
    SetNode: Any = ...
    GetNode: Any = ...
    __lt__: Any = ...
    __gt__: Any = ...
    __le__: Any = ...
    __ge__: Any = ...
    __swig_destroy__: Any = ...

class itkNodePairI2SS:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    SetValue: Any = ...
    GetValue: Any = ...
    SetNode: Any = ...
    GetNode: Any = ...
    __lt__: Any = ...
    __gt__: Any = ...
    __le__: Any = ...
    __ge__: Any = ...
    __swig_destroy__: Any = ...

class itkNodePairI2UC:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    SetValue: Any = ...
    GetValue: Any = ...
    SetNode: Any = ...
    GetNode: Any = ...
    __lt__: Any = ...
    __gt__: Any = ...
    __le__: Any = ...
    __ge__: Any = ...
    __swig_destroy__: Any = ...

class itkNodePairI3F:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    SetValue: Any = ...
    GetValue: Any = ...
    SetNode: Any = ...
    GetNode: Any = ...
    __lt__: Any = ...
    __gt__: Any = ...
    __le__: Any = ...
    __ge__: Any = ...
    __swig_destroy__: Any = ...

class itkNodePairI3SS:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    SetValue: Any = ...
    GetValue: Any = ...
    SetNode: Any = ...
    GetNode: Any = ...
    __lt__: Any = ...
    __gt__: Any = ...
    __le__: Any = ...
    __ge__: Any = ...
    __swig_destroy__: Any = ...

class itkNodePairI3UC:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    SetValue: Any = ...
    GetValue: Any = ...
    SetNode: Any = ...
    GetNode: Any = ...
    __lt__: Any = ...
    __gt__: Any = ...
    __le__: Any = ...
    __ge__: Any = ...
    __swig_destroy__: Any = ...
