import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkNormalizeImageFilterIF2IF2_New(): ...

class itkNormalizeImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNormalizeImageFilterIF2IF2___New_orig__: Any
itkNormalizeImageFilterIF2IF2_cast: Any

def itkNormalizeImageFilterIF3IF3_New(): ...

class itkNormalizeImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNormalizeImageFilterIF3IF3___New_orig__: Any
itkNormalizeImageFilterIF3IF3_cast: Any

def itkNormalizeImageFilterISS2ISS2_New(): ...

class itkNormalizeImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNormalizeImageFilterISS2ISS2___New_orig__: Any
itkNormalizeImageFilterISS2ISS2_cast: Any

def itkNormalizeImageFilterISS3ISS3_New(): ...

class itkNormalizeImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNormalizeImageFilterISS3ISS3___New_orig__: Any
itkNormalizeImageFilterISS3ISS3_cast: Any

def itkNormalizeImageFilterIUC2IUC2_New(): ...

class itkNormalizeImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNormalizeImageFilterIUC2IUC2___New_orig__: Any
itkNormalizeImageFilterIUC2IUC2_cast: Any

def itkNormalizeImageFilterIUC3IUC3_New(): ...

class itkNormalizeImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNormalizeImageFilterIUC3IUC3___New_orig__: Any
itkNormalizeImageFilterIUC3IUC3_cast: Any

def normalize_image_filter(*args: Any, **kwargs: Any): ...
def normalize_image_filter_init_docstring() -> None: ...
