import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkNarrowBandCurvesLevelSetImageFilterIF2IF2F_New(): ...

class itkNarrowBandCurvesLevelSetImageFilterIF2IF2F(itk.itkNarrowBandLevelSetImageFilterPython.itkNarrowBandLevelSetImageFilterIF2IF2F):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDerivativeSigma: Any = ...
    GetDerivativeSigma: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNarrowBandCurvesLevelSetImageFilterIF2IF2F___New_orig__: Any
itkNarrowBandCurvesLevelSetImageFilterIF2IF2F_cast: Any

def itkNarrowBandCurvesLevelSetImageFilterIF3IF3F_New(): ...

class itkNarrowBandCurvesLevelSetImageFilterIF3IF3F(itk.itkNarrowBandLevelSetImageFilterPython.itkNarrowBandLevelSetImageFilterIF3IF3F):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDerivativeSigma: Any = ...
    GetDerivativeSigma: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNarrowBandCurvesLevelSetImageFilterIF3IF3F___New_orig__: Any
itkNarrowBandCurvesLevelSetImageFilterIF3IF3F_cast: Any

def narrow_band_curves_level_set_image_filter(*args: Any, **kwargs: Any): ...
def narrow_band_curves_level_set_image_filter_init_docstring() -> None: ...
