import itk.itkFunctionBasePython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkNormalizedCorrelationImageToImageMetricIF2IF2_New(): ...

class itkNormalizedCorrelationImageToImageMetricIF2IF2(itk.itkImageToImageMetricPython.itkImageToImageMetricIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSubtractMean: Any = ...
    GetSubtractMean: Any = ...
    SubtractMeanOn: Any = ...
    SubtractMeanOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNormalizedCorrelationImageToImageMetricIF2IF2___New_orig__: Any
itkNormalizedCorrelationImageToImageMetricIF2IF2_cast: Any

def itkNormalizedCorrelationImageToImageMetricIF3IF3_New(): ...

class itkNormalizedCorrelationImageToImageMetricIF3IF3(itk.itkImageToImageMetricPython.itkImageToImageMetricIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSubtractMean: Any = ...
    GetSubtractMean: Any = ...
    SubtractMeanOn: Any = ...
    SubtractMeanOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNormalizedCorrelationImageToImageMetricIF3IF3___New_orig__: Any
itkNormalizedCorrelationImageToImageMetricIF3IF3_cast: Any

def itkNormalizedCorrelationImageToImageMetricISS2ISS2_New(): ...

class itkNormalizedCorrelationImageToImageMetricISS2ISS2(itk.itkImageToImageMetricPython.itkImageToImageMetricISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSubtractMean: Any = ...
    GetSubtractMean: Any = ...
    SubtractMeanOn: Any = ...
    SubtractMeanOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNormalizedCorrelationImageToImageMetricISS2ISS2___New_orig__: Any
itkNormalizedCorrelationImageToImageMetricISS2ISS2_cast: Any

def itkNormalizedCorrelationImageToImageMetricISS3ISS3_New(): ...

class itkNormalizedCorrelationImageToImageMetricISS3ISS3(itk.itkImageToImageMetricPython.itkImageToImageMetricISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSubtractMean: Any = ...
    GetSubtractMean: Any = ...
    SubtractMeanOn: Any = ...
    SubtractMeanOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNormalizedCorrelationImageToImageMetricISS3ISS3___New_orig__: Any
itkNormalizedCorrelationImageToImageMetricISS3ISS3_cast: Any

def itkNormalizedCorrelationImageToImageMetricIUC2IUC2_New(): ...

class itkNormalizedCorrelationImageToImageMetricIUC2IUC2(itk.itkImageToImageMetricPython.itkImageToImageMetricIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSubtractMean: Any = ...
    GetSubtractMean: Any = ...
    SubtractMeanOn: Any = ...
    SubtractMeanOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNormalizedCorrelationImageToImageMetricIUC2IUC2___New_orig__: Any
itkNormalizedCorrelationImageToImageMetricIUC2IUC2_cast: Any

def itkNormalizedCorrelationImageToImageMetricIUC3IUC3_New(): ...

class itkNormalizedCorrelationImageToImageMetricIUC3IUC3(itk.itkImageToImageMetricPython.itkImageToImageMetricIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSubtractMean: Any = ...
    GetSubtractMean: Any = ...
    SubtractMeanOn: Any = ...
    SubtractMeanOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNormalizedCorrelationImageToImageMetricIUC3IUC3___New_orig__: Any
itkNormalizedCorrelationImageToImageMetricIUC3IUC3_cast: Any
