import itk.itkImageToImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkOrientImageFilterICF3ICF3_New(): ...

class itkOrientImageFilterICF3ICF3(itk.itkImageToImageFilterBPython.itkImageToImageFilterICF3ICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateDirection: Any = ...
    GetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    GetUseImageDirection: Any = ...
    SetUseImageDirection: Any = ...
    GetPermuteOrder: Any = ...
    GetFlipAxes: Any = ...
    SetDesiredCoordinateOrientationToAxial: Any = ...
    SetDesiredCoordinateOrientationToCoronal: Any = ...
    SetDesiredCoordinateOrientationToSagittal: Any = ...
    GenerateOutputInformation: Any = ...
    InputConvertibleToOutput: Any = ...
    SameDimension: Any = ...
    DimensionShouldBe3: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOrientImageFilterICF3ICF3___New_orig__: Any
itkOrientImageFilterICF3ICF3_cast: Any

def itkOrientImageFilterICVF23ICVF23_New(): ...

class itkOrientImageFilterICVF23ICVF23(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF23ICVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateDirection: Any = ...
    GetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    GetUseImageDirection: Any = ...
    SetUseImageDirection: Any = ...
    GetPermuteOrder: Any = ...
    GetFlipAxes: Any = ...
    SetDesiredCoordinateOrientationToAxial: Any = ...
    SetDesiredCoordinateOrientationToCoronal: Any = ...
    SetDesiredCoordinateOrientationToSagittal: Any = ...
    GenerateOutputInformation: Any = ...
    InputConvertibleToOutput: Any = ...
    SameDimension: Any = ...
    DimensionShouldBe3: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOrientImageFilterICVF23ICVF23___New_orig__: Any
itkOrientImageFilterICVF23ICVF23_cast: Any

def itkOrientImageFilterICVF33ICVF33_New(): ...

class itkOrientImageFilterICVF33ICVF33(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF33ICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateDirection: Any = ...
    GetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    GetUseImageDirection: Any = ...
    SetUseImageDirection: Any = ...
    GetPermuteOrder: Any = ...
    GetFlipAxes: Any = ...
    SetDesiredCoordinateOrientationToAxial: Any = ...
    SetDesiredCoordinateOrientationToCoronal: Any = ...
    SetDesiredCoordinateOrientationToSagittal: Any = ...
    GenerateOutputInformation: Any = ...
    InputConvertibleToOutput: Any = ...
    SameDimension: Any = ...
    DimensionShouldBe3: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOrientImageFilterICVF33ICVF33___New_orig__: Any
itkOrientImageFilterICVF33ICVF33_cast: Any

def itkOrientImageFilterICVF43ICVF43_New(): ...

class itkOrientImageFilterICVF43ICVF43(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF43ICVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateDirection: Any = ...
    GetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    GetUseImageDirection: Any = ...
    SetUseImageDirection: Any = ...
    GetPermuteOrder: Any = ...
    GetFlipAxes: Any = ...
    SetDesiredCoordinateOrientationToAxial: Any = ...
    SetDesiredCoordinateOrientationToCoronal: Any = ...
    SetDesiredCoordinateOrientationToSagittal: Any = ...
    GenerateOutputInformation: Any = ...
    InputConvertibleToOutput: Any = ...
    SameDimension: Any = ...
    DimensionShouldBe3: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOrientImageFilterICVF43ICVF43___New_orig__: Any
itkOrientImageFilterICVF43ICVF43_cast: Any

def itkOrientImageFilterIF3IF3_New(): ...

class itkOrientImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateDirection: Any = ...
    GetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    GetUseImageDirection: Any = ...
    SetUseImageDirection: Any = ...
    GetPermuteOrder: Any = ...
    GetFlipAxes: Any = ...
    SetDesiredCoordinateOrientationToAxial: Any = ...
    SetDesiredCoordinateOrientationToCoronal: Any = ...
    SetDesiredCoordinateOrientationToSagittal: Any = ...
    GenerateOutputInformation: Any = ...
    InputConvertibleToOutput: Any = ...
    SameDimension: Any = ...
    DimensionShouldBe3: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOrientImageFilterIF3IF3___New_orig__: Any
itkOrientImageFilterIF3IF3_cast: Any

def itkOrientImageFilterIRGBAUC3IRGBAUC3_New(): ...

class itkOrientImageFilterIRGBAUC3IRGBAUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBAUC3IRGBAUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateDirection: Any = ...
    GetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    GetUseImageDirection: Any = ...
    SetUseImageDirection: Any = ...
    GetPermuteOrder: Any = ...
    GetFlipAxes: Any = ...
    SetDesiredCoordinateOrientationToAxial: Any = ...
    SetDesiredCoordinateOrientationToCoronal: Any = ...
    SetDesiredCoordinateOrientationToSagittal: Any = ...
    GenerateOutputInformation: Any = ...
    InputConvertibleToOutput: Any = ...
    SameDimension: Any = ...
    DimensionShouldBe3: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOrientImageFilterIRGBAUC3IRGBAUC3___New_orig__: Any
itkOrientImageFilterIRGBAUC3IRGBAUC3_cast: Any

def itkOrientImageFilterIRGBUC3IRGBUC3_New(): ...

class itkOrientImageFilterIRGBUC3IRGBUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBUC3IRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateDirection: Any = ...
    GetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    GetUseImageDirection: Any = ...
    SetUseImageDirection: Any = ...
    GetPermuteOrder: Any = ...
    GetFlipAxes: Any = ...
    SetDesiredCoordinateOrientationToAxial: Any = ...
    SetDesiredCoordinateOrientationToCoronal: Any = ...
    SetDesiredCoordinateOrientationToSagittal: Any = ...
    GenerateOutputInformation: Any = ...
    InputConvertibleToOutput: Any = ...
    SameDimension: Any = ...
    DimensionShouldBe3: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOrientImageFilterIRGBUC3IRGBUC3___New_orig__: Any
itkOrientImageFilterIRGBUC3IRGBUC3_cast: Any

def itkOrientImageFilterISS3ISS3_New(): ...

class itkOrientImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateDirection: Any = ...
    GetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    GetUseImageDirection: Any = ...
    SetUseImageDirection: Any = ...
    GetPermuteOrder: Any = ...
    GetFlipAxes: Any = ...
    SetDesiredCoordinateOrientationToAxial: Any = ...
    SetDesiredCoordinateOrientationToCoronal: Any = ...
    SetDesiredCoordinateOrientationToSagittal: Any = ...
    GenerateOutputInformation: Any = ...
    InputConvertibleToOutput: Any = ...
    SameDimension: Any = ...
    DimensionShouldBe3: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOrientImageFilterISS3ISS3___New_orig__: Any
itkOrientImageFilterISS3ISS3_cast: Any

def itkOrientImageFilterIUC3IUC3_New(): ...

class itkOrientImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateDirection: Any = ...
    GetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    GetUseImageDirection: Any = ...
    SetUseImageDirection: Any = ...
    GetPermuteOrder: Any = ...
    GetFlipAxes: Any = ...
    SetDesiredCoordinateOrientationToAxial: Any = ...
    SetDesiredCoordinateOrientationToCoronal: Any = ...
    SetDesiredCoordinateOrientationToSagittal: Any = ...
    GenerateOutputInformation: Any = ...
    InputConvertibleToOutput: Any = ...
    SameDimension: Any = ...
    DimensionShouldBe3: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOrientImageFilterIUC3IUC3___New_orig__: Any
itkOrientImageFilterIUC3IUC3_cast: Any

def itkOrientImageFilterIVF23IVF23_New(): ...

class itkOrientImageFilterIVF23IVF23(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF23IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateDirection: Any = ...
    GetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    GetUseImageDirection: Any = ...
    SetUseImageDirection: Any = ...
    GetPermuteOrder: Any = ...
    GetFlipAxes: Any = ...
    SetDesiredCoordinateOrientationToAxial: Any = ...
    SetDesiredCoordinateOrientationToCoronal: Any = ...
    SetDesiredCoordinateOrientationToSagittal: Any = ...
    GenerateOutputInformation: Any = ...
    InputConvertibleToOutput: Any = ...
    SameDimension: Any = ...
    DimensionShouldBe3: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOrientImageFilterIVF23IVF23___New_orig__: Any
itkOrientImageFilterIVF23IVF23_cast: Any

def itkOrientImageFilterIVF33IVF33_New(): ...

class itkOrientImageFilterIVF33IVF33(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF33IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateDirection: Any = ...
    GetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    GetUseImageDirection: Any = ...
    SetUseImageDirection: Any = ...
    GetPermuteOrder: Any = ...
    GetFlipAxes: Any = ...
    SetDesiredCoordinateOrientationToAxial: Any = ...
    SetDesiredCoordinateOrientationToCoronal: Any = ...
    SetDesiredCoordinateOrientationToSagittal: Any = ...
    GenerateOutputInformation: Any = ...
    InputConvertibleToOutput: Any = ...
    SameDimension: Any = ...
    DimensionShouldBe3: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOrientImageFilterIVF33IVF33___New_orig__: Any
itkOrientImageFilterIVF33IVF33_cast: Any

def itkOrientImageFilterIVF43IVF43_New(): ...

class itkOrientImageFilterIVF43IVF43(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF43IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateOrientation: Any = ...
    SetGivenCoordinateDirection: Any = ...
    GetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateOrientation: Any = ...
    SetDesiredCoordinateDirection: Any = ...
    UseImageDirectionOn: Any = ...
    UseImageDirectionOff: Any = ...
    GetUseImageDirection: Any = ...
    SetUseImageDirection: Any = ...
    GetPermuteOrder: Any = ...
    GetFlipAxes: Any = ...
    SetDesiredCoordinateOrientationToAxial: Any = ...
    SetDesiredCoordinateOrientationToCoronal: Any = ...
    SetDesiredCoordinateOrientationToSagittal: Any = ...
    GenerateOutputInformation: Any = ...
    InputConvertibleToOutput: Any = ...
    SameDimension: Any = ...
    DimensionShouldBe3: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOrientImageFilterIVF43IVF43___New_orig__: Any
itkOrientImageFilterIVF43IVF43_cast: Any

def orient_image_filter(*args: Any, **kwargs: Any): ...
def orient_image_filter_init_docstring() -> None: ...
