import itk.itkImageSourceCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkOtsuThresholdImageFilterIF2ISS2_New(): ...

class itkOtsuThresholdImageFilterIF2ISS2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReturnBinMidpoint: Any = ...
    GetReturnBinMidpoint: Any = ...
    ReturnBinMidpointOn: Any = ...
    ReturnBinMidpointOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOtsuThresholdImageFilterIF2ISS2___New_orig__: Any
itkOtsuThresholdImageFilterIF2ISS2_cast: Any

def itkOtsuThresholdImageFilterIF2IUC2_New(): ...

class itkOtsuThresholdImageFilterIF2IUC2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReturnBinMidpoint: Any = ...
    GetReturnBinMidpoint: Any = ...
    ReturnBinMidpointOn: Any = ...
    ReturnBinMidpointOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOtsuThresholdImageFilterIF2IUC2___New_orig__: Any
itkOtsuThresholdImageFilterIF2IUC2_cast: Any

def itkOtsuThresholdImageFilterIF3ISS3_New(): ...

class itkOtsuThresholdImageFilterIF3ISS3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReturnBinMidpoint: Any = ...
    GetReturnBinMidpoint: Any = ...
    ReturnBinMidpointOn: Any = ...
    ReturnBinMidpointOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOtsuThresholdImageFilterIF3ISS3___New_orig__: Any
itkOtsuThresholdImageFilterIF3ISS3_cast: Any

def itkOtsuThresholdImageFilterIF3IUC3_New(): ...

class itkOtsuThresholdImageFilterIF3IUC3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReturnBinMidpoint: Any = ...
    GetReturnBinMidpoint: Any = ...
    ReturnBinMidpointOn: Any = ...
    ReturnBinMidpointOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOtsuThresholdImageFilterIF3IUC3___New_orig__: Any
itkOtsuThresholdImageFilterIF3IUC3_cast: Any

def itkOtsuThresholdImageFilterISS2ISS2_New(): ...

class itkOtsuThresholdImageFilterISS2ISS2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReturnBinMidpoint: Any = ...
    GetReturnBinMidpoint: Any = ...
    ReturnBinMidpointOn: Any = ...
    ReturnBinMidpointOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOtsuThresholdImageFilterISS2ISS2___New_orig__: Any
itkOtsuThresholdImageFilterISS2ISS2_cast: Any

def itkOtsuThresholdImageFilterISS2IUC2_New(): ...

class itkOtsuThresholdImageFilterISS2IUC2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReturnBinMidpoint: Any = ...
    GetReturnBinMidpoint: Any = ...
    ReturnBinMidpointOn: Any = ...
    ReturnBinMidpointOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOtsuThresholdImageFilterISS2IUC2___New_orig__: Any
itkOtsuThresholdImageFilterISS2IUC2_cast: Any

def itkOtsuThresholdImageFilterISS3ISS3_New(): ...

class itkOtsuThresholdImageFilterISS3ISS3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReturnBinMidpoint: Any = ...
    GetReturnBinMidpoint: Any = ...
    ReturnBinMidpointOn: Any = ...
    ReturnBinMidpointOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOtsuThresholdImageFilterISS3ISS3___New_orig__: Any
itkOtsuThresholdImageFilterISS3ISS3_cast: Any

def itkOtsuThresholdImageFilterISS3IUC3_New(): ...

class itkOtsuThresholdImageFilterISS3IUC3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReturnBinMidpoint: Any = ...
    GetReturnBinMidpoint: Any = ...
    ReturnBinMidpointOn: Any = ...
    ReturnBinMidpointOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOtsuThresholdImageFilterISS3IUC3___New_orig__: Any
itkOtsuThresholdImageFilterISS3IUC3_cast: Any

def itkOtsuThresholdImageFilterIUC2ISS2_New(): ...

class itkOtsuThresholdImageFilterIUC2ISS2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReturnBinMidpoint: Any = ...
    GetReturnBinMidpoint: Any = ...
    ReturnBinMidpointOn: Any = ...
    ReturnBinMidpointOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOtsuThresholdImageFilterIUC2ISS2___New_orig__: Any
itkOtsuThresholdImageFilterIUC2ISS2_cast: Any

def itkOtsuThresholdImageFilterIUC2IUC2_New(): ...

class itkOtsuThresholdImageFilterIUC2IUC2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReturnBinMidpoint: Any = ...
    GetReturnBinMidpoint: Any = ...
    ReturnBinMidpointOn: Any = ...
    ReturnBinMidpointOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOtsuThresholdImageFilterIUC2IUC2___New_orig__: Any
itkOtsuThresholdImageFilterIUC2IUC2_cast: Any

def itkOtsuThresholdImageFilterIUC3ISS3_New(): ...

class itkOtsuThresholdImageFilterIUC3ISS3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReturnBinMidpoint: Any = ...
    GetReturnBinMidpoint: Any = ...
    ReturnBinMidpointOn: Any = ...
    ReturnBinMidpointOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOtsuThresholdImageFilterIUC3ISS3___New_orig__: Any
itkOtsuThresholdImageFilterIUC3ISS3_cast: Any

def itkOtsuThresholdImageFilterIUC3IUC3_New(): ...

class itkOtsuThresholdImageFilterIUC3IUC3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReturnBinMidpoint: Any = ...
    GetReturnBinMidpoint: Any = ...
    ReturnBinMidpointOn: Any = ...
    ReturnBinMidpointOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOtsuThresholdImageFilterIUC3IUC3___New_orig__: Any
itkOtsuThresholdImageFilterIUC3IUC3_cast: Any

def otsu_threshold_image_filter(*args: Any, **kwargs: Any): ...
def otsu_threshold_image_filter_init_docstring() -> None: ...
