import itk.itkArray2DPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkFRPROptimizerEnums:
    thisown: Any = ...
    Optimization_FletchReeves: Any = ...
    Optimization_PolakRibiere: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...

class itkGradientDescentOptimizerEnums:
    thisown: Any = ...
    StopConditionGradientDescentOptimizer_MaximumNumberOfIterations: Any = ...
    StopConditionGradientDescentOptimizer_MetricError: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...

def itkOptimizer_New(): ...

class itkOptimizer(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInitialPosition: Any = ...
    GetInitialPosition: Any = ...
    SetScales: Any = ...
    GetScales: Any = ...
    GetInverseScales: Any = ...
    GetCurrentPosition: Any = ...
    StartOptimization: Any = ...
    GetStopConditionDescription: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOptimizer___New_orig__: Any
itkOptimizer_cast: Any

class itkRegularStepGradientDescentBaseOptimizerEnums:
    thisown: Any = ...
    StopCondition_GradientMagnitudeTolerance: Any = ...
    StopCondition_StepTooSmall: Any = ...
    StopCondition_ImageNotAvailable: Any = ...
    StopCondition_CostFunctionError: Any = ...
    StopCondition_MaximumNumberOfIterations: Any = ...
    StopCondition_Unknown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...

class itkSPSAOptimizerEnums:
    thisown: Any = ...
    StopConditionSPSAOptimizer_Unknown: Any = ...
    StopConditionSPSAOptimizer_MaximumNumberOfIterations: Any = ...
    StopConditionSPSAOptimizer_BelowTolerance: Any = ...
    StopConditionSPSAOptimizer_MetricError: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...

def itkNonLinearOptimizer_New(): ...

class itkNonLinearOptimizer(itkOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkNonLinearOptimizer___New_orig__: Any
itkNonLinearOptimizer_cast: Any

def itkSingleValuedNonLinearOptimizer_New(): ...

class itkSingleValuedNonLinearOptimizer(itkNonLinearOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCostFunction: Any = ...
    GetModifiableCostFunction: Any = ...
    GetCostFunction: Any = ...
    GetValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSingleValuedNonLinearOptimizer___New_orig__: Any
itkSingleValuedNonLinearOptimizer_cast: Any

class itkSingleValuedNonLinearVnlOptimizer(itkSingleValuedNonLinearOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetMaximize: Any = ...
    SetMaximize: Any = ...
    MaximizeOn: Any = ...
    MaximizeOff: Any = ...
    GetMinimize: Any = ...
    SetMinimize: Any = ...
    MinimizeOn: Any = ...
    MinimizeOff: Any = ...
    GetCachedValue: Any = ...
    GetCachedDerivative: Any = ...
    GetCachedCurrentPosition: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSingleValuedNonLinearVnlOptimizer_cast: Any

def itkAmoebaOptimizer_New(): ...

class itkAmoebaOptimizer(itkSingleValuedNonLinearVnlOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaximumNumberOfIterations: Any = ...
    GetMaximumNumberOfIterations: Any = ...
    SetAutomaticInitialSimplex: Any = ...
    AutomaticInitialSimplexOn: Any = ...
    AutomaticInitialSimplexOff: Any = ...
    GetAutomaticInitialSimplex: Any = ...
    SetOptimizeWithRestarts: Any = ...
    OptimizeWithRestartsOn: Any = ...
    OptimizeWithRestartsOff: Any = ...
    GetOptimizeWithRestarts: Any = ...
    SetInitialSimplexDelta: Any = ...
    GetInitialSimplexDelta: Any = ...
    SetParametersConvergenceTolerance: Any = ...
    GetParametersConvergenceTolerance: Any = ...
    SetFunctionConvergenceTolerance: Any = ...
    GetFunctionConvergenceTolerance: Any = ...
    GetValue: Any = ...
    GetOptimizer: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkAmoebaOptimizer___New_orig__: Any
itkAmoebaOptimizer_cast: Any

def itkConjugateGradientOptimizer_New(): ...

class itkConjugateGradientOptimizer(itkSingleValuedNonLinearVnlOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOptimizer: Any = ...
    GetNumberOfIterations: Any = ...
    GetCurrentIteration: Any = ...
    GetValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkConjugateGradientOptimizer___New_orig__: Any
itkConjugateGradientOptimizer_cast: Any

def itkExhaustiveOptimizer_New(): ...

class itkExhaustiveOptimizer(itkSingleValuedNonLinearOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    StartWalking: Any = ...
    ResumeWalking: Any = ...
    StopWalking: Any = ...
    SetStepLength: Any = ...
    SetNumberOfSteps: Any = ...
    GetStepLength: Any = ...
    GetNumberOfSteps: Any = ...
    GetCurrentValue: Any = ...
    GetMaximumMetricValue: Any = ...
    GetMinimumMetricValue: Any = ...
    GetMinimumMetricValuePosition: Any = ...
    GetMaximumMetricValuePosition: Any = ...
    GetCurrentIndex: Any = ...
    GetMaximumNumberOfIterations: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkExhaustiveOptimizer___New_orig__: Any
itkExhaustiveOptimizer_cast: Any

def itkGradientDescentOptimizer_New(): ...

class itkGradientDescentOptimizer(itkSingleValuedNonLinearOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaximize: Any = ...
    SetMaximize: Any = ...
    MaximizeOn: Any = ...
    MaximizeOff: Any = ...
    GetMinimize: Any = ...
    SetMinimize: Any = ...
    MinimizeOn: Any = ...
    MinimizeOff: Any = ...
    AdvanceOneStep: Any = ...
    ResumeOptimization: Any = ...
    StopOptimization: Any = ...
    SetLearningRate: Any = ...
    GetLearningRate: Any = ...
    SetNumberOfIterations: Any = ...
    GetNumberOfIterations: Any = ...
    GetCurrentIteration: Any = ...
    GetValue: Any = ...
    GetStopCondition: Any = ...
    GetGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkGradientDescentOptimizer___New_orig__: Any
itkGradientDescentOptimizer_cast: Any

def itkLBFGSBOptimizer_New(): ...

class itkLBFGSBOptimizer(itkSingleValuedNonLinearVnlOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetTrace: Any = ...
    GetTrace: Any = ...
    TraceOn: Any = ...
    TraceOff: Any = ...
    SetLowerBound: Any = ...
    GetLowerBound: Any = ...
    SetUpperBound: Any = ...
    GetUpperBound: Any = ...
    SetBoundSelection: Any = ...
    GetBoundSelection: Any = ...
    SetCostFunctionConvergenceFactor: Any = ...
    GetCostFunctionConvergenceFactor: Any = ...
    SetProjectedGradientTolerance: Any = ...
    GetProjectedGradientTolerance: Any = ...
    SetMaximumNumberOfIterations: Any = ...
    GetMaximumNumberOfIterations: Any = ...
    SetMaximumNumberOfEvaluations: Any = ...
    GetMaximumNumberOfEvaluations: Any = ...
    SetMaximumNumberOfCorrections: Any = ...
    GetMaximumNumberOfCorrections: Any = ...
    SetScales: Any = ...
    GetCurrentIteration: Any = ...
    GetValue: Any = ...
    GetInfinityNormOfProjectedGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLBFGSBOptimizer___New_orig__: Any
itkLBFGSBOptimizer_cast: Any

def itkLBFGSOptimizer_New(): ...

class itkLBFGSOptimizer(itkSingleValuedNonLinearVnlOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOptimizer: Any = ...
    SetTrace: Any = ...
    GetTrace: Any = ...
    TraceOn: Any = ...
    TraceOff: Any = ...
    SetMaximumNumberOfFunctionEvaluations: Any = ...
    GetMaximumNumberOfFunctionEvaluations: Any = ...
    SetGradientConvergenceTolerance: Any = ...
    GetGradientConvergenceTolerance: Any = ...
    SetLineSearchAccuracy: Any = ...
    GetLineSearchAccuracy: Any = ...
    SetDefaultStepLength: Any = ...
    GetDefaultStepLength: Any = ...
    GetValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLBFGSOptimizer___New_orig__: Any
itkLBFGSOptimizer_cast: Any

def itkMultipleValuedNonLinearOptimizer_New(): ...

class itkMultipleValuedNonLinearOptimizer(itkNonLinearOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCostFunction: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMultipleValuedNonLinearOptimizer___New_orig__: Any
itkMultipleValuedNonLinearOptimizer_cast: Any

class itkMultipleValuedNonLinearVnlOptimizer(itkMultipleValuedNonLinearOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetUseCostFunctionGradient: Any = ...
    UseCostFunctionGradientOn: Any = ...
    UseCostFunctionGradientOff: Any = ...
    GetUseCostFunctionGradient: Any = ...
    GetCachedValue: Any = ...
    GetCachedDerivative: Any = ...
    GetCachedCurrentPosition: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkMultipleValuedNonLinearVnlOptimizer_cast: Any

def itkOnePlusOneEvolutionaryOptimizer_New(): ...

class itkOnePlusOneEvolutionaryOptimizer(itkSingleValuedNonLinearOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaximize: Any = ...
    MaximizeOn: Any = ...
    MaximizeOff: Any = ...
    GetMaximize: Any = ...
    GetMinimize: Any = ...
    SetMinimize: Any = ...
    MinimizeOn: Any = ...
    MinimizeOff: Any = ...
    SetMaximumIteration: Any = ...
    GetMaximumIteration: Any = ...
    SetGrowthFactor: Any = ...
    GetGrowthFactor: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactor: Any = ...
    SetInitialRadius: Any = ...
    GetInitialRadius: Any = ...
    SetEpsilon: Any = ...
    GetEpsilon: Any = ...
    GetFrobeniusNorm: Any = ...
    SetNormalVariateGenerator: Any = ...
    Initialize: Any = ...
    GetCurrentCost: Any = ...
    GetValue: Any = ...
    GetCurrentIteration: Any = ...
    GetInitialized: Any = ...
    StopOptimization: Any = ...
    GetCatchGetValueException: Any = ...
    SetCatchGetValueException: Any = ...
    GetMetricWorstPossibleValue: Any = ...
    SetMetricWorstPossibleValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOnePlusOneEvolutionaryOptimizer___New_orig__: Any
itkOnePlusOneEvolutionaryOptimizer_cast: Any

class itkParticleSwarmOptimizerBase(itkSingleValuedNonLinearOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInitializeNormalDistribution: Any = ...
    GetInitializeNormalDistribution: Any = ...
    InitializeNormalDistributionOn: Any = ...
    InitializeNormalDistributionOff: Any = ...
    SetInitialSwarm: Any = ...
    ClearSwarm: Any = ...
    SetPrintSwarm: Any = ...
    GetPrintSwarm: Any = ...
    PrintSwarmOn: Any = ...
    PrintSwarmOff: Any = ...
    SetNumberOfParticles: Any = ...
    GetNumberOfParticles: Any = ...
    SetMaximalNumberOfIterations: Any = ...
    GetMaximalNumberOfIterations: Any = ...
    SetNumberOfGenerationsWithMinimalImprovement: Any = ...
    GetNumberOfGenerationsWithMinimalImprovement: Any = ...
    SetParameterBounds: Any = ...
    GetParameterBounds: Any = ...
    SetFunctionConvergenceTolerance: Any = ...
    GetFunctionConvergenceTolerance: Any = ...
    SetParametersConvergenceTolerance: Any = ...
    GetParametersConvergenceTolerance: Any = ...
    GetPercentageParticlesConverged: Any = ...
    SetPercentageParticlesConverged: Any = ...
    SetSeed: Any = ...
    GetSeed: Any = ...
    SetUseSeed: Any = ...
    GetUseSeed: Any = ...
    UseSeedOn: Any = ...
    UseSeedOff: Any = ...
    GetValue: Any = ...
    PrintSwarm: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkParticleSwarmOptimizerBase_cast: Any

def itkPowellOptimizer_New(): ...

class itkPowellOptimizer(itkSingleValuedNonLinearOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaximize: Any = ...
    MaximizeOn: Any = ...
    MaximizeOff: Any = ...
    GetMaximize: Any = ...
    SetMaximumIteration: Any = ...
    GetMaximumIteration: Any = ...
    SetMaximumLineIteration: Any = ...
    GetMaximumLineIteration: Any = ...
    SetStepLength: Any = ...
    GetStepLength: Any = ...
    SetStepTolerance: Any = ...
    GetStepTolerance: Any = ...
    SetValueTolerance: Any = ...
    GetValueTolerance: Any = ...
    GetCurrentCost: Any = ...
    GetValue: Any = ...
    GetCurrentIteration: Any = ...
    GetCurrentLineIteration: Any = ...
    StopOptimization: Any = ...
    GetCatchGetValueException: Any = ...
    SetCatchGetValueException: Any = ...
    GetMetricWorstPossibleValue: Any = ...
    SetMetricWorstPossibleValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPowellOptimizer___New_orig__: Any
itkPowellOptimizer_cast: Any

def itkQuaternionRigidTransformGradientDescentOptimizer_New(): ...

class itkQuaternionRigidTransformGradientDescentOptimizer(itkGradientDescentOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkQuaternionRigidTransformGradientDescentOptimizer___New_orig__: Any
itkQuaternionRigidTransformGradientDescentOptimizer_cast: Any

def itkRegularStepGradientDescentBaseOptimizer_New(): ...

class itkRegularStepGradientDescentBaseOptimizer(itkSingleValuedNonLinearOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMaximize: Any = ...
    GetMaximize: Any = ...
    MaximizeOn: Any = ...
    MaximizeOff: Any = ...
    GetMinimize: Any = ...
    SetMinimize: Any = ...
    MinimizeOn: Any = ...
    MinimizeOff: Any = ...
    ResumeOptimization: Any = ...
    StopOptimization: Any = ...
    SetMaximumStepLength: Any = ...
    SetMinimumStepLength: Any = ...
    SetRelaxationFactor: Any = ...
    SetNumberOfIterations: Any = ...
    SetGradientMagnitudeTolerance: Any = ...
    GetCurrentStepLength: Any = ...
    GetMaximumStepLength: Any = ...
    GetMinimumStepLength: Any = ...
    GetRelaxationFactor: Any = ...
    GetNumberOfIterations: Any = ...
    GetGradientMagnitudeTolerance: Any = ...
    GetCurrentIteration: Any = ...
    GetStopCondition: Any = ...
    GetValue: Any = ...
    GetGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRegularStepGradientDescentBaseOptimizer___New_orig__: Any
itkRegularStepGradientDescentBaseOptimizer_cast: Any

def itkRegularStepGradientDescentOptimizer_New(): ...

class itkRegularStepGradientDescentOptimizer(itkRegularStepGradientDescentBaseOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRegularStepGradientDescentOptimizer___New_orig__: Any
itkRegularStepGradientDescentOptimizer_cast: Any

def itkSPSAOptimizer_New(): ...

class itkSPSAOptimizer(itkSingleValuedNonLinearOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    AdvanceOneStep: Any = ...
    ResumeOptimization: Any = ...
    StopOptimization: Any = ...
    GetValue: Any = ...
    GuessParameters: Any = ...
    GetCurrentIteration: Any = ...
    GetStopCondition: Any = ...
    GetLearningRate: Any = ...
    GetGradientMagnitude: Any = ...
    GetGradient: Any = ...
    SetSa: Any = ...
    GetSa: Any = ...
    Seta: Any = ...
    Geta: Any = ...
    SetSc: Any = ...
    GetSc: Any = ...
    Setc: Any = ...
    Getc: Any = ...
    SetA: Any = ...
    GetA: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetGamma: Any = ...
    GetGamma: Any = ...
    GetMaximize: Any = ...
    SetMaximize: Any = ...
    MaximizeOn: Any = ...
    MaximizeOff: Any = ...
    GetMinimize: Any = ...
    SetMinimize: Any = ...
    MinimizeOn: Any = ...
    MinimizeOff: Any = ...
    SetNumberOfPerturbations: Any = ...
    GetNumberOfPerturbations: Any = ...
    GetStateOfConvergence: Any = ...
    SetStateOfConvergenceDecayRate: Any = ...
    GetStateOfConvergenceDecayRate: Any = ...
    SetMinimumNumberOfIterations: Any = ...
    GetMinimumNumberOfIterations: Any = ...
    SetMaximumNumberOfIterations: Any = ...
    GetMaximumNumberOfIterations: Any = ...
    SetTolerance: Any = ...
    GetTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSPSAOptimizer___New_orig__: Any
itkSPSAOptimizer_cast: Any

def itkVersorRigid3DTransformOptimizer_New(): ...

class itkVersorRigid3DTransformOptimizer(itkRegularStepGradientDescentBaseOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    StepAlongGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVersorRigid3DTransformOptimizer___New_orig__: Any
itkVersorRigid3DTransformOptimizer_cast: Any

def itkVersorTransformOptimizer_New(): ...

class itkVersorTransformOptimizer(itkRegularStepGradientDescentBaseOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    StepAlongGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVersorTransformOptimizer___New_orig__: Any
itkVersorTransformOptimizer_cast: Any

def itkCumulativeGaussianOptimizer_New(): ...

class itkCumulativeGaussianOptimizer(itkMultipleValuedNonLinearOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDifferenceTolerance: Any = ...
    GetDifferenceTolerance: Any = ...
    SetVerbose: Any = ...
    GetVerbose: Any = ...
    GetComputedMean: Any = ...
    GetComputedStandardDeviation: Any = ...
    GetUpperAsymptote: Any = ...
    GetLowerAsymptote: Any = ...
    GetFinalSampledArray: Any = ...
    GetFitError: Any = ...
    SetDataArray: Any = ...
    PrintArray: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkCumulativeGaussianOptimizer___New_orig__: Any
itkCumulativeGaussianOptimizer_cast: Any

def itkFRPROptimizer_New(): ...

class itkFRPROptimizer(itkPowellOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetUseUnitLengthGradient: Any = ...
    GetUseUnitLengthGradient: Any = ...
    SetToFletchReeves: Any = ...
    SetToPolakRibiere: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkFRPROptimizer___New_orig__: Any
itkFRPROptimizer_cast: Any

def itkInitializationBiasedParticleSwarmOptimizer_New(): ...

class itkInitializationBiasedParticleSwarmOptimizer(itkParticleSwarmOptimizerBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInertiaCoefficient: Any = ...
    GetInertiaCoefficient: Any = ...
    SetPersonalCoefficient: Any = ...
    GetPersonalCoefficient: Any = ...
    SetGlobalCoefficient: Any = ...
    GetGlobalCoefficient: Any = ...
    SetInitializationCoefficient: Any = ...
    GetInitializationCoefficient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkInitializationBiasedParticleSwarmOptimizer___New_orig__: Any
itkInitializationBiasedParticleSwarmOptimizer_cast: Any

def itkLevenbergMarquardtOptimizer_New(): ...

class itkLevenbergMarquardtOptimizer(itkMultipleValuedNonLinearVnlOptimizer):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOptimizer: Any = ...
    SetNumberOfIterations: Any = ...
    SetValueTolerance: Any = ...
    SetGradientTolerance: Any = ...
    SetEpsilonFunction: Any = ...
    GetValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkLevenbergMarquardtOptimizer___New_orig__: Any
itkLevenbergMarquardtOptimizer_cast: Any

def itkParticleSwarmOptimizer_New(): ...

class itkParticleSwarmOptimizer(itkParticleSwarmOptimizerBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInertiaCoefficient: Any = ...
    GetInertiaCoefficient: Any = ...
    SetPersonalCoefficient: Any = ...
    GetPersonalCoefficient: Any = ...
    SetGlobalCoefficient: Any = ...
    GetGlobalCoefficient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkParticleSwarmOptimizer___New_orig__: Any
itkParticleSwarmOptimizer_cast: Any
