from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkOffset1:
    thisown: Any = ...
    GetOffsetDimension: Any = ...
    __add__: Any = ...
    __sub__: Any = ...
    __iadd__: Any = ...
    __isub__: Any = ...
    GetOffset: Any = ...
    SetOffset: Any = ...
    SetElement: Any = ...
    GetElement: Any = ...
    Fill: Any = ...
    GetBasisOffset: Any = ...
    assign: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    size: Any = ...
    max_size: Any = ...
    empty: Any = ...
    at: Any = ...
    front: Any = ...
    back: Any = ...
    data: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    __len__: Any = ...
    def __eq__(self, other: Any) -> Any: ...

itkOffset1_GetOffsetDimension: Any
itkOffset1_GetBasisOffset: Any
itkOffset1___len__: Any

class itkOffset2:
    thisown: Any = ...
    GetOffsetDimension: Any = ...
    __add__: Any = ...
    __sub__: Any = ...
    __iadd__: Any = ...
    __isub__: Any = ...
    GetOffset: Any = ...
    SetOffset: Any = ...
    SetElement: Any = ...
    GetElement: Any = ...
    Fill: Any = ...
    GetBasisOffset: Any = ...
    assign: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    size: Any = ...
    max_size: Any = ...
    empty: Any = ...
    at: Any = ...
    front: Any = ...
    back: Any = ...
    data: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    __len__: Any = ...
    def __eq__(self, other: Any) -> Any: ...

itkOffset2_GetOffsetDimension: Any
itkOffset2_GetBasisOffset: Any
itkOffset2___len__: Any

class itkOffset3:
    thisown: Any = ...
    GetOffsetDimension: Any = ...
    __add__: Any = ...
    __sub__: Any = ...
    __iadd__: Any = ...
    __isub__: Any = ...
    GetOffset: Any = ...
    SetOffset: Any = ...
    SetElement: Any = ...
    GetElement: Any = ...
    Fill: Any = ...
    GetBasisOffset: Any = ...
    assign: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    size: Any = ...
    max_size: Any = ...
    empty: Any = ...
    at: Any = ...
    front: Any = ...
    back: Any = ...
    data: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    __len__: Any = ...
    def __eq__(self, other: Any) -> Any: ...

itkOffset3_GetOffsetDimension: Any
itkOffset3_GetBasisOffset: Any
itkOffset3___len__: Any

class itkOffset4:
    thisown: Any = ...
    GetOffsetDimension: Any = ...
    __add__: Any = ...
    __sub__: Any = ...
    __iadd__: Any = ...
    __isub__: Any = ...
    GetOffset: Any = ...
    SetOffset: Any = ...
    SetElement: Any = ...
    GetElement: Any = ...
    Fill: Any = ...
    GetBasisOffset: Any = ...
    assign: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    size: Any = ...
    max_size: Any = ...
    empty: Any = ...
    at: Any = ...
    front: Any = ...
    back: Any = ...
    data: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    __len__: Any = ...
    def __eq__(self, other: Any) -> Any: ...

itkOffset4_GetOffsetDimension: Any
itkOffset4_GetBasisOffset: Any
itkOffset4___len__: Any
