import itk.itkDisplacementFieldTransformPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkObjectToObjectMetric22(itk.itkObjectToObjectMetricBasePython.itkObjectToObjectMetricBaseTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetFixedTransform: Any = ...
    GetModifiableFixedTransform: Any = ...
    GetFixedTransform: Any = ...
    SetMovingTransform: Any = ...
    GetModifiableMovingTransform: Any = ...
    GetMovingTransform: Any = ...
    SetTransform: Any = ...
    GetTransform: Any = ...
    GetNumberOfValidPoints: Any = ...
    SetVirtualDomain: Any = ...
    SetVirtualDomainFromImage: Any = ...
    SupportsArbitraryVirtualDomainSamples: Any = ...
    GetVirtualDomainTimeStamp: Any = ...
    GetVirtualSpacing: Any = ...
    GetVirtualOrigin: Any = ...
    GetVirtualDirection: Any = ...
    GetVirtualRegion: Any = ...
    GetModifiableVirtualImage: Any = ...
    GetVirtualImage: Any = ...
    ComputeParameterOffsetFromVirtualIndex: Any = ...
    ComputeParameterOffsetFromVirtualPoint: Any = ...
    IsInsideVirtualDomain: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkObjectToObjectMetric22_cast: Any

class itkObjectToObjectMetric33(itk.itkObjectToObjectMetricBasePython.itkObjectToObjectMetricBaseTemplateD):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetFixedTransform: Any = ...
    GetModifiableFixedTransform: Any = ...
    GetFixedTransform: Any = ...
    SetMovingTransform: Any = ...
    GetModifiableMovingTransform: Any = ...
    GetMovingTransform: Any = ...
    SetTransform: Any = ...
    GetTransform: Any = ...
    GetNumberOfValidPoints: Any = ...
    SetVirtualDomain: Any = ...
    SetVirtualDomainFromImage: Any = ...
    SupportsArbitraryVirtualDomainSamples: Any = ...
    GetVirtualDomainTimeStamp: Any = ...
    GetVirtualSpacing: Any = ...
    GetVirtualOrigin: Any = ...
    GetVirtualDirection: Any = ...
    GetVirtualRegion: Any = ...
    GetModifiableVirtualImage: Any = ...
    GetVirtualImage: Any = ...
    ComputeParameterOffsetFromVirtualIndex: Any = ...
    ComputeParameterOffsetFromVirtualPoint: Any = ...
    IsInsideVirtualDomain: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkObjectToObjectMetric33_cast: Any
