import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkOtsuMultipleThresholdsImageFilterIF2IF2_New(): ...

class itkOtsuMultipleThresholdsImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfHistogramBins: Any = ...
    GetNumberOfHistogramBins: Any = ...
    SetNumberOfThresholds: Any = ...
    GetNumberOfThresholds: Any = ...
    SetLabelOffset: Any = ...
    GetLabelOffset: Any = ...
    SetValleyEmphasis: Any = ...
    GetValleyEmphasis: Any = ...
    ValleyEmphasisOn: Any = ...
    ValleyEmphasisOff: Any = ...
    SetReturnBinMidpoint: Any = ...
    GetReturnBinMidpoint: Any = ...
    ReturnBinMidpointOn: Any = ...
    ReturnBinMidpointOff: Any = ...
    GetThresholds: Any = ...
    OutputComparableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOtsuMultipleThresholdsImageFilterIF2IF2___New_orig__: Any
itkOtsuMultipleThresholdsImageFilterIF2IF2_cast: Any

def itkOtsuMultipleThresholdsImageFilterIF3IF3_New(): ...

class itkOtsuMultipleThresholdsImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfHistogramBins: Any = ...
    GetNumberOfHistogramBins: Any = ...
    SetNumberOfThresholds: Any = ...
    GetNumberOfThresholds: Any = ...
    SetLabelOffset: Any = ...
    GetLabelOffset: Any = ...
    SetValleyEmphasis: Any = ...
    GetValleyEmphasis: Any = ...
    ValleyEmphasisOn: Any = ...
    ValleyEmphasisOff: Any = ...
    SetReturnBinMidpoint: Any = ...
    GetReturnBinMidpoint: Any = ...
    ReturnBinMidpointOn: Any = ...
    ReturnBinMidpointOff: Any = ...
    GetThresholds: Any = ...
    OutputComparableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOtsuMultipleThresholdsImageFilterIF3IF3___New_orig__: Any
itkOtsuMultipleThresholdsImageFilterIF3IF3_cast: Any

def itkOtsuMultipleThresholdsImageFilterISS2ISS2_New(): ...

class itkOtsuMultipleThresholdsImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfHistogramBins: Any = ...
    GetNumberOfHistogramBins: Any = ...
    SetNumberOfThresholds: Any = ...
    GetNumberOfThresholds: Any = ...
    SetLabelOffset: Any = ...
    GetLabelOffset: Any = ...
    SetValleyEmphasis: Any = ...
    GetValleyEmphasis: Any = ...
    ValleyEmphasisOn: Any = ...
    ValleyEmphasisOff: Any = ...
    SetReturnBinMidpoint: Any = ...
    GetReturnBinMidpoint: Any = ...
    ReturnBinMidpointOn: Any = ...
    ReturnBinMidpointOff: Any = ...
    GetThresholds: Any = ...
    OutputComparableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOtsuMultipleThresholdsImageFilterISS2ISS2___New_orig__: Any
itkOtsuMultipleThresholdsImageFilterISS2ISS2_cast: Any

def itkOtsuMultipleThresholdsImageFilterISS3ISS3_New(): ...

class itkOtsuMultipleThresholdsImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfHistogramBins: Any = ...
    GetNumberOfHistogramBins: Any = ...
    SetNumberOfThresholds: Any = ...
    GetNumberOfThresholds: Any = ...
    SetLabelOffset: Any = ...
    GetLabelOffset: Any = ...
    SetValleyEmphasis: Any = ...
    GetValleyEmphasis: Any = ...
    ValleyEmphasisOn: Any = ...
    ValleyEmphasisOff: Any = ...
    SetReturnBinMidpoint: Any = ...
    GetReturnBinMidpoint: Any = ...
    ReturnBinMidpointOn: Any = ...
    ReturnBinMidpointOff: Any = ...
    GetThresholds: Any = ...
    OutputComparableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOtsuMultipleThresholdsImageFilterISS3ISS3___New_orig__: Any
itkOtsuMultipleThresholdsImageFilterISS3ISS3_cast: Any

def itkOtsuMultipleThresholdsImageFilterIUC2IUC2_New(): ...

class itkOtsuMultipleThresholdsImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfHistogramBins: Any = ...
    GetNumberOfHistogramBins: Any = ...
    SetNumberOfThresholds: Any = ...
    GetNumberOfThresholds: Any = ...
    SetLabelOffset: Any = ...
    GetLabelOffset: Any = ...
    SetValleyEmphasis: Any = ...
    GetValleyEmphasis: Any = ...
    ValleyEmphasisOn: Any = ...
    ValleyEmphasisOff: Any = ...
    SetReturnBinMidpoint: Any = ...
    GetReturnBinMidpoint: Any = ...
    ReturnBinMidpointOn: Any = ...
    ReturnBinMidpointOff: Any = ...
    GetThresholds: Any = ...
    OutputComparableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOtsuMultipleThresholdsImageFilterIUC2IUC2___New_orig__: Any
itkOtsuMultipleThresholdsImageFilterIUC2IUC2_cast: Any

def itkOtsuMultipleThresholdsImageFilterIUC3IUC3_New(): ...

class itkOtsuMultipleThresholdsImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfHistogramBins: Any = ...
    GetNumberOfHistogramBins: Any = ...
    SetNumberOfThresholds: Any = ...
    GetNumberOfThresholds: Any = ...
    SetLabelOffset: Any = ...
    GetLabelOffset: Any = ...
    SetValleyEmphasis: Any = ...
    GetValleyEmphasis: Any = ...
    ValleyEmphasisOn: Any = ...
    ValleyEmphasisOff: Any = ...
    SetReturnBinMidpoint: Any = ...
    GetReturnBinMidpoint: Any = ...
    ReturnBinMidpointOn: Any = ...
    ReturnBinMidpointOff: Any = ...
    GetThresholds: Any = ...
    OutputComparableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOtsuMultipleThresholdsImageFilterIUC3IUC3___New_orig__: Any
itkOtsuMultipleThresholdsImageFilterIUC3IUC3_cast: Any

def otsu_multiple_thresholds_image_filter(*args: Any, **kwargs: Any): ...
def otsu_multiple_thresholds_image_filter_init_docstring() -> None: ...
