import itk.itkMeshIOBasePython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkOBJMeshIO_New(): ...

class itkOBJMeshIO(itk.itkMeshIOBasePython.itkMeshIOBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOBJMeshIO___New_orig__: Any
itkOBJMeshIO_cast: Any

def itkOBJMeshIOFactory_New(): ...

class itkOBJMeshIOFactory(itk.ITKCommonBasePython.itkObjectFactoryBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    RegisterOneFactory: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkOBJMeshIOFactory___New_orig__: Any
itkOBJMeshIOFactory_RegisterOneFactory: Any
itkOBJMeshIOFactory_cast: Any
