import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkPointSetToImageFilterPSD2IF2_New(): ...

class itkPointSetToImageFilterPSD2IF2(itk.itkImageSourcePython.itkImageSourceIF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSD2IF2___New_orig__: Any
itkPointSetToImageFilterPSD2IF2_cast: Any

def itkPointSetToImageFilterPSD2ISS2_New(): ...

class itkPointSetToImageFilterPSD2ISS2(itk.itkImageSourcePython.itkImageSourceISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSD2ISS2___New_orig__: Any
itkPointSetToImageFilterPSD2ISS2_cast: Any

def itkPointSetToImageFilterPSD2IUC2_New(): ...

class itkPointSetToImageFilterPSD2IUC2(itk.itkImageSourcePython.itkImageSourceIUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSD2IUC2___New_orig__: Any
itkPointSetToImageFilterPSD2IUC2_cast: Any

def itkPointSetToImageFilterPSD3IF3_New(): ...

class itkPointSetToImageFilterPSD3IF3(itk.itkImageSourcePython.itkImageSourceIF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSD3IF3___New_orig__: Any
itkPointSetToImageFilterPSD3IF3_cast: Any

def itkPointSetToImageFilterPSD3ISS3_New(): ...

class itkPointSetToImageFilterPSD3ISS3(itk.itkImageSourcePython.itkImageSourceISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSD3ISS3___New_orig__: Any
itkPointSetToImageFilterPSD3ISS3_cast: Any

def itkPointSetToImageFilterPSD3IUC3_New(): ...

class itkPointSetToImageFilterPSD3IUC3(itk.itkImageSourcePython.itkImageSourceIUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSD3IUC3___New_orig__: Any
itkPointSetToImageFilterPSD3IUC3_cast: Any

def itkPointSetToImageFilterPSF2IF2_New(): ...

class itkPointSetToImageFilterPSF2IF2(itk.itkImageSourcePython.itkImageSourceIF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSF2IF2___New_orig__: Any
itkPointSetToImageFilterPSF2IF2_cast: Any

def itkPointSetToImageFilterPSF2ISS2_New(): ...

class itkPointSetToImageFilterPSF2ISS2(itk.itkImageSourcePython.itkImageSourceISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSF2ISS2___New_orig__: Any
itkPointSetToImageFilterPSF2ISS2_cast: Any

def itkPointSetToImageFilterPSF2IUC2_New(): ...

class itkPointSetToImageFilterPSF2IUC2(itk.itkImageSourcePython.itkImageSourceIUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSF2IUC2___New_orig__: Any
itkPointSetToImageFilterPSF2IUC2_cast: Any

def itkPointSetToImageFilterPSF3IF3_New(): ...

class itkPointSetToImageFilterPSF3IF3(itk.itkImageSourcePython.itkImageSourceIF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSF3IF3___New_orig__: Any
itkPointSetToImageFilterPSF3IF3_cast: Any

def itkPointSetToImageFilterPSF3ISS3_New(): ...

class itkPointSetToImageFilterPSF3ISS3(itk.itkImageSourcePython.itkImageSourceISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSF3ISS3___New_orig__: Any
itkPointSetToImageFilterPSF3ISS3_cast: Any

def itkPointSetToImageFilterPSF3IUC3_New(): ...

class itkPointSetToImageFilterPSF3IUC3(itk.itkImageSourcePython.itkImageSourceIUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSF3IUC3___New_orig__: Any
itkPointSetToImageFilterPSF3IUC3_cast: Any

def itkPointSetToImageFilterPSSS2IF2_New(): ...

class itkPointSetToImageFilterPSSS2IF2(itk.itkImageSourcePython.itkImageSourceIF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSSS2IF2___New_orig__: Any
itkPointSetToImageFilterPSSS2IF2_cast: Any

def itkPointSetToImageFilterPSSS2ISS2_New(): ...

class itkPointSetToImageFilterPSSS2ISS2(itk.itkImageSourcePython.itkImageSourceISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSSS2ISS2___New_orig__: Any
itkPointSetToImageFilterPSSS2ISS2_cast: Any

def itkPointSetToImageFilterPSSS2IUC2_New(): ...

class itkPointSetToImageFilterPSSS2IUC2(itk.itkImageSourcePython.itkImageSourceIUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSSS2IUC2___New_orig__: Any
itkPointSetToImageFilterPSSS2IUC2_cast: Any

def itkPointSetToImageFilterPSSS3IF3_New(): ...

class itkPointSetToImageFilterPSSS3IF3(itk.itkImageSourcePython.itkImageSourceIF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSSS3IF3___New_orig__: Any
itkPointSetToImageFilterPSSS3IF3_cast: Any

def itkPointSetToImageFilterPSSS3ISS3_New(): ...

class itkPointSetToImageFilterPSSS3ISS3(itk.itkImageSourcePython.itkImageSourceISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSSS3ISS3___New_orig__: Any
itkPointSetToImageFilterPSSS3ISS3_cast: Any

def itkPointSetToImageFilterPSSS3IUC3_New(): ...

class itkPointSetToImageFilterPSSS3IUC3(itk.itkImageSourcePython.itkImageSourceIUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSSS3IUC3___New_orig__: Any
itkPointSetToImageFilterPSSS3IUC3_cast: Any

def itkPointSetToImageFilterPSUC2IF2_New(): ...

class itkPointSetToImageFilterPSUC2IF2(itk.itkImageSourcePython.itkImageSourceIF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSUC2IF2___New_orig__: Any
itkPointSetToImageFilterPSUC2IF2_cast: Any

def itkPointSetToImageFilterPSUC2ISS2_New(): ...

class itkPointSetToImageFilterPSUC2ISS2(itk.itkImageSourcePython.itkImageSourceISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSUC2ISS2___New_orig__: Any
itkPointSetToImageFilterPSUC2ISS2_cast: Any

def itkPointSetToImageFilterPSUC2IUC2_New(): ...

class itkPointSetToImageFilterPSUC2IUC2(itk.itkImageSourcePython.itkImageSourceIUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSUC2IUC2___New_orig__: Any
itkPointSetToImageFilterPSUC2IUC2_cast: Any

def itkPointSetToImageFilterPSUC3IF3_New(): ...

class itkPointSetToImageFilterPSUC3IF3(itk.itkImageSourcePython.itkImageSourceIF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSUC3IF3___New_orig__: Any
itkPointSetToImageFilterPSUC3IF3_cast: Any

def itkPointSetToImageFilterPSUC3ISS3_New(): ...

class itkPointSetToImageFilterPSUC3ISS3(itk.itkImageSourcePython.itkImageSourceISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSUC3ISS3___New_orig__: Any
itkPointSetToImageFilterPSUC3ISS3_cast: Any

def itkPointSetToImageFilterPSUC3IUC3_New(): ...

class itkPointSetToImageFilterPSUC3IUC3(itk.itkImageSourcePython.itkImageSourceIUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetToImageFilterPSUC3IUC3___New_orig__: Any
itkPointSetToImageFilterPSUC3IUC3_cast: Any

def point_set_to_image_filter(*args: Any, **kwargs: Any): ...
def point_set_to_image_filter_init_docstring() -> None: ...
