import numpy as np
from typing import Any, Dict, List, Optional, Tuple

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class NDArrayITKBase(np.ndarray):
    def __new__(cls, input_array: Any, itk_base: Optional[Any] = ...): ...
    itk_base: Any = ...
    def __array_finalize__(self, obj: Any) -> None: ...

def serialize(ndarray_itk_base: NDArrayITKBase) -> Tuple[Dict, List[bytes]]: ...
def deserialize(header: Dict, frames: List[bytes]) -> NDArrayITKBase: ...

class itkPyVectorContainerD:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def array_view_from_vector_container(vector_container: Any): ...
    array_view_from_vector_container: Any = ...
    def array_from_vector_container(vector_container: Any): ...
    array_from_vector_container: Any = ...
    def vector_container_from_array(ndarr: Any): ...
    vector_container_from_array: Any = ...

itkPyVectorContainerD__array_view_from_vector_container: Any
itkPyVectorContainerD__vector_container_from_array: Any

class itkPyVectorContainerF:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def array_view_from_vector_container(vector_container: Any): ...
    array_view_from_vector_container: Any = ...
    def array_from_vector_container(vector_container: Any): ...
    array_from_vector_container: Any = ...
    def vector_container_from_array(ndarr: Any): ...
    vector_container_from_array: Any = ...

itkPyVectorContainerF__array_view_from_vector_container: Any
itkPyVectorContainerF__vector_container_from_array: Any

class itkPyVectorContainerPF2:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def array_view_from_vector_container(vector_container: Any): ...
    array_view_from_vector_container: Any = ...
    def array_from_vector_container(vector_container: Any): ...
    array_from_vector_container: Any = ...
    def vector_container_from_array(ndarr: Any): ...
    vector_container_from_array: Any = ...

itkPyVectorContainerPF2__array_view_from_vector_container: Any
itkPyVectorContainerPF2__vector_container_from_array: Any

class itkPyVectorContainerPF3:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def array_view_from_vector_container(vector_container: Any): ...
    array_view_from_vector_container: Any = ...
    def array_from_vector_container(vector_container: Any): ...
    array_from_vector_container: Any = ...
    def vector_container_from_array(ndarr: Any): ...
    vector_container_from_array: Any = ...

itkPyVectorContainerPF3__array_view_from_vector_container: Any
itkPyVectorContainerPF3__vector_container_from_array: Any

class itkPyVectorContainerSS:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def array_view_from_vector_container(vector_container: Any): ...
    array_view_from_vector_container: Any = ...
    def array_from_vector_container(vector_container: Any): ...
    array_from_vector_container: Any = ...
    def vector_container_from_array(ndarr: Any): ...
    vector_container_from_array: Any = ...

itkPyVectorContainerSS__array_view_from_vector_container: Any
itkPyVectorContainerSS__vector_container_from_array: Any

class itkPyVectorContainerUC:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def array_view_from_vector_container(vector_container: Any): ...
    array_view_from_vector_container: Any = ...
    def array_from_vector_container(vector_container: Any): ...
    array_from_vector_container: Any = ...
    def vector_container_from_array(ndarr: Any): ...
    vector_container_from_array: Any = ...

itkPyVectorContainerUC__array_view_from_vector_container: Any
itkPyVectorContainerUC__vector_container_from_array: Any

class itkPyVectorContainerUI:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def array_view_from_vector_container(vector_container: Any): ...
    array_view_from_vector_container: Any = ...
    def array_from_vector_container(vector_container: Any): ...
    array_from_vector_container: Any = ...
    def vector_container_from_array(ndarr: Any): ...
    vector_container_from_array: Any = ...

itkPyVectorContainerUI__array_view_from_vector_container: Any
itkPyVectorContainerUI__vector_container_from_array: Any
