import itk.itkFiniteDifferenceFunctionPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkPDEDeformableRegistrationFunctionIF2IF2IVF22(itk.itkFiniteDifferenceFunctionPython.itkFiniteDifferenceFunctionIVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetDisplacementField: Any = ...
    GetDisplacementField: Any = ...
    SetEnergy: Any = ...
    GetEnergy: Any = ...
    SetGradientStep: Any = ...
    GetGradientStep: Any = ...
    SetNormalizeGradient: Any = ...
    GetNormalizeGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkPDEDeformableRegistrationFunctionIF2IF2IVF22_cast: Any

class itkPDEDeformableRegistrationFunctionIF2IF2IVF32(itk.itkFiniteDifferenceFunctionPython.itkFiniteDifferenceFunctionIVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetDisplacementField: Any = ...
    GetDisplacementField: Any = ...
    SetEnergy: Any = ...
    GetEnergy: Any = ...
    SetGradientStep: Any = ...
    GetGradientStep: Any = ...
    SetNormalizeGradient: Any = ...
    GetNormalizeGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkPDEDeformableRegistrationFunctionIF2IF2IVF32_cast: Any

class itkPDEDeformableRegistrationFunctionIF2IF2IVF42(itk.itkFiniteDifferenceFunctionPython.itkFiniteDifferenceFunctionIVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetDisplacementField: Any = ...
    GetDisplacementField: Any = ...
    SetEnergy: Any = ...
    GetEnergy: Any = ...
    SetGradientStep: Any = ...
    GetGradientStep: Any = ...
    SetNormalizeGradient: Any = ...
    GetNormalizeGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkPDEDeformableRegistrationFunctionIF2IF2IVF42_cast: Any

class itkPDEDeformableRegistrationFunctionIF3IF3IVF23(itk.itkFiniteDifferenceFunctionPython.itkFiniteDifferenceFunctionIVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetDisplacementField: Any = ...
    GetDisplacementField: Any = ...
    SetEnergy: Any = ...
    GetEnergy: Any = ...
    SetGradientStep: Any = ...
    GetGradientStep: Any = ...
    SetNormalizeGradient: Any = ...
    GetNormalizeGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkPDEDeformableRegistrationFunctionIF3IF3IVF23_cast: Any

class itkPDEDeformableRegistrationFunctionIF3IF3IVF33(itk.itkFiniteDifferenceFunctionPython.itkFiniteDifferenceFunctionIVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetDisplacementField: Any = ...
    GetDisplacementField: Any = ...
    SetEnergy: Any = ...
    GetEnergy: Any = ...
    SetGradientStep: Any = ...
    GetGradientStep: Any = ...
    SetNormalizeGradient: Any = ...
    GetNormalizeGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkPDEDeformableRegistrationFunctionIF3IF3IVF33_cast: Any

class itkPDEDeformableRegistrationFunctionIF3IF3IVF43(itk.itkFiniteDifferenceFunctionPython.itkFiniteDifferenceFunctionIVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetDisplacementField: Any = ...
    GetDisplacementField: Any = ...
    SetEnergy: Any = ...
    GetEnergy: Any = ...
    SetGradientStep: Any = ...
    GetGradientStep: Any = ...
    SetNormalizeGradient: Any = ...
    GetNormalizeGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkPDEDeformableRegistrationFunctionIF3IF3IVF43_cast: Any

class itkPDEDeformableRegistrationFunctionISS2ISS2IVF22(itk.itkFiniteDifferenceFunctionPython.itkFiniteDifferenceFunctionIVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetDisplacementField: Any = ...
    GetDisplacementField: Any = ...
    SetEnergy: Any = ...
    GetEnergy: Any = ...
    SetGradientStep: Any = ...
    GetGradientStep: Any = ...
    SetNormalizeGradient: Any = ...
    GetNormalizeGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkPDEDeformableRegistrationFunctionISS2ISS2IVF22_cast: Any

class itkPDEDeformableRegistrationFunctionISS2ISS2IVF32(itk.itkFiniteDifferenceFunctionPython.itkFiniteDifferenceFunctionIVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetDisplacementField: Any = ...
    GetDisplacementField: Any = ...
    SetEnergy: Any = ...
    GetEnergy: Any = ...
    SetGradientStep: Any = ...
    GetGradientStep: Any = ...
    SetNormalizeGradient: Any = ...
    GetNormalizeGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkPDEDeformableRegistrationFunctionISS2ISS2IVF32_cast: Any

class itkPDEDeformableRegistrationFunctionISS2ISS2IVF42(itk.itkFiniteDifferenceFunctionPython.itkFiniteDifferenceFunctionIVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetDisplacementField: Any = ...
    GetDisplacementField: Any = ...
    SetEnergy: Any = ...
    GetEnergy: Any = ...
    SetGradientStep: Any = ...
    GetGradientStep: Any = ...
    SetNormalizeGradient: Any = ...
    GetNormalizeGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkPDEDeformableRegistrationFunctionISS2ISS2IVF42_cast: Any

class itkPDEDeformableRegistrationFunctionISS3ISS3IVF23(itk.itkFiniteDifferenceFunctionPython.itkFiniteDifferenceFunctionIVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetDisplacementField: Any = ...
    GetDisplacementField: Any = ...
    SetEnergy: Any = ...
    GetEnergy: Any = ...
    SetGradientStep: Any = ...
    GetGradientStep: Any = ...
    SetNormalizeGradient: Any = ...
    GetNormalizeGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkPDEDeformableRegistrationFunctionISS3ISS3IVF23_cast: Any

class itkPDEDeformableRegistrationFunctionISS3ISS3IVF33(itk.itkFiniteDifferenceFunctionPython.itkFiniteDifferenceFunctionIVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetDisplacementField: Any = ...
    GetDisplacementField: Any = ...
    SetEnergy: Any = ...
    GetEnergy: Any = ...
    SetGradientStep: Any = ...
    GetGradientStep: Any = ...
    SetNormalizeGradient: Any = ...
    GetNormalizeGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkPDEDeformableRegistrationFunctionISS3ISS3IVF33_cast: Any

class itkPDEDeformableRegistrationFunctionISS3ISS3IVF43(itk.itkFiniteDifferenceFunctionPython.itkFiniteDifferenceFunctionIVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetDisplacementField: Any = ...
    GetDisplacementField: Any = ...
    SetEnergy: Any = ...
    GetEnergy: Any = ...
    SetGradientStep: Any = ...
    GetGradientStep: Any = ...
    SetNormalizeGradient: Any = ...
    GetNormalizeGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkPDEDeformableRegistrationFunctionISS3ISS3IVF43_cast: Any

class itkPDEDeformableRegistrationFunctionIUC2IUC2IVF22(itk.itkFiniteDifferenceFunctionPython.itkFiniteDifferenceFunctionIVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetDisplacementField: Any = ...
    GetDisplacementField: Any = ...
    SetEnergy: Any = ...
    GetEnergy: Any = ...
    SetGradientStep: Any = ...
    GetGradientStep: Any = ...
    SetNormalizeGradient: Any = ...
    GetNormalizeGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkPDEDeformableRegistrationFunctionIUC2IUC2IVF22_cast: Any

class itkPDEDeformableRegistrationFunctionIUC2IUC2IVF32(itk.itkFiniteDifferenceFunctionPython.itkFiniteDifferenceFunctionIVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetDisplacementField: Any = ...
    GetDisplacementField: Any = ...
    SetEnergy: Any = ...
    GetEnergy: Any = ...
    SetGradientStep: Any = ...
    GetGradientStep: Any = ...
    SetNormalizeGradient: Any = ...
    GetNormalizeGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkPDEDeformableRegistrationFunctionIUC2IUC2IVF32_cast: Any

class itkPDEDeformableRegistrationFunctionIUC2IUC2IVF42(itk.itkFiniteDifferenceFunctionPython.itkFiniteDifferenceFunctionIVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetDisplacementField: Any = ...
    GetDisplacementField: Any = ...
    SetEnergy: Any = ...
    GetEnergy: Any = ...
    SetGradientStep: Any = ...
    GetGradientStep: Any = ...
    SetNormalizeGradient: Any = ...
    GetNormalizeGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkPDEDeformableRegistrationFunctionIUC2IUC2IVF42_cast: Any

class itkPDEDeformableRegistrationFunctionIUC3IUC3IVF23(itk.itkFiniteDifferenceFunctionPython.itkFiniteDifferenceFunctionIVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetDisplacementField: Any = ...
    GetDisplacementField: Any = ...
    SetEnergy: Any = ...
    GetEnergy: Any = ...
    SetGradientStep: Any = ...
    GetGradientStep: Any = ...
    SetNormalizeGradient: Any = ...
    GetNormalizeGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkPDEDeformableRegistrationFunctionIUC3IUC3IVF23_cast: Any

class itkPDEDeformableRegistrationFunctionIUC3IUC3IVF33(itk.itkFiniteDifferenceFunctionPython.itkFiniteDifferenceFunctionIVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetDisplacementField: Any = ...
    GetDisplacementField: Any = ...
    SetEnergy: Any = ...
    GetEnergy: Any = ...
    SetGradientStep: Any = ...
    GetGradientStep: Any = ...
    SetNormalizeGradient: Any = ...
    GetNormalizeGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkPDEDeformableRegistrationFunctionIUC3IUC3IVF33_cast: Any

class itkPDEDeformableRegistrationFunctionIUC3IUC3IVF43(itk.itkFiniteDifferenceFunctionPython.itkFiniteDifferenceFunctionIVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetMovingImage: Any = ...
    GetMovingImage: Any = ...
    SetFixedImage: Any = ...
    GetFixedImage: Any = ...
    SetDisplacementField: Any = ...
    GetDisplacementField: Any = ...
    SetEnergy: Any = ...
    GetEnergy: Any = ...
    SetGradientStep: Any = ...
    GetGradientStep: Any = ...
    SetNormalizeGradient: Any = ...
    GetNormalizeGradient: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkPDEDeformableRegistrationFunctionIUC3IUC3IVF43_cast: Any
