import itk.itkDiffusionTensor3DPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkPCAShapeSignedDistanceFunctionD2ID2_New(): ...

class itkPCAShapeSignedDistanceFunctionD2ID2(itk.itkShapeSignedDistanceFunctionPython.itkShapeSignedDistanceFunctionD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfPrincipalComponents: Any = ...
    GetNumberOfPrincipalComponents: Any = ...
    SetMeanImage: Any = ...
    GetModifiableMeanImage: Any = ...
    GetMeanImage: Any = ...
    SetPrincipalComponentImages: Any = ...
    SetPrincipalComponentStandardDeviations: Any = ...
    GetPrincipalComponentStandardDeviations: Any = ...
    SetTransform: Any = ...
    GetModifiableTransform: Any = ...
    GetTransform: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPCAShapeSignedDistanceFunctionD2ID2___New_orig__: Any
itkPCAShapeSignedDistanceFunctionD2ID2_cast: Any

def itkPCAShapeSignedDistanceFunctionD2IF2_New(): ...

class itkPCAShapeSignedDistanceFunctionD2IF2(itk.itkShapeSignedDistanceFunctionPython.itkShapeSignedDistanceFunctionD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfPrincipalComponents: Any = ...
    GetNumberOfPrincipalComponents: Any = ...
    SetMeanImage: Any = ...
    GetModifiableMeanImage: Any = ...
    GetMeanImage: Any = ...
    SetPrincipalComponentImages: Any = ...
    SetPrincipalComponentStandardDeviations: Any = ...
    GetPrincipalComponentStandardDeviations: Any = ...
    SetTransform: Any = ...
    GetModifiableTransform: Any = ...
    GetTransform: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPCAShapeSignedDistanceFunctionD2IF2___New_orig__: Any
itkPCAShapeSignedDistanceFunctionD2IF2_cast: Any

def itkPCAShapeSignedDistanceFunctionD3ID3_New(): ...

class itkPCAShapeSignedDistanceFunctionD3ID3(itk.itkShapeSignedDistanceFunctionPython.itkShapeSignedDistanceFunctionD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfPrincipalComponents: Any = ...
    GetNumberOfPrincipalComponents: Any = ...
    SetMeanImage: Any = ...
    GetModifiableMeanImage: Any = ...
    GetMeanImage: Any = ...
    SetPrincipalComponentImages: Any = ...
    SetPrincipalComponentStandardDeviations: Any = ...
    GetPrincipalComponentStandardDeviations: Any = ...
    SetTransform: Any = ...
    GetModifiableTransform: Any = ...
    GetTransform: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPCAShapeSignedDistanceFunctionD3ID3___New_orig__: Any
itkPCAShapeSignedDistanceFunctionD3ID3_cast: Any

def itkPCAShapeSignedDistanceFunctionD3IF3_New(): ...

class itkPCAShapeSignedDistanceFunctionD3IF3(itk.itkShapeSignedDistanceFunctionPython.itkShapeSignedDistanceFunctionD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfPrincipalComponents: Any = ...
    GetNumberOfPrincipalComponents: Any = ...
    SetMeanImage: Any = ...
    GetModifiableMeanImage: Any = ...
    GetMeanImage: Any = ...
    SetPrincipalComponentImages: Any = ...
    SetPrincipalComponentStandardDeviations: Any = ...
    GetPrincipalComponentStandardDeviations: Any = ...
    SetTransform: Any = ...
    GetModifiableTransform: Any = ...
    GetTransform: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPCAShapeSignedDistanceFunctionD3IF3___New_orig__: Any
itkPCAShapeSignedDistanceFunctionD3IF3_cast: Any
