import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkPasteImageFilterIF2_New(): ...

class itkPasteImageFilterIF2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDestinationIndex: Any = ...
    GetDestinationIndex: Any = ...
    SetDestinationSkipAxes: Any = ...
    GetDestinationSkipAxes: Any = ...
    SetSourceRegion: Any = ...
    GetSourceRegion: Any = ...
    SetDestinationImage: Any = ...
    GetDestinationImage: Any = ...
    SetSourceImage: Any = ...
    GetSourceImage: Any = ...
    SetConstantInput: Any = ...
    SetConstant: Any = ...
    GetConstantInput: Any = ...
    GetConstant: Any = ...
    GenerateInputRequestedRegion: Any = ...
    VerifyInputInformation: Any = ...
    VerifyPreconditions: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPasteImageFilterIF2___New_orig__: Any
itkPasteImageFilterIF2_cast: Any

def itkPasteImageFilterIF3_New(): ...

class itkPasteImageFilterIF3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDestinationIndex: Any = ...
    GetDestinationIndex: Any = ...
    SetDestinationSkipAxes: Any = ...
    GetDestinationSkipAxes: Any = ...
    SetSourceRegion: Any = ...
    GetSourceRegion: Any = ...
    SetDestinationImage: Any = ...
    GetDestinationImage: Any = ...
    SetSourceImage: Any = ...
    GetSourceImage: Any = ...
    SetConstantInput: Any = ...
    SetConstant: Any = ...
    GetConstantInput: Any = ...
    GetConstant: Any = ...
    GenerateInputRequestedRegion: Any = ...
    VerifyInputInformation: Any = ...
    VerifyPreconditions: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPasteImageFilterIF3___New_orig__: Any
itkPasteImageFilterIF3_cast: Any

def itkPasteImageFilterISS2_New(): ...

class itkPasteImageFilterISS2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDestinationIndex: Any = ...
    GetDestinationIndex: Any = ...
    SetDestinationSkipAxes: Any = ...
    GetDestinationSkipAxes: Any = ...
    SetSourceRegion: Any = ...
    GetSourceRegion: Any = ...
    SetDestinationImage: Any = ...
    GetDestinationImage: Any = ...
    SetSourceImage: Any = ...
    GetSourceImage: Any = ...
    SetConstantInput: Any = ...
    SetConstant: Any = ...
    GetConstantInput: Any = ...
    GetConstant: Any = ...
    GenerateInputRequestedRegion: Any = ...
    VerifyInputInformation: Any = ...
    VerifyPreconditions: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPasteImageFilterISS2___New_orig__: Any
itkPasteImageFilterISS2_cast: Any

def itkPasteImageFilterISS3_New(): ...

class itkPasteImageFilterISS3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDestinationIndex: Any = ...
    GetDestinationIndex: Any = ...
    SetDestinationSkipAxes: Any = ...
    GetDestinationSkipAxes: Any = ...
    SetSourceRegion: Any = ...
    GetSourceRegion: Any = ...
    SetDestinationImage: Any = ...
    GetDestinationImage: Any = ...
    SetSourceImage: Any = ...
    GetSourceImage: Any = ...
    SetConstantInput: Any = ...
    SetConstant: Any = ...
    GetConstantInput: Any = ...
    GetConstant: Any = ...
    GenerateInputRequestedRegion: Any = ...
    VerifyInputInformation: Any = ...
    VerifyPreconditions: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPasteImageFilterISS3___New_orig__: Any
itkPasteImageFilterISS3_cast: Any

def itkPasteImageFilterIUC2_New(): ...

class itkPasteImageFilterIUC2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDestinationIndex: Any = ...
    GetDestinationIndex: Any = ...
    SetDestinationSkipAxes: Any = ...
    GetDestinationSkipAxes: Any = ...
    SetSourceRegion: Any = ...
    GetSourceRegion: Any = ...
    SetDestinationImage: Any = ...
    GetDestinationImage: Any = ...
    SetSourceImage: Any = ...
    GetSourceImage: Any = ...
    SetConstantInput: Any = ...
    SetConstant: Any = ...
    GetConstantInput: Any = ...
    GetConstant: Any = ...
    GenerateInputRequestedRegion: Any = ...
    VerifyInputInformation: Any = ...
    VerifyPreconditions: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPasteImageFilterIUC2___New_orig__: Any
itkPasteImageFilterIUC2_cast: Any

def itkPasteImageFilterIUC3_New(): ...

class itkPasteImageFilterIUC3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDestinationIndex: Any = ...
    GetDestinationIndex: Any = ...
    SetDestinationSkipAxes: Any = ...
    GetDestinationSkipAxes: Any = ...
    SetSourceRegion: Any = ...
    GetSourceRegion: Any = ...
    SetDestinationImage: Any = ...
    GetDestinationImage: Any = ...
    SetSourceImage: Any = ...
    GetSourceImage: Any = ...
    SetConstantInput: Any = ...
    SetConstant: Any = ...
    GetConstantInput: Any = ...
    GetConstant: Any = ...
    GenerateInputRequestedRegion: Any = ...
    VerifyInputInformation: Any = ...
    VerifyPreconditions: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPasteImageFilterIUC3___New_orig__: Any
itkPasteImageFilterIUC3_cast: Any

def paste_image_filter(*args: Any, **kwargs: Any): ...
def paste_image_filter_init_docstring() -> None: ...
