import itk.ITKCommonBasePython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkPathDCID22(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    StartOfInput: Any = ...
    EndOfInput: Any = ...
    Evaluate: Any = ...
    EvaluateToIndex: Any = ...
    IncrementInput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkPathDCID22_cast: Any

class itkPathDCID33(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    StartOfInput: Any = ...
    EndOfInput: Any = ...
    Evaluate: Any = ...
    EvaluateToIndex: Any = ...
    IncrementInput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkPathDCID33_cast: Any
