import itk.stdcomplexPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkPNGImageIO_New(): ...

class itkPNGImageIO(itk.ITKIOImageBaseBasePython.itkImageIOBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetColorPalette: Any = ...
    SetColorPalette: Any = ...
    ReadVolume: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPNGImageIO___New_orig__: Any
itkPNGImageIO_cast: Any

def itkPNGImageIOFactory_New(): ...

class itkPNGImageIOFactory(itk.ITKCommonBasePython.itkObjectFactoryBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    FactoryNew: Any = ...
    RegisterOneFactory: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPNGImageIOFactory___New_orig__: Any
itkPNGImageIOFactory_FactoryNew: Any
itkPNGImageIOFactory_RegisterOneFactory: Any
itkPNGImageIOFactory_cast: Any
