import itk.itkContinuousIndexPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class listitkPolygonSpatialObject2_Pointer:
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

class listitkPolygonSpatialObject3_Pointer:
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

def itkPolygonSpatialObject2_New(): ...

class itkPolygonSpatialObject2(itk.itkPointBasedSpatialObjectPython.itkPointBasedSpatialObject2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOrientationInObjectSpace: Any = ...
    SetThicknessInObjectSpace: Any = ...
    GetThicknessInObjectSpace: Any = ...
    SetIsClosed: Any = ...
    GetIsClosed: Any = ...
    IsClosedOn: Any = ...
    IsClosedOff: Any = ...
    MeasureAreaInObjectSpace: Any = ...
    MeasureVolumeInObjectSpace: Any = ...
    MeasurePerimeterInObjectSpace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPolygonSpatialObject2___New_orig__: Any
itkPolygonSpatialObject2_cast: Any

def itkPolygonSpatialObject3_New(): ...

class itkPolygonSpatialObject3(itk.itkPointBasedSpatialObjectPython.itkPointBasedSpatialObject3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOrientationInObjectSpace: Any = ...
    SetThicknessInObjectSpace: Any = ...
    GetThicknessInObjectSpace: Any = ...
    SetIsClosed: Any = ...
    GetIsClosed: Any = ...
    IsClosedOn: Any = ...
    IsClosedOff: Any = ...
    MeasureAreaInObjectSpace: Any = ...
    MeasureVolumeInObjectSpace: Any = ...
    MeasurePerimeterInObjectSpace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPolygonSpatialObject3___New_orig__: Any
itkPolygonSpatialObject3_cast: Any
