import itk.itkImageSourceCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkPathToImageFilterPLPP2IF2_New(): ...

class itkPathToImageFilterPLPP2IF2(itk.itkImageSourcePython.itkImageSourceIF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetPathValue: Any = ...
    GetPathValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPathToImageFilterPLPP2IF2___New_orig__: Any
itkPathToImageFilterPLPP2IF2_cast: Any

def itkPathToImageFilterPLPP2ISS2_New(): ...

class itkPathToImageFilterPLPP2ISS2(itk.itkImageSourcePython.itkImageSourceISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetPathValue: Any = ...
    GetPathValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPathToImageFilterPLPP2ISS2___New_orig__: Any
itkPathToImageFilterPLPP2ISS2_cast: Any

def itkPathToImageFilterPLPP2IUC2_New(): ...

class itkPathToImageFilterPLPP2IUC2(itk.itkImageSourcePython.itkImageSourceIUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetPathValue: Any = ...
    GetPathValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPathToImageFilterPLPP2IUC2___New_orig__: Any
itkPathToImageFilterPLPP2IUC2_cast: Any

def itkPathToImageFilterPLPP3IF3_New(): ...

class itkPathToImageFilterPLPP3IF3(itk.itkImageSourcePython.itkImageSourceIF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetPathValue: Any = ...
    GetPathValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPathToImageFilterPLPP3IF3___New_orig__: Any
itkPathToImageFilterPLPP3IF3_cast: Any

def itkPathToImageFilterPLPP3ISS3_New(): ...

class itkPathToImageFilterPLPP3ISS3(itk.itkImageSourcePython.itkImageSourceISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetPathValue: Any = ...
    GetPathValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPathToImageFilterPLPP3ISS3___New_orig__: Any
itkPathToImageFilterPLPP3ISS3_cast: Any

def itkPathToImageFilterPLPP3IUC3_New(): ...

class itkPathToImageFilterPLPP3IUC3(itk.itkImageSourcePython.itkImageSourceIUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetPathValue: Any = ...
    GetPathValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPathToImageFilterPLPP3IUC3___New_orig__: Any
itkPathToImageFilterPLPP3IUC3_cast: Any

def path_to_image_filter(*args: Any, **kwargs: Any): ...
def path_to_image_filter_init_docstring() -> None: ...
