import itk.itkImageToImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkPipelineMonitorImageFilterICF2_New(): ...

class itkPipelineMonitorImageFilterICF2(itk.itkImageToImageFilterBPython.itkImageToImageFilterICF2ICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterICF2___New_orig__: Any
itkPipelineMonitorImageFilterICF2_cast: Any

def itkPipelineMonitorImageFilterICF3_New(): ...

class itkPipelineMonitorImageFilterICF3(itk.itkImageToImageFilterBPython.itkImageToImageFilterICF3ICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterICF3___New_orig__: Any
itkPipelineMonitorImageFilterICF3_cast: Any

def itkPipelineMonitorImageFilterICVF22_New(): ...

class itkPipelineMonitorImageFilterICVF22(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF22ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterICVF22___New_orig__: Any
itkPipelineMonitorImageFilterICVF22_cast: Any

def itkPipelineMonitorImageFilterICVF23_New(): ...

class itkPipelineMonitorImageFilterICVF23(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF23ICVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterICVF23___New_orig__: Any
itkPipelineMonitorImageFilterICVF23_cast: Any

def itkPipelineMonitorImageFilterICVF32_New(): ...

class itkPipelineMonitorImageFilterICVF32(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF32ICVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterICVF32___New_orig__: Any
itkPipelineMonitorImageFilterICVF32_cast: Any

def itkPipelineMonitorImageFilterICVF33_New(): ...

class itkPipelineMonitorImageFilterICVF33(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF33ICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterICVF33___New_orig__: Any
itkPipelineMonitorImageFilterICVF33_cast: Any

def itkPipelineMonitorImageFilterICVF42_New(): ...

class itkPipelineMonitorImageFilterICVF42(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF42ICVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterICVF42___New_orig__: Any
itkPipelineMonitorImageFilterICVF42_cast: Any

def itkPipelineMonitorImageFilterICVF43_New(): ...

class itkPipelineMonitorImageFilterICVF43(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF43ICVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterICVF43___New_orig__: Any
itkPipelineMonitorImageFilterICVF43_cast: Any

def itkPipelineMonitorImageFilterIF2_New(): ...

class itkPipelineMonitorImageFilterIF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterIF2___New_orig__: Any
itkPipelineMonitorImageFilterIF2_cast: Any

def itkPipelineMonitorImageFilterIF3_New(): ...

class itkPipelineMonitorImageFilterIF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterIF3___New_orig__: Any
itkPipelineMonitorImageFilterIF3_cast: Any

def itkPipelineMonitorImageFilterIRGBAUC2_New(): ...

class itkPipelineMonitorImageFilterIRGBAUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBAUC2IRGBAUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterIRGBAUC2___New_orig__: Any
itkPipelineMonitorImageFilterIRGBAUC2_cast: Any

def itkPipelineMonitorImageFilterIRGBAUC3_New(): ...

class itkPipelineMonitorImageFilterIRGBAUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBAUC3IRGBAUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterIRGBAUC3___New_orig__: Any
itkPipelineMonitorImageFilterIRGBAUC3_cast: Any

def itkPipelineMonitorImageFilterIRGBUC2_New(): ...

class itkPipelineMonitorImageFilterIRGBUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBUC2IRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterIRGBUC2___New_orig__: Any
itkPipelineMonitorImageFilterIRGBUC2_cast: Any

def itkPipelineMonitorImageFilterIRGBUC3_New(): ...

class itkPipelineMonitorImageFilterIRGBUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBUC3IRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterIRGBUC3___New_orig__: Any
itkPipelineMonitorImageFilterIRGBUC3_cast: Any

def itkPipelineMonitorImageFilterISS2_New(): ...

class itkPipelineMonitorImageFilterISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterISS2___New_orig__: Any
itkPipelineMonitorImageFilterISS2_cast: Any

def itkPipelineMonitorImageFilterISS3_New(): ...

class itkPipelineMonitorImageFilterISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterISS3___New_orig__: Any
itkPipelineMonitorImageFilterISS3_cast: Any

def itkPipelineMonitorImageFilterIUC2_New(): ...

class itkPipelineMonitorImageFilterIUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterIUC2___New_orig__: Any
itkPipelineMonitorImageFilterIUC2_cast: Any

def itkPipelineMonitorImageFilterIUC3_New(): ...

class itkPipelineMonitorImageFilterIUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterIUC3___New_orig__: Any
itkPipelineMonitorImageFilterIUC3_cast: Any

def itkPipelineMonitorImageFilterIVF22_New(): ...

class itkPipelineMonitorImageFilterIVF22(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF22IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterIVF22___New_orig__: Any
itkPipelineMonitorImageFilterIVF22_cast: Any

def itkPipelineMonitorImageFilterIVF23_New(): ...

class itkPipelineMonitorImageFilterIVF23(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF23IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterIVF23___New_orig__: Any
itkPipelineMonitorImageFilterIVF23_cast: Any

def itkPipelineMonitorImageFilterIVF32_New(): ...

class itkPipelineMonitorImageFilterIVF32(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF32IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterIVF32___New_orig__: Any
itkPipelineMonitorImageFilterIVF32_cast: Any

def itkPipelineMonitorImageFilterIVF33_New(): ...

class itkPipelineMonitorImageFilterIVF33(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF33IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterIVF33___New_orig__: Any
itkPipelineMonitorImageFilterIVF33_cast: Any

def itkPipelineMonitorImageFilterIVF42_New(): ...

class itkPipelineMonitorImageFilterIVF42(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF42IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterIVF42___New_orig__: Any
itkPipelineMonitorImageFilterIVF42_cast: Any

def itkPipelineMonitorImageFilterIVF43_New(): ...

class itkPipelineMonitorImageFilterIVF43(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF43IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetClearPipelineOnGenerateOutputInformation: Any = ...
    GetClearPipelineOnGenerateOutputInformation: Any = ...
    ClearPipelineOnGenerateOutputInformationOn: Any = ...
    ClearPipelineOnGenerateOutputInformationOff: Any = ...
    VerifyAllInputCanStream: Any = ...
    VerifyAllInputCanNotStream: Any = ...
    VerifyAllNoUpdate: Any = ...
    VerifyDownStreamFilterExecutedPropagation: Any = ...
    VerifyInputFilterExecutedStreaming: Any = ...
    VerifyInputFilterMatchedUpdateOutputInformation: Any = ...
    VerifyInputFilterBufferedRequestedRegions: Any = ...
    VerifyInputFilterMatchedRequestedRegions: Any = ...
    VerifyInputFilterRequestedLargestRegion: Any = ...
    GetNumberOfUpdates: Any = ...
    GetOutputRequestedRegions: Any = ...
    GetInputRequestedRegions: Any = ...
    GetUpdatedBufferedRegions: Any = ...
    GetUpdatedRequestedRegions: Any = ...
    GetUpdatedOutputOrigin: Any = ...
    GetUpdatedOutputDirection: Any = ...
    GetUpdatedOutputSpacing: Any = ...
    GetUpdatedOutputLargestPossibleRegion: Any = ...
    ClearPipelineSavedInformation: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    GenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPipelineMonitorImageFilterIVF43___New_orig__: Any
itkPipelineMonitorImageFilterIVF43_cast: Any

def pipeline_monitor_image_filter(*args: Any, **kwargs: Any): ...
def pipeline_monitor_image_filter_init_docstring() -> None: ...
