import itk.itkOffsetPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkPointSetD2_New(): ...

class itkPointSetD2(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaximumNumberOfRegions: Any = ...
    PassStructure: Any = ...
    GetNumberOfPoints: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    SetPoint: Any = ...
    GetPoint: Any = ...
    SetPointData: Any = ...
    GetPointData: Any = ...
    SetRequestedRegion: Any = ...
    GetRequestedRegion: Any = ...
    SetBufferedRegion: Any = ...
    GetBufferedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetD2___New_orig__: Any
itkPointSetD2_cast: Any

def itkPointSetD3_New(): ...

class itkPointSetD3(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaximumNumberOfRegions: Any = ...
    PassStructure: Any = ...
    GetNumberOfPoints: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    SetPoint: Any = ...
    GetPoint: Any = ...
    SetPointData: Any = ...
    GetPointData: Any = ...
    SetRequestedRegion: Any = ...
    GetRequestedRegion: Any = ...
    SetBufferedRegion: Any = ...
    GetBufferedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetD3___New_orig__: Any
itkPointSetD3_cast: Any

def itkPointSetF2_New(): ...

class itkPointSetF2(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaximumNumberOfRegions: Any = ...
    PassStructure: Any = ...
    GetNumberOfPoints: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    SetPoint: Any = ...
    GetPoint: Any = ...
    SetPointData: Any = ...
    GetPointData: Any = ...
    SetRequestedRegion: Any = ...
    GetRequestedRegion: Any = ...
    SetBufferedRegion: Any = ...
    GetBufferedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetF2___New_orig__: Any
itkPointSetF2_cast: Any

def itkPointSetF3_New(): ...

class itkPointSetF3(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaximumNumberOfRegions: Any = ...
    PassStructure: Any = ...
    GetNumberOfPoints: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    SetPoint: Any = ...
    GetPoint: Any = ...
    SetPointData: Any = ...
    GetPointData: Any = ...
    SetRequestedRegion: Any = ...
    GetRequestedRegion: Any = ...
    SetBufferedRegion: Any = ...
    GetBufferedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetF3___New_orig__: Any
itkPointSetF3_cast: Any

def itkPointSetMD22_New(): ...

class itkPointSetMD22(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaximumNumberOfRegions: Any = ...
    PassStructure: Any = ...
    GetNumberOfPoints: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    SetPoint: Any = ...
    GetPoint: Any = ...
    SetPointData: Any = ...
    GetPointData: Any = ...
    SetRequestedRegion: Any = ...
    GetRequestedRegion: Any = ...
    SetBufferedRegion: Any = ...
    GetBufferedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetMD22___New_orig__: Any
itkPointSetMD22_cast: Any

def itkPointSetMD33_New(): ...

class itkPointSetMD33(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaximumNumberOfRegions: Any = ...
    PassStructure: Any = ...
    GetNumberOfPoints: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    SetPoint: Any = ...
    GetPoint: Any = ...
    SetPointData: Any = ...
    GetPointData: Any = ...
    SetRequestedRegion: Any = ...
    GetRequestedRegion: Any = ...
    SetBufferedRegion: Any = ...
    GetBufferedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetMD33___New_orig__: Any
itkPointSetMD33_cast: Any

def itkPointSetPD22STD22DD_New(): ...

class itkPointSetPD22STD22DD(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaximumNumberOfRegions: Any = ...
    PassStructure: Any = ...
    GetNumberOfPoints: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    SetPoint: Any = ...
    GetPoint: Any = ...
    SetPointData: Any = ...
    GetPointData: Any = ...
    SetRequestedRegion: Any = ...
    GetRequestedRegion: Any = ...
    SetBufferedRegion: Any = ...
    GetBufferedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetPD22STD22DD___New_orig__: Any
itkPointSetPD22STD22DD_cast: Any

def itkPointSetPD33STD33DD_New(): ...

class itkPointSetPD33STD33DD(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaximumNumberOfRegions: Any = ...
    PassStructure: Any = ...
    GetNumberOfPoints: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    SetPoint: Any = ...
    GetPoint: Any = ...
    SetPointData: Any = ...
    GetPointData: Any = ...
    SetRequestedRegion: Any = ...
    GetRequestedRegion: Any = ...
    SetBufferedRegion: Any = ...
    GetBufferedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetPD33STD33DD___New_orig__: Any
itkPointSetPD33STD33DD_cast: Any

def itkPointSetSS2_New(): ...

class itkPointSetSS2(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaximumNumberOfRegions: Any = ...
    PassStructure: Any = ...
    GetNumberOfPoints: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    SetPoint: Any = ...
    GetPoint: Any = ...
    SetPointData: Any = ...
    GetPointData: Any = ...
    SetRequestedRegion: Any = ...
    GetRequestedRegion: Any = ...
    SetBufferedRegion: Any = ...
    GetBufferedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetSS2___New_orig__: Any
itkPointSetSS2_cast: Any

def itkPointSetSS3_New(): ...

class itkPointSetSS3(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaximumNumberOfRegions: Any = ...
    PassStructure: Any = ...
    GetNumberOfPoints: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    SetPoint: Any = ...
    GetPoint: Any = ...
    SetPointData: Any = ...
    GetPointData: Any = ...
    SetRequestedRegion: Any = ...
    GetRequestedRegion: Any = ...
    SetBufferedRegion: Any = ...
    GetBufferedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetSS3___New_orig__: Any
itkPointSetSS3_cast: Any

def itkPointSetUC2_New(): ...

class itkPointSetUC2(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaximumNumberOfRegions: Any = ...
    PassStructure: Any = ...
    GetNumberOfPoints: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    SetPoint: Any = ...
    GetPoint: Any = ...
    SetPointData: Any = ...
    GetPointData: Any = ...
    SetRequestedRegion: Any = ...
    GetRequestedRegion: Any = ...
    SetBufferedRegion: Any = ...
    GetBufferedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetUC2___New_orig__: Any
itkPointSetUC2_cast: Any

def itkPointSetUC3_New(): ...

class itkPointSetUC3(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaximumNumberOfRegions: Any = ...
    PassStructure: Any = ...
    GetNumberOfPoints: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    SetPoint: Any = ...
    GetPoint: Any = ...
    SetPointData: Any = ...
    GetPointData: Any = ...
    SetRequestedRegion: Any = ...
    GetRequestedRegion: Any = ...
    SetBufferedRegion: Any = ...
    GetBufferedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetUC3___New_orig__: Any
itkPointSetUC3_cast: Any

def itkPointSetUI2DSMUI22FFUI_New(): ...

class itkPointSetUI2DSMUI22FFUI(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaximumNumberOfRegions: Any = ...
    PassStructure: Any = ...
    GetNumberOfPoints: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    SetPoint: Any = ...
    GetPoint: Any = ...
    SetPointData: Any = ...
    GetPointData: Any = ...
    SetRequestedRegion: Any = ...
    GetRequestedRegion: Any = ...
    SetBufferedRegion: Any = ...
    GetBufferedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetUI2DSMUI22FFUI___New_orig__: Any
itkPointSetUI2DSMUI22FFUI_cast: Any

def itkPointSetUI3DSMUI33FFUI_New(): ...

class itkPointSetUI3DSMUI33FFUI(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaximumNumberOfRegions: Any = ...
    PassStructure: Any = ...
    GetNumberOfPoints: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    SetPoint: Any = ...
    GetPoint: Any = ...
    SetPointData: Any = ...
    GetPointData: Any = ...
    SetRequestedRegion: Any = ...
    GetRequestedRegion: Any = ...
    SetBufferedRegion: Any = ...
    GetBufferedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetUI3DSMUI33FFUI___New_orig__: Any
itkPointSetUI3DSMUI33FFUI_cast: Any
