import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkProjectedLandweberDeconvolutionImageFilterIF2IF2_Superclass_New(): ...

class itkProjectedLandweberDeconvolutionImageFilterIF2IF2_Superclass(itk.itkLandweberDeconvolutionImageFilterPython.itkLandweberDeconvolutionImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkProjectedLandweberDeconvolutionImageFilterIF2IF2_Superclass___New_orig__: Any
itkProjectedLandweberDeconvolutionImageFilterIF2IF2_Superclass_cast: Any

def itkProjectedLandweberDeconvolutionImageFilterIF3IF3_Superclass_New(): ...

class itkProjectedLandweberDeconvolutionImageFilterIF3IF3_Superclass(itk.itkLandweberDeconvolutionImageFilterPython.itkLandweberDeconvolutionImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkProjectedLandweberDeconvolutionImageFilterIF3IF3_Superclass___New_orig__: Any
itkProjectedLandweberDeconvolutionImageFilterIF3IF3_Superclass_cast: Any

def itkProjectedLandweberDeconvolutionImageFilterISS2ISS2_Superclass_New(): ...

class itkProjectedLandweberDeconvolutionImageFilterISS2ISS2_Superclass(itk.itkLandweberDeconvolutionImageFilterPython.itkLandweberDeconvolutionImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkProjectedLandweberDeconvolutionImageFilterISS2ISS2_Superclass___New_orig__: Any
itkProjectedLandweberDeconvolutionImageFilterISS2ISS2_Superclass_cast: Any

def itkProjectedLandweberDeconvolutionImageFilterISS3ISS3_Superclass_New(): ...

class itkProjectedLandweberDeconvolutionImageFilterISS3ISS3_Superclass(itk.itkLandweberDeconvolutionImageFilterPython.itkLandweberDeconvolutionImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkProjectedLandweberDeconvolutionImageFilterISS3ISS3_Superclass___New_orig__: Any
itkProjectedLandweberDeconvolutionImageFilterISS3ISS3_Superclass_cast: Any

def itkProjectedLandweberDeconvolutionImageFilterIUC2IUC2_Superclass_New(): ...

class itkProjectedLandweberDeconvolutionImageFilterIUC2IUC2_Superclass(itk.itkLandweberDeconvolutionImageFilterPython.itkLandweberDeconvolutionImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkProjectedLandweberDeconvolutionImageFilterIUC2IUC2_Superclass___New_orig__: Any
itkProjectedLandweberDeconvolutionImageFilterIUC2IUC2_Superclass_cast: Any

def itkProjectedLandweberDeconvolutionImageFilterIUC3IUC3_Superclass_New(): ...

class itkProjectedLandweberDeconvolutionImageFilterIUC3IUC3_Superclass(itk.itkLandweberDeconvolutionImageFilterPython.itkLandweberDeconvolutionImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkProjectedLandweberDeconvolutionImageFilterIUC3IUC3_Superclass___New_orig__: Any
itkProjectedLandweberDeconvolutionImageFilterIUC3IUC3_Superclass_cast: Any

def itkProjectedLandweberDeconvolutionImageFilterIF2IF2_New(): ...

class itkProjectedLandweberDeconvolutionImageFilterIF2IF2(itkProjectedLandweberDeconvolutionImageFilterIF2IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkProjectedLandweberDeconvolutionImageFilterIF2IF2___New_orig__: Any
itkProjectedLandweberDeconvolutionImageFilterIF2IF2_cast: Any

def itkProjectedLandweberDeconvolutionImageFilterIF3IF3_New(): ...

class itkProjectedLandweberDeconvolutionImageFilterIF3IF3(itkProjectedLandweberDeconvolutionImageFilterIF3IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkProjectedLandweberDeconvolutionImageFilterIF3IF3___New_orig__: Any
itkProjectedLandweberDeconvolutionImageFilterIF3IF3_cast: Any

def itkProjectedLandweberDeconvolutionImageFilterISS2ISS2_New(): ...

class itkProjectedLandweberDeconvolutionImageFilterISS2ISS2(itkProjectedLandweberDeconvolutionImageFilterISS2ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkProjectedLandweberDeconvolutionImageFilterISS2ISS2___New_orig__: Any
itkProjectedLandweberDeconvolutionImageFilterISS2ISS2_cast: Any

def itkProjectedLandweberDeconvolutionImageFilterISS3ISS3_New(): ...

class itkProjectedLandweberDeconvolutionImageFilterISS3ISS3(itkProjectedLandweberDeconvolutionImageFilterISS3ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkProjectedLandweberDeconvolutionImageFilterISS3ISS3___New_orig__: Any
itkProjectedLandweberDeconvolutionImageFilterISS3ISS3_cast: Any

def itkProjectedLandweberDeconvolutionImageFilterIUC2IUC2_New(): ...

class itkProjectedLandweberDeconvolutionImageFilterIUC2IUC2(itkProjectedLandweberDeconvolutionImageFilterIUC2IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkProjectedLandweberDeconvolutionImageFilterIUC2IUC2___New_orig__: Any
itkProjectedLandweberDeconvolutionImageFilterIUC2IUC2_cast: Any

def itkProjectedLandweberDeconvolutionImageFilterIUC3IUC3_New(): ...

class itkProjectedLandweberDeconvolutionImageFilterIUC3IUC3(itkProjectedLandweberDeconvolutionImageFilterIUC3IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkProjectedLandweberDeconvolutionImageFilterIUC3IUC3___New_orig__: Any
itkProjectedLandweberDeconvolutionImageFilterIUC3IUC3_cast: Any

def projected_iterative_deconvolution_image_filter(*args: Any, **kwargs: Any): ...
def projected_iterative_deconvolution_image_filter_init_docstring() -> None: ...
def projected_landweber_deconvolution_image_filter(*args: Any, **kwargs: Any): ...
def projected_landweber_deconvolution_image_filter_init_docstring() -> None: ...
