import itk.pyBasePython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkPyCommand_New(): ...

class itkPyCommand(itk.ITKCommonBasePython.itkCommand):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCommandCallable: Any = ...
    GetCommandCallable: Any = ...
    Execute: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPyCommand___New_orig__: Any
itkPyCommand_cast: Any
