import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkPadLabelMapFilterLM2_New(): ...

class itkPadLabelMapFilterLM2(itk.itkChangeRegionLabelMapFilterPython.itkChangeRegionLabelMapFilterLM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetUpperBoundaryPadSize: Any = ...
    GetUpperBoundaryPadSize: Any = ...
    SetLowerBoundaryPadSize: Any = ...
    GetLowerBoundaryPadSize: Any = ...
    SetPadSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPadLabelMapFilterLM2___New_orig__: Any
itkPadLabelMapFilterLM2_cast: Any

def itkPadLabelMapFilterLM3_New(): ...

class itkPadLabelMapFilterLM3(itk.itkChangeRegionLabelMapFilterPython.itkChangeRegionLabelMapFilterLM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetUpperBoundaryPadSize: Any = ...
    GetUpperBoundaryPadSize: Any = ...
    SetLowerBoundaryPadSize: Any = ...
    GetLowerBoundaryPadSize: Any = ...
    SetPadSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPadLabelMapFilterLM3___New_orig__: Any
itkPadLabelMapFilterLM3_cast: Any

def pad_label_map_filter(*args: Any, **kwargs: Any): ...
def pad_label_map_filter_init_docstring() -> None: ...
