import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkPyImageFilterIUC2IUC2_New(): ...

class itkPyImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetPyGenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPyImageFilterIUC2IUC2___New_orig__: Any
itkPyImageFilterIUC2IUC2_cast: Any

def itkPyImageFilterIUC3IUC3_New(): ...

class itkPyImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetPyGenerateData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPyImageFilterIUC3IUC3___New_orig__: Any
itkPyImageFilterIUC3IUC3_cast: Any

def py_image_filter(*args: Any, **kwargs: Any): ...
def py_image_filter_init_docstring() -> None: ...
