import itk.itkVectorPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class vectoritkPointF2(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectoritkPointD2(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectoritkPointF3(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectoritkPointD3(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectoritkPointF4(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectoritkPointD4(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class itkPointD2(itk.itkFixedArrayPython.itkFixedArrayD2):
    thisown: Any = ...
    GetPointDimension: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    __iadd__: Any = ...
    __isub__: Any = ...
    __add__: Any = ...
    __sub__: Any = ...
    GetVectorFromOrigin: Any = ...
    GetVnlVector: Any = ...
    SetToMidPoint: Any = ...
    SetToBarycentricCombination: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    __len__: Any = ...

itkPointD2_GetPointDimension: Any
itkPointD2___len__: Any

class itkPointD3(itk.itkFixedArrayPython.itkFixedArrayD3):
    thisown: Any = ...
    GetPointDimension: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    __iadd__: Any = ...
    __isub__: Any = ...
    __add__: Any = ...
    __sub__: Any = ...
    GetVectorFromOrigin: Any = ...
    GetVnlVector: Any = ...
    SetToMidPoint: Any = ...
    SetToBarycentricCombination: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    __len__: Any = ...

itkPointD3_GetPointDimension: Any
itkPointD3___len__: Any

class itkPointD4(itk.itkFixedArrayPython.itkFixedArrayD4):
    thisown: Any = ...
    GetPointDimension: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    __iadd__: Any = ...
    __isub__: Any = ...
    __add__: Any = ...
    __sub__: Any = ...
    GetVectorFromOrigin: Any = ...
    GetVnlVector: Any = ...
    SetToMidPoint: Any = ...
    SetToBarycentricCombination: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    __len__: Any = ...

itkPointD4_GetPointDimension: Any
itkPointD4___len__: Any

class itkPointF2(itk.itkFixedArrayPython.itkFixedArrayF2):
    thisown: Any = ...
    GetPointDimension: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    __iadd__: Any = ...
    __isub__: Any = ...
    __add__: Any = ...
    __sub__: Any = ...
    GetVectorFromOrigin: Any = ...
    GetVnlVector: Any = ...
    SetToMidPoint: Any = ...
    SetToBarycentricCombination: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    __len__: Any = ...

itkPointF2_GetPointDimension: Any
itkPointF2___len__: Any

class itkPointF3(itk.itkFixedArrayPython.itkFixedArrayF3):
    thisown: Any = ...
    GetPointDimension: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    __iadd__: Any = ...
    __isub__: Any = ...
    __add__: Any = ...
    __sub__: Any = ...
    GetVectorFromOrigin: Any = ...
    GetVnlVector: Any = ...
    SetToMidPoint: Any = ...
    SetToBarycentricCombination: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    __len__: Any = ...

itkPointF3_GetPointDimension: Any
itkPointF3___len__: Any

class itkPointF4(itk.itkFixedArrayPython.itkFixedArrayF4):
    thisown: Any = ...
    GetPointDimension: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    __iadd__: Any = ...
    __isub__: Any = ...
    __add__: Any = ...
    __sub__: Any = ...
    GetVectorFromOrigin: Any = ...
    GetVnlVector: Any = ...
    SetToMidPoint: Any = ...
    SetToBarycentricCombination: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    __len__: Any = ...

itkPointF4_GetPointDimension: Any
itkPointF4___len__: Any
