import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkParallelSparseFieldLevelSetImageFilterIF2IF2_New(): ...

class itkParallelSparseFieldLevelSetImageFilterIF2IF2(itk.itkFiniteDifferenceImageFilterPython.itkFiniteDifferenceImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfLayers: Any = ...
    GetNumberOfLayers: Any = ...
    SetIsoSurfaceValue: Any = ...
    GetIsoSurfaceValue: Any = ...
    GetActiveListForIndex: Any = ...
    OutputEqualityComparableCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkParallelSparseFieldLevelSetImageFilterIF2IF2___New_orig__: Any
itkParallelSparseFieldLevelSetImageFilterIF2IF2_cast: Any

def itkParallelSparseFieldLevelSetImageFilterIF3IF3_New(): ...

class itkParallelSparseFieldLevelSetImageFilterIF3IF3(itk.itkFiniteDifferenceImageFilterPython.itkFiniteDifferenceImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfLayers: Any = ...
    GetNumberOfLayers: Any = ...
    SetIsoSurfaceValue: Any = ...
    GetIsoSurfaceValue: Any = ...
    GetActiveListForIndex: Any = ...
    OutputEqualityComparableCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkParallelSparseFieldLevelSetImageFilterIF3IF3___New_orig__: Any
itkParallelSparseFieldLevelSetImageFilterIF3IF3_cast: Any

class itkParallelSparseFieldLevelSetNodeI2:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...

class itkParallelSparseFieldLevelSetNodeI3:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...

def itkSparseFieldLayerPSFLSNI2_New(): ...

class itkSparseFieldLayerPSFLSNI2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Front: Any = ...
    PopFront: Any = ...
    PushFront: Any = ...
    Unlink: Any = ...
    Empty: Any = ...
    Size: Any = ...
    SplitRegions: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSparseFieldLayerPSFLSNI2___New_orig__: Any
itkSparseFieldLayerPSFLSNI2_cast: Any

def itkSparseFieldLayerPSFLSNI3_New(): ...

class itkSparseFieldLayerPSFLSNI3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Front: Any = ...
    PopFront: Any = ...
    PushFront: Any = ...
    Unlink: Any = ...
    Empty: Any = ...
    Size: Any = ...
    SplitRegions: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSparseFieldLayerPSFLSNI3___New_orig__: Any
itkSparseFieldLayerPSFLSNI3_cast: Any

def parallel_sparse_field_level_set_image_filter(*args: Any, **kwargs: Any): ...
def parallel_sparse_field_level_set_image_filter_init_docstring() -> None: ...
