import numpy as np
from typing import Any, Dict, List, Optional, Tuple

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class NDArrayITKBase(np.ndarray):
    def __new__(cls, input_array: Any, itk_base: Optional[Any] = ...): ...
    itk_base: Any = ...
    def __array_finalize__(self, obj: Any) -> None: ...

def serialize(ndarray_itk_base: NDArrayITKBase) -> Tuple[Dict, List[bytes]]: ...
def deserialize(header: Dict, frames: List[bytes]) -> NDArrayITKBase: ...

class itkPyBufferICVD22:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferICVD22__GetArrayViewFromImage: Any
itkPyBufferICVD22__GetImageViewFromArray: Any

class itkPyBufferICVD23:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferICVD23__GetArrayViewFromImage: Any
itkPyBufferICVD23__GetImageViewFromArray: Any

class itkPyBufferICVD32:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferICVD32__GetArrayViewFromImage: Any
itkPyBufferICVD32__GetImageViewFromArray: Any

class itkPyBufferICVD33:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferICVD33__GetArrayViewFromImage: Any
itkPyBufferICVD33__GetImageViewFromArray: Any

class itkPyBufferICVD42:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferICVD42__GetArrayViewFromImage: Any
itkPyBufferICVD42__GetImageViewFromArray: Any

class itkPyBufferICVD43:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferICVD43__GetArrayViewFromImage: Any
itkPyBufferICVD43__GetImageViewFromArray: Any

class itkPyBufferICVF22:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferICVF22__GetArrayViewFromImage: Any
itkPyBufferICVF22__GetImageViewFromArray: Any

class itkPyBufferICVF23:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferICVF23__GetArrayViewFromImage: Any
itkPyBufferICVF23__GetImageViewFromArray: Any

class itkPyBufferICVF32:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferICVF32__GetArrayViewFromImage: Any
itkPyBufferICVF32__GetImageViewFromArray: Any

class itkPyBufferICVF33:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferICVF33__GetArrayViewFromImage: Any
itkPyBufferICVF33__GetImageViewFromArray: Any

class itkPyBufferICVF42:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferICVF42__GetArrayViewFromImage: Any
itkPyBufferICVF42__GetImageViewFromArray: Any

class itkPyBufferICVF43:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferICVF43__GetArrayViewFromImage: Any
itkPyBufferICVF43__GetImageViewFromArray: Any

class itkPyBufferID2:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferID2__GetArrayViewFromImage: Any
itkPyBufferID2__GetImageViewFromArray: Any

class itkPyBufferID3:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferID3__GetArrayViewFromImage: Any
itkPyBufferID3__GetImageViewFromArray: Any

class itkPyBufferIF2:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIF2__GetArrayViewFromImage: Any
itkPyBufferIF2__GetImageViewFromArray: Any

class itkPyBufferIF3:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIF3__GetArrayViewFromImage: Any
itkPyBufferIF3__GetImageViewFromArray: Any

class itkPyBufferIRGBAUC2:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIRGBAUC2__GetArrayViewFromImage: Any
itkPyBufferIRGBAUC2__GetImageViewFromArray: Any

class itkPyBufferIRGBAUC3:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIRGBAUC3__GetArrayViewFromImage: Any
itkPyBufferIRGBAUC3__GetImageViewFromArray: Any

class itkPyBufferIRGBUC2:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIRGBUC2__GetArrayViewFromImage: Any
itkPyBufferIRGBUC2__GetImageViewFromArray: Any

class itkPyBufferIRGBUC3:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIRGBUC3__GetArrayViewFromImage: Any
itkPyBufferIRGBUC3__GetImageViewFromArray: Any

class itkPyBufferISS2:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferISS2__GetArrayViewFromImage: Any
itkPyBufferISS2__GetImageViewFromArray: Any

class itkPyBufferISS3:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferISS3__GetArrayViewFromImage: Any
itkPyBufferISS3__GetImageViewFromArray: Any

class itkPyBufferISSRTD22:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferISSRTD22__GetArrayViewFromImage: Any
itkPyBufferISSRTD22__GetImageViewFromArray: Any

class itkPyBufferISSRTD33:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferISSRTD33__GetArrayViewFromImage: Any
itkPyBufferISSRTD33__GetImageViewFromArray: Any

class itkPyBufferIUC2:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIUC2__GetArrayViewFromImage: Any
itkPyBufferIUC2__GetImageViewFromArray: Any

class itkPyBufferIUC3:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIUC3__GetArrayViewFromImage: Any
itkPyBufferIUC3__GetImageViewFromArray: Any

class itkPyBufferIUL2:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIUL2__GetArrayViewFromImage: Any
itkPyBufferIUL2__GetImageViewFromArray: Any

class itkPyBufferIUL3:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIUL3__GetArrayViewFromImage: Any
itkPyBufferIUL3__GetImageViewFromArray: Any

class itkPyBufferIVD22:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIVD22__GetArrayViewFromImage: Any
itkPyBufferIVD22__GetImageViewFromArray: Any

class itkPyBufferIVD23:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIVD23__GetArrayViewFromImage: Any
itkPyBufferIVD23__GetImageViewFromArray: Any

class itkPyBufferIVD32:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIVD32__GetArrayViewFromImage: Any
itkPyBufferIVD32__GetImageViewFromArray: Any

class itkPyBufferIVD33:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIVD33__GetArrayViewFromImage: Any
itkPyBufferIVD33__GetImageViewFromArray: Any

class itkPyBufferIVD42:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIVD42__GetArrayViewFromImage: Any
itkPyBufferIVD42__GetImageViewFromArray: Any

class itkPyBufferIVD43:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIVD43__GetArrayViewFromImage: Any
itkPyBufferIVD43__GetImageViewFromArray: Any

class itkPyBufferIVF22:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIVF22__GetArrayViewFromImage: Any
itkPyBufferIVF22__GetImageViewFromArray: Any

class itkPyBufferIVF23:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIVF23__GetArrayViewFromImage: Any
itkPyBufferIVF23__GetImageViewFromArray: Any

class itkPyBufferIVF32:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIVF32__GetArrayViewFromImage: Any
itkPyBufferIVF32__GetImageViewFromArray: Any

class itkPyBufferIVF33:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIVF33__GetArrayViewFromImage: Any
itkPyBufferIVF33__GetImageViewFromArray: Any

class itkPyBufferIVF42:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIVF42__GetArrayViewFromImage: Any
itkPyBufferIVF42__GetImageViewFromArray: Any

class itkPyBufferIVF43:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferIVF43__GetArrayViewFromImage: Any
itkPyBufferIVF43__GetImageViewFromArray: Any

class itkPyBufferVIF2:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferVIF2__GetArrayViewFromImage: Any
itkPyBufferVIF2__GetImageViewFromArray: Any

class itkPyBufferVIF3:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferVIF3__GetArrayViewFromImage: Any
itkPyBufferVIF3__GetImageViewFromArray: Any

class itkPyBufferVISS2:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferVISS2__GetArrayViewFromImage: Any
itkPyBufferVISS2__GetImageViewFromArray: Any

class itkPyBufferVISS3:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferVISS3__GetArrayViewFromImage: Any
itkPyBufferVISS3__GetImageViewFromArray: Any

class itkPyBufferVIUC2:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferVIUC2__GetArrayViewFromImage: Any
itkPyBufferVIUC2__GetImageViewFromArray: Any

class itkPyBufferVIUC3:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayViewFromImage: Any = ...
    def GetArrayFromImage(image: Any, keep_axes: bool = ..., update: bool = ...): ...
    GetArrayFromImage: Any = ...
    def GetImageViewFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageViewFromArray: Any = ...
    def GetImageFromArray(ndarr: Any, is_vector: bool = ...): ...
    GetImageFromArray: Any = ...

itkPyBufferVIUC3__GetArrayViewFromImage: Any
itkPyBufferVIUC3__GetImageViewFromArray: Any

class itkPyVnlD:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromVnlVector(vnl_vector: Any): ...
    GetArrayViewFromVnlVector: Any = ...
    def GetArrayFromVnlVector(vnl_vector: Any): ...
    GetArrayFromVnlVector: Any = ...
    def GetVnlVectorFromArray(ndarr: Any): ...
    GetVnlVectorFromArray: Any = ...
    def GetArrayViewFromVnlMatrix(vnl_matrix: Any): ...
    GetArrayViewFromVnlMatrix: Any = ...
    def GetArrayFromVnlMatrix(vnl_matrix: Any): ...
    GetArrayFromVnlMatrix: Any = ...
    def GetVnlMatrixFromArray(ndarr: Any): ...
    GetVnlMatrixFromArray: Any = ...

itkPyVnlD__GetArrayViewFromVnlVector: Any
itkPyVnlD__GetVnlVectorFromArray: Any
itkPyVnlD__GetArrayViewFromVnlMatrix: Any
itkPyVnlD__GetVnlMatrixFromArray: Any

class itkPyVnlF:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromVnlVector(vnl_vector: Any): ...
    GetArrayViewFromVnlVector: Any = ...
    def GetArrayFromVnlVector(vnl_vector: Any): ...
    GetArrayFromVnlVector: Any = ...
    def GetVnlVectorFromArray(ndarr: Any): ...
    GetVnlVectorFromArray: Any = ...
    def GetArrayViewFromVnlMatrix(vnl_matrix: Any): ...
    GetArrayViewFromVnlMatrix: Any = ...
    def GetArrayFromVnlMatrix(vnl_matrix: Any): ...
    GetArrayFromVnlMatrix: Any = ...
    def GetVnlMatrixFromArray(ndarr: Any): ...
    GetVnlMatrixFromArray: Any = ...

itkPyVnlF__GetArrayViewFromVnlVector: Any
itkPyVnlF__GetVnlVectorFromArray: Any
itkPyVnlF__GetArrayViewFromVnlMatrix: Any
itkPyVnlF__GetVnlMatrixFromArray: Any

class itkPyVnlSC:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromVnlVector(vnl_vector: Any): ...
    GetArrayViewFromVnlVector: Any = ...
    def GetArrayFromVnlVector(vnl_vector: Any): ...
    GetArrayFromVnlVector: Any = ...
    def GetVnlVectorFromArray(ndarr: Any): ...
    GetVnlVectorFromArray: Any = ...
    def GetArrayViewFromVnlMatrix(vnl_matrix: Any): ...
    GetArrayViewFromVnlMatrix: Any = ...
    def GetArrayFromVnlMatrix(vnl_matrix: Any): ...
    GetArrayFromVnlMatrix: Any = ...
    def GetVnlMatrixFromArray(ndarr: Any): ...
    GetVnlMatrixFromArray: Any = ...

itkPyVnlSC__GetArrayViewFromVnlVector: Any
itkPyVnlSC__GetVnlVectorFromArray: Any
itkPyVnlSC__GetArrayViewFromVnlMatrix: Any
itkPyVnlSC__GetVnlMatrixFromArray: Any

class itkPyVnlSI:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromVnlVector(vnl_vector: Any): ...
    GetArrayViewFromVnlVector: Any = ...
    def GetArrayFromVnlVector(vnl_vector: Any): ...
    GetArrayFromVnlVector: Any = ...
    def GetVnlVectorFromArray(ndarr: Any): ...
    GetVnlVectorFromArray: Any = ...
    def GetArrayViewFromVnlMatrix(vnl_matrix: Any): ...
    GetArrayViewFromVnlMatrix: Any = ...
    def GetArrayFromVnlMatrix(vnl_matrix: Any): ...
    GetArrayFromVnlMatrix: Any = ...
    def GetVnlMatrixFromArray(ndarr: Any): ...
    GetVnlMatrixFromArray: Any = ...

itkPyVnlSI__GetArrayViewFromVnlVector: Any
itkPyVnlSI__GetVnlVectorFromArray: Any
itkPyVnlSI__GetArrayViewFromVnlMatrix: Any
itkPyVnlSI__GetVnlMatrixFromArray: Any

class itkPyVnlSL:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromVnlVector(vnl_vector: Any): ...
    GetArrayViewFromVnlVector: Any = ...
    def GetArrayFromVnlVector(vnl_vector: Any): ...
    GetArrayFromVnlVector: Any = ...
    def GetVnlVectorFromArray(ndarr: Any): ...
    GetVnlVectorFromArray: Any = ...
    def GetArrayViewFromVnlMatrix(vnl_matrix: Any): ...
    GetArrayViewFromVnlMatrix: Any = ...
    def GetArrayFromVnlMatrix(vnl_matrix: Any): ...
    GetArrayFromVnlMatrix: Any = ...
    def GetVnlMatrixFromArray(ndarr: Any): ...
    GetVnlMatrixFromArray: Any = ...

itkPyVnlSL__GetArrayViewFromVnlVector: Any
itkPyVnlSL__GetVnlVectorFromArray: Any
itkPyVnlSL__GetArrayViewFromVnlMatrix: Any
itkPyVnlSL__GetVnlMatrixFromArray: Any

class itkPyVnlSS:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromVnlVector(vnl_vector: Any): ...
    GetArrayViewFromVnlVector: Any = ...
    def GetArrayFromVnlVector(vnl_vector: Any): ...
    GetArrayFromVnlVector: Any = ...
    def GetVnlVectorFromArray(ndarr: Any): ...
    GetVnlVectorFromArray: Any = ...
    def GetArrayViewFromVnlMatrix(vnl_matrix: Any): ...
    GetArrayViewFromVnlMatrix: Any = ...
    def GetArrayFromVnlMatrix(vnl_matrix: Any): ...
    GetArrayFromVnlMatrix: Any = ...
    def GetVnlMatrixFromArray(ndarr: Any): ...
    GetVnlMatrixFromArray: Any = ...

itkPyVnlSS__GetArrayViewFromVnlVector: Any
itkPyVnlSS__GetVnlVectorFromArray: Any
itkPyVnlSS__GetArrayViewFromVnlMatrix: Any
itkPyVnlSS__GetVnlMatrixFromArray: Any

class itkPyVnlUC:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromVnlVector(vnl_vector: Any): ...
    GetArrayViewFromVnlVector: Any = ...
    def GetArrayFromVnlVector(vnl_vector: Any): ...
    GetArrayFromVnlVector: Any = ...
    def GetVnlVectorFromArray(ndarr: Any): ...
    GetVnlVectorFromArray: Any = ...
    def GetArrayViewFromVnlMatrix(vnl_matrix: Any): ...
    GetArrayViewFromVnlMatrix: Any = ...
    def GetArrayFromVnlMatrix(vnl_matrix: Any): ...
    GetArrayFromVnlMatrix: Any = ...
    def GetVnlMatrixFromArray(ndarr: Any): ...
    GetVnlMatrixFromArray: Any = ...

itkPyVnlUC__GetArrayViewFromVnlVector: Any
itkPyVnlUC__GetVnlVectorFromArray: Any
itkPyVnlUC__GetArrayViewFromVnlMatrix: Any
itkPyVnlUC__GetVnlMatrixFromArray: Any

class itkPyVnlUI:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromVnlVector(vnl_vector: Any): ...
    GetArrayViewFromVnlVector: Any = ...
    def GetArrayFromVnlVector(vnl_vector: Any): ...
    GetArrayFromVnlVector: Any = ...
    def GetVnlVectorFromArray(ndarr: Any): ...
    GetVnlVectorFromArray: Any = ...
    def GetArrayViewFromVnlMatrix(vnl_matrix: Any): ...
    GetArrayViewFromVnlMatrix: Any = ...
    def GetArrayFromVnlMatrix(vnl_matrix: Any): ...
    GetArrayFromVnlMatrix: Any = ...
    def GetVnlMatrixFromArray(ndarr: Any): ...
    GetVnlMatrixFromArray: Any = ...

itkPyVnlUI__GetArrayViewFromVnlVector: Any
itkPyVnlUI__GetVnlVectorFromArray: Any
itkPyVnlUI__GetArrayViewFromVnlMatrix: Any
itkPyVnlUI__GetVnlMatrixFromArray: Any

class itkPyVnlUL:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromVnlVector(vnl_vector: Any): ...
    GetArrayViewFromVnlVector: Any = ...
    def GetArrayFromVnlVector(vnl_vector: Any): ...
    GetArrayFromVnlVector: Any = ...
    def GetVnlVectorFromArray(ndarr: Any): ...
    GetVnlVectorFromArray: Any = ...
    def GetArrayViewFromVnlMatrix(vnl_matrix: Any): ...
    GetArrayViewFromVnlMatrix: Any = ...
    def GetArrayFromVnlMatrix(vnl_matrix: Any): ...
    GetArrayFromVnlMatrix: Any = ...
    def GetVnlMatrixFromArray(ndarr: Any): ...
    GetVnlMatrixFromArray: Any = ...

itkPyVnlUL__GetArrayViewFromVnlVector: Any
itkPyVnlUL__GetVnlVectorFromArray: Any
itkPyVnlUL__GetArrayViewFromVnlMatrix: Any
itkPyVnlUL__GetVnlMatrixFromArray: Any

class itkPyVnlUS:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    def GetArrayViewFromVnlVector(vnl_vector: Any): ...
    GetArrayViewFromVnlVector: Any = ...
    def GetArrayFromVnlVector(vnl_vector: Any): ...
    GetArrayFromVnlVector: Any = ...
    def GetVnlVectorFromArray(ndarr: Any): ...
    GetVnlVectorFromArray: Any = ...
    def GetArrayViewFromVnlMatrix(vnl_matrix: Any): ...
    GetArrayViewFromVnlMatrix: Any = ...
    def GetArrayFromVnlMatrix(vnl_matrix: Any): ...
    GetArrayFromVnlMatrix: Any = ...
    def GetVnlMatrixFromArray(ndarr: Any): ...
    GetVnlMatrixFromArray: Any = ...

itkPyVnlUS__GetArrayViewFromVnlVector: Any
itkPyVnlUS__GetVnlVectorFromArray: Any
itkPyVnlUS__GetArrayViewFromVnlMatrix: Any
itkPyVnlUS__GetVnlMatrixFromArray: Any
