import itk.itkImageRegionPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkBoundingBoxUL2FMCULQEMPF2_New(): ...

class itkBoundingBoxUL2FMCULQEMPF2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    ComputeCorners: Any = ...
    ComputeBoundingBox: Any = ...
    GetBounds: Any = ...
    GetCenter: Any = ...
    GetMinimum: Any = ...
    SetMinimum: Any = ...
    GetMaximum: Any = ...
    SetMaximum: Any = ...
    ConsiderPoint: Any = ...
    GetDiagonalLength2: Any = ...
    IsInside: Any = ...
    DeepCopy: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBoundingBoxUL2FMCULQEMPF2___New_orig__: Any
itkBoundingBoxUL2FMCULQEMPF2_cast: Any

def itkBoundingBoxUL3FMCULQEMPF3_New(): ...

class itkBoundingBoxUL3FMCULQEMPF3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    ComputeCorners: Any = ...
    ComputeBoundingBox: Any = ...
    GetBounds: Any = ...
    GetCenter: Any = ...
    GetMinimum: Any = ...
    SetMinimum: Any = ...
    GetMaximum: Any = ...
    SetMaximum: Any = ...
    ConsiderPoint: Any = ...
    GetDiagonalLength2: Any = ...
    IsInside: Any = ...
    DeepCopy: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkBoundingBoxUL3FMCULQEMPF3___New_orig__: Any
itkBoundingBoxUL3FMCULQEMPF3_cast: Any

def itkMapContainerULCIDQEMCTI2_New(): ...

class itkMapContainerULCIDQEMCTI2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMapContainerULCIDQEMCTI2___New_orig__: Any
itkMapContainerULCIDQEMCTI2_cast: Any

def itkMapContainerULCIDQEMCTI3_New(): ...

class itkMapContainerULCIDQEMCTI3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMapContainerULCIDQEMCTI3___New_orig__: Any
itkMapContainerULCIDQEMCTI3_cast: Any

def itkMeshSourceMD2QEMTD2BBFF_New(): ...

class itkMeshSourceMD2QEMTD2BBFF(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOutput: Any = ...
    SetOutput: Any = ...
    GraftOutput: Any = ...
    GraftNthOutput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMeshSourceMD2QEMTD2BBFF___New_orig__: Any
itkMeshSourceMD2QEMTD2BBFF_cast: Any

def itkMeshSourceMD3QEMTD3BBFF_New(): ...

class itkMeshSourceMD3QEMTD3BBFF(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOutput: Any = ...
    SetOutput: Any = ...
    GraftOutput: Any = ...
    GraftNthOutput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMeshSourceMD3QEMTD3BBFF___New_orig__: Any
itkMeshSourceMD3QEMTD3BBFF_cast: Any

def itkMeshSourceQEMD2_New(): ...

class itkMeshSourceQEMD2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOutput: Any = ...
    SetOutput: Any = ...
    GraftOutput: Any = ...
    GraftNthOutput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMeshSourceQEMD2___New_orig__: Any
itkMeshSourceQEMD2_cast: Any

def itkMeshSourceQEMD3_New(): ...

class itkMeshSourceQEMD3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOutput: Any = ...
    SetOutput: Any = ...
    GraftOutput: Any = ...
    GraftNthOutput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMeshSourceQEMD3___New_orig__: Any
itkMeshSourceQEMD3_cast: Any

def itkMeshToMeshFilterQEMD2QEMD2_New(): ...

class itkMeshToMeshFilterQEMD2QEMD2(itkMeshSourceQEMD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMeshToMeshFilterQEMD2QEMD2___New_orig__: Any
itkMeshToMeshFilterQEMD2QEMD2_cast: Any

def itkMeshToMeshFilterQEMD3QEMD3_New(): ...

class itkMeshToMeshFilterQEMD3QEMD3(itkMeshSourceQEMD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMeshToMeshFilterQEMD3QEMD3___New_orig__: Any
itkMeshToMeshFilterQEMD3QEMD3_cast: Any

def itkPointSetD2QEMTD2BBFF_New(): ...

class itkPointSetD2QEMTD2BBFF(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaximumNumberOfRegions: Any = ...
    PassStructure: Any = ...
    GetNumberOfPoints: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    SetPoint: Any = ...
    GetPoint: Any = ...
    SetPointData: Any = ...
    GetPointData: Any = ...
    SetRequestedRegion: Any = ...
    GetRequestedRegion: Any = ...
    SetBufferedRegion: Any = ...
    GetBufferedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetD2QEMTD2BBFF___New_orig__: Any
itkPointSetD2QEMTD2BBFF_cast: Any

def itkPointSetD3QEMTD3BBFF_New(): ...

class itkPointSetD3QEMTD3BBFF(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaximumNumberOfRegions: Any = ...
    PassStructure: Any = ...
    GetNumberOfPoints: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    SetPoint: Any = ...
    GetPoint: Any = ...
    SetPointData: Any = ...
    GetPointData: Any = ...
    SetRequestedRegion: Any = ...
    GetRequestedRegion: Any = ...
    SetBufferedRegion: Any = ...
    GetBufferedRegion: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointSetD3QEMTD3BBFF___New_orig__: Any
itkPointSetD3QEMTD3BBFF_cast: Any

class itkImageToMeshFilterISS2MD2QEMTD2BBFF(itkMeshSourceMD2QEMTD2BBFF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterISS2MD2QEMTD2BBFF_cast: Any

class itkImageToMeshFilterISS3MD3QEMTD3BBFF(itkMeshSourceMD3QEMTD3BBFF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterISS3MD3QEMTD3BBFF_cast: Any

class itkImageToMeshFilterIUC2MD2QEMTD2BBFF(itkMeshSourceMD2QEMTD2BBFF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIUC2MD2QEMTD2BBFF_cast: Any

class itkImageToMeshFilterIUC3MD3QEMTD3BBFF(itkMeshSourceMD3QEMTD3BBFF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetOutput: Any = ...
    GenerateOutputInformation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkImageToMeshFilterIUC3MD3QEMTD3BBFF_cast: Any

def itkMeshD2QEMTD2BBFF_New(): ...

class itkMeshD2QEMTD2BBFF(itkPointSetD2QEMTD2BBFF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetNumberOfCells: Any = ...
    PassStructure: Any = ...
    GetBoundingBox: Any = ...
    SetCellLinks: Any = ...
    GetCellLinks: Any = ...
    SetCells: Any = ...
    GetCells: Any = ...
    DeleteUnusedCellData: Any = ...
    SetCell: Any = ...
    GetCell: Any = ...
    SetCellData: Any = ...
    GetCellData: Any = ...
    SetBoundaryAssignment: Any = ...
    GetBoundaryAssignment: Any = ...
    RemoveBoundaryAssignment: Any = ...
    GetNumberOfCellBoundaryFeatures: Any = ...
    GetCellBoundaryFeature: Any = ...
    GetCellBoundaryFeatureNeighbors: Any = ...
    GetCellNeighbors: Any = ...
    GetAssignedCellBoundaryIfOneExists: Any = ...
    BuildCellLinks: Any = ...
    Accept: Any = ...
    SetCellsAllocationMethod: Any = ...
    GetCellsAllocationMethod: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMeshD2QEMTD2BBFF___New_orig__: Any
itkMeshD2QEMTD2BBFF_cast: Any

def itkMeshD3QEMTD3BBFF_New(): ...

class itkMeshD3QEMTD3BBFF(itkPointSetD3QEMTD3BBFF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetNumberOfCells: Any = ...
    PassStructure: Any = ...
    GetBoundingBox: Any = ...
    SetCellLinks: Any = ...
    GetCellLinks: Any = ...
    SetCells: Any = ...
    GetCells: Any = ...
    DeleteUnusedCellData: Any = ...
    SetCell: Any = ...
    GetCell: Any = ...
    SetCellData: Any = ...
    GetCellData: Any = ...
    SetBoundaryAssignment: Any = ...
    GetBoundaryAssignment: Any = ...
    RemoveBoundaryAssignment: Any = ...
    GetNumberOfCellBoundaryFeatures: Any = ...
    GetCellBoundaryFeature: Any = ...
    GetCellBoundaryFeatureNeighbors: Any = ...
    GetCellNeighbors: Any = ...
    GetAssignedCellBoundaryIfOneExists: Any = ...
    BuildCellLinks: Any = ...
    Accept: Any = ...
    SetCellsAllocationMethod: Any = ...
    GetCellsAllocationMethod: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkMeshD3QEMTD3BBFF___New_orig__: Any
itkMeshD3QEMTD3BBFF_cast: Any

def itkQuadEdgeMeshD2_New(): ...

class itkQuadEdgeMeshD2(itkMeshD2QEMTD2BBFF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Clear: Any = ...
    GetEdgeCells: Any = ...
    SetEdgeCells: Any = ...
    SetEdgeCell: Any = ...
    SqueezePointsIds: Any = ...
    BuildCellLinks: Any = ...
    SetBoundaryAssignment: Any = ...
    GetBoundaryAssignment: Any = ...
    RemoveBoundaryAssignment: Any = ...
    GetCellBoundaryFeature: Any = ...
    GetCellBoundaryFeatureNeighbors: Any = ...
    GetCellNeighbors: Any = ...
    GetAssignedCellBoundaryIfOneExists: Any = ...
    SetCell: Any = ...
    FindFirstUnusedPointIndex: Any = ...
    FindFirstUnusedCellIndex: Any = ...
    PushOnContainer: Any = ...
    AddPoint: Any = ...
    AddEdge: Any = ...
    AddEdgeWithSecurePointList: Any = ...
    AddFace: Any = ...
    AddFaceWithSecurePointList: Any = ...
    AddFaceTriangle: Any = ...
    DeletePoint: Any = ...
    DeleteEdge: Any = ...
    LightWeightDeleteEdge: Any = ...
    DeleteFace: Any = ...
    GetPoint: Any = ...
    GetVector: Any = ...
    GetEdge: Any = ...
    FindEdge: Any = ...
    FindEdgeCell: Any = ...
    ComputeEdgeLength: Any = ...
    ComputeNumberOfPoints: Any = ...
    ComputeNumberOfFaces: Any = ...
    ComputeNumberOfEdges: Any = ...
    Splice: Any = ...
    ClearFreePointAndCellIndexesLists: Any = ...
    GetNumberOfFaces: Any = ...
    GetNumberOfEdges: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkQuadEdgeMeshD2___New_orig__: Any
itkQuadEdgeMeshD2_cast: Any

def itkQuadEdgeMeshD3_New(): ...

class itkQuadEdgeMeshD3(itkMeshD3QEMTD3BBFF):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Clear: Any = ...
    GetEdgeCells: Any = ...
    SetEdgeCells: Any = ...
    SetEdgeCell: Any = ...
    SqueezePointsIds: Any = ...
    BuildCellLinks: Any = ...
    SetBoundaryAssignment: Any = ...
    GetBoundaryAssignment: Any = ...
    RemoveBoundaryAssignment: Any = ...
    GetCellBoundaryFeature: Any = ...
    GetCellBoundaryFeatureNeighbors: Any = ...
    GetCellNeighbors: Any = ...
    GetAssignedCellBoundaryIfOneExists: Any = ...
    SetCell: Any = ...
    FindFirstUnusedPointIndex: Any = ...
    FindFirstUnusedCellIndex: Any = ...
    PushOnContainer: Any = ...
    AddPoint: Any = ...
    AddEdge: Any = ...
    AddEdgeWithSecurePointList: Any = ...
    AddFace: Any = ...
    AddFaceWithSecurePointList: Any = ...
    AddFaceTriangle: Any = ...
    DeletePoint: Any = ...
    DeleteEdge: Any = ...
    LightWeightDeleteEdge: Any = ...
    DeleteFace: Any = ...
    GetPoint: Any = ...
    GetVector: Any = ...
    GetEdge: Any = ...
    FindEdge: Any = ...
    FindEdgeCell: Any = ...
    ComputeEdgeLength: Any = ...
    ComputeNumberOfPoints: Any = ...
    ComputeNumberOfFaces: Any = ...
    ComputeNumberOfEdges: Any = ...
    Splice: Any = ...
    ClearFreePointAndCellIndexesLists: Any = ...
    GetNumberOfFaces: Any = ...
    GetNumberOfEdges: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkQuadEdgeMeshD3___New_orig__: Any
itkQuadEdgeMeshD3_cast: Any

def mesh_source(*args: Any, **kwargs: Any): ...
def mesh_source_init_docstring() -> None: ...
def mesh_to_mesh_filter(*args: Any, **kwargs: Any): ...
def mesh_to_mesh_filter_init_docstring() -> None: ...
def image_to_mesh_filter(*args: Any, **kwargs: Any): ...
def image_to_mesh_filter_init_docstring() -> None: ...
