from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkQuadEdgeMeshTraitsD2BBFF:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...

class itkQuadEdgeMeshTraitsD3BBFF:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
