import itk.stdcomplexPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkQuadEdgeMeshPointF2GQEULULBBT(itk.itkPointPython.itkPointF2):
    thisown: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    SetEdge: Any = ...
    SetPoint: Any = ...
    GetEdge: Any = ...
    IsInternal: Any = ...
    GetValence: Any = ...

class itkQuadEdgeMeshPointF3GQEULULBBT(itk.itkPointPython.itkPointF3):
    thisown: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    SetEdge: Any = ...
    SetPoint: Any = ...
    GetEdge: Any = ...
    IsInternal: Any = ...
    GetValence: Any = ...
