import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkRescaleIntensityImageFilterIF2IF2_Superclass_New(): ...

class itkRescaleIntensityImageFilterIF2IF2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIF2IF2_Superclass___New_orig__: Any
itkRescaleIntensityImageFilterIF2IF2_Superclass_cast: Any

def itkRescaleIntensityImageFilterIF2ISS2_Superclass_New(): ...

class itkRescaleIntensityImageFilterIF2ISS2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIF2ISS2_Superclass___New_orig__: Any
itkRescaleIntensityImageFilterIF2ISS2_Superclass_cast: Any

def itkRescaleIntensityImageFilterIF2IUC2_Superclass_New(): ...

class itkRescaleIntensityImageFilterIF2IUC2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIF2IUC2_Superclass___New_orig__: Any
itkRescaleIntensityImageFilterIF2IUC2_Superclass_cast: Any

def itkRescaleIntensityImageFilterIF3IF3_Superclass_New(): ...

class itkRescaleIntensityImageFilterIF3IF3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIF3IF3_Superclass___New_orig__: Any
itkRescaleIntensityImageFilterIF3IF3_Superclass_cast: Any

def itkRescaleIntensityImageFilterIF3ISS3_Superclass_New(): ...

class itkRescaleIntensityImageFilterIF3ISS3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIF3ISS3_Superclass___New_orig__: Any
itkRescaleIntensityImageFilterIF3ISS3_Superclass_cast: Any

def itkRescaleIntensityImageFilterIF3IUC3_Superclass_New(): ...

class itkRescaleIntensityImageFilterIF3IUC3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIF3IUC3_Superclass___New_orig__: Any
itkRescaleIntensityImageFilterIF3IUC3_Superclass_cast: Any

def itkRescaleIntensityImageFilterISS2IF2_Superclass_New(): ...

class itkRescaleIntensityImageFilterISS2IF2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterISS2IF2_Superclass___New_orig__: Any
itkRescaleIntensityImageFilterISS2IF2_Superclass_cast: Any

def itkRescaleIntensityImageFilterISS2ISS2_Superclass_New(): ...

class itkRescaleIntensityImageFilterISS2ISS2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterISS2ISS2_Superclass___New_orig__: Any
itkRescaleIntensityImageFilterISS2ISS2_Superclass_cast: Any

def itkRescaleIntensityImageFilterISS2IUC2_Superclass_New(): ...

class itkRescaleIntensityImageFilterISS2IUC2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterISS2IUC2_Superclass___New_orig__: Any
itkRescaleIntensityImageFilterISS2IUC2_Superclass_cast: Any

def itkRescaleIntensityImageFilterISS3IF3_Superclass_New(): ...

class itkRescaleIntensityImageFilterISS3IF3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterISS3IF3_Superclass___New_orig__: Any
itkRescaleIntensityImageFilterISS3IF3_Superclass_cast: Any

def itkRescaleIntensityImageFilterISS3ISS3_Superclass_New(): ...

class itkRescaleIntensityImageFilterISS3ISS3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterISS3ISS3_Superclass___New_orig__: Any
itkRescaleIntensityImageFilterISS3ISS3_Superclass_cast: Any

def itkRescaleIntensityImageFilterISS3IUC3_Superclass_New(): ...

class itkRescaleIntensityImageFilterISS3IUC3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterISS3IUC3_Superclass___New_orig__: Any
itkRescaleIntensityImageFilterISS3IUC3_Superclass_cast: Any

def itkRescaleIntensityImageFilterIUC2IF2_Superclass_New(): ...

class itkRescaleIntensityImageFilterIUC2IF2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIUC2IF2_Superclass___New_orig__: Any
itkRescaleIntensityImageFilterIUC2IF2_Superclass_cast: Any

def itkRescaleIntensityImageFilterIUC2ISS2_Superclass_New(): ...

class itkRescaleIntensityImageFilterIUC2ISS2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIUC2ISS2_Superclass___New_orig__: Any
itkRescaleIntensityImageFilterIUC2ISS2_Superclass_cast: Any

def itkRescaleIntensityImageFilterIUC2IUC2_Superclass_New(): ...

class itkRescaleIntensityImageFilterIUC2IUC2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIUC2IUC2_Superclass___New_orig__: Any
itkRescaleIntensityImageFilterIUC2IUC2_Superclass_cast: Any

def itkRescaleIntensityImageFilterIUC3IF3_Superclass_New(): ...

class itkRescaleIntensityImageFilterIUC3IF3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIUC3IF3_Superclass___New_orig__: Any
itkRescaleIntensityImageFilterIUC3IF3_Superclass_cast: Any

def itkRescaleIntensityImageFilterIUC3ISS3_Superclass_New(): ...

class itkRescaleIntensityImageFilterIUC3ISS3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIUC3ISS3_Superclass___New_orig__: Any
itkRescaleIntensityImageFilterIUC3ISS3_Superclass_cast: Any

def itkRescaleIntensityImageFilterIUC3IUC3_Superclass_New(): ...

class itkRescaleIntensityImageFilterIUC3IUC3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIUC3IUC3_Superclass___New_orig__: Any
itkRescaleIntensityImageFilterIUC3IUC3_Superclass_cast: Any

def itkRescaleIntensityImageFilterIF2IF2_New(): ...

class itkRescaleIntensityImageFilterIF2IF2(itkRescaleIntensityImageFilterIF2IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMinimum: Any = ...
    GetInputMaximum: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    RealTypeAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIF2IF2___New_orig__: Any
itkRescaleIntensityImageFilterIF2IF2_cast: Any

def itkRescaleIntensityImageFilterIF2ISS2_New(): ...

class itkRescaleIntensityImageFilterIF2ISS2(itkRescaleIntensityImageFilterIF2ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMinimum: Any = ...
    GetInputMaximum: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    RealTypeAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIF2ISS2___New_orig__: Any
itkRescaleIntensityImageFilterIF2ISS2_cast: Any

def itkRescaleIntensityImageFilterIF2IUC2_New(): ...

class itkRescaleIntensityImageFilterIF2IUC2(itkRescaleIntensityImageFilterIF2IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMinimum: Any = ...
    GetInputMaximum: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    RealTypeAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIF2IUC2___New_orig__: Any
itkRescaleIntensityImageFilterIF2IUC2_cast: Any

def itkRescaleIntensityImageFilterIF3IF3_New(): ...

class itkRescaleIntensityImageFilterIF3IF3(itkRescaleIntensityImageFilterIF3IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMinimum: Any = ...
    GetInputMaximum: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    RealTypeAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIF3IF3___New_orig__: Any
itkRescaleIntensityImageFilterIF3IF3_cast: Any

def itkRescaleIntensityImageFilterIF3ISS3_New(): ...

class itkRescaleIntensityImageFilterIF3ISS3(itkRescaleIntensityImageFilterIF3ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMinimum: Any = ...
    GetInputMaximum: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    RealTypeAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIF3ISS3___New_orig__: Any
itkRescaleIntensityImageFilterIF3ISS3_cast: Any

def itkRescaleIntensityImageFilterIF3IUC3_New(): ...

class itkRescaleIntensityImageFilterIF3IUC3(itkRescaleIntensityImageFilterIF3IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMinimum: Any = ...
    GetInputMaximum: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    RealTypeAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIF3IUC3___New_orig__: Any
itkRescaleIntensityImageFilterIF3IUC3_cast: Any

def itkRescaleIntensityImageFilterISS2IF2_New(): ...

class itkRescaleIntensityImageFilterISS2IF2(itkRescaleIntensityImageFilterISS2IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMinimum: Any = ...
    GetInputMaximum: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    RealTypeAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterISS2IF2___New_orig__: Any
itkRescaleIntensityImageFilterISS2IF2_cast: Any

def itkRescaleIntensityImageFilterISS2ISS2_New(): ...

class itkRescaleIntensityImageFilterISS2ISS2(itkRescaleIntensityImageFilterISS2ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMinimum: Any = ...
    GetInputMaximum: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    RealTypeAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterISS2ISS2___New_orig__: Any
itkRescaleIntensityImageFilterISS2ISS2_cast: Any

def itkRescaleIntensityImageFilterISS2IUC2_New(): ...

class itkRescaleIntensityImageFilterISS2IUC2(itkRescaleIntensityImageFilterISS2IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMinimum: Any = ...
    GetInputMaximum: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    RealTypeAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterISS2IUC2___New_orig__: Any
itkRescaleIntensityImageFilterISS2IUC2_cast: Any

def itkRescaleIntensityImageFilterISS3IF3_New(): ...

class itkRescaleIntensityImageFilterISS3IF3(itkRescaleIntensityImageFilterISS3IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMinimum: Any = ...
    GetInputMaximum: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    RealTypeAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterISS3IF3___New_orig__: Any
itkRescaleIntensityImageFilterISS3IF3_cast: Any

def itkRescaleIntensityImageFilterISS3ISS3_New(): ...

class itkRescaleIntensityImageFilterISS3ISS3(itkRescaleIntensityImageFilterISS3ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMinimum: Any = ...
    GetInputMaximum: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    RealTypeAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterISS3ISS3___New_orig__: Any
itkRescaleIntensityImageFilterISS3ISS3_cast: Any

def itkRescaleIntensityImageFilterISS3IUC3_New(): ...

class itkRescaleIntensityImageFilterISS3IUC3(itkRescaleIntensityImageFilterISS3IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMinimum: Any = ...
    GetInputMaximum: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    RealTypeAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterISS3IUC3___New_orig__: Any
itkRescaleIntensityImageFilterISS3IUC3_cast: Any

def itkRescaleIntensityImageFilterIUC2IF2_New(): ...

class itkRescaleIntensityImageFilterIUC2IF2(itkRescaleIntensityImageFilterIUC2IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMinimum: Any = ...
    GetInputMaximum: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    RealTypeAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIUC2IF2___New_orig__: Any
itkRescaleIntensityImageFilterIUC2IF2_cast: Any

def itkRescaleIntensityImageFilterIUC2ISS2_New(): ...

class itkRescaleIntensityImageFilterIUC2ISS2(itkRescaleIntensityImageFilterIUC2ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMinimum: Any = ...
    GetInputMaximum: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    RealTypeAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIUC2ISS2___New_orig__: Any
itkRescaleIntensityImageFilterIUC2ISS2_cast: Any

def itkRescaleIntensityImageFilterIUC2IUC2_New(): ...

class itkRescaleIntensityImageFilterIUC2IUC2(itkRescaleIntensityImageFilterIUC2IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMinimum: Any = ...
    GetInputMaximum: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    RealTypeAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIUC2IUC2___New_orig__: Any
itkRescaleIntensityImageFilterIUC2IUC2_cast: Any

def itkRescaleIntensityImageFilterIUC3IF3_New(): ...

class itkRescaleIntensityImageFilterIUC3IF3(itkRescaleIntensityImageFilterIUC3IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMinimum: Any = ...
    GetInputMaximum: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    RealTypeAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIUC3IF3___New_orig__: Any
itkRescaleIntensityImageFilterIUC3IF3_cast: Any

def itkRescaleIntensityImageFilterIUC3ISS3_New(): ...

class itkRescaleIntensityImageFilterIUC3ISS3(itkRescaleIntensityImageFilterIUC3ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMinimum: Any = ...
    GetInputMaximum: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    RealTypeAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIUC3ISS3___New_orig__: Any
itkRescaleIntensityImageFilterIUC3ISS3_cast: Any

def itkRescaleIntensityImageFilterIUC3IUC3_New(): ...

class itkRescaleIntensityImageFilterIUC3IUC3(itkRescaleIntensityImageFilterIUC3IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMinimum: Any = ...
    SetOutputMaximum: Any = ...
    GetOutputMinimum: Any = ...
    GetOutputMaximum: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMinimum: Any = ...
    GetInputMaximum: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    RealTypeAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRescaleIntensityImageFilterIUC3IUC3___New_orig__: Any
itkRescaleIntensityImageFilterIUC3IUC3_cast: Any

def unary_functor_image_filter(*args: Any, **kwargs: Any): ...
def unary_functor_image_filter_init_docstring() -> None: ...
def rescale_intensity_image_filter(*args: Any, **kwargs: Any): ...
def rescale_intensity_image_filter_init_docstring() -> None: ...
