import itk.itkMatrixOffsetTransformBasePython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkRigid2DTransformD_New(): ...

class itkRigid2DTransformD(itk.itkMatrixOffsetTransformBasePython.itkMatrixOffsetTransformBaseD22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMatrix: Any = ...
    Translate: Any = ...
    BackTransform: Any = ...
    SetAngle: Any = ...
    GetAngle: Any = ...
    SetAngleInDegrees: Any = ...
    SetRotation: Any = ...
    GetRotation: Any = ...
    CloneInverseTo: Any = ...
    GetInverse: Any = ...
    CloneTo: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRigid2DTransformD___New_orig__: Any
itkRigid2DTransformD_cast: Any
