import itk.itkImageSourceCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkRenyiEntropyThresholdImageFilterIF2ISS2_New(): ...

class itkRenyiEntropyThresholdImageFilterIF2ISS2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRenyiEntropyThresholdImageFilterIF2ISS2___New_orig__: Any
itkRenyiEntropyThresholdImageFilterIF2ISS2_cast: Any

def itkRenyiEntropyThresholdImageFilterIF2IUC2_New(): ...

class itkRenyiEntropyThresholdImageFilterIF2IUC2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRenyiEntropyThresholdImageFilterIF2IUC2___New_orig__: Any
itkRenyiEntropyThresholdImageFilterIF2IUC2_cast: Any

def itkRenyiEntropyThresholdImageFilterIF3ISS3_New(): ...

class itkRenyiEntropyThresholdImageFilterIF3ISS3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRenyiEntropyThresholdImageFilterIF3ISS3___New_orig__: Any
itkRenyiEntropyThresholdImageFilterIF3ISS3_cast: Any

def itkRenyiEntropyThresholdImageFilterIF3IUC3_New(): ...

class itkRenyiEntropyThresholdImageFilterIF3IUC3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRenyiEntropyThresholdImageFilterIF3IUC3___New_orig__: Any
itkRenyiEntropyThresholdImageFilterIF3IUC3_cast: Any

def itkRenyiEntropyThresholdImageFilterISS2ISS2_New(): ...

class itkRenyiEntropyThresholdImageFilterISS2ISS2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRenyiEntropyThresholdImageFilterISS2ISS2___New_orig__: Any
itkRenyiEntropyThresholdImageFilterISS2ISS2_cast: Any

def itkRenyiEntropyThresholdImageFilterISS2IUC2_New(): ...

class itkRenyiEntropyThresholdImageFilterISS2IUC2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRenyiEntropyThresholdImageFilterISS2IUC2___New_orig__: Any
itkRenyiEntropyThresholdImageFilterISS2IUC2_cast: Any

def itkRenyiEntropyThresholdImageFilterISS3ISS3_New(): ...

class itkRenyiEntropyThresholdImageFilterISS3ISS3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRenyiEntropyThresholdImageFilterISS3ISS3___New_orig__: Any
itkRenyiEntropyThresholdImageFilterISS3ISS3_cast: Any

def itkRenyiEntropyThresholdImageFilterISS3IUC3_New(): ...

class itkRenyiEntropyThresholdImageFilterISS3IUC3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRenyiEntropyThresholdImageFilterISS3IUC3___New_orig__: Any
itkRenyiEntropyThresholdImageFilterISS3IUC3_cast: Any

def itkRenyiEntropyThresholdImageFilterIUC2ISS2_New(): ...

class itkRenyiEntropyThresholdImageFilterIUC2ISS2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRenyiEntropyThresholdImageFilterIUC2ISS2___New_orig__: Any
itkRenyiEntropyThresholdImageFilterIUC2ISS2_cast: Any

def itkRenyiEntropyThresholdImageFilterIUC2IUC2_New(): ...

class itkRenyiEntropyThresholdImageFilterIUC2IUC2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRenyiEntropyThresholdImageFilterIUC2IUC2___New_orig__: Any
itkRenyiEntropyThresholdImageFilterIUC2IUC2_cast: Any

def itkRenyiEntropyThresholdImageFilterIUC3ISS3_New(): ...

class itkRenyiEntropyThresholdImageFilterIUC3ISS3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRenyiEntropyThresholdImageFilterIUC3ISS3___New_orig__: Any
itkRenyiEntropyThresholdImageFilterIUC3ISS3_cast: Any

def itkRenyiEntropyThresholdImageFilterIUC3IUC3_New(): ...

class itkRenyiEntropyThresholdImageFilterIUC3IUC3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRenyiEntropyThresholdImageFilterIUC3IUC3___New_orig__: Any
itkRenyiEntropyThresholdImageFilterIUC3IUC3_cast: Any

def renyi_entropy_threshold_image_filter(*args: Any, **kwargs: Any): ...
def renyi_entropy_threshold_image_filter_init_docstring() -> None: ...
