import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkRelabelLabelMapFilterLM2_Superclass_New(): ...

class itkRelabelLabelMapFilterLM2_Superclass(itk.itkInPlaceLabelMapFilterPython.itkInPlaceLabelMapFilterLM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReverseOrdering: Any = ...
    GetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRelabelLabelMapFilterLM2_Superclass___New_orig__: Any
itkRelabelLabelMapFilterLM2_Superclass_cast: Any

def itkRelabelLabelMapFilterLM3_Superclass_New(): ...

class itkRelabelLabelMapFilterLM3_Superclass(itk.itkInPlaceLabelMapFilterPython.itkInPlaceLabelMapFilterLM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReverseOrdering: Any = ...
    GetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRelabelLabelMapFilterLM3_Superclass___New_orig__: Any
itkRelabelLabelMapFilterLM3_Superclass_cast: Any

def itkRelabelLabelMapFilterLM2_New(): ...

class itkRelabelLabelMapFilterLM2(itkRelabelLabelMapFilterLM2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRelabelLabelMapFilterLM2___New_orig__: Any
itkRelabelLabelMapFilterLM2_cast: Any

def itkRelabelLabelMapFilterLM3_New(): ...

class itkRelabelLabelMapFilterLM3(itkRelabelLabelMapFilterLM3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRelabelLabelMapFilterLM3___New_orig__: Any
itkRelabelLabelMapFilterLM3_cast: Any

def attribute_relabel_label_map_filter(*args: Any, **kwargs: Any): ...
def attribute_relabel_label_map_filter_init_docstring() -> None: ...
def relabel_label_map_filter(*args: Any, **kwargs: Any): ...
def relabel_label_map_filter_init_docstring() -> None: ...
