import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkRecursiveMultiResolutionPyramidImageFilterIF2IF2_New(): ...

class itkRecursiveMultiResolutionPyramidImageFilterIF2IF2(itk.itkMultiResolutionPyramidImageFilterPython.itkMultiResolutionPyramidImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRecursiveMultiResolutionPyramidImageFilterIF2IF2___New_orig__: Any
itkRecursiveMultiResolutionPyramidImageFilterIF2IF2_cast: Any

def itkRecursiveMultiResolutionPyramidImageFilterIF3IF3_New(): ...

class itkRecursiveMultiResolutionPyramidImageFilterIF3IF3(itk.itkMultiResolutionPyramidImageFilterPython.itkMultiResolutionPyramidImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRecursiveMultiResolutionPyramidImageFilterIF3IF3___New_orig__: Any
itkRecursiveMultiResolutionPyramidImageFilterIF3IF3_cast: Any

def itkRecursiveMultiResolutionPyramidImageFilterISS2ISS2_New(): ...

class itkRecursiveMultiResolutionPyramidImageFilterISS2ISS2(itk.itkMultiResolutionPyramidImageFilterPython.itkMultiResolutionPyramidImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRecursiveMultiResolutionPyramidImageFilterISS2ISS2___New_orig__: Any
itkRecursiveMultiResolutionPyramidImageFilterISS2ISS2_cast: Any

def itkRecursiveMultiResolutionPyramidImageFilterISS3ISS3_New(): ...

class itkRecursiveMultiResolutionPyramidImageFilterISS3ISS3(itk.itkMultiResolutionPyramidImageFilterPython.itkMultiResolutionPyramidImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRecursiveMultiResolutionPyramidImageFilterISS3ISS3___New_orig__: Any
itkRecursiveMultiResolutionPyramidImageFilterISS3ISS3_cast: Any

def itkRecursiveMultiResolutionPyramidImageFilterIUC2IUC2_New(): ...

class itkRecursiveMultiResolutionPyramidImageFilterIUC2IUC2(itk.itkMultiResolutionPyramidImageFilterPython.itkMultiResolutionPyramidImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRecursiveMultiResolutionPyramidImageFilterIUC2IUC2___New_orig__: Any
itkRecursiveMultiResolutionPyramidImageFilterIUC2IUC2_cast: Any

def itkRecursiveMultiResolutionPyramidImageFilterIUC3IUC3_New(): ...

class itkRecursiveMultiResolutionPyramidImageFilterIUC3IUC3(itk.itkMultiResolutionPyramidImageFilterPython.itkMultiResolutionPyramidImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRecursiveMultiResolutionPyramidImageFilterIUC3IUC3___New_orig__: Any
itkRecursiveMultiResolutionPyramidImageFilterIUC3IUC3_cast: Any

def recursive_multi_resolution_pyramid_image_filter(*args: Any, **kwargs: Any): ...
def recursive_multi_resolution_pyramid_image_filter_init_docstring() -> None: ...
