import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkReconstructionByDilationImageFilterIF2IF2_Superclass_New(): ...

class itkReconstructionByDilationImageFilterIF2IF2_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMarkerImage: Any = ...
    GetMarkerImage: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    SetUseInternalCopy: Any = ...
    GetUseInternalCopy: Any = ...
    UseInternalCopyOn: Any = ...
    UseInternalCopyOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkReconstructionByDilationImageFilterIF2IF2_Superclass___New_orig__: Any
itkReconstructionByDilationImageFilterIF2IF2_Superclass_cast: Any

def itkReconstructionByDilationImageFilterIF3IF3_Superclass_New(): ...

class itkReconstructionByDilationImageFilterIF3IF3_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMarkerImage: Any = ...
    GetMarkerImage: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    SetUseInternalCopy: Any = ...
    GetUseInternalCopy: Any = ...
    UseInternalCopyOn: Any = ...
    UseInternalCopyOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkReconstructionByDilationImageFilterIF3IF3_Superclass___New_orig__: Any
itkReconstructionByDilationImageFilterIF3IF3_Superclass_cast: Any

def itkReconstructionByDilationImageFilterISS2ISS2_Superclass_New(): ...

class itkReconstructionByDilationImageFilterISS2ISS2_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMarkerImage: Any = ...
    GetMarkerImage: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    SetUseInternalCopy: Any = ...
    GetUseInternalCopy: Any = ...
    UseInternalCopyOn: Any = ...
    UseInternalCopyOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkReconstructionByDilationImageFilterISS2ISS2_Superclass___New_orig__: Any
itkReconstructionByDilationImageFilterISS2ISS2_Superclass_cast: Any

def itkReconstructionByDilationImageFilterISS3ISS3_Superclass_New(): ...

class itkReconstructionByDilationImageFilterISS3ISS3_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMarkerImage: Any = ...
    GetMarkerImage: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    SetUseInternalCopy: Any = ...
    GetUseInternalCopy: Any = ...
    UseInternalCopyOn: Any = ...
    UseInternalCopyOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkReconstructionByDilationImageFilterISS3ISS3_Superclass___New_orig__: Any
itkReconstructionByDilationImageFilterISS3ISS3_Superclass_cast: Any

def itkReconstructionByDilationImageFilterIUC2IUC2_Superclass_New(): ...

class itkReconstructionByDilationImageFilterIUC2IUC2_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMarkerImage: Any = ...
    GetMarkerImage: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    SetUseInternalCopy: Any = ...
    GetUseInternalCopy: Any = ...
    UseInternalCopyOn: Any = ...
    UseInternalCopyOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkReconstructionByDilationImageFilterIUC2IUC2_Superclass___New_orig__: Any
itkReconstructionByDilationImageFilterIUC2IUC2_Superclass_cast: Any

def itkReconstructionByDilationImageFilterIUC3IUC3_Superclass_New(): ...

class itkReconstructionByDilationImageFilterIUC3IUC3_Superclass(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMarkerImage: Any = ...
    GetMarkerImage: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetFullyConnected: Any = ...
    GetFullyConnected: Any = ...
    FullyConnectedOn: Any = ...
    FullyConnectedOff: Any = ...
    SetUseInternalCopy: Any = ...
    GetUseInternalCopy: Any = ...
    UseInternalCopyOn: Any = ...
    UseInternalCopyOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkReconstructionByDilationImageFilterIUC3IUC3_Superclass___New_orig__: Any
itkReconstructionByDilationImageFilterIUC3IUC3_Superclass_cast: Any

def itkReconstructionByDilationImageFilterIF2IF2_New(): ...

class itkReconstructionByDilationImageFilterIF2IF2(itkReconstructionByDilationImageFilterIF2IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkReconstructionByDilationImageFilterIF2IF2___New_orig__: Any
itkReconstructionByDilationImageFilterIF2IF2_cast: Any

def itkReconstructionByDilationImageFilterIF3IF3_New(): ...

class itkReconstructionByDilationImageFilterIF3IF3(itkReconstructionByDilationImageFilterIF3IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkReconstructionByDilationImageFilterIF3IF3___New_orig__: Any
itkReconstructionByDilationImageFilterIF3IF3_cast: Any

def itkReconstructionByDilationImageFilterISS2ISS2_New(): ...

class itkReconstructionByDilationImageFilterISS2ISS2(itkReconstructionByDilationImageFilterISS2ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkReconstructionByDilationImageFilterISS2ISS2___New_orig__: Any
itkReconstructionByDilationImageFilterISS2ISS2_cast: Any

def itkReconstructionByDilationImageFilterISS3ISS3_New(): ...

class itkReconstructionByDilationImageFilterISS3ISS3(itkReconstructionByDilationImageFilterISS3ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkReconstructionByDilationImageFilterISS3ISS3___New_orig__: Any
itkReconstructionByDilationImageFilterISS3ISS3_cast: Any

def itkReconstructionByDilationImageFilterIUC2IUC2_New(): ...

class itkReconstructionByDilationImageFilterIUC2IUC2(itkReconstructionByDilationImageFilterIUC2IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkReconstructionByDilationImageFilterIUC2IUC2___New_orig__: Any
itkReconstructionByDilationImageFilterIUC2IUC2_cast: Any

def itkReconstructionByDilationImageFilterIUC3IUC3_New(): ...

class itkReconstructionByDilationImageFilterIUC3IUC3(itkReconstructionByDilationImageFilterIUC3IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkReconstructionByDilationImageFilterIUC3IUC3___New_orig__: Any
itkReconstructionByDilationImageFilterIUC3IUC3_cast: Any

def reconstruction_image_filter(*args: Any, **kwargs: Any): ...
def reconstruction_image_filter_init_docstring() -> None: ...
def reconstruction_by_dilation_image_filter(*args: Any, **kwargs: Any): ...
def reconstruction_by_dilation_image_filter_init_docstring() -> None: ...
