import itk.itkSymmetricSecondRankTensorPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkRigid3DTransformD_New(): ...

class itkRigid3DTransformD(itk.itkMatrixOffsetTransformBasePython.itkMatrixOffsetTransformBaseD33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetMatrix: Any = ...
    Translate: Any = ...
    MatrixIsOrthogonal: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRigid3DTransformD___New_orig__: Any
itkRigid3DTransformD_cast: Any
