import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkRecursiveSeparableImageFilterIF2IF2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetDirection: Any = ...
    SetDirection: Any = ...
    SetInputImage: Any = ...
    GetInputImage: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRecursiveSeparableImageFilterIF2IF2_cast: Any

class itkRecursiveSeparableImageFilterIF3IF3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetDirection: Any = ...
    SetDirection: Any = ...
    SetInputImage: Any = ...
    GetInputImage: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRecursiveSeparableImageFilterIF3IF3_cast: Any

class itkRecursiveSeparableImageFilterISS2ISS2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetDirection: Any = ...
    SetDirection: Any = ...
    SetInputImage: Any = ...
    GetInputImage: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRecursiveSeparableImageFilterISS2ISS2_cast: Any

class itkRecursiveSeparableImageFilterISS3ISS3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetDirection: Any = ...
    SetDirection: Any = ...
    SetInputImage: Any = ...
    GetInputImage: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRecursiveSeparableImageFilterISS3ISS3_cast: Any

class itkRecursiveSeparableImageFilterIUC2IUC2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetDirection: Any = ...
    SetDirection: Any = ...
    SetInputImage: Any = ...
    GetInputImage: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRecursiveSeparableImageFilterIUC2IUC2_cast: Any

class itkRecursiveSeparableImageFilterIUC3IUC3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetDirection: Any = ...
    SetDirection: Any = ...
    SetInputImage: Any = ...
    GetInputImage: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkRecursiveSeparableImageFilterIUC3IUC3_cast: Any

def recursive_separable_image_filter(*args: Any, **kwargs: Any): ...
def recursive_separable_image_filter_init_docstring() -> None: ...
