import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkRecursiveGaussianImageFilterEnums:
    thisown: Any = ...
    GaussianOrder_ZeroOrder: Any = ...
    GaussianOrder_FirstOrder: Any = ...
    GaussianOrder_SecondOrder: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...

def itkRecursiveGaussianImageFilterIF2IF2_New(): ...

class itkRecursiveGaussianImageFilterIF2IF2(itk.itkRecursiveSeparableImageFilterPython.itkRecursiveSeparableImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetSigma: Any = ...
    SetSigma: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    SetOrder: Any = ...
    GetOrder: Any = ...
    SetZeroOrder: Any = ...
    SetFirstOrder: Any = ...
    SetSecondOrder: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRecursiveGaussianImageFilterIF2IF2___New_orig__: Any
itkRecursiveGaussianImageFilterIF2IF2_cast: Any

def itkRecursiveGaussianImageFilterIF3IF3_New(): ...

class itkRecursiveGaussianImageFilterIF3IF3(itk.itkRecursiveSeparableImageFilterPython.itkRecursiveSeparableImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetSigma: Any = ...
    SetSigma: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    SetOrder: Any = ...
    GetOrder: Any = ...
    SetZeroOrder: Any = ...
    SetFirstOrder: Any = ...
    SetSecondOrder: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRecursiveGaussianImageFilterIF3IF3___New_orig__: Any
itkRecursiveGaussianImageFilterIF3IF3_cast: Any

def itkRecursiveGaussianImageFilterISS2ISS2_New(): ...

class itkRecursiveGaussianImageFilterISS2ISS2(itk.itkRecursiveSeparableImageFilterPython.itkRecursiveSeparableImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetSigma: Any = ...
    SetSigma: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    SetOrder: Any = ...
    GetOrder: Any = ...
    SetZeroOrder: Any = ...
    SetFirstOrder: Any = ...
    SetSecondOrder: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRecursiveGaussianImageFilterISS2ISS2___New_orig__: Any
itkRecursiveGaussianImageFilterISS2ISS2_cast: Any

def itkRecursiveGaussianImageFilterISS3ISS3_New(): ...

class itkRecursiveGaussianImageFilterISS3ISS3(itk.itkRecursiveSeparableImageFilterPython.itkRecursiveSeparableImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetSigma: Any = ...
    SetSigma: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    SetOrder: Any = ...
    GetOrder: Any = ...
    SetZeroOrder: Any = ...
    SetFirstOrder: Any = ...
    SetSecondOrder: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRecursiveGaussianImageFilterISS3ISS3___New_orig__: Any
itkRecursiveGaussianImageFilterISS3ISS3_cast: Any

def itkRecursiveGaussianImageFilterIUC2IUC2_New(): ...

class itkRecursiveGaussianImageFilterIUC2IUC2(itk.itkRecursiveSeparableImageFilterPython.itkRecursiveSeparableImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetSigma: Any = ...
    SetSigma: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    SetOrder: Any = ...
    GetOrder: Any = ...
    SetZeroOrder: Any = ...
    SetFirstOrder: Any = ...
    SetSecondOrder: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRecursiveGaussianImageFilterIUC2IUC2___New_orig__: Any
itkRecursiveGaussianImageFilterIUC2IUC2_cast: Any

def itkRecursiveGaussianImageFilterIUC3IUC3_New(): ...

class itkRecursiveGaussianImageFilterIUC3IUC3(itk.itkRecursiveSeparableImageFilterPython.itkRecursiveSeparableImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetSigma: Any = ...
    SetSigma: Any = ...
    SetNormalizeAcrossScale: Any = ...
    GetNormalizeAcrossScale: Any = ...
    SetOrder: Any = ...
    GetOrder: Any = ...
    SetZeroOrder: Any = ...
    SetFirstOrder: Any = ...
    SetSecondOrder: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRecursiveGaussianImageFilterIUC3IUC3___New_orig__: Any
itkRecursiveGaussianImageFilterIUC3IUC3_cast: Any

def recursive_gaussian_image_filter(*args: Any, **kwargs: Any): ...
def recursive_gaussian_image_filter_init_docstring() -> None: ...
