import itk.itkVariableLengthVectorPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkRigid3DPerspectiveTransformD_New(): ...

class itkRigid3DPerspectiveTransformD(itk.itkTransformBasePython.itkTransformD32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOffset: Any = ...
    GetRotation: Any = ...
    SetOffset: Any = ...
    SetRotation: Any = ...
    SetFocalDistance: Any = ...
    GetFocalDistance: Any = ...
    TransformVector: Any = ...
    GetRotationMatrix: Any = ...
    ComputeMatrix: Any = ...
    GetFixedOffset: Any = ...
    SetFixedOffset: Any = ...
    SetCenterOfRotation: Any = ...
    GetCenterOfRotation: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkRigid3DPerspectiveTransformD___New_orig__: Any
itkRigid3DPerspectiveTransformD_cast: Any
