import itk.itkRGBPixelPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkScalarImageToHistogramGeneratorIF2_New(): ...

class itkScalarImageToHistogramGeneratorIF2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Compute: Any = ...
    SetInput: Any = ...
    GetOutput: Any = ...
    SetNumberOfBins: Any = ...
    SetMarginalScale: Any = ...
    SetHistogramMin: Any = ...
    SetHistogramMax: Any = ...
    SetAutoHistogramMinimumMaximum: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToHistogramGeneratorIF2___New_orig__: Any
itkScalarImageToHistogramGeneratorIF2_cast: Any

def itkScalarImageToHistogramGeneratorIF3_New(): ...

class itkScalarImageToHistogramGeneratorIF3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Compute: Any = ...
    SetInput: Any = ...
    GetOutput: Any = ...
    SetNumberOfBins: Any = ...
    SetMarginalScale: Any = ...
    SetHistogramMin: Any = ...
    SetHistogramMax: Any = ...
    SetAutoHistogramMinimumMaximum: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToHistogramGeneratorIF3___New_orig__: Any
itkScalarImageToHistogramGeneratorIF3_cast: Any

def itkScalarImageToHistogramGeneratorISS2_New(): ...

class itkScalarImageToHistogramGeneratorISS2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Compute: Any = ...
    SetInput: Any = ...
    GetOutput: Any = ...
    SetNumberOfBins: Any = ...
    SetMarginalScale: Any = ...
    SetHistogramMin: Any = ...
    SetHistogramMax: Any = ...
    SetAutoHistogramMinimumMaximum: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToHistogramGeneratorISS2___New_orig__: Any
itkScalarImageToHistogramGeneratorISS2_cast: Any

def itkScalarImageToHistogramGeneratorISS3_New(): ...

class itkScalarImageToHistogramGeneratorISS3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Compute: Any = ...
    SetInput: Any = ...
    GetOutput: Any = ...
    SetNumberOfBins: Any = ...
    SetMarginalScale: Any = ...
    SetHistogramMin: Any = ...
    SetHistogramMax: Any = ...
    SetAutoHistogramMinimumMaximum: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToHistogramGeneratorISS3___New_orig__: Any
itkScalarImageToHistogramGeneratorISS3_cast: Any

def itkScalarImageToHistogramGeneratorIUC2_New(): ...

class itkScalarImageToHistogramGeneratorIUC2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Compute: Any = ...
    SetInput: Any = ...
    GetOutput: Any = ...
    SetNumberOfBins: Any = ...
    SetMarginalScale: Any = ...
    SetHistogramMin: Any = ...
    SetHistogramMax: Any = ...
    SetAutoHistogramMinimumMaximum: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToHistogramGeneratorIUC2___New_orig__: Any
itkScalarImageToHistogramGeneratorIUC2_cast: Any

def itkScalarImageToHistogramGeneratorIUC3_New(): ...

class itkScalarImageToHistogramGeneratorIUC3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Compute: Any = ...
    SetInput: Any = ...
    GetOutput: Any = ...
    SetNumberOfBins: Any = ...
    SetMarginalScale: Any = ...
    SetHistogramMin: Any = ...
    SetHistogramMax: Any = ...
    SetAutoHistogramMinimumMaximum: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToHistogramGeneratorIUC3___New_orig__: Any
itkScalarImageToHistogramGeneratorIUC3_cast: Any
