import itk.itkArray2DPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkShapePriorMAPCostFunctionBaseIF2F(itk.ITKCostFunctionsPython.itkSingleValuedCostFunction):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetShapeFunction: Any = ...
    GetModifiableShapeFunction: Any = ...
    GetShapeFunction: Any = ...
    SetActiveRegion: Any = ...
    GetActiveRegion: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    ComputeLogInsideTerm: Any = ...
    ComputeLogGradientTerm: Any = ...
    ComputeLogShapePriorTerm: Any = ...
    ComputeLogPosePriorTerm: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkShapePriorMAPCostFunctionBaseIF2F_cast: Any

class itkShapePriorMAPCostFunctionBaseIF3F(itk.ITKCostFunctionsPython.itkSingleValuedCostFunction):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetShapeFunction: Any = ...
    GetModifiableShapeFunction: Any = ...
    GetShapeFunction: Any = ...
    SetActiveRegion: Any = ...
    GetActiveRegion: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    ComputeLogInsideTerm: Any = ...
    ComputeLogGradientTerm: Any = ...
    ComputeLogShapePriorTerm: Any = ...
    ComputeLogPosePriorTerm: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkShapePriorMAPCostFunctionBaseIF3F_cast: Any
