import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkShrinkImageFilterICF2ICF2_New(): ...

class itkShrinkImageFilterICF2ICF2(itk.itkImageToImageFilterBPython.itkImageToImageFilterICF2ICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterICF2ICF2___New_orig__: Any
itkShrinkImageFilterICF2ICF2_cast: Any

def itkShrinkImageFilterICF3ICF3_New(): ...

class itkShrinkImageFilterICF3ICF3(itk.itkImageToImageFilterBPython.itkImageToImageFilterICF3ICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterICF3ICF3___New_orig__: Any
itkShrinkImageFilterICF3ICF3_cast: Any

def itkShrinkImageFilterICVF22ICVF22_New(): ...

class itkShrinkImageFilterICVF22ICVF22(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF22ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterICVF22ICVF22___New_orig__: Any
itkShrinkImageFilterICVF22ICVF22_cast: Any

def itkShrinkImageFilterICVF23ICVF23_New(): ...

class itkShrinkImageFilterICVF23ICVF23(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF23ICVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterICVF23ICVF23___New_orig__: Any
itkShrinkImageFilterICVF23ICVF23_cast: Any

def itkShrinkImageFilterICVF32ICVF32_New(): ...

class itkShrinkImageFilterICVF32ICVF32(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF32ICVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterICVF32ICVF32___New_orig__: Any
itkShrinkImageFilterICVF32ICVF32_cast: Any

def itkShrinkImageFilterICVF33ICVF33_New(): ...

class itkShrinkImageFilterICVF33ICVF33(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF33ICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterICVF33ICVF33___New_orig__: Any
itkShrinkImageFilterICVF33ICVF33_cast: Any

def itkShrinkImageFilterICVF42ICVF42_New(): ...

class itkShrinkImageFilterICVF42ICVF42(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF42ICVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterICVF42ICVF42___New_orig__: Any
itkShrinkImageFilterICVF42ICVF42_cast: Any

def itkShrinkImageFilterICVF43ICVF43_New(): ...

class itkShrinkImageFilterICVF43ICVF43(itk.itkImageToImageFilterAPython.itkImageToImageFilterICVF43ICVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterICVF43ICVF43___New_orig__: Any
itkShrinkImageFilterICVF43ICVF43_cast: Any

def itkShrinkImageFilterIF2IF2_New(): ...

class itkShrinkImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterIF2IF2___New_orig__: Any
itkShrinkImageFilterIF2IF2_cast: Any

def itkShrinkImageFilterIF3IF3_New(): ...

class itkShrinkImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterIF3IF3___New_orig__: Any
itkShrinkImageFilterIF3IF3_cast: Any

def itkShrinkImageFilterIRGBAUC2IRGBAUC2_New(): ...

class itkShrinkImageFilterIRGBAUC2IRGBAUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBAUC2IRGBAUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterIRGBAUC2IRGBAUC2___New_orig__: Any
itkShrinkImageFilterIRGBAUC2IRGBAUC2_cast: Any

def itkShrinkImageFilterIRGBAUC3IRGBAUC3_New(): ...

class itkShrinkImageFilterIRGBAUC3IRGBAUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBAUC3IRGBAUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterIRGBAUC3IRGBAUC3___New_orig__: Any
itkShrinkImageFilterIRGBAUC3IRGBAUC3_cast: Any

def itkShrinkImageFilterIRGBUC2IRGBUC2_New(): ...

class itkShrinkImageFilterIRGBUC2IRGBUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBUC2IRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterIRGBUC2IRGBUC2___New_orig__: Any
itkShrinkImageFilterIRGBUC2IRGBUC2_cast: Any

def itkShrinkImageFilterIRGBUC3IRGBUC3_New(): ...

class itkShrinkImageFilterIRGBUC3IRGBUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIRGBUC3IRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterIRGBUC3IRGBUC3___New_orig__: Any
itkShrinkImageFilterIRGBUC3IRGBUC3_cast: Any

def itkShrinkImageFilterISS2ISS2_New(): ...

class itkShrinkImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterISS2ISS2___New_orig__: Any
itkShrinkImageFilterISS2ISS2_cast: Any

def itkShrinkImageFilterISS3ISS3_New(): ...

class itkShrinkImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterISS3ISS3___New_orig__: Any
itkShrinkImageFilterISS3ISS3_cast: Any

def itkShrinkImageFilterIUC2IUC2_New(): ...

class itkShrinkImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterIUC2IUC2___New_orig__: Any
itkShrinkImageFilterIUC2IUC2_cast: Any

def itkShrinkImageFilterIUC3IUC3_New(): ...

class itkShrinkImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterIUC3IUC3___New_orig__: Any
itkShrinkImageFilterIUC3IUC3_cast: Any

def itkShrinkImageFilterIVF22IVF22_New(): ...

class itkShrinkImageFilterIVF22IVF22(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF22IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterIVF22IVF22___New_orig__: Any
itkShrinkImageFilterIVF22IVF22_cast: Any

def itkShrinkImageFilterIVF23IVF23_New(): ...

class itkShrinkImageFilterIVF23IVF23(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF23IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterIVF23IVF23___New_orig__: Any
itkShrinkImageFilterIVF23IVF23_cast: Any

def itkShrinkImageFilterIVF32IVF32_New(): ...

class itkShrinkImageFilterIVF32IVF32(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF32IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterIVF32IVF32___New_orig__: Any
itkShrinkImageFilterIVF32IVF32_cast: Any

def itkShrinkImageFilterIVF33IVF33_New(): ...

class itkShrinkImageFilterIVF33IVF33(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF33IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterIVF33IVF33___New_orig__: Any
itkShrinkImageFilterIVF33IVF33_cast: Any

def itkShrinkImageFilterIVF42IVF42_New(): ...

class itkShrinkImageFilterIVF42IVF42(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF42IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterIVF42IVF42___New_orig__: Any
itkShrinkImageFilterIVF42IVF42_cast: Any

def itkShrinkImageFilterIVF43IVF43_New(): ...

class itkShrinkImageFilterIVF43IVF43(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF43IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShrinkFactors: Any = ...
    SetShrinkFactor: Any = ...
    GetShrinkFactors: Any = ...
    GenerateOutputInformation: Any = ...
    GenerateInputRequestedRegion: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    SameDimensionCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShrinkImageFilterIVF43IVF43___New_orig__: Any
itkShrinkImageFilterIVF43IVF43_cast: Any

def shrink_image_filter(*args: Any, **kwargs: Any): ...
def shrink_image_filter_init_docstring() -> None: ...
