import itk.itkRGBPixelPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkScalarImageToRunLengthFeaturesFilterIF2_New(): ...

class itkScalarImageToRunLengthFeaturesFilterIF2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFeatureMeansOutput: Any = ...
    GetFeatureStandardDeviationsOutput: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetFeatureMeans: Any = ...
    GetFeatureStandardDeviations: Any = ...
    SetRequestedFeatures: Any = ...
    GetRequestedFeatures: Any = ...
    SetOffsets: Any = ...
    GetOffsets: Any = ...
    SetNumberOfBinsPerAxis: Any = ...
    SetPixelValueMinMax: Any = ...
    SetDistanceValueMinMax: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetInsidePixelValue: Any = ...
    GetFastCalculations: Any = ...
    SetFastCalculations: Any = ...
    FastCalculationsOn: Any = ...
    FastCalculationsOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToRunLengthFeaturesFilterIF2___New_orig__: Any
itkScalarImageToRunLengthFeaturesFilterIF2_cast: Any

def itkScalarImageToRunLengthFeaturesFilterIF3_New(): ...

class itkScalarImageToRunLengthFeaturesFilterIF3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFeatureMeansOutput: Any = ...
    GetFeatureStandardDeviationsOutput: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetFeatureMeans: Any = ...
    GetFeatureStandardDeviations: Any = ...
    SetRequestedFeatures: Any = ...
    GetRequestedFeatures: Any = ...
    SetOffsets: Any = ...
    GetOffsets: Any = ...
    SetNumberOfBinsPerAxis: Any = ...
    SetPixelValueMinMax: Any = ...
    SetDistanceValueMinMax: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetInsidePixelValue: Any = ...
    GetFastCalculations: Any = ...
    SetFastCalculations: Any = ...
    FastCalculationsOn: Any = ...
    FastCalculationsOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToRunLengthFeaturesFilterIF3___New_orig__: Any
itkScalarImageToRunLengthFeaturesFilterIF3_cast: Any

def itkScalarImageToRunLengthFeaturesFilterISS2_New(): ...

class itkScalarImageToRunLengthFeaturesFilterISS2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFeatureMeansOutput: Any = ...
    GetFeatureStandardDeviationsOutput: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetFeatureMeans: Any = ...
    GetFeatureStandardDeviations: Any = ...
    SetRequestedFeatures: Any = ...
    GetRequestedFeatures: Any = ...
    SetOffsets: Any = ...
    GetOffsets: Any = ...
    SetNumberOfBinsPerAxis: Any = ...
    SetPixelValueMinMax: Any = ...
    SetDistanceValueMinMax: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetInsidePixelValue: Any = ...
    GetFastCalculations: Any = ...
    SetFastCalculations: Any = ...
    FastCalculationsOn: Any = ...
    FastCalculationsOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToRunLengthFeaturesFilterISS2___New_orig__: Any
itkScalarImageToRunLengthFeaturesFilterISS2_cast: Any

def itkScalarImageToRunLengthFeaturesFilterISS3_New(): ...

class itkScalarImageToRunLengthFeaturesFilterISS3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFeatureMeansOutput: Any = ...
    GetFeatureStandardDeviationsOutput: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetFeatureMeans: Any = ...
    GetFeatureStandardDeviations: Any = ...
    SetRequestedFeatures: Any = ...
    GetRequestedFeatures: Any = ...
    SetOffsets: Any = ...
    GetOffsets: Any = ...
    SetNumberOfBinsPerAxis: Any = ...
    SetPixelValueMinMax: Any = ...
    SetDistanceValueMinMax: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetInsidePixelValue: Any = ...
    GetFastCalculations: Any = ...
    SetFastCalculations: Any = ...
    FastCalculationsOn: Any = ...
    FastCalculationsOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToRunLengthFeaturesFilterISS3___New_orig__: Any
itkScalarImageToRunLengthFeaturesFilterISS3_cast: Any

def itkScalarImageToRunLengthFeaturesFilterIUC2_New(): ...

class itkScalarImageToRunLengthFeaturesFilterIUC2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFeatureMeansOutput: Any = ...
    GetFeatureStandardDeviationsOutput: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetFeatureMeans: Any = ...
    GetFeatureStandardDeviations: Any = ...
    SetRequestedFeatures: Any = ...
    GetRequestedFeatures: Any = ...
    SetOffsets: Any = ...
    GetOffsets: Any = ...
    SetNumberOfBinsPerAxis: Any = ...
    SetPixelValueMinMax: Any = ...
    SetDistanceValueMinMax: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetInsidePixelValue: Any = ...
    GetFastCalculations: Any = ...
    SetFastCalculations: Any = ...
    FastCalculationsOn: Any = ...
    FastCalculationsOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToRunLengthFeaturesFilterIUC2___New_orig__: Any
itkScalarImageToRunLengthFeaturesFilterIUC2_cast: Any

def itkScalarImageToRunLengthFeaturesFilterIUC3_New(): ...

class itkScalarImageToRunLengthFeaturesFilterIUC3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFeatureMeansOutput: Any = ...
    GetFeatureStandardDeviationsOutput: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetFeatureMeans: Any = ...
    GetFeatureStandardDeviations: Any = ...
    SetRequestedFeatures: Any = ...
    GetRequestedFeatures: Any = ...
    SetOffsets: Any = ...
    GetOffsets: Any = ...
    SetNumberOfBinsPerAxis: Any = ...
    SetPixelValueMinMax: Any = ...
    SetDistanceValueMinMax: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetInsidePixelValue: Any = ...
    GetFastCalculations: Any = ...
    SetFastCalculations: Any = ...
    FastCalculationsOn: Any = ...
    FastCalculationsOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToRunLengthFeaturesFilterIUC3___New_orig__: Any
itkScalarImageToRunLengthFeaturesFilterIUC3_cast: Any

def scalar_image_to_run_length_features_filter(*args: Any, **kwargs: Any): ...
def scalar_image_to_run_length_features_filter_init_docstring() -> None: ...
