import itk.itkLabelObjectLinePython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkFixedArrayPD24:
    thisown: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    SetElement: Any = ...
    GetElement: Any = ...
    GetDataPointer: Any = ...
    data: Any = ...
    cbegin: Any = ...
    begin: Any = ...
    cend: Any = ...
    end: Any = ...
    crbegin: Any = ...
    rbegin: Any = ...
    crend: Any = ...
    rend: Any = ...
    Size: Any = ...
    size: Any = ...
    Fill: Any = ...
    swap: Any = ...
    Filled: Any = ...

itkFixedArrayPD24_Filled: Any

class itkFixedArrayPD38:
    thisown: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __eq__: Any = ...
    __ne__: Any = ...
    SetElement: Any = ...
    GetElement: Any = ...
    GetDataPointer: Any = ...
    data: Any = ...
    cbegin: Any = ...
    begin: Any = ...
    cend: Any = ...
    end: Any = ...
    crbegin: Any = ...
    rbegin: Any = ...
    crend: Any = ...
    rend: Any = ...
    Size: Any = ...
    size: Any = ...
    Fill: Any = ...
    swap: Any = ...
    Filled: Any = ...

itkFixedArrayPD38_Filled: Any

def itkShapeLabelObjectUL2_New(): ...

class itkShapeLabelObjectUL2(itk.itkLabelObjectPython.itkLabelObjectUL2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetAttributeFromName: Any = ...
    GetNameFromAttribute: Any = ...
    GetBoundingBox: Any = ...
    SetBoundingBox: Any = ...
    GetPhysicalSize: Any = ...
    SetPhysicalSize: Any = ...
    GetNumberOfPixels: Any = ...
    SetNumberOfPixels: Any = ...
    GetCentroid: Any = ...
    SetCentroid: Any = ...
    GetNumberOfPixelsOnBorder: Any = ...
    SetNumberOfPixelsOnBorder: Any = ...
    GetPerimeterOnBorder: Any = ...
    SetPerimeterOnBorder: Any = ...
    GetFeretDiameter: Any = ...
    SetFeretDiameter: Any = ...
    GetPrincipalMoments: Any = ...
    SetPrincipalMoments: Any = ...
    GetPrincipalAxes: Any = ...
    SetPrincipalAxes: Any = ...
    GetElongation: Any = ...
    SetElongation: Any = ...
    GetPerimeter: Any = ...
    SetPerimeter: Any = ...
    GetRoundness: Any = ...
    SetRoundness: Any = ...
    GetEquivalentSphericalRadius: Any = ...
    SetEquivalentSphericalRadius: Any = ...
    GetEquivalentSphericalPerimeter: Any = ...
    SetEquivalentSphericalPerimeter: Any = ...
    GetEquivalentEllipsoidDiameter: Any = ...
    SetEquivalentEllipsoidDiameter: Any = ...
    GetFlatness: Any = ...
    SetFlatness: Any = ...
    GetPerimeterOnBorderRatio: Any = ...
    SetPerimeterOnBorderRatio: Any = ...
    GetOrientedBoundingBoxOrigin: Any = ...
    SetOrientedBoundingBoxOrigin: Any = ...
    GetOrientedBoundingBoxSize: Any = ...
    SetOrientedBoundingBoxSize: Any = ...
    GetRegion: Any = ...
    GetOrientedBoundingBoxDirection: Any = ...
    GetOrientedBoundingBoxVertices: Any = ...
    GetPrincipalAxesToPhysicalAxesTransform: Any = ...
    GetPhysicalAxesToPrincipalAxesTransform: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShapeLabelObjectUL2___New_orig__: Any
itkShapeLabelObjectUL2_GetAttributeFromName: Any
itkShapeLabelObjectUL2_GetNameFromAttribute: Any
itkShapeLabelObjectUL2_cast: Any

def itkShapeLabelObjectUL3_New(): ...

class itkShapeLabelObjectUL3(itk.itkLabelObjectPython.itkLabelObjectUL3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetAttributeFromName: Any = ...
    GetNameFromAttribute: Any = ...
    GetBoundingBox: Any = ...
    SetBoundingBox: Any = ...
    GetPhysicalSize: Any = ...
    SetPhysicalSize: Any = ...
    GetNumberOfPixels: Any = ...
    SetNumberOfPixels: Any = ...
    GetCentroid: Any = ...
    SetCentroid: Any = ...
    GetNumberOfPixelsOnBorder: Any = ...
    SetNumberOfPixelsOnBorder: Any = ...
    GetPerimeterOnBorder: Any = ...
    SetPerimeterOnBorder: Any = ...
    GetFeretDiameter: Any = ...
    SetFeretDiameter: Any = ...
    GetPrincipalMoments: Any = ...
    SetPrincipalMoments: Any = ...
    GetPrincipalAxes: Any = ...
    SetPrincipalAxes: Any = ...
    GetElongation: Any = ...
    SetElongation: Any = ...
    GetPerimeter: Any = ...
    SetPerimeter: Any = ...
    GetRoundness: Any = ...
    SetRoundness: Any = ...
    GetEquivalentSphericalRadius: Any = ...
    SetEquivalentSphericalRadius: Any = ...
    GetEquivalentSphericalPerimeter: Any = ...
    SetEquivalentSphericalPerimeter: Any = ...
    GetEquivalentEllipsoidDiameter: Any = ...
    SetEquivalentEllipsoidDiameter: Any = ...
    GetFlatness: Any = ...
    SetFlatness: Any = ...
    GetPerimeterOnBorderRatio: Any = ...
    SetPerimeterOnBorderRatio: Any = ...
    GetOrientedBoundingBoxOrigin: Any = ...
    SetOrientedBoundingBoxOrigin: Any = ...
    GetOrientedBoundingBoxSize: Any = ...
    SetOrientedBoundingBoxSize: Any = ...
    GetRegion: Any = ...
    GetOrientedBoundingBoxDirection: Any = ...
    GetOrientedBoundingBoxVertices: Any = ...
    GetPrincipalAxesToPhysicalAxesTransform: Any = ...
    GetPhysicalAxesToPrincipalAxesTransform: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShapeLabelObjectUL3___New_orig__: Any
itkShapeLabelObjectUL3_GetAttributeFromName: Any
itkShapeLabelObjectUL3_GetNameFromAttribute: Any
itkShapeLabelObjectUL3_cast: Any
