import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkSimilarityIndexImageFilterIF2IF2_New(): ...

class itkSimilarityIndexImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    GetInput1: Any = ...
    GetInput2: Any = ...
    GetSimilarityIndex: Any = ...
    Input1HasNumericTraitsCheck: Any = ...
    Input2HasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimilarityIndexImageFilterIF2IF2___New_orig__: Any
itkSimilarityIndexImageFilterIF2IF2_cast: Any

def itkSimilarityIndexImageFilterIF3IF3_New(): ...

class itkSimilarityIndexImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    GetInput1: Any = ...
    GetInput2: Any = ...
    GetSimilarityIndex: Any = ...
    Input1HasNumericTraitsCheck: Any = ...
    Input2HasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimilarityIndexImageFilterIF3IF3___New_orig__: Any
itkSimilarityIndexImageFilterIF3IF3_cast: Any

def itkSimilarityIndexImageFilterISS2ISS2_New(): ...

class itkSimilarityIndexImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    GetInput1: Any = ...
    GetInput2: Any = ...
    GetSimilarityIndex: Any = ...
    Input1HasNumericTraitsCheck: Any = ...
    Input2HasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimilarityIndexImageFilterISS2ISS2___New_orig__: Any
itkSimilarityIndexImageFilterISS2ISS2_cast: Any

def itkSimilarityIndexImageFilterISS3ISS3_New(): ...

class itkSimilarityIndexImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    GetInput1: Any = ...
    GetInput2: Any = ...
    GetSimilarityIndex: Any = ...
    Input1HasNumericTraitsCheck: Any = ...
    Input2HasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimilarityIndexImageFilterISS3ISS3___New_orig__: Any
itkSimilarityIndexImageFilterISS3ISS3_cast: Any

def itkSimilarityIndexImageFilterIUC2IUC2_New(): ...

class itkSimilarityIndexImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    GetInput1: Any = ...
    GetInput2: Any = ...
    GetSimilarityIndex: Any = ...
    Input1HasNumericTraitsCheck: Any = ...
    Input2HasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimilarityIndexImageFilterIUC2IUC2___New_orig__: Any
itkSimilarityIndexImageFilterIUC2IUC2_cast: Any

def itkSimilarityIndexImageFilterIUC3IUC3_New(): ...

class itkSimilarityIndexImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    GetInput1: Any = ...
    GetInput2: Any = ...
    GetSimilarityIndex: Any = ...
    Input1HasNumericTraitsCheck: Any = ...
    Input2HasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimilarityIndexImageFilterIUC3IUC3___New_orig__: Any
itkSimilarityIndexImageFilterIUC3IUC3_cast: Any

def similarity_index_image_filter(*args: Any, **kwargs: Any): ...
def similarity_index_image_filter_init_docstring() -> None: ...
