import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkStatisticsUniqueLabelMapFilterLM2_New(): ...

class itkStatisticsUniqueLabelMapFilterLM2(itk.itkShapeUniqueLabelMapFilterPython.itkShapeUniqueLabelMapFilterLM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStatisticsUniqueLabelMapFilterLM2___New_orig__: Any
itkStatisticsUniqueLabelMapFilterLM2_cast: Any

def itkStatisticsUniqueLabelMapFilterLM3_New(): ...

class itkStatisticsUniqueLabelMapFilterLM3(itk.itkShapeUniqueLabelMapFilterPython.itkShapeUniqueLabelMapFilterLM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStatisticsUniqueLabelMapFilterLM3___New_orig__: Any
itkStatisticsUniqueLabelMapFilterLM3_cast: Any

def statistics_unique_label_map_filter(*args: Any, **kwargs: Any): ...
def statistics_unique_label_map_filter_init_docstring() -> None: ...
