import itk.itkLabelObjectLinePython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class mapitkStatisticsLabelObjectUL2(collections.abc.MutableMapping):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    def __iter__(self) -> Any: ...
    def iterkeys(self): ...
    def itervalues(self): ...
    def iteritems(self): ...
    __getitem__: Any = ...
    __delitem__: Any = ...
    has_key: Any = ...
    keys: Any = ...
    values: Any = ...
    items: Any = ...
    __contains__: Any = ...
    key_iterator: Any = ...
    value_iterator: Any = ...
    __setitem__: Any = ...
    asdict: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    count: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    __swig_destroy__: Any = ...

class vectoritkStatisticsLabelObjectUL2(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class mapitkStatisticsLabelObjectUL3(collections.abc.MutableMapping):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    def __iter__(self) -> Any: ...
    def iterkeys(self): ...
    def itervalues(self): ...
    def iteritems(self): ...
    __getitem__: Any = ...
    __delitem__: Any = ...
    has_key: Any = ...
    keys: Any = ...
    values: Any = ...
    items: Any = ...
    __contains__: Any = ...
    key_iterator: Any = ...
    value_iterator: Any = ...
    __setitem__: Any = ...
    asdict: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    count: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    __swig_destroy__: Any = ...

class vectoritkStatisticsLabelObjectUL3(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

def itkStatisticsLabelObjectUL2_New(): ...

class itkStatisticsLabelObjectUL2(itk.itkShapeLabelObjectPython.itkShapeLabelObjectUL2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetAttributeFromName: Any = ...
    GetNameFromAttribute: Any = ...
    GetMinimum: Any = ...
    SetMinimum: Any = ...
    GetMaximum: Any = ...
    SetMaximum: Any = ...
    GetMean: Any = ...
    SetMean: Any = ...
    GetSum: Any = ...
    SetSum: Any = ...
    GetStandardDeviation: Any = ...
    SetStandardDeviation: Any = ...
    GetVariance: Any = ...
    SetVariance: Any = ...
    GetMedian: Any = ...
    SetMedian: Any = ...
    GetMaximumIndex: Any = ...
    SetMaximumIndex: Any = ...
    GetMinimumIndex: Any = ...
    SetMinimumIndex: Any = ...
    GetCenterOfGravity: Any = ...
    SetCenterOfGravity: Any = ...
    GetWeightedPrincipalMoments: Any = ...
    SetWeightedPrincipalMoments: Any = ...
    GetWeightedPrincipalAxes: Any = ...
    SetWeightedPrincipalAxes: Any = ...
    GetSkewness: Any = ...
    SetSkewness: Any = ...
    GetKurtosis: Any = ...
    SetKurtosis: Any = ...
    GetWeightedElongation: Any = ...
    SetWeightedElongation: Any = ...
    GetHistogram: Any = ...
    SetHistogram: Any = ...
    GetWeightedFlatness: Any = ...
    SetWeightedFlatness: Any = ...
    GetWeightedPrincipalAxesToPhysicalAxesTransform: Any = ...
    GetPhysicalAxesToWeightedPrincipalAxesTransform: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStatisticsLabelObjectUL2___New_orig__: Any
itkStatisticsLabelObjectUL2_GetAttributeFromName: Any
itkStatisticsLabelObjectUL2_GetNameFromAttribute: Any
itkStatisticsLabelObjectUL2_cast: Any

def itkStatisticsLabelObjectUL3_New(): ...

class itkStatisticsLabelObjectUL3(itk.itkShapeLabelObjectPython.itkShapeLabelObjectUL3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetAttributeFromName: Any = ...
    GetNameFromAttribute: Any = ...
    GetMinimum: Any = ...
    SetMinimum: Any = ...
    GetMaximum: Any = ...
    SetMaximum: Any = ...
    GetMean: Any = ...
    SetMean: Any = ...
    GetSum: Any = ...
    SetSum: Any = ...
    GetStandardDeviation: Any = ...
    SetStandardDeviation: Any = ...
    GetVariance: Any = ...
    SetVariance: Any = ...
    GetMedian: Any = ...
    SetMedian: Any = ...
    GetMaximumIndex: Any = ...
    SetMaximumIndex: Any = ...
    GetMinimumIndex: Any = ...
    SetMinimumIndex: Any = ...
    GetCenterOfGravity: Any = ...
    SetCenterOfGravity: Any = ...
    GetWeightedPrincipalMoments: Any = ...
    SetWeightedPrincipalMoments: Any = ...
    GetWeightedPrincipalAxes: Any = ...
    SetWeightedPrincipalAxes: Any = ...
    GetSkewness: Any = ...
    SetSkewness: Any = ...
    GetKurtosis: Any = ...
    SetKurtosis: Any = ...
    GetWeightedElongation: Any = ...
    SetWeightedElongation: Any = ...
    GetHistogram: Any = ...
    SetHistogram: Any = ...
    GetWeightedFlatness: Any = ...
    SetWeightedFlatness: Any = ...
    GetWeightedPrincipalAxesToPhysicalAxesTransform: Any = ...
    GetPhysicalAxesToWeightedPrincipalAxesTransform: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStatisticsLabelObjectUL3___New_orig__: Any
itkStatisticsLabelObjectUL3_GetAttributeFromName: Any
itkStatisticsLabelObjectUL3_GetNameFromAttribute: Any
itkStatisticsLabelObjectUL3_cast: Any
