import itk.itkArray2DPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkShapePriorMAPCostFunctionIF2F_New(): ...

class itkShapePriorMAPCostFunctionIF2F(itk.itkShapePriorMAPCostFunctionBasePython.itkShapePriorMAPCostFunctionBaseIF2F):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShapeParameterMeans: Any = ...
    GetShapeParameterMeans: Any = ...
    SetShapeParameterStandardDeviations: Any = ...
    GetShapeParameterStandardDeviations: Any = ...
    SetWeights: Any = ...
    GetWeights: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShapePriorMAPCostFunctionIF2F___New_orig__: Any
itkShapePriorMAPCostFunctionIF2F_cast: Any

def itkShapePriorMAPCostFunctionIF3F_New(): ...

class itkShapePriorMAPCostFunctionIF3F(itk.itkShapePriorMAPCostFunctionBasePython.itkShapePriorMAPCostFunctionBaseIF3F):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShapeParameterMeans: Any = ...
    GetShapeParameterMeans: Any = ...
    SetShapeParameterStandardDeviations: Any = ...
    GetShapeParameterStandardDeviations: Any = ...
    SetWeights: Any = ...
    GetWeights: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShapePriorMAPCostFunctionIF3F___New_orig__: Any
itkShapePriorMAPCostFunctionIF3F_cast: Any
