import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkSimpleContourExtractorImageFilterIF2IF2_New(): ...

class itkSimpleContourExtractorImageFilterIF2IF2(itk.itkBoxImageFilterPython.itkBoxImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputForegroundValue: Any = ...
    GetInputForegroundValue: Any = ...
    SetInputBackgroundValue: Any = ...
    GetInputBackgroundValue: Any = ...
    SetOutputForegroundValue: Any = ...
    GetOutputForegroundValue: Any = ...
    SetOutputBackgroundValue: Any = ...
    GetOutputBackgroundValue: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleContourExtractorImageFilterIF2IF2___New_orig__: Any
itkSimpleContourExtractorImageFilterIF2IF2_cast: Any

def itkSimpleContourExtractorImageFilterIF3IF3_New(): ...

class itkSimpleContourExtractorImageFilterIF3IF3(itk.itkBoxImageFilterPython.itkBoxImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputForegroundValue: Any = ...
    GetInputForegroundValue: Any = ...
    SetInputBackgroundValue: Any = ...
    GetInputBackgroundValue: Any = ...
    SetOutputForegroundValue: Any = ...
    GetOutputForegroundValue: Any = ...
    SetOutputBackgroundValue: Any = ...
    GetOutputBackgroundValue: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleContourExtractorImageFilterIF3IF3___New_orig__: Any
itkSimpleContourExtractorImageFilterIF3IF3_cast: Any

def itkSimpleContourExtractorImageFilterISS2ISS2_New(): ...

class itkSimpleContourExtractorImageFilterISS2ISS2(itk.itkBoxImageFilterPython.itkBoxImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputForegroundValue: Any = ...
    GetInputForegroundValue: Any = ...
    SetInputBackgroundValue: Any = ...
    GetInputBackgroundValue: Any = ...
    SetOutputForegroundValue: Any = ...
    GetOutputForegroundValue: Any = ...
    SetOutputBackgroundValue: Any = ...
    GetOutputBackgroundValue: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleContourExtractorImageFilterISS2ISS2___New_orig__: Any
itkSimpleContourExtractorImageFilterISS2ISS2_cast: Any

def itkSimpleContourExtractorImageFilterISS3ISS3_New(): ...

class itkSimpleContourExtractorImageFilterISS3ISS3(itk.itkBoxImageFilterPython.itkBoxImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputForegroundValue: Any = ...
    GetInputForegroundValue: Any = ...
    SetInputBackgroundValue: Any = ...
    GetInputBackgroundValue: Any = ...
    SetOutputForegroundValue: Any = ...
    GetOutputForegroundValue: Any = ...
    SetOutputBackgroundValue: Any = ...
    GetOutputBackgroundValue: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleContourExtractorImageFilterISS3ISS3___New_orig__: Any
itkSimpleContourExtractorImageFilterISS3ISS3_cast: Any

def itkSimpleContourExtractorImageFilterIUC2IUC2_New(): ...

class itkSimpleContourExtractorImageFilterIUC2IUC2(itk.itkBoxImageFilterPython.itkBoxImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputForegroundValue: Any = ...
    GetInputForegroundValue: Any = ...
    SetInputBackgroundValue: Any = ...
    GetInputBackgroundValue: Any = ...
    SetOutputForegroundValue: Any = ...
    GetOutputForegroundValue: Any = ...
    SetOutputBackgroundValue: Any = ...
    GetOutputBackgroundValue: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleContourExtractorImageFilterIUC2IUC2___New_orig__: Any
itkSimpleContourExtractorImageFilterIUC2IUC2_cast: Any

def itkSimpleContourExtractorImageFilterIUC3IUC3_New(): ...

class itkSimpleContourExtractorImageFilterIUC3IUC3(itk.itkBoxImageFilterPython.itkBoxImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetInputForegroundValue: Any = ...
    GetInputForegroundValue: Any = ...
    SetInputBackgroundValue: Any = ...
    GetInputBackgroundValue: Any = ...
    SetOutputForegroundValue: Any = ...
    GetOutputForegroundValue: Any = ...
    SetOutputBackgroundValue: Any = ...
    GetOutputBackgroundValue: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleContourExtractorImageFilterIUC3IUC3___New_orig__: Any
itkSimpleContourExtractorImageFilterIUC3IUC3_cast: Any

def simple_contour_extractor_image_filter(*args: Any, **kwargs: Any): ...
def simple_contour_extractor_image_filter_init_docstring() -> None: ...
