import itk.itkRGBPixelPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkSpatialFunctionD2PD2(itk.itkFunctionBasePython.itkFunctionBasePD2D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class itkSpatialFunctionD3PD3(itk.itkFunctionBasePython.itkFunctionBasePD3D):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class itkSpatialFunctionF2PD2(itk.itkFunctionBasePython.itkFunctionBasePD2F):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class itkSpatialFunctionF3PD3(itk.itkFunctionBasePython.itkFunctionBasePD3F):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
