import itk.itkContinuousIndexPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkScalarImageToRunLengthMatrixFilterIF2_New(): ...

class itkScalarImageToRunLengthMatrixFilterIF2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOffsets: Any = ...
    SetOffset: Any = ...
    GetModifiableOffsets: Any = ...
    GetOffsets: Any = ...
    SetNumberOfBinsPerAxis: Any = ...
    GetNumberOfBinsPerAxis: Any = ...
    SetPixelValueMinMax: Any = ...
    GetMin: Any = ...
    GetMax: Any = ...
    SetDistanceValueMinMax: Any = ...
    GetMinDistance: Any = ...
    GetMaxDistance: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    GetOutput: Any = ...
    SetInsidePixelValue: Any = ...
    GetInsidePixelValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToRunLengthMatrixFilterIF2___New_orig__: Any
itkScalarImageToRunLengthMatrixFilterIF2_cast: Any

def itkScalarImageToRunLengthMatrixFilterIF3_New(): ...

class itkScalarImageToRunLengthMatrixFilterIF3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOffsets: Any = ...
    SetOffset: Any = ...
    GetModifiableOffsets: Any = ...
    GetOffsets: Any = ...
    SetNumberOfBinsPerAxis: Any = ...
    GetNumberOfBinsPerAxis: Any = ...
    SetPixelValueMinMax: Any = ...
    GetMin: Any = ...
    GetMax: Any = ...
    SetDistanceValueMinMax: Any = ...
    GetMinDistance: Any = ...
    GetMaxDistance: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    GetOutput: Any = ...
    SetInsidePixelValue: Any = ...
    GetInsidePixelValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToRunLengthMatrixFilterIF3___New_orig__: Any
itkScalarImageToRunLengthMatrixFilterIF3_cast: Any

def itkScalarImageToRunLengthMatrixFilterISS2_New(): ...

class itkScalarImageToRunLengthMatrixFilterISS2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOffsets: Any = ...
    SetOffset: Any = ...
    GetModifiableOffsets: Any = ...
    GetOffsets: Any = ...
    SetNumberOfBinsPerAxis: Any = ...
    GetNumberOfBinsPerAxis: Any = ...
    SetPixelValueMinMax: Any = ...
    GetMin: Any = ...
    GetMax: Any = ...
    SetDistanceValueMinMax: Any = ...
    GetMinDistance: Any = ...
    GetMaxDistance: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    GetOutput: Any = ...
    SetInsidePixelValue: Any = ...
    GetInsidePixelValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToRunLengthMatrixFilterISS2___New_orig__: Any
itkScalarImageToRunLengthMatrixFilterISS2_cast: Any

def itkScalarImageToRunLengthMatrixFilterISS3_New(): ...

class itkScalarImageToRunLengthMatrixFilterISS3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOffsets: Any = ...
    SetOffset: Any = ...
    GetModifiableOffsets: Any = ...
    GetOffsets: Any = ...
    SetNumberOfBinsPerAxis: Any = ...
    GetNumberOfBinsPerAxis: Any = ...
    SetPixelValueMinMax: Any = ...
    GetMin: Any = ...
    GetMax: Any = ...
    SetDistanceValueMinMax: Any = ...
    GetMinDistance: Any = ...
    GetMaxDistance: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    GetOutput: Any = ...
    SetInsidePixelValue: Any = ...
    GetInsidePixelValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToRunLengthMatrixFilterISS3___New_orig__: Any
itkScalarImageToRunLengthMatrixFilterISS3_cast: Any

def itkScalarImageToRunLengthMatrixFilterIUC2_New(): ...

class itkScalarImageToRunLengthMatrixFilterIUC2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOffsets: Any = ...
    SetOffset: Any = ...
    GetModifiableOffsets: Any = ...
    GetOffsets: Any = ...
    SetNumberOfBinsPerAxis: Any = ...
    GetNumberOfBinsPerAxis: Any = ...
    SetPixelValueMinMax: Any = ...
    GetMin: Any = ...
    GetMax: Any = ...
    SetDistanceValueMinMax: Any = ...
    GetMinDistance: Any = ...
    GetMaxDistance: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    GetOutput: Any = ...
    SetInsidePixelValue: Any = ...
    GetInsidePixelValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToRunLengthMatrixFilterIUC2___New_orig__: Any
itkScalarImageToRunLengthMatrixFilterIUC2_cast: Any

def itkScalarImageToRunLengthMatrixFilterIUC3_New(): ...

class itkScalarImageToRunLengthMatrixFilterIUC3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOffsets: Any = ...
    SetOffset: Any = ...
    GetModifiableOffsets: Any = ...
    GetOffsets: Any = ...
    SetNumberOfBinsPerAxis: Any = ...
    GetNumberOfBinsPerAxis: Any = ...
    SetPixelValueMinMax: Any = ...
    GetMin: Any = ...
    GetMax: Any = ...
    SetDistanceValueMinMax: Any = ...
    GetMinDistance: Any = ...
    GetMaxDistance: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    GetOutput: Any = ...
    SetInsidePixelValue: Any = ...
    GetInsidePixelValue: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToRunLengthMatrixFilterIUC3___New_orig__: Any
itkScalarImageToRunLengthMatrixFilterIUC3_cast: Any

def scalar_image_to_run_length_matrix_filter(*args: Any, **kwargs: Any): ...
def scalar_image_to_run_length_matrix_filter_init_docstring() -> None: ...
