import itk.itkContinuousIndexPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class listitkPointBasedSpatialObjectSurface2_Pointer:
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

class listitkPointBasedSpatialObjectSurface3_Pointer:
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

class listitkSurfaceSpatialObject2_Pointer:
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

class listitkSurfaceSpatialObject3_Pointer:
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

def itkPointBasedSpatialObjectSurface2_New(): ...

class itkPointBasedSpatialObjectSurface2(itk.itkSpatialObjectBasePython.itkSpatialObject2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    AddPoint: Any = ...
    RemovePoint: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    GetPoint: Any = ...
    GetNumberOfPoints: Any = ...
    ClosestPointInWorldSpace: Any = ...
    ClosestPointInObjectSpace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointBasedSpatialObjectSurface2___New_orig__: Any
itkPointBasedSpatialObjectSurface2_cast: Any

def itkPointBasedSpatialObjectSurface3_New(): ...

class itkPointBasedSpatialObjectSurface3(itk.itkSpatialObjectBasePython.itkSpatialObject3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    AddPoint: Any = ...
    RemovePoint: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    GetPoint: Any = ...
    GetNumberOfPoints: Any = ...
    ClosestPointInWorldSpace: Any = ...
    ClosestPointInObjectSpace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointBasedSpatialObjectSurface3___New_orig__: Any
itkPointBasedSpatialObjectSurface3_cast: Any

def itkSurfaceSpatialObject2_New(): ...

class itkSurfaceSpatialObject2(itkPointBasedSpatialObjectSurface2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Approximate3DNormals: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSurfaceSpatialObject2___New_orig__: Any
itkSurfaceSpatialObject2_cast: Any

def itkSurfaceSpatialObject3_New(): ...

class itkSurfaceSpatialObject3(itkPointBasedSpatialObjectSurface3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Approximate3DNormals: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSurfaceSpatialObject3___New_orig__: Any
itkSurfaceSpatialObject3_cast: Any
