import itk.itkContinuousIndexPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkScalarImageToTextureFeaturesFilterIF2_New(): ...

class itkScalarImageToTextureFeaturesFilterIF2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFeatureMeansOutput: Any = ...
    GetFeatureStandardDeviationsOutput: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetFeatureMeans: Any = ...
    GetFeatureStandardDeviations: Any = ...
    SetRequestedFeatures: Any = ...
    GetRequestedFeatures: Any = ...
    SetOffsets: Any = ...
    GetOffsets: Any = ...
    SetNumberOfBinsPerAxis: Any = ...
    SetPixelValueMinMax: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetInsidePixelValue: Any = ...
    GetFastCalculations: Any = ...
    SetFastCalculations: Any = ...
    FastCalculationsOn: Any = ...
    FastCalculationsOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToTextureFeaturesFilterIF2___New_orig__: Any
itkScalarImageToTextureFeaturesFilterIF2_cast: Any

def itkScalarImageToTextureFeaturesFilterIF3_New(): ...

class itkScalarImageToTextureFeaturesFilterIF3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFeatureMeansOutput: Any = ...
    GetFeatureStandardDeviationsOutput: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetFeatureMeans: Any = ...
    GetFeatureStandardDeviations: Any = ...
    SetRequestedFeatures: Any = ...
    GetRequestedFeatures: Any = ...
    SetOffsets: Any = ...
    GetOffsets: Any = ...
    SetNumberOfBinsPerAxis: Any = ...
    SetPixelValueMinMax: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetInsidePixelValue: Any = ...
    GetFastCalculations: Any = ...
    SetFastCalculations: Any = ...
    FastCalculationsOn: Any = ...
    FastCalculationsOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToTextureFeaturesFilterIF3___New_orig__: Any
itkScalarImageToTextureFeaturesFilterIF3_cast: Any

def itkScalarImageToTextureFeaturesFilterISS2_New(): ...

class itkScalarImageToTextureFeaturesFilterISS2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFeatureMeansOutput: Any = ...
    GetFeatureStandardDeviationsOutput: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetFeatureMeans: Any = ...
    GetFeatureStandardDeviations: Any = ...
    SetRequestedFeatures: Any = ...
    GetRequestedFeatures: Any = ...
    SetOffsets: Any = ...
    GetOffsets: Any = ...
    SetNumberOfBinsPerAxis: Any = ...
    SetPixelValueMinMax: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetInsidePixelValue: Any = ...
    GetFastCalculations: Any = ...
    SetFastCalculations: Any = ...
    FastCalculationsOn: Any = ...
    FastCalculationsOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToTextureFeaturesFilterISS2___New_orig__: Any
itkScalarImageToTextureFeaturesFilterISS2_cast: Any

def itkScalarImageToTextureFeaturesFilterISS3_New(): ...

class itkScalarImageToTextureFeaturesFilterISS3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFeatureMeansOutput: Any = ...
    GetFeatureStandardDeviationsOutput: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetFeatureMeans: Any = ...
    GetFeatureStandardDeviations: Any = ...
    SetRequestedFeatures: Any = ...
    GetRequestedFeatures: Any = ...
    SetOffsets: Any = ...
    GetOffsets: Any = ...
    SetNumberOfBinsPerAxis: Any = ...
    SetPixelValueMinMax: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetInsidePixelValue: Any = ...
    GetFastCalculations: Any = ...
    SetFastCalculations: Any = ...
    FastCalculationsOn: Any = ...
    FastCalculationsOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToTextureFeaturesFilterISS3___New_orig__: Any
itkScalarImageToTextureFeaturesFilterISS3_cast: Any

def itkScalarImageToTextureFeaturesFilterIUC2_New(): ...

class itkScalarImageToTextureFeaturesFilterIUC2(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFeatureMeansOutput: Any = ...
    GetFeatureStandardDeviationsOutput: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetFeatureMeans: Any = ...
    GetFeatureStandardDeviations: Any = ...
    SetRequestedFeatures: Any = ...
    GetRequestedFeatures: Any = ...
    SetOffsets: Any = ...
    GetOffsets: Any = ...
    SetNumberOfBinsPerAxis: Any = ...
    SetPixelValueMinMax: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetInsidePixelValue: Any = ...
    GetFastCalculations: Any = ...
    SetFastCalculations: Any = ...
    FastCalculationsOn: Any = ...
    FastCalculationsOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToTextureFeaturesFilterIUC2___New_orig__: Any
itkScalarImageToTextureFeaturesFilterIUC2_cast: Any

def itkScalarImageToTextureFeaturesFilterIUC3_New(): ...

class itkScalarImageToTextureFeaturesFilterIUC3(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFeatureMeansOutput: Any = ...
    GetFeatureStandardDeviationsOutput: Any = ...
    SetInput: Any = ...
    GetInput: Any = ...
    GetFeatureMeans: Any = ...
    GetFeatureStandardDeviations: Any = ...
    SetRequestedFeatures: Any = ...
    GetRequestedFeatures: Any = ...
    SetOffsets: Any = ...
    GetOffsets: Any = ...
    SetNumberOfBinsPerAxis: Any = ...
    SetPixelValueMinMax: Any = ...
    SetMaskImage: Any = ...
    GetMaskImage: Any = ...
    SetInsidePixelValue: Any = ...
    GetFastCalculations: Any = ...
    SetFastCalculations: Any = ...
    FastCalculationsOn: Any = ...
    FastCalculationsOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageToTextureFeaturesFilterIUC3___New_orig__: Any
itkScalarImageToTextureFeaturesFilterIUC3_cast: Any

def scalar_image_to_texture_features_filter(*args: Any, **kwargs: Any): ...
def scalar_image_to_texture_features_filter_init_docstring() -> None: ...
