import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkShiftScaleImageFilterIF2IF2_New(): ...

class itkShiftScaleImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    SetScale: Any = ...
    GetScale: Any = ...
    GetUnderflowCount: Any = ...
    GetOverflowCount: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    InputPlusRealTypeCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShiftScaleImageFilterIF2IF2___New_orig__: Any
itkShiftScaleImageFilterIF2IF2_cast: Any

def itkShiftScaleImageFilterIF3IF3_New(): ...

class itkShiftScaleImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    SetScale: Any = ...
    GetScale: Any = ...
    GetUnderflowCount: Any = ...
    GetOverflowCount: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    InputPlusRealTypeCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShiftScaleImageFilterIF3IF3___New_orig__: Any
itkShiftScaleImageFilterIF3IF3_cast: Any

def itkShiftScaleImageFilterISS2ISS2_New(): ...

class itkShiftScaleImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    SetScale: Any = ...
    GetScale: Any = ...
    GetUnderflowCount: Any = ...
    GetOverflowCount: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    InputPlusRealTypeCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShiftScaleImageFilterISS2ISS2___New_orig__: Any
itkShiftScaleImageFilterISS2ISS2_cast: Any

def itkShiftScaleImageFilterISS3ISS3_New(): ...

class itkShiftScaleImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    SetScale: Any = ...
    GetScale: Any = ...
    GetUnderflowCount: Any = ...
    GetOverflowCount: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    InputPlusRealTypeCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShiftScaleImageFilterISS3ISS3___New_orig__: Any
itkShiftScaleImageFilterISS3ISS3_cast: Any

def itkShiftScaleImageFilterIUC2IUC2_New(): ...

class itkShiftScaleImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    SetScale: Any = ...
    GetScale: Any = ...
    GetUnderflowCount: Any = ...
    GetOverflowCount: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    InputPlusRealTypeCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShiftScaleImageFilterIUC2IUC2___New_orig__: Any
itkShiftScaleImageFilterIUC2IUC2_cast: Any

def itkShiftScaleImageFilterIUC3IUC3_New(): ...

class itkShiftScaleImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetShift: Any = ...
    GetShift: Any = ...
    SetScale: Any = ...
    GetScale: Any = ...
    GetUnderflowCount: Any = ...
    GetOverflowCount: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    InputPlusRealTypeCheck: Any = ...
    RealTypeMultiplyOperatorCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShiftScaleImageFilterIUC3IUC3___New_orig__: Any
itkShiftScaleImageFilterIUC3IUC3_cast: Any

def shift_scale_image_filter(*args: Any, **kwargs: Any): ...
def shift_scale_image_filter_init_docstring() -> None: ...
