import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkShapeOpeningLabelMapFilterLM2_New(): ...

class itkShapeOpeningLabelMapFilterLM2(itk.itkInPlaceLabelMapFilterPython.itkInPlaceLabelMapFilterLM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetLambda: Any = ...
    SetLambda: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShapeOpeningLabelMapFilterLM2___New_orig__: Any
itkShapeOpeningLabelMapFilterLM2_cast: Any

def itkShapeOpeningLabelMapFilterLM3_New(): ...

class itkShapeOpeningLabelMapFilterLM3(itk.itkInPlaceLabelMapFilterPython.itkInPlaceLabelMapFilterLM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetLambda: Any = ...
    SetLambda: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShapeOpeningLabelMapFilterLM3___New_orig__: Any
itkShapeOpeningLabelMapFilterLM3_cast: Any

def shape_opening_label_map_filter(*args: Any, **kwargs: Any): ...
def shape_opening_label_map_filter_init_docstring() -> None: ...
