import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkShapeLabelMapFilterLM2_New(): ...

class itkShapeLabelMapFilterLM2(itk.itkInPlaceLabelMapFilterPython.itkInPlaceLabelMapFilterLM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetComputeFeretDiameter: Any = ...
    GetComputeFeretDiameter: Any = ...
    ComputeFeretDiameterOn: Any = ...
    ComputeFeretDiameterOff: Any = ...
    SetComputePerimeter: Any = ...
    GetComputePerimeter: Any = ...
    ComputePerimeterOn: Any = ...
    ComputePerimeterOff: Any = ...
    SetComputeOrientedBoundingBox: Any = ...
    GetComputeOrientedBoundingBox: Any = ...
    ComputeOrientedBoundingBoxOn: Any = ...
    ComputeOrientedBoundingBoxOff: Any = ...
    SetLabelImage: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShapeLabelMapFilterLM2___New_orig__: Any
itkShapeLabelMapFilterLM2_cast: Any

def itkShapeLabelMapFilterLM3_New(): ...

class itkShapeLabelMapFilterLM3(itk.itkInPlaceLabelMapFilterPython.itkInPlaceLabelMapFilterLM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetComputeFeretDiameter: Any = ...
    GetComputeFeretDiameter: Any = ...
    ComputeFeretDiameterOn: Any = ...
    ComputeFeretDiameterOff: Any = ...
    SetComputePerimeter: Any = ...
    GetComputePerimeter: Any = ...
    ComputePerimeterOn: Any = ...
    ComputePerimeterOff: Any = ...
    SetComputeOrientedBoundingBox: Any = ...
    GetComputeOrientedBoundingBox: Any = ...
    ComputeOrientedBoundingBoxOn: Any = ...
    ComputeOrientedBoundingBoxOff: Any = ...
    SetLabelImage: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShapeLabelMapFilterLM3___New_orig__: Any
itkShapeLabelMapFilterLM3_cast: Any

def shape_label_map_filter(*args: Any, **kwargs: Any): ...
def shape_label_map_filter_init_docstring() -> None: ...
