from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class vectoritkSpatialObjectPoint2:
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectoritkSpatialObjectPoint3:
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class itkSpatialObjectPoint2:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    GetNameOfClass: Any = ...
    SetId: Any = ...
    GetId: Any = ...
    SetPositionInObjectSpace: Any = ...
    GetPositionInObjectSpace: Any = ...
    SetSpatialObject: Any = ...
    GetSpatialObject: Any = ...
    SetPositionInWorldSpace: Any = ...
    GetPositionInWorldSpace: Any = ...
    GetColor: Any = ...
    SetColor: Any = ...
    SetRed: Any = ...
    GetRed: Any = ...
    SetGreen: Any = ...
    GetGreen: Any = ...
    SetBlue: Any = ...
    GetBlue: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetTagScalarValue: Any = ...
    GetTagScalarValue: Any = ...
    GetTagScalarDictionary: Any = ...
    SetTagScalarDictionary: Any = ...
    Print: Any = ...

class itkSpatialObjectPoint3:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    GetNameOfClass: Any = ...
    SetId: Any = ...
    GetId: Any = ...
    SetPositionInObjectSpace: Any = ...
    GetPositionInObjectSpace: Any = ...
    SetSpatialObject: Any = ...
    GetSpatialObject: Any = ...
    SetPositionInWorldSpace: Any = ...
    GetPositionInWorldSpace: Any = ...
    GetColor: Any = ...
    SetColor: Any = ...
    SetRed: Any = ...
    GetRed: Any = ...
    SetGreen: Any = ...
    GetGreen: Any = ...
    SetBlue: Any = ...
    GetBlue: Any = ...
    SetAlpha: Any = ...
    GetAlpha: Any = ...
    SetTagScalarValue: Any = ...
    GetTagScalarValue: Any = ...
    GetTagScalarDictionary: Any = ...
    SetTagScalarDictionary: Any = ...
    Print: Any = ...
