import itk.stdcomplexPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkSiemensVisionImageIO_New(): ...

class itkSiemensVisionImageIO(itk.itkIPLCommonImageIOPython.itkIPLCommonImageIO):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSiemensVisionImageIO___New_orig__: Any
itkSiemensVisionImageIO_cast: Any

def itkSiemensVisionImageIOFactory_New(): ...

class itkSiemensVisionImageIOFactory(itk.ITKCommonBasePython.itkObjectFactoryBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    RegisterOneFactory: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSiemensVisionImageIOFactory___New_orig__: Any
itkSiemensVisionImageIOFactory_RegisterOneFactory: Any
itkSiemensVisionImageIOFactory_cast: Any
