import itk.vnl_vector_refPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkSampleAD(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleAD_cast: Any

class itkSampleAF(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleAF_cast: Any

class itkSampleFAD1(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFAD1_cast: Any

class itkSampleFAD2(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFAD2_cast: Any

class itkSampleFAD3(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFAD3_cast: Any

class itkSampleFAF1(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFAF1_cast: Any

class itkSampleFAF2(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFAF2_cast: Any

class itkSampleFAF3(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFAF3_cast: Any

class itkSampleFASC1(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFASC1_cast: Any

class itkSampleFASC2(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFASC2_cast: Any

class itkSampleFASC3(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFASC3_cast: Any

class itkSampleFASL1(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFASL1_cast: Any

class itkSampleFASL2(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFASL2_cast: Any

class itkSampleFASL3(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFASL3_cast: Any

class itkSampleFASS1(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFASS1_cast: Any

class itkSampleFASS2(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFASS2_cast: Any

class itkSampleFASS3(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFASS3_cast: Any

class itkSampleFAUC1(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFAUC1_cast: Any

class itkSampleFAUC2(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFAUC2_cast: Any

class itkSampleFAUC3(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFAUC3_cast: Any

class itkSampleFAUL1(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFAUL1_cast: Any

class itkSampleFAUL2(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFAUL2_cast: Any

class itkSampleFAUL3(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFAUL3_cast: Any

class itkSampleFAUS1(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFAUS1_cast: Any

class itkSampleFAUS2(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFAUS2_cast: Any

class itkSampleFAUS3(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleFAUS3_cast: Any

class itkSampleVF2(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleVF2_cast: Any

class itkSampleVF3(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Size: Any = ...
    GetMeasurementVector: Any = ...
    GetFrequency: Any = ...
    GetTotalFrequency: Any = ...
    SetMeasurementVectorSize: Any = ...
    GetMeasurementVectorSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSampleVF3_cast: Any
