from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkSize1:
    thisown: Any = ...
    GetSizeDimension: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __mul__: Any = ...
    __imul__: Any = ...
    GetSize: Any = ...
    SetSize: Any = ...
    SetElement: Any = ...
    GetElement: Any = ...
    Fill: Any = ...
    assign: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    size: Any = ...
    max_size: Any = ...
    empty: Any = ...
    at: Any = ...
    front: Any = ...
    back: Any = ...
    data: Any = ...
    Filled: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    __len__: Any = ...
    def __eq__(self, other: Any) -> Any: ...

itkSize1_GetSizeDimension: Any
itkSize1_Filled: Any
itkSize1___len__: Any

class itkSize2:
    thisown: Any = ...
    GetSizeDimension: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __mul__: Any = ...
    __imul__: Any = ...
    GetSize: Any = ...
    SetSize: Any = ...
    SetElement: Any = ...
    GetElement: Any = ...
    Fill: Any = ...
    assign: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    size: Any = ...
    max_size: Any = ...
    empty: Any = ...
    at: Any = ...
    front: Any = ...
    back: Any = ...
    data: Any = ...
    Filled: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    __len__: Any = ...
    def __eq__(self, other: Any) -> Any: ...

itkSize2_GetSizeDimension: Any
itkSize2_Filled: Any
itkSize2___len__: Any

class itkSize3:
    thisown: Any = ...
    GetSizeDimension: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __mul__: Any = ...
    __imul__: Any = ...
    GetSize: Any = ...
    SetSize: Any = ...
    SetElement: Any = ...
    GetElement: Any = ...
    Fill: Any = ...
    assign: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    size: Any = ...
    max_size: Any = ...
    empty: Any = ...
    at: Any = ...
    front: Any = ...
    back: Any = ...
    data: Any = ...
    Filled: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    __len__: Any = ...
    def __eq__(self, other: Any) -> Any: ...

itkSize3_GetSizeDimension: Any
itkSize3_Filled: Any
itkSize3___len__: Any

class itkSize4:
    thisown: Any = ...
    GetSizeDimension: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __mul__: Any = ...
    __imul__: Any = ...
    GetSize: Any = ...
    SetSize: Any = ...
    SetElement: Any = ...
    GetElement: Any = ...
    Fill: Any = ...
    assign: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    size: Any = ...
    max_size: Any = ...
    empty: Any = ...
    at: Any = ...
    front: Any = ...
    back: Any = ...
    data: Any = ...
    Filled: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    __len__: Any = ...
    def __eq__(self, other: Any) -> Any: ...

itkSize4_GetSizeDimension: Any
itkSize4_Filled: Any
itkSize4___len__: Any
