import itk.itkPointSetPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkSphereMeshSourceMF2_New(): ...

class itkSphereMeshSourceMF2(itk.itkMeshSourcePython.itkMeshSourceMF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetResolutionX: Any = ...
    SetResolutionY: Any = ...
    SetCenter: Any = ...
    SetScale: Any = ...
    SetSquareness1: Any = ...
    SetSquareness2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSphereMeshSourceMF2___New_orig__: Any
itkSphereMeshSourceMF2_cast: Any

def itkSphereMeshSourceMF3_New(): ...

class itkSphereMeshSourceMF3(itk.itkMeshSourcePython.itkMeshSourceMF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetResolutionX: Any = ...
    SetResolutionY: Any = ...
    SetCenter: Any = ...
    SetScale: Any = ...
    SetSquareness1: Any = ...
    SetSquareness2: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSphereMeshSourceMF3___New_orig__: Any
itkSphereMeshSourceMF3_cast: Any

def sphere_mesh_source(*args: Any, **kwargs: Any): ...
def sphere_mesh_source_init_docstring() -> None: ...
