import itk.itkInPlaceImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkSubtractImageFilterIF2IF2IF2_New(): ...

class itkSubtractImageFilterIF2IF2IF2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIF2IF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1Input2OutputAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSubtractImageFilterIF2IF2IF2___New_orig__: Any
itkSubtractImageFilterIF2IF2IF2_cast: Any

def itkSubtractImageFilterIF3IF3IF3_New(): ...

class itkSubtractImageFilterIF3IF3IF3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIF3IF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1Input2OutputAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSubtractImageFilterIF3IF3IF3___New_orig__: Any
itkSubtractImageFilterIF3IF3IF3_cast: Any

def itkSubtractImageFilterISS2ISS2ISS2_New(): ...

class itkSubtractImageFilterISS2ISS2ISS2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterISS2ISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1Input2OutputAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSubtractImageFilterISS2ISS2ISS2___New_orig__: Any
itkSubtractImageFilterISS2ISS2ISS2_cast: Any

def itkSubtractImageFilterISS3ISS3ISS3_New(): ...

class itkSubtractImageFilterISS3ISS3ISS3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterISS3ISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1Input2OutputAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSubtractImageFilterISS3ISS3ISS3___New_orig__: Any
itkSubtractImageFilterISS3ISS3ISS3_cast: Any

def itkSubtractImageFilterIUC2IUC2IUC2_New(): ...

class itkSubtractImageFilterIUC2IUC2IUC2(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC2IUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1Input2OutputAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSubtractImageFilterIUC2IUC2IUC2___New_orig__: Any
itkSubtractImageFilterIUC2IUC2IUC2_cast: Any

def itkSubtractImageFilterIUC3IUC3IUC3_New(): ...

class itkSubtractImageFilterIUC3IUC3IUC3(itk.itkBinaryGeneratorImageFilterPython.itkBinaryGeneratorImageFilterIUC3IUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Input1Input2OutputAdditiveOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSubtractImageFilterIUC3IUC3IUC3___New_orig__: Any
itkSubtractImageFilterIUC3IUC3IUC3_cast: Any

def subtract_image_filter(*args: Any, **kwargs: Any): ...
def subtract_image_filter_init_docstring() -> None: ...
