import itk.itkRGBPixelPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkSimpleDataObjectDecoratorAD_New(): ...

class itkSimpleDataObjectDecoratorAD(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorAD___New_orig__: Any
itkSimpleDataObjectDecoratorAD_cast: Any

def itkSimpleDataObjectDecoratorAF_New(): ...

class itkSimpleDataObjectDecoratorAF(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorAF___New_orig__: Any
itkSimpleDataObjectDecoratorAF_cast: Any

def itkSimpleDataObjectDecoratorAUL_New(): ...

class itkSimpleDataObjectDecoratorAUL(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorAUL___New_orig__: Any
itkSimpleDataObjectDecoratorAUL_cast: Any

def itkSimpleDataObjectDecoratorAULL_New(): ...

class itkSimpleDataObjectDecoratorAULL(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorAULL___New_orig__: Any
itkSimpleDataObjectDecoratorAULL_cast: Any

def itkSimpleDataObjectDecoratorB_New(): ...

class itkSimpleDataObjectDecoratorB(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorB___New_orig__: Any
itkSimpleDataObjectDecoratorB_cast: Any

def itkSimpleDataObjectDecoratorCF_New(): ...

class itkSimpleDataObjectDecoratorCF(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorCF___New_orig__: Any
itkSimpleDataObjectDecoratorCF_cast: Any

def itkSimpleDataObjectDecoratorCVF2_New(): ...

class itkSimpleDataObjectDecoratorCVF2(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorCVF2___New_orig__: Any
itkSimpleDataObjectDecoratorCVF2_cast: Any

def itkSimpleDataObjectDecoratorCVF3_New(): ...

class itkSimpleDataObjectDecoratorCVF3(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorCVF3___New_orig__: Any
itkSimpleDataObjectDecoratorCVF3_cast: Any

def itkSimpleDataObjectDecoratorCVF4_New(): ...

class itkSimpleDataObjectDecoratorCVF4(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorCVF4___New_orig__: Any
itkSimpleDataObjectDecoratorCVF4_cast: Any

def itkSimpleDataObjectDecoratorD_New(): ...

class itkSimpleDataObjectDecoratorD(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorD___New_orig__: Any
itkSimpleDataObjectDecoratorD_cast: Any

def itkSimpleDataObjectDecoratorF_New(): ...

class itkSimpleDataObjectDecoratorF(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorF___New_orig__: Any
itkSimpleDataObjectDecoratorF_cast: Any

def itkSimpleDataObjectDecoratorRGBAUC_New(): ...

class itkSimpleDataObjectDecoratorRGBAUC(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorRGBAUC___New_orig__: Any
itkSimpleDataObjectDecoratorRGBAUC_cast: Any

def itkSimpleDataObjectDecoratorRGBUC_New(): ...

class itkSimpleDataObjectDecoratorRGBUC(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorRGBUC___New_orig__: Any
itkSimpleDataObjectDecoratorRGBUC_cast: Any

def itkSimpleDataObjectDecoratorSC_New(): ...

class itkSimpleDataObjectDecoratorSC(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorSC___New_orig__: Any
itkSimpleDataObjectDecoratorSC_cast: Any

def itkSimpleDataObjectDecoratorSL_New(): ...

class itkSimpleDataObjectDecoratorSL(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorSL___New_orig__: Any
itkSimpleDataObjectDecoratorSL_cast: Any

def itkSimpleDataObjectDecoratorSLL_New(): ...

class itkSimpleDataObjectDecoratorSLL(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorSLL___New_orig__: Any
itkSimpleDataObjectDecoratorSLL_cast: Any

def itkSimpleDataObjectDecoratorSS_New(): ...

class itkSimpleDataObjectDecoratorSS(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorSS___New_orig__: Any
itkSimpleDataObjectDecoratorSS_cast: Any

def itkSimpleDataObjectDecoratorUC_New(): ...

class itkSimpleDataObjectDecoratorUC(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorUC___New_orig__: Any
itkSimpleDataObjectDecoratorUC_cast: Any

def itkSimpleDataObjectDecoratorUL_New(): ...

class itkSimpleDataObjectDecoratorUL(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorUL___New_orig__: Any
itkSimpleDataObjectDecoratorUL_cast: Any

def itkSimpleDataObjectDecoratorULL_New(): ...

class itkSimpleDataObjectDecoratorULL(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorULL___New_orig__: Any
itkSimpleDataObjectDecoratorULL_cast: Any

def itkSimpleDataObjectDecoratorUS_New(): ...

class itkSimpleDataObjectDecoratorUS(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorUS___New_orig__: Any
itkSimpleDataObjectDecoratorUS_cast: Any

def itkSimpleDataObjectDecoratorVF2_New(): ...

class itkSimpleDataObjectDecoratorVF2(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorVF2___New_orig__: Any
itkSimpleDataObjectDecoratorVF2_cast: Any

def itkSimpleDataObjectDecoratorVF3_New(): ...

class itkSimpleDataObjectDecoratorVF3(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorVF3___New_orig__: Any
itkSimpleDataObjectDecoratorVF3_cast: Any

def itkSimpleDataObjectDecoratorVF4_New(): ...

class itkSimpleDataObjectDecoratorVF4(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorVF4___New_orig__: Any
itkSimpleDataObjectDecoratorVF4_cast: Any

def itkSimpleDataObjectDecoratorstring_New(): ...

class itkSimpleDataObjectDecoratorstring(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSimpleDataObjectDecoratorstring___New_orig__: Any
itkSimpleDataObjectDecoratorstring_cast: Any
