import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkScalarConnectedComponentImageFilterISS2ISS2_Superclass_New(): ...

class itkScalarConnectedComponentImageFilterISS2ISS2_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarConnectedComponentImageFilterISS2ISS2_Superclass___New_orig__: Any
itkScalarConnectedComponentImageFilterISS2ISS2_Superclass_cast: Any

def itkScalarConnectedComponentImageFilterISS2IUL2_Superclass_New(): ...

class itkScalarConnectedComponentImageFilterISS2IUL2_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterISS2IUL2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarConnectedComponentImageFilterISS2IUL2_Superclass___New_orig__: Any
itkScalarConnectedComponentImageFilterISS2IUL2_Superclass_cast: Any

def itkScalarConnectedComponentImageFilterISS3ISS3_Superclass_New(): ...

class itkScalarConnectedComponentImageFilterISS3ISS3_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarConnectedComponentImageFilterISS3ISS3_Superclass___New_orig__: Any
itkScalarConnectedComponentImageFilterISS3ISS3_Superclass_cast: Any

def itkScalarConnectedComponentImageFilterISS3IUL3_Superclass_New(): ...

class itkScalarConnectedComponentImageFilterISS3IUL3_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterISS3IUL3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarConnectedComponentImageFilterISS3IUL3_Superclass___New_orig__: Any
itkScalarConnectedComponentImageFilterISS3IUL3_Superclass_cast: Any

def itkScalarConnectedComponentImageFilterIUC2ISS2_Superclass_New(): ...

class itkScalarConnectedComponentImageFilterIUC2ISS2_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterIUC2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarConnectedComponentImageFilterIUC2ISS2_Superclass___New_orig__: Any
itkScalarConnectedComponentImageFilterIUC2ISS2_Superclass_cast: Any

def itkScalarConnectedComponentImageFilterIUC2IUL2_Superclass_New(): ...

class itkScalarConnectedComponentImageFilterIUC2IUL2_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterIUC2IUL2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarConnectedComponentImageFilterIUC2IUL2_Superclass___New_orig__: Any
itkScalarConnectedComponentImageFilterIUC2IUL2_Superclass_cast: Any

def itkScalarConnectedComponentImageFilterIUC3ISS3_Superclass_New(): ...

class itkScalarConnectedComponentImageFilterIUC3ISS3_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterIUC3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarConnectedComponentImageFilterIUC3ISS3_Superclass___New_orig__: Any
itkScalarConnectedComponentImageFilterIUC3ISS3_Superclass_cast: Any

def itkScalarConnectedComponentImageFilterIUC3IUL3_Superclass_New(): ...

class itkScalarConnectedComponentImageFilterIUC3IUL3_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterIUC3IUL3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarConnectedComponentImageFilterIUC3IUL3_Superclass___New_orig__: Any
itkScalarConnectedComponentImageFilterIUC3IUL3_Superclass_cast: Any

def itkScalarConnectedComponentImageFilterISS2ISS2_New(): ...

class itkScalarConnectedComponentImageFilterISS2ISS2(itkScalarConnectedComponentImageFilterISS2ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    MaskEqualityComparableCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarConnectedComponentImageFilterISS2ISS2___New_orig__: Any
itkScalarConnectedComponentImageFilterISS2ISS2_cast: Any

def itkScalarConnectedComponentImageFilterISS2IUL2_New(): ...

class itkScalarConnectedComponentImageFilterISS2IUL2(itkScalarConnectedComponentImageFilterISS2IUL2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    MaskEqualityComparableCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarConnectedComponentImageFilterISS2IUL2___New_orig__: Any
itkScalarConnectedComponentImageFilterISS2IUL2_cast: Any

def itkScalarConnectedComponentImageFilterISS3ISS3_New(): ...

class itkScalarConnectedComponentImageFilterISS3ISS3(itkScalarConnectedComponentImageFilterISS3ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    MaskEqualityComparableCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarConnectedComponentImageFilterISS3ISS3___New_orig__: Any
itkScalarConnectedComponentImageFilterISS3ISS3_cast: Any

def itkScalarConnectedComponentImageFilterISS3IUL3_New(): ...

class itkScalarConnectedComponentImageFilterISS3IUL3(itkScalarConnectedComponentImageFilterISS3IUL3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    MaskEqualityComparableCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarConnectedComponentImageFilterISS3IUL3___New_orig__: Any
itkScalarConnectedComponentImageFilterISS3IUL3_cast: Any

def itkScalarConnectedComponentImageFilterIUC2ISS2_New(): ...

class itkScalarConnectedComponentImageFilterIUC2ISS2(itkScalarConnectedComponentImageFilterIUC2ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    MaskEqualityComparableCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarConnectedComponentImageFilterIUC2ISS2___New_orig__: Any
itkScalarConnectedComponentImageFilterIUC2ISS2_cast: Any

def itkScalarConnectedComponentImageFilterIUC2IUL2_New(): ...

class itkScalarConnectedComponentImageFilterIUC2IUL2(itkScalarConnectedComponentImageFilterIUC2IUL2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    MaskEqualityComparableCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarConnectedComponentImageFilterIUC2IUL2___New_orig__: Any
itkScalarConnectedComponentImageFilterIUC2IUL2_cast: Any

def itkScalarConnectedComponentImageFilterIUC3ISS3_New(): ...

class itkScalarConnectedComponentImageFilterIUC3ISS3(itkScalarConnectedComponentImageFilterIUC3ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    MaskEqualityComparableCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarConnectedComponentImageFilterIUC3ISS3___New_orig__: Any
itkScalarConnectedComponentImageFilterIUC3ISS3_cast: Any

def itkScalarConnectedComponentImageFilterIUC3IUL3_New(): ...

class itkScalarConnectedComponentImageFilterIUC3IUL3(itkScalarConnectedComponentImageFilterIUC3IUL3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    MaskEqualityComparableCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarConnectedComponentImageFilterIUC3IUL3___New_orig__: Any
itkScalarConnectedComponentImageFilterIUC3IUL3_cast: Any

def connected_component_functor_image_filter(*args: Any, **kwargs: Any): ...
def connected_component_functor_image_filter_init_docstring() -> None: ...
def scalar_connected_component_image_filter(*args: Any, **kwargs: Any): ...
def scalar_connected_component_image_filter_init_docstring() -> None: ...
