import itk.itkOptimizerParametersPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkShapeSignedDistanceFunctionD2(itk.itkSpatialFunctionPython.itkSpatialFunctionD2PD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetParameters: Any = ...
    GetParameters: Any = ...
    GetNumberOfShapeParameters: Any = ...
    GetNumberOfPoseParameters: Any = ...
    GetNumberOfParameters: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkShapeSignedDistanceFunctionD2_cast: Any

class itkShapeSignedDistanceFunctionD3(itk.itkSpatialFunctionPython.itkSpatialFunctionD3PD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    SetParameters: Any = ...
    GetParameters: Any = ...
    GetNumberOfShapeParameters: Any = ...
    GetNumberOfPoseParameters: Any = ...
    GetNumberOfParameters: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkShapeSignedDistanceFunctionD3_cast: Any
