import itk.itkImageRegionPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkSegmentationLevelSetFunctionIF2IF2(itk.itkLevelSetFunctionPython.itkLevelSetFunctionIF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetFeatureImage: Any = ...
    SetFeatureImage: Any = ...
    GetSpeedImage: Any = ...
    SetSpeedImage: Any = ...
    GetAdvectionImage: Any = ...
    SetAdvectionImage: Any = ...
    CalculateSpeedImage: Any = ...
    CalculateAdvectionImage: Any = ...
    AllocateSpeedImage: Any = ...
    AllocateAdvectionImage: Any = ...
    ReverseExpansionDirection: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSegmentationLevelSetFunctionIF2IF2_cast: Any

class itkSegmentationLevelSetFunctionIF3IF3(itk.itkLevelSetFunctionPython.itkLevelSetFunctionIF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    GetFeatureImage: Any = ...
    SetFeatureImage: Any = ...
    GetSpeedImage: Any = ...
    SetSpeedImage: Any = ...
    GetAdvectionImage: Any = ...
    SetAdvectionImage: Any = ...
    CalculateSpeedImage: Any = ...
    CalculateAdvectionImage: Any = ...
    AllocateSpeedImage: Any = ...
    AllocateAdvectionImage: Any = ...
    ReverseExpansionDirection: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...

itkSegmentationLevelSetFunctionIF3IF3_cast: Any
