import itk.itkLabelMapFilterPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkStatisticsLabelMapFilterLM2IF2_New(): ...

class itkStatisticsLabelMapFilterLM2IF2(itk.itkShapeLabelMapFilterPython.itkShapeLabelMapFilterLM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetComputeHistogram: Any = ...
    GetComputeHistogram: Any = ...
    ComputeHistogramOn: Any = ...
    ComputeHistogramOff: Any = ...
    SetNumberOfBins: Any = ...
    GetNumberOfBins: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStatisticsLabelMapFilterLM2IF2___New_orig__: Any
itkStatisticsLabelMapFilterLM2IF2_cast: Any

def itkStatisticsLabelMapFilterLM2ISS2_New(): ...

class itkStatisticsLabelMapFilterLM2ISS2(itk.itkShapeLabelMapFilterPython.itkShapeLabelMapFilterLM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetComputeHistogram: Any = ...
    GetComputeHistogram: Any = ...
    ComputeHistogramOn: Any = ...
    ComputeHistogramOff: Any = ...
    SetNumberOfBins: Any = ...
    GetNumberOfBins: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStatisticsLabelMapFilterLM2ISS2___New_orig__: Any
itkStatisticsLabelMapFilterLM2ISS2_cast: Any

def itkStatisticsLabelMapFilterLM2IUC2_New(): ...

class itkStatisticsLabelMapFilterLM2IUC2(itk.itkShapeLabelMapFilterPython.itkShapeLabelMapFilterLM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetComputeHistogram: Any = ...
    GetComputeHistogram: Any = ...
    ComputeHistogramOn: Any = ...
    ComputeHistogramOff: Any = ...
    SetNumberOfBins: Any = ...
    GetNumberOfBins: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStatisticsLabelMapFilterLM2IUC2___New_orig__: Any
itkStatisticsLabelMapFilterLM2IUC2_cast: Any

def itkStatisticsLabelMapFilterLM3IF3_New(): ...

class itkStatisticsLabelMapFilterLM3IF3(itk.itkShapeLabelMapFilterPython.itkShapeLabelMapFilterLM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetComputeHistogram: Any = ...
    GetComputeHistogram: Any = ...
    ComputeHistogramOn: Any = ...
    ComputeHistogramOff: Any = ...
    SetNumberOfBins: Any = ...
    GetNumberOfBins: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStatisticsLabelMapFilterLM3IF3___New_orig__: Any
itkStatisticsLabelMapFilterLM3IF3_cast: Any

def itkStatisticsLabelMapFilterLM3ISS3_New(): ...

class itkStatisticsLabelMapFilterLM3ISS3(itk.itkShapeLabelMapFilterPython.itkShapeLabelMapFilterLM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetComputeHistogram: Any = ...
    GetComputeHistogram: Any = ...
    ComputeHistogramOn: Any = ...
    ComputeHistogramOff: Any = ...
    SetNumberOfBins: Any = ...
    GetNumberOfBins: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStatisticsLabelMapFilterLM3ISS3___New_orig__: Any
itkStatisticsLabelMapFilterLM3ISS3_cast: Any

def itkStatisticsLabelMapFilterLM3IUC3_New(): ...

class itkStatisticsLabelMapFilterLM3IUC3(itk.itkShapeLabelMapFilterPython.itkShapeLabelMapFilterLM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFeatureImage: Any = ...
    GetFeatureImage: Any = ...
    SetInput1: Any = ...
    SetInput2: Any = ...
    SetComputeHistogram: Any = ...
    GetComputeHistogram: Any = ...
    ComputeHistogramOn: Any = ...
    ComputeHistogramOff: Any = ...
    SetNumberOfBins: Any = ...
    GetNumberOfBins: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStatisticsLabelMapFilterLM3IUC3___New_orig__: Any
itkStatisticsLabelMapFilterLM3IUC3_cast: Any

def statistics_label_map_filter(*args: Any, **kwargs: Any): ...
def statistics_label_map_filter_init_docstring() -> None: ...
