import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkShapeRelabelLabelMapFilterLM2_New(): ...

class itkShapeRelabelLabelMapFilterLM2(itk.itkInPlaceLabelMapFilterPython.itkInPlaceLabelMapFilterLM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReverseOrdering: Any = ...
    GetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShapeRelabelLabelMapFilterLM2___New_orig__: Any
itkShapeRelabelLabelMapFilterLM2_cast: Any

def itkShapeRelabelLabelMapFilterLM3_New(): ...

class itkShapeRelabelLabelMapFilterLM3(itk.itkInPlaceLabelMapFilterPython.itkInPlaceLabelMapFilterLM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReverseOrdering: Any = ...
    GetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShapeRelabelLabelMapFilterLM3___New_orig__: Any
itkShapeRelabelLabelMapFilterLM3_cast: Any

def shape_relabel_label_map_filter(*args: Any, **kwargs: Any): ...
def shape_relabel_label_map_filter_init_docstring() -> None: ...
