import itk.itkArrayPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkScalarImageKmeansImageFilterIF2ISS2_New(): ...

class itkScalarImageKmeansImageFilterIF2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    AddClassWithInitialMean: Any = ...
    GetFinalMeans: Any = ...
    SetUseNonContiguousLabels: Any = ...
    GetUseNonContiguousLabels: Any = ...
    UseNonContiguousLabelsOn: Any = ...
    UseNonContiguousLabelsOff: Any = ...
    SetImageRegion: Any = ...
    GetImageRegion: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageKmeansImageFilterIF2ISS2___New_orig__: Any
itkScalarImageKmeansImageFilterIF2ISS2_cast: Any

def itkScalarImageKmeansImageFilterIF2IUC2_New(): ...

class itkScalarImageKmeansImageFilterIF2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    AddClassWithInitialMean: Any = ...
    GetFinalMeans: Any = ...
    SetUseNonContiguousLabels: Any = ...
    GetUseNonContiguousLabels: Any = ...
    UseNonContiguousLabelsOn: Any = ...
    UseNonContiguousLabelsOff: Any = ...
    SetImageRegion: Any = ...
    GetImageRegion: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageKmeansImageFilterIF2IUC2___New_orig__: Any
itkScalarImageKmeansImageFilterIF2IUC2_cast: Any

def itkScalarImageKmeansImageFilterIF3ISS3_New(): ...

class itkScalarImageKmeansImageFilterIF3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    AddClassWithInitialMean: Any = ...
    GetFinalMeans: Any = ...
    SetUseNonContiguousLabels: Any = ...
    GetUseNonContiguousLabels: Any = ...
    UseNonContiguousLabelsOn: Any = ...
    UseNonContiguousLabelsOff: Any = ...
    SetImageRegion: Any = ...
    GetImageRegion: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageKmeansImageFilterIF3ISS3___New_orig__: Any
itkScalarImageKmeansImageFilterIF3ISS3_cast: Any

def itkScalarImageKmeansImageFilterIF3IUC3_New(): ...

class itkScalarImageKmeansImageFilterIF3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    AddClassWithInitialMean: Any = ...
    GetFinalMeans: Any = ...
    SetUseNonContiguousLabels: Any = ...
    GetUseNonContiguousLabels: Any = ...
    UseNonContiguousLabelsOn: Any = ...
    UseNonContiguousLabelsOff: Any = ...
    SetImageRegion: Any = ...
    GetImageRegion: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageKmeansImageFilterIF3IUC3___New_orig__: Any
itkScalarImageKmeansImageFilterIF3IUC3_cast: Any

def itkScalarImageKmeansImageFilterISS2ISS2_New(): ...

class itkScalarImageKmeansImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    AddClassWithInitialMean: Any = ...
    GetFinalMeans: Any = ...
    SetUseNonContiguousLabels: Any = ...
    GetUseNonContiguousLabels: Any = ...
    UseNonContiguousLabelsOn: Any = ...
    UseNonContiguousLabelsOff: Any = ...
    SetImageRegion: Any = ...
    GetImageRegion: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageKmeansImageFilterISS2ISS2___New_orig__: Any
itkScalarImageKmeansImageFilterISS2ISS2_cast: Any

def itkScalarImageKmeansImageFilterISS2IUC2_New(): ...

class itkScalarImageKmeansImageFilterISS2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    AddClassWithInitialMean: Any = ...
    GetFinalMeans: Any = ...
    SetUseNonContiguousLabels: Any = ...
    GetUseNonContiguousLabels: Any = ...
    UseNonContiguousLabelsOn: Any = ...
    UseNonContiguousLabelsOff: Any = ...
    SetImageRegion: Any = ...
    GetImageRegion: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageKmeansImageFilterISS2IUC2___New_orig__: Any
itkScalarImageKmeansImageFilterISS2IUC2_cast: Any

def itkScalarImageKmeansImageFilterISS3ISS3_New(): ...

class itkScalarImageKmeansImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    AddClassWithInitialMean: Any = ...
    GetFinalMeans: Any = ...
    SetUseNonContiguousLabels: Any = ...
    GetUseNonContiguousLabels: Any = ...
    UseNonContiguousLabelsOn: Any = ...
    UseNonContiguousLabelsOff: Any = ...
    SetImageRegion: Any = ...
    GetImageRegion: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageKmeansImageFilterISS3ISS3___New_orig__: Any
itkScalarImageKmeansImageFilterISS3ISS3_cast: Any

def itkScalarImageKmeansImageFilterISS3IUC3_New(): ...

class itkScalarImageKmeansImageFilterISS3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    AddClassWithInitialMean: Any = ...
    GetFinalMeans: Any = ...
    SetUseNonContiguousLabels: Any = ...
    GetUseNonContiguousLabels: Any = ...
    UseNonContiguousLabelsOn: Any = ...
    UseNonContiguousLabelsOff: Any = ...
    SetImageRegion: Any = ...
    GetImageRegion: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageKmeansImageFilterISS3IUC3___New_orig__: Any
itkScalarImageKmeansImageFilterISS3IUC3_cast: Any

def itkScalarImageKmeansImageFilterIUC2ISS2_New(): ...

class itkScalarImageKmeansImageFilterIUC2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    AddClassWithInitialMean: Any = ...
    GetFinalMeans: Any = ...
    SetUseNonContiguousLabels: Any = ...
    GetUseNonContiguousLabels: Any = ...
    UseNonContiguousLabelsOn: Any = ...
    UseNonContiguousLabelsOff: Any = ...
    SetImageRegion: Any = ...
    GetImageRegion: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageKmeansImageFilterIUC2ISS2___New_orig__: Any
itkScalarImageKmeansImageFilterIUC2ISS2_cast: Any

def itkScalarImageKmeansImageFilterIUC2IUC2_New(): ...

class itkScalarImageKmeansImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    AddClassWithInitialMean: Any = ...
    GetFinalMeans: Any = ...
    SetUseNonContiguousLabels: Any = ...
    GetUseNonContiguousLabels: Any = ...
    UseNonContiguousLabelsOn: Any = ...
    UseNonContiguousLabelsOff: Any = ...
    SetImageRegion: Any = ...
    GetImageRegion: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageKmeansImageFilterIUC2IUC2___New_orig__: Any
itkScalarImageKmeansImageFilterIUC2IUC2_cast: Any

def itkScalarImageKmeansImageFilterIUC3ISS3_New(): ...

class itkScalarImageKmeansImageFilterIUC3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    AddClassWithInitialMean: Any = ...
    GetFinalMeans: Any = ...
    SetUseNonContiguousLabels: Any = ...
    GetUseNonContiguousLabels: Any = ...
    UseNonContiguousLabelsOn: Any = ...
    UseNonContiguousLabelsOff: Any = ...
    SetImageRegion: Any = ...
    GetImageRegion: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageKmeansImageFilterIUC3ISS3___New_orig__: Any
itkScalarImageKmeansImageFilterIUC3ISS3_cast: Any

def itkScalarImageKmeansImageFilterIUC3IUC3_New(): ...

class itkScalarImageKmeansImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    AddClassWithInitialMean: Any = ...
    GetFinalMeans: Any = ...
    SetUseNonContiguousLabels: Any = ...
    GetUseNonContiguousLabels: Any = ...
    UseNonContiguousLabelsOn: Any = ...
    UseNonContiguousLabelsOff: Any = ...
    SetImageRegion: Any = ...
    GetImageRegion: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScalarImageKmeansImageFilterIUC3IUC3___New_orig__: Any
itkScalarImageKmeansImageFilterIUC3IUC3_cast: Any

def scalar_image_kmeans_image_filter(*args: Any, **kwargs: Any): ...
def scalar_image_kmeans_image_filter_init_docstring() -> None: ...
