import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkShapeKeepNObjectsLabelMapFilterLM2_New(): ...

class itkShapeKeepNObjectsLabelMapFilterLM2(itk.itkInPlaceLabelMapFilterPython.itkInPlaceLabelMapFilterLM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReverseOrdering: Any = ...
    GetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    SetNumberOfObjects: Any = ...
    GetNumberOfObjects: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShapeKeepNObjectsLabelMapFilterLM2___New_orig__: Any
itkShapeKeepNObjectsLabelMapFilterLM2_cast: Any

def itkShapeKeepNObjectsLabelMapFilterLM3_New(): ...

class itkShapeKeepNObjectsLabelMapFilterLM3(itk.itkInPlaceLabelMapFilterPython.itkInPlaceLabelMapFilterLM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetReverseOrdering: Any = ...
    GetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    SetNumberOfObjects: Any = ...
    GetNumberOfObjects: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShapeKeepNObjectsLabelMapFilterLM3___New_orig__: Any
itkShapeKeepNObjectsLabelMapFilterLM3_cast: Any

def shape_keep_n_objects_label_map_filter(*args: Any, **kwargs: Any): ...
def shape_keep_n_objects_label_map_filter_init_docstring() -> None: ...
