import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkShapeUniqueLabelMapFilterLM2_New(): ...

class itkShapeUniqueLabelMapFilterLM2(itk.itkInPlaceLabelMapFilterPython.itkInPlaceLabelMapFilterLM2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShapeUniqueLabelMapFilterLM2___New_orig__: Any
itkShapeUniqueLabelMapFilterLM2_cast: Any

def itkShapeUniqueLabelMapFilterLM3_New(): ...

class itkShapeUniqueLabelMapFilterLM3(itk.itkInPlaceLabelMapFilterPython.itkInPlaceLabelMapFilterLM3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetReverseOrdering: Any = ...
    SetReverseOrdering: Any = ...
    ReverseOrderingOn: Any = ...
    ReverseOrderingOff: Any = ...
    GetAttribute: Any = ...
    SetAttribute: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkShapeUniqueLabelMapFilterLM3___New_orig__: Any
itkShapeUniqueLabelMapFilterLM3_cast: Any

def shape_unique_label_map_filter(*args: Any, **kwargs: Any): ...
def shape_unique_label_map_filter_init_docstring() -> None: ...
