from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkScanlineFilterCommonICVF22ISS2_New(): ...

class itkScanlineFilterCommonICVF22ISS2:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterICVF22ISS2) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonICVF22ISS2___New_orig__: Any
itkScanlineFilterCommonICVF22ISS2_cast: Any

def itkScanlineFilterCommonICVF22IUC2_New(): ...

class itkScanlineFilterCommonICVF22IUC2:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterICVF22IUC2) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonICVF22IUC2___New_orig__: Any
itkScanlineFilterCommonICVF22IUC2_cast: Any

def itkScanlineFilterCommonICVF23ISS3_New(): ...

class itkScanlineFilterCommonICVF23ISS3:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterICVF23ISS3) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonICVF23ISS3___New_orig__: Any
itkScanlineFilterCommonICVF23ISS3_cast: Any

def itkScanlineFilterCommonICVF23IUC3_New(): ...

class itkScanlineFilterCommonICVF23IUC3:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterICVF23IUC3) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonICVF23IUC3___New_orig__: Any
itkScanlineFilterCommonICVF23IUC3_cast: Any

def itkScanlineFilterCommonICVF32ISS2_New(): ...

class itkScanlineFilterCommonICVF32ISS2:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterICVF32ISS2) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonICVF32ISS2___New_orig__: Any
itkScanlineFilterCommonICVF32ISS2_cast: Any

def itkScanlineFilterCommonICVF32IUC2_New(): ...

class itkScanlineFilterCommonICVF32IUC2:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterICVF32IUC2) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonICVF32IUC2___New_orig__: Any
itkScanlineFilterCommonICVF32IUC2_cast: Any

def itkScanlineFilterCommonICVF33ISS3_New(): ...

class itkScanlineFilterCommonICVF33ISS3:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterICVF33ISS3) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonICVF33ISS3___New_orig__: Any
itkScanlineFilterCommonICVF33ISS3_cast: Any

def itkScanlineFilterCommonICVF33IUC3_New(): ...

class itkScanlineFilterCommonICVF33IUC3:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterICVF33IUC3) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonICVF33IUC3___New_orig__: Any
itkScanlineFilterCommonICVF33IUC3_cast: Any

def itkScanlineFilterCommonICVF42ISS2_New(): ...

class itkScanlineFilterCommonICVF42ISS2:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterICVF42ISS2) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonICVF42ISS2___New_orig__: Any
itkScanlineFilterCommonICVF42ISS2_cast: Any

def itkScanlineFilterCommonICVF42IUC2_New(): ...

class itkScanlineFilterCommonICVF42IUC2:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterICVF42IUC2) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonICVF42IUC2___New_orig__: Any
itkScanlineFilterCommonICVF42IUC2_cast: Any

def itkScanlineFilterCommonICVF43ISS3_New(): ...

class itkScanlineFilterCommonICVF43ISS3:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterICVF43ISS3) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonICVF43ISS3___New_orig__: Any
itkScanlineFilterCommonICVF43ISS3_cast: Any

def itkScanlineFilterCommonICVF43IUC3_New(): ...

class itkScanlineFilterCommonICVF43IUC3:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterICVF43IUC3) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonICVF43IUC3___New_orig__: Any
itkScanlineFilterCommonICVF43IUC3_cast: Any

def itkScanlineFilterCommonIF2IF2_New(): ...

class itkScanlineFilterCommonIF2IF2:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterIF2IF2) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonIF2IF2___New_orig__: Any
itkScanlineFilterCommonIF2IF2_cast: Any

def itkScanlineFilterCommonIF3IF3_New(): ...

class itkScanlineFilterCommonIF3IF3:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterIF3IF3) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonIF3IF3___New_orig__: Any
itkScanlineFilterCommonIF3IF3_cast: Any

def itkScanlineFilterCommonISS2ISS2_New(): ...

class itkScanlineFilterCommonISS2ISS2:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterISS2ISS2) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonISS2ISS2___New_orig__: Any
itkScanlineFilterCommonISS2ISS2_cast: Any

def itkScanlineFilterCommonISS2IUC2_New(): ...

class itkScanlineFilterCommonISS2IUC2:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterISS2IUC2) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonISS2IUC2___New_orig__: Any
itkScanlineFilterCommonISS2IUC2_cast: Any

def itkScanlineFilterCommonISS2IUL2_New(): ...

class itkScanlineFilterCommonISS2IUL2:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterISS2IUL2) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonISS2IUL2___New_orig__: Any
itkScanlineFilterCommonISS2IUL2_cast: Any

def itkScanlineFilterCommonISS3ISS3_New(): ...

class itkScanlineFilterCommonISS3ISS3:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterISS3ISS3) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonISS3ISS3___New_orig__: Any
itkScanlineFilterCommonISS3ISS3_cast: Any

def itkScanlineFilterCommonISS3IUC3_New(): ...

class itkScanlineFilterCommonISS3IUC3:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterISS3IUC3) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonISS3IUC3___New_orig__: Any
itkScanlineFilterCommonISS3IUC3_cast: Any

def itkScanlineFilterCommonISS3IUL3_New(): ...

class itkScanlineFilterCommonISS3IUL3:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterISS3IUL3) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonISS3IUL3___New_orig__: Any
itkScanlineFilterCommonISS3IUL3_cast: Any

def itkScanlineFilterCommonIUC2ISS2_New(): ...

class itkScanlineFilterCommonIUC2ISS2:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterIUC2ISS2) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonIUC2ISS2___New_orig__: Any
itkScanlineFilterCommonIUC2ISS2_cast: Any

def itkScanlineFilterCommonIUC2IUC2_New(): ...

class itkScanlineFilterCommonIUC2IUC2:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterIUC2IUC2) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonIUC2IUC2___New_orig__: Any
itkScanlineFilterCommonIUC2IUC2_cast: Any

def itkScanlineFilterCommonIUC2IUL2_New(): ...

class itkScanlineFilterCommonIUC2IUL2:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterIUC2IUL2) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonIUC2IUL2___New_orig__: Any
itkScanlineFilterCommonIUC2IUL2_cast: Any

def itkScanlineFilterCommonIUC3ISS3_New(): ...

class itkScanlineFilterCommonIUC3ISS3:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterIUC3ISS3) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonIUC3ISS3___New_orig__: Any
itkScanlineFilterCommonIUC3ISS3_cast: Any

def itkScanlineFilterCommonIUC3IUC3_New(): ...

class itkScanlineFilterCommonIUC3IUC3:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterIUC3IUC3) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonIUC3IUC3___New_orig__: Any
itkScanlineFilterCommonIUC3IUC3_cast: Any

def itkScanlineFilterCommonIUC3IUL3_New(): ...

class itkScanlineFilterCommonIUC3IUL3:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterIUC3IUL3) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonIUC3IUL3___New_orig__: Any
itkScanlineFilterCommonIUC3IUL3_cast: Any

def itkScanlineFilterCommonIVF22ISS2_New(): ...

class itkScanlineFilterCommonIVF22ISS2:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterIVF22ISS2) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonIVF22ISS2___New_orig__: Any
itkScanlineFilterCommonIVF22ISS2_cast: Any

def itkScanlineFilterCommonIVF22IUC2_New(): ...

class itkScanlineFilterCommonIVF22IUC2:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterIVF22IUC2) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonIVF22IUC2___New_orig__: Any
itkScanlineFilterCommonIVF22IUC2_cast: Any

def itkScanlineFilterCommonIVF23ISS3_New(): ...

class itkScanlineFilterCommonIVF23ISS3:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterIVF23ISS3) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonIVF23ISS3___New_orig__: Any
itkScanlineFilterCommonIVF23ISS3_cast: Any

def itkScanlineFilterCommonIVF23IUC3_New(): ...

class itkScanlineFilterCommonIVF23IUC3:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterIVF23IUC3) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonIVF23IUC3___New_orig__: Any
itkScanlineFilterCommonIVF23IUC3_cast: Any

def itkScanlineFilterCommonIVF32ISS2_New(): ...

class itkScanlineFilterCommonIVF32ISS2:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterIVF32ISS2) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonIVF32ISS2___New_orig__: Any
itkScanlineFilterCommonIVF32ISS2_cast: Any

def itkScanlineFilterCommonIVF32IUC2_New(): ...

class itkScanlineFilterCommonIVF32IUC2:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterIVF32IUC2) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonIVF32IUC2___New_orig__: Any
itkScanlineFilterCommonIVF32IUC2_cast: Any

def itkScanlineFilterCommonIVF33ISS3_New(): ...

class itkScanlineFilterCommonIVF33ISS3:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterIVF33ISS3) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonIVF33ISS3___New_orig__: Any
itkScanlineFilterCommonIVF33ISS3_cast: Any

def itkScanlineFilterCommonIVF33IUC3_New(): ...

class itkScanlineFilterCommonIVF33IUC3:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterIVF33IUC3) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonIVF33IUC3___New_orig__: Any
itkScanlineFilterCommonIVF33IUC3_cast: Any

def itkScanlineFilterCommonIVF42ISS2_New(): ...

class itkScanlineFilterCommonIVF42ISS2:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterIVF42ISS2) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonIVF42ISS2___New_orig__: Any
itkScanlineFilterCommonIVF42ISS2_cast: Any

def itkScanlineFilterCommonIVF42IUC2_New(): ...

class itkScanlineFilterCommonIVF42IUC2:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterIVF42IUC2) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonIVF42IUC2___New_orig__: Any
itkScanlineFilterCommonIVF42IUC2_cast: Any

def itkScanlineFilterCommonIVF43ISS3_New(): ...

class itkScanlineFilterCommonIVF43ISS3:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterIVF43ISS3) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonIVF43ISS3___New_orig__: Any
itkScanlineFilterCommonIVF43ISS3_cast: Any

def itkScanlineFilterCommonIVF43IUC3_New(): ...

class itkScanlineFilterCommonIVF43IUC3:
    thisown: Any = ...
    __New_orig__: Any = ...
    SameDimension: Any = ...
    def __init__(self, enclosingFilter: itkImageToImageFilterIVF43IUC3) -> None: ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkScanlineFilterCommonIVF43IUC3___New_orig__: Any
itkScanlineFilterCommonIVF43IUC3_cast: Any
