import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkSymmetricForcesDemonsRegistrationFilterIF2IF2IVF22_New(): ...

class itkSymmetricForcesDemonsRegistrationFilterIF2IF2IVF22(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIF2IF2IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSymmetricForcesDemonsRegistrationFilterIF2IF2IVF22___New_orig__: Any
itkSymmetricForcesDemonsRegistrationFilterIF2IF2IVF22_cast: Any

def itkSymmetricForcesDemonsRegistrationFilterIF2IF2IVF32_New(): ...

class itkSymmetricForcesDemonsRegistrationFilterIF2IF2IVF32(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIF2IF2IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSymmetricForcesDemonsRegistrationFilterIF2IF2IVF32___New_orig__: Any
itkSymmetricForcesDemonsRegistrationFilterIF2IF2IVF32_cast: Any

def itkSymmetricForcesDemonsRegistrationFilterIF2IF2IVF42_New(): ...

class itkSymmetricForcesDemonsRegistrationFilterIF2IF2IVF42(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIF2IF2IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSymmetricForcesDemonsRegistrationFilterIF2IF2IVF42___New_orig__: Any
itkSymmetricForcesDemonsRegistrationFilterIF2IF2IVF42_cast: Any

def itkSymmetricForcesDemonsRegistrationFilterIF3IF3IVF23_New(): ...

class itkSymmetricForcesDemonsRegistrationFilterIF3IF3IVF23(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIF3IF3IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSymmetricForcesDemonsRegistrationFilterIF3IF3IVF23___New_orig__: Any
itkSymmetricForcesDemonsRegistrationFilterIF3IF3IVF23_cast: Any

def itkSymmetricForcesDemonsRegistrationFilterIF3IF3IVF33_New(): ...

class itkSymmetricForcesDemonsRegistrationFilterIF3IF3IVF33(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIF3IF3IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSymmetricForcesDemonsRegistrationFilterIF3IF3IVF33___New_orig__: Any
itkSymmetricForcesDemonsRegistrationFilterIF3IF3IVF33_cast: Any

def itkSymmetricForcesDemonsRegistrationFilterIF3IF3IVF43_New(): ...

class itkSymmetricForcesDemonsRegistrationFilterIF3IF3IVF43(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIF3IF3IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSymmetricForcesDemonsRegistrationFilterIF3IF3IVF43___New_orig__: Any
itkSymmetricForcesDemonsRegistrationFilterIF3IF3IVF43_cast: Any

def itkSymmetricForcesDemonsRegistrationFilterISS2ISS2IVF22_New(): ...

class itkSymmetricForcesDemonsRegistrationFilterISS2ISS2IVF22(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterISS2ISS2IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSymmetricForcesDemonsRegistrationFilterISS2ISS2IVF22___New_orig__: Any
itkSymmetricForcesDemonsRegistrationFilterISS2ISS2IVF22_cast: Any

def itkSymmetricForcesDemonsRegistrationFilterISS2ISS2IVF32_New(): ...

class itkSymmetricForcesDemonsRegistrationFilterISS2ISS2IVF32(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterISS2ISS2IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSymmetricForcesDemonsRegistrationFilterISS2ISS2IVF32___New_orig__: Any
itkSymmetricForcesDemonsRegistrationFilterISS2ISS2IVF32_cast: Any

def itkSymmetricForcesDemonsRegistrationFilterISS2ISS2IVF42_New(): ...

class itkSymmetricForcesDemonsRegistrationFilterISS2ISS2IVF42(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterISS2ISS2IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSymmetricForcesDemonsRegistrationFilterISS2ISS2IVF42___New_orig__: Any
itkSymmetricForcesDemonsRegistrationFilterISS2ISS2IVF42_cast: Any

def itkSymmetricForcesDemonsRegistrationFilterISS3ISS3IVF23_New(): ...

class itkSymmetricForcesDemonsRegistrationFilterISS3ISS3IVF23(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterISS3ISS3IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSymmetricForcesDemonsRegistrationFilterISS3ISS3IVF23___New_orig__: Any
itkSymmetricForcesDemonsRegistrationFilterISS3ISS3IVF23_cast: Any

def itkSymmetricForcesDemonsRegistrationFilterISS3ISS3IVF33_New(): ...

class itkSymmetricForcesDemonsRegistrationFilterISS3ISS3IVF33(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterISS3ISS3IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSymmetricForcesDemonsRegistrationFilterISS3ISS3IVF33___New_orig__: Any
itkSymmetricForcesDemonsRegistrationFilterISS3ISS3IVF33_cast: Any

def itkSymmetricForcesDemonsRegistrationFilterISS3ISS3IVF43_New(): ...

class itkSymmetricForcesDemonsRegistrationFilterISS3ISS3IVF43(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterISS3ISS3IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSymmetricForcesDemonsRegistrationFilterISS3ISS3IVF43___New_orig__: Any
itkSymmetricForcesDemonsRegistrationFilterISS3ISS3IVF43_cast: Any

def itkSymmetricForcesDemonsRegistrationFilterIUC2IUC2IVF22_New(): ...

class itkSymmetricForcesDemonsRegistrationFilterIUC2IUC2IVF22(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIUC2IUC2IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSymmetricForcesDemonsRegistrationFilterIUC2IUC2IVF22___New_orig__: Any
itkSymmetricForcesDemonsRegistrationFilterIUC2IUC2IVF22_cast: Any

def itkSymmetricForcesDemonsRegistrationFilterIUC2IUC2IVF32_New(): ...

class itkSymmetricForcesDemonsRegistrationFilterIUC2IUC2IVF32(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIUC2IUC2IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSymmetricForcesDemonsRegistrationFilterIUC2IUC2IVF32___New_orig__: Any
itkSymmetricForcesDemonsRegistrationFilterIUC2IUC2IVF32_cast: Any

def itkSymmetricForcesDemonsRegistrationFilterIUC2IUC2IVF42_New(): ...

class itkSymmetricForcesDemonsRegistrationFilterIUC2IUC2IVF42(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIUC2IUC2IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSymmetricForcesDemonsRegistrationFilterIUC2IUC2IVF42___New_orig__: Any
itkSymmetricForcesDemonsRegistrationFilterIUC2IUC2IVF42_cast: Any

def itkSymmetricForcesDemonsRegistrationFilterIUC3IUC3IVF23_New(): ...

class itkSymmetricForcesDemonsRegistrationFilterIUC3IUC3IVF23(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIUC3IUC3IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSymmetricForcesDemonsRegistrationFilterIUC3IUC3IVF23___New_orig__: Any
itkSymmetricForcesDemonsRegistrationFilterIUC3IUC3IVF23_cast: Any

def itkSymmetricForcesDemonsRegistrationFilterIUC3IUC3IVF33_New(): ...

class itkSymmetricForcesDemonsRegistrationFilterIUC3IUC3IVF33(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIUC3IUC3IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSymmetricForcesDemonsRegistrationFilterIUC3IUC3IVF33___New_orig__: Any
itkSymmetricForcesDemonsRegistrationFilterIUC3IUC3IVF33_cast: Any

def itkSymmetricForcesDemonsRegistrationFilterIUC3IUC3IVF43_New(): ...

class itkSymmetricForcesDemonsRegistrationFilterIUC3IUC3IVF43(itk.itkPDEDeformableRegistrationFilterPython.itkPDEDeformableRegistrationFilterIUC3IUC3IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMetric: Any = ...
    SetIntensityDifferenceThreshold: Any = ...
    GetIntensityDifferenceThreshold: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkSymmetricForcesDemonsRegistrationFilterIUC3IUC3IVF43___New_orig__: Any
itkSymmetricForcesDemonsRegistrationFilterIUC3IUC3IVF43_cast: Any

def symmetric_forces_demons_registration_filter(*args: Any, **kwargs: Any): ...
def symmetric_forces_demons_registration_filter_init_docstring() -> None: ...
