import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkStreamingImageFilterIF2IF2_New(): ...

class itkStreamingImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetRegionSplitter: Any = ...
    GetModifiableRegionSplitter: Any = ...
    GetRegionSplitter: Any = ...
    SameDimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStreamingImageFilterIF2IF2___New_orig__: Any
itkStreamingImageFilterIF2IF2_cast: Any

def itkStreamingImageFilterIF3IF3_New(): ...

class itkStreamingImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetRegionSplitter: Any = ...
    GetModifiableRegionSplitter: Any = ...
    GetRegionSplitter: Any = ...
    SameDimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStreamingImageFilterIF3IF3___New_orig__: Any
itkStreamingImageFilterIF3IF3_cast: Any

def itkStreamingImageFilterISS2ISS2_New(): ...

class itkStreamingImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetRegionSplitter: Any = ...
    GetModifiableRegionSplitter: Any = ...
    GetRegionSplitter: Any = ...
    SameDimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStreamingImageFilterISS2ISS2___New_orig__: Any
itkStreamingImageFilterISS2ISS2_cast: Any

def itkStreamingImageFilterISS3ISS3_New(): ...

class itkStreamingImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetRegionSplitter: Any = ...
    GetModifiableRegionSplitter: Any = ...
    GetRegionSplitter: Any = ...
    SameDimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStreamingImageFilterISS3ISS3___New_orig__: Any
itkStreamingImageFilterISS3ISS3_cast: Any

def itkStreamingImageFilterIUC2IUC2_New(): ...

class itkStreamingImageFilterIUC2IUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetRegionSplitter: Any = ...
    GetModifiableRegionSplitter: Any = ...
    GetRegionSplitter: Any = ...
    SameDimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStreamingImageFilterIUC2IUC2___New_orig__: Any
itkStreamingImageFilterIUC2IUC2_cast: Any

def itkStreamingImageFilterIUC3IUC3_New(): ...

class itkStreamingImageFilterIUC3IUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetRegionSplitter: Any = ...
    GetModifiableRegionSplitter: Any = ...
    GetRegionSplitter: Any = ...
    SameDimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStreamingImageFilterIUC3IUC3___New_orig__: Any
itkStreamingImageFilterIUC3IUC3_cast: Any

def itkStreamingImageFilterIVF22IVF22_New(): ...

class itkStreamingImageFilterIVF22IVF22(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF22IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetRegionSplitter: Any = ...
    GetModifiableRegionSplitter: Any = ...
    GetRegionSplitter: Any = ...
    SameDimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStreamingImageFilterIVF22IVF22___New_orig__: Any
itkStreamingImageFilterIVF22IVF22_cast: Any

def itkStreamingImageFilterIVF23IVF23_New(): ...

class itkStreamingImageFilterIVF23IVF23(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF23IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetRegionSplitter: Any = ...
    GetModifiableRegionSplitter: Any = ...
    GetRegionSplitter: Any = ...
    SameDimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStreamingImageFilterIVF23IVF23___New_orig__: Any
itkStreamingImageFilterIVF23IVF23_cast: Any

def itkStreamingImageFilterIVF32IVF32_New(): ...

class itkStreamingImageFilterIVF32IVF32(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF32IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetRegionSplitter: Any = ...
    GetModifiableRegionSplitter: Any = ...
    GetRegionSplitter: Any = ...
    SameDimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStreamingImageFilterIVF32IVF32___New_orig__: Any
itkStreamingImageFilterIVF32IVF32_cast: Any

def itkStreamingImageFilterIVF33IVF33_New(): ...

class itkStreamingImageFilterIVF33IVF33(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF33IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetRegionSplitter: Any = ...
    GetModifiableRegionSplitter: Any = ...
    GetRegionSplitter: Any = ...
    SameDimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStreamingImageFilterIVF33IVF33___New_orig__: Any
itkStreamingImageFilterIVF33IVF33_cast: Any

def itkStreamingImageFilterIVF42IVF42_New(): ...

class itkStreamingImageFilterIVF42IVF42(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF42IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetRegionSplitter: Any = ...
    GetModifiableRegionSplitter: Any = ...
    GetRegionSplitter: Any = ...
    SameDimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStreamingImageFilterIVF42IVF42___New_orig__: Any
itkStreamingImageFilterIVF42IVF42_cast: Any

def itkStreamingImageFilterIVF43IVF43_New(): ...

class itkStreamingImageFilterIVF43IVF43(itk.itkImageToImageFilterAPython.itkImageToImageFilterIVF43IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNumberOfStreamDivisions: Any = ...
    GetNumberOfStreamDivisions: Any = ...
    SetRegionSplitter: Any = ...
    GetModifiableRegionSplitter: Any = ...
    GetRegionSplitter: Any = ...
    SameDimensionCheck: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkStreamingImageFilterIVF43IVF43___New_orig__: Any
itkStreamingImageFilterIVF43IVF43_cast: Any

def streaming_image_filter(*args: Any, **kwargs: Any): ...
def streaming_image_filter_init_docstring() -> None: ...
