import itk.itkInPlaceImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkTanImageFilterIF2IF2_New(): ...

class itkTanImageFilterIF2IF2(itk.itkUnaryGeneratorImageFilterPython.itkUnaryGeneratorImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToDoubleCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTanImageFilterIF2IF2___New_orig__: Any
itkTanImageFilterIF2IF2_cast: Any

def itkTanImageFilterIF3IF3_New(): ...

class itkTanImageFilterIF3IF3(itk.itkUnaryGeneratorImageFilterPython.itkUnaryGeneratorImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToDoubleCheck: Any = ...
    DoubleConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTanImageFilterIF3IF3___New_orig__: Any
itkTanImageFilterIF3IF3_cast: Any

def tan_image_filter(*args: Any, **kwargs: Any): ...
def tan_image_filter_init_docstring() -> None: ...
