import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkThresholdImageFilterIF2_New(): ...

class itkThresholdImageFilterIF2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PixelTypeComparableCheck: Any = ...
    PixelTypeOStreamWritableCheck: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    ThresholdAbove: Any = ...
    ThresholdBelow: Any = ...
    ThresholdOutside: Any = ...
    SetLower: Any = ...
    GetLower: Any = ...
    SetUpper: Any = ...
    GetUpper: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkThresholdImageFilterIF2___New_orig__: Any
itkThresholdImageFilterIF2_cast: Any

def itkThresholdImageFilterIF3_New(): ...

class itkThresholdImageFilterIF3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PixelTypeComparableCheck: Any = ...
    PixelTypeOStreamWritableCheck: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    ThresholdAbove: Any = ...
    ThresholdBelow: Any = ...
    ThresholdOutside: Any = ...
    SetLower: Any = ...
    GetLower: Any = ...
    SetUpper: Any = ...
    GetUpper: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkThresholdImageFilterIF3___New_orig__: Any
itkThresholdImageFilterIF3_cast: Any

def itkThresholdImageFilterISS2_New(): ...

class itkThresholdImageFilterISS2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PixelTypeComparableCheck: Any = ...
    PixelTypeOStreamWritableCheck: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    ThresholdAbove: Any = ...
    ThresholdBelow: Any = ...
    ThresholdOutside: Any = ...
    SetLower: Any = ...
    GetLower: Any = ...
    SetUpper: Any = ...
    GetUpper: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkThresholdImageFilterISS2___New_orig__: Any
itkThresholdImageFilterISS2_cast: Any

def itkThresholdImageFilterISS3_New(): ...

class itkThresholdImageFilterISS3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PixelTypeComparableCheck: Any = ...
    PixelTypeOStreamWritableCheck: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    ThresholdAbove: Any = ...
    ThresholdBelow: Any = ...
    ThresholdOutside: Any = ...
    SetLower: Any = ...
    GetLower: Any = ...
    SetUpper: Any = ...
    GetUpper: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkThresholdImageFilterISS3___New_orig__: Any
itkThresholdImageFilterISS3_cast: Any

def itkThresholdImageFilterIUC2_New(): ...

class itkThresholdImageFilterIUC2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PixelTypeComparableCheck: Any = ...
    PixelTypeOStreamWritableCheck: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    ThresholdAbove: Any = ...
    ThresholdBelow: Any = ...
    ThresholdOutside: Any = ...
    SetLower: Any = ...
    GetLower: Any = ...
    SetUpper: Any = ...
    GetUpper: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkThresholdImageFilterIUC2___New_orig__: Any
itkThresholdImageFilterIUC2_cast: Any

def itkThresholdImageFilterIUC3_New(): ...

class itkThresholdImageFilterIUC3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PixelTypeComparableCheck: Any = ...
    PixelTypeOStreamWritableCheck: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    ThresholdAbove: Any = ...
    ThresholdBelow: Any = ...
    ThresholdOutside: Any = ...
    SetLower: Any = ...
    GetLower: Any = ...
    SetUpper: Any = ...
    GetUpper: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkThresholdImageFilterIUC3___New_orig__: Any
itkThresholdImageFilterIUC3_cast: Any

def threshold_image_filter(*args: Any, **kwargs: Any): ...
def threshold_image_filter_init_docstring() -> None: ...
