import itk.itkImageSourceCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkTriangleThresholdImageFilterIF2ISS2_New(): ...

class itkTriangleThresholdImageFilterIF2ISS2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTriangleThresholdImageFilterIF2ISS2___New_orig__: Any
itkTriangleThresholdImageFilterIF2ISS2_cast: Any

def itkTriangleThresholdImageFilterIF2IUC2_New(): ...

class itkTriangleThresholdImageFilterIF2IUC2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTriangleThresholdImageFilterIF2IUC2___New_orig__: Any
itkTriangleThresholdImageFilterIF2IUC2_cast: Any

def itkTriangleThresholdImageFilterIF3ISS3_New(): ...

class itkTriangleThresholdImageFilterIF3ISS3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTriangleThresholdImageFilterIF3ISS3___New_orig__: Any
itkTriangleThresholdImageFilterIF3ISS3_cast: Any

def itkTriangleThresholdImageFilterIF3IUC3_New(): ...

class itkTriangleThresholdImageFilterIF3IUC3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTriangleThresholdImageFilterIF3IUC3___New_orig__: Any
itkTriangleThresholdImageFilterIF3IUC3_cast: Any

def itkTriangleThresholdImageFilterISS2ISS2_New(): ...

class itkTriangleThresholdImageFilterISS2ISS2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTriangleThresholdImageFilterISS2ISS2___New_orig__: Any
itkTriangleThresholdImageFilterISS2ISS2_cast: Any

def itkTriangleThresholdImageFilterISS2IUC2_New(): ...

class itkTriangleThresholdImageFilterISS2IUC2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTriangleThresholdImageFilterISS2IUC2___New_orig__: Any
itkTriangleThresholdImageFilterISS2IUC2_cast: Any

def itkTriangleThresholdImageFilterISS3ISS3_New(): ...

class itkTriangleThresholdImageFilterISS3ISS3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTriangleThresholdImageFilterISS3ISS3___New_orig__: Any
itkTriangleThresholdImageFilterISS3ISS3_cast: Any

def itkTriangleThresholdImageFilterISS3IUC3_New(): ...

class itkTriangleThresholdImageFilterISS3IUC3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTriangleThresholdImageFilterISS3IUC3___New_orig__: Any
itkTriangleThresholdImageFilterISS3IUC3_cast: Any

def itkTriangleThresholdImageFilterIUC2ISS2_New(): ...

class itkTriangleThresholdImageFilterIUC2ISS2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTriangleThresholdImageFilterIUC2ISS2___New_orig__: Any
itkTriangleThresholdImageFilterIUC2ISS2_cast: Any

def itkTriangleThresholdImageFilterIUC2IUC2_New(): ...

class itkTriangleThresholdImageFilterIUC2IUC2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTriangleThresholdImageFilterIUC2IUC2___New_orig__: Any
itkTriangleThresholdImageFilterIUC2IUC2_cast: Any

def itkTriangleThresholdImageFilterIUC3ISS3_New(): ...

class itkTriangleThresholdImageFilterIUC3ISS3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTriangleThresholdImageFilterIUC3ISS3___New_orig__: Any
itkTriangleThresholdImageFilterIUC3ISS3_cast: Any

def itkTriangleThresholdImageFilterIUC3IUC3_New(): ...

class itkTriangleThresholdImageFilterIUC3IUC3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTriangleThresholdImageFilterIUC3IUC3___New_orig__: Any
itkTriangleThresholdImageFilterIUC3IUC3_cast: Any

def triangle_threshold_image_filter(*args: Any, **kwargs: Any): ...
def triangle_threshold_image_filter_init_docstring() -> None: ...
