import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkThresholdSegmentationLevelSetImageFilterIF2IF2F_New(): ...

class itkThresholdSegmentationLevelSetImageFilterIF2IF2F(itk.itkSegmentationLevelSetImageFilterPython.itkSegmentationLevelSetImageFilterIF2IF2F):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetUpperThreshold: Any = ...
    SetLowerThreshold: Any = ...
    GetUpperThreshold: Any = ...
    GetLowerThreshold: Any = ...
    SetEdgeWeight: Any = ...
    GetEdgeWeight: Any = ...
    SetSmoothingIterations: Any = ...
    GetSmoothingIterations: Any = ...
    SetSmoothingTimeStep: Any = ...
    GetSmoothingTimeStep: Any = ...
    SetSmoothingConductance: Any = ...
    GetSmoothingConductance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkThresholdSegmentationLevelSetImageFilterIF2IF2F___New_orig__: Any
itkThresholdSegmentationLevelSetImageFilterIF2IF2F_cast: Any

def itkThresholdSegmentationLevelSetImageFilterIF3IF3F_New(): ...

class itkThresholdSegmentationLevelSetImageFilterIF3IF3F(itk.itkSegmentationLevelSetImageFilterPython.itkSegmentationLevelSetImageFilterIF3IF3F):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetUpperThreshold: Any = ...
    SetLowerThreshold: Any = ...
    GetUpperThreshold: Any = ...
    GetLowerThreshold: Any = ...
    SetEdgeWeight: Any = ...
    GetEdgeWeight: Any = ...
    SetSmoothingIterations: Any = ...
    GetSmoothingIterations: Any = ...
    SetSmoothingTimeStep: Any = ...
    GetSmoothingTimeStep: Any = ...
    SetSmoothingConductance: Any = ...
    GetSmoothingConductance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkThresholdSegmentationLevelSetImageFilterIF3IF3F___New_orig__: Any
itkThresholdSegmentationLevelSetImageFilterIF3IF3F_cast: Any

def threshold_segmentation_level_set_image_filter(*args: Any, **kwargs: Any): ...
def threshold_segmentation_level_set_image_filter_init_docstring() -> None: ...
