import itk.itkPointSetPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkPoint1D:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    getX: Any = ...
    getSign: Any = ...
    __swig_destroy__: Any = ...

def itkTriangleMeshToBinaryImageFilterMF3IF3_New(): ...

class itkTriangleMeshToBinaryImageFilterMF3IF3(itk.itkImageSourcePython.itkImageSourceIF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    SetInput: Any = ...
    SetInfoImage: Any = ...
    GetInput: Any = ...
    SetTolerance: Any = ...
    GetTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTriangleMeshToBinaryImageFilterMF3IF3___New_orig__: Any
itkTriangleMeshToBinaryImageFilterMF3IF3_cast: Any

def itkTriangleMeshToBinaryImageFilterMSS3ISS3_New(): ...

class itkTriangleMeshToBinaryImageFilterMSS3ISS3(itk.itkImageSourcePython.itkImageSourceISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    SetInput: Any = ...
    SetInfoImage: Any = ...
    GetInput: Any = ...
    SetTolerance: Any = ...
    GetTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTriangleMeshToBinaryImageFilterMSS3ISS3___New_orig__: Any
itkTriangleMeshToBinaryImageFilterMSS3ISS3_cast: Any

def itkTriangleMeshToBinaryImageFilterMUC3IUC3_New(): ...

class itkTriangleMeshToBinaryImageFilterMUC3IUC3(itk.itkImageSourcePython.itkImageSourceIUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSpacing: Any = ...
    GetSpacing: Any = ...
    SetDirection: Any = ...
    GetDirection: Any = ...
    SetInsideValue: Any = ...
    GetInsideValue: Any = ...
    SetOutsideValue: Any = ...
    GetOutsideValue: Any = ...
    SetOrigin: Any = ...
    GetOrigin: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    SetSize: Any = ...
    GetSize: Any = ...
    SetInput: Any = ...
    SetInfoImage: Any = ...
    GetInput: Any = ...
    SetTolerance: Any = ...
    GetTolerance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTriangleMeshToBinaryImageFilterMUC3IUC3___New_orig__: Any
itkTriangleMeshToBinaryImageFilterMUC3IUC3_cast: Any

def triangle_mesh_to_binary_image_filter(*args: Any, **kwargs: Any): ...
def triangle_mesh_to_binary_image_filter_init_docstring() -> None: ...
