import itk.itkImageRegionPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class listitkPointBasedSpatialObjectTube2_Pointer(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

class listitkPointBasedSpatialObjectTube3_Pointer(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

class listitkTubeSpatialObject2_Pointer(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

class listitkTubeSpatialObject3_Pointer(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

def itkPointBasedSpatialObjectTube2_New(): ...

class itkPointBasedSpatialObjectTube2(itk.itkSpatialObjectBasePython.itkSpatialObject2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    AddPoint: Any = ...
    RemovePoint: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    GetPoint: Any = ...
    GetNumberOfPoints: Any = ...
    ClosestPointInWorldSpace: Any = ...
    ClosestPointInObjectSpace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointBasedSpatialObjectTube2___New_orig__: Any
itkPointBasedSpatialObjectTube2_cast: Any

def itkPointBasedSpatialObjectTube3_New(): ...

class itkPointBasedSpatialObjectTube3(itk.itkSpatialObjectBasePython.itkSpatialObject3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    AddPoint: Any = ...
    RemovePoint: Any = ...
    SetPoints: Any = ...
    GetPoints: Any = ...
    GetPoint: Any = ...
    GetNumberOfPoints: Any = ...
    ClosestPointInWorldSpace: Any = ...
    ClosestPointInObjectSpace: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkPointBasedSpatialObjectTube3___New_orig__: Any
itkPointBasedSpatialObjectTube3_cast: Any

def itkTubeSpatialObject2_New(): ...

class itkTubeSpatialObject2(itkPointBasedSpatialObjectTube2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetEndRounded: Any = ...
    GetEndRounded: Any = ...
    EndRoundedOn: Any = ...
    EndRoundedOff: Any = ...
    ComputeTangentsAndNormals: Any = ...
    RemoveDuplicatePointsInObjectSpace: Any = ...
    SetParentPoint: Any = ...
    GetParentPoint: Any = ...
    SetRoot: Any = ...
    GetRoot: Any = ...
    RootOn: Any = ...
    RootOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTubeSpatialObject2___New_orig__: Any
itkTubeSpatialObject2_cast: Any

def itkTubeSpatialObject3_New(): ...

class itkTubeSpatialObject3(itkPointBasedSpatialObjectTube3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetEndRounded: Any = ...
    GetEndRounded: Any = ...
    EndRoundedOn: Any = ...
    EndRoundedOff: Any = ...
    ComputeTangentsAndNormals: Any = ...
    RemoveDuplicatePointsInObjectSpace: Any = ...
    SetParentPoint: Any = ...
    GetParentPoint: Any = ...
    SetRoot: Any = ...
    GetRoot: Any = ...
    RootOn: Any = ...
    RootOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTubeSpatialObject3___New_orig__: Any
itkTubeSpatialObject3_cast: Any
