from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkTriangleHelperPD2:
    thisown: Any = ...
    IsObtuse: Any = ...
    ComputeNormal: Any = ...
    Cotangent: Any = ...
    ComputeBarycenter: Any = ...
    ComputeAngle: Any = ...
    ComputeGravityCenter: Any = ...
    ComputeCircumCenter: Any = ...
    ComputeConstrainedCircumCenter: Any = ...
    ComputeArea: Any = ...
    ComputeMixedArea: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...

itkTriangleHelperPD2_IsObtuse: Any
itkTriangleHelperPD2_ComputeNormal: Any
itkTriangleHelperPD2_Cotangent: Any
itkTriangleHelperPD2_ComputeBarycenter: Any
itkTriangleHelperPD2_ComputeAngle: Any
itkTriangleHelperPD2_ComputeGravityCenter: Any
itkTriangleHelperPD2_ComputeCircumCenter: Any
itkTriangleHelperPD2_ComputeConstrainedCircumCenter: Any
itkTriangleHelperPD2_ComputeArea: Any
itkTriangleHelperPD2_ComputeMixedArea: Any

class itkTriangleHelperPD3:
    thisown: Any = ...
    IsObtuse: Any = ...
    ComputeNormal: Any = ...
    Cotangent: Any = ...
    ComputeBarycenter: Any = ...
    ComputeAngle: Any = ...
    ComputeGravityCenter: Any = ...
    ComputeCircumCenter: Any = ...
    ComputeConstrainedCircumCenter: Any = ...
    ComputeArea: Any = ...
    ComputeMixedArea: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...

itkTriangleHelperPD3_IsObtuse: Any
itkTriangleHelperPD3_ComputeNormal: Any
itkTriangleHelperPD3_Cotangent: Any
itkTriangleHelperPD3_ComputeBarycenter: Any
itkTriangleHelperPD3_ComputeAngle: Any
itkTriangleHelperPD3_ComputeGravityCenter: Any
itkTriangleHelperPD3_ComputeCircumCenter: Any
itkTriangleHelperPD3_ComputeConstrainedCircumCenter: Any
itkTriangleHelperPD3_ComputeArea: Any
itkTriangleHelperPD3_ComputeMixedArea: Any

class itkTriangleHelperPF2:
    thisown: Any = ...
    IsObtuse: Any = ...
    ComputeNormal: Any = ...
    Cotangent: Any = ...
    ComputeBarycenter: Any = ...
    ComputeAngle: Any = ...
    ComputeGravityCenter: Any = ...
    ComputeCircumCenter: Any = ...
    ComputeConstrainedCircumCenter: Any = ...
    ComputeArea: Any = ...
    ComputeMixedArea: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...

itkTriangleHelperPF2_IsObtuse: Any
itkTriangleHelperPF2_ComputeNormal: Any
itkTriangleHelperPF2_Cotangent: Any
itkTriangleHelperPF2_ComputeBarycenter: Any
itkTriangleHelperPF2_ComputeAngle: Any
itkTriangleHelperPF2_ComputeGravityCenter: Any
itkTriangleHelperPF2_ComputeCircumCenter: Any
itkTriangleHelperPF2_ComputeConstrainedCircumCenter: Any
itkTriangleHelperPF2_ComputeArea: Any
itkTriangleHelperPF2_ComputeMixedArea: Any

class itkTriangleHelperPF3:
    thisown: Any = ...
    IsObtuse: Any = ...
    ComputeNormal: Any = ...
    Cotangent: Any = ...
    ComputeBarycenter: Any = ...
    ComputeAngle: Any = ...
    ComputeGravityCenter: Any = ...
    ComputeCircumCenter: Any = ...
    ComputeConstrainedCircumCenter: Any = ...
    ComputeArea: Any = ...
    ComputeMixedArea: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...

itkTriangleHelperPF3_IsObtuse: Any
itkTriangleHelperPF3_ComputeNormal: Any
itkTriangleHelperPF3_Cotangent: Any
itkTriangleHelperPF3_ComputeBarycenter: Any
itkTriangleHelperPF3_ComputeAngle: Any
itkTriangleHelperPF3_ComputeGravityCenter: Any
itkTriangleHelperPF3_ComputeCircumCenter: Any
itkTriangleHelperPF3_ComputeConstrainedCircumCenter: Any
itkTriangleHelperPF3_ComputeArea: Any
itkTriangleHelperPF3_ComputeMixedArea: Any
