import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkTobogganImageFilterIF2_New(): ...

class itkTobogganImageFilterIF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IUL2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ImageDimension: Any = ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GenerateData: Any = ...
    GenerateInputRequestedRegion: Any = ...
    LessThanComparableCheck: Any = ...
    OStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTobogganImageFilterIF2___New_orig__: Any
itkTobogganImageFilterIF2_cast: Any

def itkTobogganImageFilterIF3_New(): ...

class itkTobogganImageFilterIF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IUL3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ImageDimension: Any = ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GenerateData: Any = ...
    GenerateInputRequestedRegion: Any = ...
    LessThanComparableCheck: Any = ...
    OStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTobogganImageFilterIF3___New_orig__: Any
itkTobogganImageFilterIF3_cast: Any

def itkTobogganImageFilterISS2_New(): ...

class itkTobogganImageFilterISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2IUL2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ImageDimension: Any = ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GenerateData: Any = ...
    GenerateInputRequestedRegion: Any = ...
    LessThanComparableCheck: Any = ...
    OStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTobogganImageFilterISS2___New_orig__: Any
itkTobogganImageFilterISS2_cast: Any

def itkTobogganImageFilterISS3_New(): ...

class itkTobogganImageFilterISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3IUL3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ImageDimension: Any = ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GenerateData: Any = ...
    GenerateInputRequestedRegion: Any = ...
    LessThanComparableCheck: Any = ...
    OStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTobogganImageFilterISS3___New_orig__: Any
itkTobogganImageFilterISS3_cast: Any

def itkTobogganImageFilterIUC2_New(): ...

class itkTobogganImageFilterIUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUL2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ImageDimension: Any = ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GenerateData: Any = ...
    GenerateInputRequestedRegion: Any = ...
    LessThanComparableCheck: Any = ...
    OStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTobogganImageFilterIUC2___New_orig__: Any
itkTobogganImageFilterIUC2_cast: Any

def itkTobogganImageFilterIUC3_New(): ...

class itkTobogganImageFilterIUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUL3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ImageDimension: Any = ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GenerateData: Any = ...
    GenerateInputRequestedRegion: Any = ...
    LessThanComparableCheck: Any = ...
    OStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTobogganImageFilterIUC3___New_orig__: Any
itkTobogganImageFilterIUC3_cast: Any

def toboggan_image_filter(*args: Any, **kwargs: Any): ...
def toboggan_image_filter_init_docstring() -> None: ...
