import itk.itkSymmetricSecondRankTensorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkTransformMeshFilterMF2MF2TD22_New(): ...

class itkTransformMeshFilterMF2MF2TD22(itk.itkMeshToMeshFilterPython.itkMeshToMeshFilterMF2MF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetTransform: Any = ...
    GetModifiableTransform: Any = ...
    GetTransform: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTransformMeshFilterMF2MF2TD22___New_orig__: Any
itkTransformMeshFilterMF2MF2TD22_cast: Any

def itkTransformMeshFilterMF2MF2TF22_New(): ...

class itkTransformMeshFilterMF2MF2TF22(itk.itkMeshToMeshFilterPython.itkMeshToMeshFilterMF2MF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetTransform: Any = ...
    GetModifiableTransform: Any = ...
    GetTransform: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTransformMeshFilterMF2MF2TF22___New_orig__: Any
itkTransformMeshFilterMF2MF2TF22_cast: Any

def itkTransformMeshFilterMF3MF3TD33_New(): ...

class itkTransformMeshFilterMF3MF3TD33(itk.itkMeshToMeshFilterPython.itkMeshToMeshFilterMF3MF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetTransform: Any = ...
    GetModifiableTransform: Any = ...
    GetTransform: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTransformMeshFilterMF3MF3TD33___New_orig__: Any
itkTransformMeshFilterMF3MF3TD33_cast: Any

def itkTransformMeshFilterMF3MF3TF33_New(): ...

class itkTransformMeshFilterMF3MF3TF33(itk.itkMeshToMeshFilterPython.itkMeshToMeshFilterMF3MF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetTransform: Any = ...
    GetModifiableTransform: Any = ...
    GetTransform: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkTransformMeshFilterMF3MF3TF33___New_orig__: Any
itkTransformMeshFilterMF3MF3TF33_cast: Any

def transform_mesh_filter(*args: Any, **kwargs: Any): ...
def transform_mesh_filter_init_docstring() -> None: ...
