import itk.itkImageRegionPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class vectoritkTubeSpatialObjectPoint2(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectoritkTubeSpatialObjectPoint3(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class itkTubeSpatialObjectPoint2(itk.itkSpatialObjectPointPython.itkSpatialObjectPoint2):
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    GetRadiusInObjectSpace: Any = ...
    GetRadiusInWorldSpace: Any = ...
    SetRadiusInObjectSpace: Any = ...
    SetRadiusInWorldSpace: Any = ...
    GetTangentInObjectSpace: Any = ...
    GetTangentInWorldSpace: Any = ...
    SetTangentInObjectSpace: Any = ...
    SetTangentInWorldSpace: Any = ...
    GetNormal1InObjectSpace: Any = ...
    GetNormal1InWorldSpace: Any = ...
    SetNormal1InObjectSpace: Any = ...
    SetNormal1InWorldSpace: Any = ...
    GetNormal2InObjectSpace: Any = ...
    GetNormal2InWorldSpace: Any = ...
    SetNormal2InObjectSpace: Any = ...
    SetNormal2InWorldSpace: Any = ...
    SetRidgeness: Any = ...
    GetRidgeness: Any = ...
    SetCurvature: Any = ...
    GetCurvature: Any = ...
    SetLevelness: Any = ...
    GetLevelness: Any = ...
    SetRoundness: Any = ...
    GetRoundness: Any = ...
    SetIntensity: Any = ...
    GetIntensity: Any = ...
    SetMedialness: Any = ...
    GetMedialness: Any = ...
    SetBranchness: Any = ...
    GetBranchness: Any = ...
    SetAlpha1: Any = ...
    GetAlpha1: Any = ...
    SetAlpha2: Any = ...
    GetAlpha2: Any = ...
    SetAlpha3: Any = ...
    GetAlpha3: Any = ...

class itkTubeSpatialObjectPoint3(itk.itkSpatialObjectPointPython.itkSpatialObjectPoint3):
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    GetRadiusInObjectSpace: Any = ...
    GetRadiusInWorldSpace: Any = ...
    SetRadiusInObjectSpace: Any = ...
    SetRadiusInWorldSpace: Any = ...
    GetTangentInObjectSpace: Any = ...
    GetTangentInWorldSpace: Any = ...
    SetTangentInObjectSpace: Any = ...
    SetTangentInWorldSpace: Any = ...
    GetNormal1InObjectSpace: Any = ...
    GetNormal1InWorldSpace: Any = ...
    SetNormal1InObjectSpace: Any = ...
    SetNormal1InWorldSpace: Any = ...
    GetNormal2InObjectSpace: Any = ...
    GetNormal2InWorldSpace: Any = ...
    SetNormal2InObjectSpace: Any = ...
    SetNormal2InWorldSpace: Any = ...
    SetRidgeness: Any = ...
    GetRidgeness: Any = ...
    SetCurvature: Any = ...
    GetCurvature: Any = ...
    SetLevelness: Any = ...
    GetLevelness: Any = ...
    SetRoundness: Any = ...
    GetRoundness: Any = ...
    SetIntensity: Any = ...
    GetIntensity: Any = ...
    SetMedialness: Any = ...
    GetMedialness: Any = ...
    SetBranchness: Any = ...
    GetBranchness: Any = ...
    SetAlpha1: Any = ...
    GetAlpha1: Any = ...
    SetAlpha2: Any = ...
    GetAlpha2: Any = ...
    SetAlpha3: Any = ...
    GetAlpha3: Any = ...
