import itk.itkImageToImageFilterCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkUnaryFrequencyDomainFilterICF2_New(): ...

class itkUnaryFrequencyDomainFilterICF2(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterICF2ICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageTypeHasNumericTraitsCheck: Any = ...
    SetActualXDimensionIsOdd: Any = ...
    GetActualXDimensionIsOdd: Any = ...
    ActualXDimensionIsOddOn: Any = ...
    ActualXDimensionIsOddOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryFrequencyDomainFilterICF2___New_orig__: Any
itkUnaryFrequencyDomainFilterICF2_cast: Any

def itkUnaryFrequencyDomainFilterICF3_New(): ...

class itkUnaryFrequencyDomainFilterICF3(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterICF3ICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageTypeHasNumericTraitsCheck: Any = ...
    SetActualXDimensionIsOdd: Any = ...
    GetActualXDimensionIsOdd: Any = ...
    ActualXDimensionIsOddOn: Any = ...
    ActualXDimensionIsOddOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryFrequencyDomainFilterICF3___New_orig__: Any
itkUnaryFrequencyDomainFilterICF3_cast: Any

def unary_frequency_domain_filter(*args: Any, **kwargs: Any): ...
def unary_frequency_domain_filter_init_docstring() -> None: ...
