import itk.itkInPlaceImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkUnaryGeneratorImageFilterICF2ICF2_New(): ...

class itkUnaryGeneratorImageFilterICF2ICF2(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterICF2ICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterICF2ICF2___New_orig__: Any
itkUnaryGeneratorImageFilterICF2ICF2_cast: Any

def itkUnaryGeneratorImageFilterICF2IF2_New(): ...

class itkUnaryGeneratorImageFilterICF2IF2(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterICF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterICF2IF2___New_orig__: Any
itkUnaryGeneratorImageFilterICF2IF2_cast: Any

def itkUnaryGeneratorImageFilterICF2ISS2_New(): ...

class itkUnaryGeneratorImageFilterICF2ISS2(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterICF2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterICF2ISS2___New_orig__: Any
itkUnaryGeneratorImageFilterICF2ISS2_cast: Any

def itkUnaryGeneratorImageFilterICF2IUC2_New(): ...

class itkUnaryGeneratorImageFilterICF2IUC2(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterICF2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterICF2IUC2___New_orig__: Any
itkUnaryGeneratorImageFilterICF2IUC2_cast: Any

def itkUnaryGeneratorImageFilterICF3ICF3_New(): ...

class itkUnaryGeneratorImageFilterICF3ICF3(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterICF3ICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterICF3ICF3___New_orig__: Any
itkUnaryGeneratorImageFilterICF3ICF3_cast: Any

def itkUnaryGeneratorImageFilterICF3IF3_New(): ...

class itkUnaryGeneratorImageFilterICF3IF3(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterICF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterICF3IF3___New_orig__: Any
itkUnaryGeneratorImageFilterICF3IF3_cast: Any

def itkUnaryGeneratorImageFilterICF3ISS3_New(): ...

class itkUnaryGeneratorImageFilterICF3ISS3(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterICF3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterICF3ISS3___New_orig__: Any
itkUnaryGeneratorImageFilterICF3ISS3_cast: Any

def itkUnaryGeneratorImageFilterICF3IUC3_New(): ...

class itkUnaryGeneratorImageFilterICF3IUC3(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterICF3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterICF3IUC3___New_orig__: Any
itkUnaryGeneratorImageFilterICF3IUC3_cast: Any

def itkUnaryGeneratorImageFilterIF2ICF2_New(): ...

class itkUnaryGeneratorImageFilterIF2ICF2(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterIF2ICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterIF2ICF2___New_orig__: Any
itkUnaryGeneratorImageFilterIF2ICF2_cast: Any

def itkUnaryGeneratorImageFilterIF2IF2_New(): ...

class itkUnaryGeneratorImageFilterIF2IF2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterIF2IF2___New_orig__: Any
itkUnaryGeneratorImageFilterIF2IF2_cast: Any

def itkUnaryGeneratorImageFilterIF2ISS2_New(): ...

class itkUnaryGeneratorImageFilterIF2ISS2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterIF2ISS2___New_orig__: Any
itkUnaryGeneratorImageFilterIF2ISS2_cast: Any

def itkUnaryGeneratorImageFilterIF2IUC2_New(): ...

class itkUnaryGeneratorImageFilterIF2IUC2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterIF2IUC2___New_orig__: Any
itkUnaryGeneratorImageFilterIF2IUC2_cast: Any

def itkUnaryGeneratorImageFilterIF3ICF3_New(): ...

class itkUnaryGeneratorImageFilterIF3ICF3(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterIF3ICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterIF3ICF3___New_orig__: Any
itkUnaryGeneratorImageFilterIF3ICF3_cast: Any

def itkUnaryGeneratorImageFilterIF3IF3_New(): ...

class itkUnaryGeneratorImageFilterIF3IF3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterIF3IF3___New_orig__: Any
itkUnaryGeneratorImageFilterIF3IF3_cast: Any

def itkUnaryGeneratorImageFilterIF3ISS3_New(): ...

class itkUnaryGeneratorImageFilterIF3ISS3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterIF3ISS3___New_orig__: Any
itkUnaryGeneratorImageFilterIF3ISS3_cast: Any

def itkUnaryGeneratorImageFilterIF3IUC3_New(): ...

class itkUnaryGeneratorImageFilterIF3IUC3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterIF3IUC3___New_orig__: Any
itkUnaryGeneratorImageFilterIF3IUC3_cast: Any

def itkUnaryGeneratorImageFilterIRGBAUC2IUC2_New(): ...

class itkUnaryGeneratorImageFilterIRGBAUC2IUC2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIRGBAUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterIRGBAUC2IUC2___New_orig__: Any
itkUnaryGeneratorImageFilterIRGBAUC2IUC2_cast: Any

def itkUnaryGeneratorImageFilterIRGBAUC3IUC3_New(): ...

class itkUnaryGeneratorImageFilterIRGBAUC3IUC3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIRGBAUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterIRGBAUC3IUC3___New_orig__: Any
itkUnaryGeneratorImageFilterIRGBAUC3IUC3_cast: Any

def itkUnaryGeneratorImageFilterIRGBUC2IUC2_New(): ...

class itkUnaryGeneratorImageFilterIRGBUC2IUC2(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterIRGBUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterIRGBUC2IUC2___New_orig__: Any
itkUnaryGeneratorImageFilterIRGBUC2IUC2_cast: Any

def itkUnaryGeneratorImageFilterIRGBUC3IUC3_New(): ...

class itkUnaryGeneratorImageFilterIRGBUC3IUC3(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterIRGBUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterIRGBUC3IUC3___New_orig__: Any
itkUnaryGeneratorImageFilterIRGBUC3IUC3_cast: Any

def itkUnaryGeneratorImageFilterISS2ICF2_New(): ...

class itkUnaryGeneratorImageFilterISS2ICF2(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterISS2ICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterISS2ICF2___New_orig__: Any
itkUnaryGeneratorImageFilterISS2ICF2_cast: Any

def itkUnaryGeneratorImageFilterISS2IF2_New(): ...

class itkUnaryGeneratorImageFilterISS2IF2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterISS2IF2___New_orig__: Any
itkUnaryGeneratorImageFilterISS2IF2_cast: Any

def itkUnaryGeneratorImageFilterISS2ISS2_New(): ...

class itkUnaryGeneratorImageFilterISS2ISS2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterISS2ISS2___New_orig__: Any
itkUnaryGeneratorImageFilterISS2ISS2_cast: Any

def itkUnaryGeneratorImageFilterISS2IUC2_New(): ...

class itkUnaryGeneratorImageFilterISS2IUC2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterISS2IUC2___New_orig__: Any
itkUnaryGeneratorImageFilterISS2IUC2_cast: Any

def itkUnaryGeneratorImageFilterISS3ICF3_New(): ...

class itkUnaryGeneratorImageFilterISS3ICF3(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterISS3ICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterISS3ICF3___New_orig__: Any
itkUnaryGeneratorImageFilterISS3ICF3_cast: Any

def itkUnaryGeneratorImageFilterISS3IF3_New(): ...

class itkUnaryGeneratorImageFilterISS3IF3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterISS3IF3___New_orig__: Any
itkUnaryGeneratorImageFilterISS3IF3_cast: Any

def itkUnaryGeneratorImageFilterISS3ISS3_New(): ...

class itkUnaryGeneratorImageFilterISS3ISS3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterISS3ISS3___New_orig__: Any
itkUnaryGeneratorImageFilterISS3ISS3_cast: Any

def itkUnaryGeneratorImageFilterISS3IUC3_New(): ...

class itkUnaryGeneratorImageFilterISS3IUC3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterISS3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterISS3IUC3___New_orig__: Any
itkUnaryGeneratorImageFilterISS3IUC3_cast: Any

def itkUnaryGeneratorImageFilterIUC2ICF2_New(): ...

class itkUnaryGeneratorImageFilterIUC2ICF2(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterIUC2ICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterIUC2ICF2___New_orig__: Any
itkUnaryGeneratorImageFilterIUC2ICF2_cast: Any

def itkUnaryGeneratorImageFilterIUC2IF2_New(): ...

class itkUnaryGeneratorImageFilterIUC2IF2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterIUC2IF2___New_orig__: Any
itkUnaryGeneratorImageFilterIUC2IF2_cast: Any

def itkUnaryGeneratorImageFilterIUC2ISS2_New(): ...

class itkUnaryGeneratorImageFilterIUC2ISS2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterIUC2ISS2___New_orig__: Any
itkUnaryGeneratorImageFilterIUC2ISS2_cast: Any

def itkUnaryGeneratorImageFilterIUC2IUC2_New(): ...

class itkUnaryGeneratorImageFilterIUC2IUC2(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterIUC2IUC2___New_orig__: Any
itkUnaryGeneratorImageFilterIUC2IUC2_cast: Any

def itkUnaryGeneratorImageFilterIUC3ICF3_New(): ...

class itkUnaryGeneratorImageFilterIUC3ICF3(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterIUC3ICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterIUC3ICF3___New_orig__: Any
itkUnaryGeneratorImageFilterIUC3ICF3_cast: Any

def itkUnaryGeneratorImageFilterIUC3IF3_New(): ...

class itkUnaryGeneratorImageFilterIUC3IF3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterIUC3IF3___New_orig__: Any
itkUnaryGeneratorImageFilterIUC3IF3_cast: Any

def itkUnaryGeneratorImageFilterIUC3ISS3_New(): ...

class itkUnaryGeneratorImageFilterIUC3ISS3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterIUC3ISS3___New_orig__: Any
itkUnaryGeneratorImageFilterIUC3ISS3_cast: Any

def itkUnaryGeneratorImageFilterIUC3IUC3_New(): ...

class itkUnaryGeneratorImageFilterIUC3IUC3(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkUnaryGeneratorImageFilterIUC3IUC3___New_orig__: Any
itkUnaryGeneratorImageFilterIUC3IUC3_cast: Any

def unary_generator_image_filter(*args: Any, **kwargs: Any): ...
def unary_generator_image_filter_init_docstring() -> None: ...
