import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkVectorCurvatureAnisotropicDiffusionImageFilterICVF22ICVF22_New(): ...

class itkVectorCurvatureAnisotropicDiffusionImageFilterICVF22ICVF22(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterICVF22ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorCurvatureAnisotropicDiffusionImageFilterICVF22ICVF22___New_orig__: Any
itkVectorCurvatureAnisotropicDiffusionImageFilterICVF22ICVF22_cast: Any

def itkVectorCurvatureAnisotropicDiffusionImageFilterICVF23ICVF23_New(): ...

class itkVectorCurvatureAnisotropicDiffusionImageFilterICVF23ICVF23(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterICVF23ICVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorCurvatureAnisotropicDiffusionImageFilterICVF23ICVF23___New_orig__: Any
itkVectorCurvatureAnisotropicDiffusionImageFilterICVF23ICVF23_cast: Any

def itkVectorCurvatureAnisotropicDiffusionImageFilterICVF32ICVF32_New(): ...

class itkVectorCurvatureAnisotropicDiffusionImageFilterICVF32ICVF32(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterICVF32ICVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorCurvatureAnisotropicDiffusionImageFilterICVF32ICVF32___New_orig__: Any
itkVectorCurvatureAnisotropicDiffusionImageFilterICVF32ICVF32_cast: Any

def itkVectorCurvatureAnisotropicDiffusionImageFilterICVF33ICVF33_New(): ...

class itkVectorCurvatureAnisotropicDiffusionImageFilterICVF33ICVF33(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterICVF33ICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorCurvatureAnisotropicDiffusionImageFilterICVF33ICVF33___New_orig__: Any
itkVectorCurvatureAnisotropicDiffusionImageFilterICVF33ICVF33_cast: Any

def itkVectorCurvatureAnisotropicDiffusionImageFilterICVF42ICVF42_New(): ...

class itkVectorCurvatureAnisotropicDiffusionImageFilterICVF42ICVF42(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterICVF42ICVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorCurvatureAnisotropicDiffusionImageFilterICVF42ICVF42___New_orig__: Any
itkVectorCurvatureAnisotropicDiffusionImageFilterICVF42ICVF42_cast: Any

def itkVectorCurvatureAnisotropicDiffusionImageFilterICVF43ICVF43_New(): ...

class itkVectorCurvatureAnisotropicDiffusionImageFilterICVF43ICVF43(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterICVF43ICVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorCurvatureAnisotropicDiffusionImageFilterICVF43ICVF43___New_orig__: Any
itkVectorCurvatureAnisotropicDiffusionImageFilterICVF43ICVF43_cast: Any

def itkVectorCurvatureAnisotropicDiffusionImageFilterIVF22IVF22_New(): ...

class itkVectorCurvatureAnisotropicDiffusionImageFilterIVF22IVF22(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterIVF22IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorCurvatureAnisotropicDiffusionImageFilterIVF22IVF22___New_orig__: Any
itkVectorCurvatureAnisotropicDiffusionImageFilterIVF22IVF22_cast: Any

def itkVectorCurvatureAnisotropicDiffusionImageFilterIVF23IVF23_New(): ...

class itkVectorCurvatureAnisotropicDiffusionImageFilterIVF23IVF23(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterIVF23IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorCurvatureAnisotropicDiffusionImageFilterIVF23IVF23___New_orig__: Any
itkVectorCurvatureAnisotropicDiffusionImageFilterIVF23IVF23_cast: Any

def itkVectorCurvatureAnisotropicDiffusionImageFilterIVF32IVF32_New(): ...

class itkVectorCurvatureAnisotropicDiffusionImageFilterIVF32IVF32(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterIVF32IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorCurvatureAnisotropicDiffusionImageFilterIVF32IVF32___New_orig__: Any
itkVectorCurvatureAnisotropicDiffusionImageFilterIVF32IVF32_cast: Any

def itkVectorCurvatureAnisotropicDiffusionImageFilterIVF33IVF33_New(): ...

class itkVectorCurvatureAnisotropicDiffusionImageFilterIVF33IVF33(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterIVF33IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorCurvatureAnisotropicDiffusionImageFilterIVF33IVF33___New_orig__: Any
itkVectorCurvatureAnisotropicDiffusionImageFilterIVF33IVF33_cast: Any

def itkVectorCurvatureAnisotropicDiffusionImageFilterIVF42IVF42_New(): ...

class itkVectorCurvatureAnisotropicDiffusionImageFilterIVF42IVF42(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterIVF42IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorCurvatureAnisotropicDiffusionImageFilterIVF42IVF42___New_orig__: Any
itkVectorCurvatureAnisotropicDiffusionImageFilterIVF42IVF42_cast: Any

def itkVectorCurvatureAnisotropicDiffusionImageFilterIVF43IVF43_New(): ...

class itkVectorCurvatureAnisotropicDiffusionImageFilterIVF43IVF43(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterIVF43IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorCurvatureAnisotropicDiffusionImageFilterIVF43IVF43___New_orig__: Any
itkVectorCurvatureAnisotropicDiffusionImageFilterIVF43IVF43_cast: Any

def vector_curvature_anisotropic_diffusion_image_filter(*args: Any, **kwargs: Any): ...
def vector_curvature_anisotropic_diffusion_image_filter_init_docstring() -> None: ...
