import itk.itkArrayPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkVTKPolyDataReaderMD2_Superclass_New(): ...

class itkVTKPolyDataReaderMD2_Superclass(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOutput: Any = ...
    SetOutput: Any = ...
    GraftOutput: Any = ...
    GraftNthOutput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKPolyDataReaderMD2_Superclass___New_orig__: Any
itkVTKPolyDataReaderMD2_Superclass_cast: Any

def itkVTKPolyDataReaderMD3_Superclass_New(): ...

class itkVTKPolyDataReaderMD3_Superclass(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOutput: Any = ...
    SetOutput: Any = ...
    GraftOutput: Any = ...
    GraftNthOutput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKPolyDataReaderMD3_Superclass___New_orig__: Any
itkVTKPolyDataReaderMD3_Superclass_cast: Any

def itkVTKPolyDataReaderMF2_Superclass_New(): ...

class itkVTKPolyDataReaderMF2_Superclass(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOutput: Any = ...
    SetOutput: Any = ...
    GraftOutput: Any = ...
    GraftNthOutput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKPolyDataReaderMF2_Superclass___New_orig__: Any
itkVTKPolyDataReaderMF2_Superclass_cast: Any

def itkVTKPolyDataReaderMF3_Superclass_New(): ...

class itkVTKPolyDataReaderMF3_Superclass(itk.ITKCommonBasePython.itkProcessObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetOutput: Any = ...
    SetOutput: Any = ...
    GraftOutput: Any = ...
    GraftNthOutput: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKPolyDataReaderMF3_Superclass___New_orig__: Any
itkVTKPolyDataReaderMF3_Superclass_cast: Any

def itkVTKPolyDataReaderMD2_New(): ...

class itkVTKPolyDataReaderMD2(itkVTKPolyDataReaderMD2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    GetVersion: Any = ...
    GetHeader: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKPolyDataReaderMD2___New_orig__: Any
itkVTKPolyDataReaderMD2_cast: Any

def itkVTKPolyDataReaderMD3_New(): ...

class itkVTKPolyDataReaderMD3(itkVTKPolyDataReaderMD3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    GetVersion: Any = ...
    GetHeader: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKPolyDataReaderMD3___New_orig__: Any
itkVTKPolyDataReaderMD3_cast: Any

def itkVTKPolyDataReaderMF2_New(): ...

class itkVTKPolyDataReaderMF2(itkVTKPolyDataReaderMF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    GetVersion: Any = ...
    GetHeader: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKPolyDataReaderMF2___New_orig__: Any
itkVTKPolyDataReaderMF2_cast: Any

def itkVTKPolyDataReaderMF3_New(): ...

class itkVTKPolyDataReaderMF3(itkVTKPolyDataReaderMF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetFileName: Any = ...
    GetFileName: Any = ...
    GetVersion: Any = ...
    GetHeader: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKPolyDataReaderMF3___New_orig__: Any
itkVTKPolyDataReaderMF3_cast: Any

def vtk_poly_data_reader(*args: Any, **kwargs: Any): ...
def vtk_poly_data_reader_init_docstring() -> None: ...
def mesh_source(*args: Any, **kwargs: Any): ...
def mesh_source_init_docstring() -> None: ...
