import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkVotingBinaryIterativeHoleFillingImageFilterISS2_New(): ...

class itkVotingBinaryIterativeHoleFillingImageFilterISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaximumNumberOfIterations: Any = ...
    SetMaximumNumberOfIterations: Any = ...
    GetCurrentNumberOfIterations: Any = ...
    SetCurrentNumberOfIterations: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetForegroundValue: Any = ...
    GetMajorityThreshold: Any = ...
    SetMajorityThreshold: Any = ...
    GetNumberOfPixelsChanged: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputOStreamWritableeCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVotingBinaryIterativeHoleFillingImageFilterISS2___New_orig__: Any
itkVotingBinaryIterativeHoleFillingImageFilterISS2_cast: Any

def itkVotingBinaryIterativeHoleFillingImageFilterISS3_New(): ...

class itkVotingBinaryIterativeHoleFillingImageFilterISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaximumNumberOfIterations: Any = ...
    SetMaximumNumberOfIterations: Any = ...
    GetCurrentNumberOfIterations: Any = ...
    SetCurrentNumberOfIterations: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetForegroundValue: Any = ...
    GetMajorityThreshold: Any = ...
    SetMajorityThreshold: Any = ...
    GetNumberOfPixelsChanged: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputOStreamWritableeCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVotingBinaryIterativeHoleFillingImageFilterISS3___New_orig__: Any
itkVotingBinaryIterativeHoleFillingImageFilterISS3_cast: Any

def itkVotingBinaryIterativeHoleFillingImageFilterIUC2_New(): ...

class itkVotingBinaryIterativeHoleFillingImageFilterIUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaximumNumberOfIterations: Any = ...
    SetMaximumNumberOfIterations: Any = ...
    GetCurrentNumberOfIterations: Any = ...
    SetCurrentNumberOfIterations: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetForegroundValue: Any = ...
    GetMajorityThreshold: Any = ...
    SetMajorityThreshold: Any = ...
    GetNumberOfPixelsChanged: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputOStreamWritableeCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVotingBinaryIterativeHoleFillingImageFilterIUC2___New_orig__: Any
itkVotingBinaryIterativeHoleFillingImageFilterIUC2_cast: Any

def itkVotingBinaryIterativeHoleFillingImageFilterIUC3_New(): ...

class itkVotingBinaryIterativeHoleFillingImageFilterIUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetMaximumNumberOfIterations: Any = ...
    SetMaximumNumberOfIterations: Any = ...
    GetCurrentNumberOfIterations: Any = ...
    SetCurrentNumberOfIterations: Any = ...
    SetRadius: Any = ...
    GetRadius: Any = ...
    SetBackgroundValue: Any = ...
    SetForegroundValue: Any = ...
    GetBackgroundValue: Any = ...
    GetForegroundValue: Any = ...
    GetMajorityThreshold: Any = ...
    SetMajorityThreshold: Any = ...
    GetNumberOfPixelsChanged: Any = ...
    InputEqualityComparableCheck: Any = ...
    InputOStreamWritableeCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVotingBinaryIterativeHoleFillingImageFilterIUC3___New_orig__: Any
itkVotingBinaryIterativeHoleFillingImageFilterIUC3_cast: Any

def voting_binary_iterative_hole_filling_image_filter(*args: Any, **kwargs: Any): ...
def voting_binary_iterative_hole_filling_image_filter_init_docstring() -> None: ...
