import itk.itkInPlaceImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkVectorIndexSelectionCastImageFilterICVF22IF2_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterICVF22IF2_Superclass(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterICVF22IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterICVF22IF2_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterICVF22IF2_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterICVF23IF3_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterICVF23IF3_Superclass(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterICVF23IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterICVF23IF3_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterICVF23IF3_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterICVF32IF2_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterICVF32IF2_Superclass(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterICVF32IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterICVF32IF2_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterICVF32IF2_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterICVF33IF3_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterICVF33IF3_Superclass(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterICVF33IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterICVF33IF3_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterICVF33IF3_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterICVF42IF2_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterICVF42IF2_Superclass(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterICVF42IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterICVF42IF2_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterICVF42IF2_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterICVF43IF3_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterICVF43IF3_Superclass(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterICVF43IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterICVF43IF3_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterICVF43IF3_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterIRGBAUC2IUC2_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterIRGBAUC2IUC2_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIRGBAUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterIRGBAUC2IUC2_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterIRGBAUC2IUC2_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterIRGBAUC3IUC3_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterIRGBAUC3IUC3_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIRGBAUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterIRGBAUC3IUC3_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterIRGBAUC3IUC3_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterIRGBUC2IUC2_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterIRGBUC2IUC2_Superclass(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterIRGBUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterIRGBUC2IUC2_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterIRGBUC2IUC2_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterIRGBUC3IUC3_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterIRGBUC3IUC3_Superclass(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterIRGBUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterIRGBUC3IUC3_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterIRGBUC3IUC3_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterIVF22IF2_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterIVF22IF2_Superclass(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterIVF22IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterIVF22IF2_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterIVF22IF2_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterIVF23IF3_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterIVF23IF3_Superclass(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterIVF23IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterIVF23IF3_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterIVF23IF3_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterIVF32IF2_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterIVF32IF2_Superclass(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterIVF32IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterIVF32IF2_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterIVF32IF2_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterIVF33IF3_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterIVF33IF3_Superclass(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterIVF33IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterIVF33IF3_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterIVF33IF3_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterIVF42IF2_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterIVF42IF2_Superclass(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterIVF42IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterIVF42IF2_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterIVF42IF2_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterIVF43IF3_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterIVF43IF3_Superclass(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterIVF43IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterIVF43IF3_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterIVF43IF3_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterVIF2IF2_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterVIF2IF2_Superclass(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterVIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterVIF2IF2_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterVIF2IF2_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterVIF3IF3_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterVIF3IF3_Superclass(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterVIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterVIF3IF3_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterVIF3IF3_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterVISS2ISS2_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterVISS2ISS2_Superclass(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterVISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterVISS2ISS2_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterVISS2ISS2_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterVISS3ISS3_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterVISS3ISS3_Superclass(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterVISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterVISS3ISS3_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterVISS3ISS3_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterVIUC2IUC2_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterVIUC2IUC2_Superclass(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterVIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterVIUC2IUC2_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterVIUC2IUC2_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterVIUC3IUC3_Superclass_New(): ...

class itkVectorIndexSelectionCastImageFilterVIUC3IUC3_Superclass(itk.itkInPlaceImageFilterBPython.itkInPlaceImageFilterVIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterVIUC3IUC3_Superclass___New_orig__: Any
itkVectorIndexSelectionCastImageFilterVIUC3IUC3_Superclass_cast: Any

def itkVectorIndexSelectionCastImageFilterICVF22IF2_New(): ...

class itkVectorIndexSelectionCastImageFilterICVF22IF2(itkVectorIndexSelectionCastImageFilterICVF22IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterICVF22IF2___New_orig__: Any
itkVectorIndexSelectionCastImageFilterICVF22IF2_cast: Any

def itkVectorIndexSelectionCastImageFilterICVF23IF3_New(): ...

class itkVectorIndexSelectionCastImageFilterICVF23IF3(itkVectorIndexSelectionCastImageFilterICVF23IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterICVF23IF3___New_orig__: Any
itkVectorIndexSelectionCastImageFilterICVF23IF3_cast: Any

def itkVectorIndexSelectionCastImageFilterICVF32IF2_New(): ...

class itkVectorIndexSelectionCastImageFilterICVF32IF2(itkVectorIndexSelectionCastImageFilterICVF32IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterICVF32IF2___New_orig__: Any
itkVectorIndexSelectionCastImageFilterICVF32IF2_cast: Any

def itkVectorIndexSelectionCastImageFilterICVF33IF3_New(): ...

class itkVectorIndexSelectionCastImageFilterICVF33IF3(itkVectorIndexSelectionCastImageFilterICVF33IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterICVF33IF3___New_orig__: Any
itkVectorIndexSelectionCastImageFilterICVF33IF3_cast: Any

def itkVectorIndexSelectionCastImageFilterICVF42IF2_New(): ...

class itkVectorIndexSelectionCastImageFilterICVF42IF2(itkVectorIndexSelectionCastImageFilterICVF42IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterICVF42IF2___New_orig__: Any
itkVectorIndexSelectionCastImageFilterICVF42IF2_cast: Any

def itkVectorIndexSelectionCastImageFilterICVF43IF3_New(): ...

class itkVectorIndexSelectionCastImageFilterICVF43IF3(itkVectorIndexSelectionCastImageFilterICVF43IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterICVF43IF3___New_orig__: Any
itkVectorIndexSelectionCastImageFilterICVF43IF3_cast: Any

def itkVectorIndexSelectionCastImageFilterIRGBAUC2IUC2_New(): ...

class itkVectorIndexSelectionCastImageFilterIRGBAUC2IUC2(itkVectorIndexSelectionCastImageFilterIRGBAUC2IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterIRGBAUC2IUC2___New_orig__: Any
itkVectorIndexSelectionCastImageFilterIRGBAUC2IUC2_cast: Any

def itkVectorIndexSelectionCastImageFilterIRGBAUC3IUC3_New(): ...

class itkVectorIndexSelectionCastImageFilterIRGBAUC3IUC3(itkVectorIndexSelectionCastImageFilterIRGBAUC3IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterIRGBAUC3IUC3___New_orig__: Any
itkVectorIndexSelectionCastImageFilterIRGBAUC3IUC3_cast: Any

def itkVectorIndexSelectionCastImageFilterIRGBUC2IUC2_New(): ...

class itkVectorIndexSelectionCastImageFilterIRGBUC2IUC2(itkVectorIndexSelectionCastImageFilterIRGBUC2IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterIRGBUC2IUC2___New_orig__: Any
itkVectorIndexSelectionCastImageFilterIRGBUC2IUC2_cast: Any

def itkVectorIndexSelectionCastImageFilterIRGBUC3IUC3_New(): ...

class itkVectorIndexSelectionCastImageFilterIRGBUC3IUC3(itkVectorIndexSelectionCastImageFilterIRGBUC3IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterIRGBUC3IUC3___New_orig__: Any
itkVectorIndexSelectionCastImageFilterIRGBUC3IUC3_cast: Any

def itkVectorIndexSelectionCastImageFilterIVF22IF2_New(): ...

class itkVectorIndexSelectionCastImageFilterIVF22IF2(itkVectorIndexSelectionCastImageFilterIVF22IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterIVF22IF2___New_orig__: Any
itkVectorIndexSelectionCastImageFilterIVF22IF2_cast: Any

def itkVectorIndexSelectionCastImageFilterIVF23IF3_New(): ...

class itkVectorIndexSelectionCastImageFilterIVF23IF3(itkVectorIndexSelectionCastImageFilterIVF23IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterIVF23IF3___New_orig__: Any
itkVectorIndexSelectionCastImageFilterIVF23IF3_cast: Any

def itkVectorIndexSelectionCastImageFilterIVF32IF2_New(): ...

class itkVectorIndexSelectionCastImageFilterIVF32IF2(itkVectorIndexSelectionCastImageFilterIVF32IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterIVF32IF2___New_orig__: Any
itkVectorIndexSelectionCastImageFilterIVF32IF2_cast: Any

def itkVectorIndexSelectionCastImageFilterIVF33IF3_New(): ...

class itkVectorIndexSelectionCastImageFilterIVF33IF3(itkVectorIndexSelectionCastImageFilterIVF33IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterIVF33IF3___New_orig__: Any
itkVectorIndexSelectionCastImageFilterIVF33IF3_cast: Any

def itkVectorIndexSelectionCastImageFilterIVF42IF2_New(): ...

class itkVectorIndexSelectionCastImageFilterIVF42IF2(itkVectorIndexSelectionCastImageFilterIVF42IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterIVF42IF2___New_orig__: Any
itkVectorIndexSelectionCastImageFilterIVF42IF2_cast: Any

def itkVectorIndexSelectionCastImageFilterIVF43IF3_New(): ...

class itkVectorIndexSelectionCastImageFilterIVF43IF3(itkVectorIndexSelectionCastImageFilterIVF43IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterIVF43IF3___New_orig__: Any
itkVectorIndexSelectionCastImageFilterIVF43IF3_cast: Any

def itkVectorIndexSelectionCastImageFilterVIF2IF2_New(): ...

class itkVectorIndexSelectionCastImageFilterVIF2IF2(itkVectorIndexSelectionCastImageFilterVIF2IF2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterVIF2IF2___New_orig__: Any
itkVectorIndexSelectionCastImageFilterVIF2IF2_cast: Any

def itkVectorIndexSelectionCastImageFilterVIF3IF3_New(): ...

class itkVectorIndexSelectionCastImageFilterVIF3IF3(itkVectorIndexSelectionCastImageFilterVIF3IF3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterVIF3IF3___New_orig__: Any
itkVectorIndexSelectionCastImageFilterVIF3IF3_cast: Any

def itkVectorIndexSelectionCastImageFilterVISS2ISS2_New(): ...

class itkVectorIndexSelectionCastImageFilterVISS2ISS2(itkVectorIndexSelectionCastImageFilterVISS2ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterVISS2ISS2___New_orig__: Any
itkVectorIndexSelectionCastImageFilterVISS2ISS2_cast: Any

def itkVectorIndexSelectionCastImageFilterVISS3ISS3_New(): ...

class itkVectorIndexSelectionCastImageFilterVISS3ISS3(itkVectorIndexSelectionCastImageFilterVISS3ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterVISS3ISS3___New_orig__: Any
itkVectorIndexSelectionCastImageFilterVISS3ISS3_cast: Any

def itkVectorIndexSelectionCastImageFilterVIUC2IUC2_New(): ...

class itkVectorIndexSelectionCastImageFilterVIUC2IUC2(itkVectorIndexSelectionCastImageFilterVIUC2IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterVIUC2IUC2___New_orig__: Any
itkVectorIndexSelectionCastImageFilterVIUC2IUC2_cast: Any

def itkVectorIndexSelectionCastImageFilterVIUC3IUC3_New(): ...

class itkVectorIndexSelectionCastImageFilterVIUC3IUC3(itkVectorIndexSelectionCastImageFilterVIUC3IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetIndex: Any = ...
    GetIndex: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorIndexSelectionCastImageFilterVIUC3IUC3___New_orig__: Any
itkVectorIndexSelectionCastImageFilterVIUC3IUC3_cast: Any

def vector_index_selection_cast_image_filter(*args: Any, **kwargs: Any): ...
def vector_index_selection_cast_image_filter_init_docstring() -> None: ...
def unary_functor_image_filter(*args: Any, **kwargs: Any): ...
def unary_functor_image_filter_init_docstring() -> None: ...
