import itk.itkMeshIOBasePython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkVTKPolyDataMeshIO_New(): ...

class itkVTKPolyDataMeshIO(itk.itkMeshIOBasePython.itkMeshIOBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKPolyDataMeshIO___New_orig__: Any
itkVTKPolyDataMeshIO_cast: Any

def itkVTKPolyDataMeshIOFactory_New(): ...

class itkVTKPolyDataMeshIOFactory(itk.ITKCommonBasePython.itkObjectFactoryBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    RegisterOneFactory: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKPolyDataMeshIOFactory___New_orig__: Any
itkVTKPolyDataMeshIOFactory_RegisterOneFactory: Any
itkVTKPolyDataMeshIOFactory_cast: Any
