import itk.itkImageSourceCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkVTKImageImportICVF22_New(): ...

class itkVTKImageImportICVF22(itk.itkImageSourcePython.itkImageSourceICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportICVF22___New_orig__: Any
itkVTKImageImportICVF22_cast: Any

def itkVTKImageImportICVF23_New(): ...

class itkVTKImageImportICVF23(itk.itkImageSourcePython.itkImageSourceICVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportICVF23___New_orig__: Any
itkVTKImageImportICVF23_cast: Any

def itkVTKImageImportICVF32_New(): ...

class itkVTKImageImportICVF32(itk.itkImageSourcePython.itkImageSourceICVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportICVF32___New_orig__: Any
itkVTKImageImportICVF32_cast: Any

def itkVTKImageImportICVF33_New(): ...

class itkVTKImageImportICVF33(itk.itkImageSourcePython.itkImageSourceICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportICVF33___New_orig__: Any
itkVTKImageImportICVF33_cast: Any

def itkVTKImageImportICVF42_New(): ...

class itkVTKImageImportICVF42(itk.itkImageSourcePython.itkImageSourceICVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportICVF42___New_orig__: Any
itkVTKImageImportICVF42_cast: Any

def itkVTKImageImportICVF43_New(): ...

class itkVTKImageImportICVF43(itk.itkImageSourcePython.itkImageSourceICVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportICVF43___New_orig__: Any
itkVTKImageImportICVF43_cast: Any

def itkVTKImageImportIF2_New(): ...

class itkVTKImageImportIF2(itk.itkImageSourcePython.itkImageSourceIF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportIF2___New_orig__: Any
itkVTKImageImportIF2_cast: Any

def itkVTKImageImportIF3_New(): ...

class itkVTKImageImportIF3(itk.itkImageSourcePython.itkImageSourceIF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportIF3___New_orig__: Any
itkVTKImageImportIF3_cast: Any

def itkVTKImageImportIRGBAUC2_New(): ...

class itkVTKImageImportIRGBAUC2(itk.itkImageSourcePython.itkImageSourceIRGBAUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportIRGBAUC2___New_orig__: Any
itkVTKImageImportIRGBAUC2_cast: Any

def itkVTKImageImportIRGBAUC3_New(): ...

class itkVTKImageImportIRGBAUC3(itk.itkImageSourcePython.itkImageSourceIRGBAUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportIRGBAUC3___New_orig__: Any
itkVTKImageImportIRGBAUC3_cast: Any

def itkVTKImageImportIRGBUC2_New(): ...

class itkVTKImageImportIRGBUC2(itk.itkImageSourcePython.itkImageSourceIRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportIRGBUC2___New_orig__: Any
itkVTKImageImportIRGBUC2_cast: Any

def itkVTKImageImportIRGBUC3_New(): ...

class itkVTKImageImportIRGBUC3(itk.itkImageSourcePython.itkImageSourceIRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportIRGBUC3___New_orig__: Any
itkVTKImageImportIRGBUC3_cast: Any

def itkVTKImageImportISS2_New(): ...

class itkVTKImageImportISS2(itk.itkImageSourcePython.itkImageSourceISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportISS2___New_orig__: Any
itkVTKImageImportISS2_cast: Any

def itkVTKImageImportISS3_New(): ...

class itkVTKImageImportISS3(itk.itkImageSourcePython.itkImageSourceISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportISS3___New_orig__: Any
itkVTKImageImportISS3_cast: Any

def itkVTKImageImportIUC2_New(): ...

class itkVTKImageImportIUC2(itk.itkImageSourcePython.itkImageSourceIUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportIUC2___New_orig__: Any
itkVTKImageImportIUC2_cast: Any

def itkVTKImageImportIUC3_New(): ...

class itkVTKImageImportIUC3(itk.itkImageSourcePython.itkImageSourceIUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportIUC3___New_orig__: Any
itkVTKImageImportIUC3_cast: Any

def itkVTKImageImportIUL2_New(): ...

class itkVTKImageImportIUL2(itk.itkImageSourcePython.itkImageSourceIUL2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportIUL2___New_orig__: Any
itkVTKImageImportIUL2_cast: Any

def itkVTKImageImportIUL3_New(): ...

class itkVTKImageImportIUL3(itk.itkImageSourcePython.itkImageSourceIUL3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportIUL3___New_orig__: Any
itkVTKImageImportIUL3_cast: Any

def itkVTKImageImportIVF22_New(): ...

class itkVTKImageImportIVF22(itk.itkImageSourcePython.itkImageSourceIVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportIVF22___New_orig__: Any
itkVTKImageImportIVF22_cast: Any

def itkVTKImageImportIVF23_New(): ...

class itkVTKImageImportIVF23(itk.itkImageSourcePython.itkImageSourceIVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportIVF23___New_orig__: Any
itkVTKImageImportIVF23_cast: Any

def itkVTKImageImportIVF32_New(): ...

class itkVTKImageImportIVF32(itk.itkImageSourcePython.itkImageSourceIVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportIVF32___New_orig__: Any
itkVTKImageImportIVF32_cast: Any

def itkVTKImageImportIVF33_New(): ...

class itkVTKImageImportIVF33(itk.itkImageSourcePython.itkImageSourceIVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportIVF33___New_orig__: Any
itkVTKImageImportIVF33_cast: Any

def itkVTKImageImportIVF42_New(): ...

class itkVTKImageImportIVF42(itk.itkImageSourcePython.itkImageSourceIVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportIVF42___New_orig__: Any
itkVTKImageImportIVF42_cast: Any

def itkVTKImageImportIVF43_New(): ...

class itkVTKImageImportIVF43(itk.itkImageSourcePython.itkImageSourceIVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetCallbackUserData: Any = ...
    GetCallbackUserData: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageImportIVF43___New_orig__: Any
itkVTKImageImportIVF43_cast: Any

def vtk_image_import(*args: Any, **kwargs: Any): ...
def vtk_image_import_init_docstring() -> None: ...
