import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkVnlForwardFFTImageFilterIF2ICF2_New(): ...

class itkVnlForwardFFTImageFilterIF2ICF2(itk.itkForwardFFTImageFilterPython.itkForwardFFTImageFilterIF2ICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionsMatchCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVnlForwardFFTImageFilterIF2ICF2___New_orig__: Any
itkVnlForwardFFTImageFilterIF2ICF2_cast: Any

def itkVnlForwardFFTImageFilterIF3ICF3_New(): ...

class itkVnlForwardFFTImageFilterIF3ICF3(itk.itkForwardFFTImageFilterPython.itkForwardFFTImageFilterIF3ICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionsMatchCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVnlForwardFFTImageFilterIF3ICF3___New_orig__: Any
itkVnlForwardFFTImageFilterIF3ICF3_cast: Any

def vnl_forward_fft_image_filter(*args: Any, **kwargs: Any): ...
def vnl_forward_fft_image_filter_init_docstring() -> None: ...
