from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class itkVariableSizeMatrixD:
    thisown: Any = ...
    __add__: Any = ...
    __iadd__: Any = ...
    __sub__: Any = ...
    __isub__: Any = ...
    __neg__: Any = ...
    __imul__: Any = ...
    __mul__: Any = ...
    def __itruediv__(self, *args: Any): ...
    __idiv__: Any = ...
    def __truediv__(self, *args: Any): ...
    __div__: Any = ...
    __call__: Any = ...
    GetVnlMatrix: Any = ...
    SetIdentity: Any = ...
    Fill: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    GetInverse: Any = ...
    GetTranspose: Any = ...
    def __init__(self, *args: Any) -> None: ...
    Rows: Any = ...
    Cols: Any = ...
    SetSize: Any = ...
    __swig_destroy__: Any = ...
