import itk.itkArrayPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkVnlRealToHalfHermitianForwardFFTImageFilterIF2ICF2_New(): ...

class itkVnlRealToHalfHermitianForwardFFTImageFilterIF2ICF2(itk.itkRealToHalfHermitianForwardFFTImageFilterPython.itkRealToHalfHermitianForwardFFTImageFilterIF2ICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionsMatchCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVnlRealToHalfHermitianForwardFFTImageFilterIF2ICF2___New_orig__: Any
itkVnlRealToHalfHermitianForwardFFTImageFilterIF2ICF2_cast: Any

def itkVnlRealToHalfHermitianForwardFFTImageFilterIF3ICF3_New(): ...

class itkVnlRealToHalfHermitianForwardFFTImageFilterIF3ICF3(itk.itkRealToHalfHermitianForwardFFTImageFilterPython.itkRealToHalfHermitianForwardFFTImageFilterIF3ICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    ImageDimensionsMatchCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVnlRealToHalfHermitianForwardFFTImageFilterIF3ICF3___New_orig__: Any
itkVnlRealToHalfHermitianForwardFFTImageFilterIF3ICF3_cast: Any

def vnl_real_to_half_hermitian_forward_fft_image_filter(*args: Any, **kwargs: Any): ...
def vnl_real_to_half_hermitian_forward_fft_image_filter_init_docstring() -> None: ...
