import itk.itkImageRegionPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkVelocityFieldTransformD2_New(): ...

class itkVelocityFieldTransformD2(itk.itkDisplacementFieldTransformPython.itkDisplacementFieldTransformD2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetVelocityField: Any = ...
    GetModifiableVelocityField: Any = ...
    GetVelocityField: Any = ...
    SetVelocityFieldInterpolator: Any = ...
    GetModifiableVelocityFieldInterpolator: Any = ...
    GetVelocityFieldInterpolator: Any = ...
    GetVelocityFieldSetTime: Any = ...
    UpdateTransformParameters: Any = ...
    GetInverse: Any = ...
    IntegrateVelocityField: Any = ...
    SetLowerTimeBound: Any = ...
    GetLowerTimeBound: Any = ...
    SetUpperTimeBound: Any = ...
    GetUpperTimeBound: Any = ...
    SetNumberOfIntegrationSteps: Any = ...
    GetNumberOfIntegrationSteps: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVelocityFieldTransformD2___New_orig__: Any
itkVelocityFieldTransformD2_cast: Any

def itkVelocityFieldTransformD3_New(): ...

class itkVelocityFieldTransformD3(itk.itkDisplacementFieldTransformPython.itkDisplacementFieldTransformD3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetVelocityField: Any = ...
    GetModifiableVelocityField: Any = ...
    GetVelocityField: Any = ...
    SetVelocityFieldInterpolator: Any = ...
    GetModifiableVelocityFieldInterpolator: Any = ...
    GetVelocityFieldInterpolator: Any = ...
    GetVelocityFieldSetTime: Any = ...
    UpdateTransformParameters: Any = ...
    GetInverse: Any = ...
    IntegrateVelocityField: Any = ...
    SetLowerTimeBound: Any = ...
    GetLowerTimeBound: Any = ...
    SetUpperTimeBound: Any = ...
    GetUpperTimeBound: Any = ...
    SetNumberOfIntegrationSteps: Any = ...
    GetNumberOfIntegrationSteps: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVelocityFieldTransformD3___New_orig__: Any
itkVelocityFieldTransformD3_cast: Any
