import itk.itkImageToImageFilterBPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkVectorConnectedComponentImageFilterICVF22ISS2_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterICVF22ISS2_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterICVF22ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF22ISS2_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF22ISS2_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterICVF22IUC2_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterICVF22IUC2_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterICVF22IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF22IUC2_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF22IUC2_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterICVF23ISS3_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterICVF23ISS3_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterICVF23ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF23ISS3_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF23ISS3_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterICVF23IUC3_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterICVF23IUC3_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterICVF23IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF23IUC3_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF23IUC3_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterICVF32ISS2_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterICVF32ISS2_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterICVF32ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF32ISS2_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF32ISS2_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterICVF32IUC2_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterICVF32IUC2_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterICVF32IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF32IUC2_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF32IUC2_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterICVF33ISS3_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterICVF33ISS3_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterICVF33ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF33ISS3_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF33ISS3_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterICVF33IUC3_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterICVF33IUC3_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterICVF33IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF33IUC3_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF33IUC3_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterICVF42ISS2_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterICVF42ISS2_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterICVF42ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF42ISS2_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF42ISS2_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterICVF42IUC2_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterICVF42IUC2_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterICVF42IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF42IUC2_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF42IUC2_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterICVF43ISS3_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterICVF43ISS3_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterICVF43ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF43ISS3_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF43ISS3_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterICVF43IUC3_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterICVF43IUC3_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterICVF43IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF43IUC3_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF43IUC3_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterIVF22ISS2_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterIVF22ISS2_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterIVF22ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF22ISS2_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF22ISS2_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterIVF22IUC2_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterIVF22IUC2_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterIVF22IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF22IUC2_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF22IUC2_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterIVF23ISS3_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterIVF23ISS3_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterIVF23ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF23ISS3_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF23ISS3_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterIVF23IUC3_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterIVF23IUC3_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterIVF23IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF23IUC3_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF23IUC3_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterIVF32ISS2_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterIVF32ISS2_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterIVF32ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF32ISS2_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF32ISS2_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterIVF32IUC2_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterIVF32IUC2_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterIVF32IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF32IUC2_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF32IUC2_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterIVF33ISS3_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterIVF33ISS3_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterIVF33ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF33ISS3_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF33ISS3_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterIVF33IUC3_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterIVF33IUC3_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterIVF33IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF33IUC3_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF33IUC3_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterIVF42ISS2_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterIVF42ISS2_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterIVF42ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF42ISS2_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF42ISS2_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterIVF42IUC2_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterIVF42IUC2_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterIVF42IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF42IUC2_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF42IUC2_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterIVF43ISS3_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterIVF43ISS3_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterIVF43ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF43ISS3_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF43ISS3_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterIVF43IUC3_Superclass_New(): ...

class itkVectorConnectedComponentImageFilterIVF43IUC3_Superclass(itk.itkConnectedComponentImageFilterPython.itkConnectedComponentImageFilterIVF43IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    SameDimensionCheck: Any = ...
    InputEqualityComparableCheck: Any = ...
    OutputEqualityComparableCheck: Any = ...
    OutputConvertibleToUnsignedIntCheck: Any = ...
    OutputConvertibleToUnsignedLongCheck: Any = ...
    OutputConvertibleToLongCheck: Any = ...
    UnsignedLongConvertibleToOutputCheck: Any = ...
    OutputIncrementDecrementOperatorsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF43IUC3_Superclass___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF43IUC3_Superclass_cast: Any

def itkVectorConnectedComponentImageFilterICVF22ISS2_New(): ...

class itkVectorConnectedComponentImageFilterICVF22ISS2(itkVectorConnectedComponentImageFilterICVF22ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF22ISS2___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF22ISS2_cast: Any

def itkVectorConnectedComponentImageFilterICVF22IUC2_New(): ...

class itkVectorConnectedComponentImageFilterICVF22IUC2(itkVectorConnectedComponentImageFilterICVF22IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF22IUC2___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF22IUC2_cast: Any

def itkVectorConnectedComponentImageFilterICVF23ISS3_New(): ...

class itkVectorConnectedComponentImageFilterICVF23ISS3(itkVectorConnectedComponentImageFilterICVF23ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF23ISS3___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF23ISS3_cast: Any

def itkVectorConnectedComponentImageFilterICVF23IUC3_New(): ...

class itkVectorConnectedComponentImageFilterICVF23IUC3(itkVectorConnectedComponentImageFilterICVF23IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF23IUC3___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF23IUC3_cast: Any

def itkVectorConnectedComponentImageFilterICVF32ISS2_New(): ...

class itkVectorConnectedComponentImageFilterICVF32ISS2(itkVectorConnectedComponentImageFilterICVF32ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF32ISS2___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF32ISS2_cast: Any

def itkVectorConnectedComponentImageFilterICVF32IUC2_New(): ...

class itkVectorConnectedComponentImageFilterICVF32IUC2(itkVectorConnectedComponentImageFilterICVF32IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF32IUC2___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF32IUC2_cast: Any

def itkVectorConnectedComponentImageFilterICVF33ISS3_New(): ...

class itkVectorConnectedComponentImageFilterICVF33ISS3(itkVectorConnectedComponentImageFilterICVF33ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF33ISS3___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF33ISS3_cast: Any

def itkVectorConnectedComponentImageFilterICVF33IUC3_New(): ...

class itkVectorConnectedComponentImageFilterICVF33IUC3(itkVectorConnectedComponentImageFilterICVF33IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF33IUC3___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF33IUC3_cast: Any

def itkVectorConnectedComponentImageFilterICVF42ISS2_New(): ...

class itkVectorConnectedComponentImageFilterICVF42ISS2(itkVectorConnectedComponentImageFilterICVF42ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF42ISS2___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF42ISS2_cast: Any

def itkVectorConnectedComponentImageFilterICVF42IUC2_New(): ...

class itkVectorConnectedComponentImageFilterICVF42IUC2(itkVectorConnectedComponentImageFilterICVF42IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF42IUC2___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF42IUC2_cast: Any

def itkVectorConnectedComponentImageFilterICVF43ISS3_New(): ...

class itkVectorConnectedComponentImageFilterICVF43ISS3(itkVectorConnectedComponentImageFilterICVF43ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF43ISS3___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF43ISS3_cast: Any

def itkVectorConnectedComponentImageFilterICVF43IUC3_New(): ...

class itkVectorConnectedComponentImageFilterICVF43IUC3(itkVectorConnectedComponentImageFilterICVF43IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterICVF43IUC3___New_orig__: Any
itkVectorConnectedComponentImageFilterICVF43IUC3_cast: Any

def itkVectorConnectedComponentImageFilterIVF22ISS2_New(): ...

class itkVectorConnectedComponentImageFilterIVF22ISS2(itkVectorConnectedComponentImageFilterIVF22ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF22ISS2___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF22ISS2_cast: Any

def itkVectorConnectedComponentImageFilterIVF22IUC2_New(): ...

class itkVectorConnectedComponentImageFilterIVF22IUC2(itkVectorConnectedComponentImageFilterIVF22IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF22IUC2___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF22IUC2_cast: Any

def itkVectorConnectedComponentImageFilterIVF23ISS3_New(): ...

class itkVectorConnectedComponentImageFilterIVF23ISS3(itkVectorConnectedComponentImageFilterIVF23ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF23ISS3___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF23ISS3_cast: Any

def itkVectorConnectedComponentImageFilterIVF23IUC3_New(): ...

class itkVectorConnectedComponentImageFilterIVF23IUC3(itkVectorConnectedComponentImageFilterIVF23IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF23IUC3___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF23IUC3_cast: Any

def itkVectorConnectedComponentImageFilterIVF32ISS2_New(): ...

class itkVectorConnectedComponentImageFilterIVF32ISS2(itkVectorConnectedComponentImageFilterIVF32ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF32ISS2___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF32ISS2_cast: Any

def itkVectorConnectedComponentImageFilterIVF32IUC2_New(): ...

class itkVectorConnectedComponentImageFilterIVF32IUC2(itkVectorConnectedComponentImageFilterIVF32IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF32IUC2___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF32IUC2_cast: Any

def itkVectorConnectedComponentImageFilterIVF33ISS3_New(): ...

class itkVectorConnectedComponentImageFilterIVF33ISS3(itkVectorConnectedComponentImageFilterIVF33ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF33ISS3___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF33ISS3_cast: Any

def itkVectorConnectedComponentImageFilterIVF33IUC3_New(): ...

class itkVectorConnectedComponentImageFilterIVF33IUC3(itkVectorConnectedComponentImageFilterIVF33IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF33IUC3___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF33IUC3_cast: Any

def itkVectorConnectedComponentImageFilterIVF42ISS2_New(): ...

class itkVectorConnectedComponentImageFilterIVF42ISS2(itkVectorConnectedComponentImageFilterIVF42ISS2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF42ISS2___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF42ISS2_cast: Any

def itkVectorConnectedComponentImageFilterIVF42IUC2_New(): ...

class itkVectorConnectedComponentImageFilterIVF42IUC2(itkVectorConnectedComponentImageFilterIVF42IUC2_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF42IUC2___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF42IUC2_cast: Any

def itkVectorConnectedComponentImageFilterIVF43ISS3_New(): ...

class itkVectorConnectedComponentImageFilterIVF43ISS3(itkVectorConnectedComponentImageFilterIVF43ISS3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF43ISS3___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF43ISS3_cast: Any

def itkVectorConnectedComponentImageFilterIVF43IUC3_New(): ...

class itkVectorConnectedComponentImageFilterIVF43IUC3(itkVectorConnectedComponentImageFilterIVF43IUC3_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetDistanceThreshold: Any = ...
    GetDistanceThreshold: Any = ...
    InputValueHasNumericTraitsCheck: Any = ...
    InputValyeTypeIsFloatingCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorConnectedComponentImageFilterIVF43IUC3___New_orig__: Any
itkVectorConnectedComponentImageFilterIVF43IUC3_cast: Any

def connected_component_functor_image_filter(*args: Any, **kwargs: Any): ...
def connected_component_functor_image_filter_init_docstring() -> None: ...
def vector_connected_component_image_filter(*args: Any, **kwargs: Any): ...
def vector_connected_component_image_filter_init_docstring() -> None: ...
