import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkVectorRescaleIntensityImageFilterIVF22IVF22_Superclass_New(): ...

class itkVectorRescaleIntensityImageFilterIVF22IVF22_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIVF22IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorRescaleIntensityImageFilterIVF22IVF22_Superclass___New_orig__: Any
itkVectorRescaleIntensityImageFilterIVF22IVF22_Superclass_cast: Any

def itkVectorRescaleIntensityImageFilterIVF23IVF23_Superclass_New(): ...

class itkVectorRescaleIntensityImageFilterIVF23IVF23_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIVF23IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorRescaleIntensityImageFilterIVF23IVF23_Superclass___New_orig__: Any
itkVectorRescaleIntensityImageFilterIVF23IVF23_Superclass_cast: Any

def itkVectorRescaleIntensityImageFilterIVF32IVF32_Superclass_New(): ...

class itkVectorRescaleIntensityImageFilterIVF32IVF32_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIVF32IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorRescaleIntensityImageFilterIVF32IVF32_Superclass___New_orig__: Any
itkVectorRescaleIntensityImageFilterIVF32IVF32_Superclass_cast: Any

def itkVectorRescaleIntensityImageFilterIVF33IVF33_Superclass_New(): ...

class itkVectorRescaleIntensityImageFilterIVF33IVF33_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIVF33IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorRescaleIntensityImageFilterIVF33IVF33_Superclass___New_orig__: Any
itkVectorRescaleIntensityImageFilterIVF33IVF33_Superclass_cast: Any

def itkVectorRescaleIntensityImageFilterIVF42IVF42_Superclass_New(): ...

class itkVectorRescaleIntensityImageFilterIVF42IVF42_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIVF42IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorRescaleIntensityImageFilterIVF42IVF42_Superclass___New_orig__: Any
itkVectorRescaleIntensityImageFilterIVF42IVF42_Superclass_cast: Any

def itkVectorRescaleIntensityImageFilterIVF43IVF43_Superclass_New(): ...

class itkVectorRescaleIntensityImageFilterIVF43IVF43_Superclass(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIVF43IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetFunctor: Any = ...
    SetFunctor: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorRescaleIntensityImageFilterIVF43IVF43_Superclass___New_orig__: Any
itkVectorRescaleIntensityImageFilterIVF43IVF43_Superclass_cast: Any

def itkVectorRescaleIntensityImageFilterIVF22IVF22_New(): ...

class itkVectorRescaleIntensityImageFilterIVF22IVF22(itkVectorRescaleIntensityImageFilterIVF22IVF22_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMaximumMagnitude: Any = ...
    GetOutputMaximumMagnitude: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMaximumMagnitude: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorRescaleIntensityImageFilterIVF22IVF22___New_orig__: Any
itkVectorRescaleIntensityImageFilterIVF22IVF22_cast: Any

def itkVectorRescaleIntensityImageFilterIVF23IVF23_New(): ...

class itkVectorRescaleIntensityImageFilterIVF23IVF23(itkVectorRescaleIntensityImageFilterIVF23IVF23_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMaximumMagnitude: Any = ...
    GetOutputMaximumMagnitude: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMaximumMagnitude: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorRescaleIntensityImageFilterIVF23IVF23___New_orig__: Any
itkVectorRescaleIntensityImageFilterIVF23IVF23_cast: Any

def itkVectorRescaleIntensityImageFilterIVF32IVF32_New(): ...

class itkVectorRescaleIntensityImageFilterIVF32IVF32(itkVectorRescaleIntensityImageFilterIVF32IVF32_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMaximumMagnitude: Any = ...
    GetOutputMaximumMagnitude: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMaximumMagnitude: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorRescaleIntensityImageFilterIVF32IVF32___New_orig__: Any
itkVectorRescaleIntensityImageFilterIVF32IVF32_cast: Any

def itkVectorRescaleIntensityImageFilterIVF33IVF33_New(): ...

class itkVectorRescaleIntensityImageFilterIVF33IVF33(itkVectorRescaleIntensityImageFilterIVF33IVF33_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMaximumMagnitude: Any = ...
    GetOutputMaximumMagnitude: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMaximumMagnitude: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorRescaleIntensityImageFilterIVF33IVF33___New_orig__: Any
itkVectorRescaleIntensityImageFilterIVF33IVF33_cast: Any

def itkVectorRescaleIntensityImageFilterIVF42IVF42_New(): ...

class itkVectorRescaleIntensityImageFilterIVF42IVF42(itkVectorRescaleIntensityImageFilterIVF42IVF42_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMaximumMagnitude: Any = ...
    GetOutputMaximumMagnitude: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMaximumMagnitude: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorRescaleIntensityImageFilterIVF42IVF42___New_orig__: Any
itkVectorRescaleIntensityImageFilterIVF42IVF42_cast: Any

def itkVectorRescaleIntensityImageFilterIVF43IVF43_New(): ...

class itkVectorRescaleIntensityImageFilterIVF43IVF43(itkVectorRescaleIntensityImageFilterIVF43IVF43_Superclass):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetOutputMaximumMagnitude: Any = ...
    GetOutputMaximumMagnitude: Any = ...
    GetScale: Any = ...
    GetShift: Any = ...
    GetInputMaximumMagnitude: Any = ...
    BeforeThreadedGenerateData: Any = ...
    PrintSelf: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorRescaleIntensityImageFilterIVF43IVF43___New_orig__: Any
itkVectorRescaleIntensityImageFilterIVF43IVF43_cast: Any

def vector_rescale_intensity_image_filter(*args: Any, **kwargs: Any): ...
def vector_rescale_intensity_image_filter_init_docstring() -> None: ...
def unary_functor_image_filter(*args: Any, **kwargs: Any): ...
def unary_functor_image_filter_init_docstring() -> None: ...
