import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkVectorGradientAnisotropicDiffusionImageFilterICVF22ICVF22_New(): ...

class itkVectorGradientAnisotropicDiffusionImageFilterICVF22ICVF22(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterICVF22ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorGradientAnisotropicDiffusionImageFilterICVF22ICVF22___New_orig__: Any
itkVectorGradientAnisotropicDiffusionImageFilterICVF22ICVF22_cast: Any

def itkVectorGradientAnisotropicDiffusionImageFilterICVF23ICVF23_New(): ...

class itkVectorGradientAnisotropicDiffusionImageFilterICVF23ICVF23(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterICVF23ICVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorGradientAnisotropicDiffusionImageFilterICVF23ICVF23___New_orig__: Any
itkVectorGradientAnisotropicDiffusionImageFilterICVF23ICVF23_cast: Any

def itkVectorGradientAnisotropicDiffusionImageFilterICVF32ICVF32_New(): ...

class itkVectorGradientAnisotropicDiffusionImageFilterICVF32ICVF32(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterICVF32ICVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorGradientAnisotropicDiffusionImageFilterICVF32ICVF32___New_orig__: Any
itkVectorGradientAnisotropicDiffusionImageFilterICVF32ICVF32_cast: Any

def itkVectorGradientAnisotropicDiffusionImageFilterICVF33ICVF33_New(): ...

class itkVectorGradientAnisotropicDiffusionImageFilterICVF33ICVF33(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterICVF33ICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorGradientAnisotropicDiffusionImageFilterICVF33ICVF33___New_orig__: Any
itkVectorGradientAnisotropicDiffusionImageFilterICVF33ICVF33_cast: Any

def itkVectorGradientAnisotropicDiffusionImageFilterICVF42ICVF42_New(): ...

class itkVectorGradientAnisotropicDiffusionImageFilterICVF42ICVF42(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterICVF42ICVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorGradientAnisotropicDiffusionImageFilterICVF42ICVF42___New_orig__: Any
itkVectorGradientAnisotropicDiffusionImageFilterICVF42ICVF42_cast: Any

def itkVectorGradientAnisotropicDiffusionImageFilterICVF43ICVF43_New(): ...

class itkVectorGradientAnisotropicDiffusionImageFilterICVF43ICVF43(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterICVF43ICVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorGradientAnisotropicDiffusionImageFilterICVF43ICVF43___New_orig__: Any
itkVectorGradientAnisotropicDiffusionImageFilterICVF43ICVF43_cast: Any

def itkVectorGradientAnisotropicDiffusionImageFilterIVF22IVF22_New(): ...

class itkVectorGradientAnisotropicDiffusionImageFilterIVF22IVF22(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterIVF22IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorGradientAnisotropicDiffusionImageFilterIVF22IVF22___New_orig__: Any
itkVectorGradientAnisotropicDiffusionImageFilterIVF22IVF22_cast: Any

def itkVectorGradientAnisotropicDiffusionImageFilterIVF23IVF23_New(): ...

class itkVectorGradientAnisotropicDiffusionImageFilterIVF23IVF23(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterIVF23IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorGradientAnisotropicDiffusionImageFilterIVF23IVF23___New_orig__: Any
itkVectorGradientAnisotropicDiffusionImageFilterIVF23IVF23_cast: Any

def itkVectorGradientAnisotropicDiffusionImageFilterIVF32IVF32_New(): ...

class itkVectorGradientAnisotropicDiffusionImageFilterIVF32IVF32(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterIVF32IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorGradientAnisotropicDiffusionImageFilterIVF32IVF32___New_orig__: Any
itkVectorGradientAnisotropicDiffusionImageFilterIVF32IVF32_cast: Any

def itkVectorGradientAnisotropicDiffusionImageFilterIVF33IVF33_New(): ...

class itkVectorGradientAnisotropicDiffusionImageFilterIVF33IVF33(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterIVF33IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorGradientAnisotropicDiffusionImageFilterIVF33IVF33___New_orig__: Any
itkVectorGradientAnisotropicDiffusionImageFilterIVF33IVF33_cast: Any

def itkVectorGradientAnisotropicDiffusionImageFilterIVF42IVF42_New(): ...

class itkVectorGradientAnisotropicDiffusionImageFilterIVF42IVF42(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterIVF42IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorGradientAnisotropicDiffusionImageFilterIVF42IVF42___New_orig__: Any
itkVectorGradientAnisotropicDiffusionImageFilterIVF42IVF42_cast: Any

def itkVectorGradientAnisotropicDiffusionImageFilterIVF43IVF43_New(): ...

class itkVectorGradientAnisotropicDiffusionImageFilterIVF43IVF43(itk.itkAnisotropicDiffusionImageFilterPython.itkAnisotropicDiffusionImageFilterIVF43IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputHasNumericTraitsCheck: Any = ...
    OutputHasNumericTraitsCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorGradientAnisotropicDiffusionImageFilterIVF43IVF43___New_orig__: Any
itkVectorGradientAnisotropicDiffusionImageFilterIVF43IVF43_cast: Any

def vector_gradient_anisotropic_diffusion_image_filter(*args: Any, **kwargs: Any): ...
def vector_gradient_anisotropic_diffusion_image_filter_init_docstring() -> None: ...
