import itk.itkArrayPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkVnlHalfHermitianToRealInverseFFTImageFilterICF2IF2_New(): ...

class itkVnlHalfHermitianToRealInverseFFTImageFilterICF2IF2(itk.itkHalfHermitianToRealInverseFFTImageFilterPython.itkHalfHermitianToRealInverseFFTImageFilterICF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PixelUnsignedIntDivisionOperatorsCheck: Any = ...
    ImageDimensionsMatchCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVnlHalfHermitianToRealInverseFFTImageFilterICF2IF2___New_orig__: Any
itkVnlHalfHermitianToRealInverseFFTImageFilterICF2IF2_cast: Any

def itkVnlHalfHermitianToRealInverseFFTImageFilterICF3IF3_New(): ...

class itkVnlHalfHermitianToRealInverseFFTImageFilterICF3IF3(itk.itkHalfHermitianToRealInverseFFTImageFilterPython.itkHalfHermitianToRealInverseFFTImageFilterICF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    PixelUnsignedIntDivisionOperatorsCheck: Any = ...
    ImageDimensionsMatchCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVnlHalfHermitianToRealInverseFFTImageFilterICF3IF3___New_orig__: Any
itkVnlHalfHermitianToRealInverseFFTImageFilterICF3IF3_cast: Any

def vnl_half_hermitian_to_real_inverse_fft_image_filter(*args: Any, **kwargs: Any): ...
def vnl_half_hermitian_to_real_inverse_fft_image_filter_init_docstring() -> None: ...
