import itk.itkOffsetPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkDataObjectDecoratorVCUCD_New(): ...

class itkDataObjectDecoratorVCUCD(itk.ITKCommonBasePython.itkDataObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    Set: Any = ...
    Get: Any = ...
    GetModifiable: Any = ...
    Graft: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkDataObjectDecoratorVCUCD___New_orig__: Any
itkDataObjectDecoratorVCUCD_cast: Any

def itkVectorContainerUCD_New(): ...

class itkVectorContainerUCD(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerUCD___New_orig__: Any
itkVectorContainerUCD_cast: Any

def itkVectorContainerUCF_New(): ...

class itkVectorContainerUCF(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerUCF___New_orig__: Any
itkVectorContainerUCF_cast: Any

def itkVectorContainerUCO2_New(): ...

class itkVectorContainerUCO2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerUCO2___New_orig__: Any
itkVectorContainerUCO2_cast: Any

def itkVectorContainerUCO3_New(): ...

class itkVectorContainerUCO3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerUCO3___New_orig__: Any
itkVectorContainerUCO3_cast: Any

def itkVectorContainerUCSS_New(): ...

class itkVectorContainerUCSS(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerUCSS___New_orig__: Any
itkVectorContainerUCSS_cast: Any

def itkVectorContainerUCUC_New(): ...

class itkVectorContainerUCUC(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerUCUC___New_orig__: Any
itkVectorContainerUCUC_cast: Any

def itkVectorContainerUCUI_New(): ...

class itkVectorContainerUCUI(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerUCUI___New_orig__: Any
itkVectorContainerUCUI_cast: Any

def itkVectorContainerUCUL_New(): ...

class itkVectorContainerUCUL(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerUCUL___New_orig__: Any
itkVectorContainerUCUL_cast: Any

def itkVectorContainerUICID2_New(): ...

class itkVectorContainerUICID2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerUICID2___New_orig__: Any
itkVectorContainerUICID2_cast: Any

def itkVectorContainerUICID3_New(): ...

class itkVectorContainerUICID3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerUICID3___New_orig__: Any
itkVectorContainerUICID3_cast: Any

def itkVectorContainerUIUC_New(): ...

class itkVectorContainerUIUC(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerUIUC___New_orig__: Any
itkVectorContainerUIUC_cast: Any

def itkVectorContainerUIUI_New(): ...

class itkVectorContainerUIUI(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerUIUI___New_orig__: Any
itkVectorContainerUIUI_cast: Any

def itkVectorContainerUIUL_New(): ...

class itkVectorContainerUIUL(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerUIUL___New_orig__: Any
itkVectorContainerUIUL_cast: Any

def itkVectorContainerUIVUC1_New(): ...

class itkVectorContainerUIVUC1(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerUIVUC1___New_orig__: Any
itkVectorContainerUIVUC1_cast: Any

def itkVectorContainerULD_New(): ...

class itkVectorContainerULD(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerULD___New_orig__: Any
itkVectorContainerULD_cast: Any

def itkVectorContainerULF_New(): ...

class itkVectorContainerULF(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerULF___New_orig__: Any
itkVectorContainerULF_cast: Any

def itkVectorContainerULMD22_New(): ...

class itkVectorContainerULMD22(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerULMD22___New_orig__: Any
itkVectorContainerULMD22_cast: Any

def itkVectorContainerULMD33_New(): ...

class itkVectorContainerULMD33(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerULMD33___New_orig__: Any
itkVectorContainerULMD33_cast: Any

def itkVectorContainerULMF22_New(): ...

class itkVectorContainerULMF22(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerULMF22___New_orig__: Any
itkVectorContainerULMF22_cast: Any

def itkVectorContainerULMF33_New(): ...

class itkVectorContainerULMF33(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerULMF33___New_orig__: Any
itkVectorContainerULMF33_cast: Any

def itkVectorContainerULPD2_New(): ...

class itkVectorContainerULPD2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerULPD2___New_orig__: Any
itkVectorContainerULPD2_cast: Any

def itkVectorContainerULPD3_New(): ...

class itkVectorContainerULPD3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerULPD3___New_orig__: Any
itkVectorContainerULPD3_cast: Any

def itkVectorContainerULPF2_New(): ...

class itkVectorContainerULPF2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerULPF2___New_orig__: Any
itkVectorContainerULPF2_cast: Any

def itkVectorContainerULPF3_New(): ...

class itkVectorContainerULPF3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerULPF3___New_orig__: Any
itkVectorContainerULPF3_cast: Any

def itkVectorContainerULSS_New(): ...

class itkVectorContainerULSS(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerULSS___New_orig__: Any
itkVectorContainerULSS_cast: Any

def itkVectorContainerULSUL_New(): ...

class itkVectorContainerULSUL(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerULSUL___New_orig__: Any
itkVectorContainerULSUL_cast: Any

def itkVectorContainerULUC_New(): ...

class itkVectorContainerULUC(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerULUC___New_orig__: Any
itkVectorContainerULUC_cast: Any

def itkVectorContainerULUI_New(): ...

class itkVectorContainerULUI(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerULUI___New_orig__: Any
itkVectorContainerULUI_cast: Any

def itkVectorContainerULUL_New(): ...

class itkVectorContainerULUL(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerULUL___New_orig__: Any
itkVectorContainerULUL_cast: Any

def itkVectorContainerULVD2_New(): ...

class itkVectorContainerULVD2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerULVD2___New_orig__: Any
itkVectorContainerULVD2_cast: Any

def itkVectorContainerULVD3_New(): ...

class itkVectorContainerULVD3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerULVD3___New_orig__: Any
itkVectorContainerULVD3_cast: Any

def itkVectorContainerULVF2_New(): ...

class itkVectorContainerULVF2(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerULVF2___New_orig__: Any
itkVectorContainerULVF2_cast: Any

def itkVectorContainerULVF3_New(): ...

class itkVectorContainerULVF3(itk.ITKCommonBasePython.itkObject):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    CastToSTLContainer: Any = ...
    CastToSTLConstContainer: Any = ...
    ElementAt: Any = ...
    CreateElementAt: Any = ...
    GetElement: Any = ...
    SetElement: Any = ...
    InsertElement: Any = ...
    IndexExists: Any = ...
    GetElementIfIndexExists: Any = ...
    CreateIndex: Any = ...
    DeleteIndex: Any = ...
    Size: Any = ...
    Reserve: Any = ...
    Squeeze: Any = ...
    Initialize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVectorContainerULVF3___New_orig__: Any
itkVectorContainerULVF3_cast: Any
