import itk.stdcomplexPython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkVTKImageIO_New(): ...

class itkVTKImageIO(itk.ITKIOImageBaseBasePython.itkStreamingImageIOBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetHeaderSize: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageIO___New_orig__: Any
itkVTKImageIO_cast: Any

def itkVTKImageIOFactory_New(): ...

class itkVTKImageIOFactory(itk.ITKCommonBasePython.itkObjectFactoryBase):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    RegisterOneFactory: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkVTKImageIOFactory___New_orig__: Any
itkVTKImageIOFactory_RegisterOneFactory: Any
itkVTKImageIOFactory_cast: Any
