import itk.itkMathematicalMorphologyEnumsPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkWhiteTopHatImageFilterIF2IF2SE2_New(): ...

class itkWhiteTopHatImageFilterIF2IF2SE2(itk.itkFlatStructuringElementPython.itkKernelImageFilterIF2IF2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetForceAlgorithm: Any = ...
    GetForceAlgorithm: Any = ...
    ForceAlgorithmOn: Any = ...
    ForceAlgorithmOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWhiteTopHatImageFilterIF2IF2SE2___New_orig__: Any
itkWhiteTopHatImageFilterIF2IF2SE2_cast: Any

def itkWhiteTopHatImageFilterIF3IF3SE3_New(): ...

class itkWhiteTopHatImageFilterIF3IF3SE3(itk.itkFlatStructuringElementPython.itkKernelImageFilterIF3IF3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetForceAlgorithm: Any = ...
    GetForceAlgorithm: Any = ...
    ForceAlgorithmOn: Any = ...
    ForceAlgorithmOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWhiteTopHatImageFilterIF3IF3SE3___New_orig__: Any
itkWhiteTopHatImageFilterIF3IF3SE3_cast: Any

def itkWhiteTopHatImageFilterISS2ISS2SE2_New(): ...

class itkWhiteTopHatImageFilterISS2ISS2SE2(itk.itkFlatStructuringElementPython.itkKernelImageFilterISS2ISS2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetForceAlgorithm: Any = ...
    GetForceAlgorithm: Any = ...
    ForceAlgorithmOn: Any = ...
    ForceAlgorithmOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWhiteTopHatImageFilterISS2ISS2SE2___New_orig__: Any
itkWhiteTopHatImageFilterISS2ISS2SE2_cast: Any

def itkWhiteTopHatImageFilterISS3ISS3SE3_New(): ...

class itkWhiteTopHatImageFilterISS3ISS3SE3(itk.itkFlatStructuringElementPython.itkKernelImageFilterISS3ISS3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetForceAlgorithm: Any = ...
    GetForceAlgorithm: Any = ...
    ForceAlgorithmOn: Any = ...
    ForceAlgorithmOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWhiteTopHatImageFilterISS3ISS3SE3___New_orig__: Any
itkWhiteTopHatImageFilterISS3ISS3SE3_cast: Any

def itkWhiteTopHatImageFilterIUC2IUC2SE2_New(): ...

class itkWhiteTopHatImageFilterIUC2IUC2SE2(itk.itkFlatStructuringElementPython.itkKernelImageFilterIUC2IUC2SE2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetForceAlgorithm: Any = ...
    GetForceAlgorithm: Any = ...
    ForceAlgorithmOn: Any = ...
    ForceAlgorithmOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWhiteTopHatImageFilterIUC2IUC2SE2___New_orig__: Any
itkWhiteTopHatImageFilterIUC2IUC2SE2_cast: Any

def itkWhiteTopHatImageFilterIUC3IUC3SE3_New(): ...

class itkWhiteTopHatImageFilterIUC3IUC3SE3(itk.itkFlatStructuringElementPython.itkKernelImageFilterIUC3IUC3SE3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetSafeBorder: Any = ...
    GetSafeBorder: Any = ...
    SafeBorderOn: Any = ...
    SafeBorderOff: Any = ...
    SetAlgorithm: Any = ...
    GetAlgorithm: Any = ...
    SetForceAlgorithm: Any = ...
    GetForceAlgorithm: Any = ...
    ForceAlgorithmOn: Any = ...
    ForceAlgorithmOff: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWhiteTopHatImageFilterIUC3IUC3SE3___New_orig__: Any
itkWhiteTopHatImageFilterIUC3IUC3SE3_cast: Any

def white_top_hat_image_filter(*args: Any, **kwargs: Any): ...
def white_top_hat_image_filter_init_docstring() -> None: ...
