import itk.itkImageToImageFilterAPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkWrapPadImageFilterICF2ICF2_New(): ...

class itkWrapPadImageFilterICF2ICF2(itk.itkPadImageFilterPython.itkPadImageFilterICF2ICF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterICF2ICF2___New_orig__: Any
itkWrapPadImageFilterICF2ICF2_cast: Any

def itkWrapPadImageFilterICF3ICF3_New(): ...

class itkWrapPadImageFilterICF3ICF3(itk.itkPadImageFilterPython.itkPadImageFilterICF3ICF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterICF3ICF3___New_orig__: Any
itkWrapPadImageFilterICF3ICF3_cast: Any

def itkWrapPadImageFilterICVF22ICVF22_New(): ...

class itkWrapPadImageFilterICVF22ICVF22(itk.itkPadImageFilterPython.itkPadImageFilterICVF22ICVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterICVF22ICVF22___New_orig__: Any
itkWrapPadImageFilterICVF22ICVF22_cast: Any

def itkWrapPadImageFilterICVF23ICVF23_New(): ...

class itkWrapPadImageFilterICVF23ICVF23(itk.itkPadImageFilterPython.itkPadImageFilterICVF23ICVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterICVF23ICVF23___New_orig__: Any
itkWrapPadImageFilterICVF23ICVF23_cast: Any

def itkWrapPadImageFilterICVF32ICVF32_New(): ...

class itkWrapPadImageFilterICVF32ICVF32(itk.itkPadImageFilterPython.itkPadImageFilterICVF32ICVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterICVF32ICVF32___New_orig__: Any
itkWrapPadImageFilterICVF32ICVF32_cast: Any

def itkWrapPadImageFilterICVF33ICVF33_New(): ...

class itkWrapPadImageFilterICVF33ICVF33(itk.itkPadImageFilterPython.itkPadImageFilterICVF33ICVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterICVF33ICVF33___New_orig__: Any
itkWrapPadImageFilterICVF33ICVF33_cast: Any

def itkWrapPadImageFilterICVF42ICVF42_New(): ...

class itkWrapPadImageFilterICVF42ICVF42(itk.itkPadImageFilterPython.itkPadImageFilterICVF42ICVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterICVF42ICVF42___New_orig__: Any
itkWrapPadImageFilterICVF42ICVF42_cast: Any

def itkWrapPadImageFilterICVF43ICVF43_New(): ...

class itkWrapPadImageFilterICVF43ICVF43(itk.itkPadImageFilterPython.itkPadImageFilterICVF43ICVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterICVF43ICVF43___New_orig__: Any
itkWrapPadImageFilterICVF43ICVF43_cast: Any

def itkWrapPadImageFilterIF2IF2_New(): ...

class itkWrapPadImageFilterIF2IF2(itk.itkPadImageFilterPython.itkPadImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterIF2IF2___New_orig__: Any
itkWrapPadImageFilterIF2IF2_cast: Any

def itkWrapPadImageFilterIF3IF3_New(): ...

class itkWrapPadImageFilterIF3IF3(itk.itkPadImageFilterPython.itkPadImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterIF3IF3___New_orig__: Any
itkWrapPadImageFilterIF3IF3_cast: Any

def itkWrapPadImageFilterIRGBAUC2IRGBAUC2_New(): ...

class itkWrapPadImageFilterIRGBAUC2IRGBAUC2(itk.itkPadImageFilterPython.itkPadImageFilterIRGBAUC2IRGBAUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterIRGBAUC2IRGBAUC2___New_orig__: Any
itkWrapPadImageFilterIRGBAUC2IRGBAUC2_cast: Any

def itkWrapPadImageFilterIRGBAUC3IRGBAUC3_New(): ...

class itkWrapPadImageFilterIRGBAUC3IRGBAUC3(itk.itkPadImageFilterPython.itkPadImageFilterIRGBAUC3IRGBAUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterIRGBAUC3IRGBAUC3___New_orig__: Any
itkWrapPadImageFilterIRGBAUC3IRGBAUC3_cast: Any

def itkWrapPadImageFilterIRGBUC2IRGBUC2_New(): ...

class itkWrapPadImageFilterIRGBUC2IRGBUC2(itk.itkPadImageFilterPython.itkPadImageFilterIRGBUC2IRGBUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterIRGBUC2IRGBUC2___New_orig__: Any
itkWrapPadImageFilterIRGBUC2IRGBUC2_cast: Any

def itkWrapPadImageFilterIRGBUC3IRGBUC3_New(): ...

class itkWrapPadImageFilterIRGBUC3IRGBUC3(itk.itkPadImageFilterPython.itkPadImageFilterIRGBUC3IRGBUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterIRGBUC3IRGBUC3___New_orig__: Any
itkWrapPadImageFilterIRGBUC3IRGBUC3_cast: Any

def itkWrapPadImageFilterISS2ISS2_New(): ...

class itkWrapPadImageFilterISS2ISS2(itk.itkPadImageFilterPython.itkPadImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterISS2ISS2___New_orig__: Any
itkWrapPadImageFilterISS2ISS2_cast: Any

def itkWrapPadImageFilterISS3ISS3_New(): ...

class itkWrapPadImageFilterISS3ISS3(itk.itkPadImageFilterPython.itkPadImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterISS3ISS3___New_orig__: Any
itkWrapPadImageFilterISS3ISS3_cast: Any

def itkWrapPadImageFilterIUC2IUC2_New(): ...

class itkWrapPadImageFilterIUC2IUC2(itk.itkPadImageFilterPython.itkPadImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterIUC2IUC2___New_orig__: Any
itkWrapPadImageFilterIUC2IUC2_cast: Any

def itkWrapPadImageFilterIUC3IUC3_New(): ...

class itkWrapPadImageFilterIUC3IUC3(itk.itkPadImageFilterPython.itkPadImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterIUC3IUC3___New_orig__: Any
itkWrapPadImageFilterIUC3IUC3_cast: Any

def itkWrapPadImageFilterIVF22IVF22_New(): ...

class itkWrapPadImageFilterIVF22IVF22(itk.itkPadImageFilterPython.itkPadImageFilterIVF22IVF22):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterIVF22IVF22___New_orig__: Any
itkWrapPadImageFilterIVF22IVF22_cast: Any

def itkWrapPadImageFilterIVF23IVF23_New(): ...

class itkWrapPadImageFilterIVF23IVF23(itk.itkPadImageFilterPython.itkPadImageFilterIVF23IVF23):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterIVF23IVF23___New_orig__: Any
itkWrapPadImageFilterIVF23IVF23_cast: Any

def itkWrapPadImageFilterIVF32IVF32_New(): ...

class itkWrapPadImageFilterIVF32IVF32(itk.itkPadImageFilterPython.itkPadImageFilterIVF32IVF32):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterIVF32IVF32___New_orig__: Any
itkWrapPadImageFilterIVF32IVF32_cast: Any

def itkWrapPadImageFilterIVF33IVF33_New(): ...

class itkWrapPadImageFilterIVF33IVF33(itk.itkPadImageFilterPython.itkPadImageFilterIVF33IVF33):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterIVF33IVF33___New_orig__: Any
itkWrapPadImageFilterIVF33IVF33_cast: Any

def itkWrapPadImageFilterIVF42IVF42_New(): ...

class itkWrapPadImageFilterIVF42IVF42(itk.itkPadImageFilterPython.itkPadImageFilterIVF42IVF42):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterIVF42IVF42___New_orig__: Any
itkWrapPadImageFilterIVF42IVF42_cast: Any

def itkWrapPadImageFilterIVF43IVF43_New(): ...

class itkWrapPadImageFilterIVF43IVF43(itk.itkPadImageFilterPython.itkPadImageFilterIVF43IVF43):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    InputConvertibleToOutputCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWrapPadImageFilterIVF43IVF43___New_orig__: Any
itkWrapPadImageFilterIVF43IVF43_cast: Any

def wrap_pad_image_filter(*args: Any, **kwargs: Any): ...
def wrap_pad_image_filter_init_docstring() -> None: ...
