import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkWienerDeconvolutionImageFilterIF2IF2_New(): ...

class itkWienerDeconvolutionImageFilterIF2IF2(itk.itkInverseDeconvolutionImageFilterPython.itkInverseDeconvolutionImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNoiseVariance: Any = ...
    GetNoiseVariance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWienerDeconvolutionImageFilterIF2IF2___New_orig__: Any
itkWienerDeconvolutionImageFilterIF2IF2_cast: Any

def itkWienerDeconvolutionImageFilterIF3IF3_New(): ...

class itkWienerDeconvolutionImageFilterIF3IF3(itk.itkInverseDeconvolutionImageFilterPython.itkInverseDeconvolutionImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNoiseVariance: Any = ...
    GetNoiseVariance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWienerDeconvolutionImageFilterIF3IF3___New_orig__: Any
itkWienerDeconvolutionImageFilterIF3IF3_cast: Any

def itkWienerDeconvolutionImageFilterISS2ISS2_New(): ...

class itkWienerDeconvolutionImageFilterISS2ISS2(itk.itkInverseDeconvolutionImageFilterPython.itkInverseDeconvolutionImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNoiseVariance: Any = ...
    GetNoiseVariance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWienerDeconvolutionImageFilterISS2ISS2___New_orig__: Any
itkWienerDeconvolutionImageFilterISS2ISS2_cast: Any

def itkWienerDeconvolutionImageFilterISS3ISS3_New(): ...

class itkWienerDeconvolutionImageFilterISS3ISS3(itk.itkInverseDeconvolutionImageFilterPython.itkInverseDeconvolutionImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNoiseVariance: Any = ...
    GetNoiseVariance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWienerDeconvolutionImageFilterISS3ISS3___New_orig__: Any
itkWienerDeconvolutionImageFilterISS3ISS3_cast: Any

def itkWienerDeconvolutionImageFilterIUC2IUC2_New(): ...

class itkWienerDeconvolutionImageFilterIUC2IUC2(itk.itkInverseDeconvolutionImageFilterPython.itkInverseDeconvolutionImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNoiseVariance: Any = ...
    GetNoiseVariance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWienerDeconvolutionImageFilterIUC2IUC2___New_orig__: Any
itkWienerDeconvolutionImageFilterIUC2IUC2_cast: Any

def itkWienerDeconvolutionImageFilterIUC3IUC3_New(): ...

class itkWienerDeconvolutionImageFilterIUC3IUC3(itk.itkInverseDeconvolutionImageFilterPython.itkInverseDeconvolutionImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    SetNoiseVariance: Any = ...
    GetNoiseVariance: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkWienerDeconvolutionImageFilterIUC3IUC3___New_orig__: Any
itkWienerDeconvolutionImageFilterIUC3IUC3_cast: Any

def wiener_deconvolution_image_filter(*args: Any, **kwargs: Any): ...
def wiener_deconvolution_image_filter_init_docstring() -> None: ...
