import itk.itkImageSourceCommonPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkYenThresholdImageFilterIF2ISS2_New(): ...

class itkYenThresholdImageFilterIF2ISS2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkYenThresholdImageFilterIF2ISS2___New_orig__: Any
itkYenThresholdImageFilterIF2ISS2_cast: Any

def itkYenThresholdImageFilterIF2IUC2_New(): ...

class itkYenThresholdImageFilterIF2IUC2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkYenThresholdImageFilterIF2IUC2___New_orig__: Any
itkYenThresholdImageFilterIF2IUC2_cast: Any

def itkYenThresholdImageFilterIF3ISS3_New(): ...

class itkYenThresholdImageFilterIF3ISS3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkYenThresholdImageFilterIF3ISS3___New_orig__: Any
itkYenThresholdImageFilterIF3ISS3_cast: Any

def itkYenThresholdImageFilterIF3IUC3_New(): ...

class itkYenThresholdImageFilterIF3IUC3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIF3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkYenThresholdImageFilterIF3IUC3___New_orig__: Any
itkYenThresholdImageFilterIF3IUC3_cast: Any

def itkYenThresholdImageFilterISS2ISS2_New(): ...

class itkYenThresholdImageFilterISS2ISS2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkYenThresholdImageFilterISS2ISS2___New_orig__: Any
itkYenThresholdImageFilterISS2ISS2_cast: Any

def itkYenThresholdImageFilterISS2IUC2_New(): ...

class itkYenThresholdImageFilterISS2IUC2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkYenThresholdImageFilterISS2IUC2___New_orig__: Any
itkYenThresholdImageFilterISS2IUC2_cast: Any

def itkYenThresholdImageFilterISS3ISS3_New(): ...

class itkYenThresholdImageFilterISS3ISS3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkYenThresholdImageFilterISS3ISS3___New_orig__: Any
itkYenThresholdImageFilterISS3ISS3_cast: Any

def itkYenThresholdImageFilterISS3IUC3_New(): ...

class itkYenThresholdImageFilterISS3IUC3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterISS3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkYenThresholdImageFilterISS3IUC3___New_orig__: Any
itkYenThresholdImageFilterISS3IUC3_cast: Any

def itkYenThresholdImageFilterIUC2ISS2_New(): ...

class itkYenThresholdImageFilterIUC2ISS2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkYenThresholdImageFilterIUC2ISS2___New_orig__: Any
itkYenThresholdImageFilterIUC2ISS2_cast: Any

def itkYenThresholdImageFilterIUC2IUC2_New(): ...

class itkYenThresholdImageFilterIUC2IUC2(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC2IUC2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkYenThresholdImageFilterIUC2IUC2___New_orig__: Any
itkYenThresholdImageFilterIUC2IUC2_cast: Any

def itkYenThresholdImageFilterIUC3ISS3_New(): ...

class itkYenThresholdImageFilterIUC3ISS3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkYenThresholdImageFilterIUC3ISS3___New_orig__: Any
itkYenThresholdImageFilterIUC3ISS3_cast: Any

def itkYenThresholdImageFilterIUC3IUC3_New(): ...

class itkYenThresholdImageFilterIUC3IUC3(itk.itkHistogramThresholdImageFilterPython.itkHistogramThresholdImageFilterIUC3IUC3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkYenThresholdImageFilterIUC3IUC3___New_orig__: Any
itkYenThresholdImageFilterIUC3IUC3_cast: Any

def yen_threshold_image_filter(*args: Any, **kwargs: Any): ...
def yen_threshold_image_filter_init_docstring() -> None: ...
