import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkZeroCrossingBasedEdgeDetectionImageFilterIF2IF2_New(): ...

class itkZeroCrossingBasedEdgeDetectionImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetVariance: Any = ...
    GetMaximumError: Any = ...
    GetBackgroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetForegroundValue: Any = ...
    SetVariance: Any = ...
    SetMaximumError: Any = ...
    OutputEqualityComparableCheck: Any = ...
    SameDimensionCheck: Any = ...
    SameTypeCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    PixelTypeIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkZeroCrossingBasedEdgeDetectionImageFilterIF2IF2___New_orig__: Any
itkZeroCrossingBasedEdgeDetectionImageFilterIF2IF2_cast: Any

def itkZeroCrossingBasedEdgeDetectionImageFilterIF3IF3_New(): ...

class itkZeroCrossingBasedEdgeDetectionImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GetVariance: Any = ...
    GetMaximumError: Any = ...
    GetBackgroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetForegroundValue: Any = ...
    SetVariance: Any = ...
    SetMaximumError: Any = ...
    OutputEqualityComparableCheck: Any = ...
    SameDimensionCheck: Any = ...
    SameTypeCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    PixelTypeIsFloatingPointCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkZeroCrossingBasedEdgeDetectionImageFilterIF3IF3___New_orig__: Any
itkZeroCrossingBasedEdgeDetectionImageFilterIF3IF3_cast: Any

def zero_crossing_based_edge_detection_image_filter(*args: Any, **kwargs: Any): ...
def zero_crossing_based_edge_detection_image_filter_init_docstring() -> None: ...
