import itk.itkVariableLengthVectorPython
from itk.support import itkHelpers as itkHelpers
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

def itkZeroCrossingImageFilterIF2IF2_New(): ...

class itkZeroCrossingImageFilterIF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF2IF2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    OutputEqualityComparableCheck: Any = ...
    SameDimensionCheck: Any = ...
    InputComparableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkZeroCrossingImageFilterIF2IF2___New_orig__: Any
itkZeroCrossingImageFilterIF2IF2_cast: Any

def itkZeroCrossingImageFilterIF3IF3_New(): ...

class itkZeroCrossingImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    OutputEqualityComparableCheck: Any = ...
    SameDimensionCheck: Any = ...
    InputComparableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkZeroCrossingImageFilterIF3IF3___New_orig__: Any
itkZeroCrossingImageFilterIF3IF3_cast: Any

def itkZeroCrossingImageFilterISS2ISS2_New(): ...

class itkZeroCrossingImageFilterISS2ISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    OutputEqualityComparableCheck: Any = ...
    SameDimensionCheck: Any = ...
    InputComparableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkZeroCrossingImageFilterISS2ISS2___New_orig__: Any
itkZeroCrossingImageFilterISS2ISS2_cast: Any

def itkZeroCrossingImageFilterISS3ISS3_New(): ...

class itkZeroCrossingImageFilterISS3ISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __New_orig__: Any = ...
    Clone: Any = ...
    GenerateInputRequestedRegion: Any = ...
    SetForegroundValue: Any = ...
    GetForegroundValue: Any = ...
    SetBackgroundValue: Any = ...
    GetBackgroundValue: Any = ...
    OutputEqualityComparableCheck: Any = ...
    SameDimensionCheck: Any = ...
    InputComparableCheck: Any = ...
    OutputOStreamWritableCheck: Any = ...
    __swig_destroy__: Any = ...
    cast: Any = ...
    def New(*args: Any, **kargs: Any): ...
    New: Any = ...

itkZeroCrossingImageFilterISS3ISS3___New_orig__: Any
itkZeroCrossingImageFilterISS3ISS3_cast: Any

def zero_crossing_image_filter(*args: Any, **kwargs: Any): ...
def zero_crossing_image_filter_init_docstring() -> None: ...
