import collections.abc
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class SwigPyIterator:
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    __swig_destroy__: Any = ...
    value: Any = ...
    incr: Any = ...
    decr: Any = ...
    distance: Any = ...
    equal: Any = ...
    copy: Any = ...
    next: Any = ...
    __next__: Any = ...
    previous: Any = ...
    advance: Any = ...
    __eq__: Any = ...
    __ne__: Any = ...
    __iadd__: Any = ...
    __isub__: Any = ...
    __add__: Any = ...
    __sub__: Any = ...
    def __iter__(self) -> Any: ...

class ios_base:
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    erase_event: Any = ...
    imbue_event: Any = ...
    copyfmt_event: Any = ...
    register_callback: Any = ...
    flags: Any = ...
    setf: Any = ...
    unsetf: Any = ...
    precision: Any = ...
    width: Any = ...
    sync_with_stdio: Any = ...
    imbue: Any = ...
    getloc: Any = ...
    xalloc: Any = ...
    iword: Any = ...
    pword: Any = ...
    __swig_destroy__: Any = ...

cvar: Any
ios_base_sync_with_stdio: Any
ios_base_xalloc: Any

class ios(ios_base):
    thisown: Any = ...
    rdstate: Any = ...
    clear: Any = ...
    setstate: Any = ...
    good: Any = ...
    eof: Any = ...
    fail: Any = ...
    bad: Any = ...
    exceptions: Any = ...
    def __init__(self, __sb: 'std::basic_streambuf< char,std::char_traits< char > > *') -> None: ...
    __swig_destroy__: Any = ...
    tie: Any = ...
    rdbuf: Any = ...
    copyfmt: Any = ...
    fill: Any = ...
    imbue: Any = ...
    narrow: Any = ...
    widen: Any = ...

class ostream(ios):
    thisown: Any = ...
    def __init__(self, __sb: 'std::basic_streambuf< char,std::char_traits< char > > *') -> None: ...
    __swig_destroy__: Any = ...
    __lshift__: Any = ...
    put: Any = ...
    write: Any = ...
    flush: Any = ...
    tellp: Any = ...
    seekp: Any = ...

cin: Any
cout: Any
cerr: Any
clog: Any

class istream(ios):
    thisown: Any = ...
    def __init__(self, __sb: 'std::basic_streambuf< char,std::char_traits< char > > *') -> None: ...
    __swig_destroy__: Any = ...
    __rshift__: Any = ...
    gcount: Any = ...
    get: Any = ...
    getline: Any = ...
    ignore: Any = ...
    peek: Any = ...
    read: Any = ...
    readsome: Any = ...
    putback: Any = ...
    unget: Any = ...
    sync: Any = ...
    tellg: Any = ...
    seekg: Any = ...

class iostream(istream, ostream):
    thisown: Any = ...
    def __init__(self, __sb: 'std::basic_streambuf< char,std::char_traits< char > > *') -> None: ...
    __swig_destroy__: Any = ...

endl_cb_ptr: Any
endl: Any
ends_cb_ptr: Any
ends: Any
flush_cb_ptr: Any
flush: Any
str = str

class mapULD(collections.abc.MutableMapping):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    def __iter__(self) -> Any: ...
    def iterkeys(self): ...
    def itervalues(self): ...
    def iteritems(self): ...
    __getitem__: Any = ...
    __delitem__: Any = ...
    has_key: Any = ...
    keys: Any = ...
    values: Any = ...
    items: Any = ...
    __contains__: Any = ...
    key_iterator: Any = ...
    value_iterator: Any = ...
    __setitem__: Any = ...
    asdict: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    count: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    __swig_destroy__: Any = ...

class mapBB(collections.abc.MutableMapping):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    def __iter__(self) -> Any: ...
    def iterkeys(self): ...
    def itervalues(self): ...
    def iteritems(self): ...
    __getitem__: Any = ...
    __delitem__: Any = ...
    has_key: Any = ...
    keys: Any = ...
    values: Any = ...
    items: Any = ...
    __contains__: Any = ...
    key_iterator: Any = ...
    value_iterator: Any = ...
    __setitem__: Any = ...
    asdict: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    count: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    __swig_destroy__: Any = ...

class mapII(collections.abc.MutableMapping):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    def __iter__(self) -> Any: ...
    def iterkeys(self): ...
    def itervalues(self): ...
    def iteritems(self): ...
    __getitem__: Any = ...
    __delitem__: Any = ...
    has_key: Any = ...
    keys: Any = ...
    values: Any = ...
    items: Any = ...
    __contains__: Any = ...
    key_iterator: Any = ...
    value_iterator: Any = ...
    __setitem__: Any = ...
    asdict: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    count: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    __swig_destroy__: Any = ...

class mapUCUC(collections.abc.MutableMapping):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    def __iter__(self) -> Any: ...
    def iterkeys(self): ...
    def itervalues(self): ...
    def iteritems(self): ...
    __getitem__: Any = ...
    __delitem__: Any = ...
    has_key: Any = ...
    keys: Any = ...
    values: Any = ...
    items: Any = ...
    __contains__: Any = ...
    key_iterator: Any = ...
    value_iterator: Any = ...
    __setitem__: Any = ...
    asdict: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    count: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    __swig_destroy__: Any = ...

class mapUIUI(collections.abc.MutableMapping):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    def __iter__(self) -> Any: ...
    def iterkeys(self): ...
    def itervalues(self): ...
    def iteritems(self): ...
    __getitem__: Any = ...
    __delitem__: Any = ...
    has_key: Any = ...
    keys: Any = ...
    values: Any = ...
    items: Any = ...
    __contains__: Any = ...
    key_iterator: Any = ...
    value_iterator: Any = ...
    __setitem__: Any = ...
    asdict: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    count: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    __swig_destroy__: Any = ...

class mapUSUS(collections.abc.MutableMapping):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    def __iter__(self) -> Any: ...
    def iterkeys(self): ...
    def itervalues(self): ...
    def iteritems(self): ...
    __getitem__: Any = ...
    __delitem__: Any = ...
    has_key: Any = ...
    keys: Any = ...
    values: Any = ...
    items: Any = ...
    __contains__: Any = ...
    key_iterator: Any = ...
    value_iterator: Any = ...
    __setitem__: Any = ...
    asdict: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    count: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    __swig_destroy__: Any = ...

class mapULUL(collections.abc.MutableMapping):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    def __iter__(self) -> Any: ...
    def iterkeys(self): ...
    def itervalues(self): ...
    def iteritems(self): ...
    __getitem__: Any = ...
    __delitem__: Any = ...
    has_key: Any = ...
    keys: Any = ...
    values: Any = ...
    items: Any = ...
    __contains__: Any = ...
    key_iterator: Any = ...
    value_iterator: Any = ...
    __setitem__: Any = ...
    asdict: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    count: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    __swig_destroy__: Any = ...

class mapSCSC(collections.abc.MutableMapping):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    def __iter__(self) -> Any: ...
    def iterkeys(self): ...
    def itervalues(self): ...
    def iteritems(self): ...
    __getitem__: Any = ...
    __delitem__: Any = ...
    has_key: Any = ...
    keys: Any = ...
    values: Any = ...
    items: Any = ...
    __contains__: Any = ...
    key_iterator: Any = ...
    value_iterator: Any = ...
    __setitem__: Any = ...
    asdict: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    count: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    __swig_destroy__: Any = ...

class mapSSSS(collections.abc.MutableMapping):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    def __iter__(self) -> Any: ...
    def iterkeys(self): ...
    def itervalues(self): ...
    def iteritems(self): ...
    __getitem__: Any = ...
    __delitem__: Any = ...
    has_key: Any = ...
    keys: Any = ...
    values: Any = ...
    items: Any = ...
    __contains__: Any = ...
    key_iterator: Any = ...
    value_iterator: Any = ...
    __setitem__: Any = ...
    asdict: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    count: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    __swig_destroy__: Any = ...

class mapSLSL(collections.abc.MutableMapping):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    def __iter__(self) -> Any: ...
    def iterkeys(self): ...
    def itervalues(self): ...
    def iteritems(self): ...
    __getitem__: Any = ...
    __delitem__: Any = ...
    has_key: Any = ...
    keys: Any = ...
    values: Any = ...
    items: Any = ...
    __contains__: Any = ...
    key_iterator: Any = ...
    value_iterator: Any = ...
    __setitem__: Any = ...
    asdict: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    count: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    __swig_destroy__: Any = ...

class mapFF(collections.abc.MutableMapping):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    def __iter__(self) -> Any: ...
    def iterkeys(self): ...
    def itervalues(self): ...
    def iteritems(self): ...
    __getitem__: Any = ...
    __delitem__: Any = ...
    has_key: Any = ...
    keys: Any = ...
    values: Any = ...
    items: Any = ...
    __contains__: Any = ...
    key_iterator: Any = ...
    value_iterator: Any = ...
    __setitem__: Any = ...
    asdict: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    count: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    __swig_destroy__: Any = ...

class mapDD(collections.abc.MutableMapping):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    def __iter__(self) -> Any: ...
    def iterkeys(self): ...
    def itervalues(self): ...
    def iteritems(self): ...
    __getitem__: Any = ...
    __delitem__: Any = ...
    has_key: Any = ...
    keys: Any = ...
    values: Any = ...
    items: Any = ...
    __contains__: Any = ...
    key_iterator: Any = ...
    value_iterator: Any = ...
    __setitem__: Any = ...
    asdict: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    count: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    __swig_destroy__: Any = ...

class pairI:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    first: Any = ...
    second: Any = ...
    def __len__(self): ...
    def __getitem__(self, index: Any): ...
    def __setitem__(self, index: Any, val: Any) -> None: ...
    __swig_destroy__: Any = ...

class pairUI:
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    first: Any = ...
    second: Any = ...
    def __len__(self): ...
    def __getitem__(self, index: Any): ...
    def __setitem__(self, index: Any, val: Any) -> None: ...
    __swig_destroy__: Any = ...

class vectorB:
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorvectorB(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorI(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorvectorI(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorUC(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorvectorUC(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorUS(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorvectorUS(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorUI(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorvectorUI(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorUL(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorvectorUL(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorSC(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorvectorSC(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorSS(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorvectorSS(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorSL(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorvectorSL(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorF(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorvectorF(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorD(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorvectorD(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class vectorstring(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class listB(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

class listI(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

class listUC(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

class listUS(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

class listUI(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

class listUL(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

class listSC(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

class listSS(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

class listSL(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

class listF(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

class listD(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

class liststring(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    pop_front: Any = ...
    push_front: Any = ...
    reverse: Any = ...
    __swig_destroy__: Any = ...

class setB(collections.abc.MutableSet):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    append: Any = ...
    __contains__: Any = ...
    __getitem__: Any = ...
    add: Any = ...
    discard: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    clear: Any = ...
    swap: Any = ...
    count: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    equal_range: Any = ...
    insert: Any = ...
    __swig_destroy__: Any = ...

class setI(collections.abc.MutableSet):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    append: Any = ...
    __contains__: Any = ...
    __getitem__: Any = ...
    add: Any = ...
    discard: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    clear: Any = ...
    swap: Any = ...
    count: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    equal_range: Any = ...
    insert: Any = ...
    __swig_destroy__: Any = ...

class setUC(collections.abc.MutableSet):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    append: Any = ...
    __contains__: Any = ...
    __getitem__: Any = ...
    add: Any = ...
    discard: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    clear: Any = ...
    swap: Any = ...
    count: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    equal_range: Any = ...
    insert: Any = ...
    __swig_destroy__: Any = ...

class setUS(collections.abc.MutableSet):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    append: Any = ...
    __contains__: Any = ...
    __getitem__: Any = ...
    add: Any = ...
    discard: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    clear: Any = ...
    swap: Any = ...
    count: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    equal_range: Any = ...
    insert: Any = ...
    __swig_destroy__: Any = ...

class setUI(collections.abc.MutableSet):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    append: Any = ...
    __contains__: Any = ...
    __getitem__: Any = ...
    add: Any = ...
    discard: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    clear: Any = ...
    swap: Any = ...
    count: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    equal_range: Any = ...
    insert: Any = ...
    __swig_destroy__: Any = ...

class setUL(collections.abc.MutableSet):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    append: Any = ...
    __contains__: Any = ...
    __getitem__: Any = ...
    add: Any = ...
    discard: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    clear: Any = ...
    swap: Any = ...
    count: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    equal_range: Any = ...
    insert: Any = ...
    __swig_destroy__: Any = ...

class setULL(collections.abc.MutableSet):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    append: Any = ...
    __contains__: Any = ...
    __getitem__: Any = ...
    add: Any = ...
    discard: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    clear: Any = ...
    swap: Any = ...
    count: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    equal_range: Any = ...
    insert: Any = ...
    __swig_destroy__: Any = ...

class setSC(collections.abc.MutableSet):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    append: Any = ...
    __contains__: Any = ...
    __getitem__: Any = ...
    add: Any = ...
    discard: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    clear: Any = ...
    swap: Any = ...
    count: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    equal_range: Any = ...
    insert: Any = ...
    __swig_destroy__: Any = ...

class setSS(collections.abc.MutableSet):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    append: Any = ...
    __contains__: Any = ...
    __getitem__: Any = ...
    add: Any = ...
    discard: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    clear: Any = ...
    swap: Any = ...
    count: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    equal_range: Any = ...
    insert: Any = ...
    __swig_destroy__: Any = ...

class setSL(collections.abc.MutableSet):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    append: Any = ...
    __contains__: Any = ...
    __getitem__: Any = ...
    add: Any = ...
    discard: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    clear: Any = ...
    swap: Any = ...
    count: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    equal_range: Any = ...
    insert: Any = ...
    __swig_destroy__: Any = ...

class setSLL(collections.abc.MutableSet):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    append: Any = ...
    __contains__: Any = ...
    __getitem__: Any = ...
    add: Any = ...
    discard: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    clear: Any = ...
    swap: Any = ...
    count: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    equal_range: Any = ...
    insert: Any = ...
    __swig_destroy__: Any = ...

class setF(collections.abc.MutableSet):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    append: Any = ...
    __contains__: Any = ...
    __getitem__: Any = ...
    add: Any = ...
    discard: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    clear: Any = ...
    swap: Any = ...
    count: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    equal_range: Any = ...
    insert: Any = ...
    __swig_destroy__: Any = ...

class setD(collections.abc.MutableSet):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    append: Any = ...
    __contains__: Any = ...
    __getitem__: Any = ...
    add: Any = ...
    discard: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    clear: Any = ...
    swap: Any = ...
    count: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    equal_range: Any = ...
    insert: Any = ...
    __swig_destroy__: Any = ...

class vectorsetUL(collections.abc.MutableSequence):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    __getslice__: Any = ...
    __setslice__: Any = ...
    __delslice__: Any = ...
    __delitem__: Any = ...
    __getitem__: Any = ...
    __setitem__: Any = ...
    pop: Any = ...
    append: Any = ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    pop_back: Any = ...
    erase: Any = ...
    def __init__(self, *args: Any) -> None: ...
    push_back: Any = ...
    front: Any = ...
    back: Any = ...
    assign: Any = ...
    resize: Any = ...
    insert: Any = ...
    reserve: Any = ...
    capacity: Any = ...
    __swig_destroy__: Any = ...

class mapsetUL(collections.abc.MutableMapping):
    thisown: Any = ...
    iterator: Any = ...
    def __iter__(self) -> Any: ...
    __nonzero__: Any = ...
    __bool__: Any = ...
    __len__: Any = ...
    def __iter__(self) -> Any: ...
    def iterkeys(self): ...
    def itervalues(self): ...
    def iteritems(self): ...
    __getitem__: Any = ...
    __delitem__: Any = ...
    has_key: Any = ...
    keys: Any = ...
    values: Any = ...
    items: Any = ...
    __contains__: Any = ...
    key_iterator: Any = ...
    value_iterator: Any = ...
    __setitem__: Any = ...
    asdict: Any = ...
    def __init__(self, *args: Any) -> None: ...
    empty: Any = ...
    size: Any = ...
    swap: Any = ...
    begin: Any = ...
    end: Any = ...
    rbegin: Any = ...
    rend: Any = ...
    clear: Any = ...
    get_allocator: Any = ...
    count: Any = ...
    erase: Any = ...
    find: Any = ...
    lower_bound: Any = ...
    upper_bound: Any = ...
    __swig_destroy__: Any = ...
