from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class stdcomplexD:
    thisown: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    real: Any = ...
    imag: Any = ...
    __iadd__: Any = ...
    __isub__: Any = ...
    __imul__: Any = ...
    def __itruediv__(self, *args: Any): ...
    __idiv__: Any = ...
    def __complex__(self): ...

class stdcomplexF:
    thisown: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
    real: Any = ...
    imag: Any = ...
    __iadd__: Any = ...
    __isub__: Any = ...
    __imul__: Any = ...
    def __itruediv__(self, *args: Any): ...
    __idiv__: Any = ...
    def __complex__(self): ...
