import itk.pyBasePython
from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class vnl_vector_refCF(itk.vnl_vectorPython.vnl_vectorCF):
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    non_const: Any = ...
    as_vector: Any = ...

class vnl_vector_refD(itk.vnl_vectorPython.vnl_vectorD):
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    non_const: Any = ...
    as_vector: Any = ...

class vnl_vector_refF(itk.vnl_vectorPython.vnl_vectorF):
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    non_const: Any = ...
    as_vector: Any = ...

class vnl_vector_refLD(itk.vnl_vectorPython.vnl_vectorLD):
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    non_const: Any = ...
    as_vector: Any = ...

class vnl_vector_refSC(itk.vnl_vectorPython.vnl_vectorSC):
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    non_const: Any = ...
    as_vector: Any = ...

class vnl_vector_refSI(itk.vnl_vectorPython.vnl_vectorSI):
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    non_const: Any = ...
    as_vector: Any = ...

class vnl_vector_refSL(itk.vnl_vectorPython.vnl_vectorSL):
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    non_const: Any = ...
    as_vector: Any = ...

class vnl_vector_refSLL(itk.vnl_vectorPython.vnl_vectorSLL):
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    non_const: Any = ...
    as_vector: Any = ...

class vnl_vector_refSS(itk.vnl_vectorPython.vnl_vectorSS):
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    non_const: Any = ...
    as_vector: Any = ...

class vnl_vector_refUC(itk.vnl_vectorPython.vnl_vectorUC):
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    non_const: Any = ...
    as_vector: Any = ...

class vnl_vector_refUI(itk.vnl_vectorPython.vnl_vectorUI):
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    non_const: Any = ...
    as_vector: Any = ...

class vnl_vector_refUL(itk.vnl_vectorPython.vnl_vectorUL):
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    non_const: Any = ...
    as_vector: Any = ...

class vnl_vector_refULL(itk.vnl_vectorPython.vnl_vectorULL):
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    non_const: Any = ...
    as_vector: Any = ...

class vnl_vector_refUS(itk.vnl_vectorPython.vnl_vectorUS):
    thisown: Any = ...
    def __init__(self, *args: Any) -> None: ...
    __swig_destroy__: Any = ...
    non_const: Any = ...
    as_vector: Any = ...
