from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class vnl_least_squares_function:
    thisown: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    UseGradient_no_gradient: Any = ...
    UseGradient_use_gradient: Any = ...
    __swig_destroy__: Any = ...
    throw_failure: Any = ...
    clear_failure: Any = ...
    f: Any = ...
    gradf: Any = ...
    fdgradf: Any = ...
    ffdgradf: Any = ...
    trace: Any = ...
    rms: Any = ...
    get_number_of_unknowns: Any = ...
    get_number_of_residuals: Any = ...
    has_gradient: Any = ...
