from typing import Any

class _SwigNonDynamicMeta(type):
    __setattr__: Any = ...

class vnl_fortran_copyCF:
    thisown: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...

class vnl_fortran_copyD:
    thisown: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...

class vnl_fortran_copyF:
    thisown: Any = ...
    __swig_destroy__: Any = ...
    def __init__(self, *args: Any) -> None: ...
